### ISSUE TITLE
jira-client jar missing

### ISSUE THREAD

**Issue by tongqqiu** [capitalone/Hygieia#10]
When building the lira collector: 
com.capitalone.versionone:jira-client:jar:01.01.00.01-SNAPSHOT is missing, no dependency information available

**Comment by amp5208** [comment]
Thank you for reaching out regarding the missing dependency.  You were correct - that dependency is inaccessible.  I have fixed this since pull request #11 .  Feel free to update your code.

Thank you, and let us know if you have any other questions or issues.

**Comment by amp5208** [comment]
@amitmawkin :  You may close this issue.
