### ISSUE TITLE
Issue with saving new Code Repo configuration when collector has not been run

### ISSUE THREAD

**Issue by jmcshane** [capitalone/Hygieia#1003]
As an individual who is configuring a new Hygieia project, when I try to save a new Code Repo instance for a collector type that has not been registered, I would like to get a message telling me that this CodeRepo type has not been enabled so that I am aware that this precondition step still need to be completed.

Current Behavior: When the save button is clicked, two different things occur:

1. When no SCM collectors have been configured, I do not see any Console errors in the javascript or in the network requests.  Nothing occurs on the screen.

2. When one SCM collector has been configured and I am attempting to create a Code Repo instance for another type that has not been configured, a console error appears in the Javascript:
```
TypeError: Cannot read property 'id' of undefined
    at createCollectorItem (config.js:163)
    at RepoConfigController.submitForm [as submit] (config.js:111)
    at $parseFunctionCall (bower.js:13881)
    at callback (bower.js:23107)
    at Scope.$eval (bower.js:15977)
    at Scope.$apply (bower.js:16076)
    at HTMLFormElement.<anonymous> (bower.js:23112)
    at HTMLFormElement.eventHandler (bower.js:4454)
```
No error appears on the browser window.

**Comment by satishc1** [comment]
@jmcshane @mrpudn 
Will be tracked as part of https://github.com/capitalone/Hygieia/issues/388

**Comment by jmcshane** [comment]
Thanks @satishc1.  I'm working on contributing in another area of the project for now, but I will track that issue to provide any feedback necessary.
