### ISSUE TITLE
Deployment API endpoint does not create deployments that display properly

### ISSUE THREAD

**Issue by jmcshane** [capitalone/Hygieia#1004]
The deployment POST endpoint does not align with the way that the data is displayed in a number of ways:

1. The jobUrl property is completely ignored (search for references to  DeployDataCreateRequest::getJobUrl() in IDE).  There should be an option to access the job URL component by component.
2. The `appName`/`instanceUrl` property pair is being defined as distinct in the backend [here](https://github.com/capitalone/Hygieia/blob/master/api/src/main/java/com/capitalone/dashboard/service/DeployServiceImpl.java#L242) because the query looks to match the options passed in.  This means that two collectors can be created with the same name, which then appears as the same name in the Deploy widget dropdown.
3. The environmentUrl doesn't get set in the [createEnvComponent](https://github.com/capitalone/Hygieia/blob/master/api/src/main/java/com/capitalone/dashboard/service/DeployServiceImpl.java#L248) method.  This means that jobs submitted by the POST endpoint do not have a functional "View in Jenkins" link, as this is captured by the `environment.url` property [here](https://github.com/capitalone/Hygieia/blob/master/UI/src/components/widgets/deploy/detail.html#L25)

My suggested solution:
1. `jobUrl` property gets set on the environment_component collection object, then if this value is set it is used by the [deploy detail modal](https://github.com/capitalone/Hygieia/blob/master/UI/src/components/widgets/deploy/detail.html).  It will need to be at the component level, as the `jobUrl` property is specifying a deploy URL for a component.
2. Make `applicationName` distinct in the CollectorItem repo by removing `option.put("instanceUrl", request.getInstanceUrl());` from [DeployServiceImpl.java](https://github.com/capitalone/Hygieia/blob/master/api/src/main/java/com/capitalone/dashboard/service/DeployServiceImpl.java).  I realize this would be a breaking change for those with duplicate records here already by `applicationName` and `instanceUrl`.  I don't know what the project stance on this issue would be.
3. The `environmentUrl` should be set by the `instanceUrl` that is available in the API object.

I will be creating a PR for the related issues above.  I wanted the issue created to begin a discussion on these solutions.

**Comment by jmcshane** [comment]
Issue 2 becomes especially clear in the code when you look at the `hashCode` and `equals` methods for [`Environment.java`](https://github.com/capitalone/Hygieia/blob/master/api/src/main/java/com/capitalone/dashboard/model/deploy/Environment.java).  The URL is not taken into account when comparing these environments for equality.

**Comment by MarkRx** [comment]
> Make applicationName distinct in the CollectorItem repo by removing option.put("instanceUrl", request.getInstanceUrl()); from DeployServiceImpl.java. I realize this would be a breaking change for those with duplicate records here already by applicationName and instanceUrl. I don't know what the project stance on this issue would be.

This will not work in all cases. It is perfectly valid to have the same application name on different instances and these would in turn be different logical items.

**Comment by jmcshane** [comment]
@MarkRx Then the `Environment.java` file needs to change as well as the view for choosing Deployment collectors, as right now the instanceUrl is not included in the display for choosing the collector.  The environment being tested for equality based only on the `appName` property means that I cannot create a map keyed on the `Environment` when there are two records with the same app name.

If you have another solution that allows these multiple instanceUrls in a way that makes it easy to work with, I'm definitely interested in working through this.  We could set a time to discuss on the gitter chat for this project if you are interested.

**Comment by tabladrum** [comment]
Let me review this tonight.

**Comment by MarkRx** [comment]
> If you have another solution that allows these multiple instanceUrls in a way that makes it easy to work with, I'm definitely interested in working through this. We could set a time to discuss on the gitter chat for this project if you are interested.

What are you trying to accomplish? If you have the same application spread vertically accross different instances look #891.

In the collector model there is a single collector that defines N number of URLs and niceNames. Each collectorItem refers to the collector and has applicationName, instanceUrl (in options) and 'niceName' set. If the collectorItem has 'niceName' set the UI will differentiate entries using that.
