### ISSUE TITLE
Add a Rundeck Deploy Collector

### ISSUE THREAD

**Issue by jmcshane** [capitalone/Hygieia#1008]
I have been working on a Rundeck collector which creates EnvironmentComponent deploy records.  I have a couple questions about the implementation:

1. I could use the Rundeck post-completion webhook to send records to a collector or build a collector from the API to run on a cron schedule, as the Github collector does. Is there a preferred approach?  Could I build the Rundeck post-completion webhook feature into the api itself, while also building a separate collector that runs on a cron schedule?
2. When building separate collectors, is it preferred to use the api endpoints to create mongo objects or do the collectors generally have their own `Repository` bean with a connection to the mongo db directly?

I created two PRs that I will be depending on for the implementation #1007 and #1005.  If these are not yet resolved, I would ask that we begin discussion there and then talk about the implementation here.

Adding #785 for reference.

**Comment by tabladrum** [comment]
Great! @jmcshane Thanks. To answer your question, collectors have their own repository beans. 
We are keeping both webhook and collector approaches - since different users will have different requirements etc. I am reviewing the PRs.

**Comment by satishc1** [comment]
Closed.
