### ISSUE TITLE
Coverage is showing line coverage

### ISSUE THREAD

**Issue by bodiam** [capitalone/Hygieia#101]
The documentation says the following configuration:

````
sonar.metrics=ncloc,coverage,violations,critical_violations,major_violations,blocker_violations
````

However, this results in the following:

<img width="836" alt="screen shot 2015-08-28 at 13 17 05" src="https://cloud.githubusercontent.com/assets/46468/9545408/076e3dfc-4d8a-11e5-8789-375b5c98fadc.png">

(So, 0% coverage data).

This is because the sonar metrics displayed in the UI is not the coverage, but the line coverage (line_coverage). It's confusing.

Then, updating the configuration doesn't do anything. I add the metric line_coverage, and no line_coverage is added. The non-obvious fix for that is to run the following Mongo query:

`db.code_quality.drop()`

What are you ideas on that?

**Comment by krismy93** [comment]
I am having this same issue. I am trying to get the % of coverage to show up.

**Comment by krismy93** [comment]
I was able to get the line coverage to show by:
1. Dropping the "code_quality" collection
2. Re-editing the application.properties file:
`sonar.metrics=ncloc,line_coverage,violations,critical_violations,major_violations,blocker_violations`
3. Re-starting the jar

![screen shot 2015-08-31 at 10 34 36 am](https://cloud.githubusercontent.com/assets/5998068/9585505/3b8ae394-4fcc-11e5-8814-0e9101597ec7.png)

**Comment by bodiam** [comment]
Hi @krismy93 , sorry to hear you had the same issue. I'll try to get into it this week and make a fix + pull request for this.

**Comment by krismy93** [comment]
Thanks @bodiam 
To get all the widgets to display the relevant information the final application.properties had:
`sonar.metrics=ncloc,line_coverage,violations,critical_violations,major_violations,blocker_violations,sqale_index,test_success_density,test_failures,test_errors,tests`

This should probably be updated within the sample file.

**Comment by tabladrum** [comment]
@krismy93 Thanks for the suggestion. I will take the PR if you submit one. Or I can do the update. Let me know.

**Comment by krismy93** [comment]
@tabladrum just submitted one

**Comment by jdamick** [comment]
@krismy93 which pull was this in? (was it merged yet?)

**Comment by krismy93** [comment]
@jdamick it was pull request #107. It has already been merged

**Comment by jdamick** [comment]
closing
