### ISSUE TITLE
Gitlab docker:build broke

### ISSUE THREAD

**Issue by MarkRx** [capitalone/Hygieia#1012]
> [INFO] com.capitalone.dashboard:github-scm-collector ...... SUCCESS [ 24.772 s]
> [INFO] com.capitalone.dashboard:subversion-collector ...... SUCCESS [ 18.490 s]
> [INFO] com.capitalone.dashboard:gitlab-git-collector ...... FAILURE [ 24.634 s]
> [INFO] com.capitalone.dashboard:UI ........................ SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 09:13 min
> [INFO] Finished at: 2016-12-05T16:19:34+00:00
> [INFO] Final Memory: 101M/478M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.10:build (default-cli) on project gitlab-git-collector: Exception caught: lstat application.properties: no such file or directory -> [Help 1]

@rob-miller-777 @mrpudn

**Comment by rob-miller-777** [comment]
Yeah, that is one of the things we recently ran into when trying to do a docker build.  Going to open a pull request with these changes in the next day or two which should resolve this issue.  https://github.com/capitalone/Hygieia/compare/master...StateFarmIns:gitlabCollectorDockerConfig

**Comment by mrpudn** [comment]
Yup, I reopened #957 - we can track it there
