### ISSUE TITLE
Is BrowserSync ghostMode necessary?

### ISSUE THREAD

**Issue by pxk5958** [capitalone/Hygieia#1016]
When we serve the UI with gulp serve (without nginx), the interaction synchronization through [ghostMode](https://www.browsersync.io/docs/options#option-ghostMode) option causes problems. It is not working as intended and browsers end up in different pages sometimes and cause problems during testing. For example, we consistently end up in a scenario where one browser goes into a dashboard page whereas another browser remains in the home page (site.html), and eventually interactions trigger the deleteDashboard() javascript function on the latter browser. We consistently get a dashboard deleted when the Monitor widget's configure wheel button is clicked in the first browser. That is not the only case where dashboards get deleted though.

So the question is, was ghostMode intended to be used? If not, we could turn it off in gulpfile.js when initializing browser-sync, since it's causing the dashboards to be deleted during testing, which is rather annoying.

Other issues reporting similar problems: [#871](https://github.com/capitalone/Hygieia/issues/871), [#627](https://github.com/capitalone/Hygieia/issues/627)

@mrpudn @amitmawkin @tabladrum

**Comment by mrpudn** [comment]
`ghostMode` can be useful if you're demonstrating something with a teammate or something, but I agree that this functionality could be provided via a separate command (i.e. `npm run develop` or `gulp develop`) and turned off by default.

I don't think this would be terribly hard to implement, and changing the default behavior of `gulp serve` should be transparent to users.

**Comment by xpdable** [comment]
@mrpudn currently how to start Hygieia instance from gulp without ghost mode ?

**Comment by mrpudn** [comment]
I just created a PR to address this issue.

If it gets merged, ghost mode will be disabled, by default. To enable it, you will be able to run `gulp serve:ghost-mode`
