### ISSUE TITLE
API connectivity not working on UI

### ISSUE THREAD

**Issue by vetrivelan25** [capitalone/Hygieia#1019]
Hi,
I have pulled the latest code today then i tried mvn clean install package build was successful.Tried to build the api that also successful but API layer is not connecting with UI layer i already configure API and UI layer along with below properties file ,
```properties
dashboard.properties:
dbname=dashboarddb
dbusername=dashboarduser
dbpassword=dbpassword
dbhost=127.0.0.1
dbport=27017
server.contextPath=/api
server.port=8080
```
Command:
```
sudo java -jar api.jar \
  --spring.config.name=api \
  --spring.config.location=/home/ubuntu/Hygieia/api/dashboard.properties
```
![api](https://cloud.githubusercontent.com/assets/23630163/20962549/bfa4d55a-bc8f-11e6-9404-aae286dacade.png)
![ui](https://cloud.githubusercontent.com/assets/23630163/20962554/c76227ac-bc8f-11e6-8c28-65dffe901ab4.png)

**Comment by tabladrum** [comment]
The only thing I can think of is that the spring.config.location may be incorrect. Can you please verify.

**Comment by amitmawkin** [comment]
what's the output of http://localhost:8080/api/ping

**Comment by pxk5958** [comment]
Please post the UI log too

**Comment by nireeshT** [comment]
@vetrivelan25 - based on your API log it looks like your API module is working. Also were you able to hit http://localhost:8080/api/ping and get a response "true". If Yes then your API module is working. 
How are you launching your UI, is it through gulp? Let us know your config details on how you are connecting to API from the UI. You can find this in your gulp file or in your httpd conf.

**Comment by nireeshT** [comment]
Closing the issue due to no response from @vetrivelan25 . Please reopen the case if the issue still persists. 

_*We are closing issues if there is no response from the user for more than 3 business days with the assumption as issue resolved. Please reopen the issue if otherwise._

**Comment by anuragmishracrest** [comment]
I cloned this and performed mvn clean install package
1. from target i did java -jar api.jar --spring.config.name=api --spring.config.location=application.properties.
2. It got started but on localhost:8080/ping instead of localhost:8080/api/ping.

UI I have started using gulp server with no code change
but api status is not connected

please tell me where I am wrong

**Comment by petro-osypenko-lebara** [comment]
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.


Same thing for me

http://localhost:8080/api/ping 


There was an unexpected error (type=Internal Server Error, status=500).
Unresolved compilation problem: Type mismatch: cannot convert from Collection<capture#2-of ? extends GrantedAuthority> to Collection<GrantedAuthority>

**Comment by crackthisequation** [comment]
I am getting the same whitelabel page when I run http://localhost:8080/api/ping 
Please help.

**Comment by GPreksha** [comment]
I am getting Api connectivity error, Login button i grey out

**Comment by aishwaryamv123** [comment]
I am facing similar issue, api log says connected to mongodb on port 27017, but localhost:8090/api/ping doesn't return true and give me a whitelabel error message page.
UI says red on api connectivity. It was working well earlier suddenly it isnt working, Can someone please help me with this/if any faced same ??

**Comment by Rajeswa** [comment]
I am facing issue in API - UI connectivity. API instance is running and am getting the response (response as true) when I hit http://localhost:8081/api/ping. I have deployed UI via gulp serve command and in the UI page its showing as no API connectivity. When I try to hit http://localhost:8081/api/dashboard, am getting empty json. From the API logs, I saw it has established connection to mongodb successfully. Can you help me to sort out this?

I have built the entire project successfully that I have cloned from GitHub. Mongodb,npm,bower installation -> successful. No error message in api log.

in UI page, GET method http://localhost:8081/api/authenticationProviders & http://localhost:8081/api/appinfo returns 404 page not found response

**Comment by blasteravismaster** [comment]
Im facing the same issue. Is this issue reolved?
