### ISSUE TITLE
Rules compliance

### ISSUE THREAD

**Issue by bodiam** [capitalone/Hygieia#102]
The current quality UI widget has a 'rules compliance' metric. However, since version 4.0, this metric has been removed from Sonar: https://jira.sonarsource.com/browse/SONAR-4755

What do we want to do with this? Remove it from the UI also?

**Comment by tabladrum** [comment]
May be it should be replaced with this: http://docs.sonarqube.org/display/PLUG/Issues+Density+Plugin

**Comment by mickfeech** [comment]
It looks like the issues density plugin has also been deprecated.

**Comment by Sbrenthughes** [comment]
Please reopen if this is still a valid issue.
