### ISSUE TITLE
90 days pipeline information

### ISSUE THREAD

**Issue by BoomaBaskaran** [capitalone/Hygieia#1023]
Hi,

We don't find any good detailed documents for Product Dashboard 90 days Health trend. Please post here if there is any. 

Thanks,
Booma Baskaran.

**Comment by mrpudn** [comment]
From #1024:

> In 90 days pipeline health trend, code coverage tab (2nd tab)says its code coverage but the label in the vertical line shows its the # of code issues per day. What does it mean?

**Comment by BoomaBaskaran** [comment]
@mrpudn - Any update on this.

**Comment by mrpudn** [comment]
I think I'll defer to @tabladrum on this one :)

**Comment by tabladrum** [comment]
Ah.... good catch - haven't noticed it. Should be "code coverage" on the Y axis. Is a quick fix on this line:

https://github.com/capitalone/Hygieia/blob/master/UI/src/components/widgets/product/quality-details/qualityDetails.js
``
ctrl.codeCoverageChartOptions = getDefaultChartOptions('# of code issues per day');
``

**Comment by BoomaBaskaran** [comment]
@tabladrum.. Any detailed documents are there for product dashboard especially for 90 days pipeline chart?

**Comment by nireeshT** [comment]
@BoomaBaskaran refer https://github.com/capitalone/Hygieia/issues/1512 . Reopen if you need more information
