### ISSUE TITLE
Github Code Repo Bug

### ISSUE THREAD

**Issue by krismy93** [capitalone/Hygieia#103]
Not showing the correct number of commits/contributors from Github.

As explained by tabladrum:
When the collector runs continuously, the numbers will be correct over 14 days. Each time (based on the cron setting) the collector runs, it fetches commits from lastupdated - 10 mins (randomly set) and discards the duplications while saving it.

Enhancement needed: For the first run, go back 14 days.

**Comment by tabladrum** [comment]
Working on it. Thanks for reporting the bug.

**Comment by tabladrum** [comment]
Update: Github commit api by default returns 30 commits per request and sets the pagination information in the response header. It also limits the number of commit api requests to 60 per hour for unauthenticated user. For "busy" repo's on github.com, I see that we can possibly reach the limit easily.

**Comment by tabladrum** [comment]
@krismy93 Can you test github collector updated code from here: https://github.com/tabladrum/Hygieia
It now handles paging to handle default 30 per page commits.

Need to put in some comments and logs if it looks ok.
Caution: The api calls still are unauthenticated - and that will probably cause HTTP 403 once number of calls reaches 60 in an hour.

**Comment by tabladrum** [comment]
@krismy93 Can we close this?

**Comment by krismy93** [comment]
Yes. Thank you!
