### ISSUE TITLE
No teams were found in Deploy widget of Hygieia db

### ISSUE THREAD

**Issue by supremex1** [capitalone/Hygieia#1034]
Hi Team,
I am using the Hygieia Jenkins plugin to publish deployment details on Hygieia db but it is not clearly documented anywhere as how to and why to create different environments like Dev, Int, Perf in jenkins so that it will reflect on teams of Deploy widget configuration. Any clarification would be helpful. Thanks.

**Comment by satishc1** [comment]
@supremex1 You can create jobs in Jenkins that deploy to Dev , QA , Int , Perf , Prod.
In these jobs, under Post Build Actions -> Hygieia Publisher -> select "Publish Build Status" and  "Publish Deployment Results" and fill in the details of your artifact. The environment name will be set to one of Dev , QA , Int , Perf , Prod.  Then run these jobs and you should see the deploy widget populated.
