### ISSUE TITLE
Jira-Collector Potential NPE  with lower version Jira instance

### ISSUE THREAD

**Issue by xpdable** [capitalone/Hygieia#1035]
Unfortunately, we still have a jira 5.1 instance running in the company with which I met a NullPointerException in Jira collector. I change the code locally to get it working with jira 5.1 api, currently.
Therefore, I am not sure do your team has the clear scope on what is the lowest supported version of Jira (mostly we're running 6+)?  

Plus to share the issue:
on the jira API  <jira-host>/rest/api/2/status: 
6.1+
```json
{
  "description": "The issue is open and ready for the assignee to start work on it.",
  "iconUrl": "http://xxx/images/icons/statuses/open.png",
  "id": "1",
  "name": "Open",
  "self": "http://xxx/rest/api/2/status/1",
  "statusCategory": {
    "colorName": "blue-gray",
    "id": 2,
    "key": "new",
    "name": "To Do",
    "self": "http://xxx/rest/api/2/statuscategory/2"
  }
}
```
5.1:
```json
{
  "description": "The issue is open and ready for the assignee to start work on it.",
  "iconUrl": "http://xxxx/images/icons/status_open.gif",
  "id": "1",
  "name": "Open",
  "self": "http://xxx/rest/api/2/status/1"
}
```
According to **Hygieia/collectors/feature/jira/src/main/java/com/capitalone/dashboard/client/DefaultJiraClient.java**, line [367-369]:
```java
Object statusCategory = jsonStatus.get("statusCategory");
JSONObject jsonStatusCategory = (JSONObject) statusCategory;
String statusCategoryName = (String) jsonStatusCategory.get("name");
```
Obviously, if I am running with jira 5.1 api, I will get a null statusCategory which leads to a NullPointerException when I afterwards try to get() from null :(

Currently I make the if statement after line 367 to judge with I get a null of 'statusCategory' to get everything working.

Please advice if you're support jira 5.1 .

Thanks,
Xiaopeng

**Comment by MarkRx** [comment]
I don't know if there is a decided upon lowest supported jira instance. I added that null guard to #1030.

**Comment by xpdable** [comment]
Great! Really appreciate the quick patch :)

**Comment by satishc1** [comment]
@xpdable Functionality merged in https://github.com/capitalone/Hygieia/pull/1137 Use latest codebase and follow cleanup instructions provided in PR.
