### ISSUE TITLE
Need documentation on how to contribute collectors and widgets and dashboards

### ISSUE THREAD

**Issue by davidcastagna** [capitalone/Hygieia#1037]
I am interested in writing my own collectors/widgets/dashboards for a Hygieia stand-up we’re working on.

Besides the obvious generatable javadoc are there any reference materials that would help me to better understand collector design and how I would create my own?

Also if you have any relevant information about the widget and dashboard sides of the equation that
Would be immensely helpful as well.

**Comment by mrpudn** [comment]
Here are some places to start looking:
  - Collectors
    - #985 Creating Custom collectors (Skeleton project)
    - #747
    - #733
    - #726
    - #713
  - Widgets
    - #837
    - #291
    - #283
  - General
    - #221 
    - #67

**Comment by monabhardwaj** [comment]
Hello! I'm new to Hygieia and currently attempting to create a custom github collector. I have gone through various articles on the same but weren't of much help on the beginner level. It would be  invaluable for me if could extend any advice or sample projects on how you got your custom collector working. Thank You!
@davidcastagna

**Comment by golokeshpatra45** [comment]
@tabladrum 

I need to get started with the making of custom collectors, can you help me ? 
I have no idea how to get started, what to do and what not to, but I have been told to use the already present collector like (Github SCM collector) and modify it to my use. 

Can you please help me how to do that ?

**Comment by GPreksha** [comment]
Hi,  I need the steps to configure  "GIT HUB" code repo to hygiea?
