### ISSUE TITLE
UI Style Missing

### ISSUE THREAD

**Issue by Mark-Smithh** [capitalone/Hygieia#1040]
Everything builds and I am able to run it.   But when the UI opens on port 3000 it has no style elements.  It is just a black and white page with text and buttons.

I notice this error in the build output, could this have something to do with it?
```
[INFO] [16:53:10] Finished 'fonts' after 39 ms
[ERROR] Error in plugin 'gulp-less'
[ERROR] Message:
[ERROR]     '../../../../bower_components/angular-ui-select/dist/select.css' wasn't found in file C:\Users\uname\Workspaces\Hygieia\Hygieia\UI\src\components\widgets\build\build.less line no. 3
[ERROR] Details:
[ERROR]     type: File
[ERROR]     filename: C:\Users\uname\Workspaces\Hygieia\Hygieia\UI\src\components\widgets\build\build.less
[ERROR]     index: 107
[ERROR]     line: 3
[ERROR]     callLine: NaN
[ERROR]     callExtract: undefined
[ERROR]     column: 0
[ERROR]     extract: @import (reference) '../../../app/css/mixins.less';,@import (less)  '../../../../bower_components/angular-ui-select/dist/select.css';,
[ERROR]     lineNumber: 3
[ERROR]     fileName: C:\Users\uname\Workspaces\Hygieia\Hygieia\UI\src\components\widgets\build\build.less
```

**Comment by Mark-Smithh** [comment]
Entire build output included.

[Hygieia_Build_Output.txt](https://github.com/capitalone/Hygieia/files/661743/Hygieia_Build_Output.txt)

**Comment by mrpudn** [comment]
Alright, and can you share the output of `ls -al` (bash) or `dir` (command prompt) in your `C:\Users\uname\Workspaces\Hygieia\Hygieia\UI\src` directory?

**Comment by Mark-Smithh** [comment]
C:\Users\uname\Workspaces\Hygieia\Hygieia\UI\src>ls -al output attached

[Hygieia_UI_src.txt](https://github.com/capitalone/Hygieia/files/662112/Hygieia_UI_src.txt)

**Comment by Mark-Smithh** [comment]
I see now the AngularJS ui-select dependency is missing from UI/src folder.  

When I run bower install angular-ui-select I get message below 
 ECONFLICT Unable to find suitable version for angular-ui-select

**Comment by mrpudn** [comment]
Try running `bower install` from the `UI` directory. It doesn't appear as though you have any bower components installed.

**Comment by Mark-Smithh** [comment]
I run bower install and nothing happens.  I uninstalled bower.  Reinstalled bower.  Same results.

**Comment by mrpudn** [comment]
You appear to be running it from the `src` directory - run `bower install` from the `Hygieia\UI` where the `bower.json` file is stored.

**Comment by Mark-Smithh** [comment]
I am running from UI folder

user@domain MINGW64 /c/users/uname/workspaces/hygieia/hygieia/ui (master)
$ bower --verbose install

user@domain MINGW64 /c/users/uname/workspaces/hygieia/hygieia/ui (master)

**Comment by Mark-Smithh** [comment]
Thought I'd add system Info:

System info:
Bower version: 1.8.0
Node version: 6.9.2
OS: Windows_NT 6.1.7601 x64

**Comment by Mark-Smithh** [comment]
I resolved the issue.  Problem was in by .bowerrc file.  

I had following in the file:
`{
    "directory": "library",
	"registry": "http://bower.herokuapp.com",
	"proxy":"[PROXY_SERVER_ADDRESS_:PORT_HERE]",		
    "https-proxy":"PROXY_SERVER_ADDRESS:PORT_HERE"
}
`

When I changed to this:
`{
 "proxy":"[PROXY_SERVER_ADDRESS_:PORT_HERE]",		
    "https-proxy":"PROXY_SERVER_ADDRESS:PORT_HERE"
}
`

It worked.

Thanks for pointing me in the right direction.

**Comment by mrpudn** [comment]
Ah, ok - glad to see you got it resolved.

As a side note - you shouldn't have to set the bower proxy setting explicitly like that. It should honor your `HTTP_PROXY` and `HTTPS_PROXY` environment variables, if you have them set. Most tools follow this convention, which makes things much easier behind a proxy.

**Comment by Joshnachristline** [comment]
Hi,
Im facing the same error and despite of the solutions suggested above, the error still remains. 
Im here trying to give the command "gulp serve". It ends up with this error. 

Thanks in advance
