### ISSUE TITLE
Sonar

### ISSUE THREAD

**Issue by eldojoseph** [capitalone/Hygieia#1041]
Is there a option to access sonar url which is protected by userid/password? I tried adding sonar.username and sonar.apiKey but didnt work. collector able to access the url but failing to pull the data due to authentication issue.

**Comment by tabladrum** [comment]
Sonar collector does support userid/password based basic auth. Does not (yet) handle token based. Let me know is basic auth is not working for you. Will be good to have token based auth.

**Comment by tabladrum** [comment]
Can we close this @eldojoseph

**Comment by eldojoseph** [comment]
@tabladrum sorry I missed to update you. Basic auth didnt work. I am yet to dig more on it. please share if someone is using token based auth.

**Comment by tabladrum** [comment]
If you have any log to share, it will be helpful.

**Comment by eldojoseph** [comment]
I am sorry. I cannot share logs from my client's machine.
