### ISSUE TITLE
appdynamics collector

### ISSUE THREAD

**Issue by anjana83** [capitalone/Hygieia#1044]
Hi,

is appdynamics collector ready to use or still work in progress? I see "paychex" has started working on that but I cloudn't find enough details about it.

Thanks,
Anjana

**Comment by pxk5958** [comment]
Paychex is not working on it. I guess CapitalOne is according to this: https://github.com/capitalone/Hygieia/issues/697

**Comment by tabladrum** [comment]
Yes. We are. We have some working version ready. Need some brush up before it goes out.

**Comment by wanamaker44** [comment]
Any update on this? Would love to integrate an AppD collector into our environment.

**Comment by tabladrum** [comment]
@nireeshT @satishc1 showed me the work today - looks like PR will be merged next week?

**Comment by Rishikeshpal** [comment]
@tabladrum  anyone from your team will be able to help me with my issue on appD and hygieia integration? i have raised the issue. https://github.com/Hygieia/hygieia-perf-appdynamics-collector/issues/2
