### ISSUE TITLE
Hygieia publisher not working 

### ISSUE THREAD

**Issue by vetrivelan25** [capitalone/Hygieia#1046]
Hi,
     I have configure Hygieia Publiser in jenkins but nothing is displayed on hygieia dashboard.
After successful build i tried to check on Configure Deploy widget on Hygieia dashboard it shows ****No items were found.****

Jenkins Global Configure:
Jenkins global configuration done got success message.

I have done all the Hygieia Publisher job level configuration also have some issue so not able upload the my configuration screen shots.

MY Console outoput:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.894 s
[INFO] Finished at: 2016-12-21T05:57:38+00:00
[INFO] Final Memory: 23M/279M
[INFO] ------------------------------------------------------------------------
[JENKINS] Archiving /home/jenkins/workspace/...../pom.xml to com.comcast.rphy/devops/0.0.1-SNAPSHOT/devops-0.0.1-SNAPSHOT.pom
[JENKINS] Archiving /home/jenkins/workspace/...../target/devops.war to com......rphy/devops/0.0.1-SNAPSHOT/devops-0.0.1-SNAPSHOT.war
channel stopped
Hygieia: Published Build Complete Data. Response Code: 201. Response Value= 585a19c9f290810f1fb84199
Hygieia Build Artifact Publisher - Looking for file pattern 'devops.war' in directory /home/jenkins/workspace/.../.../ws/target
Hygieia: Published Sonar Result. Nothing to publish
Hygieia Deployment Publisher - Looking for file pattern 'devops.war' in directory /home/jenkins/workspace/...../..../ws/target
Finished: SUCCESS
```

**Comment by satishc1** [comment]
@vetrivelan25 
Hygieia Deployment Publisher - Looking for file pattern 'devops.war' in directory /home/jenkins/workspace/...../..../ws/target

Can you confirm that the file devops.war exists in the file system path as listed in the log ?

**Comment by vetrivelan25** [comment]
Hi,
   Problem in deployment path.Now it's working.Thanks for your help.
