### ISSUE TITLE
Dashboard.properties

### ISSUE THREAD

**Issue by shilpsl1** [capitalone/Hygieia#1047]
Hi,

I am trying to set up API Layer. I have placed dashboard.properties in Hygieia-master folder and running below command from /home/shree/Hygieia/Hygieia-master/api/target folder and I am getting below error.
```bash
java -jar api.jar --spring.config.location=/home/shree/Hygieia/Hygieia-master/dashboard.properties 
```
```properties
# dashboard.properties
dbname=dashboard
dbusername=dashboarduser
dbpassword=dbpassword
dbhost=10.0.0.0
dbport=27017
dbreplicaset=false
```
```
INFO  org.mongodb.driver.cluster - Exception in monitor thread while connecting to server 10.0.0.0:27017
com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.connection.SocketStream.open(SocketStream.java:63) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:114) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:127) ~[mongo-java-driver-3.0.2.jar!/:na]
	at java.lang.Thread.run(Thread.java:785) [na:1.8.0-internal]
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0-internal]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:380) ~[na:1.8.0-internal]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:236) ~[na:1.8.0-internal]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:218) ~[na:1.8.0-internal]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[na:1.8.0-internal]
	at java.net.Socket.connect(Socket.java:666) ~[na:1.8.0-internal]
	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.connection.SocketStream.open(SocketStream.java:58) ~[mongo-java-driver-3.0.2.jar!/:na]
	... 3 common frames omitted
2016-12-21 12:21:44,902 INFO  o.s.b.c.e.ServletRegistrationBean - Mapping servlet: 'dispatcherServlet' to [/]
2016-12-21 12:21:44,910 INFO  o.s.b.c.e.FilterRegistrationBean - Mapping filter: 'characterEncodingFilter' to: [/*]
2016-12-21 12:21:44,911 INFO  o.s.b.c.e.FilterRegistrationBean - Mapping filter: 'loggingFilter' to: [/*]
2016-12-21 12:21:45,038 INFO  org.mongodb.driver.cluster - No server chosen by PrimaryServerSelector from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, all=[ServerDescription{address=10.0.0.0:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused}}]}. Waiting for 30000 ms before timing out
```

**Comment by mrpudn** [comment]
Try this from the `/Hygieia-master` root directory:
```bash
java -jar api/target/api.jar --spring.config.location=dashboard.properties
```

Also, make sure you can connect to your MongoDB instance at `10.0.0.0:27017` and that you've created the `dashboarduser` MongoDB user with password `dbpassword`.

Try to connect with the mongo shell:
```bash
mongo mongodb://dashboarduser@dbpassword:10.0.0.0:27017/dashboard
```

**Comment by shilpsl1** [comment]
Yesterday i was able to login to mongo DB successfully. This is ouput I got when I created DB and user
Successfully added user: {
	"user" : "dashboarduser",
	"roles" : [
		{
			"role" : "readWrite",
			"db" : "dashboard"
		}
	]
}

But now when I try to login,
> mongo 10.0.0.0:27017/dashboard -u dashboarduser -p dbpassword
MongoDB shell version v3.4.0
connecting to: mongodb://10.0.0.0:27017/dashboard
MongoDB server version: 3.4.0
2016-12-21T13:59:40.395-0600 E QUERY    [main] Error: Authentication failed. :
DB.prototype._authOrThrow@src/mongo/shell/db.js:1459:20
@(auth):6:1
@(auth):1:2
exception: login failed

**Comment by shilpsl1** [comment]
I am sure of that the password is right, I removed user and created again also

> use dashboarddb
switched to db dashboarddb
> db.createUser(
...                 {
...                   user: "dashboarduser",
...                   pwd: "dbpassword",
...                   roles: [
...                      {role: "readWrite", db: "dashboard"}
...                           ]
...                   })
Successfully added user: {
	"user" : "dashboarduser",
	"roles" : [
		{
			"role" : "readWrite",
			"db" : "dashboard"
		}
	]
}
> ^C
bye

**Even then I am getting error, I don't understand what is going wrong. Please help!!! ** 

Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='dashboarduser', source='dashboard', password=<hidden>, mechanismProperties={}}
	at com.mongodb.connection.SaslAuthenticator.authenticate(SaslAuthenticator.java:61) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.connection.InternalStreamConnectionInitializer.authenticateAll(InternalStreamConnectionInitializer.java:99) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.connection.InternalStreamConnectionInitializer.initialize(InternalStreamConnectionInitializer.java:44) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:115) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:127) ~[mongo-java-driver-3.0.2.jar!/:na]
	at java.lang.Thread.run(Thread.java:785) [na:1.8.0-internal]
Caused by: com.mongodb.MongoCommandException: Command failed with error 18: 'Authentication failed.' on server 10.0.0.0:27017. The full response is { "ok" : 0.0, "errmsg" : "Authentication failed.", "code" : 18, "codeName" : "AuthenticationFailed" }

**Comment by shilpsl1** [comment]
I got fix Db issue...

But it failed again with below error:

Error starting ApplicationContext. To display the auto-configuration report enable debug logging (start with --debug)

2016-12-21 15:42:02,166 ERROR o.s.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pingController': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private java.lang.String com.capitalone.dashboard.rest.PingController.versionNumber; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'version.number' in string value "${version.number}"

**Comment by amitmawkin** [comment]
did you run the mvn clean compile package command?

**Comment by shilpsl1** [comment]
Yes !!! But UI build failed, First time I faced the same issue ... I installed Bower with below command,
**bower install –allow-root**
and I have this
# bower --version
1.8.0
# gulp --version
[16:19:21] CLI version 3.9.1

But now I again get, 

[INFO] com.capitalone.dashboard:gitlab-git-collector ..... SUCCESS [  5.335 s]
[INFO] com.capitalone.dashboard:UI ....................... FAILURE [ 20.719 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:56 min
[INFO] Finished at: 2016-12-21T16:16:24-06:00
[INFO] Final Memory: 103M/234M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.29:bower (bower install) on project UI: Failed to run task: 'bower install' failed. (error code 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by amitmawkin** [comment]
you need to build the complete project including the api and the collectors

**Comment by shilpsl1** [comment]
That is the problem I am facing.Ho can I do run the build.
If I run as root user, UI build fails saying Bower cannot install . If I run as non root user other build fails. How do I make it fully run.

**Comment by mrpudn** [comment]
Please refer to this article regarding global node module permissions:
https://docs.npmjs.com/getting-started/fixing-npm-permissions

You need to reinstall bower properly in order for the build to succeed

**Comment by shilpsl1** [comment]
I am not sure whether it is really a problem with npm, I still tried npm permissions from the link you provided. But still no use. I had to end up in,

[INFO] Node v5.4.1 is already installed.
[INFO] NPM 2.14.15 is already installed.
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.29:npm (npm install) @ UI ---
[INFO] Found proxies: []
[INFO] Running 'npm install' in /home/shree/Hygieia/Hygieia-master/UI
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.29:bower (bower install -allow-root) @ UI ---
[INFO] Found proxies: []
[INFO] Running 'bower install' in /home/shree/Hygieia/Hygieia-master/UI
[ERROR] bower ESUDO         Cannot be run with sudo
[ERROR] 
[ERROR] Additional error details:
[ERROR] Since bower is a user command, there is no need to execute it with superuser permissions.
[ERROR] If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.
[ERROR] 
[ERROR] http://www.joyent.com/blog/installing-node-and-npm
[ERROR] https://gist.github.com/isaacs/579814
[ERROR] 
[ERROR] You can however run a command with sudo using --allow-root option
[INFO] -----------------------------------------------------------------------

**Comment by mrpudn** [comment]
Are you running `mvn clean install` without `sudo`?

**Comment by shilpsl1** [comment]
I am using root user. 
I tried using non root user Hygieia build itself failed

**Comment by mrpudn** [comment]
Please try again as a non-root user and provide the output. Installing Hygieia does not require root privileges

**Comment by shilpsl1** [comment]
Build was success as a non root user Thanks!!!
But why root user cannot be used ?

**Comment by shilpsl1** [comment]
Once the build is success i created dashboard.properties and ran
java -jar api/target/api.jar --spring.config.location=dashboard.properties
also tried 
java -jar api.jar --spring.config.location=/home/admin/Hygieia-master/dashboard.properties

 WARN  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pingController': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private java.lang.String com.capitalone.dashboard.rest.PingController.versionNumber; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'version.number' in string value "${version.number}"
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]

**Comment by mrpudn** [comment]
It's generally considered bad practice to give more permissions to something than it requires. Some libraries put safeguards in place to deter you from giving too many permissions to things:
```
[ERROR] Additional error details:
[ERROR] Since bower is a user command, there is no need to execute it with superuser permissions.
[ERROR] If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.
```

As for the error you're getting - I'm not 100% sure, but it looks like a spring config error. I think @amitmawkin was the one who added the version number to the `PingController`, so I'll defer to him

**Comment by shilpsl1** [comment]
Can I please get if any updates available for the above error. I am tired fixing it  :(

**Comment by amitmawkin** [comment]
@shilpsl1 are you running a maven build , cause as part of build it generates a file containing the version number under the api project, in your case looks like it is not happening. 

What command are you using for build?

**Comment by shilpsl1** [comment]
@amitmawkin 
I ran -- "mvn clean install package" in hygieia-master folder and the build was success.

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] com.capitalone.dashboard:Hygieia .................. SUCCESS [  3.031 s]
[INFO] com.capitalone.dashboard:core ..................... SUCCESS [ 53.359 s]
[INFO] com.capitalone.dashboard:api ...................... SUCCESS [ 20.106 s]
[INFO] com.capitalone.dashboard:artifactory-artifact-collector  SUCCESS [  8.389 s]
[INFO] com.capitalone.dashboard:bamboo-build-collector ... SUCCESS [  6.288 s]
[INFO] com.capitalone.dashboard:jenkins-build-collector .. SUCCESS [  6.388 s]
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector  SUCCESS [  6.019 s]
[INFO] com.capitalone.dashboard:sonar-codequality-collector  SUCCESS [  1.742 s]
[INFO] com.capitalone.dashboard:aws-cloud-collector ...... SUCCESS [  4.608 s]
[INFO] com.capitalone.dashboard:udeploy-deployment-collector  SUCCESS [  5.314 s]
[INFO] com.capitalone.dashboard:xldeploy-deployment-collector  SUCCESS [  5.997 s]
[INFO] com.capitalone.dashboard:jira-feature-collector ... SUCCESS [ 15.286 s]
[INFO] com.capitalone.dashboard:versionone-feature-collector  SUCCESS [  5.727 s]
[INFO] com.capitalone.dashboard:chat-ops-collector ....... SUCCESS [  1.574 s]
[INFO] com.capitalone.dashboard:bitbucket-scm-collector .. SUCCESS [  6.310 s]
[INFO] com.capitalone.dashboard:github-scm-collector ..... SUCCESS [  5.444 s]
[INFO] com.capitalone.dashboard:subversion-collector ..... SUCCESS [  1.537 s]
[INFO] com.capitalone.dashboard:gitlab-git-collector ..... SUCCESS [  5.410 s]
[INFO] com.capitalone.dashboard:UI ....................... SUCCESS [01:24 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ---------------

After the build api folder:
api]$ ls
docker  logs  pom.xml  README.md  src  target
 
Then created dashboard.properties files in Hygieia-master/api/target 
dbname=dashboard
dbusername=dashboarduser
dbpassword=dashpassword
dbhost=10.0.0.0
dbport=27017
server.contextPath=/api
server.port=8080

**java -jar api.jar --spring.config.location=dashboard.properties**

which gives me below error:

 Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pingController': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private java.lang.String com.capitalone.dashboard.rest.PingController.versionNumber; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'version.number' in string value "${version.number}"

**Comment by shilpsl1** [comment]
Am I missing any step ??

**Comment by tabladrum** [comment]
try this: 
java -jar api.jar --spring.config.location=<full path of the properties file>  --spring.config.name=api

**Comment by shilpsl1** [comment]
**Tried, still I get same error**

2017-01-03 10:19:48,317 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:2, serverValue:179}] to 10.0.0.0:27017
2017-01-03 10:19:49,715 WARN  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pingController': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private java.lang.String com.capitalone.dashboard.rest.PingController.versionNumber; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'version.number' in string value "${version.number}"
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]

**Comment by amitmawkin** [comment]
what version of maven are you using?.

**Comment by shilpsl1** [comment]
Apache Maven 3.2.1

**Comment by amitmawkin** [comment]
can you try 3.3.9 please or anything above 3.3

**Comment by shilpsl1** [comment]
okay let me try and update

**Comment by shilpsl1** [comment]
I just upgraded to Apache Maven 3.3.9 still i get same error...

**Comment by shilpsl1** [comment]
I tried running gulp server, when UI is connected it throws below error... 
It is failing to connect 8080 port
Any suggestion how to fix this connection problem

[Proxy] { Error: connect ECONNREFUSED 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8080 }

**Comment by mrpudn** [comment]
It looks like your API isn't running - can you confirm that your API is also up and running?

**Comment by shilpsl1** [comment]
API is not running that is why the above 2 errors... 
When I am running, java -jar api.jar --spring.config.location=dashboard.properties 
i am getting those errors... If any solution please me know

**Comment by amitmawkin** [comment]
can you download the api.jar from  here run it http://repo1.maven.org/maven2/com/capitalone/dashboard/api/2.0.4/api-2.0.4.jar

**Comment by shilpsl1** [comment]
**Replaced still same error :**  
Error creating bean with name 'pingController': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private java.lang.String com.capitalone.dashboard.rest.PingController.versionNumber; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'version.number' in string value "${version.number}"

**Comment by satishc1** [comment]
@shilpsl1 
Add this line to your dashboard.properties file

version.number=@application.version.number@

And then run the api with the command 
java -jar api.jar --spring.config.name=api --spring.config.location=/yourfullpathto/dashboard.properties

**Comment by shilpsl1** [comment]
It works fine after adding version.number=@application.version.number@ in dashboard.properties
Thank you so much!!!

**Comment by satishc1** [comment]
@shilpsl1 Glad to note its working now.

**Comment by shilpsl1** [comment]
@satishc1 
Just to understand, i never saw in any or mentioned anywhere adding this line in property file. why should this be added explicitly..

**Comment by mhoffman78** [comment]
My API Connectivity is showing a red circle with a "X" so I am assuming there is no connectivity.  Do I need both a dashboard.properties and api.properties?

**Comment by elzerver** [comment]
Hey there!

You need the properties file in the UI side, that red mark means that you
don't have the connectivity to the API.

Cheers!
