### ISSUE TITLE
Jenkins Plugin: Jenkins 2.0 support

### ISSUE THREAD

**Issue by tabladrum** [capitalone/Hygieia#1048]
Here is my fork where I am pushing code to have pipeline support to Jenkins plugin. I have so far done build and artifact publishing. The changes should be backward compatible. Will appreciate if anyone has time to do some testing and pre-review.

https://github.com/tabladrum/Hygieia/tree/master/hygieia-jenkins-plugin

@MarkRx Question for you: the Metadata section in ArtifactBuilder will not work for pipeline. Instead of getting the SCM metadata from envVar, I will get it from the build data that I already have in that section of the code. May be a second thought on the meta data? Do we need it? Or should reduce duplication and have only the meta data? In any case, pipeline api returns a list of SCMs and I will have to handle it as a list - which means the SCM metadata must be a list. Thoughts?

**Comment by MarkRx** [comment]
How does the jenkins plugin handle multiple scms right now? Are we just using the first?

The metadata is needed. It wouldn't make sense for metadata to be a list as it is simply a key-value property holder (that corresponds to artifactory properties). Instead you could use a numbering scheme similar to how jenkins handles multiple repositories. Example:

```
scmUrl: "url",
scmUrl1: "url1",
scmUrl2: "url2"
scmBranch: "..."
scmBranch1: "..."
```

@pxk5958 did you encounter this with #1038?

**Comment by tabladrum** [comment]
Currently it stores the SCMs in a list of CodeRepo structure. For most cases it is just one. Not sure if any one builds multiple repos at once.

**Comment by tabladrum** [comment]
https://github.com/capitalone/Hygieia/pull/1055

**Comment by tabladrum** [comment]
Closing this as the PR is in.
