### ISSUE TITLE
How to add custom environment name in UI

### ISSUE THREAD

**Issue by vetrivelan25** [capitalone/Hygieia#1052]
Hi,
I want to add or display our  custom environment name in **Configure Delivery Pipeline** currently DEV,QA,INT,PERF,PROD environments are available.
suppose i want to add environment one new environment SIT for that how to configure or which file i have change?? or is it possible to change the existing display environment names in UI.

**Comment by MarkRx** [comment]
PR #1020 adds this functionality but has not been accepted yet.

**Comment by vetrivelan25** [comment]
Kindly send me the latest packge link once merge your changes in to master

**Comment by MarkRx** [comment]
It would be easiest to wait for them to get merged in.

You can build the branch here: https://github.com/paychex/Hygieia/tree/feature/TAXSDLC-1100

**Comment by vetrivelan25** [comment]
Sure Kindly send me  the latest link once you merge the changes into master branch.and also explain how to change our environment names.

**Comment by vetrivelan25** [comment]
@MarkRx  
Hi,
     Reg  https://github.com/paychex/Hygieia/tree/feature/TAXSDLC-1100  bild merge was completed on master branch? Kindly send me the link.

**Comment by MarkRx** [comment]
Ask @tabladrum @amitmawkin :)

**Comment by vetrivelan25** [comment]
Hi @tabladrum  @amitmawkin,
Reg https://github.com/paychex/Hygieia/tree/feature/TAXSDLC-1100 build merge was completed on master branch? If merge was completed Kindly send me the link.

**Comment by vetrivelan25** [comment]
Hi @tabladrum and @amitmawkin,
Reg https://github.com/paychex/Hygieia/tree/feature/TAXSDLC-1100 build merge was completed on master branch? If merge was completed Kindly send me the link.
Kindly respond

**Comment by nireeshT** [comment]
@vetrivelan25  - Update to latest code base and use the pipeline widget to customize the stage names for deployed environments.
