### ISSUE TITLE
integrate with perforce (scm tool)

### ISSUE THREAD

**Issue by Hokwang** [capitalone/Hygieia#1056]
Hello.

Do you have a plan for supporting perforce?

Or is there a way to connect perforce?

Thank you in advanced.

**Comment by amitmawkin** [comment]
We would expect the Hygieia community to contribute a collector for perforce based on need and desire , we can guide you if you are interested in doing so. 

Hygieia core team  does not have access to perforce so it would be hard to comment on what kind of integrations does its api/hook supports (push vs pull) 

For an example of a community contributed  collector please see the below link https://github.com/capitalone/Hygieia/tree/master/collectors/scm/gitlab
