### ISSUE TITLE
Null pointer exception when starting bamboo collector

### ISSUE THREAD

**Issue by roshanvc** [capitalone/Hygieia#1061]
when I start the bamboo collector, I get a null pointer exception. I have attached the log file with the error

[buildcollector-2016-12-28.txt](https://github.com/capitalone/Hygieia/files/682039/buildcollector-2016-12-28.txt)

This is the properties file I am using to start the collector
```properties
spring.data.mongodb.database=dashboarddb
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.username=dashboarduser
spring.data.mongodb.password=dbpassword
# Collector schedule (required)
bamboo.cron=0 0/5 * * * *
# Jenkins server (required) - Can provide multiple
bamboo.servers[0]=http://bambooserver:8085/
bamboos.saveLog=false
```

**Comment by tabladrum** [comment]
Can you paste the command line that you used to start the collector?

**Comment by roshanvc** [comment]
Here is the command

java -jar bamboo-build-collector-2.0.4-SNAPSHOT.jar --spring.config.name=application.properties --spring.config.location=C:\Hygieia\Hygieia-master\collectors\build\bamboo\target

I am executing the above command inside the folder C:\Hygieia\Hygieia-master\collectors\build\bamboo\target. Both the jar and the property file exists in the same location

**Comment by zenglincui** [comment]
I have to copy the property file to target directory and use following command to resolve this issue.
~\bamboo\target\java -jar bamboo-build-collector-2.0.4-SNAPSHOT.jar --spring.config.name=bamboo --spring.config.location=application.properties

**Comment by roshanvc** [comment]
The property file and the jar files are present in the same directory(target) already. I tried the above command but still get the same exception

**Comment by tabladrum** [comment]
note the ``--spring.config.name=bamboo`` instead of ``--spring.config.name=application.properties``

**Comment by zenglincui** [comment]
In Windows, this command
~\bamboo\target\java \
  -jar bamboo-build-collector-2.0.4-SNAPSHOT.jar \
  --spring.config.name=bamboo \
  --spring.config.location=application.properties
resolved the error mentioned, but I got a different error - "404 Not found" and could not make the data flow from Bamboo to the UI.  Refer to https://github.com/capitalone/Hygieia/issues/1072.

it doesn't recognize the path if I use something like
~\bamboo\target\java \
  -jar bamboo-build-collector-2.0.4-SNAPSHOT.jar \
  --spring.config.name=bamboo \
  --spring.config.location=C:\Hygieia\Hygieia-master\collectors\build\bamboo\src\main\resources\application.properties

**Comment by roshanvc** [comment]
I did a fresh build in Ubuntu and it worked for me. But doing the same on a windows OS is giving this null pointer exception

**Comment by Ramesh18190** [comment]
Can anyone help me here?
here are my log file, looks like slimier kind of errors,
![bamboo logs](https://cloud.githubusercontent.com/assets/19280204/22751389/c9c8e896-edf9-11e6-8fdf-cdef8872ef14.PNG)

and if i try same build plan on browser i am getting this,
![bamboo api](https://cloud.githubusercontent.com/assets/19280204/22752667/0177023c-edff-11e6-9c96-67cbd7d38772.PNG)


 Here is my property file
#########################################
dbname=dashboarddb
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
dbusername=dashboarduser
dbpassword=dbpassword
bamboo.cron=0 0/1 * * * *
bamboo.servers[0]=http://myec2publicip.amazonaws.com:8085
bamboo.username=myusername
bamboo.apiKey=mypassword
bamboo.saveLog=true
###########################

Tried with both  properties at --spring.config.name=bamboo and --spring.config.name= application

**Comment by Ramesh18190** [comment]
@tabladrum Can you please help me here,

**Comment by Ramesh18190** [comment]
@roshanvc @tabladrum please help me here, I am desperately looking fr a help,

**Comment by tabladrum** [comment]
Do you have bamboos.saveLog=true in your properties file? That's what seems to be the problem here (based on the code that I see). If yes, turn it off and see if the error is there.

**Comment by Ramesh18190** [comment]
@tabladrum Thank you so much! issue is resolved

**Comment by satishc1** [comment]
Closed.
