### ISSUE TITLE
How to set results directory and file name pattern in Publish Test Results?

### ISSUE THREAD

**Issue by wangjianwen** [capitalone/Hygieia#1062]
I want to collect unit test result by using hygieia-jenkins-plugin. How to set results directory and file name pattern in Publish Test Results. What plug-INS generate these files and file content?

**Comment by tabladrum** [comment]
For unit tests, Hygieia expects the tests in Sonar. For functional tests that are cucumber/selenium based, you can use the hygieia-jenkins plugin option. Jenkins cucumber plugin generates the json files that are read by the hygieia plugin.

**Comment by wangjianwen** [comment]
Thanks you reply. But I have a question:  Jenkins cucumber plugin can generate unit test result in json files? In general, cucumber is used for Behaviour-Driven Development. But I still do not understand why the cucumber can also be used to produce unit test results？

**Comment by tabladrum** [comment]
Yes it can. As long as there is a json file the hygieia plugin should work.

**Comment by wangjianwen** [comment]
Thanks you reply! I will try to install Jenkins cucumber plugin.
