### ISSUE TITLE
How can I configure multiple Bitbucket Repos in a single page ?

### ISSUE THREAD

**Issue by juantoledo** [capitalone/Hygieia#1064]
Hello, 
I'm trying to configure multiple BB Repos in a single page? When I add new rows, all results are replicating on each one.

I'm trying to fulfill an entire template.  Like this:

![captura](https://cloud.githubusercontent.com/assets/972961/21622579/ff3d36e6-d1dc-11e6-997f-b5b1062a6d75.PNG)

Multirow and multicolumn.

Thanks in advance.

**Comment by MarkRx** [comment]
You can't. The design of a dashboard is 1:1:1. 1 Component, 1 Repository, 1 Jenkins Job. Technically the model could support it but I don't think that is wanted. It would cause complications for the pipeline and team dashboards.

**Comment by juantoledo** [comment]
Thanks for the response. I've seen someone wrote about playing with the rows in a single page could do the trick.

**Comment by tabladrum** [comment]
Technically you can do it. But then you have just created a dashboard for showing only Github repo's.

**Comment by juantoledo** [comment]
That's exactly what I want. I think template should support any kind of widget organization

**Comment by nitin1706** [comment]
'Multiple widgets of same type' will be available soon.

**Comment by wwei1896** [comment]
@nitin1706  hi, Nitin  is the 'Multiple widgets of same type'  feature can be supported on the latest version? When is the entry for the feature? thanks a lot!

**Comment by alihussainiF1** [comment]
Hi I am trying to do the same display multiple repos in one dashboard is there an already working solution for the same ?
