### ISSUE TITLE
Docker image links need capitalone prefix

### ISSUE THREAD

**Issue by urbaitel** [capitalone/Hygieia#1065]
Docker image links are missing the capitalone/ prefix as in here:
https://hub.docker.com/u/capitalone/

Shall I do a PR to fix?   

Also, need to either add docker images for the missing ones or use this guys:
https://hub.docker.com/u/smartlxh/

**Comment by matthewbeasley** [comment]
@urbaitel - the compose file included in the repo is intended to be for getting a local setup running. It references the images on your local machine which are made available after running `mvn clean install docker:build`. We currently don't keep the images in Docker Hub updated but we intend to do so in the near future. In the meantime you can run the above command to generate the images and from there you can push the images anywhere you'd like.
