### ISSUE TITLE
Question: Dashboard name validation

### ISSUE THREAD

**Issue by Mpluya** [capitalone/Hygieia#1067]
We ran into a scenario where one of our users created a dashboard with a slash ('/') in the name, i.e. "Test/Dashboard". While dashboard creation was successful, he then was unable to configure any of the widgets. This is so because the configure action was unable to hit the '/dashboard/myowner/{dashboardtitle}' endpoint, since his request was '/dashboard/myowner/Test/Dashboard'. My question to the group is, would there be interest in adding a validation around the dashboard name to prevent slashes and or any special characters? If yes, I'll open a PR on this. Thanks.

**Comment by satishc1** [comment]
@Mpluya Sure.. please do. Thanks for the help.

**Comment by Mpluya** [comment]
@satishc1 thank you.

**Comment by satishc1** [comment]
@Mpluya Closed.
