### ISSUE TITLE
Is it possible to create Administor groups in hygieia dashboard.

### ISSUE THREAD

**Issue by vetrivelan25** [capitalone/Hygieia#1074]
Hi,
   As per now who ever created the dashboard that only person has full rights his dashboard other users only view the dashboard.
 We need one user that have all privileges means read/write of all user dashboard's like a admin.
Is it possible to create admin group under all the user have admin rights??

Regards,
Vetrivelan T

**Comment by MarkRx** [comment]
Nope. Perhaps #1031 will address that.

@rob-miller-777

**Comment by rob-miller-777** [comment]
Correct @MarkRx, we will be making admin a "role", so you can have multiple admin accounts.  We do not intend on adding functionality to add new admins with #1031 however, we felt that was beyond the scope of the pull request.  We just wanted to get it back to the current state with backend security.  We did lay the groundwork to make it possible though.

**Comment by satishc1** [comment]
@vetrivelan25 Not at this time.
