### ISSUE TITLE
What am i missing ?

### ISSUE THREAD

**Issue by roshanvc** [capitalone/Hygieia#1076]
Hi,

I am trying to setup the dashboard. I have built all the jar files. Below are the steps which i have done. 

1. Started Mongo DB
2. Started API
3. Started Jenkins Collector
4. Started UI

I was able to create a user and login to the User in the UI. I have created my own project/team dashboard. When i create one, its not getting reflecting back in the UI. The dashboard name is inserted into the DB though. Not able to see the dashboard names even if restart the UI.

What am i missing here ?

As per my understanding of the documentation, once i start all the above(DB,API,Collector and UI), i should be able to see the Jenkins information in the dashboard. 
What am i missing here? as i dont see any information or details about Jenkins in the dashboard. I am not sure if the Jenkins collector is talking to the API and API is passing on the information to the dashboard.

**Comment by tabladrum** [comment]
Two questions
1. Do you have a build performed in Jenkins recently (in past 14 days)
2. Do you see your Jenkins job in the drop down?

**Comment by roshanvc** [comment]
Do you have a build performed in Jenkins recently (in past 14 days)
- Yes
Do you see your Jenkins job in the drop down?
- No

**Comment by nireeshT** [comment]
@roshanvc - You see any errors in collector log? if yes, share the error log. Alternately check if collector is persisting Jenkins info to Mongo.

**Comment by satishc1** [comment]
@roshanvc Closed. Reopen if still an issue and provide error logs if any.
