### ISSUE TITLE
Jira collector error ERROR c.c.d.c.DefaultBitbucketClient - 404 Not Found for Commit\since

### ISSUE THREAD

**Issue by bimalvasan** [capitalone/Hygieia#1081]
I am getting 
`ERROR c.c.d.c.DefaultBitbucketClient - 404 Not Found:`
when query for 
`/commits?sha=master&since=2017-01-11T18:48Z`

I am using api/1.0

Thanks,
Bimal

**Comment by MarkRx** [comment]
What version of Bitbucket? Did you set git.product correctly?

**Comment by nitin1706** [comment]
please try with latest codebase. Open a new issue if it still exists.
