### ISSUE TITLE
Sonarqube Authentication

### ISSUE THREAD

**Issue by chethanbs** [capitalone/Hygieia#1085]
I am trying to pull the data from sonarqube to Hygieia dashboard.Sonarqube requires authentication.

Currently I am using the sonarqube URL in **application.properties** file.

could you please tell me how to make use of credentials and where to enter them?

will that be inside **application.properties** file? if yes then please share me the sample file so that i will make the changes accordingly.

**Comment by nireeshT** [comment]
@chethanbs  - refer  https://github.com/capitalone/Hygieia/issues/905

**Comment by chethanbs** [comment]
Thank you.it works
