### ISSUE TITLE
No data displayed on Jira widget after updating Scope.java and feature .java with Adittional parameter to collect Project Key

### ISSUE THREAD

**Issue by varundevopsid99** [capitalone/Hygieia#1096]
Hi Team, I was able to collect and display Jira data succesfully on hygieia Jira widget. i have updated the code to collect project key and it is able to collect it successfully and store it in mongodb but  on UI side it is failing to display the data for jira. please let me know if i need to any additional changes:

**Updated MongoDB:**
    "sProjectName": "Sample Scrum Project",
    "sProjectID": "10001",
    "sProjectKey": "SSP"

**Issue on UI side- view.js for Jira:**

Fails to at the below higlighted while fetching Sprint data :
if (isInIssuesArray(data.result[i].sNumber, issueCollection) === false) {
            issue = {
              sNumber: data.result[i].sNumber,
              sName: data.result[i].sName,
              sUrl: data.result[i].sUrl,
              changeDate: data.result[i].changeDate,
              sEstimate: data.result[i].sEstimate,
              sEstimateTime: data.result[i].sEstimateTime !== null ? (parseInt(data.result[i].sEstimateTime)/60).toString() : null,
              **sStatus: data.result[i].sStatus !== null ? data.result[i].sStatus.toLowerCase() : null**
            };

**Browser console error:**

bower.js:13113 TypeError: Cannot read property 'toLowerCase' of undefined
    at processSprintResponse (view.js:198)
    at view.js:79
    at processQueue (bower.js:14725)
    at bower.js:14741
    at Scope.$eval (bower.js:15977)
    at Scope.$digest (bower.js:15793)
    at Scope.$apply (bower.js:16082)
    at done (bower.js:11132)
    at completeRequest (bower.js:11322)
    at XMLHttpRequest.requestLoaded (bower.js:11263)

**Comment by MarkRx** [comment]
Issue occurs when 'Any' is selected for teams. Should get fixed with #1030

**Comment by varundevopsid99** [comment]
Thanks for the update @MarkRx , i will try the updated code...also wanted to add one more point, in my Jira i have not added the team tempo plugin and i have not created any teams. But on Hygieia UI side under teams dropdown it's picking up the projects name as team names which seems like odd behaviour.

So in my case i am getting same names under the project and team dropdown on Hygieia UI. Shouldn't team dropdown display only 'any' in dropdown in case i havent congigured any teams in Jira?

**Comment by MarkRx** [comment]
I Agree. We are disucssing that in #1030

**Comment by varundevopsid99** [comment]
I tested it and now it's displaying only 'any' in the team dropdown and all the data is coming up correct. thank you team.

**Comment by varundevopsid99** [comment]
@MarkRx hi mark! i want to modify the jira collector such that it collects data for more then one project depending upon the number of project id's supllied in mongodb rest api request, on what all files i might need to make changes if u can help, thanks.

**Comment by MarkRx** [comment]
It would be possible but you would have to wait for the changes to convert the dropdowns to selectize instead of ui-select (selectize should have a multi-select feature) and the refactor from #1030

**Comment by satishc1** [comment]
@varundevopsid99 Functionality merged in https://github.com/capitalone/Hygieia/pull/1137 Use latest codebase and follow cleanup instructions provided in PR.
