### ISSUE TITLE
Hygieia publisher results not visible in dashboard

### ISSUE THREAD

**Issue by evaldasou** [capitalone/Hygieia#1099]
Hey guys,

I have compiled and integrated Hygieia Jenkins plugin. 
Configured it, configured my project, tested that API access is reachable from Jenkins.

After build I am getting success message:

` "Hygieia: Published Build Complete Data. Response Code: 201. Response Value= 587e56fac9e77c000d08069f"`

In mongo database, `builds and collector_items collections` are not empty, - they have the data from jenkins.

However, in the dashboard, I am not able to configure deploy widget nor Delivery pipeline: 
it says : ` "No deployment job was found"`

Any ideas?

**Comment by evaldasou** [comment]
Everything seems good if so? :)

**Comment by tabladrum** [comment]
Hi @evaldasou builds show up in builds widget drop down. For deployment, publish deployment option. Are you using pipeline or standard job config?

**Comment by evaldasou** [comment]
Hi @tabladrum , I have used "Freestyle project" maybe that's an issue? 
Does it work only with "Pipeline" or "Multibranch Pipeline" ? 

Thanks!

**Comment by tabladrum** [comment]
Works with freestyle as well as pipeline. For freestyle, configure Hygiea publisher as post build action and select to publish deploy data. You will need an App Name to publish under (this is the one you will select in Hygieia deploy widget config drop down), an env name (whatever you want such as Dev, QA, Prod etc), a namespace, select which artifacts are being deployed (files under your workspace, supports wildcard) and optionally version number. Supply version number if the filename does not contain version number.

**Comment by evaldasou** [comment]
Thanks @tabladrum , but I followed all the examples and configured it exactly it says. I am getting Hygieia plugin success messages in Jenkins... getting data in mongo database collections... 
However, I'm not able to see/select this data from Dashboard UI.

I mean,is it still possible that something wrong with my configuration, even if I am getting success messages and data in mongo?

Thanks!

**Comment by tabladrum** [comment]
Can you paste a screen shot of the Hygieia UI config drop down? And the last about 20 lines of Jenkins build log.

**Comment by evaldasou** [comment]
Sure. If on Jenkins:

This is under build step:
![screen shot 2017-01-21 at 03 35 03](https://cloud.githubusercontent.com/assets/13851543/22170747/cad0fb70-df8a-11e6-9a73-8880d8c704f8.png)

This is under promotion step:
![screen shot 2017-01-21 at 03 35 31](https://cloud.githubusercontent.com/assets/13851543/22170753/d8c01068-df8a-11e6-8983-592461ac0040.png)

Jenkins log after the build:
`Archiving artifacts
Hygieia: Published Build Complete Data. Response Code: 201. Response Value= 5882549bc9e77c000d79edad
Hygieia Test Result Publisher - Looking for file pattern '/' in directory /opt/bitnami/apps/jenkins/jenkins_home/jobs/backend-api/workspace
Hygieia: Published Test Data. Nothing to publish
Finished: SUCCESS`

Hygieia UI:
![screen shot 2017-01-21 at 03 39 29](https://cloud.githubusercontent.com/assets/13851543/22170793/3f5a5694-df8b-11e6-9d5d-273314a0366f.png)

Thanks!

**Comment by satishc1** [comment]
@evaldasou Refer to https://github.com/capitalone/Hygieia/issues/884 for how to setup the deployment job. Reopen if still an issue.

**Comment by evaldasou** [comment]
@tabladrum @satishc1 - thanks guys, just wanted to ask, - does it work overal for non java projects?
My artifacts are not .jar files at all. What should I use for file name pattern and artifact group then?

Thanks!
