### ISSUE TITLE
Teamdash board has commit graph and stats but the same in not present in product dashboard

### ISSUE THREAD

**Issue by anandsit** [capitalone/Hygieia#1100]
I have have team dash board which correctly shows the commit stats and graph but when the same dashboard is included in the product dashboard, it does not show up any data against "commit" column

FYI: The same team dashboard also has "build"data and the same is correctly shown in product dashboard.

Any help is greatly appreciated

**Comment by Mahendra1260** [comment]
I have faced the similar issue with the deployment data. I can see the deployment data on team dashboard but the similar is missing on product dashboard

**Comment by MarkRx** [comment]
Might be hitting #804. 

You could try the dynamic pipeline by putting this in your api.properties file: 

> feature.dynamicPipeline=enabled

**Comment by Mahendra1260** [comment]
Tried adding the above property into my api properties.
Performed the deployed again via Jenkins and using curl command. Still no luck in the data display under Product dashboard whears it is clearly seen in Team Dashboard

**Comment by anandsit** [comment]
Again was browser cache issue!! 
it was working --> after upgrade did not work --> found to be browser cache issue
