### ISSUE TITLE
Cross-origin resource sharing error between api and ui

### ISSUE THREAD

**Issue by jshpopelka272** [capitalone/Hygieia#1103]
I'm trying to get Hygieia running in containers with Openshift. 

I have three separate pods: mongo, api, ui. The api layer is able to communicate with the mongo pod. 

The UI layer is running, but not able to connect to the api layer. In my Chrome browser console, I see this error:

> XMLHttpRequest cannot load http://api-hygieia.apps.cluster.local/api/dashboard. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://ui-hygieia.apps.cluster.local' is therefore not allowed access.

When I add the cross-origin resource sharing extension to my browser, they are able to connect. 

Is there a better solution for this so all users won't have to add the extension?

**Comment by tabladrum** [comment]
@amitmawkin please see.

**Comment by jshpopelka272** [comment]
Update: I was able to find a solution to this CORS filter issue.

By adding these four lines of code into the LoggingFilter.java file and running the maven build on the api layer, cross origin domains are accepted.

`httpServletResponse.addHeader("Access-Control-Allow-Origin", "*");
httpServletResponse.addHeader("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE");			httpServletResponse.addHeader("Access-Control-Allow-Headers", "Content-Type");
httpServletResponse.addHeader("Access-Control-Max-Age", "1");`

I'll be adding a pull request for this so others can avoid this issue.
