### ISSUE TITLE
Ability to Configure Widgets

### ISSUE THREAD

**Issue by amit1s** [capitalone/Hygieia#1105]
As a power user of Hygieia
I want to have the ability to configure widgets
So that I can tailor the Dashboard to different audiences
For example:
Engineers would most likely be interested in the entire DevOps details
Product Owners might only be interested in the Features and Quality Widgets
#890

**Comment by nitin1706** [comment]
@amit1s :  we have a configurable dashboard in latest codebase, we will also be supporting multiple widgets of same type soon.
