### ISSUE TITLE
Looks for support to update text color

### ISSUE THREAD

**Issue by eldojoseph** [capitalone/Hygieia#1109]
someone please guide me to update text color at product dashboard (all texts)? Also where can I update template names?

**Comment by varundevopsid99** [comment]
you can find the html and js template files under the templates folder in UI or just press ctrl+shift+R in case you have work space in eclipse and search for the templates by their names, also make sure to update the karma conf js in case you create a new template...to update the text color update the html tag with color property in product dashboard template html file.

**Comment by nireeshT** [comment]
@eldojoseph  - edit in product.less
