### ISSUE TITLE
Product Dashboard commit looks empty 

### ISSUE THREAD

**Issue by shilpsl1** [capitalone/Hygieia#1112]
Hi,

In the team dashboard Gitlab is integrated successfully and able to view in widget as well but Product dashboard shows only build result and not commit results. Below are the screen shots attached.

![3090a96c3d99a2c6](https://cloud.githubusercontent.com/assets/24657895/22166092/54cb7e3a-df2d-11e6-9d77-eeb036bf8041.jpg)
![3c641ff04c36a495](https://cloud.githubusercontent.com/assets/24657895/22166094/59ebfd86-df2d-11e6-96a2-e8b74fc35ea8.jpg)

**Comment by tabladrum** [comment]
Commits move from Commit to Build stage when the commits are built. An empty commit grid is actually a healthy one (from CI/CD pipeline perspective).

**Comment by shilpsl1** [comment]
Okay... Thank you
Is it like if the commit is not build will be shown in commit tab ??

**Comment by tabladrum** [comment]
That's right.

**Comment by satishc1** [comment]
@shilpsl1 Closed.
