### ISSUE TITLE
Unable to access jira instance hosted in a different network from jira collector hosted in another network machine

### ISSUE THREAD

**Issue by varundevopsid99** [capitalone/Hygieia#1115]
Hi Team,

There is a jira instance which is hosted on some other network. i am able to access the jira via my browser and hit all the rest api's and view data in json format but when i try to fetch the data from jira collector, it fails to fetch the information. is there any extra configuration that i might i need to do?

Following error coming in Jira log:

314 ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
java.lang.RuntimeException: java.net.SocketTimeoutException

**Comment by varundevopsid99** [comment]
I have checked with network team and they say all the necessary ports are open and can be accessed.

**Comment by satishc1** [comment]
@varundevopsid99 If you are able to access the jira instance url from your local laptop/machine, run the collector from your local laptop/machine. This should tell us whether your collector runs and your jira.properties is setup properly.

**Comment by varundevopsid99** [comment]
@satishc1 collector is working fine on local machine but when i try to collect data from a collector running on a machine on a different network i face this issue, have u hosted any collector across different network in ur case and done any additional setting?

**Comment by satishc1** [comment]
@varundevopsid99 Login to the machine where your jira collector is hosted and try to issue a curl command to your jira url. Also Is your url http or https ?

**Comment by satishc1** [comment]
@varundevopsid99 Closed. Reopen if still an issue.
