### ISSUE TITLE
Getting Maven build failure

### ISSUE THREAD

**Issue by narayann0929** [capitalone/Hygieia#1117]
I am getting build failure. Can someone help?

[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ Rest ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\Neha\workspace\Rest\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ Rest ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ Rest ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-war-plugin:2.2:war (default-war) @ Rest ---
[INFO] Packaging webapp
[INFO] Assembling webapp [Rest] in [C:\Users\Neha\workspace\Rest\target\Rest-0.0.1-SNAPSHOT]
[INFO] Processing war project
[INFO] Copying webapp resources [C:\Users\Neha\workspace\Rest\src\main\webapp]
[INFO] Webapp assembled in [2468 msecs]
[INFO] Building war: C:\Users\Neha\workspace\Rest\target\Rest-0.0.1-SNAPSHOT.war
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20.621 s
[INFO] Finished at: 2017-01-23T22:32:20-05:00
[INFO] Final Memory: 13M/72M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-war-plugin:2.2:war (default-war) on project Rest: Error assembling WAR: webxml attribute is required (or pre-existing WEB-INF/web.xml if executing in update mode) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by tabladrum** [comment]
Are you building Hygieia project? Doesn't look like it.

**Comment by narayann0929** [comment]
It's a restful webservice project using jersey .

**Comment by satishc1** [comment]
@narayann0929 Stackoverflow would be a good forum for general questions on maven. As for the build error above this line tells you why "webxml attribute is required (or pre-existing WEB-INF/web.xml if executing in update mode)"
