### ISSUE TITLE
Product dashboard questions

### ISSUE THREAD

**Issue by anjana83** [capitalone/Hygieia#1118]
Hi,

Thanks for support.
I have some questions here. Can you please help me here..

1.  On product dashboard page, it displays data for commit, build, dev,qa, int, perf... prod.
     Many time team deploys code in QA and Perf at the same time.
     Also, some time they really skip deployment in INT environment.. 
     how does product dash board behave in such cases.. or its always compulsory to follow sequence of   deployments.

2. Jenkin plugin push build and deployment data to Hygieia into build, artifact and environment_compontents collections.
   Do we still need run any deployment collector?

thanks so much.

**Comment by tabladrum** [comment]
1. We are refactoring the pipeline to allow more flexible way to set up the stages and name them
2. With Jenkins push, you dont need collectors.

**Comment by satishc1** [comment]
@anjana83 closed.
