### ISSUE TITLE
Sonar analysis in Hygieia to Sonarqube Server

### ISSUE THREAD

**Issue by prvnsinghal** [capitalone/Hygieia#1122]
Hi there,
Is it possible to go to Sonarqube Server from the sonar Analysis in Hygieia Dashboard? like when we see the build of Jenkins job and click on the build then it redirect us to Jenkins Server.

Regards,
Praveen Kumar

**Comment by tabladrum** [comment]
The UI does not have a link to click. Though it's pretty straight forward to do it. Will take this as an enhancement request.

**Comment by Mpluya** [comment]
@brennanananan is already working on this. There should be a PR on this soon. Thanks!
