### ISSUE TITLE
Problems getting Hygieia UI under Tomcat to connect to API

### ISSUE THREAD

**Issue by amayesthing** [capitalone/Hygieia#1127]
I am hoping someone can me out.  I think I am missing something very basic.  

I have Hygieia set up on a system and can run each piece correctly using the gulp
serve.  This means the API comes and connects to mongod and the UI launches under
gulp and I can access the dashboard through the UI interface.   I have been asked to
get the UI up under Tomcat rather than gulp serve.  To do this I set up Tomcat on the
same system, changed the port to 8090 so it did not conflict with the API Tomcat instance
and then moved the UI dist folder under the Tomcat webapps folder (and renamed it to
Hygieia).  Now, if I access Tomcat on that system and tell it specifically to bring up Hygieia .....
                                        localhost:8090/Hygieia
the login page appears but the API Connectivity shows no connection.

I have seen that in the gulpfile.js file, a proxy is set up to point to localhost:8080 where the 
instance of the API Tomcat would be.  I thought that is what I need to add to the start up of 
my instance of Tomcat but so far everything I have tried (adding proxy elements to both the
catalina.sh and to the JAVA_OPT in the catalina.properties files) does not work. 

I have looked through numerous other posts to try and find nuggets that I might be able
to look into to help me crack this nut - one post asked the submitter for the UI log files.  I
have not been able to find these on my system and I am pretty sure they might provide
some insight.

At this point I am thinking I am making this much more difficult than it has to be.  Any help
that anyone might be able to provide would be greatly appreciated.

**Comment by satishc1** [comment]
@amayesthing You can use apache httpd instead of tomcat and refer to   https://github.com/capitalone/Hygieia/issues/895

**Comment by amayesthing** [comment]
Thank you @satishc1 
I had looked into that because the issue that I cited above referring to the UI log files #1019 also requested details on the connection in the httpd conf.  I appreciate your suggestion and will take it back to the team to see if that would meet everyone's needs.  I would like to keep this open until I get concurrence from the team just in case anyone has a clever way to get it working under Tomcat.  Thanks again.

**Comment by spyndi** [comment]
@amayesthing @satishc1 

I got this working by deploying the Hygieia API within the Tomcat container. Basically, the UI and the API are deployed within Tomcat and all the collectors are running as a stand-alone java process. It works good and also provides an opportunity to scale-up & load balance APIs, if needed.

Let me know if you are interested in this deployment, I can document the changes (2 changes) and will send it out to you.

**Comment by amayesthing** [comment]
@spyndi 

Wow - thank you.  Yes I am interested in seeing how to set that up.  That is very helpful.  Please send it to me when you get the chance.  Thank you!!

**Comment by spyndi** [comment]
@amayesthing 

You are welcome! Here it is..

1. Build the Hygieia API project as a WAR artifact instead of JAR. i.e, Change the packaging to war in API project pom.xml, like below:
`<packaging>war</packaging>`
and re-build the API project.

2. Deploy the api*.war file in Tomcat.

3. Hygieia API requires the "dashboard.properties" file for MongoDB connectivity. To set this up with in Tomcat container, do the following:
       - Add a CATALINA_OPTS variable in Catalina.bat (or. sh under Linux) file like below (update the path based on your environment):
         `set CATALINA_OPTS="-Dspring.config.location=file:C:\DevOps\HygieiaApi\dashboard.properties"`

   Note : I added the above variable right below this line:
           :java_dir_displayed
           echo Using CLASSPATH:       "%CLASSPATH%"
           set CATALINA_OPTS="-Dspring.config.location=file:C:\DevOps\HygieiaApi\dashboard.properties"

Restart your Tomcat server. You should be able to run the UI that should connect to your API deployed within Tomcat successfully. Try it out!

**Comment by satishc1** [comment]
@spyndi thanks.

**Comment by amayesthing** [comment]
Thanks @spyndi - I appreciate your help - I have not tried this yet but it looks straight forward to me and I think it will resolve our problem.  Thank you for closing this issue.

**Comment by anuragmishracrest** [comment]
@spyndi why dashboard.properties is required the same mongo's configuration is already present in application.properties

**Comment by nireeshT** [comment]
@anuragmishracrest  - both are same, it is just how you name the properties file.
