### ISSUE TITLE
Scheduling collectors

### ISSUE THREAD

**Issue by eldojoseph** [capitalone/Hygieia#1132]
I am trying to schedule collector to fetch data everyday at 6pm. But it is failing with below error. Could someone help me?

Caused by: java.lang.IllegalArgumentException: Incrementer delta must be 1 or higher: '0/0' in expression "0 0/0 18 * * *"

**Comment by Mpluya** [comment]
Try "0 * 18 * * *". 
Here's the reference -- http://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/scheduling/support/CronSequenceGenerator.html

**Comment by satishc1** [comment]
@Mpluya thanks.

**Comment by eldojoseph** [comment]
@Mpluya Thank you.
