### ISSUE TITLE
Password / Documentation

### ISSUE THREAD

**Issue by benjaminwootton** [capitalone/Hygieia#1136]
I'm having problems getting the frontend and API talking due to the password.

Master API contains:

[centos@devopsmetrics0 Hygieia]$ more api/target/classes/application.properties
dbname=dashboarddb
dbusername=dashboarduser
dbpassword=ENC(C9PLVDJ/1OfkT/3jvC/wEB20R1XPJtg9)
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
server.contextPath=/api
server.port=8080

But the documentation says to setup Mongo with db / dbpass as the user.

I've tried reverse engineering the encrypted password, or setting a new password in Mongo, but the Java stuff for creating an encrypted password hangs.

Any clear steps on how to get the two talking, or can we update the repo so it's easier to get started?

**Comment by benjaminwootton** [comment]
If I do a clean checkout, docker build and docker-compose run, api service fails with this:

aused by: java.lang.IllegalArgumentException: Password cannot be set empty
	at org.jasypt.commons.CommonUtils.validateIsTrue(CommonUtils.java:150)
	at org.jasypt.encryption.pbe.StandardPBEByteEncryptor.resolveConfigurationPassword(StandardPBEByteEncryptor.java:792)

I think because JASYPT_ENCRYPTOR_SECRET is not set.  There isnt much mention of this in the docs either.

**Comment by benjaminwootton** [comment]
Related - https://github.com/capitalone/Hygieia/issues/796

**Comment by satishc1** [comment]
@benjaminwootton 
Refer to api module readme updated by @Mpluya 
https://github.com/capitalone/Hygieia/tree/master/api

Via docker, pass as an environment variable docker run -t -p 8080:8080 -v ./logs:/hygieia/logs -e "SPRING_DATA_MONGODB_HOST=127.0.0.1" -e "JASYPT_ENCRYPTOR_SECRET=hygieiasecret" -i hygieia-api:latest then pass the environment variable as a Spring boot system property java -Djasypt.encryptor.password=$JASYPT_ENCRYPTOR_SECRET -jar api.jar --spring.config.location=dashboard.properties

**Comment by Mpluya** [comment]
@benjaminwootton you could also just pass an environment variable called JASYPT_ENCRYPTOR_PASSWORD if you dont want to update your Dockerfile. The command would be : docker run -t -p 8080:8080 -v ./logs:/hygieia/logs -e "SPRING_DATA_MONGODB_HOST=127.0.0.1" -e "JASYPT_ENCRYPTOR_PASSWORD=hygieiasecret" -i hygieia-api:latest

**Comment by benjaminwootton** [comment]
That works thanks - the password 'hygieiasecret' is the missing piece of info - thanks!  
Some cleanup of the docs would really help with adoption of Hygieia.  I've tried a few times but havent managed to get it started yet.

**Comment by satishc1** [comment]
@benjaminwootton @Mpluya Thanks. All help is welcome.

**Comment by MarkRx** [comment]
#1207
