### ISSUE TITLE
how to create/record new Soap based webservice using Lisa/Dev test

### ISSUE THREAD

**Issue by srivi1225** [capitalone/Hygieia#1140]
Hi All,

I am new to Devtest and trying to record a new soap based web service using lisa to virtualize my service in dev environment. I tried to record using  Devtest 9.1 tool( not portal) record WSVI. Can some one please guide me on this or provide some videos.

Thank you
Sri

**Comment by tabladrum** [comment]
@srivi1225 Not sure if you posted this in here by mistake.

**Comment by srivi1225** [comment]
yes, i posted this by mistake
