### ISSUE TITLE
How to configure the team dashboards widgets based on the code committing version number

### ISSUE THREAD

**Issue by princevijayakumar** [capitalone/Hygieia#1141]
Hi All,
         How to configure the team dashboard widgets (Jenkins, Sonar, Bitbucket and Version one) based on the version number which we are building in Jenkins(ex: 0.0.1-SNAPSHOT,0.0.5-RELEASE). Can some one please guide me on this.

Thanks & Reagards,
Prince Vijayakumar

**Comment by satishc1** [comment]
@princevijayakumar Closed. You'll need to run the collectors in question and populate the data which can then be selected in the team dashboard. Refer to http://capitalone.io/Hygieia for how to get started.
