### ISSUE TITLE
Can't build Jenkins plugin

### ISSUE THREAD

**Issue by svscorp** [capitalone/Hygieia#1142]
Hello,

Trying to follow instructions for getting hpi for Jenkins.

1. Checked out at tag "Hygieia-2.0.4".
2. cd to "core", then mvn clean install. Success.
3. cd to hygieia-jenkins-plugin, then mvn clean package. Failure.

````
[ERROR] Failed to execute goal on project hygieia-publisher: Could not resolve dependencies for project org.jenkins-ci.plugins:hygieia-publisher:hpi:1.5-SNAPSHOT: Failed to collect dependencies for [commons-httpclient:commons-httpclient:jar:3.1 (compile), 
org.json:json:jar:20131018 (compile), 
junit:junit:jar:4.10 (test), 
commons-codec:commons-codec:jar:1.10 (test), 
log4j:log4j:jar:1.2.9 (provided), 
commons-logging:commons-logging:jar:1.0.4 (provided), 
commons-io:commons-io:jar:2.4 (compile), net.java.dev.jna:jna:jar:3.2.2 (compile), com.fasterxml.jackson.core:jackson-databind:jar:2.7.0 (compile), 
org.codehaus.jackson:jackson-core-asl:jar:1.9.13 (compile), 
org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13 (compile), 
javax.validation:validation-api:jar:1.1.0.Final (compile), org.apache.commons:commons-lang3:jar:3.3.2 (compile), com.capitalone.dashboard:core:jar:2.0.4-SNAPSHOT (compile), org.apache.httpcomponents:httpcore:jar:4.4 (compile), 
org.apache.httpcomponents:httpclient:jar:4.5.1 (compile), 
org.jenkins-ci.plugins:git:jar:2.5.0 (compile), 
org.jenkins-ci.plugins:multiple-scms:jar:0.6 (compile),
org.jenkins-ci.plugins:subversion:jar:2.6 (compile), 
org.tmatesoft.svnkit:svnkit:jar:1.8.11 (compile),
 org.jenkins-ci.main:jenkins-war:war:1.567 (test), 
org.jenkins-ci.main:jenkins-core:jar:1.567 (provided), 
org.jenkins-ci.main:jenkins-test-harness:jar:1.567 (test), 
javax.servlet:servlet-api:jar:2.4 (provided), 
org.codehaus.mojo:animal-sniffer-annotations:jar:1.9 (provided?)]: Failed to read artifact descriptor for com.capitalone.dashboard:core:jar:2.0.4-SNAPSHOT: Failure to find com.capitalone.dashboard:Hygieia:pom:2.0.4-SNAPSHOT in http://repo.jenkins-ci.org/public/ was cached in the local repository, resolution will not be reattempted until the update interval of repo.jenkins-ci.org has elapsed or updates are forced -> [Help 1]
[ERROR]
````

What am I doing wrong? Other projects are building normally.

````
Apache Maven 3.0.5
Java version: 1.8.0_45
````

**Comment by tabladrum** [comment]
Can you try 2.0.5?
Also, are you behind a corporate proxy?

**Comment by tinabear** [comment]
I tried with latest code:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project hygieia-publisher: Compilation failure: Compilation failure:
[ERROR] /home/dxiong/Hygieia/hygieia-jenkins-plugin/src/main/java/hygieia/builder/ArtifactBuilder.java:[97,20] cannot find symbol
[ERROR] symbol:   method setArtifactModule(java.lang.String)
[ERROR] location: variable bac of type com.capitalone.dashboard.request.BinaryArtifactCreateRequest
[ERROR] /home/dxiong/Hygieia/hygieia-jenkins-plugin/src/main/java/hygieia/builder/ArtifactBuilder.java:[98,20] cannot find symbol

**Comment by satishc1** [comment]
@tinabear Refer to https://github.com/capitalone/Hygieia/issues/946 . Is the plugin pom <version>2.0.5-SNAPSHOT</version> ?

**Comment by tinabear** [comment]
Sorry, I just made a clean build. It works.

**Comment by satishc1** [comment]
@tinabear Good to know its working. @svscorp Please try latest codebase. Reopen if still an issue.

**Comment by vkosilko** [comment]
Looks like I have same issue:
```
[ERROR] Failed to execute goal on project hygieia-publisher: Could not resolve dependencies 
for project org.jenkins-ci.plugins:hygieia-publisher:hpi:2.0.5-SNAPSHOT: Failure to find 
com.capitalone.dashboard:core:jar:2.0.4-SNAPSHOT in http://repo.jenkins-ci.org/public/
was cached in the local repository, resolution will not be reattempted until the update 
interval of repo.jenkins-ci.org has elapsed or updates are forced
```
pom.xml in core and hygieia-jenkins-plugin folder is fine: 
  ```
  <version>2.0.5-SNAPSHOT</version>

**Comment by satishc1** [comment]
@vkosilko change the core dependency to 2.0.5 in your plugin pom.xml and it'll work.

**Comment by rohitthe** [comment]
@tabladrum yes, I am behind corporate proxy and getting below issues.

[INFO] com.capitalone.dashboard:nexus-iq-collector ........ SUCCESS [  9.149 s]
[INFO] Hygieia Publisher Plugin ........................... FAILURE [ 30.054 s]
[INFO] com.capitalone.dashboard:UI ........................ SKIPPED
[INFO] com.capitalone.dashboard:ui-tests .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:17 min
[INFO] Finished at: 2018-02-26T16:53:24+05:30
[INFO] Final Memory: 154M/486M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project hygieia-publisher: Could not resolve d
ependencies for project org.jenkins-ci.plugins:hygieia-publisher:hpi:2.0.5-SNAPS
HOT: Could not transfer artifact org.jenkins-ci.main:jenkins-core:jar:1.609.2 fr
om/to repo.jenkins-ci.org (http://repo.jenkins-ci.org/public/): Access denied to
: http://repo.jenkins-ci.org/public/org/jenkins-ci/main/jenkins-core/1.609.2/jen
kins-core-1.609.2.jar , ReasonPhrase:Forbidden. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :hygieia-publisher

Please help...
