### ISSUE TITLE
Gitlab collector does not show data when it was not running

### ISSUE THREAD

**Issue by shilpsl1** [capitalone/Hygieia#1144]
I had stopped all collectors and committed the code, build in Jenkins.
And then I started the collectors. 
What I observed is, Jenkins collector is picking up the data, which had built even when collector was not running after it started.
But GitLab collector is not picking up the data which was committed when collector was not running,  even after the collector started running.
Is this how it works or is it an issue ?

**Comment by shilpsl1** [comment]
Its not too old, Just for checking what happens if we stop, commit and then start.
I stopped it. I did commit, and then started immediately but  it does not show any update.
Only when Collector is running is it updating Dashboard.
whereas If we do samething for jenkins, it has updated the builds which was done when collector was not running, after collector started.

**Comment by satishc1** [comment]
@shilpsl1 Try with https://github.com/capitalone/Hygieia/pull/1149 . Re-save the config to reset the lastUpdated value on the gitlab collector_item. Then you can try your tests and see if the problem still happens. If it does, reopen the issue.

**Comment by shilpsl1** [comment]
@satishc1 
Sorry I was not able to get it, what does re-save config mean ? could you please explain.

**Comment by satishc1** [comment]
@shilpsl1 Open the gitlab config in your dashboard. Make some changes and save it. Open it back up and change the values back to what you need, click save.

**Comment by shilpsl1** [comment]
okay I will try, thanks!!!
