### ISSUE TITLE
API Startup fails when following documented instructions

### ISSUE THREAD

**Issue by rirl** [capitalone/Hygieia#1152]
Following the instructions https://github.com/capitalone/Hygieia/tree/master/api exactly as recorded there and having performed all the previous steps (including using robomongo to validate the DB setup) simply fails, reporting: 

Encryption configuration property missing: jasypt.encryptor.password

Here is the command I executed:
java -jar api.jar --spring.config.location=dashboard.properties -Djasypt.encryptor.password=hygieiasecret

**Comment by avadhmr** [comment]
Try running java -jar api.jar --spring.config.location=dashboard.properties  only
Also may be try absolute path for dashboard.properties

**Comment by satishc1** [comment]
@rirl As suggested by @avadhmr If you aren't using encrypted properties, remove -Djasypt.encryptor.password=hygieiasecret
And full path to dashboard.properties will help.

**Comment by satishc1** [comment]
@rirl Closed. Reopen if still an issue.
