### ISSUE TITLE
Does jenkins collector update the existing fetched jenkins data in mongoDB? 

### ISSUE THREAD

**Issue by varundevopsid99** [capitalone/Hygieia#1153]
I am able fetch and store the running status of a job in Mongodb but even after the job has completed running, the status is not updated in mongodb. can you let me know does the jenkins collector update the existing jenkins job data in mongodb?

**Comment by nireeshT** [comment]
@varundevopsid99  - Collectors run to fetch data depends on the desired cron settings in properties and yes data will be updated in Mongo. Give it some time to pull data, if you did not see the data refresh, paste the debug log for Jenkins collector.

**Comment by nireeshT** [comment]
@varundevopsid99  - closing issue. Reopen if not resolved.
