### ISSUE TITLE
Add Pulls and Issues to Commits widget

### ISSUE THREAD

**Issue by thummalapalli** [capitalone/Hygieia#1155]
Using Hygieia as one tool across your enterprise for single view into your env, you can measure your progress for SDLC for your projects projects hosted on GIT. Metrics for Pulls and Issues can be added to the commits graph to show how the Pull Requests( code contributions) and Issues (ideas that help shape your project) are flowing in - and counts of developers committing, requesting a Pull and creating issues - would help us understand how popular your repo is.

Once the collector runs scanning GIT for all Pulls and Issues along with Commits as it does currently, it leaves the entries for the developers LOB/Department heads etc as TBD items so you can implement a local collector for your enterprise that scans for these and updates the fields by accessing your “HR” data sources.

Code changes required would include API, githubcollector and UI.

**Comment by nitin1706** [comment]
Merged
