### ISSUE TITLE
Product Dashboard issue

### ISSUE THREAD

**Issue by shilpsl1** [capitalone/Hygieia#1165]
Hi, 
I have configured the deploy widget and  in pipeline tab i have added the environment and added the team dashboard to product dashboard.
I can see build details but I see empty in product dashboard view of pipeline environment. Am I missing anything ?
Attached are screen shots for reference, please help on this.
![675342194d85bca8](https://cloud.githubusercontent.com/assets/24657895/22840828/0e348a40-ef9d-11e6-9b8a-8cce73eaa0d6.jpg)
![44d3d91df6c90568](https://cloud.githubusercontent.com/assets/24657895/22840835/14417c86-ef9d-11e6-8152-7c965c71795c.jpg)
![103e214b9b6a8885](https://cloud.githubusercontent.com/assets/24657895/22840840/1992f02a-ef9d-11e6-950e-2e2b43a7ec2d.jpg)

**Comment by tabladrum** [comment]
What is your deployment tool?

**Comment by shilpsl1** [comment]
Urbancode deploy

**Comment by nireeshT** [comment]
@shilpsl1  - update to latest code and try out below steps 

1) configure build widget, repo widget and deploy widget  and run collectors.
2) Configure pipeline with customized names for all environments deployed.
3) add team dashboard to product dashboard. 
Product dashboard should display COMMIT, BUILD and configured stages.

**Comment by shilpsl1** [comment]
@nireeshT 
Tried by using latest code,
1. I got the error : PhantomJS not found on PATH
    So I copied old code Hygieia/UI/node_modules folder to new code. Then build was success.
2. I followed the the above 3 steps
    But I donot see anything in Product dashboard. Jenkins and gitlab is also configured.
    Also even though deployment was success it is showing failure.

![390ec0aa71aa60a8](https://cloud.githubusercontent.com/assets/24657895/23435513/ade86692-fdd5-11e6-8f19-ed0b4c692698.jpg)
![5ce052bdb2d042ac](https://cloud.githubusercontent.com/assets/24657895/23435521/b2fb5180-fdd5-11e6-9e76-48af1e63e588.jpg)
![1598cd43daefe974](https://cloud.githubusercontent.com/assets/24657895/23435601/dd716918-fdd5-11e6-9ba0-12a5e0902334.jpg)

![291f42f4fb47613c](https://cloud.githubusercontent.com/assets/24657895/23435556/c06fadc0-fdd5-11e6-9099-f4bb2ee23f1b.jpg)

**Comment by nireeshT** [comment]
@shilpsl1  - when is your last commit in your repo. will you be able to do one more commit and build/deploy after you configured pipeline and run collectors to see if data is polled on product dashboard.

**Comment by shilpsl1** [comment]
@nireeshT 
Just did a new commit, build, deploy but no fun 
![238bf20533f8bcf9](https://cloud.githubusercontent.com/assets/24657895/23471586/db919986-fe77-11e6-829f-ff23e47844a8.jpg)
![4341bf67f34a4183](https://cloud.githubusercontent.com/assets/24657895/23471590/de1905ae-fe77-11e6-8502-80843c9bec9c.jpg)
![345a152df924c54f](https://cloud.githubusercontent.com/assets/24657895/23471591/e054f5ee-fe77-11e6-839a-9306b50d03b5.jpg)

**Comment by nireeshT** [comment]
@shilpsl1  - paste here JSON response coming from pipeline for this dashboard, mask the confidential information if necessary.

**Comment by shilpsl1** [comment]
@nireeshT 
Please find below JSON : 
http://0.0.0.0:3000/api/dashboard/58b5e6460b2f3878d2207f78

{"id":"58b5e6460b2f3878d2207f78","template":"product-dashboard","title":"PDTestprod","widgets":[{"id":"58b5e64c0b2f3878d2207f79","name":"product","componentId":"58b5e6460b2f3878d2207f77","options":{"teams":[{"collectorItemId":"58b6f8910b2f383451a039ee","name":"TestProdDash"}],"id":"product0"}}],"owner":"shilpsl1","type":"Product","application":{"name":"Sample","components":[{"id":"58b5e6460b2f3878d2207f77","name":"Sample","collectorItems":{"Product":[{"id":"58b6f8910b2f383451a039ee","description":"TestProdDash","enabled":true,"pushed":false,"collectorId":"58b0c25d0b2f3841daf4dced","lastUpdated":0,"options":{"dashboardId":"58b6f8910b2f383451a039ed"},"collector":{"id":"58b0c25d0b2f3841daf4dced","name":"Product","collectorType":"Product","enabled":true,"online":true,"lastExecuted":0}}]}}]}}

**Comment by shilpsl1** [comment]
@nireeshT 
This is from team dashboard, pipeline tab
http://10.107.100.191:3000/api/dashboard/58b6f8910b2f383451a039ed

{"id":"58b6f8910b2f383451a039ed","template":"capone","title":"TestProdDash","widgets":[{"id":"58b6f89d0b2f383451a039ef","name":"build","componentId":"58b6f8910b2f383451a039ec","options":{"buildDurationThreshold":3,"id":"build0","consecutiveFailureThreshold":5}},{"id":"58b6f8a40b2f383451a039f0","name":"deploy","componentId":"58b6f8910b2f383451a039ec","options":{"id":"deploy0","ignoreRegex":"","aggregateServers":false}},{"id":"58b6f8da0b2f383451a039f1","name":"repo","componentId":"58b6f8910b2f383451a039ec","options":{"id":"repo0","scm":{"name":"Gitlab","value":"Gitlab"},"branch":"master","userID":"SfcpxAxtusgrZZKT","url":"http://0.0.0.0/shilpsl1/Dashboard_Repo.git"}},{"id":"58b6f8ea0b2f383451a039f2","name":"pipeline","options":{"mappings":{"Env1":"test_env"},"id":"pipeline0","prod":"","order":{"0":"Env1","1":""}}}],"owner":"shilpsl1","type":"Team","application":{"name":"Sample","components":[{"id":"58b6f8910b2f383451a039ec","name":"Sample","collectorItems":{"Build":[{"id":"58b116580b2f3842b44d7f85","description":"Dashboard_Build","enabled":true,"pushed":false,"collectorId":"58b116580b2f3842b44d7f84","lastUpdated":0,"options":{"jobName":"Dashboard_Build","jobUrl":"http://0.0.0.0:8000/jenkins/job/Dashboard_Build/","instanceUrl":"http://0.0.0.0:8000/jenkins"},"collector":{"id":"58b116580b2f3842b44d7f84","name":"Hudson","collectorType":"Build","enabled":true,"online":true,"lastExecuted":1488397560072}}],"Deployment":[{"id":"58b116590b2f384255157b76","description":"Sample_App_Deploy","enabled":true,"pushed":false,"collectorId":"58b116580b2f384255157b75","lastUpdated":0,"options":{"applicationId":"7f7032e9-fb5c-4f62-ad7b-55295a1a5bf0","applicationName":"Sample_App_Deploy","instanceUrl":"https://0.0.0.0:8443"},"collector":{"id":"58b116580b2f384255157b75","name":"UDeploy","collectorType":"Deployment","enabled":true,"online":true,"lastExecuted":1488397500258}}],"SCM":[{"id":"58b117750b2f38413edd44c7","enabled":true,"pushed":false,"collectorId":"58b1161c0b2f3843063f3fee","lastUpdated":0,"options":{"scm":"Gitlab","branch":"master","userID":"SfcpxAxtusgrZZKT","url":"http://0.0.0.0/shilpsl1/Dashboard_Repo.git"},"collector":{"id":"58b1161c0b2f3843063f3fee","name":"Gitlab","collectorType":"SCM","enabled":true,"online":true,"lastExecuted":1488397620066}}]}}]}}

**Comment by nireeshT** [comment]
@shilpsl1  - send me a private message in gitter.im with your google id and time for screen share.

**Comment by shilpsl1** [comment]
{ "_id" : ObjectId("58b117840b2f3843063f3fef"), "_class" : "com.capitalone.dashboard.model.Commit", "collectorItemId" : ObjectId("58b117750b2f38413edd44c7"), "timestamp" : NumberLong("1488000900948"), "scmUrl" : "http://10.107.100.145/shilpsl1/Dashboard_Repo.git", "scmBranch" : "master", "scmRevisionNumber" : "c43a08d5fb6edb81d9c852d683f766c5ff5336f6", "scmCommitLog" : "commit 19\n", "scmAuthor" : "shilpa", "scmCommitTimestamp" : NumberLong("1487976586000"), "numberOfChanges" : NumberLong(1) }
{ "_id" : ObjectId("58b117850b2f3843063f3ff0"), "_class" : "com.capitalone.dashboard.model.Commit", "collectorItemId" : ObjectId("58b117750b2f38413edd44c7"), "timestamp" : NumberLong("1488000900948"), "scmUrl" : "http://10.107.100.145/shilpsl1/Dashboard_Repo.git", "scmBranch" : "master", "scmRevisionNumber" : "9a4309e125cbaa425e62795f8c6e71ca8899fb6f", "scmCommitLog" : "commit 18\n", "scmAuthor" : "shilpa", "scmCommitTimestamp" : NumberLong("1487973566000"), "numberOfChanges" : NumberLong(1) }
{ "_id" : ObjectId("58b117850b2f3843063f3ff1"), "_class" : "com.capitalone.dashboard.model.Commit", "collectorItemId" : ObjectId("58b117750b2f38413edd44c7"), "timestamp" : NumberLong("1488000900949"), "scmUrl" : "http://10.107.100.145/shilpsl1/Dashboard_Repo.git", "scmBranch" : "master", "scmRevisionNumber" : "9305f48bebcf0525d145f6fca197f37c5e458dd2", "scmCommitLog" : "commit 17\n", "scmAuthor" : "shilpa", "scmCommitTimestamp" : NumberLong("1487972987000"), "numberOfChanges" : NumberLong(1) }
{ "_id" : ObjectId("58b117850b2f3843063f3ff2"), "_class" : "com.capitalone.dashboard.model.Commit", "collectorItemId" : ObjectId("58b117750b2f38413edd44c7"), "timestamp" : NumberLong("1488000900949"), "scmUrl" : "http://10.107.100.145/shilpsl1/Dashboard_Repo.git", "scmBranch" : "master", "scmRevisionNumber" : "d122b3f20eb038fa3db1aea633d708b43a9bc9cb", "scmCommitLog" : "commit 16\n", "scmAuthor" : "shilpa", "scmCommitTimestamp" : NumberLong("1487972005000"), "numberOfChanges" : NumberLong(1) }
{ "_id" : ObjectId("58b117850b2f3843063f3ff3"), "_class" : "com.capitalone.dashboard.model.Commit", "collectorItemId" : ObjectId("58b117750b2f38413edd44c7"), "timestamp" : NumberLong("1488000900949"), "scmUrl" : "http://10.107.100.145/shilpsl1/Dashboard_Repo.git", "scmBranch" : "master", "scmRevisionNumber" : "ecfdce8166d176a20e74e40279fcfc2303cb2bcb", "scmCommitLog" : "commit 15\n", "scmAuthor" : "shilpa", "scmCommitTimestamp" : NumberLong("1487963762000"), "numberOfChanges" : NumberLong(1) }
{ "_id" : ObjectId("58b117850b2f3843063f3ff4"), "_class" : "com.capitalone.dashboard.model.Commit", "collectorItemId" : ObjectId("58b117750b2f38413edd44c7"), "timestamp" : NumberLong("1488000900949"), "scmUrl" : "http://10.107.100.145/shilpsl1/Dashboard_Repo.git", "scmBranch" : "master", "scmRevisionNumber" : "5c846ec71ff2609bc0d5903b5b5922b7737435c2", "scmCommitLog" : "commit 14\n", "scmAuthor" : "shilpa", "scmCommitTimestamp" : NumberLong("1487273109000"), "numberOfChanges" : NumberLong(1) }
{ "_id" : ObjectId("58b117850b2f3843063f3ff5"), "_class" : "com.capitalone.dashboard.model.Commit", "collectorItemId" : ObjectId("58b117750b2f38413edd44c7"), "timestamp" : NumberLong("1488000900950"), "scmUrl" : "http://10.107.100.145/shilpsl1/Dashboard_Repo.git", "scmBranch" : "master", "scmRevisionNumber" : "53dff777a344df43ef6852bdc9d7ad9d669f8ca8", "scmCommitLog" : "commit 13\n", "scmAuthor" : "shilpa", "scmCommitTimestamp" : NumberLong("1487272242000"), "numberOfChanges" : NumberLong(1) }
{ "_id" : ObjectId("58b117850b2f3843063f3ff6"), "_class" : "com.capitalone.dashboard.model.Commit", "collectorItemId" : ObjectId("58b117750b2f38413edd44c7"), "timestamp" : NumberLong("1488000900950"), "scmUrl" : "http://10.107.100.145/shilpsl1/Dashboard_Repo.git", "scmBranch" : "master", "scmRevisionNumber" : "132050c78f952ae5231abc867693896db7931be4", "scmCommitLog" : "commit 13\n", "scmAuthor" : "shilpa", "scmCommitTimestamp" : NumberLong("1487087495000"), "numberOfChanges" : NumberLong(1) }
{ "_id" : ObjectId("58b117850b2f3843063f3ff7"), "_class" : "com.capitalone.dashboard.model.Commit", "collectorItemId" : ObjectId("58b117750b2f38413edd44c7"), "timestamp" : NumberLong("1488000900954"), "scmUrl" : "http://10.107.100.145/shilpsl1/Dashboard_Repo.git", "scmBranch" : "master", "scmRevisionNumber" : "ce597008c926df4f208fe78878b7559045c9b4ff", "scmCommitLog" : "commit 12\n", "scmAuthor" : "shilpa", "scmCommitTimestamp" : NumberLong("1487022891000"), "numberOfChanges" : NumberLong(1) }
{ "_id" : ObjectId("58b11acc0b2f3843063f3ff8"), "_class" : "com.capitalone.dashboard.model.Commit", "collectorItemId" : ObjectId("58b117750b2f38413edd44c7"), "timestamp" : NumberLong("1488001740064"), "scmUrl" : "http://10.107.100.145/shilpsl1/Dashboard_Repo.git", "scmBranch" : "master", "scmRevisionNumber" : "4a67a55ccbf5038d4d1b92fc97015156ed6deef9", "scmCommitLog" : "commit 20\n", "scmAuthor" : "shilpa", "scmCommitTimestamp" : NumberLong("1488001708000"), "numberOfChanges" : NumberLong(1) }
{ "_id" : ObjectId("58b137280b2f385c61325682"), "_class" : "com.capitalone.dashboard.model.Commit", "collectorItemId" : ObjectId("58b117750b2f38413edd44c7"), "timestamp" : NumberLong("1488009000755"), "scmUrl" : "http://10.107.100.145/shilpsl1/Dashboard_Repo.git", "scmBranch" : "master", "scmRevisionNumber" : "085eaa194fb578b32dcb5962b1ad0c37de5b9086", "scmCommitLog" : "commit 21\n", "scmAuthor" : "shilpa", "scmCommitTimestamp" : NumberLong("1488008688000"), "numberOfChanges" : NumberLong(1) }
{ "_id" : ObjectId("58b138180b2f385c61325683"), "_class" : "com.capitalone.dashboard.model.Commit", "collectorItemId" : ObjectId("58b117750b2f38413edd44c7"), "timestamp" : NumberLong("1488009240072"), "scmUrl" : "http://10.107.100.145/shilpsl1/Dashboard_Repo.git", "scmBranch" : "master", "scmRevisionNumber" : "00dea72610d1ad0640b6a7a87e2661d5b675a23d", "scmCommitLog" : "commit 22\n", "scmAuthor" : "shilpa", "scmCommitTimestamp" : NumberLong("1488009173000"), "numberOfChanges" : NumberLong(1) }
{ "_id" : ObjectId("58b428700b2f38093d41ff3c"), "_class" : "com.capitalone.dashboard.model.Commit", "collectorItemId" : ObjectId("58b117750b2f38413edd44c7"), "timestamp" : NumberLong("1488201840151"), "scmUrl" : "http://10.107.100.145/shilpsl1/Dashboard_Repo.git", "scmBranch" : "master", "scmRevisionNumber" : "5e3b3eb04c38489428e42e8d7564c86134b706f4", "scmCommitLog" : "commit 23\n", "scmAuthor" : "shilpa", "scmCommitTimestamp" : NumberLong("1488201773000"), "numberOfChanges" : NumberLong(1) }
{ "_id" : ObjectId("58b43b300b2f38093d41ff3d"), "_class" : "com.capitalone.dashboard.model.Commit", "collectorItemId" : ObjectId("58b117750b2f38413edd44c7"), "timestamp" : NumberLong("1488206640082"), "scmUrl" : "http://10.107.100.145/shilpsl1/Dashboard_Repo.git", "scmBranch" : "master", "scmRevisionNumber" : "2730b9b637b3dae70d1457badec91d681bdfb4f3", "scmCommitLog" : "commit 24\n", "scmAuthor" : "shilpa", "scmCommitTimestamp" : NumberLong("1488206596000"), "numberOfChanges" : NumberLong(1) }
{ "_id" : ObjectId("58b6f9600b2f3834fec64a2b"), "_class" : "com.capitalone.dashboard.model.Commit", "collectorItemId" : ObjectId("58b117750b2f38413edd44c7"), "timestamp" : NumberLong("1488386400127"), "scmUrl" : "http://10.107.100.145/shilpsl1/Dashboard_Repo.git", "scmBranch" : "master", "scmRevisionNumber" : "951824da7b8fdfbc8487f3bf3d74befaf66c2ce4", "scmCommitLog" : "commit 25\n", "scmAuthor" : "shilpa", "scmCommitTimestamp" : NumberLong("1488386349000"), "numberOfChanges" : NumberLong(1) }
{ "_id" : ObjectId("58b6fca80b2f3834fec64a2c"), "_class" : "com.capitalone.dashboard.model.Commit", "collectorItemId" : ObjectId("58b117750b2f38413edd44c7"), "timestamp" : NumberLong("1488387240102"), "scmUrl" : "http://10.107.100.145/shilpsl1/Dashboard_Repo.git", "scmBranch" : "master", "scmRevisionNumber" : "842478b21464cbbbe223f8193040d3fa973a9c83", "scmCommitLog" : "commit 26\n", "scmAuthor" : "shilpa", "scmCommitTimestamp" : NumberLong("1488387161000"), "numberOfChanges" : NumberLong(1) }
{ "_id" : ObjectId("58b83cd00b2f38431cf7b656"), "_class" : "com.capitalone.dashboard.model.Commit", "collectorItemId" : ObjectId("58b117750b2f38413edd44c7"), "timestamp" : NumberLong("1488469200322"), "scmUrl" : "http://10.107.100.145/shilpsl1/Dashboard_Repo.git", "scmBranch" : "master", "scmRevisionNumber" : "68db74935df55a8066e1e10357db6badfe620b52", "scmCommitLog" : "commit 27\n", "scmAuthor" : "shilpa", "scmCommitTimestamp" : NumberLong("1488469142000"), "numberOfChanges" : NumberLong(1) }
{ "_id" : ObjectId("58b84a2c0b2f384fafd689ea"), "_class" : "com.capitalone.dashboard.model.Commit", "collectorItemId" : ObjectId("58b117750b2f38413edd44c7"), "timestamp" : NumberLong("1488472620053"), "scmUrl" : "http://10.107.100.145/shilpsl1/Dashboard_Repo.git", "scmBranch" : "master", "scmRevisionNumber" : "69769c50b99db3ac0e548d57391d7708fca286fa", "scmCommitLog" : "commit 28\n", "scmAuthor" : "shilpa", "scmCommitTimestamp" : NumberLong("1488472565000"), "numberOfChanges" : NumberLong(1) }
{ "_id" : ObjectId("58b84c480b2f384fafd689eb"), "_class" : "com.capitalone.dashboard.model.Commit", "collectorItemId" : ObjectId("58b117750b2f38413edd44c7"), "timestamp" : NumberLong("1488473160071"), "scmUrl" : "http://10.107.100.145/shilpsl1/Dashboard_Repo.git", "scmBranch" : "master", "scmRevisionNumber" : "f3977f4396642d5e4e21b392e27993efd98b4fe1", "scmCommitLog" : "commit 29\n", "scmAuthor" : "shilpa", "scmCommitTimestamp" : NumberLong("1488473116000"), "numberOfChanges" : NumberLong(1) }

**Comment by shilpsl1** [comment]
{ "_id" : ObjectId("58b117840b2f384255157b78"), "_class" : "com.capitalone.dashboard.model.Pipeline", "collectorItemId" : ObjectId("58b117040b2f38413edd44c5"), "stages" : { "Test_Env" : { "commits" : [ ] }, "Build" : { "commits" : [ { "timestamp" : NumberLong("1487977087827"), "scmRevisionNumber" : "c43a08d5fb6edb81d9c852d683f766c5ff5336f6", "scmCommitLog" : "commit 19", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1487976586000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1487972107622"), "scmRevisionNumber" : "d122b3f20eb038fa3db1aea633d708b43a9bc9cb", "scmCommitLog" : "commit 16", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1487972005000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1487972107622"), "scmRevisionNumber" : "9a4309e125cbaa425e62795f8c6e71ca8899fb6f", "scmCommitLog" : "commit 18", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1487973566000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1487972107622"), "scmRevisionNumber" : "9305f48bebcf0525d145f6fca197f37c5e458dd2", "scmCommitLog" : "commit 17", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1487972987000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1487963887308"), "scmRevisionNumber" : "ecfdce8166d176a20e74e40279fcfc2303cb2bcb", "scmCommitLog" : "commit 15", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1487963762000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1487273226762"), "scmRevisionNumber" : "5c846ec71ff2609bc0d5903b5b5922b7737435c2", "scmCommitLog" : "commit 14", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1487273109000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1487272386721"), "scmRevisionNumber" : "53dff777a344df43ef6852bdc9d7ad9d669f8ca8", "scmCommitLog" : "commit 13", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1487272242000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1487087589742"), "scmRevisionNumber" : "132050c78f952ae5231abc867693896db7931be4", "scmCommitLog" : "commit 13", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1487087495000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1487022967232"), "scmRevisionNumber" : "ce597008c926df4f208fe78878b7559045c9b4ff", "scmCommitLog" : "commit 12", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1487022891000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1486670646331"), "scmRevisionNumber" : "f172732b0b469bc5991c071085cda2babeba6edb", "scmCommitLog" : "commit 11", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1486670552000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1486489569314"), "scmRevisionNumber" : "c098ed23f461dd46de0e59264e05e8da3da54d91", "scmCommitLog" : "commit 10", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1486489470000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1486481228986"), "scmRevisionNumber" : "1b10748135997c36037800ce9b651f68906dc308", "scmCommitLog" : "commit 9", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1486481130000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1486145825976"), "scmRevisionNumber" : "7517f98a6dcd51aeae72808fd604b758a227fb0a", "scmCommitLog" : "commit 8", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1486145673000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1486137665656"), "scmRevisionNumber" : "fcdd038e33b1d6d31a211535497e086edbff7eb3", "scmCommitLog" : "commit 8", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1486137582000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1486067707916"), "scmRevisionNumber" : "3061d4ed04f9b22dbfc2328773fa99ce0834763e", "scmCommitLog" : "commit 8", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1486067622000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1485879905657"), "scmRevisionNumber" : "3f1db0da4261e46cf184589a5a0e62c714b41f00", "scmCommitLog" : "commit 8", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1485879858000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1485806587764"), "scmRevisionNumber" : "cdc7372c71d097ea6858ec244d9af42add14a1cc", "scmCommitLog" : "commit 7", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1485806493000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1485195189105"), "scmRevisionNumber" : "3840c872b7d200b456d9d59c6b3c837fe354c5aa", "scmCommitLog" : "commit 6", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1485195090000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1485186428773"), "scmRevisionNumber" : "fde390d2e92adf84eaf9b827b6b9405270af2eea", "scmCommitLog" : "commit 5", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1485186296000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1484941929771"), "scmRevisionNumber" : "cb0bba9be356e574559ceb89294687833d4c3fe4", "scmCommitLog" : "commit 4", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1484941813000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1484932149404"), "scmRevisionNumber" : "7bb8ef0de073ae1f3759f7fc61b458b598713fd2", "scmCommitLog" : "commit 3", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1484932024000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1484932149404"), "scmRevisionNumber" : "17d7eb026947c108da1f1f9a9deed23fa8be30fa", "scmCommitLog" : "commit 3", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1484941616000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1484930649346"), "scmRevisionNumber" : "188aa56a4758064274c5bba6bee596e67fbd39a6", "scmCommitLog" : "commit 3", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1484930157000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1484929809305"), "scmRevisionNumber" : "92de7bf57f73ce526cdb8c4dd6c11c0d8e682620", "scmCommitLog" : "commit 3", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1484929601000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1488009250059"), "scmRevisionNumber" : "00dea72610d1ad0640b6a7a87e2661d5b675a23d", "scmCommitLog" : "commit 22", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1488009173000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1488009250059"), "scmRevisionNumber" : "4a67a55ccbf5038d4d1b92fc97015156ed6deef9", "scmCommitLog" : "commit 20", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1488001708000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1488009250059"), "scmRevisionNumber" : "085eaa194fb578b32dcb5962b1ad0c37de5b9086", "scmCommitLog" : "commit 21", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1488008688000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1488201847232"), "scmRevisionNumber" : "5e3b3eb04c38489428e42e8d7564c86134b706f4", "scmCommitLog" : "commit 23", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1488201773000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1488206647421"), "scmRevisionNumber" : "2730b9b637b3dae70d1457badec91d681bdfb4f3", "scmCommitLog" : "commit 24", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1488206596000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1488387247870"), "scmRevisionNumber" : "842478b21464cbbbe223f8193040d3fa973a9c83", "scmCommitLog" : "commit 26", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1488387161000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1488387247870"), "scmRevisionNumber" : "951824da7b8fdfbc8487f3bf3d74befaf66c2ce4", "scmCommitLog" : "commit 25", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1488386349000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1488469205979"), "scmRevisionNumber" : "68db74935df55a8066e1e10357db6badfe620b52", "scmCommitLog" : "commit 27", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1488469142000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1488472626111"), "scmRevisionNumber" : "69769c50b99db3ac0e548d57391d7708fca286fa", "scmCommitLog" : "commit 28", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1488472565000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1488473166137"), "scmRevisionNumber" : "f3977f4396642d5e4e21b392e27993efd98b4fe1", "scmCommitLog" : "commit 29", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1488473116000"), "numberOfChanges" : NumberLong(1) } ] } }, "failedBuilds" : [ ] }
{ "_id" : ObjectId("58b5e5fc0b2f38799a21edd4"), "_class" : "com.capitalone.dashboard.model.Pipeline", "collectorItemId" : ObjectId("58b5e5740b2f3878d2207f72"), "stages" : { "Test_Env" : { "commits" : [ ] } }, "failedBuilds" : [ ] }
{ "_id" : ObjectId("58b5ee5f0b2f3801e9189c9b"), "_class" : "com.capitalone.dashboard.model.Pipeline", "collectorItemId" : ObjectId("58b5ee400b2f3801e9189c98"), "stages" : { "Test_Env" : { "commits" : [ ] } }, "failedBuilds" : [ ] }
{ "_id" : ObjectId("58b6f8f70b2f383451a039f3"), "_class" : "com.capitalone.dashboard.model.Pipeline", "collectorItemId" : ObjectId("58b6f8910b2f383451a039ee"), "stages" : { "Test_Env" : { "commits" : [ ] }, "Build" : { "commits" : [ { "timestamp" : NumberLong("1488387247870"), "scmRevisionNumber" : "842478b21464cbbbe223f8193040d3fa973a9c83", "scmCommitLog" : "commit 26", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1488387161000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1488387247870"), "scmRevisionNumber" : "951824da7b8fdfbc8487f3bf3d74befaf66c2ce4", "scmCommitLog" : "commit 25", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1488386349000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1488469205979"), "scmRevisionNumber" : "68db74935df55a8066e1e10357db6badfe620b52", "scmCommitLog" : "commit 27", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1488469142000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1488472626111"), "scmRevisionNumber" : "69769c50b99db3ac0e548d57391d7708fca286fa", "scmCommitLog" : "commit 28", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1488472565000"), "numberOfChanges" : NumberLong(1) }, { "timestamp" : NumberLong("1488473166137"), "scmRevisionNumber" : "f3977f4396642d5e4e21b392e27993efd98b4fe1", "scmCommitLog" : "commit 29", "scmAuthor" : "shilpsl1", "scmCommitTimestamp" : NumberLong("1488473116000"), "numberOfChanges" : NumberLong(1) } ] } }, "failedBuilds" : [ ] }

**Comment by nireeshT** [comment]
@shilpsl1  update to latest code base and check. Reopen if still issue.
