### ISSUE TITLE
Latest Hygieia code has broken Sonar

### ISSUE THREAD

**Issue by anandsit** [capitalone/Hygieia#1166]
Hi Team,

Hygieia dashboard was working fine with Jenkins, Sonar, Stash integrated. Jira was not working. I was told that latest hygieia code has fixes for Jira. I got the latest code deployed. 

Now i see Sonar is broken. Please look into the issue at the earliest.

the last commit included in my build is 30e7e19df795dea683f88df8a858d6855fb44b4c

**Comment by anandsit** [comment]
It has also broken the product dashboard as well

**Comment by avadhmr** [comment]
@anandsit - what errors are you getting?....it is working fine on my setup.

**Comment by xpdable** [comment]
I have met similar issue as what I post on the gitter
I've got one item in the database:
![image](https://cloud.githubusercontent.com/assets/2903719/22873266/ee78edd6-f1f9-11e6-95db-b9ab66627e0e.png)
However UI does not show it:
![image](https://cloud.githubusercontent.com/assets/2903719/22873272/f9576b74-f1f9-11e6-9545-a93e9ce7a367.png)

This Sonar instance is just upgraded to Version 5.6.3 which is running in 5.2 months before

Reversely, I've another Sonar instance in Version 5.6.3, and it is running with Hygieia correctly.
Before, I set both Sonar to Hygieia, but currently only one is running fine.

> #Sonar server(s) (required) - Can provide multiple
sonar.servers[0]=http://sonar.badSonar.com/
sonar.servers[1]=http://10.35.24.62:9000/

**Comment by smsuresh** [comment]
for me , not even this job/project names are being displayed..
no error either. :(

**Comment by tabladrum** [comment]
Can you clear your bro

**Comment by tabladrum** [comment]
Browser cache

**Comment by smsuresh** [comment]
yes, switching to chrome worked!, Thankyou.

**Comment by anandsit** [comment]
yes!! browser cache issue. now resolved.
thanks. Good that i was busy over weekend and did not downgrade ;-)
