### ISSUE TITLE
Unable to add the Widgets

### ISSUE THREAD

**Issue by RAMESHBABU18** [capitalone/Hygieia#1170]
Trying to add the SCM(Bitbucket) Widgets in the dashboard..,
Executed the command java -jar bitbucket-scm-collector-2.0.5-SNAPSHOT.jar  --spring.config.location=application.properties
Properties file is below:
dbhost= dashboarddb
dbhost= localhost
dbport= 27017
dbusername=dashboarduser
dbpassword=dbpassword

#Collector schedule (required)
git.cron=0 0/1 * * * *

#mandatory
git.host = https://bitbucket.org/

#mandatory
git.api=/rest/api/1.0/

#Maximum number of days to go back in time when fetching commits
git.commitThresholdDays=15

#Credentials should be enter in the UI. Is not necessary.
git.user=*****
git.password=******

Is their anything to add for property file..,Could any one help me

**Comment by nireeshT** [comment]
@RAMESHBABU18  - paste error log.

**Comment by Sbrenthughes** [comment]
@RAMESHBABU18 - Are you still experiencing this issue? Can you please paste the error logs?

**Comment by Sbrenthughes** [comment]
@RAMESHBABU18 I am closing this issue. If you are still having problems please reopen.
