### ISSUE TITLE
sonar config ( security &  unit tests)

### ISSUE THREAD

**Issue by smsuresh** [capitalone/Hygieia#1171]
Can someone provide steps to configure "security  analysis"  & "Unit tests"  for sonarqube in hygieia..
As of now I see only "static analysis " been populated..

our prj has chkstyle & PMD as well, integrated with maven & ant.

**Comment by bikebaba** [comment]
Same here. I'm looking to get the Security Analysis piece also. Thanks.

**Comment by smsuresh** [comment]
@bikebaba I believe its supporting only the results from Fortify for now, not other tools :(

**Comment by satishc1** [comment]
Closed.
