### ISSUE TITLE
Unable to fetch commit count in GUI using private Bitbucket collector

### ISSUE THREAD

**Issue by gowthamastute** [capitalone/Hygieia#1172]
Hi

When I run the Bitbucket collector it is automatically embedding "projects/repo" in middle of the URL, so I am getting 404 URL not found error.
 
My private Bitbucket URL is:
https://bitbucket.company.com/projects/PDC/repos/browse/.gitignore/commits?until=develop&limit=25

But the below URL is verified after executing collector to check for the commit so I am getting 404 not found error.

https://bitbucket.company.com/rest/api/1.0/projects/projects/repos/PDC/repos/browse/.gitignore/commits?until=develop&limit=25

URL embedded in between:
1./rest/api/1.0
2./projects/repo
The above stated is added in between my private URL. Please help me should I need to modify any file to rectify this error.

Property file:
dbname=dashboarddb
dbhost=localhost
dbport=27017
dbusername=user
dbpassword=password
git.cron=0 0/5 * * * *
git.host=https://bitbucket.company.com
git.api=/rest/api/1.0/
git.username=username
git.password=password
git.key=hdqe40mYMhM9AemY9rgDiRfDIvepJb
github.key=hdqe40mYMhM9AemY9rgDiRfDIvepJb
git.commitThresholdDays=15
git.pageSize=25
git.product=server

I execute the below command 
java -jar bitbucket-scm-collector-2.0.5-SNAPSHOT.jar --spring.config.location=/home/hygieiaconf/applicationbb.properties

Got output as:
2017-02-13 06:05:00,196 INFO  c.c.d.collector.CollectorTask - Repo Count              2        0s
2017-02-13 06:05:00,196 INFO  c.c.d.collector.CollectorTask - New Commits          0        0s
2017-02-13 06:05:00,196 INFO  c.c.d.collector.CollectorTask - Finished                              0s

Unable to get the commit count.

**Comment by MarkRx** [comment]
You need to use the git url in the UI. Not the url to browse files.

**Comment by gowthamastute** [comment]
Thanks for your feedback.

I have tried with the git url in the UI too but getting the same above error. 
Any other suggestion, do i need to change any logic from any java files?

**Comment by nitin1706** [comment]
@gowthamastute  : it should work. can you try with latest codebase to see if it exists. 
Try giving git url in UI while configuring widget.

**Comment by nitin1706** [comment]
re-open with logs if issue exists.
