### ISSUE TITLE
Is Jira collector going to fetch Team information without Tempo-Team plugin?

### ISSUE THREAD

**Issue by tinabear** [capitalone/Hygieia#1173]
Right now, Jira collector only supports Tempo-Team plugin. Any plan about working for Jira without this plugin?

Thank you,

Dongsheng

**Comment by MarkRx** [comment]
It does work without it. Use the latest codebase and remove the temp teams property

**Comment by tinabear** [comment]
Sorry, maybe i didn't express my question clearly.
I just want jira collector to show jira issues for different teams where tempo-team plugin is not installed.

**Comment by satishc1** [comment]
@tinabear Do you have projects and teams configured in Jira without having the tempo-team plugin ? If you have a custom field defined for teams, you could set it for the property below and see if it works. Else set it to blank and the UI will assume team = Any.

#############################################################################
# In Jira, your instance will have its own custom field created for "team"
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's team ID field name via the following URI where your
# queried user story issue has team set on it; your custom field name describes the
# team value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraTeamFieldName=

**Comment by tinabear** [comment]
Yes, when I set the property as 
**feature.teamQuery=teaminfo
feature.jiraTeamFieldName=customfield_10703**

I can find error in the log:
2017-02-14 14:50:00,333 ERROR c.c.d.client.DefaultJiraClient - IOException
java.io.FileNotFoundException: https://jira.xxxxxx.com/rest/tempo-teams/1/team
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872) ~[na:1.8.0_111]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) ~[na:1.8.0_111]

Anything wrong with my configuration?

**Comment by satishc1** [comment]
@tinabear The code currently uses the TEMPO_TEAMS_REST_SUFFIX when you set feature.jiraTeamFieldName . Since you don't have tempo teams, hence the error when trying to invoke https://jira.xxxxxx.com/rest/tempo-teams/1/team . Can you find out the rest url for your team info and a sample json that is returned ?

**Comment by MarkRx** [comment]
The code does not support alternative mechanisms to representing teams outside of the tempo-team plugin at this time. The teamQuery setting does not appear to be used.

**Comment by tinabear** [comment]
@MarkRx So I cannot change anything to make the collector show team info outside of the tempo-team plugin, can I? Any further plan for this issue?

Thank you

**Comment by MarkRx** [comment]
Correct. My team had discussed the idea of allowing arbitrary queries into the feature collection but we decided against it due to the complexity of having to support a query DSL. It would also require the collectors to have knowledge and be able to pull in arbitrary fields from the json response.

I do not have any plans to implement being able to support non-standard fields for teams.

**Comment by tinabear** [comment]
Thank you for answering my question. @MarkRx

**Comment by satishc1** [comment]
Closed.

**Comment by shabna96** [comment]
Hi,Is there an update on this? Is there anyway to use team concept in Jira without using tempo-teams plugin?

**Comment by satishc1** [comment]
@shabna96 Try this https://github.com/capitalone/Hygieia/pull/1644
