### ISSUE TITLE
Pipeline configuration

### ISSUE THREAD

**Issue by smsuresh** [capitalone/Hygieia#1175]
Can you help with a sample pipeline configuration for Hygieia, I've no clue what to need to be provided for each environment ( DEV,QA,Int,etc )..

Thanks in advance..

**Comment by nireeshT** [comment]
@smsuresh Current pipeline configuration widget allows to choose the environments for DEV, QA,INT,PERF,..etc. Environment drop down will be populated with the values from deploy widget (if using uDeploy  collector or Hygieia Jenkins publisher data will be pushed to deploy widget).  #1020  is in progress, which dealt to customize the stage names for each environment.

**Comment by smsuresh** [comment]
Thankyou Nireesh @nireeshT

**Comment by satishc1** [comment]
@smsuresh  Refer https://github.com/capitalone/Hygieia/issues/884 for info on configuring the pipeline.

**Comment by smsuresh** [comment]
@satishc1  Thankyou Satish, I've configured it , but  im able to select only "ONE" environment in Deployment widget, unable to see all the environments,
So in pipeline also ,seeing only either DEV/QA/PROD..

**Comment by satishc1** [comment]
@smsuresh Do you have a deployment job configured with the jenkins hygieia publisher for each of the environments you want to see in hygieia ? Dev , QA , Prod etc need its own deployment jobs. Make sure you set up all the jobs and run them in jenkins and push the stuff to hygieia.

**Comment by smsuresh** [comment]
@satishc1 Yes I've jobs, It worked now

The issue was   " I DID NOT maintain similar string Application Name for all the environment, so it didn't join them,,

Earlier I had like  APP_DEV, APP_QA  
Now I just kept them as "APP"

I see all environments in deployment widget & ALSO in pipeline now!!

Started enjoying hygiea now, very useful tool :)

**Comment by satishc1** [comment]
@smsuresh Excellent.
