### ISSUE TITLE
multiple environments in Deploy widget

### ISSUE THREAD

**Issue by smsuresh** [capitalone/Hygieia#1177]
As of now, im able to add only one environement under Depploy widget 
Either DEV/QA/Prod,etc

But I see few screenshots having all environtments listed under the single dashboard.
Can you please share me the configuration details, how to add multiple environments under a single dashboard (deploy widget)

**Comment by satishc1** [comment]
@smsuresh Refer to my comments in your earlier tickets on how to configure the pipeline.
