### ISSUE TITLE
Hygieia jenkins publisher error

### ISSUE THREAD

**Issue by smsuresh** [capitalone/Hygieia#1178]
Hi,
 Can you please help to fix the below error..

Hygieia: Failed Publishing Build Complete Data. Response Code: 400. 
Hygieia Build Artifact Publisher - Looking for file pattern '*.jar' in directory /var/lib/jenkins/workspace/scan-Hybris/target
Hygieia Artifact Publisher: Processing  file: /var/lib/jenkins/workspace/scan-Hybris/target/hybris-types-1.0.jar
Hygieia: Failed Publishing Build Artifact Data. hybris-types-2.3.jar, Name=hybris-types, Version=1.0, Group=comergent. Response Code: 400. 

--------
Hygieia: Failed Publishing 
Response Code: 400. 
------
sonar is up & running fine, Hygieia is up & running fine, Jenkins is running fine..

**Comment by satishc1** [comment]
@smsuresh Refer to https://github.com/capitalone/Hygieia/issues/884 on how to populate the "Publish Artifact Information" fields in the Post-Build Actions of the jenkins hygieia publisher plugin. Reopen if still an issue.

**Comment by smsuresh** [comment]
@satishc1  I use 2 Jenkins
Everything working fine in 1 server
In another server, I Still see 400 error..

Please help to resolve it..

**Comment by satishc1** [comment]
@smsuresh You have 2 jenkins, one of them working ..one not. Compare the options for the two.
Jenkins -> Manage Jenkins -> Configure System
Jenkins -> Manage Jenkins -> Manage Plugins (check plugin version for hygieia)
And compare your job config.

**Comment by vijay4057** [comment]
Getting Hygieia: Failed Publishing Build Complete Data. Response Code: 200. In Jenkins pipeline. How to verify the issue?
