### ISSUE TITLE
product view, not getting udpated

### ISSUE THREAD

**Issue by smsuresh** [capitalone/Hygieia#1179]
I've configured HYgieia-Jenkins plugins for DEV & QA
1)  able to see  in the drop down of deployment widget, but im not seeing respective product view dashboard getting updated for each build/deployment, its empty always..

2) Im able to select only one env under deployment widget (either DEV/QA), but not both :(

Please help to configure them.
[productDB config issue.docx](https://github.com/capitalone/Hygieia/files/779732/productDB.config.issue.docx)

**Comment by satishc1** [comment]
@smsuresh Refer to my comments in your earlier tickets on how to configure your pipeline.
