### ISSUE TITLE
Hygieia - Jenkins publisher error

### ISSUE THREAD

**Issue by smsuresh** [capitalone/Hygieia#1180]
Hygieia: Failed Publishing Build Complete Data. Response Code: 400. 
Hygieia Build Artifact Publisher - Looking for file pattern '*.jar' in directory /var/lib/jenkins/workspace/scan-HybrisExtensions-QA/target
Hygieia Artifact Publisher: Processing  file: /var/lib/jenkins/workspace/scan-HybrisExtensions-QA/target/HybrisTmp-1.2.jar
Hygieia: Failed Publishing Build Artifact Data. HybrisTmp-1.2.jar, Name=HybrisTmp, Version=1.2, Group=comergent. Response Code: 400. 

--------
Please help to fix the issue..
Response Code: 400.

**Comment by satishc1** [comment]
@smsuresh You have 2 jenkins, one of them working ..one not. Compare the options for the two.
Jenkins -> Manage Jenkins -> Configure System
Jenkins -> Manage Jenkins -> Manage Plugins (check plugin version for hygieia)
And compare your job config.
