### ISSUE TITLE
Gerrit collector will not get new commit info when the time of gerrit server is later than hygieia server.

### ISSUE THREAD

**Issue by wdquan1985** [capitalone/Hygieia#1184]
For example, gerrit collector in hygieia server get the last commit info from gerrit server, and now gerrit server is 2:00, hygieia server is 3:00.  Then gerrit server has a new commit at 2:10, collector will get commit info from 3:00, it can't get the commit info commited at 2:10, and will never get any new commit info.
So I suggest we can use the time in commit info as the last updated time, I have made a simple change in the collect method of the class GerritCollectorTask in my local code:

    @Override
    public void collect(Collector collector) {

        logBanner("Starting...");
        long start = System.currentTimeMillis();
        int repoCount = 0;
        int commitCount = 0;

        clean(collector);
        for (GerritRepo repo : enabledRepos(collector)) {
     	
            LOG.debug(repo.getOptions().toString() + "::" + repo.getBranch());
            long lastCommitUpdateTime = 0L;

            for (Commit commit : getCommits(repo)) {
                LOG.debug(commit.getTimestamp() + ":::" + commit.getScmCommitLog());
                               
                if (isNewCommit(repo, commit)) {
        	
                    commit.setCollectorItemId(repo.getId());
                    commitRepository.save(commit);
                    commitCount++;       
                    //why when commitCount==1, because we arrange commit info in reverse chronological order according to the time.
                    if (commitCount == 1) {                  
                        lastCommitUpdateTime = commit.getScmCommitTimestamp();					
		        }
                }
            }
            
            //why do this setting, in order to ignore different time.
            //If can't get any commit info, don't change lastUpdatedTime.
            if (lastCommitUpdateTime != 0L) {
		 repo.setLastUpdated(lastCommitUpdateTime);
	    }          
            repo.removeLastUpdateDate();  //moved last update date to collector item. This is to clean old data.
            gerritRepoRepository.save(repo);
            
            repoCount++;
        }
        log("Repo Count", start, repoCount);
        log("New Commits", start, commitCount);
        log("Finished", start);
    }

Hope it's useful.

**Comment by nitin1706** [comment]
@wdquan1985 : Can you submit a PR with these changes.

**Comment by wdquan1985** [comment]
@nitin1706 - Is the gerrit supported now? I get these code from the branch https://github.com/capitalone/Hygieia/tree/gerrit-integration. If it's supported now, I will submit a PR.
