### ISSUE TITLE
Not able to get Jenkins Hygieia Plugins

### ISSUE THREAD

**Issue by Clement06** [capitalone/Hygieia#1188]
I am getting the below error when I run mvn clean package from the Hygieia-plugin folder ,

![image](https://cloud.githubusercontent.com/assets/25548421/23145743/927444fc-f7c8-11e6-9182-7220407fedc1.png)

Steps followed:

1. From the core folder , I run mvn clean install
2. From the Hygieia-Jenkins-plugin folder, I run mvn test and mvn clean package

Please assit. @jdamick @satishc1 @jaredsmith

**Comment by MarkRx** [comment]
Double check you are using the latest code. Try running maven with -U. If that doesn't work delete your .m2/repository directory to clear the cache.

**Comment by nireeshT** [comment]
@Clement06  - refer #1142

**Comment by nireeshT** [comment]
@Clement06  - closing issue. Reopen if it is not resolved.
