### ISSUE TITLE
Alternative Jenkins CodeQuality Collector

### ISSUE THREAD

**Issue by MarkRx** [capitalone/Hygieia#1191]
Looking to see if anyone thinks this would be useful. Right now the only way to get code quality data is with sonar. I've investigated and it seems that Jenkins has endpoints that can be hit to obtain junit, jacoco, findbugs, pmd, and checkstyle data with plugins. This would be used to populate a bunch of the code quality data. There is nothing for security analysis, technical debt, or "functional tests".

This would allow users to use the codequality widget without relying on sonar. It would be a Jenkins specific implementation.

@amitmawkin @tabladrum @satishc1

**Comment by schecbr** [comment]
@MarkRx , this would be extremely useful!  We currently do not have an enterprise service (like Sonar) available at our company and are looking to fill the gap by continuing to promote the use of many of the tools you listed above.. Having the ability to then pull this info into the dashboard would be a great step forward!

**Comment by tinabear** [comment]
We are also using Veracode scan. It would be great if we can use this collector to collect Veracode analysis results obtained by Jenkins jobs.

**Comment by stevegal** [comment]
see https://github.com/capitalone/Hygieia/pull/1368 for such a collector (does jacoco,findbugs,pmd and checkstyle)

**Comment by nitin1706** [comment]
This collector has been merged in PR mentioned above.
