### ISSUE TITLE
artifactory collector not showing any information

### ISSUE THREAD

**Issue by rsingh22** [capitalone/Hygieia#1193]
Below is my property file which is giving me below results because we don't have

```
artifactory.endpoint=artifactory/ in our artifactory

> # Database Name
> dbname=dashboard
> 
> # Database HostName - default is localhost
> dbhost=localhost
> 
> # Database Port - default is 27017
> dbport=27017
> 
> # Database Username - default is blank
> dbusername=db
> 
> # Database Password - default is blank
> dbpassword=dbpass
> 
> # Collector schedule (required)
> artifactory.cron=0 0/5 * * * *
> 
> # Artifactory server (required) - Can provide multiple
> artifactory.servers[0]=http://artifactory.test.com:9000/
> 
> # Artifactory user name (required)
> artifactory.username=abcdefg
> 
> # Artifactory api key (required)
> artifactory.apiKey=AKCp2VpEfLRH
> 
> # The repo to collect artifacts from (required) - Can provide multiple (comma separated for each server) 
> artifactory.repos[0]=libs-release-local
> 
> # Artifactory REST endpoint
> artifactory.endpoint=artifactory/
> 
> # Artifact Regex Patterns
> # Each artifact found is matched against the following patterns in order (first one wins)
> # The following capture groups are available:
> #  - group
> #  - module
> #  - artifact
> #  - version
> #  - classifier
> #  - ext
> # Matches maven artifacts of the form [org]/[module]/[version]/[module]-[version]([-classifier])(.[ext])
> artifactory.patterns[0]=(?<group>.+)/(?<module>[^/]+)/(?<version>[^/]+)/(?<artifact>\\k<module>)-\\k<version>(-(?<classifier>[^\\.]+))?(\\.(?<ext>.+))?
> 
> # Matches ivy files of the form [org]/[module]/[revision]/ivy-[revision](-[classifier]).xml 
> artifactory.patterns[1]=(?<group>.+)/(?<module>[^/]+)/(?<version>[^/]+)/(?<artifact>ivy)-\\k<version>(-(?<classifier>[^\\.]+))?\\.(?<ext>xml)
> 
> # Matches ivy artifact files of the form [org]/[module]/[revision]/[type]/[artifact]-[revision](-[classifier])(.[ext])
> artifactory.patterns[2]=(?<group>.+)/(?<module>[^/]+)/(?<version>[^/]+)/(?<type>[^/]+)/(?<artifact>[^\\.-/]+)-\\k<version>(-(?<classifier>[^\\.]+))?(\\.(?<ext>.+))?
```

then it is giving me the below error

2017-02-21 20:00:00,075 INFO  c.c.d.collector.CollectorTask - http://artifactory.test.com:9000/
2017-02-21 20:00:00,075 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-02-21 20:00:00,427 ERROR c.c.d.c.DefaultArtifactoryClient - Error with REST url: http://artifactory.test.com:9000/artifactory/api/repositories
2017-02-21 20:00:00,427 ERROR c.c.d.c.DefaultArtifactoryClient - 404 Not Found

I commented out this property then it is connecting but giving me below error 

```
# Artifactory REST endpoint
 artifactory.endpoint=artifactory/
```

Error
2017-02-21 20:10:00,028 INFO  c.c.d.collector.CollectorTask - Running Collector: Artifactory
2017-02-21 20:10:00,087 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-02-21 20:10:00,088 INFO  c.c.d.collector.CollectorTask - http://artifactory.test.com:9000
2017-02-21 20:10:00,088 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-02-21 20:10:00,488 INFO  c.c.d.collector.CollectorTask - Fetched repos                    0s
2017-02-21 20:10:00,492 INFO  c.c.d.collector.CollectorTask - New repos               0        0s
2017-02-21 20:10:00,592 ERROR c.c.d.c.DefaultArtifactoryClient - Error with REST url: http://artifactory.test.com:9000/api/search/aql
2017-02-21 20:10:00,592 ERROR c.c.d.c.DefaultArtifactoryClient - 403 Forbidden
2017-02-21 20:10:00,600 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.

Reason : I am using artifactory.repos[0]=libs-release-local(Because I am using full name of the repo libs-release-local)..

If I change it to libs-release then it is connecting but giving no information

Please let me know what am I missing here?

**Comment by MarkRx** [comment]
Looks like the doc is out of date. The servers, usernames, apiKeys, and repos are all arrays:

> > artifactory.servers[0]=http://artifactory.test.com:9000/
> 
> # Artifactory user name (required)
> artifactory.usernames[0]=abcdefg
> 
> # Artifactory api key (required)
> artifactory.apiKeys[0]=AKCp2VpEfLRH
> 
> # The repo to collect artifacts from (required) - Can provide multiple (comma separated for each server) 
> artifactory.repos[0]=libs-release-local

**Comment by rsingh22** [comment]
Hi @MarkRx I updated what you mentioned in my property file and now it calculated the infor first time and after that showing no information

> 2017-02-22 11:15:24,071 INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
> 2017-02-22 11:15:24,077 INFO  com.capitalone.dashboard.Application - Started Application in 4.138 seconds (JVM running for 4.7
> 2017-02-22 11:20:00,035 INFO  c.c.d.collector.CollectorTask - Running Collector: Artifactory
> 2017-02-22 11:20:00,072 INFO  c.c.d.collector.CollectorTask - -----------------------------------
> 2017-02-22 11:20:00,072 INFO  c.c.d.collector.CollectorTask - http://artifactory.test.com:9000/
> 2017-02-22 11:20:00,072 INFO  c.c.d.collector.CollectorTask - -----------------------------------
> 2017-02-22 11:20:00,386 INFO  c.c.d.collector.CollectorTask - Fetched repos                    0s
> 2017-02-22 11:20:00,388 INFO  c.c.d.collector.CollectorTask - New repos               0        0s
> 2017-02-22 12:04:39,540 INFO  c.c.d.collector.CollectorTask - New artifacts       76132     2679s
> 2017-02-22 12:04:39,541 INFO  c.c.d.collector.CollectorTask - Finished                      2679s
> 2017-02-22 12:05:00,002 INFO  c.c.d.collector.CollectorTask - Running Collector: Artifactory
> 2017-02-22 12:05:00,009 INFO  c.c.d.collector.CollectorTask - -----------------------------------
> 2017-02-22 12:05:00,010 INFO  c.c.d.collector.CollectorTask - http://artifactory.test.com:9000/
> 2017-02-22 12:05:00,010 INFO  c.c.d.collector.CollectorTask - -----------------------------------
> 2017-02-22 12:05:00,303 INFO  c.c.d.collector.CollectorTask - Fetched repos                    0s
> 2017-02-22 12:05:00,305 INFO  c.c.d.collector.CollectorTask - New repos               0        0s
> 2017-02-22 12:05:06,449 INFO  c.c.d.collector.CollectorTask - New artifacts           0        6s
> 2017-02-22 12:05:06,449 INFO  c.c.d.collector.CollectorTask - Finished                         6s
> 2017-02-22 12:10:00,013 INFO  c.c.d.collector.CollectorTask - Running Collector: Artifactory
> 2017-02-22 12:10:00,030 INFO  c.c.d.collector.CollectorTask - -----------------------------------
> 2017-02-22 12:10:00,030 INFO  c.c.d.collector.CollectorTask - http://artifactory.test.com:9000/
> 2017-02-22 12:10:00,030 INFO  c.c.d.collector.CollectorTask - -----------------------------------
> 2017-02-22 12:10:00,143 INFO  c.c.d.collector.CollectorTask - Fetched repos                    0s
> 2017-02-22 12:10:00,145 INFO  c.c.d.collector.CollectorTask - New repos               0        0s
> 2017-02-22 12:10:42,290 INFO  c.c.d.collector.CollectorTask - New artifacts           0       42s
> 2017-02-22 12:10:42,291 INFO  c.c.d.collector.CollectorTask - Finished                        42s
> 2017-02-22 12:15:00,012 INFO  c.c.d.collector.CollectorTask - Running Collector: Artifactory

**Comment by MarkRx** [comment]
That looks correct. It only gathers information on artifacts that have been modified after the last time the collector has run.

**Comment by rsingh22** [comment]
Thanks for you support
