### ISSUE TITLE
Jenkins pipeline plugins HTTP 500 

### ISSUE THREAD

**Issue by xpdable** [capitalone/Hygieia#1195]
I am using latest version for Hygieia and the jenkins plugin, while I publish from jenkinsfile (pipeline) getting this error:

> [Pipeline] hygieiaDeployPublishStep
Hygieia: Failed Publishing Build Data for Deployment Publishing. Response Code: 500. Response Value= {timestamp:1487753969114,status:500,error:Internal Server Error,exception:java.lang.StackOverflowError,message:No message available,path:/api/build}
Hygieia Deployment Publisher - Looking for file pattern '*.jar' in directory /home/ejvqa-win-01-jenkins/workspace/jira-connector/target
Hygieia Deployment Publisher: Processing file: /home/ejvqa-win-01-jenkins/workspace/jira-connector/target/jira-connector-2.0.0.jar
Hygieia Deployment Publisher: Processing file: /home/ejvqa-win-01-jenkins/workspace/jira-connector/target/jira-connector-2.0.0-jar-with-dependencies.jar
Hygieia: Published Deploy Data: Response Code: 201. Response Value= "58ad52f15c61b42158f9bb5a"
Hygieia: Published Deploy Data: Response Code: 201. Response Value= "58ad52f15c61b42158f9bb5b"
[Pipeline] }
[Pipeline] // stage

meanwhile in api log :

> 2017-02-22 17:04:08,185 ERROR c.c.d.rest.RestApiExceptionHandler - Field 'url' cannot be missing or null or empty
com.capitalone.dashboard.misc.HygieiaException: Field 'url' cannot be missing or null or empty
at com.capitalone.dashboard.service.CommitServiceImpl$GitHubv3.str(CommitServiceImpl.java:223) ~[api.jar!/:2.0.5-SNAPSHOT]
at com.capitalone.dashboard.service.CommitServiceImpl$GitHubv3.buildCommits(CommitServiceImpl.java:185) ~[api.jar!/:2.0.5-SNAPSHOT]
at com.capitalone.dashboard.service.CommitServiceImpl$GitHubv3.<init>(CommitServiceImpl.java:140) ~[api.jar!/:2.0.5-SNAPSHOT]
at com.capitalone.dashboard.service.CommitServiceImpl.createFromGitHubv3(CommitServiceImpl.java:92) ~[api.jar!/:2.0.5-SNAPSHOT]
at com.capitalone.dashboard.rest.ZCommitController.createGitHubv3(ZCommitController.java:44) ~[api.jar!/:2.0.5-SNAPSHOT]

**Comment by satishc1** [comment]
@xpdable Refer to https://github.com/capitalone/Hygieia/issues/884 for how to setup your deployment jobs in Jenkins.  If it doesn't help then reopen with screenshots of your hygieia publisher configuration and the deploy job configuration.

**Comment by xpdable** [comment]
First of all, my Hygieia works fine with the plugin in a non jenkinsfile configuration and the connection is fine:
![image](https://cloud.githubusercontent.com/assets/2903719/23240435/86b9eb76-f9a8-11e6-8691-4b9f8459bd9a.png)


part of my jenkinsfile of Hygieia job :
`stage('Hygieia-Build'){
        hygieiaDeployPublishStep applicationName: 'jira-connector', artifactDirectory: '/target', artifactGroup: 'com.thomsonreuters.ejvqa', artifactName: '*.jar', artifactVersion: '', buildStatus: 'Success', environmentName: 'Dev'
   }`

My Jenkins configuration:
![image](https://cloud.githubusercontent.com/assets/2903719/23240386/3778d0e0-f9a8-11e6-882f-1698666d9d11.png)

Then the above log shows the response 500 error

**Comment by xpdable** [comment]
@satishc1 seems I cannot reopen it but still have I the problem. Could you help ? Thanks

**Comment by satishc1** [comment]
@xpdable Can you also post the screenshot of the hygieia plugin version from Manage Jenkins -> Manage Plugins -> Installed

**Comment by xpdable** [comment]
@satishc1  Please find it at the screenshot above, it's 2.32.2

**Comment by satishc1** [comment]
@xpdable 2.32.2 is the jenkins verison.  I was asking about the hygieia plugin version. Go to Manage Jenkins -> Manage Plugins -> Installed and look for hygieia.

**Comment by xpdable** [comment]
@satishc1 
![image](https://cloud.githubusercontent.com/assets/2903719/23284592/3c07c67e-fa67-11e6-8575-744aa41c9c01.png)

**Comment by xpdable** [comment]
Updated everything.. jenkins plugins dependencies, Hygieia codes .... no more http 50x error.
