### ISSUE TITLE
Hygieia Dashboard doesn't populate the details like builds/commits etc 

### ISSUE THREAD

**Issue by vandz1** [capitalone/Hygieia#1196]
Hygieia Dashboard doesn't populate the details like builds/commits .Please help

**Comment by nireeshT** [comment]
@vandz1  - are build and code repo collectors running ? can you see the collections polled to Mongo? if you see any error in collectors log, paste it here.

**Comment by satishc1** [comment]
@vandz1 Closed. Try with latest codebase. If still an issue, then reopen with more info logs / screenshots.
