### ISSUE TITLE
Contributor Guidlines

### ISSUE THREAD

**Issue by grocky** [capitalone/Hygieia#12]
Hi!

Are there any guidelines for contributing? I've submitted the form for the license agreement and I'd like to implement Collectors for CircleCI and Pivotal. I'm not sure if you'd like them to contributed back to this repo or just kept in my fork.

**Comment by amitmawkin** [comment]
Thanks for submitting the CPL, and also on your decision to contribute back to Hygieia, Please follow the same project structure model for your collectors as exist today for other available collectors , once you have these collectors implemented please submit a pull request back, we should be able to validate them and accept the pull request to make them available for CircleCI and Pivotal users from Hygieia master branch.

Please feel free to drop suggestions, or any feedback you have for us.  
Also let me know if I can close this issue.

**Comment by grocky** [comment]
Thanks for the response Amit! I'll implement them and submit a PR.
