### ISSUE TITLE
Build failed due to compilation error

### ISSUE THREAD

**Issue by xpdable** [capitalone/Hygieia#1200]
After I pulled latest build where the PR-1020 is merged : 

> [ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /D:/test/Hygieia/api/src/test/java/com/capitalone/dashboard/config/TestC
onfig.java:[24,40] cannot find symbol
  symbol:   class SystemConfigService
  location: package com.capitalone.dashboard.service
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] com.capitalone.dashboard:Hygieia ................... SUCCESS [  0.700 s]
[INFO] com.capitalone.dashboard:core ...................... SUCCESS [ 39.253 s]
[INFO] com.capitalone.dashboard:api ....................... FAILURE [  2.930 s]
[INFO] com.capitalone.dashboard:artifactory-artifact-collector SKIPPED
[INFO] com.capitalone.dashboard:bamboo-build-collector .... SKIPPED
[INFO] com.capitalone.dashboard:jenkins-build-collector ... SKIPPED
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SKIPPED
[INFO] com.capitalone.dashboard:sonar-codequality-collector SKIPPED
[INFO] com.capitalone.dashboard:aws-cloud-collector ....... SKIPPED
[INFO] com.capitalone.dashboard:udeploy-deployment-collector SKIPPED
[INFO] com.capitalone.dashboard:xldeploy-deployment-collector SKIPPED
[INFO] com.capitalone.dashboard:jira-feature-collector .... SKIPPED
[INFO] com.capitalone.dashboard:versionone-feature-collector SKIPPED
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SKIPPED
[INFO] com.capitalone.dashboard:bitbucket-scm-collector ... SKIPPED
[INFO] com.capitalone.dashboard:github-scm-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:subversion-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:gitlab-git-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:UI ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 43.695 s
[INFO] Finished at: 2017-02-24T08:07:28+08:00
[INFO] Final Memory: 75M/627M
[INFO] ------------------------------------------------------------------------

**Comment by xpdable** [comment]
BUILD SUCCEED while I comment that line out anyway...
`//import` com.capitalone.dashboard.service.SystemConfigService;`

**Comment by xpdable** [comment]
However the deploy widget is broken with below browser console error : 

> Error: [$injector:unpr] Unknown provider: systemConfigDataProvider <- systemConfigData <- deployConfigController <- deployConfigController <- deployConfigController <- deployConfigController <- deployConfigController <- deployConfigController <- deployConfigController <- deployConfigController <- deployConfigController <- deployConfigController <- deployConfigController <- deployConfigController <- deployConfigController
http://errors.angularjs.org/1.5.11/$injector/unpr?p0=systemConfigDataProvid…Controller%20%3C-%20deployConfigController%20%3C-%20deployConfigController
    at bower.js:1475
    at bower.js:5970
    at Object.getService [as get] (bower.js:6123)
    at bower.js:5975
    at getService (bower.js:6123)
    at injectionArgs (bower.js:6148)
    at Object.invoke (bower.js:6170)
    at $controllerInit (bower.js:11999)
    at resolveSuccess (bower.js:49359)
    at processQueue (bower.js:18103)

**Comment by satishc1** [comment]
@xpdable Thanks. PR-1020 is being reviewed. Should get corrected soon.

**Comment by tabladrum** [comment]
Master is broken. Working to fix it.

**Comment by satishc1** [comment]
@xpdable Try now. Get latest codebase, rebuild and clear your browser cache before running.

**Comment by tabladrum** [comment]
Master is still unstable..

**Comment by MarkRx** [comment]
Master builds for me now.

**Comment by nireeshT** [comment]
Issue resolved
