### ISSUE TITLE
jira-collector properties

### ISSUE THREAD

**Issue by charan1011** [capitalone/Hygieia#1206]
The description to generate below properties are bit confusing and i couldnt able to find the exact custom field value.

Please help me with more details on how to find these fields

feature.jiraSprintDataFieldName=
feature.jiraEpicIdFieldName=
feature.jiraStoryPointsFieldName=
feature.jiraTeamFieldName=

**Comment by ebosveld** [comment]
Could you edit your issue so that it isn't one giant header? It'll make it more readable. Do you use Docker or do you want to run Hygieia on a normal server?

**Comment by charan1011** [comment]
@ebosveld What is meant by [some-issue-name] ?

**Comment by nitin1706** [comment]
Like mentioned above, not all the fields are required. You need to set the ones you need. 
[some-issue-name] is the title of issue in Jira board.
