### ISSUE TITLE
Hygieia should be capable of fetching data using dates

### ISSUE THREAD

**Issue by shilpsl1** [capitalone/Hygieia#1208]
This would be a suggestion like provide FROM and TO calendar and user should be able to view the data from those those dates as Hygieia supports only 15 days old data as of now.
If we require to view the previous data in Hygieia it would be good if we are able to filter using dates.
Thanks!!!

**Comment by tabladrum** [comment]
While technically it is possible to store data for longer time, we intentionally kept it for 14 days for one reason: From DevOps/Agile perspective, 14 days i.e., sprint cycle is what should matter in terms of fast feedback to developers.

Note that the data actually don't get purged off. It's the UI which restricts displaying the data. 

However, an analytics aspect of all these is a fair ask and we do have the same internally. For analytical solution, you could replicate the data on to a separate MongoDB instance and run your preferred analytics tool on that. 

On the product dashboard page, you do have a view to 90 days trend on few metrics such as code quality, build break MTR, security vulnerability etc. We are planning to add more on that area. 

Would love to hear what others think.

**Comment by shilpsl1** [comment]
Thank you for your response.
I totally agree with you,DevOps/Agile perspective, 14 days i.e., sprint cycle is what matter and I know that data is not puffed off. But what I was trying to tell is suppose in team dashboard if a option is ther to select from and to date like,
FROM: Jan 1, 2017  TO Jan 14, 2017 
and view those data in team dashboard it would be good. 
Thanks.

**Comment by satishc1** [comment]
@shilpsl1 Closed.
