### ISSUE TITLE
doubt reg UI

### ISSUE THREAD

**Issue by smsuresh** [capitalone/Hygieia#1212]
I've another internal executive dashboard ( JSP based) ,  Iam using Hygieia as well.
is it possible to use only of the widget from available in Hygieia to embed in my other application? ( say, just embed the sonar widget in other app, using any of HTML statement?  )

please clarify

**Comment by satishc1** [comment]
@smsuresh You could use something like an iframe to embed one webapp inside another webapp. If you want just one widget, you would need to create an additional template with just that widget and then embed it inside another app.
