### ISSUE TITLE
Data are not reflected in the dashboard 

### ISSUE THREAD

**Issue by BindhuEva** [capitalone/Hygieia#1216]
Hi
I have cloned Hygieia and UI is working fine. But my Jenkins data is not populated in the dashboard.
when I checked API connectivity using postman is shows crumb issue. 
Jenkins version : 2.32.1
Jenkins collector version : 2.0.5
 Am in need of help. Thanks in advance.
My logs doesn't show any error and I have attached my configuration
![image](https://cloud.githubusercontent.com/assets/26113775/23460205/262e1398-feaa-11e6-9a41-7444ddec9522.png)

![image](https://cloud.githubusercontent.com/assets/26113775/23460261/75a3a83e-feaa-11e6-830f-464fa682bee1.png)

**Comment by satishc1** [comment]
@BindhuEva On the "Configure Build Widget", what happens when you click on the "Build Job" search field ? Does it list the job in the dropdown ? Its a search box so try typing in your job name to narrow down the results. Also try clearing your browser cache.

**Comment by BindhuEva** [comment]
@satishc1  I can list down the jobs from jenkins but other details are not reflected.
The jobs also listed more than 1 times. I couldn't get why that happens..
![image](https://cloud.githubusercontent.com/assets/26113775/23493430/c4c01d44-ff31-11e6-848d-de6b3ad0a58f.png)

**Comment by satishc1** [comment]
@BindhuEva Paste your collectors and collector_items collections.

**Comment by satishc1** [comment]
@BindhuEva Closed. Reopen if still an issue.
