### ISSUE TITLE
Dependency failure for Building Hygieia Publisher Plugin 2.0.5-SNAPSHOT

### ISSUE THREAD

**Issue by satyakv786** [capitalone/Hygieia#1219]
Iam unable to create the hpi file., I have updated the snapshot version to 2.0.5 in the plugins pom.xml as well but still I see this error :

C:\Users\HOME PC\Documents\Hygieia-master\hygieia-jenkins-plugin>mvn install
[INFO] Scanning for projects...
[WARNING] The POM for org.jenkins-ci.tools:maven-hpi-plugin:jar:1.106 is missing, no dependency information available
[WARNING] Failed to build parent project for org.jenkins-ci.plugins:hygieia-publisher:hpi:2.0.5-SNAPSHOT
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.jenkins-ci.plugins:hygieia-publisher:hpi:2.0.5-SNAPSHOT
[WARNING] 'parent.relativePath' of POM org.jenkins-ci.plugins:hygieia-publisher:2.0.5-SNAPSHOT (C:\Users\HOME PC\Documents\Hygieia-master\hygieia-jenkins-plugin\pom.xml) points at com.capitalone.dashboard:Hygieia instead of org.jenkins-ci.plugins:plugin, please verify your project structure @ line 15, column 13
[WARNING] 'build.plugins.plugin.version' for org.jacoco:jacoco-maven-plugin is missing. @ line 190, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Hygieia Publisher Plugin 2.0.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.capitalone.dashboard:core:jar:2.0.5-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.943 s
[INFO] Finished at: 2017-03-01T19:04:19-05:00
[INFO] Final Memory: 20M/315M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project hygieia-publisher: Could not resolve dependencies for project org.jenkins-ci.plugins:hygieia-publisher:hpi:2.0.5-SNAPSHOT: Failure to find com.capitalone.dashboard:core:jar:2.0.5-SNAPSHOT in http://repo.jenkins-ci.org/public/ was cached in the local repository, resolution will not be reattempted until the update interval of repo.jenkins-ci.org has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by satyakv786** [comment]
pom file attached.
[pomfile.txt](https://github.com/capitalone/Hygieia/files/812458/pomfile.txt)

**Comment by nireeshT** [comment]
@satyakv786  - refer https://github.com/capitalone/Hygieia/issues/1142

**Comment by satyakv786** [comment]
I did follow the same steps as in ticket : 1142
changed pom.cml in plugins to 
<version>2.0.5-SNAPSHOT</version>
   </dependency>

1. cd to "core", then mvn clean install. Success.
2. cd to hygieia-jenkins-plugin, then mvn clean package. Failure.

i tried this multiple times but still get the same error .
can u pls forward me the hpi file ?

**Comment by satishc1** [comment]
@satyakv786 
1. 
The pomfile.txt you have attached doesn't match the log line numbers "line 15" etc.
(C:\Users\HOME PC\Documents\Hygieia-master\hygieia-jenkins-plugin\pom.xml) points at com.capitalone.dashboard:Hygieia instead of org.jenkins-ci.plugins:plugin, please verify your project structure @ line 15, column 13

It looks formatted wrong and has a bunch of "-" characters also.  So check to make sure you grab the latest pom.xml from the repo.  The only change you need to make in it is change the core dependency to 2.0.5-SNAPSHOT.

2. Do a mvn package install from the root of Hygieia.  Then check to make sure the core packages got installed in your local maven repository. If yes, then cd to the hygieia-jenkins-plugin folder and do a mvn package install. Check if your local repository is set in the maven settings if mvn has trouble locating the core jars.

**Comment by satyakv786** [comment]
Hi Satish,
               Thanks for reply. I followed ur instructions but received the attached error message.

C:\Users\HOME PC\Desktop\Hygieia-master\hygieia-jenkins-plugin>mvn package install
[INFO] Scanning for projects...
[WARNING] The POM for org.jenkins-ci.tools:maven-hpi-plugin:jar:1.106 is missing, no dependency information available
[WARNING] Failed to build parent project for org.jenkins-ci.plugins:hygieia-publisher:hpi:2.0.5-SNAPSHOT
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.jenkins-ci.plugins:hygieia-publisher:hpi:2.0.5-SNAPSHOT
[WARNING] 'parent.relativePath' of POM org.jenkins-ci.plugins:hygieia-publisher:2.0.5-SNAPSHOT (C:\Users\HOME PC\Desktop\Hygieia-master\hygieia-jenkins-plugin\pom.xml) points at com.capitalone.dashboard:Hygieia instead of org.jenkins-ci.plugins:plugin, please verify your project structure @ line 15, column 13
[WARNING] 'build.plugins.plugin.version' for org.jacoco:jacoco-maven-plugin is missing. @ line 190, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[outputlog.txt](https://github.com/capitalone/Hygieia/files/815641/outputlog.txt)

**Comment by satishc1** [comment]
@satyakv786 Can you paste a dir listing of C:\Users\HOME PC\Desktop\Hygieia-master\
And paste the output of mvn package install from C:\Users\HOME PC\Desktop\Hygieia-master\

**Comment by satyakv786** [comment]
Please find attached dir listing of C:\Users\HOME PC\Desktop\Hygieia-master folder.
[Dir_listing.txt](https://github.com/capitalone/Hygieia/files/815704/Dir_listing.txt) and mvn package install output of master .
[mvn package install_output.txt](https://github.com/capitalone/Hygieia/files/815717/mvn.package.install_output.txt)
Can you please verify the settings.xml file from m2 repository (attached).
[settings.txt](https://github.com/capitalone/Hygieia/files/815722/settings.txt)

**Comment by satishc1** [comment]
@satyakv786 Try replacing your settings.xml with this one 
```
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">

  <localRepository>C:\Users\HOME PC\.m2\repository</localRepository>
  <pluginGroups>
    
  </pluginGroups>

  <profiles>
  </profiles>
  <mirrors>

  </mirrors>
</settings>
```

**Comment by satyakv786** [comment]
Hi Satish,
              Thank you very much for ur help, changing the settings helped !

**Comment by satishc1** [comment]
@satyakv786 Closed. Good to know it worked.

**Comment by chethanbs** [comment]
I have made the changes in settings.XML as given above and also POM.XML in jenkins plugin folder is pointing to 2.0.5-SNAPSHOT.

I ran MVN install command in "core" folder and build is successfull.After that I am trying to build plugin by running "mvn clean package" inside jenkin plugin folder and build is failing with below errors.

I have taken the latest code from GITHUB today.

Could you please help me out to fix the issue?

C:\Hygieia\Hygieia_sourcecode\hygieia-jenki[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.604 s
[INFO] Finished at: 2017-05-05T18:43:30-04:00
[INFO] Final Memory: 48M/347M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.kohsuke:access-modifier-checker:1.11:enforce
(default-enforce) on project hygieia-publisher: Access modifier checks failed. S
ee the details above -> [Help 1]ns-plugin

**Comment by preetcam** [comment]
When I build Hygiea root, its a success. But when I run Hygiea-publisher, I get the following error. Please guide .. [INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 25.298 s
[INFO] Finished at: 2017-09-19T17:39:19-07:00
[INFO] Final Memory: 31M/341M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jenkins-ci.tools:maven-hpi-plugin:1.106:test-hpl (default-test-hpl) on project hygieia-publisher: Error preparing the manifest: Failed to open artifact javax.el:javax.el-api:jar:2.2.4:compile at C:\Users\kamakaur\.m2\repository\javax\el\javax.el-api\2.2.4\javax.el-api-2.2.4.jar: 1 problem was encountered while building the effective model for javax.el:javax.el-api:2.2.4
[ERROR] [FATAL] 'parent.artifactId' must be changed, the parent element cannot have the same groupId:artifactId as the project. @ line 44, column 21
[ERROR]  for project javax.el:javax.el-api:2.2.4 for project javax.el:javax.el-api:2.2.4
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by Praveen-chaganti** [comment]
[INFO] com.capitalone.dashboard:score-collector ........... SUCCESS [ 13.485 s]
[INFO] Hygieia Publisher Plugin 2.1.3-SNAPSHOT ............ FAILURE [  9.554 s]
[INFO] com.capitalone.dashboard:UI ........................ SKIPPED
[INFO] com.capitalone.dashboard:ui-tests 2.0.5-SNAPSHOT ... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:52 min
[INFO] Finished at: 2018-10-04T11:59:45-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project hygieia-publisher: Could not resolve dependencies for project org.jenkins-ci.plugins:hygieia-publisher:hpi:2.1.3-SNAPSHOT: Failed to collect dependencies at org.jenkins-ci.plugins.workflow:workflow-aggregator:jar:2.5: F
ailed to read artifact descriptor for org.jenkins-ci.plugins.workflow:workflow-aggregator:jar:2.5: Could not transfer artifact org.jenkins-ci.plugins.workflow:workflow-aggregator:pom:2.5 from/to resolution (https://nexus.kdc.capitalone.com/nexus/content/groups/
CLM): Remote host closed connection during handshake: SSL peer shut down incorrectly -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hygieia-publisher
