### ISSUE TITLE
Add Configure Feature Widget ,select box without value

### ISSUE THREAD

**Issue by JackLeeZhang** [capitalone/Hygieia#1226]
When I add the Configure Feature Widget, a select box without value, is that where there is no configuration?The diagram below:

![20170306172157](https://cloud.githubusercontent.com/assets/25958908/23604404/c1d6c0c8-0293-11e7-965c-e1e371e9ae4c.png)

Thank you very much for your help!

**Comment by satishc1** [comment]
@JackLeeZhang Is this built with the latest codebase? Try clearing your browser cache.

**Comment by JackLeeZhang** [comment]
@satishc1 I used yesterday from docker image "docker.io/devopsopen/docker-cov-hygui".But now i use latest codebase,the Problems still exist. I use the commad is "docker run -h="hygui" -t -p 8088:80 --link hyapi -e "HYGIEIA_API_PORT=tcp://10.2.27.49:8080" --name hygui -i devopsopen/docker-cov-hygui",to run UI layer,Right?

**Comment by JackLeeZhang** [comment]
@satishc1 In another way,can you tell me where the select box's data  come from? Thank you very much for your help!

**Comment by satishc1** [comment]
@JackLeeZhang From the collectors collection select name where "collectorType" : "AgileTool"

**Comment by JackLeeZhang** [comment]
Sorry I still don't quite understand, could you speak more detail?

**Comment by JackLeeZhang** [comment]
I have no idea , I only with combing the data relationship, finally understand the meaning of the answer you yesterday, but there are still questions.
![20170310152217](https://cloud.githubusercontent.com/assets/25958908/23786238/e07919ac-05a6-11e7-9199-edbda2dfe6d2.png)

**Comment by satishc1** [comment]
@JackLeeZhang The product collector is created by default on startup. Your screenshot looks correct.

**Comment by JackLeeZhang** [comment]
@satishc1 Thank you very much for your help, I'll take a look.

**Comment by JackLeeZhang** [comment]
@satishc1 Why did I add Dashboard are added to the id "58b6a6804cedfd00143df509" rather than ObjectId: "58b7ef3c821c8e2ab9912827"? I'd like to add to the collector with id "58b7ef3c821c8e2ab9912827".how can i to do ? 
![20170313145457](https://cloud.githubusercontent.com/assets/25958908/23844536/b55f2c58-07fd-11e7-8a87-ff8a0c2784a4.png)

**Comment by satishc1** [comment]
@JackLeeZhang Are you trying to get the jira feature widget to work or are you changing some code and questioning the data relationship ?

**Comment by JackLeeZhang** [comment]
I want to collect jira data ,and jira collector's ObjectId: "58b7ef3c821c8e2ab9912827",I don't know why the new dashboard ObjectId: is "58b6a6804cedfd00143df509".
![20170314085309](https://cloud.githubusercontent.com/assets/25958908/23881254/5a5ec182-0894-11e7-99c5-04dac6d82cef.png)

**Comment by satishc1** [comment]
@JackLeeZhang What's the output when you run the jira collector? Is there an exception or does it run successfully and gather data ?

**Comment by JackLeeZhang** [comment]
The output log normal, see below:
![20170315092133](https://cloud.githubusercontent.com/assets/25958908/23929504/b4528994-0961-11e7-8629-9ec60a231da4.png)
Directing a corresponding data for:
![20170315092429](https://cloud.githubusercontent.com/assets/25958908/23929555/0a713046-0962-11e7-9acf-107d3b838438.png)
