### ISSUE TITLE
how to configure selenium test results to Functional Test in Quality widget?

### ISSUE THREAD

**Issue by runapal5** [capitalone/Hygieia#1229]
how to configure selenium test results to Functional Test in Quality widget?

**Comment by runapal5** [comment]
Hi ,

Please let me know how will I integrate Selenium Test Case result integrated with Hygieia Dashboard?

Thanks
Runa Pal

**Comment by satishc1** [comment]
@runapal5 If your test case results are a cucumber format file, it is supported. https://github.com/capitalone/Hygieia/issues/1161
Other formats is a wip.
