### ISSUE TITLE
collectors to use simplified & common http client code

### ISSUE THREAD

**Issue by jdamick** [capitalone/Hygieia#123]
Several of the collectors have copy & pasted code for the http clients & processing code.  I'd like to see them share a common set of utils & clients.  I would suggest something like https://github.com/Netflix/feign with okhttp, such that the code would be more readable.
- [ ] Create shared client code / utils
- [ ] Simplify http client code across collectors
- [ ] Ability to record server responses - so that we can replay them for unit tests

**Comment by Sbrenthughes** [comment]
Please reopen if this is still a valid issue.
