### ISSUE TITLE
Unable to compile latest Hygieia API

### ISSUE THREAD

**Issue by anandsit** [capitalone/Hygieia#1230]
Getting the below error while compiling Hygieia API. Any help is appreciated.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project api: Compilation failure: Compilation failure:
[ERROR] /var/hy/Hygieia/api/src/main/java/com/capitalone/dashboard/model/PipelineResponse.java:[62,57] cannot find symbol
[ERROR] symbol:   class PipelineStage
[ERROR] location: class com.capitalone.dashboard.model.PipelineResponse
[ERROR] /var/hy/Hygieia/api/src/main/java/com/capitalone/dashboard/model/PipelineResponse.java:[66,33] cannot find symbol
[ERROR] symbol:   class PipelineStage
[ERROR] location: class com.capitalone.dashboard.model.PipelineResponse
[ERROR] /var/hy/Hygieia/api/src/main/java/com/capitalone/dashboard/model/PipelineResponse.java:[70,28] cannot find symbol
[ERROR] symbol:   class PipelineStage
[ERROR] location: class com.capitalone.dashboard.model.PipelineResponse
[ERROR] /var/hy/Hygieia/api/src/main/java/com/capitalone/dashboard/model/PipelineResponseCommit.java:[14,50] cannot find symbol
[ERROR] symbol:   class PipelineStage
[ERROR] location: class com.capitalone.dashboard.model.PipelineResponseCommit
[ERROR] /var/hy/Hygieia/api/src/main/java/com/capitalone/dashboard/service/PipelineServiceImpl.java:[96,132] cannot find symbol
[ERROR] symbol:   class PipelineStage

Thanks
Anand

**Comment by satishc1** [comment]
@anandsit class PipelineStage is in the core package. Did you grab the latest code ? Were you able to build and install the core package ?

**Comment by satishc1** [comment]
@anandsit Closed. Reopen if still an issue.
