### ISSUE TITLE
Jenkins deployment information using the jenkins-hygieia-plugin.

### ISSUE THREAD

**Issue by Satheesh-b** [capitalone/Hygieia#1232]
How to fetch a jenkins deployment from the hygieia plugin? when I hit the 
http://hygieiaApiUrl/deploy/application/api/json , it results in 404 error.
What is the hygieiaApiUrl?
How to successfully set up the hygieia plugin to get the information about deployment.

Thanks in advance.

**Comment by satishc1** [comment]
@Satheesh-b 
Please refer https://github.com/capitalone/Hygieia/issues/884 for info on configuring the plugin and pipeline.

**Comment by Satheesh-b** [comment]
Thank you so much for the prompt reply. But I have a general doubt, that how the data is stored in the collector_items collection in the MongoDB? Should I have to write a collector to get the response from plugin and store in DB? Or it is done from plugin itself?

**Comment by satishc1** [comment]
@Satheesh-b If you use the plugin, you don't need the jenkins collector. The former is push based, the later pull.
