### ISSUE TITLE
Failed to execute goal com.github.eirslett

### ISSUE THREAD

**Issue by KMedhansh** [capitalone/Hygieia#1233]
[INFO] 
[INFO] com.capitalone.dashboard:Hygieia .................. SUCCESS [4.835s]
[INFO] com.capitalone.dashboard:core ..................... SUCCESS [32.012s]
[INFO] com.capitalone.dashboard:api ...................... SUCCESS [16.606s]
[INFO] com.capitalone.dashboard:artifactory-artifact-collector  SUCCESS [8.767s]
[INFO] com.capitalone.dashboard:bamboo-build-collector ... SUCCESS [9.026s]
[INFO] com.capitalone.dashboard:jenkins-build-collector .. SUCCESS [9.617s]
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector  SUCCESS [2.691s]
[INFO] com.capitalone.dashboard:sonar-codequality-collector  SUCCESS [7.947s]
[INFO] com.capitalone.dashboard:aws-cloud-collector ...... SUCCESS [44.802s]
[INFO] com.capitalone.dashboard:udeploy-deployment-collector  SUCCESS [38.983s]
[INFO] com.capitalone.dashboard:xldeploy-deployment-collector  SUCCESS [4.091s]
[INFO] com.capitalone.dashboard:jira-feature-collector ... SUCCESS [15.489s]
[INFO] com.capitalone.dashboard:versionone-feature-collector  SUCCESS [5.633s]
[INFO] com.capitalone.dashboard:chat-ops-collector ....... SUCCESS [2.086s]
[INFO] com.capitalone.dashboard:bitbucket-scm-collector .. SUCCESS [2.584s]
[INFO] com.capitalone.dashboard:github-scm-collector ..... SUCCESS [3.305s]
[INFO] com.capitalone.dashboard:subversion-collector ..... SUCCESS [4.133s]
[INFO] com.capitalone.dashboard:gitlab-git-collector ..... SUCCESS [3.631s]
[INFO] com.capitalone.dashboard:UI ....................... FAILURE [0.360s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3:38.855s
[INFO] Finished at: Thu Mar 09 17:07:04 IST 2017
[INFO] Final Memory: 85M/339M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.29:install-node-and-npm (install node and npm) on project UI: The plugin com.github.eirslett:frontend-maven-plugin:0.0.29 requires Maven version 3.1.0 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginIncompatibleException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :UI

**Comment by KMedhansh** [comment]
My Config Details : 

Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T22:11:47+05:30)
Java version: 1.8.0_11, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_11\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 8.1", version: "6.3", arch: "amd64", family: "dos"

BUILD COMMAND USED: mvn clean install -DskipTests

**Comment by KMedhansh** [comment]
When I ran the individual UI project, I'm getting below issue:

[ERROR] npm WARN unmet dependency which is version 3.1.0
[INFO]
[INFO] --- frontend-maven-plugin:0.0.29:bower (bower install) @ UI ---
[INFO] Found proxies: []
[INFO] Running 'bower install' in D:\GIT_HUB_POC\Hygieia\UI
[INFO]
[INFO] --- frontend-maven-plugin:0.0.29:gulp (gulp build) @ UI ---
[INFO] Running 'gulp.js build' in D:\GIT_HUB_POC\Hygieia\UI
[ERROR] module.js:327
[ERROR]     throw err;
[ERROR]     ^
[ERROR]
[ERROR] Error: Cannot find module 'lodash._getnative'
[ERROR]     at Function.Module._resolveFilename (module.js:325:15)
[ERROR]     at Function.Module._load (module.js:276:25)
[ERROR]     at Module.require (module.js:353:17)
[ERROR]     at require (internal/module.js:12:17)
[ERROR]     at Object.<anonymous> (D:\GIT_HUB_POC\Hygieia\UI\node_modules\gulp\node_modules\gulp-util\node_modules\lodash.template\node_modules\lodash.keys\index.js:9:17)
[ERROR]     at Module._compile (module.js:397:26)
[ERROR]     at Object.Module._extensions..js (module.js:404:10)
[ERROR]     at Module.load (module.js:343:32)
[ERROR]     at Function.Module._load (module.js:300:12)
[ERROR]     at Module.require (module.js:353:17)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.855 s
[INFO] Finished at: 2017-03-09T17:27:30+05:30
[INFO] Final Memory: 18M/105M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.29:gulp (gulp build) on project UI: Failed to run task: 'gulp.js build' failed. (error code 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by KMedhansh** [comment]
MVN CONFIG FOR ABOVE LOGS:

Apache Maven 3.1.0 (893ca28a1da9d5f51ac03827af98bb730128f9f2; 2013-06-28 07:45:32+0530)
Java version: 1.8.0_11, vendor: Oracle Corporation
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 8.1", version: "6.3", arch: "amd64", family: "dos"

**Comment by KMedhansh** [comment]
[INFO] --- frontend-maven-plugin:0.0.29:gulp (gulp build) @ UI ---
[INFO] Running 'gulp.js build' in D:\GIT_HUB_POC\Hygieia\UI
[ERROR] module.js:327
[ERROR]     throw err;
[ERROR]     ^
[ERROR]
[ERROR] Error: Cannot find module 'lodash._getnative'
[ERROR]     at Function.Module._resolveFilename (module.js:325:15)
[ERROR]     at Function.Module._load (module.js:276:25)
[ERROR]     at Module.require (module.js:353:17)
[ERROR]     at require (internal/module.js:12:17)
[ERROR]     at Object.<anonymous> (D:\GIT_HUB_POC\Hygieia\UI\node_modules\gulp\node_modules\gulp-util\node_modules\lodash.template\node_modules\lodash.keys\index.js:9:17)
[ERROR]     at Module._compile (module.js:397:26)
[ERROR]     at Object.Module._extensions..js (module.js:404:10)
[ERROR]     at Module.load (module.js:343:32)
[ERROR]     at Function.Module._load (module.js:300:12)
[ERROR]     at Module.require (module.js:353:17)
[INFO] ------------------------------------------------------------------------

**Comment by KMedhansh** [comment]
ISSUE RESOLVED WITH BELOW STEPS:

install node js (http://blog.teamtreehouse.com/install-node-js-npm-windows)
  
  install node js and do a test run.
  
  goto UI project where you find package.json and execute cmd: npm install lodash --save
  (http://stackoverflow.com/questions/27431187/cannot-find-module-lodash)
  
  build UI project.(BUILD WILL SUCCESS)

Then build entire project.

**Comment by adityabalhara** [comment]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] com.capitalone.dashboard:Hygieia .................. SUCCESS [0.715s]
[INFO] com.capitalone.dashboard:core ..................... SUCCESS [24.908s]
[INFO] com.capitalone.dashboard:api ...................... SUCCESS [5.303s]
[INFO] com.capitalone.dashboard:artifactory-artifact-collector  SUCCESS [2.319s]
[INFO] com.capitalone.dashboard:bamboo-build-collector ... SUCCESS [2.375s]
[INFO] com.capitalone.dashboard:jenkins-build-collector .. SUCCESS [2.557s]
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector  SUCCESS [2.654s]
[INFO] com.capitalone.dashboard:sonar-codequality-collector  SUCCESS [0.639s]
[INFO] com.capitalone.dashboard:aws-cloud-collector ...... SUCCESS [1.539s]
[INFO] com.capitalone.dashboard:udeploy-deployment-collector  SUCCESS [2.276s]
[INFO] com.capitalone.dashboard:xldeploy-deployment-collector  SUCCESS [2.286s]
[INFO] com.capitalone.dashboard:jira-feature-collector ... SUCCESS [6.265s]
[INFO] com.capitalone.dashboard:versionone-feature-collector  SUCCESS [1.792s]
[INFO] com.capitalone.dashboard:chat-ops-collector ....... SUCCESS [0.510s]
[INFO] com.capitalone.dashboard:bitbucket-scm-collector .. SUCCESS [2.412s]
[INFO] com.capitalone.dashboard:github-scm-collector ..... SUCCESS [1.976s]
[INFO] com.capitalone.dashboard:subversion-collector ..... SUCCESS [0.525s]
[INFO] com.capitalone.dashboard:gitlab-git-collector ..... SUCCESS [2.461s]
[INFO] com.capitalone.dashboard:UI ....................... FAILURE [0.016s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:03.982s
[INFO] Finished at: Tue Jun 13 01:57:50 EDT 2017
[INFO] Final Memory: 71M/369M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.29:install-node-and-npm (install node and npm) on project UI: The plugin com.github.eirslett:frontend-maven-plugin:0.0.29 requires Maven version 3.1.0 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginIncompatibleException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :UI
[root@ip-192-168-1-61 Hygieia-Hygieia-2.0.4]# npm -v
3.10.10
[root@ip-192-168-1-61 Hygieia-Hygieia-2.0.4]# node -v
v6.11.0
#installed node and npm but still getting error.

**Comment by mkim37** [comment]
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building com.capitalone.dashboard:UI 2.0.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ UI ---
[INFO] 
[INFO] >>> maven-pmd-plugin:3.6:check (default) @ UI >>>
[INFO] 
[INFO] --- maven-pmd-plugin:3.6:pmd (pmd) @ UI ---
[INFO] 
[INFO] <<< maven-pmd-plugin:3.6:check (default) @ UI <<<
[INFO] 
[INFO] --- maven-pmd-plugin:3.6:check (default) @ UI ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.6.201602180812:prepare-agent (default) @ UI ---
[INFO] argLine set to -javaagent:/root/.m2/repository/org/jacoco/org.jacoco.agent/0.7.6.201602180812/org.jacoco.agent-0.7.6.201602180812-runtime.jar=destfile=/opt/Hygieia/UI/target/jacoco.exec
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.151s
[INFO] Finished at: Thu Jul 13 16:51:02 UTC 2017
[INFO] Final Memory: 16M/298M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.29:install-node-and-npm (install node and npm) on project UI: The plugin com.github.eirslett:frontend-maven-plugin:0.0.29 requires Maven version 3.1.0 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginIncompatibleException

using:
maven 3.5.0
npm 3.10.10
node 6.11.1
