### ISSUE TITLE
System requirement to setup hygieia on linux

### ISSUE THREAD

**Issue by varundevopsid99** [capitalone/Hygieia#1235]
hi team,

i reffered one of the issue opened here for system requirement which mentioned system requirement as follows, **can you please also share what will be the minimum required disk space to be available?**:

Red Hat Enterprise Linux Server release 7.2 (Maipo)
Linux kernel 3.10.0-327.36.1.el7.x86_64
16GB Ram
The average RAM consumption will be 130 Mb for apache httpd. This will go up depending on how many users hit apache. These numbers are for light usage with about 10 people running the UI.
MongoDb 3.2.9 takes up about 1 Gb RAM.
The API process takes up about 1 Gb RAM.
On average each collector running will have RAM consumption of 1gb per collector.

**Comment by satishc1** [comment]
@varundevopsid99  It will depend on whether you run all the modules on the same server or separate it out. Ui , api and collector modules will pretty much remain static except for log files that will grow.  The mongo data is the one you need to compute and plan for. A size of 20 to 30 Gb should be sufficient for mongo.

**Comment by varundevopsid99** [comment]
Thanks... Also can you let me know have you configured Docker on this linux setup?which version? and if possible can you share steps how you configured Hygieia setup in docker...thanks
