### ISSUE TITLE
[JIRA] Sprint status not being updated

### ISSUE THREAD

**Issue by alfonso-presa** [capitalone/Hygieia#1238]
We've made an installation of Hygieia and everything seems to be working fine. But when an Sprint associated with an Issue is  closed or opened that information doesn't seem to be reflected in the MongoDB until that Issue gets modified.

I've seen that the UpdatedDate of the issues is not being changed when their associated Sprint get's opened or closed, and I guess that's the reason the "story.st" query doesn't return those issues and thus they are not updated.

I've being reading almost all the opened and closed issues in this GitHub project and I've not seen anything related with this.... Am I missing something obvious in Jira's/Hygieia configuration?

See below the relevant configuration options

```
feature.pageSize=100

feature.deltaStartDate=2016-02-01T00:00:00.000000
feature.masterStartDate=2016-02-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2016-02-01T00:00:00.000000

feature.cron=0 */5 * * * *

feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic

feature.jiraIssueTypeNames=Epic,Feature,Story,Bug,Task
```

We have double checked that the custom_fields are properly configured.

Thanks!

**Comment by MarkRx** [comment]
That is correct. The underlying model does not have "Sprint" types. Instead each issue stores information about the sprint directly. As a result as you have observed updates to the sprint data will only get reflected on issues if the issue also updates.

I would think in most situations this should not be an issue. If you are closing a sprint then all the issues should be removed from the sprint. In our jira instance sprints cannot be closed with open issues. If all of the issues are closed or moved back to the backlog they would end up being updated (the spring field change) and hence you would get the sprint data updated for free.

Those query settings refer to *.st files in the code at src/main/resources/jiraapi-queries. It might be possible to set the queryFolder property and point it to a mounted directory with custom *.st queries. I've never tried it though and that code has been there before I started working with Hygieia.

**Comment by alfonso-presa** [comment]
Ok. I was just wondering if there was something we were missing, but If this is a known issue or just the expected behavior then I guess we will have to live with that :-).

In our instance issues are not being updated on sprint closed/activated actions, but that might be something we have not configured properly in Jira.

Thank you very much!
