### ISSUE TITLE
Get the jenkins Job name for relevant Userid

### ISSUE THREAD

**Issue by gokulknewt** [capitalone/Hygieia#1239]
Hi Team,

In Dashboard widget, currently we are getting the list of Job names using Jenkins REST API.
But we need to get the Job name for the specific user Id using Rest API.How do we get the Job name for specific user Id.Could you please assist for this issue.

**Also how to find out the users assigned to a which particular JOB name.**

Regards,
Gokul k

**Comment by satishc1** [comment]
@gokulknewt You will have to change the jenkins rest call to get the jenkins user info and add it to the collector_item. Then filter based on it. But you also need to map the hygieia user to a jenkins user.

**Comment by gokulknewt** [comment]
I can map into the collector_item table that's not an issue.But my question is that,For each(Specific) user
 how many Job url configured from Jenkins.How do i find using Rest API.Can you please let me know this exact scenario.

For example in my application using rest api like this.Do i have to modify further on this.

http://cbjm.qcorpaa.aa.com:8080/api/json?tree=jobs[name,url,builds[number,url],jobs[name,url]]

Thank you for your response

**Comment by satishc1** [comment]
@gokulknewt You could use changeSet to get the user info from jenkins
http://cbjm.qcorpaa.aa.com:8080/api/json?tree=jobs[name,lastBuild[number,duration,timestamp,result,changeSet[items[msg,author[fullName]]]]]

**Comment by satishc1** [comment]
Closed.

**Comment by gokulknewt** [comment]
Thank you for your response Satishc1

Which  you have shared above url same stuff we already tried in our application.But we are not getting as expected result.Currently we have configured as admin user lever i mean  it will return the result as,  list of job url  for all user configured from jenkins.

But our requirement is that like this,For that do we have any Rest API from Jenkins.
For Ex:
user1 => Job1, Job2
User2 => Job3 ,Job1
user3 => Job2, Job3

**Comment by gokulknewt** [comment]
HI Satishc,

As you provided above changeSet command we tried,but we are not getting user info.We tried below this command and result are getting like this,

Curl -g -u username:password "http://cbjm.qcorpaa.aa.com:8080/api/json?tree=jobs[name,lastBuild[number,duration,timestamp,result,changeSet[items[msg,author[fullName]]]]]"

![image](https://cloud.githubusercontent.com/assets/23208312/24285268/668b2474-1095-11e7-9117-0d940d19ebc6.png)

Could you help on this to proceed further.

Regards,
Gokul
