### ISSUE TITLE
create a new template which has all the type of  widgets as same in the dashboard

### ISSUE THREAD

**Issue by kakumasn** [capitalone/Hygieia#1241]
Hello,

I am currently working on creating a new template for dashboard. Where I want to have a dashboard with 6 sonarqube widgets and only those widgets and nothing else. I am working for a similar functionality for the rest of widgets too. So In short I am creating a template  with all the widgets as sonar widgets. So I want to have one sonarqube dashboard, one bamboo dashboard , udeploy dashboard etc.  

So i was able to create a template with all sonrqube widgets. The problem I am running into is the data in all the sonarqube widgets is getting reflected the same. If I select one sonarqube report in one sonarqube widget, the same same report is getting reflected in all the widgets. Here are my screenshots

The empty dashboard looks like this
![empty dashboard](https://cloud.githubusercontent.com/assets/26384694/23861568/d567632a-07e0-11e7-9ebf-8714467a3f4d.PNG)

And all the widgets show the same data
![dashboard screenshots 1](https://cloud.githubusercontent.com/assets/26384694/23861591/e9dd9392-07e0-11e7-83fe-9ea199907b02.PNG)
![dashboard screenshots 2](https://cloud.githubusercontent.com/assets/26384694/23861597/f022b264-07e0-11e7-8b97-38c0a5e23f47.PNG)

I looked at the components collection in the database. Even though there are 6 code quality widgets in the dashboard. It only stores one code quality element in the collectorItems. This might me the reason for this.
![1](https://cloud.githubusercontent.com/assets/26384694/23862127/9b76a124-07e2-11e7-91cb-024193c1a8fa.PNG)

Any inputs on this would be appreciated.

**Comment by satishc1** [comment]
@kakumasn When you save a widget from your new template what does your dashboards collection look like ? Its probably got only one codeanalysis widget. You would probably need to have multiple widgets of the same type in the dashboards collection.

**Comment by kakumasn** [comment]
Hi Satishc1,

My dashboard collection has six widgets . Here are the screenshots from the database.
![dashboard collection db](https://cloud.githubusercontent.com/assets/26384694/23870030/86fe7b36-07fb-11e7-85df-7164d7fbf6e8.PNG)

![dashboard colletion widgets db](https://cloud.githubusercontent.com/assets/26384694/23870052/9042c77e-07fb-11e7-8f46-56e79e09e63f.PNG)


My concern is with component collection of the database. Although I have six Collectoritems of type SonarQube. I can only see one collectoritem in the components  collection.

![1](https://cloud.githubusercontent.com/assets/26384694/23870109/b5a8f1f0-07fb-11e7-9cef-8079b35d581f.PNG)


I am thinking about this class Hygieia/core/src/main/java/com/capitalone/dashboard/model/Component.java
 Line no 53

  public void addCollectorItem(CollectorType collectorType, CollectorItem collectorItem) {
        // **Currently only one collectorItem per collectorType is supported**
        if (collectorItems.get(collectorType) == null) {
            collectorItems.put(collectorType, Arrays.asList(collectorItem));
        } else {
            List<CollectorItem> existing = new ArrayList<> (collectorItems.get(collectorType));
            if (isNewCollectorItem(existing, collectorItem)) {
                existing.add(collectorItem);
                collectorItems.put(collectorType, existing);
            }
        }
    }
When we are adding the collector only one collector item per Collector type is supported. How I can change that or any other inputs.

**Comment by satishc1** [comment]
@kakumasn Take a look at DashboardServiceImpl and follow the code when you add a widget to the Dashboard. You'll have to change the code at multiple places to do what you are trying to achieve. 
https://github.com/capitalone/Hygieia/issues/1064

**Comment by satishc1** [comment]
@kakumasn Closed.
