### ISSUE TITLE
Sending artifact info Unauthorized by using interface provided by api layer.

### ISSUE THREAD

**Issue by wdquan1985** [capitalone/Hygieia#1244]
I test the ldap authentication function using this branch https://github.com/StateFarmIns/Hygieia/tree/springSecurityIntegration.
I use shell script to send build info to hygieia, for example:
curl --connect-timeout 10 -m 60 -i -X POST --header "Content-Type:application/json" -H "Accept:application/json" --data
'{"artifactName":"SANDBOX","canonicalName":"SANDBOX","artifactGroup":"SANDBOX","artifactVersion":"1.0","buildId":"timestamp","timestamp":1488942038335,"sourceChangeSet":[{"scmUrl":"http://127.0.0.1/gerrit/60730","scmBranch":"1.0","scmRevisionNumber":"Ica15fe4f1f9d05a3c6bf74b7c0df8191565fcf76","scmAuthor":"ZHANG,Harry(Harry)","scmParentRevisionNumbers":["d61cbc08f08bb8f674c41b4f55ff6e4fd784378d"],"type":"New","scmCommitTimestamp":1488963918000,"numberOfChanges":1}],"metadata":{"jobName":"SANDBOX","buildUrl":"127.0.0.1/job/SANDBOX/179/","buildNumber":179,"jobUrl":"http://127.0.0.1/job/SANDBOX/","instanceUrl":"http://127.0.0.1/"}}' -u userName:password http://127.0.0.1:8080/api/artifact .
I have send the username and password to hygieia, but there is an error:
_{"timestamp":1489558957506,"status":401,"error":"Unauthorized","message":"Full authentication is required to access this resource","path":"/api/artifact"}_
 
Then I permit the url request which start with api by changing code in the spring security java configuration file com.capitalone.dashboard.config.WebSecurityConfig.java.
	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http.headers().cacheControl();
		http.csrf().disable()
			.authorizeRequests().antMatchers("/appinfo").permitAll()
								.antMatchers("/registerUser").permitAll()
								.antMatchers("/login**").permitAll()
                                                                _.antMatchers("/api**").permitAll()_
								.antMatchers(HttpMethod.GET, "/**").permitAll()			
								.anyRequest().authenticated()
									.and()
								.addFilterBefore(standardLoginRequestFilter(), UsernamePasswordAuthenticationFilter.class)
								.addFilterBefore(ldapLoginRequestFilter(), UsernamePasswordAuthenticationFilter.class)
								.addFilterBefore(jwtAuthenticationFilter, UsernamePasswordAuthenticationFilter.class)
								.exceptionHandling().authenticationEntryPoint(new Http401AuthenticationEntryPoint("Authorization"));
	}.

But it still can't work, how can I configure to ignore the authentication and authorization checks?
When I send the jenkins build into to hygieia, there is no any error, but the hygieia mongo db can't search the corresponding record.

**Comment by rob-miller-777** [comment]
Could you put this info in the pull request that's open.  This is something I will look at tomorrow.  We hadn't considered the jenkins plugin since it wasn't something we have used yet.

**Comment by rob-miller-777** [comment]
#1129

**Comment by rob-miller-777** [comment]
Pull the latest and try again.  The reason adding `.antMatchers("/api**").permitAll()` didn't work for you was because that isn't part of the path spring security is looking at.  Had you done `.antMatchers("/**").permitAll()`, it would have worked, but also unsecured everything.  I put a temporary solution in place for the jenkins plugin.  But it should probably be secured with an API key in the future.

**Comment by wdquan1985** [comment]
Thanks, I have put this info to the pull request. 
I add .antMatchers("/build","/artifact","/quality/**").permitAll(), because I use shell script to send build info, artifact info and sonarQube report to hygieia server. 
I have not used the jenkins plugin.  I only use shell script, is your temporary solution avilable for shell script?
For example:
curl --connect-timeout 10 -m 60 -i -X POST --header "Content-Type:application/json" -H "Accept:application/json" -u userName:password --data '{~~~~~~}'  http://127.0.0.1:8080/api/build

**Comment by lklkxcxc** [comment]
@wdquan1985 
`[root@host-10-0-0-28 rundeck]# curl --connect-timeout 10 -m 60 -i -X POST --header "Content-Type:application/json" -H "Accept:application/json" -u admin:laosiji --data '{
artifactName=deployment,
envName=TEST,
niceName=testk8s
}' http://hygieia.k8s.gaia/api/deploy/rundeck
HTTP/1.1 500 Internal Server Error
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Type: application/json;charset=UTF-8
Date: Tue, 09 Jan 2018 10:37:50 GMT
Expires: 0
Pragma: no-cache
Server: Apache-Coyote/1.1
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block
Content-Length: 228

{"timestamp":1515494270387,"status":500,"error":"Internal Server Error","exception":"io.jsonwebtoken.MalformedJwtException","message":"JWT strings must contain exactly 2 period characters. Found: 0","path":"/api/deploy/rundeck"}`
