### ISSUE TITLE
Gonfigure Code Repo Widget is not working for gitlab reporsitories

### ISSUE THREAD

**Issue by shivamms** [capitalone/Hygieia#1245]
I am getting "TypeError: Cannot read property '$setValidity' of undefined" when I tried to configure the widget. I tried both on-premise hosted and gitlab.com.
![image](https://cloud.githubusercontent.com/assets/8627753/23997318/3a3726e4-0a27-11e7-98d2-1d553b69eb18.png)

**Comment by rob-miller-777** [comment]
Check this one #1071

**Comment by shivamms** [comment]
I am not sure that helps. This is my properties file settings.
---------------------------------------------------------------------------------
# Database Name
dbname=dashboard

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
dbreplicaset=false
#dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=

# Database Password - default is blank
dbpassword=

# Logging File location
logging.file=./logs/gitlab.log

#Collector schedule (required)
gitlab.cron=0 0/1 * * * *

#Gitlab host (optional, defaults to "gitlab.com")
gitlab.host=https://git.mycompanyserver/

#Gitlab protocol (optional, defaults to "http")
gitlab.protocol=https

#Gitlab port (optional, defaults to protocol default port)
#gitlab.port=80

#If your instance of Gitlab is using a self signed certificate, set to true, default is false
gitlab.selfSignedCertificate=true

#Gitlab API Token (required, token of user the collector will use by default, can be overriden on a per repo basis from the UI. API token 

provided by Gitlab)
gitlab.apiToken=XXXXXXXXXXXXXXXXXXXXXXX
------------------------------------------------------------------------------------
The collector runs without any issues. But there is no entry for this gitlab collector item.

**Comment by nireeshT** [comment]
@shivamms  - As a workaround do below steps. 
1) Delete dashboard and create new.
2) configure Configure code repo widget -> select Gitlab 
3) provide url, branch and API key.
4) Save
This error seems to happen when widget is already configured with github (username and password) page became dirty and later toggled to configure gitlab.

**Comment by shivamms** [comment]
Same error. I created new dashboard.

![image](https://cloud.githubusercontent.com/assets/8627753/24005201/c1e7bb0a-0a3e-11e7-8a39-a61e3db455be.png)

**Comment by shivamms** [comment]
I guess the issue is with browser. It did work with IE but did not work with Chrome. Any idea?

**Comment by nireeshT** [comment]
@shivamms  - chrome version ?

**Comment by shivamms** [comment]
Version 56.0.2924.87 (64-bit)

But now it works on both browser.  I am not sure what fixed it.
I did two things:

1. Added certificate to JVM
2. As per your workaround, deleted and created new dashboard.

**Comment by nireeshT** [comment]
@shivamms  - sounds good. Closing issue .
