### ISSUE TITLE
Need help to push functional test data from selenium to Hygieia

### ISSUE THREAD

**Issue by jagadeeshkumarpatti** [capitalone/Hygieia#1246]
I am trying to push the data from selenium to Hygieia. Can someone please help me on how to push the functional test results data to Hygieia either through jenkins or selenium.

**Comment by nireeshT** [comment]
@jagadeeshkumarpatti  - check this out https://github.com/capitalone/Hygieia/issues/1229

**Comment by nireeshT** [comment]
@jagadeeshkumarpatti  - Reopen if issue is not resolved.
