### ISSUE TITLE
Question regarding Version One Collector

### ISSUE THREAD

**Issue by brennanananan** [capitalone/Hygieia#1247]
We're trying to deploy an instance of the version one collector with Docker, so on container creation the versionone-properties-builder.sh is applying properties for the collector jar. I noticed that many of the other properties builder scripts are applying a CRON setting 

```bash
# from multiple files...
jenkins.cron=${JENKINS_CRON:-0 0/5 * * * *}
sonar.cron=${SONAR_CRON:-0 0/5 * * * *}
subversion.cron=${SUBVERSION_CRON:-0 0/5 * * * *}
```

However, the versionone builder script has no such property being set. Is this intentional? Am I missing something?

**Comment by satishc1** [comment]
Closed.
