### ISSUE TITLE
Jenkins Plugin Hanging

### ISSUE THREAD

**Issue by rob-miller-777** [capitalone/Hygieia#1249]
Trying to use the jenkins plugin to get deployment data.  I built from 2.0.5, but had to update the pom to use the 2.0.5 version of the Hygieia-core dependency.  After successfully building and installing/configuring in jenkins.  When I run a pipeline, it gets to the Publishing Deployment stage, and just hangs there forever.  When I run the test connection step, it seems to hit my API fine, but something in the plugin itself keeps getting stuck.  

Here is my groovy script for the plugin. `hygieiaDeployPublishStep applicationName: 'Hygieia', artifactDirectory: '/api/target', artifactGroup: 'com.capitalone.dashboard', artifactName: '*.jar', artifactVersion: '2.0.5', buildStatus: 'Success', environmentName: 'dev'
`  

One thing to note is that using the groovy script generator, I was not able to select a build status, so I added that manually.  I also put some debug log statements in the plugin to see if I could track down exactly where it was hanging, and it looks like it is getting stuck on line 197 in the [HygieiaDeployPublishStep.java class](https://github.com/capitalone/Hygieia/blob/master/hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/workflow/HygieiaDeployPublishStep.java).  I can't get it to log anything inside the BuildBuilder constructor it is calling, or after this line.  Any help would be appreciated, I will continue looking at, but don't have much experience with jenkins plugins.

**Comment by nireeshT** [comment]
@rob-miller-777  - check this https://github.com/capitalone/Hygieia/issues/1195

**Comment by tabladrum** [comment]
line# 197 is: BuildBuilder buildBuilder = new BuildBuilder(run, hygieiaDesc.getHygieiaJenkinsName(), listener, BuildStatus.Success, true);  
The next line is the call to publish: HygieiaResponse buildResponse = hygieiaService.publishBuildData(buildBuilder.getBuildData());

@rob-miller-777 do you see anything in the api log?

**Comment by rob-miller-777** [comment]
No, it never makes it that far.  Threw a logging message after that line, and got nothing.  Put a logging message inside that constructor and saw nothing.  That includes the jenkins logs and api logs.  I am currently under the assumption that our jenkins server isn't configured properly, so trying to run a jenkins server locally to test that out.

**Comment by rob-miller-777** [comment]
Yeah, I tried the same plugin on a locally running jenkins server, and it worked fine.  So I need to figure out whats wrong with the jenkins server.
