### ISSUE TITLE
I am getting following error while taking  bower.json file from hygieia

### ISSUE THREAD

**Issue by dhivaharNewt** [capitalone/Hygieia#1252]
Error: [$injector:unpr] Unknown provider: $tooltipProvider <- $tooltip <- popoverHtmlUnsafeDirective...

Please help me out to resolve this issue.

**Comment by nireeshT** [comment]
@dhivaharNewt - please provide more information.

**Comment by dhivaharNewt** [comment]
- Previously I have used "angular": "~1.3.4" and "angular-bootstrap": "~0.12.0"
- Currently I am changing to "angular": "~1.5.9", and "angular-bootstrap": "~2.3.0". When I am using this I have modified the code according to migrated version, In js files dependencies like "uibModal" instead of "modal"  and "uibModalInstance" instead of "modalInstance" . After resolving those issues I am finally getting below error in the browser console.

Error: [$injector:unpr] Unknown provider: $tooltipProvider <- $tooltip <- popoverHtmlUnsafeDirective

**Comment by nireeshT** [comment]
@dhivaharNewt- Are you working on latest code base, because we upgraded to latest version of angular and bootstrap already. Rebake to the latest master.

**Comment by rob-miller-777** [comment]
Tooltip was another one they now prefix with "uib".  So $tooltip will have to be prefixed with "uib" similar to how $modal was.

**Comment by dhivaharNewt** [comment]
Thanks @rob-miller-777 . Issue got fixed.
