### ISSUE TITLE
Jira collector expects team details whereas our Jira instance does not use team concept - Can't we skip this?

### ISSUE THREAD

**Issue by shivamms** [capitalone/Hygieia#1253]
Our Jira instance does not have team concept used and when I tried to skip custom field for team with same field name given for sprint, I am getting the following error:

![image](https://cloud.githubusercontent.com/assets/8627753/24113465/47e43c88-0d73-11e7-9dad-e63ba08d0183.png)

Is there any workaround here? If yes, what is that?

My jira collector properties file goes like this:

# Database Name
dbname=dashboard

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
dbreplicaset=[false if you are not using MongoDB replicaset]
#dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=

# Database Password - default is blank
dbpassword=

# Logging File location
logging.file=./logs/jira.log

# PageSize - Expand contract this value depending on Jira implementation's
# default server timeout setting (You will likely receive a SocketTimeoutException)
feature.pageSize=100

# Delta change date that modulates the collector item task
# Occasionally, these values should be modified if database size is a concern
feature.deltaStartDate=2016-03-01T00:00:00.000000
feature.masterStartDate=2016-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2016-03-01T00:00:00.000000

# Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 * * * * *

# ST Query File Details - Required, but DO NOT MODIFY
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic

# JIRA CONNECTION DETAILS:
# Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY
#feature.jiraProxyUrl=http://proxy.com
#feature.jiraProxyPort=9000
feature.jiraBaseUrl=https://XXXXXXXXXXXXXXX.atlassian.net/
feature.jiraQueryEndpoint=rest/api/2/
# For basic authentication, requires username:password as string in base64
# This command will make this for you:  echo -n username:password | base64
feature.jiraCredentials=cwBtAGEAeQBhAGsAawBhAHIAdQBwAHAAYQBuADoAMgAwADMAMQAyADEAVAB5ADEAOQA5ADYAQAA=
# OAuth is not fully implemented; please blank-out the OAuth values:
feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=

#############################################################################
# In Jira, general IssueType IDs are associated to various "issue"
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a string name reference to your instance's IssueType for
# the lowest level of Issues (e.g., "user story") specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType Name
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
# Multiple comma-separated values can be specified.
#############################################################################
feature.jiraIssueTypeNames=Malicious Intent, Defect, CAC: Certification Issue Typenpot, Research/Inquiry, Advisory, Firewall, Purchase, Buffer, IT Help, Quality Issue in Production, Technical task, Certified, Production Bug, IT Change, Bug (DO NOT USE), Header/Footer, Idea, Improvement, DDL with DML, Monitor, Change, Initiative, Shared Services, QA Sub Task, RE, Web Element, Time Tracking, CAC: TIG Backlog Item, Logo Update, Policy Violation, Vulnerability, Terms Update, Incident, Response, Lost/Stolen Equipment, External Dependency Sub-Task, Lookup File/ReleaseBin, Engineering Sub-Task, File Failure, Epic, Data Analysis, DML (Data Manipulation Language), PCI, Scripts, Service Desk Request, CAC:, Defect Found Post-Release, DB Performance, CAC: Defect Found Internally, Access, Test, Fault, Sub-task, Task, BUG, AV/Malware, Direct Bank Integration, Phishing/SPAM, SOC1&2, Template, Story, DDOS, Maintenance and Support Agreement, Termination, Spike, AST Project, BT Knowledge Base, DDL (Data Definition Language), Infrastructure, Access Control, Trusty Help, CAC: Product Backlog Item, UX, Feature, Office Hardware, HIPAA, Document, New Hire, DLP, Emergency Change, Admin, Support

#############################################################################
# In Jira, your instance will have its own custom field created for "sprint" or "timebox" details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name com.atlassian.greenhopper.service.sprint.Sprint;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraSprintDataFieldName=customfield_10007

#############################################################################
# In Jira, your instance will have its own custom field created for "super story" or "epic" back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (e.g., epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraEpicIdFieldName=customfield_10300

#############################################################################
# In Jira, your instance will have its own custom field created for "story points"
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's storypoints ID field name via the following URI where your
# queried user story issue has story points set on it; your custom field name describes the
# story points value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraStoryPointsFieldName=customfield_10004

#############################################################################
# In Jira, your instance will have its own custom field created for "team"
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's team ID field name via the following URI where your
# queried user story issue has team set on it; your custom field name describes the
# team value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraTeamFieldName=customfield_10007

Any help is appreciated.

Thanks.

**Comment by nireeshT** [comment]
@shivamms  - Do you have projects and teams configured in Jira without having the tempo-team plugin ? If you have a custom field defined for teams, you could set it for the property below and see if it works. Else set it to blank and the UI will assume team = Any.

#############################################################################
# In Jira, your instance will have its own custom field created for "team"
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's team ID field name via the following URI where your
# queried user story issue has team set on it; your custom field name describes the
# team value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraTeamFieldName=

**Comment by shivamms** [comment]
Thanks for the quick reply. Much appreciated.

I left the team field blank. Now it says blank data for status:

![image](https://cloud.githubusercontent.com/assets/8627753/24115783/e1066736-0d7a-11e7-97b2-b45a85cfb244.png)

And there is no list down for project and others in UI though this could see that the collector for Jira is running:

![image](https://cloud.githubusercontent.com/assets/8627753/24115873/2bca7956-0d7b-11e7-9069-e705bace9ef9.png)

**Comment by shivamms** [comment]
There is no record available in the mongodb in feature collection though there is one record each in collector and collector items collections for Jira.

![image](https://cloud.githubusercontent.com/assets/8627753/24116099/ef607f1e-0d7b-11e7-9dcf-13b120e7c6b3.png)


![image](https://cloud.githubusercontent.com/assets/8627753/24116030/bed6ae36-0d7b-11e7-8b8f-f3d814517800.png)

**Comment by MarkRx** [comment]
What version of jira are you running?

**Comment by shivamms** [comment]
JIRA v1000.824.3

I guess it is hosted service.

**Comment by MarkRx** [comment]
You are running Jira Cloud. Per the REST api that call should work (https://docs.atlassian.com/jira/REST/1000.824.0/#api/2/status-getStatuses).

All of your responses are 500 errors. See if you can hit any of the REST api using a browser.

I have not tried Jira cloud.

**Comment by shivamms** [comment]
Yes. We are using cloud version. And when I hit this "https://xxxxxxxxxxxxxxx.atlassian.net/rest/api/2/status" with browser, i am getting full page json.

**Comment by shivamms** [comment]
I was able to fix it. It was primarily authentication issue. But since it did not give proper error response code (All I got was 500), I could not figure it out easily.
