### ISSUE TITLE
Spring security: pipeline in product level dashboard can't show when use the springSecurityIntergration branch.

### ISSUE THREAD

**Issue by wdquan1985** [capitalone/Hygieia#1254]
In order to use the ldap authentication function, I use the springSecurityIntergration https://github.com/StateFarmIns/Hygieia/tree/springSecurityIntegration.
The ldap authentication function works well, but the pipeline in the procuct level dashboard can't show.
![pipeline](https://cloud.githubusercontent.com/assets/15209842/24136508/0c614d68-0e4a-11e7-8d78-8d32369b2d83.png)

**Comment by nireeshT** [comment]
@wdquan1985  - remove team dashboard from product dash, reconfigure pipeline widget and add it back. Make sure code repo and build widgets are configured as well.

**Comment by wdquan1985** [comment]
@nireeshT , I configure the code repo and build widgets in their team level dashboard, remove team dashboard from product dash, and add it back, but still can't show pipeline.
![teamlevel](https://cloud.githubusercontent.com/assets/15209842/24179520/877c1154-0eea-11e7-943e-a6c81ffcdf4e.png)
![productlevel](https://cloud.githubusercontent.com/assets/15209842/24179524/8ef59a5e-0eea-11e7-8796-adff7b1658f4.png)
 And the pipeline data in mongo db has been produced.
![pipelines](https://cloud.githubusercontent.com/assets/15209842/24179562/ceb44410-0eea-11e7-97b1-f4fe31962ec5.png)

**Comment by nireeshT** [comment]
@wdquan1985  - you configured pipeline widget with custom stage names ?

**Comment by wdquan1985** [comment]
@nireeshT , I can't find anything, I can't find custom stage names.
![pipelineconfigure](https://cloud.githubusercontent.com/assets/15209842/24227931/d24904be-0fab-11e7-9624-4a32943f7628.png)
Is there anything wrong in my application?

**Comment by wdquan1985** [comment]
@nireeshT - additional information to explain, I add a configuration "feature.dynamicPipeline=enabled" in application.properties for api, so when request for pipeline info, it use dynamic pipeline service, and the value of property orderMap will not be set when build pipeline response, but this property will be used in the product level dash to show all the pipeline stages, so there is no any stage data shown.

**Comment by nireeshT** [comment]
@wdquan1985  - remove  "feature.dynamicPipeline=enabled" and re run api. You should see COMMIT and BUILD.

**Comment by MarkRx** [comment]
In order for the dynamic pipeline to work your git repo url must match what jenkins is reporting it is using. The branch must match as well. Turning on debug in the API should show you what is going on.

**Comment by wdquan1985** [comment]
@nireeshT , @MarkRx , I add the following code to the method buildPipelineResponse of DynamicPipelineServiceImpl.java file, it can work now.
        _pipelineResponse.setProdStage(PipelineUtils.getProdStage(dashboard));
        pipelineResponse.setOrderMap(PipelineUtils.getOrderForStages(dashboard));_
![dynamic](https://cloud.githubusercontent.com/assets/15209842/24286224/20c0de24-10af-11e7-85b9-5767caf88db4.png)

The dynamic pipeline service will be disabled in future? I think it's better than the pipeline service.

**Comment by nireeshT** [comment]
@wdquan1985  - sounds good. Have you tried removing "feature.dynamicPipeline=enabled" from properties to see product dashboard, want to make sure both dynamic pipeline and pipeline service are working as expected.

**Comment by wdquan1985** [comment]
@nireeshT - I had tried removing "feature.dynamicPipeline=enabled" from properties, but it can't work as well as adding "feature.dynamicPipeline=enabled". When remove it, assume that team dashboard 1 has pipeline stages data, add a new team dashboard 2, add the same build data and repo data to team dash 2, there will be no stages data of team dashboard 2.

**Comment by wdquan1985** [comment]
@nireeshT, @MarkRx - I think the goal of pipeline is to see movement of each code commit through the different development stages – code commit, build, deployment to DEV, QA, INT etc. all the way to production. Each of these stages shows the number of commits waiting to go to the next stage – amplifying the wait-times between the stages.

**Comment by MarkRx** [comment]
I have as of yet had time to go back and touch up the dynamic pipeline services to make it more robust. Basically the idea is to build the pipeline dynamically with the data on hand as opposed to building it when the data is added as this has a number of problems (https://github.com/capitalone/Hygieia/issues/804#issuecomment-247391585). Looks like that change you made adds in some missing logic that was added to the regular pipeline when custom names of environments were added.

**Comment by wdquan1985** [comment]
@MarkRx - My change only add prodStage and orderMap info in pipeline response, so the pipeline info can show in the product dash. Hope for the whole dynamical pipeline can work as soon as possible.

Thanks.

**Comment by nireeshT** [comment]
@wdquan1985  update to latest code base and check. Reopen if still issue.
