### ISSUE TITLE
Deploying UI in IIS

### ISSUE THREAD

**Issue by srinivas-n4u** [capitalone/Hygieia#1256]
Hello,

Can we deploy UI in microsoft IIS? I've created a website pointing to dist directory and started API component in 8888 port in same server. 
I am able to launch UI in browser but it is not connecting to API module. Tried url redirect and other ways in IIS to redirect :3000/api to :8888/api, still no luck.

Please help understand building/deploying UI component to work in IIS.

Thanks and Regards,
Srinivas

**Comment by nireeshT** [comment]
@srinivas-n4u  - have you configured server port to 8888 in application.properties/ dashboard.properties.

**Comment by srinivas-n4u** [comment]
I configured it in dashboard.properties but not in application.properties. Do we need to override in both places?

**Comment by nireeshT** [comment]
@srinivas-n4u  - share your command to run api.

**Comment by srinivas-n4u** [comment]
@nireeshT  - Please find the command below.

java -jar api.jar --spring.config.location=dashboard.properties

![image](https://cloud.githubusercontent.com/assets/1190268/24224778/7fe5a682-0f33-11e7-9445-17a63b5ffb22.png)

![image](https://cloud.githubusercontent.com/assets/1190268/24224794/98ff546a-0f33-11e7-8aa0-a0553f3ff69b.png)

**Comment by nireeshT** [comment]
@srinivas-n4u  - change the log level to DEBUG and run api and paste app log here.  
api -> logback.xml - change loglevel ="DEBUG"

**Comment by Sbrenthughes** [comment]
The UI is defaulted to point to 8080. You'll need to point it to 8888.
