### ISSUE TITLE
I would like to create new widget for AWS CodeDeploy. Any suggestion/idea? 

### ISSUE THREAD

**Issue by shivamms** [capitalone/Hygieia#1258]
We are using AWS CodeDeploy to deploy on premise servers. Can I create customized widget and add to dashboard? I may not need a collector to pull data from AWS and store it in MongoDB as I can do that part with a Python API. I would like to add the part which is used by UI.

**Comment by satishc1** [comment]
@shivamms Perhaps you could add a jenkins job which includes steps for   https://github.com/awslabs/aws-codedeploy-plugin and the hygieia plugin.  You won't need another widget because it should show up in the existing deploy widget in hygieia.

**Comment by satishc1** [comment]
@shivamms Please refer https://github.com/capitalone/Hygieia/issues/1037 for info on how to create custom collectors.
