### ISSUE TITLE
Login form broadcasts typing to other open browsers

### ISSUE THREAD

**Issue by MikePulcini** [capitalone/Hygieia#126]
When typing in the login form, the username/password are automatically populated in any other browsers that are currently viewing the login page, as you type. 

![17b4c6ce003b48164a270cddfd54cf49](https://cloud.githubusercontent.com/assets/2133246/9996665/0c9bd288-6056-11e5-9951-986b17711185.gif)

**Comment by MikePulcini** [comment]
This is also broadcasting passwords to other browsers on invalid login attempts.

![61fe7f16e5d321e1b5cda872f5ed765c](https://cloud.githubusercontent.com/assets/2133246/9997152/a4bd38de-6058-11e5-989e-e810448dcd3c.gif)

**Comment by amitmawkin** [comment]
Mike the gulp node server uses browser-sync http://www.browsersync.io/ for unified browser testing, so if you are using gulp serve it uses that plugin by default and from which ever browser you are accessing the local testing URL http://localhost:3000, 
You will not see this behavior if you run the UI in apache, node etc...

**Comment by amitmawkin** [comment]
let me know I can close this issue..

**Comment by jmh** [comment]
This really deserves a prominent mention in the docs. As it is now following your instructions to set up UI will result in the bizarre behavior above (extremely alarming if you don't know what's causing it).

**Comment by amitmawkin** [comment]
sure we can add this as an advice that gulp serve can have this behavior... , we will put that in our next update , closing this thread now
