### ISSUE TITLE
BitBucket authentication not working

### ISSUE THREAD

**Issue by maheshgohil1989** [capitalone/Hygieia#1260]
I generated key using below commands
java -jar target/core-2.0.5-SNAPSH
OT.jar com.capitalone.dashboard.util.Encryption
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further detail
s.
Your secret key is:
L+oZeib+QDiu2nBbtRwmUdVbkWKUHLov
Sample encrypted string with the above key for 'thisIsMyPassword' is:
tFgykCo/JuMjfWaddQkZpcy8fc2eQTS9

I put this key in api.properties 
key=L+oZeib+QDiu2nBbtRwmUdVbkWKUHLov

Also put in the bitbucket collector
git.product=server
git.key=L+oZeib+QDiu2nBbtRwmUdVbkWKUHLov

But when below url runs i got 401 unauthorized
2017-03-23 13:21:00,124 ERROR c.c.d.c.DefaultBitbucketServerClient - Cannot decrypt this message
Given final block not properly padded
2017-03-23 13:21:00,550 ERROR c.c.d.c.DefaultBitbucketServerClient - Failed to obtain commits from http://mycompany:7990/rest/api/1.0/projects/sfl/repos/backend-source/commits?until=master&limit=25
org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]

I get the commit info when hitting below on browser provide i login in browser. 
http://mycompany:7990/rest/api/1.0/projects/sfl/repos/backend-source/commits?until=master&limit=25

Is it something that i miss. Please help me out.

**Comment by rkhajja** [comment]
Any update on this. I had configured everything jira,jenkins,sonarqube except the git private repo.
Dashboard looks awesome but this issue correctly becomes the blocker for us. 
Please help me out.

**Comment by maheshgohil1989** [comment]
Any update on this. I had configured everything jira,jenkins,sonarqube except the git private repo.
Dashboard looks awesome but this issue correctly becomes the blocker for us. 
Please help me out.

**Comment by nireeshT** [comment]
@maheshgohil1989  - share your properties file.

**Comment by maheshgohil1989** [comment]
Thanks for your update.Below are the properties

Dashboard.properties 
===================
dbname=dashboard
dbusername=hygieia
dbpassword=hygieia
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=
server.contextPath=/api
server.port=3001
version.number=1.0.0
key=L+oZeib+QDiu2nBbtRwmUdVbkWKUHLov
==============================

BitBucket.properties
==========================================
dbname=dashboard
dbhost=localhost
dbport=27017
dbreplicaset=[false if you are not using MongoDB replicaset]
dbhostport=[host1:port1,host2:port2,host3:port3]
dbusername=hygieia
dbpassword=hygieia
logging.file=./logs/bitbucket.log
git.cron=0 0/1 * * * *

git.host=http://mycompany.com:7990/
git.api=/rest/api/1.0/

git.commitThresholdDays=15

git.pageSize=25

git.product=server
git.key=L+oZeib+QDiu2nBbtRwmUdVbkWKUHLov
==================================

**Comment by maheshgohil1989** [comment]
@nireeshT We also check bitbucket with public repository it works fine. 
We face issue with private repos.

**Comment by maheshgohil1989** [comment]
Any update on this.

**Comment by KMedhansh** [comment]
Any update on the above issues? I'm also facing same issue.

**Comment by oshingc** [comment]
Any update on this?

**Comment by meet101** [comment]
Any update on this. i am also facing an issue with Bitbucket private repo as per #1418

**Comment by dsanchezseco** [comment]
Same here!

**Comment by NikhilYadavGIT** [comment]
Hi @meet101, have u got any solution for it...Is it still throwing 404 error. I am also getting same.

**Comment by pallavi-d** [comment]
Getting same issue, any updates on this

**Comment by sachingupta771** [comment]
i'm also getting same issue even in the latest code pls help it worked earlier but now giving out the problem.

**Comment by pallavi-d** [comment]
Was getting 401 due to a special character in the password. Removed the special character and it worked

**Comment by sachingupta771** [comment]
I think I got the error 
The URL made is https://del.tools.publicis.sapient.com/projects/bitbucket/repos/scm/sk/kairos_initial/commits?until=release-1.2&limit=10
Whereas it needs to be 
Https://del.tools.publicis.sapient.com/bitbucket/scm/sk/kairos_initial.git



Thus /projects/ and /repos/ are extra thus it is not able to find the repo
Might be helpful if removed from this file hygieia/collectors/scm/bitbucket/src/test/java/com/capitalone/dashboard/collector/defaultbitbucketserverclienttest.java

**Comment by satishc1** [comment]
![image](https://user-images.githubusercontent.com/21199084/30386655-640ce960-9878-11e7-9f03-6373e9927f95.png)
