### ISSUE TITLE
Jenkins plugin- How to setup deploy widget?

### ISSUE THREAD

**Issue by Satheesh-b** [capitalone/Hygieia#1261]
I have added the hygieia-jenkins plugin in my jenkins. 
I would like to know what is the connectivity between the environments(dev,prod,qa) I specify in the plugin setup and the environments in the jenkins? I see there is no step to give the jenkins server in the plugin setup.

And also I would like to know how the environments are listed down in the "configure deploy widget" step.
I am not getting any environments in the dropdown.

Please clarify as soon as possible.

**Comment by nireeshT** [comment]
@Satheesh-b  -  make sure you give environment name in Hygieia publisher settings. Environment value is what displayed in deploy widget for the selected deploy job. Make sure Application name remains same for all the deploy jobs in different environments. Refer screenshot.
<img width="947" alt="screen shot 2017-03-23 at 9 30 41 am" src="https://cloud.githubusercontent.com/assets/22962180/24249974/a1301fa2-0fab-11e7-9a39-d17f02c41b6c.png">

**Comment by Satheesh-b** [comment]
@nireeshT thanks for the prompt reply. But where we are supposed to give the deployment environment URL(IP address) for each environment. How the plugin fetches the data from each environment without the URL?

Currently, my plugin returns environment URL which is as same of the Jenkins URL(Referred from environment_components table). It should point to each deployment environment URL. I would like to know where I should give the environment URL in the configuration for each environment.

**Comment by celamb4** [comment]
Im also having a similar issue. Jenkins plugin is deployed, configured and connect to Hygieia successfully. I then integrated the hygieia pipeline steps within my groovy script. Here is my example for deploy step:

`hygieiaDeployPublishStep applicationName: 'App name', artifactDirectory: 'app/target', artifactGroup: 'com.yourcompany.product1', artifactName: '*.jar', artifactVersion: '0.0.1', buildStatus: 'Success', environmentName: 'DEV'`

The pipeline finishes/passes but I'm not gettng a dropdown in the Hygieia deploy widget.

**Comment by satishc1** [comment]
@Satheesh-b Please follow the steps listed in https://github.com/capitalone/Hygieia/blob/master/hygieia-jenkins-plugin/README.md on how to configure the plugin.
And follow steps listed in https://github.com/capitalone/Hygieia/issues/884 on how to configure your deployment jobs.
The hygieia plugin does not need to know any information about "deployment environment URL(IP address) for each environment" . Your jenkins deploy job takes care of that based on what you specify for the deploy and the post build step tells Hygieia about a "successful" deployment.

**Comment by nireeshT** [comment]
@Satheesh-b @celamb4   - Reopen if issue not resolved.

**Comment by Satheesh-b** [comment]
@satishc1 
Thanks for your reply. I have successfully configured the plugin and able to get the information from local jenkins. But our actual requirement is to display the deployment information for an application which resides in a remote server.

How can I monitor an application deployed via jenkins into a remote server? In that case what would be the artifact directory?

**Comment by satishc1** [comment]
@Satheesh-b You can "monitor" a url using the monitor widget.

The artifact directory is on the jenkins server that builds the artifact. Your deployment job needs to have steps (eg.shell, pipeline etc) in the deploy job to "send" the artifact to the environment in question. The hygieia plugin doesn't monitor the artifact end location.

**Comment by celamb4** [comment]
@satishc1 Thank you for your reply. Just went over #884 not sure if I'm missing something since I'm still missing the data in the UI.

1. Hygieia jenkins plugin is configured and connects to hygieia api.
2. In my pipeline. I have added all steps from the hygieia plugin in their respected locations. For example, buildstatus, aritfact, deploy, etc.
3. I then go to the hygieia UI --> deploy widget but dont have any apps listed.

Here is the example of my hygieia deploy step in the jenkins pipeline.

`hygieiaDeployPublishStep applicationName: 'App name', artifactDirectory: 'app/target', artifactGroup: 'com.yourcompany.product1', artifactName: '*.jar', artifactVersion: '0.0.1', buildStatus: 'Success', environmentName: 'DEV'`

Thanks again!

**Comment by satishc1** [comment]
@celamb4 Assuming your artifact is being generated inside $yourjenkinsworkspace/app/target Try changing artifactDirectory: 'app/target'  to be artifactDirectory: '/app/target' 

Verify that you have a jar file inside $yourjenkinsworkspace/app/target 

Try that and if still an issue, please post your jenkins job log.

**Comment by celamb4** [comment]
artifactDirectory: '/app/target'

Did the trick! Thanks.

**Comment by Satheesh-b** [comment]
The **Deployed** status is always **false** in the **environment_components** table.  I am getting published deploy data: response code: 201 in jenkins pipeline console output. Because of this the deploy widget always be in red colour. 

1. When the deployed status will change to **true**?
2. Server up count is always 0 in deploy widget. why? I also see there is no environment_status table getting generated.

**Comment by syedsfayaz** [comment]
@Satheesh-b  Hi Sateesh, I am facing the similar issue. My deployment status is always true. So the pipeline is always green and if i intentionally fail the job. There is no update in mongo db. Any idea how you resolved this .

**Comment by Satheesh-Balachandran** [comment]
@syedsfayaz Change the buildStatus : "Failure" in hygieiaDeployPublishStep, if you have a condition to check the status of your deployment in pipeline and it reports that the deployment doesn't happen due to any reason.

**Comment by syedsfayaz** [comment]
@Satheesh-b @nireeshT I was trying to manually modify the status and i see this error. ( do we have any status apart from passed and failed)

db.environment_components.update({"_id" : ObjectId("5ac40ca105d8147f02b94d2b")},{$set:{"deployed" :InProgress}})
2018-04-04T13:41:25.284-0700 E QUERY    [thread1] ReferenceError: InProgress is not defined :
@(shell):1:88
