### ISSUE TITLE
Sonar quality configure code Analysis Widget disabled issue

### ISSUE THREAD

**Issue by elangesk** [capitalone/Hygieia#1266]
I was able to see sonar quality configure code Analysis Widget with drop downs. But now I am facing issue that configure code Analysis Widget disabled.

Please let me know the reason and how to slove this isse.

Regards,
Elanges

**Comment by elangesk** [comment]
@timgifford 
Please provide your suggestion to reslove this.

**Comment by elangesk** [comment]
@tabladrum 
  Added in the issue loop

**Comment by nireeshT** [comment]
@elangesk  - you using the owner of the dashboard(meaning same user who created dashboard) to configure sonar widget, otherwise it is read only.

**Comment by elangesk** [comment]
@nireeshT 
 Thanks for your quick reply. I am able to see "configure code Analysis Widget" and drop downs are disabled. 

Note: I used same user that drop downs were worked properly.

**Comment by nireeshT** [comment]
@elangesk  - run sonar collector and that should pull all your projects from sonar.

**Comment by elangesk** [comment]
Due to sonar self sign certificate updated and "sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: " error occurred. once imported certificate and placed in JAVA_HOME\jre\lib\security folder, then "**configure code Analysis Widget**" dropdowns working fine.
