### ISSUE TITLE
How is jenkins hygieia plugin related to jenkins build collector

### ISSUE THREAD

**Issue by alagus84** [capitalone/Hygieia#1267]
I see that the Jenkins build collector makes a rest call to Jenkins to get the instance jobs and returns the response json object with either the job or build details. 
How is the build data really made available as a result of the rest call from build collector?
Does the hygieialistener in the hygieia Jenkins plugin package intercepts this rest call and collects the build information and supplies it back?

I apologize if this is a novice question, please direct me to the post if this question is already answered.

I am in the process of collecting deploy data from Jenkins and I see this deploy data will be published from the listener on an overidden onCompleted method inside the listener, if deploy data is set to published in the plugin UI. I am currently getting only the build json response on the deploy job. I am expecting deploy json data as mentioned in the DeployDataCreateRequest.java dashboard model class in core api, not sure what step I am missing here

**Comment by nireeshT** [comment]
@alagus84 - When hygieia plugin is configured, hygieialistener wil push build and deploy data to MongoDB and supply it to UI.  Looks like you have done a partial configuration of hygieia publisher on jenkins job. Follow screenshot and check deploy settings and rerun jenkins, that should push deply details to Mongo. 
<img width="947" alt="screen shot 2017-03-23 at 9 30 41 am" src="https://cloud.githubusercontent.com/assets/22962180/24313166/32492d10-10b2-11e7-9b7a-e2c3bb85c662.png">

**Comment by alagus84** [comment]
I did configure the deploy job, but I will go back check if the configuration was correct or if I missed anything.
I am slightly confused when you said hygieialistener will push build and deploy data to mongodb.

I see following activity is done by Jenkins-build-collector
1. Hit mongodb to verify if the collector is present in the collector repository
2. Make a rest call to Get job count and the instance jobs from Jenkins by making recursive calls Jenkins, provided if there are subjobs
3. Hit Mongodb to get all the existing build jobs
4. Filter new jobs by comparing results from step 2 & 3
5. Add new job and build details to Mongo db

So from the above step, I see Jenkins build collector collects the job and build data from Jenkins and pushes it to mongo db

Following is what I see happening in Jenkins hygieia plugin
1) HygieiaListener has a lifecycle methods onstarted and oncompleted. onstarted publishes build data and oncompleted publishes build, artifact, sonar, test results, and deploy data
2) publish build data makes a rest call to jenkins and publishes build information and publish deploy data makes a rest call to Jenkins to retrieve and publish deploy information


First question is what is this listener configured to listen to?
Second question, to whom are they publishing this information to?
Thirdly, If Jenkins build collector retrieves the job and build data from Jenkins, reconciles and pushes the new job and build data to mongo db, what is the need to have a hygieia listener.

Again I am sorry if I am confusing you, but I am trying to understand the very existence of hygieialistener and the duties it does. Probably if my above 3 question were answered, that would shed me some light to proceed further. Thanks for your help

**Comment by nireeshT** [comment]
@alagus84  - Hygieia publisher plugin configuration does collect build data and deploy data if you configure in jenkins job as mentioned in screenshot. Two ways you can collect build data - either by using Jenkins build collector or by configuring Hygieia publisher plugin in Jenkins job like screenshot above( use either one way but not both). I am assuming you are using Hygieia publisher plugin, your second post said otherwise. 
Deploy data  can be collected - either using uDeploy collector or by configuring Hygieia publisher plugin(use either one). if you want to collect build and deploy data separately with different collectors, use Jenkins-build collector and uDeploy collector but not Hygieia publisher plugin.

**Comment by satishc1** [comment]
@alagus84 Closed. Reopen with screenshot or error log on a specific problem you are having.
