### ISSUE TITLE
Build Process on Mac.  

### ISSUE THREAD

**Issue by hughbrien** [capitalone/Hygieia#127]
MacOS build keeps failing because of permissions with "npm" 

Do you have additional instructions when this occurs.

**Comment by amitmawkin** [comment]
Hugh,
are you running behind a corporate proxy by any chance?..

**Comment by hughbrien** [comment]
No.  It's  file system permission.   I have shelved this build for now and decided to work on a Docker build.  I have everything working with the exception of the UI build process.  

Is there anyway you can describe or point me to the steps that I need execute in order to:

Create the Correction environment and dependencies.  : Versions of NodeJS, NPM, Mongo

**Comment by hughbrien** [comment]
I left out the UI build portion and I think most of it works.  

Reactor Summary:
[INFO] 
[INFO] com.capitalone.dashboard:Hygieia .................. SUCCESS [  0.249 s]
[INFO] com.capitalone.dashboard:core ..................... SUCCESS [  7.396 s]
[INFO] com.capitalone.dashboard:rest-api ................. SUCCESS [ 17.798 s]
[INFO] com.capitalone.dashboard:hudson-collector ......... SUCCESS [  1.468 s]
[INFO] com.capitalone.dashboard:sonar-collector .......... SUCCESS [  0.304 s]
[INFO] com.capitalone.dashboard:subversion-collector ..... SUCCESS [  0.353 s]
[INFO] com.capitalone.dashboard:github-collector ......... SUCCESS [  0.251 s]
[INFO] com.capitalone.dashboard:versionone-feature-collector  SUCCESS [  1.867 s]
[INFO] com.capitalone.dashboard:udeploy-collector ........ SUCCESS [  0.307 s]
[INFO] com.capitalone.dashboard:jira-feature-collector ... SUCCESS [  1.445 s]
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector  SUCCESS [  0.683 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS

**Comment by hughbrien** [comment]
I am trying to get through the UI build.  

Running into Dependency Hell on NodeJS and Gulp.   I did upgrade the Gulp to 3.9. I think I am close. 

 ------------------------------------------------------------------------
[INFO] Building com.capitalone.dashboard:UI 0.1.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ UI ---
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.23:install-node-and-npm (install node and npm) @ UI ---
[INFO] Node v0.12.0 is already installed.
[INFO] Found NPM version 2.7.1
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.23:npm (npm install) @ UI ---
[INFO] Running 'npm install --color=false' in /Users/hbrien/Software/Hygieia/UI
[ERROR] npm WARN package.json Dependency 'gulp' exists in both dependencies and devDependencies, using 'gulp@^3.9.0' from dependencies
[ERROR] npm WARN package.json karma-phantomjs-launcher@0.1.4 No README data
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.23:bower (bower install) @ UI ---
[INFO] Running 'bower install' in /Users/hbrien/Software/Hygieia/UI
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.23:gulp (gulp build) @ UI ---
[INFO] Running 'gulp build --no-color' in /Users/hbrien/Software/Hygieia/UI
[INFO] [11:15:06] Using gulpfile ~/Software/Hygieia/UI/gulpfile.js
[INFO] [11:15:06] Starting 'wiredep'...
[INFO] [11:15:06] Starting 'injector:css:preprocessor'...
[INFO] [11:15:06] Starting 'scripts'...
[INFO] [11:15:06] Starting 'consolidate:jade:app'...
[INFO] [11:15:06] Starting 'consolidate:jade:components'...
[INFO] [11:15:06] Starting 'images'...
[INFO] [11:15:06] Starting 'fonts'...
[INFO] [11:15:07] Starting 'misc'...
[INFO] [11:15:07] Finished 'consolidate:jade:app' after 430 ms
[INFO] [11:15:07] Finished 'consolidate:jade:components' after 278 ms
[INFO] [11:15:07] Starting 'consolidate:jade'...
[INFO] [11:15:07] Finished 'consolidate:jade' after 13 μs
[INFO] [11:15:07] Starting 'consolidate'...
[INFO] [11:15:07] Finished 'consolidate' after 7.24 μs
[INFO] [11:15:07] Starting 'partials'...
[INFO] [11:15:07] gulp-inject 7 files into index.less.
[INFO] [11:15:07] 'wiredep' errored after 922 ms
[INFO] [11:15:07] Error: EPERM, chmod '/Users/hbrien/Software/Hygieia/UI/src/index.html'
[INFO]     at Error (native)
[INFO] [11:15:07] 'injector:css:preprocessor' errored after 1.02 s
[INFO] [11:15:07] Error: EPERM, chmod '/Users/hbrien/Software/Hygieia/UI/src/app/index.less'
[INFO]     at Error (native)
[INFO] [11:15:07] Finished 'misc' after 420 ms
[INFO] 
[INFO] /Users/hbrien/Software/Hygieia/UI/src/app/chartist/plugins/tooltip.js
[INFO]   line 91  col 22  Don't make functions within a loop.
[INFO]   line 97  col 22  Don't make functions within a loop.
[INFO] 
[INFO]   ⚠  2 warnings
[INFO] 
[INFO] 
[INFO] /Users/hbrien/Software/Hygieia/UI/src/app/dashboard/controllers/site.js
[INFO]   line 121  col 10  Unnecessary semicolon.
[INFO] 
[INFO]   ⚠  1 warning
[INFO] 
[INFO] 
[INFO] /Users/hbrien/Software/Hygieia/UI/src/app/dashboard/directives/widget-container.js
[INFO]   line 87  col 33  Use '===' to compare with 'null'.
[INFO] 
[INFO]   ⚠  1 warning
[INFO] 
[INFO] [11:15:07] Finished 'images' after 830 ms
[INFO] [11:15:08] Finished 'fonts' after 1.21 s
[INFO] 
[INFO] /Users/hbrien/Software/Hygieia/UI/src/app/dashboard/core/extensions/ng-fitText.js
[INFO]   line 68  col 26  Don't make functions within a loop.
[INFO]   line 73  col 99  Expected an assignment or function call and instead saw an expression.
[INFO] 
[INFO]   ⚠  2 warnings
[INFO] 
[INFO] [11:15:08] Finished 'scripts' after 1.8 s
[INFO] [11:15:08] Finished 'partials' after 1.21 s
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] com.capitalone.dashboard:Hygieia .................. SUCCESS [  0.311 s]
[INFO] com.capitalone.dashboard:core ..................... SUCCESS [  8.288 s]
[INFO] com.capitalone.dashboard:rest-api ................. SUCCESS [ 21.685 s]
[INFO] com.capitalone.dashboard:hudson-collector ......... SUCCESS [  1.995 s]
[INFO] com.capitalone.dashboard:sonar-collector .......... SUCCESS [  0.304 s]
[INFO] com.capitalone.dashboard:subversion-collector ..... SUCCESS [  0.425 s]
[INFO] com.capitalone.dashboard:github-collector ......... SUCCESS [  0.295 s]
[INFO] com.capitalone.dashboard:versionone-feature-collector  SUCCESS [  1.823 s]
[INFO] com.capitalone.dashboard:udeploy-collector ........ SUCCESS [  0.318 s]
[INFO] com.capitalone.dashboard:jira-feature-collector ... SUCCESS [  1.641 s]
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector  SUCCESS [  0.774 s]
[INFO] com.capitalone.dashboard:UI ....................... FAILURE [ 11.357 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 49.817 s
[INFO] Finished at: 2015-09-28T11:15:08-05:00
[INFO] Final Memory: 70M/359M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.23:gulp (gulp build) on project UI: Failed to run task: 'gulp build --no-color' failed. (error code 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :UI
osxlthbrien:Hygieia hbrien$

**Comment by amitmawkin** [comment]
Brien,

Have you made code changes already, or you are trying to compile a vanilla project straight out of Github.
It looks like you are running into compilation issues… make sure your js and html compiles an easy way is just to run
Gulp build and it can give you the same output.

[INFO] [11:15:07] gulp-inject 7 files into index.less.
[INFO] [11:15:07] 'wiredep' errored after 922 ms
[INFO] [11:15:07] Error: EPERM, chmod '/Users/hbrien/Software/Hygieia/UI/src/index.html'
[INFO] at Error (native)
[INFO] [11:15:07] 'injector:css:preprocessor' errored after 1.02 s
[INFO] [11:15:07] Error: EPERM, chmod '/Users/hbrien/Software/Hygieia/UI/src/app/index.less'
[INFO] at Error (native)
[INFO] [11:15:07] Finished 'misc' after 420 ms

**Comment by hughbrien** [comment]
Sorry this has been a little confusing:

I am attempting two builds: Both are just standard builds from source.

One on my Mac

Another via Docker which implies UBuntu.  

I will open a new Issue for the Docker build so as to keep them separate.

**Comment by hughbrien** [comment]
I got the Mac build kind of running but I had to do 

sudo gulp serve
without it I get 

osxlthbrien:UI hbrien$ 
osxlthbrien:UI hbrien$  gulp serve
[13:30:48] Using gulpfile ~/Software/Hygieia/UI/gulpfile.js
[13:30:48] Starting 'consolidate:jade:app'...
[13:30:48] Starting 'consolidate:jade:components'...
[13:30:48] Starting 'wiredep'...
[13:30:48] Starting 'injector:css:preprocessor'...
[13:30:48] Starting 'themes-watcher'...
[13:30:48] Starting 'scripts'...
[13:30:48] Starting 'fonts'...
[13:30:48] Finished 'consolidate:jade:app' after 557 ms
[13:30:48] Finished 'consolidate:jade:components' after 419 ms
[13:30:48] Starting 'consolidate:jade'...
[13:30:48] Finished 'consolidate:jade' after 184 μs
[13:30:48] Starting 'consolidate'...
[13:30:48] Finished 'consolidate' after 5.86 μs
[13:30:48] gulp-inject 7 files into index.less.
[13:30:48] 'wiredep' errored after 444 ms
[13:30:48] Error: EPERM: operation not permitted, chmod '/Users/hbrien/Software/Hygieia/UI/src/index.html'
    at Error (native)
[13:30:49] 'injector:css:preprocessor' errored after 544 ms
[13:30:49] Error: EPERM: operation not permitted, chmod '/Users/hbrien/Software/Hygieia/UI/src/app/index.less'
    at Error (native)

/Users/hbrien/Software/Hygieia/UI/src/app/chartist/plugins/tooltip.js
  line 91  col 22  Don't make functions within a loop.
  line 97  col 22  Don't make functions within a loop.

  ⚠  2 warnings


/Users/hbrien/Software/Hygieia/UI/src/app/dashboard/controllers/site.js
  line 121  col 10  Unnecessary semicolon.

  ⚠  1 warning


/Users/hbrien/Software/Hygieia/UI/src/app/dashboard/directives/widget-container.js
  line 87  col 33  Use '===' to compare with 'null'.

  ⚠  1 warning

[13:30:51] Finished 'themes-watcher' after 3.05 s
[13:30:51] Finished 'fonts' after 3.22 s

/Users/hbrien/Software/Hygieia/UI/src/app/dashboard/core/extensions/ng-fitText.js
  line 68  col 26  Don't make functions within a loop.
  line 73  col 99  Expected an assignment or function call and instead saw an expression.

  ⚠  2 warnings

[13:30:52] Finished 'scripts' after 3.53 s

**Comment by amitmawkin** [comment]
closing this issue as your build was successful as reported
