### ISSUE TITLE
Docker Image - Get UI Up

### ISSUE THREAD

**Issue by tomservo11** [capitalone/Hygieia#1271]
I have followed the directions and have all prereqs installed on a linux CentOS vagrant box. I tried two separate ways, running manual install and by loading the Docker Images. I received no errors but when I run gulp serve I am unable to get the UI to load. Let me know if any more information is required.

Build Docker images and setup id for mongodb

Build the containers
mvn docker:build
Bring up the container images
docker-compose up -d
Create user in mongo (if you log into the container then you dont have to install mongo locally)
docker exec -t -i mongodb2 bash
mongo 192.168.64.2/admin  --eval 'db.getSiblingDB("dashboard").createUser({user: "db", pwd: "dbpass", roles: [{role: "readWrite", db: "dashboard"}]})'

[INFO] com.capitalone.dashboard:Hygieia ................... SUCCESS [  3.050 s]
[INFO] com.capitalone.dashboard:core ...................... SUCCESS [  0.022 s]
[INFO] com.capitalone.dashboard:api ....................... SUCCESS [01:55 min]
[INFO] com.capitalone.dashboard:artifactory-artifact-collector SUCCESS [ 18.892 s]
[INFO] com.capitalone.dashboard:bamboo-build-collector .... SUCCESS [ 19.087 s]
[INFO] com.capitalone.dashboard:jenkins-build-collector ... SUCCESS [ 18.278 s]
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SUCCESS [ 15.697 s]
[INFO] com.capitalone.dashboard:sonar-codequality-collector SUCCESS [ 15.978 s]
[INFO] com.capitalone.dashboard:aws-cloud-collector ....... SUCCESS [  0.028 s]
[INFO] com.capitalone.dashboard:udeploy-deployment-collector SUCCESS [ 20.326 s]
[INFO] com.capitalone.dashboard:xldeploy-deployment-collector SUCCESS [ 18.359 s]
[INFO] com.capitalone.dashboard:jira-feature-collector .... SUCCESS [ 26.041 s]
[INFO] com.capitalone.dashboard:versionone-feature-collector SUCCESS [ 20.682 s]
[INFO] com.capitalone.dashboard:gitlab-feature-collector .. SUCCESS [ 18.372 s]
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SUCCESS [ 15.490 s]
[INFO] com.capitalone.dashboard:bitbucket-scm-collector ... SUCCESS [ 19.003 s]
[INFO] com.capitalone.dashboard:github-scm-collector ...... SUCCESS [ 19.827 s]
[INFO] com.capitalone.dashboard:subversion-collector ...... SUCCESS [ 18.356 s]
[INFO] com.capitalone.dashboard:gitlab-git-collector ...... SUCCESS [ 16.043 s]
[INFO] com.capitalone.dashboard:UI ........................ SUCCESS [  8.822 s]

**Comment by deanchin** [comment]
Running into the same issue.  No errors in logs but the UI does not seem to populate (get a blank screen on http://localhost:8088/ )

**Comment by JackLeeZhang** [comment]
Please provide the docker the run command e.g : docker run XXXXX UI

**Comment by timja-kainos** [comment]
I hit this when trying to do docker-compose up, might be the same problem
https://github.com/capitalone/Hygieia/issues/1207

**Comment by matthewbeasley** [comment]
@tomservo11 - we have recently merged the first in a series of upgrades to our docker set up. Please update your clone of Hygieia and run `mvn clean install docker:build; docker-compose up -d` and you should have the api, ui and db up and running. I'm going to close this issue but if you have any questions of feedback, please feel free to open another or contact us via [gitter.im](https://gitter.im/capitalone/Hygieia)
