### ISSUE TITLE
Functional test 

### ISSUE THREAD

**Issue by jagadeeshkumarpatti** [capitalone/Hygieia#1273]
I have configured my functional test results using cucumber.json file and able to see success % for that particular module. 
![image](https://cloud.githubusercontent.com/assets/25560784/24374817/db2045b8-12fb-11e7-8ff1-8e27fccaf8b4.png)

Instead of seeing only success percentage, is it possible to display success, failure, skipped and total count of functional tests on the dashboard itself.
![image](https://cloud.githubusercontent.com/assets/25560784/24374763/a7896ba8-12fb-11e7-9e1d-3e967807b14b.png)

**Comment by satishc1** [comment]
@jagadeeshkumarpatti The quality widget is a combination of several things, hence it has limited space on what we can show directly on the dashboard. You could choose to create a new template and configure the widget based on your requirement.
