### ISSUE TITLE
Additional target for Collector collected data?

### ISSUE THREAD

**Issue by ceytalis** [capitalone/Hygieia#1274]
Question for the Hygieia community.  I have seen some issues posted here asking about the support for alternative datasources from MongoDB.  But, I was thinking of an alternative option from supporting alternative "datasource".

How much interest would there be for an enhancement to Hygieia that would enable collectors to send the data they collect to a configurable endpoint (e.g REST) in addition to going to MongoDB?  I was thinking this destination endpoint would be configured per collector.  The endpoint would be optional, so it is only executed if it is configured.

**Comment by satishc1** [comment]
@ceytalis What will be the role of the endpoint? Is it used by Hygieia in any way or is it some analytical tool ?

**Comment by ceytalis** [comment]
@satishc1 I saw the role of the endpoint as a way to share the data collection event preformed by Hygieia with systems external to Hygieia.  It is a notification that a particular data collection event took place and here is the data that was collected.  The system behind the endpoint could then do whatever it wants with the notification and data.
