### ISSUE TITLE
password encryption error: 

### ISSUE THREAD

**Issue by anuragmishracrest** [capitalone/Hygieia#1284]
I went through #856 

@satishc1 Do I have to specify my github username and password in github collectors properties file before generating key using core?
github.host=github.com
github.username=anuraXXXXX
github.password=XXXasaXXX

2nd you have mentioned api.properties but in your repo api.properties is not present
does it mean application.properties?

3rd will it work with 12factor enable repos?

**Comment by satishc1** [comment]
@anuragmishracrest Refer to encryption section in https://github.com/capitalone/Hygieia/blob/master/UI/README.md

Do I have to specify my github username and password in github collectors properties file before generating key using core?
github.host=github.com
github.username=anuraXXXXX
github.password=XXXasaXXX
No. In your github.properties you'll need
github.host=github.com
github.key=your-generated-key

2nd you have mentioned api.properties but in your repo api.properties is not present
does it mean application.properties?
The properties file that you use to launch the api module = api.properties or whatever you named it.

3rd will it work with 12factor enable repos?
Maybe not. Looking at https://github.com/blog/1614-two-factor-authentication it will need a token to authenticate for 2 factor repos. Might need a code change. Let us know how it goes.

**Comment by anuragmishracrest** [comment]
@satishc1 Thanks for the reply

I tried the above mentioned steps
It allows add repo to configure when I leave credential blank

Whenever I put credential it gives me error and It always gives "Error encrypting password."

apart from this I found that for 2factor enabled repo I need OTP with credential.

**Comment by satishc1** [comment]
@anuragmishracrest Paste your api.properties file and the command you use to launch the api.  Also paste your github.properties file and the command you use to launch the github collector.

**Comment by anuragmishracrest** [comment]
in github : `java -jar java -jar github-scm-collector-2.0.5-SNAPSHOT.jar --spring.config.location=application.properties`


`# Database Name
dbname=dashboard
# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
dbreplicaset=[false if you are not using MongoDB replicaset]
dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=dashboarduser

# Database Password - default is blank
dbpassword=dbpassword

# Logging File location
logging.file=./logs/github.log

# Collector schedule (required)
github.cron=0 0/5 * * * *

github.host=github.com

github.key=PuyhTPitKenTSkaMzcuU5Xr4ED0IdtOr

# Maximum number of days to go back in time when fetching commits
github.commitThresholdDays=15`

api : java -jar -Dserver.contextPath=/api api.jar --spring.config.name=api --spring.config.location=application.properties

```
dbname=dashboard
dbusername=dashboarduser
dbpassword=dbpassword
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
server.contextPath=/api
server.port=8080
key=PuyhTPitKenTSkaMzcuU5Xr4ED0IdtOr
```

**Comment by anuragmishracrest** [comment]
@satishc1 issue **resolved** 
Apisetting.java was not able to load key from application.properties.
at this moment I have had coded the Key
Will figure out why it is not be loaded from properties file.

Thanks
