### ISSUE TITLE
Getting an error after setting up hygieia plugin to collect build and deploy data for jenkins pre 2.0

### ISSUE THREAD

**Issue by alagus84** [capitalone/Hygieia#1290]
Hi, I followed the instruction to setup hygieia plugin to collect build and deploy data for Jenkins pre2.0 version and I don't see any build or deploy collectors in mongo db and therefore nothing is showing up in dashboard.

Following is the error I am getting.

[api_20170328_224947.txt](https://github.com/capitalone/Hygieia/files/886289/api_20170328_224947.txt)

Could you please let me know if I am missing any configuration that causes this null pointer exception

**Comment by satishc1** [comment]
@alagus84 Paste screenshots of your jenkins hygieia plugin config and the jenkins deploy job. Also attach your jenkins job log.

**Comment by alagus84** [comment]
@satishc1 Please find the screen shot attached for the deploy job configuration.
![deployjobfrompluginui](https://cloud.githubusercontent.com/assets/7706835/24667119/41a28ac8-1930-11e7-9835-390efed62eb2.jpg)

**Comment by nireeshT** [comment]
@alagus84  - do the same config for "Publish Artifact Information" as "Publish Deployment Results"

**Comment by alagus84** [comment]
@nireeshT Thank you. Will try that. I believe after setting Publish artifact information, a build/deploy job needs to triggered to invoke the plugin to collect the data, am I right? Or does the plugin collects the data automatically after the settings are saved in the ui?

**Comment by nireeshT** [comment]
@alagus84  That is correct, after setting artifact information trigger build and deploy so the plugin will push data to Mongo and then to UI.

**Comment by alagus84** [comment]
@nireeshT I now enabled publish artifact status also but nothing in DB yet. I looked at the build job log and I don't see any publish build status in the logs. Neither I see any logs in API logs. 

Am I watching the right logs?. Please let me know if u need any further info to trouble shoot

**Comment by nireeshT** [comment]
@alagus84 share screenshot for build widget config and deploy widget config . Do you see any values in dropdown for both config widgets

**Comment by alagus84** [comment]
@nireeshT no I don't see any values in drop down on both the widgets. I used to see values in build widget when I was using build collector. Later I stopped build collector and used new Db to get data through plugin alone. That's when the data stopped flowing to mongodb and therefore nothing is showing in UI

**Comment by alagus84** [comment]
@nireeshT I preferred to go with plugin because I wanted to collect deploy data as well. I'm not successful in writing a separate deploy collector for collecting deploy data from Jenkins as the Hudson rest API doesn't have / expose deploy tree information like it does for jobs and builds which build collector is using to collect builds and jobs data

**Comment by nireeshT** [comment]
@alagus84 paste screenshot of all the settings configured for this jenkins job

**Comment by alagus84** [comment]
@nireeshT 
Xml info for the same job:
<publishers>
   <jenkins.plugins.hygieia.HygieiaPublisher plugin="hygieia-publisher@2.0.5-SNAPSHOT">
     <hygieiaBuild>
       <publishBuildStart>true</publishBuildStart> 
     </hygieiaBuild>
     <hygieiaArtifact>
        <artifactName>csg.war</artifactName> 
        <artifactDirectory>csg/csg-ws/target/</artifactDirectory> 
        <artifactGroup>com.freddiemac.csg</artifactGroup> 
        <artifactVersion>0.0.1-SNAPSHOT</artifactVersion> 
     </hygieiaArtifact>
     <hygieiaDeploy>
        <artifactName>csg.war</artifactName> 
        <artifactDirectory>csg/csg-ws/target/</artifactDirectory> 
        <artifactGroup>com.freddiemac.csg</artifactGroup> 
        <artifactVersion>0.0.1-SNAPSHOT</artifactVersion> 
        <applicationName>csg</applicationName> 
        <environmentName>dev</environmentName> 
        <publishDeployStart>true</publishDeployStart> 
     </hygieiaDeploy>
   </jenkins.plugins.hygieia.HygieiaPublisher>
   ......
  </publishers>

api.properties:
dbname=dashboard
dbusername=xxxx
dbpassword=yyyy
dbhost=localhost
dbport=27017
dbreplicaset=false
#dbhostport=[host1:port1,host2:port2,host3:port3]
#server.contextPath=[Web Context path if any]
server.port=8080
version.number=@2.0.5@

**Comment by alagus84** [comment]
<publishers>
   <jenkins.plugins.hygieia.HygieiaPublisher plugin="hygieia-publisher@2.0.5-SNAPSHOT">
     <hygieiaBuild>
       <publishBuildStart>true</publishBuildStart> 
     </hygieiaBuild>
     <hygieiaArtifact>
        <artifactName>csg.war</artifactName> 
        <artifactDirectory>csg/csg-ws/target/</artifactDirectory> 
        <artifactGroup>com.freddiemac.csg</artifactGroup> 
        <artifactVersion>0.0.1-SNAPSHOT</artifactVersion> 
     </hygieiaArtifact>
     <hygieiaDeploy>
        <artifactName>csg.war</artifactName> 
        <artifactDirectory>csg/csg-ws/target/</artifactDirectory> 
        <artifactGroup>com.freddiemac.csg</artifactGroup> 
        <artifactVersion>0.0.1-SNAPSHOT</artifactVersion> 
        <applicationName>csg</applicationName> 
        <environmentName>dev</environmentName> 
        <publishDeployStart>true</publishDeployStart> 
     </hygieiaDeploy>
   </jenkins.plugins.hygieia.HygieiaPublisher>
   ......
  </publishers>

**Comment by alagus84** [comment]
{
   "jenkins.plugins.hygieia.HygieiaPublisher": {
      "@plugin": "hygieia-publisher@2.0.5-SNAPSHOT",
      "hygieiaBuild": {
         "publishBuildStart": "true"
      },
      "hygieiaArtifact": {
         "artifactName": "csg.war",
         "artifactDirectory": "csg/csg-ws/target/",
         "artifactGroup": "com.freddiemac.csg",
         "artifactVersion": "0.0.1-SNAPSHOT"
      },
      "hygieiaDeploy": {
         "artifactName": "csg.war",
         "artifactDirectory": "csg/csg-ws/target/",
         "artifactGroup": "com.freddiemac.csg",
         "artifactVersion": "0.0.1-SNAPSHOT",
         "applicationName": "csg",
         "environmentName": "dev",
         "publishDeployStart": "true"
      }
   }
}

**Comment by alagus84** [comment]
@nireeshT 
Unable to paste the xml, therefore converted xml message to json

{
   "jenkins.plugins.hygieia.HygieiaPublisher": {
      "@plugin": "hygieia-publisher@2.0.5-SNAPSHOT",
      "hygieiaBuild": {
         "publishBuildStart": "true"
      },
      "hygieiaArtifact": {
         "artifactName": "csg.war",
         "artifactDirectory": "csg/csg-ws/target/",
         "artifactGroup": "com.freddiemac.csg",
         "artifactVersion": "0.0.1-SNAPSHOT"
      },
      "hygieiaDeploy": {
         "artifactName": "csg.war",
         "artifactDirectory": "csg/csg-ws/target/",
         "artifactGroup": "com.freddiemac.csg",
         "artifactVersion": "0.0.1-SNAPSHOT",
         "applicationName": "csg",
         "environmentName": "dev",
         "publishDeployStart": "true"
      }
   }
}

Above is the job config details within jenkins

**Comment by nireeshT** [comment]
@alagus84  I meant the screenshot like the one you pasted earlier, this time full config details for csg-maven-build

**Comment by alagus84** [comment]
@nireeshT 
![job page1](https://cloud.githubusercontent.com/assets/7706835/24767121/e78403da-1acb-11e7-9ec4-737a239ac93d.jpg)
![job page2](https://cloud.githubusercontent.com/assets/7706835/24767130/f417e300-1acb-11e7-9700-6ec33d3df795.jpg)
![job page3](https://cloud.githubusercontent.com/assets/7706835/24767139/fb43ea48-1acb-11e7-877a-8d1c493d0ecf.jpg)
![job page4](https://cloud.githubusercontent.com/assets/7706835/24767148/02211bba-1acc-11e7-9113-7fa761be3276.jpg)
![job page5](https://cloud.githubusercontent.com/assets/7706835/24767152/080bcea8-1acc-11e7-86cb-017cd11e71a2.jpg)
![job page6](https://cloud.githubusercontent.com/assets/7706835/24767161/0fafaf76-1acc-11e7-83db-cfaea7cd67c4.jpg)
![job page7](https://cloud.githubusercontent.com/assets/7706835/24767167/189fdaf2-1acc-11e7-8b5b-84af56bb297d.jpg)
![job page8](https://cloud.githubusercontent.com/assets/7706835/24767176/1e57ea84-1acc-11e7-8c40-5cbe7a793827.jpg)
![job page9](https://cloud.githubusercontent.com/assets/7706835/24767184/2685c4f6-1acc-11e7-8a66-d00e5c646ae7.jpg)

**Comment by alagus84** [comment]
@nireeshT do you have any update on this?

**Comment by nireeshT** [comment]
@alagus84  enable GitHub project checkbox under General section and pass github url and then do commit and build.

**Comment by alagus84** [comment]
@nireeshT sure will give a try but could you shed some light as to why this option has anything to do with getting build and deploy data

**Comment by nireeshT** [comment]
@alagus84 Also did you setup Global Hygieia Publisher Settings

**Comment by alagus84** [comment]
@nireeshT Yes, I have added the Hygieia api module url and the test connection is successful

**Comment by alagus84** [comment]
@nireeshT Also we don't use GitHub rather use teamforge, Do you want me to provide teamforge url in place of github url?

**Comment by nireeshT** [comment]
@alagus84  Yep.

**Comment by alagus84** [comment]
@nireeshT 
![globalsettings](https://cloud.githubusercontent.com/assets/7706835/24817704/9cb8e696-1bab-11e7-9df3-b332d4c2ea62.jpg)

**Comment by nitin1706** [comment]
@alagus84 : are you still facing this issue.?

**Comment by nitin1706** [comment]
Closing this issue as no response. Re-open if needed
