### ISSUE TITLE
Running Gitlab behind Reverse Proxy

### ISSUE THREAD

**Issue by IAPOLINARIO** [capitalone/Hygieia#1291]
I'm running my Gitlab behind Nginx proxy. So, I'm using the context "/gitlab". But there's no way to configure Gitlab Collector to look to this context. The only possible configuration is to point directly to host:port.

**Comment by rob-miller-777** [comment]
@IAPOLINARIO Can you pull down this branch and try it?  Don't have a great way to test it here, but it should provide the functionality you are looking for.  If it works correctly, I will open a pull request.  https://github.com/StateFarmIns/Hygieia/tree/gitlabOptionalPath
