### ISSUE TITLE
Vulnerability in Logback Classic Module 1.1.3 of capitalone/Hygieia

### ISSUE THREAD

**Issue by curphey** [capitalone/Hygieia#1294]
Your **Logback Classic Module 1.1.3** library, a direct dependency in your **capitalone/Hygieia** repository, is subject to vulnerability [SID-3657: arbitrary code execution via serialization](https://www.sourceclear.com/registry/vulnerabilities/3657).

A direct dependency is a library that is specified in your project’s api/pom.xml.  A vulnerability in a direct dependency can be fixed by updating the version of the library in your project and rebuilding it.

This issue was fixed in version 1.2.0. However, that version may itself be subject to [other vulnerabilities](https://www.sourceclear.com/registry/libraries/434?version=1.2.0). We suggest that you upgrade to version 1.1.11, which is considered safe.

Be sure to build, test, and re-scan your project to ensure this fix has been successful.

##### api/pom.xml
```java
<dependency>
  <groupId>ch.qos.logback</groupId>
  <artifactId>1</artifactId>
  <version>1.1.11</version>
</dependency>
```

For more information on this vulnerability, please visit the [SourceClear Registry](https://www.sourceclear.com/registry/vulnerabilities/3657).

**Comment by rvema** [comment]
@curphey Please submit the PR with these changes and we can merge the same.
