### ISSUE TITLE
build hygieia project from github error 

### ISSUE THREAD

**Issue by marrwa** [capitalone/Hygieia#1295]
hello 
I have done a mvn clean install package for Hygieia project and got the below error:
Please help.

`[INFO] com.capitalone.dashboard:jenkins-build-collector .. SUCCESS [12.631s]
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector  SUCCESS [11.223s]
[INFO] com.capitalone.dashboard:sonar-codequality-collector  SUCCESS [5.811s]
[INFO] com.capitalone.dashboard:aws-cloud-collector ...... SUCCESS [6.880s]
[INFO] com.capitalone.dashboard:udeploy-deployment-collector  SUCCESS [8.710s]
[INFO] com.capitalone.dashboard:xldeploy-deployment-collector  SUCCESS [9.771s]
[INFO] com.capitalone.dashboard:jira-feature-collector ... SUCCESS [22.203s]
[INFO] com.capitalone.dashboard:versionone-feature-collector  SUCCESS [7.956s]
[INFO] com.capitalone.dashboard:gitlab-feature-collector . SUCCESS [13.075s]
[INFO] com.capitalone.dashboard:chat-ops-collector ....... SUCCESS [2.579s]
[INFO] com.capitalone.dashboard:bitbucket-scm-collector .. SUCCESS [8.335s]
[INFO] com.capitalone.dashboard:github-scm-collector ..... SUCCESS [7.003s]
[INFO] com.capitalone.dashboard:subversion-collector ..... SUCCESS [3.640s]
[INFO] com.capitalone.dashboard:gitlab-scm-collector ..... SUCCESS [6.668s]
[INFO] com.capitalone.dashboard:UI ....................... FAILURE [1.361s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3:43.629s
[INFO] Finished at: Wed Apr 05 16:46:01 CEST 2017
[INFO] Final Memory: 112M/544M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.6:single (create-archive) on project UI: Failed to create assembly: Error creating assembly archive src: You must set at least one file. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :UI
root@marwa-vbx:/home/marwa/Hygieia-master# ^C
root@marwa-vbx:/home/marwa/Hygieia-master# 
`
 bin.xml file:
 
 `<assembly xmlns="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.2"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.2 http://maven.apache.org/xsd/assembly-1.1.2.xsd">
    <id>src</id>
    <formats>
        <format>tar.gz</format>
    </formats>
    <fileSets>
        <fileSet>
            <directory>${project.basedir}/dist</directory>
            <includes>
                <include>**/*</include>
            </includes>
            <useDefaultExcludes>true</useDefaultExcludes>
        </fileSet>
    </fileSets>
</assembly>`

**Comment by omarmahmoudi** [comment]
hi marwa i have also the same problem please if you get any answer let me now

**Comment by nireeshT** [comment]
@marrwa  @omarmahmoudi  - maven version ? upgrade to latest and try.

**Comment by marrwa** [comment]
my maven version is 3.1.0 
should i upgrade it to maven 4 ?

**Comment by marrwa** [comment]
@nireeshT i've upgrade my maven to the latest version and the error it is the same.

`Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.6:single (create-archive) on project UI: Failed to create assembly: Error creating assembly archive src: You must set at least one file. -> 
`

**Comment by nireeshT** [comment]
@marrwa @omarmahmoudi  are you using mvn clean install or mvn clean install package . Use mvn clean install

**Comment by marrwa** [comment]
@nireeshT  i've used mvn clean install

**Comment by nireeshT** [comment]
@marrwa @omarmahmoudi  - 
1) Which java version used ? use java 8. 
2) try deleting full .m2 local repository and rebuild. 
3) if still issue run -> mvn clean install -X to find root cause

**Comment by marrwa** [comment]
@nireeshT do u know please how to connect to the hygieia api? which login and password should i put ?

**Comment by nireeshT** [comment]
@marrwa - run api from target folder with below command 

java -jar api.jar --spring.config.location=dashboard.properties

For dashboard.properties file refer https://github.com/capitalone/Hygieia/tree/master/api - README.md

From UI folder -> gulp serve 

Once Hygieia is launched on localhost, you can sign up users

**Comment by nireeshT** [comment]
@marrwa @omarmahmoudi  Reopen if issue is not resolved.

**Comment by marrwa** [comment]
thank u @nireeshT  i'll try it

**Comment by marrwa** [comment]
@nireeshT  where can i find plz the dashboard.properties file ?? should i create it somewhere ?

**Comment by nireeshT** [comment]
@marrwa create dashboard.properties in any location and reference the same location in below command to run api 
java -jar api.jar --spring.config.location=<location>/dashboard.properties
or 
create dashboard.properties and drop it in your api project and run below command. 
java -jar api.jar --spring.config.location=dashboard.properties

**Comment by marrwa** [comment]
i got this error when running the cmd  : java -jar api.jar --spring.config.location=/dashboard.properties

>` Exception in monitor thread while connecting to server 127.0.0.1:27017
com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='dashboarduser', source='dashboard', password=<hidden>, mechanismPrope`
 and in the properties file i've put the correct properties and i can connect  successfully on mongo with `mongo -u *** -p***`  
i don't know really where is the prb ??

**Comment by nireeshT** [comment]
@marrwa  did you start mongo? if not follow http://www.capitalone.io/Hygieia/getting_started.html#database

**Comment by marrwa** [comment]
yes i've started mongod and I'm able to logon to the mongodb from mongo shell fine.
i don't understand where is the prb ??

**Comment by marrwa** [comment]
@nireeshT i've run the hygieia dashboard and i want to run and configure collectors, starting with jenkins  i've copy this cmd to my shell 
`java -Jar hudson-collector.jar` and i see that i'm unable to access to this jar file .
where can i find it please ??

**Comment by nireeshT** [comment]
@marrwa  - 
1)  run mvn clean install on root Hygieia
2) go to target folder of  Hygieia/collectors/build/jenkins/ target/ and run that command. Make sure that jar file is present in that folder ( or change name of hudson-collector.jar in your command to whatever it is in that location). 
3) Create a properties file for Hudson/Jenkins collector, place it in local and refer the same location in below command from target folder 
java -jar jarfilename.jar --spring.config.location=location you copied/jenkins.properties

Refer this link for sample jenkins properties : http://www.capitalone.io/Hygieia/jenkinsbuild_collector.html 

Do similar steps for all the collectors, create different properties for each collector. I prefer to copy all prop files in same location and refer them in run command. 
Refer : https://developer.capitalone.com/opensource-projects/hygieia/

**Comment by marrwa** [comment]
@nireeshT  After building successfully the project when i run this cmd under target folder  `java -jar jenkins-build-collector-2.0.5-SNAPSHOT.jar` 

 i've got the below error: 

` Exception encountered during context initialization - cancelling refresh attempt org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hudsonCollectorTask': Invocation of init method failed; nested exception is java.lang.NullPointerException`
 
and when i search from the internet i understand  that this is a  problem with Spring and Jackson versions? should i downgrade the spring version or this is not the real cause ??

**Comment by nireeshT** [comment]
@marrwa  use this command 

java -jar jenkins-build-collector-2.0.5-SNAPSHOT.jar --spring.config.location=location you copied/jenkins.properties

**Comment by marrwa** [comment]
thanks @nireeshT  my application is started but when i want to start the UI with gulp serve i can't connect to the api ?? should i configure something ??

**Comment by nireeshT** [comment]
@marrwa  check in api log if you see errors.

**Comment by marrwa** [comment]
@nireeshT  i've fixed this error i can connect to the api thank u but when running collector: Hudson with java -jar jenkins-build-collector-2.0.5-SNAPSHOT.jar --spring.config.location=application.properties i got the below  error 
 `  com.capitalone.dashboard.Application - Started Application in 14.006 seconds (JVM running for 16.141)
2017-04-20 16:20:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2017-04-20 16:20:00,061 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-04-20 16:20:00,062 INFO  c.c.d.collector.CollectorTask - http://127.0.0.1:8080
2017-04-20 16:20:00,063 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-04-20 16:20:00,232 ERROR c.c.d.collector.DefaultHudsonClient - client exception loading jobs
org.springframework.web.client.HttpClientErrorException: 403 Forbidden`

`Error getting jobs for: http://127.0.0.1:8080`

and i'm sure that 127.0.0.1:8080 is my jenkins url. what can i do plz ?

**Comment by nireeshT** [comment]
@marrwa  - use this url in properties file - https://username:password@127.0.0.1:8080

use jenkins username and pwd

**Comment by marrwa** [comment]
@nireeshT  i can't  access to jenkins with https url  i have acces to it with http only and when i put http://admin:admin@127.0.0.1:8080 it doesn't work the erro is the same. :/

**Comment by marrwa** [comment]
@nireeshT it seems that  my jenkins collector doesn't work correctly.. it can't collect data from build jobs  to show it on hygieia dashboard. i got the below erro : 


`2017-05-02 17:39:04,957 INFO  com.capitalone.dashboard.Application - Started Application in 26.322 seconds (JVM running for 30.531)
2017-05-02 17:40:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2017-05-02 17:40:00,256 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-05-02 17:40:00,258 INFO  c.c.d.collector.CollectorTask - http://admin:admin@localhost:8080
2017-05-02 17:40:00,262 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-05-02 17:40:00,981 INFO  c.c.d.collector.CollectorTask - Fetched jobs                     0s
2017-05-02 17:40:00,985 INFO  c.c.d.collector.CollectorTask - New jobs                0        0s
2017-05-02 17:40:01,430 ERROR c.c.d.collector.DefaultHudsonClient - Client exception loading build details: 403 Forbidden. URL =http://localhost:8080/job/my_first_job/2/
2017-05-02 17:40:01,721 ERROR c.c.d.collector.DefaultHudsonClient - Client exception loading build details: 403 Forbidden. URL =http://localhost:8080/job/my_first_job/1/
2017-05-02 17:40:02,003 ERROR c.c.d.collector.DefaultHudsonClient - Client exception loading build details: 403 Forbidden. URL =http://localhost:8080/job/job2/2/
2017-05-02 17:40:02,351 ERROR c.c.d.collector.DefaultHudsonClient - Client exception loading build details: 403 Forbidden. URL =http://localhost:8080/job/job2/1/
2017-05-02 17:40:02,354 INFO  c.c.d.collector.CollectorTask - New builds              0        1s
2017-05-02 17:40:02,358 INFO  c.c.d.collector.CollectorTask - Finished                         2s
`
what can i do plz

**Comment by marrwa** [comment]
> 2017-05-03 11:08:05,320 INFO  com.capitalone.dashboard.Application - Started Application in 20.463 seconds (JVM running for 24.008)
2017-05-03 11:10:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2017-05-03 11:10:00,257 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-05-03 11:10:00,261 INFO  c.c.d.collector.CollectorTask - http://admin:admin@localhost:8080
2017-05-03 11:10:00,262 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-05-03 11:10:03,140 INFO  c.c.d.collector.CollectorTask - Fetched jobs                     3s
2017-05-03 11:10:03,144 INFO  c.c.d.collector.CollectorTask - New jobs                0        0s
2017-05-03 11:10:04,244 ERROR c.c.d.collector.DefaultHudsonClient - Client exception loading build details: 403 Forbidden. URL =http://localhost:8080/job/my_first_job/2/
2017-05-03 11:10:04,898 ERROR c.c.d.collector.DefaultHudsonClient - Client exception loading build details: 403 Forbidden. URL =http://localhost:8080/job/my_first_job/1/
2017-05-03 11:10:05,515 ERROR c.c.d.collector.DefaultHudsonClient - Client exception loading build details: 403 Forbidden. URL =http://localhost:8080/job/job2/2/
2017-05-03 11:10:06,091 ERROR c.c.d.collector.DefaultHudsonClient - Client exception loading build details: 403 Forbidden. URL =http://localhost:8080/job/job2/1/
2017-05-03 11:10:06,093 INFO  c.c.d.collector.CollectorTask - New builds              0        2s
2017-05-03 11:10:06,096 INFO  c.c.d.collector.CollectorTask - Finished                         6s

**Comment by monabhardwaj** [comment]
Has anyone tried making a custom collector? It would be a great help if you could share some input regarding the same. Thank You!

**Comment by marrwa** [comment]
@nireeshT  hi niresht  i would like to know how data is proccessed from the api to the ui . i have to customize the sonar widget and the api to display the history of several analysis . thank you for your help in advance .

**Comment by nitin1706** [comment]
@marrwa :  for UI code, you can refer to code under Hygieia/UI and similarly for api, you can refer to code under: Hygieia/api. UI makes REST calls to API to get the processed data.
