### ISSUE TITLE
few mins, KT possible?

### ISSUE THREAD

**Issue by smsuresh** [capitalone/Hygieia#1299]
Iam planning to create collectors for servicenow & HP-ALM,  is it possible for you spare few mins on explaining me the current code flow. so that it'll be easy to create..
I shall create pull request once everything is fine!

**Comment by nireeshT** [comment]
@smsuresh  Please message me on gitter.im

**Comment by satishc1** [comment]
@smsuresh Please refer https://github.com/capitalone/Hygieia/issues/1037 for info on how to create custom collectors. And msg on gitter.

**Comment by monabhardwaj** [comment]
Hello! I'm new to Hygieia and currently attempting to create a custom collector. I have gone through various articles on the same but weren't of much help on the beginner level. It would be invaluable for me if could extend any advice or sample projects on how you got your custom collector working. Also the current code flow so I could conveniently get started .@smsuresh  @nireeshT 
Thank You!
