### ISSUE TITLE
Values not displaying in Security Analysis and Functional Tests sections.

### ISSUE THREAD

**Issue by pauljanis** [capitalone/Hygieia#130]
Values not displaying in Security Analysis and Functional Tests sections in the Quality Widget.  This has been an issue for months with no timeline of when it's going to be resolved.  When Hygieia was introduced to the world this issue was present.  At one time when the product was called Dash it worked.

![image](https://cloud.githubusercontent.com/assets/14823365/10076870/40e1bd4c-62a3-11e5-9f36-f90221ac0249.png)

**Comment by tabladrum** [comment]
Are you using cucumber/jenkins for functional tests?

**Comment by pauljanis** [comment]
Yes.  I’ve chosen a few different tests just to see if anything shows numbers with no luck.

Paul Janis
Quality Engineer, Galactic Republic
630-346-7333 (Cell)
paul.janis2@capitalone.com<mailto:paul.janis2@capitalone.com>

[cid:image001.gif@01D0F6B1.16775CF0]

**Comment by pauljanis** [comment]
Hi tabladrum,

Has this been fixed yet?

Thanks,

Paul Janis
Quality Engineer, Galactic Republic
630-346-7333 (Cell)
paul.janis2@capitalone.com<mailto:paul.janis2@capitalone.com>

[cid:image001.gif@01D0F776.02ECA850]

From: Janis, Paul (CONT)
Sent: Thursday, September 24, 2015 10:09 AM
To: 'capitalone/Hygieia'; capitalone/Hygieia
Subject: RE: [Hygieia] Values not displaying in Security Analysis and Functional Tests sections. (#130)

Yes.  I’ve chosen a few different tests just to see if anything shows numbers with no luck.

Paul Janis
Quality Engineer, Galactic Republic
630-346-7333 (Cell)
paul.janis2@capitalone.com<mailto:paul.janis2@capitalone.com>

[cid:image001.gif@01D0F776.02ECA850]

**Comment by aniketvsawant** [comment]
Hi, I am using spock for unit and functional testing. As current hygieia implementation only supports cucumber, it doesnt get all the details in analysis dashboard. Is there work around this issue ? please assist. Thanks.

**Comment by tabladrum** [comment]
A rewrite (enhanced) version of the cucumber integration is in the works. You can test it out from the "cucumber" branch. Currently there is no support for spock. It is easy to create one - you need to write a "collector" (see JenkinsCucumber collector for example).

**Comment by tabladrum** [comment]
See latest Hygieia 2.0 documentation for how to publish test results from jenkins to hygieia. Here is a picture sample working job:

![image](https://cloud.githubusercontent.com/assets/6014941/13815521/496ce968-eb61-11e5-969a-832400ac4db7.png)
