### ISSUE TITLE
Api documentation link is not working

### ISSUE THREAD

**Issue by subratafouzder** [capitalone/Hygieia#1300]
Hi 
This is not really an  issue but can you please enable the Api documentation link.
![api_doc_not_working](https://cloud.githubusercontent.com/assets/7325473/24758366/ce800184-1aff-11e7-8306-ab5354b38975.JPG)

**Comment by satishc1** [comment]
@subratafouzder In the meantime you can use this link http://www.capitalone.io/Hygieia/getting_started.html   and scroll down to the "API Layer"

**Comment by Megha849** [comment]
@subratafouzder - The API documentation link is updated: https://github.com/capitalone/Hygieia/blob/gh-pages/pages/hygieia/setup.md
