### ISSUE TITLE
Multiple jenkins instance on Hygieia running on Linux instance

### ISSUE THREAD

**Issue by Ishan1987** [capitalone/Hygieia#1301]
I am trying to configure 2 Jenkins instance in hygieia by updating the dashboard.properties but its allowing me either of them to be configured. How can we configured multiple jenkins instance in hygieia to fetch data of build job in different dashboard?

Please let me know if you require more detail.

**Comment by satishc1** [comment]
@Ishan1987 Run one jenkins collector and specify jenkins.servers[0] and jenkins.servers[1] in its properties file.

**Comment by Ishan1987** [comment]
Thanks @satishc1 for your reply. I have tried to add two jenkins instance as suggested "jenkins.servers[0] and jenkins.servers[1]" with jenkins urls but Hygieia is fetching data for 1 instance and for other its throwing below error "**ERROR c.c.d.collector.DefaultHudsonClient - Client exception loading build details: 403 Forbidden. URL**" though when i am defining 1 instance at a time ( Any one from 2) its working so i am expecting no access related error.

**Comment by satishc1** [comment]
@Ishan1987 Are you using the latest codebase ? Post the jenkins collector log and your dashboard properties file.

**Comment by Ishan1987** [comment]
@satishc1 No i have old codebase. Does new codebase support "mutiple Jenkins instance" ?

**Comment by satishc1** [comment]
@Ishan1987 Update your codebase and try it.

**Comment by satishc1** [comment]
@Ishan1987 Closed. Reopen if still an issue.

**Comment by Ishan1987** [comment]
@satishc1  Thanks for your suggestion. After upgrading hygieia codebase , its able to fetch data of "Build job" on hygieia dashboard.
