### ISSUE TITLE
Hygieia - Conference Call

### ISSUE THREAD

**Issue by amitmawkin** [capitalone/Hygieia#1307]
Calling all folks who are actively participating in Hygieia development. Please see discussion topic below on the agenda and please feel free to add more if needed.

Topics

- Hygieia Github Code Base restructuring
- Hygieia Build optimization

@tabladrum & I will facilitate with dates/logistics etc.

If you would like to be included please tag yourself to this thread.

**Comment by amitmawkin** [comment]
Tagging some known contributors.
@MarkRx 
@rob-miller-777 
@jaredsmith 
@brennanananan 
@swizzley

**Comment by rob-miller-777** [comment]
#1293 Which might go hand in hand with restructuring the code base.

**Comment by alagus84** [comment]
@alagus84

**Comment by amitmawkin** [comment]
We are still working on the logistics and approvals from our end. Just wanted to check on everyone's willingness to attend the call. Please respond to this thread

**Comment by rob-miller-777** [comment]
@brennanananan and I are planning on attending.

**Comment by alagus84** [comment]
@alagus84 adding myself. Yes interested

**Comment by swizzley** [comment]
@amitmawkin ready and willing

**Comment by xpdable** [comment]
@xpdable Shall I ? We've got some resource and willing to contribute to the project

**Comment by satishc1** [comment]
@xpdable Absolutely.

**Comment by gttps** [comment]
@gttps

**Comment by anjana83** [comment]
@anjana83

**Comment by sibaom** [comment]
@sibaom interested

**Comment by amitmawkin** [comment]
thanks all , will be sending the date and time for this shortly. Thanks for showing the interest.

**Comment by amitmawkin** [comment]
Guys here are the logistics details for the meetings

May 25 2PM EST. 

https://hangouts.google.com/call/ej44lzyjbrfjjoc7mf6he5jmrqu

**Comment by amitmawkin** [comment]
Talk to you all tomorrow. Please join and discuss the features you all want in Hygieia and help  shape up the roadmap

**Comment by amitmawkin** [comment]
https://hangouts.google.com/call/ej44lzyjbrfjjoc7mf6he5jmrqu

**Comment by amitmawkin** [comment]
Talk to all of you at 2pm E.S.T today please do try to attend

https://hangouts.google.com/call/ej44lzyjbrfjjoc7mf6he5jmrqu

**Comment by rob-miller-777** [comment]
Didn't catch at the end how you were going to send out that roadmap.

**Comment by tabladrum** [comment]
@rob-miller-777 send me your contact email to tapabrata.pal@capitalone.com

**Comment by amitmawkin** [comment]
Thanks all for attending. Great to see and hear you all
