### ISSUE TITLE
Stash Collector using wrong port

### ISSUE THREAD

**Issue by vinodhkumarvm** [capitalone/Hygieia#1309]
I configured stash properties with below host. 

`git.host=https://stash.******.com:7990`

But collector is failing with error `ERROR c.c.d.c.DefaultBitbucketServerClient - Failed to obtain commits from https://stash.******.com:7999/rest/api/1.0/projects/devops/repos/sandbox/commits?until=master&limit=25` by using wrong port.

Why the collector is trying to use 7999 when actual is 7990.

My rest api is absolutely working with the 7990 `https://stash.******.com:7990/rest/api/1.0/projects/devops/repos/sandbox/commits?until=master&limit=25` when i hit in browser.

Please advice.

**Comment by MarkRx** [comment]
It is using the git url that is setup in the UI. One of your dashboards must be using a URL with port 7999.

**Comment by satishc1** [comment]
@vinodhkumarvm Closed. Reopen if still an issue.
