### ISSUE TITLE
API version 2.0.5 not found

### ISSUE THREAD

**Issue by stevenmherring** [capitalone/Hygieia#1312]
[ERROR] Failed to execute goal on project api: Could not resolve dependencies for project com.capitalone.dashboard:api:jar:2.0.5-SNAPSHOT: Could not find artifact com.capitalone.dashboard:core:jar:2.0.5-SNAPSHOT -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project api: Could not resolve dependencies for project com.capitalone.dashboard:api:jar:2.0.5-SNAPSHOT: Could not find artifact com.capitalone.dashboard:core:jar:2.0.5-SNAPSHOT

Should we convert and use 2.0.4 since that is still available, or is 2.0.5 expected?

**Comment by satishc1** [comment]
@stevenmherring Run mvn clean package install from the root of hygieia. That will create the core jar you are missing.

**Comment by stevenmherring** [comment]
Right, I went through the steps via dev exchange site. Doing that still gets `Could not resolve dependencies for project com.capitalone.dashboard:api:jar:2.0.5-SNAPSHOT:` when trying to build [API]

**Comment by satishc1** [comment]
@stevenmherring Try mvn clean package install in the core project. And check whether the core file gets installed in your local repo.

**Comment by stevenmherring** [comment]
core-2.0.5-SNAPSHOT.jar and core-2.0.5-SNAPSHOT.jar.original both exist

I appreciate the help by the way.

**Comment by satishc1** [comment]
@stevenmherring No problem. Try this https://github.com/capitalone/Hygieia/issues/1219

**Comment by satishc1** [comment]
@stevenmherring Closed. Reopen if still an issue.
