### ISSUE TITLE
Hygieia jenkins plugins build issues

### ISSUE THREAD

**Issue by maheshgohil1989** [capitalone/Hygieia#1314]
I try to build Hygieia jenkins plugins by executing comand - mvn clean package and got below errors

Downloading: http://repo.jenkins-ci.org/public/com/capitalone/dashboard/Hygieia/
2.0.5-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata com.capitalone.dashboard:Hygieia:2.0.5-SNA
PSHOT/maven-metadata.xml from/to repo.jenkins-ci.org (http://repo.jenkins-ci.org
/public/): repo.jenkins-ci.org
Downloading: http://repo.jenkins-ci.org/public/com/capitalone/dashboard/Hygieia/
2.0.5-SNAPSHOT/Hygieia-2.0.5-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.125 s
[INFO] Finished at: 2017-04-12T14:54:00+05:30
[INFO] Final Memory: 22M/421M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project hygieia-publisher: Could not resolve d
ependencies for project org.jenkins-ci.plugins:hygieia-publisher:hpi:2.0.5-SNAPS
HOT: Failed to collect dependencies at com.capitalone.dashboard:core:jar:2.0.5-S
NAPSHOT: Failed to read artifact descriptor for com.capitalone.dashboard:core:ja
r:2.0.5-SNAPSHOT: Could not transfer artifact com.capitalone.dashboard:Hygieia:p
om:2.0.5-SNAPSHOT from/to repo.jenkins-ci.org (http://repo.jenkins-ci.org/public
/): repo.jenkins-ci.org: Unknown host repo.jenkins-ci.org -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException

Can someone please help me out?
I use the latest code and also build the core before building this plugins.

**Comment by nireeshT** [comment]
@maheshgohil1989  https://github.com/capitalone/Hygieia/issues/1219

**Comment by satishc1** [comment]
@maheshgohil1989 Closed. Reopen if still an issue.

**Comment by maheshgohil1989** [comment]
Still issue 
[ERROR] Failed to execute goal on project hygieia-publisher: Could not resolve d
ependencies for project org.jenkins-ci.plugins:hygieia-publisher:hpi:2.0.5-SNAPS
HOT: Failed to collect dependencies at com.capitalone.dashboard:core:jar:2.0.5-S
NAPSHOT: Failed to read artifact descriptor for com.capitalone.dashboard:core:ja
r:2.0.5-SNAPSHOT: Could not find artifact com.capitalone.dashboard:Hygieia:pom:2
.0.5-SNAPSHOT in repo.jenkins-ci.org (http://repo.jenkins-ci.org/public/) -> [He
lp 1]
[ERROR]

**Comment by maheshgohil1989** [comment]
Also http://repo.jenkins-ci.org/public/ doesn't contains com.capitalone.dashboard:Hygieia:pom:2
.0.5-SNAPSHOT

**Comment by maheshgohil1989** [comment]
@satishc1  Please open this issue.

**Comment by maheshgohil1989** [comment]
Face lots many issue in building hygiene jenkins plugins. Please help me out. 
Does any body else able to build this plugins.If yes then please provide hpi file so that i can put in my jenkins ,

**Comment by maheshgohil1989** [comment]
mvn clean package
[INFO] Scanning for projects...
[WARNING] The POM for org.jenkins-ci.tools:maven-hpi-plugin:jar:1.106 is missing
, no dependency information available
[WARNING] Failed to build parent project for org.jenkins-ci.plugins:hygieia-publ
isher:hpi:2.0.5-SNAPSHOT
[WARNING]
[WARNING] Some problems were encountered while building the effective model for
org.jenkins-ci.plugins:hygieia-publisher:hpi:2.0.5-SNAPSHOT
[WARNING] 'parent.relativePath' of POM org.jenkins-ci.plugins:hygieia-publisher:
2.0.5-SNAPSHOT (D:\Installation\hygieia\code\Hygieia\hygieia-jenkins-plugin\pom.
xml) points at com.capitalone.dashboard:Hygieia instead of org.jenkins-ci.plugin
s:plugin, please verify your project structure @ line 15, column 13
[WARNING] 'build.plugins.plugin.version' for org.jacoco:jacoco-maven-plugin is m
issing. @ line 190, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten t
he stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support buildin
g such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Hygieia Publisher Plugin 2.0.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.jenkins-ci.org/public/org/jenkins-ci/main/jenkins-war/1
.609.2/jenkins-war-1.609.2.war
Downloading: http://repo.jenkins-ci.org/public/org/jenkins-ci/main/jenkins-war/1
.609.2/jenkins-war-1.609.2-war-for-test.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 09:50 min
[INFO] Finished at: 2017-04-24T15:47:57+05:30
[INFO] Final Memory: 28M/597M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project hygieia-publisher: Could not resolve d
ependencies for project org.jenkins-ci.plugins:hygieia-publisher:hpi:2.0.5-SNAPS
HOT: The following artifacts could not be resolved: org.jenkins-ci.main:jenkins-
war:war:1.609.2, org.jenkins-ci.main:jenkins-war:jar:war-for-test:1.609.2: Could
 not transfer artifact org.jenkins-ci.main:jenkins-war:war:1.609.2 from/to repo.
jenkins-ci.org (http://repo.jenkins-ci.org/public/): GET request of: org/jenkins
-ci/main/jenkins-war/1.609.2/jenkins-war-1.609.2.war from repo.jenkins-ci.org fa
iled: Premature end of Content-Length delimited message body (expected: 68976099
; received: 13944387 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException

**Comment by maheshgohil1989** [comment]
Today i am able to build the plugins. No need to open the ticket.

**Comment by seshudanda27** [comment]
Mahesh
can you please let us know what are the steps followed. 
I am new to the Hygieia & JAVA and I am getting the similar exceptions.
Can you please help to let us know the detailed steps you have performed.
