### ISSUE TITLE
Sonar widget-All the projects are not getting listed in the drop down

### ISSUE THREAD

**Issue by chethanbs** [capitalone/Hygieia#1320]
Collector is fetching 500 projects from sonarqube which i can see in sonar collector logs.

But only few projects are getting listed in the sonarqube widget 

Also i don't see it as drop down box.It just looks as search box.when I enter few letter of any projects then it will just list few projects.

Please let me know what could be the issue

**Comment by satishc1** [comment]
@chethanbs It is a paginated search box. Read through the PR contribution for details https://github.com/capitalone/Hygieia/pull/1068

**Comment by chethanbs** [comment]
Awesome.thank you..it works fine now

**Comment by satishc1** [comment]
@chethanbs Good to know its working.
