### ISSUE TITLE
unable to open swagger-ui , with api running

### ISSUE THREAD

**Issue by smsuresh** [capitalone/Hygieia#1324]
Hi,
  I did setup the whole Hygieia project,  started mongodb  & api.
  API seem to be running fine, but unable to see API/any details using swagger UI.
 
 Please help to find the gap.

Below are the URLs I tried..
http://localhost:8080/
http://localhost:8080/swagger-ui.html
http://localhost:8080/swagger/index.html
http://localhost:8080/api/swagger-ui.html

**Comment by satishc1** [comment]
@smsuresh https://github.com/capitalone/Hygieia/issues/987

**Comment by smsuresh** [comment]
Thankyou @satishc1
