### ISSUE TITLE
API docker properties-builder.sh is missing authentication properties

### ISSUE THREAD

**Issue by MarkRx** [capitalone/Hygieia#1326]
A number of properties are missing from the docker properties builder.

https://github.com/capitalone/Hygieia/blob/master/api/docker/properties-builder.sh

> auth.expirationTime=[JWT expiration time in milliseconds]
> auth.secret=[Secret Key used to validate the JWT tokens]
> auth.ldapServerUrl=[LDAP Server Url, including port of your LDAP server]
> auth.ldapUserDnPattern=[LDAP User Dn Pattern, where the username is replaced with '{0}']

@rob-miller-777 @nireeshT

**Comment by satishc1** [comment]
@MarkRx @rob-miller-777 @nireeshT Planning a pr soon which will include the fixes.

**Comment by rob-miller-777** [comment]
Yeah, I am the worst when it comes to updating the docker props...

**Comment by MarkRx** [comment]
This was added in #1354.
