### ISSUE TITLE
IntelliJ (or Eclipse) settings

### ISSUE THREAD

**Issue by vanjos** [capitalone/Hygieia#1328]
I started to poke around and wanted to start some work on Gitlab CI and another project management platform.

Would be nice to have a quickstart for contributing to this project as well as settings to use (for IntelliJ / Eclipse).

**Comment by satishc1** [comment]
@vanjos Please refer https://github.com/capitalone/Hygieia/issues/1037 for info on how to create custom collectors. Thanks to @mrpudn for compiling the list.

In regards to IntelliJ settings, you should just be able to import as maven project and step through the defaults. Let us know if you run into any issues.
