### ISSUE TITLE
Code Repo Widget - Duplicate messages

### ISSUE THREAD

**Issue by jas5843** [capitalone/Hygieia#133]
The code repo widget is pulling in the same commit message multiple times (i.e. when clicking on the code repo graph). The longer you keep your dashboard active in your browser, the more messages appear.

**Comment by tabladrum** [comment]
@jas5843 do you still see the issue? If not can we close this?

**Comment by jas5843** [comment]
Yes, this is fixed, this can be closed. Thank you.
