### ISSUE TITLE
hygieia jenkins plugin sonar authentication

### ISSUE THREAD

**Issue by cpham831** [capitalone/Hygieia#1330]
Hello,
Is it possible to pass in authentication to the hygieiaSonarPublishStep?
I tried wrapping the step in the withSonarQubeEnv {} block to use the authentication token set for the Sonar plugin on Jenkins, but it doesn't seem to take it.

**Comment by satishc1** [comment]
@cpham831 Have you supplied the authentication in the jenkins "SonarQube servers" section?

**Comment by cpham831** [comment]
Yes, I tried "Server authentication token" and also setting sonar.username/sonar.login and sonar.password in "Additional analysis properties" under Sonarqube configurations in Jenkins. I should note the sonar version I am using only allows token which is why I set the username and password as additional analysis properties

**Comment by cpham831** [comment]
Issue resolved, I used the ',' to separate sonar.login and sonar.password instead of space. That was dumb of me.
