### ISSUE TITLE
Jira collector not updating status of issues when it is changed in Jira

### ISSUE THREAD

**Issue by shivamms** [capitalone/Hygieia#1332]
Jira collector not updating status of issues in mongodb when it is changed in Jira, hence not reflecting correct status of issues in the dashboard...

**Comment by git4giri** [comment]
Yes I'm also facing same issue...
After deleting the 'feature' collection its fetching all updates... but its not the solution... 
Please give some inputs on this...

**Comment by shivamms** [comment]
I did not get any solution from CapitalOne so I am in the process of
writing my own collector in Python which will check for the updates and
keep the status up to-date.

**Comment by tabladrum** [comment]
There is a design flaw we discovered. It's all due to some timing of data change in JIRA and data collection - certain scenarios can cause JIRA api to fail and the collector does not go back and retry to collect the data. We are working to fix it.

**Comment by satishc1** [comment]
@shivamms Try out the latest codebase.

**Comment by sri1256** [comment]
I have also tried latest update.But it same issue, it is not updating.Can you please help me asap.

**Comment by sri1256** [comment]
@satishc1,I have also tried latest update.But it same issue, it is not updating.Can you please help me asap. 
@tabladrum, this is blocker for everyone.

**Comment by tomusaleem** [comment]
I'm facing same issue. I don't know this issue is resolved or not. I think this is some datetime issue. In my case api make a call to fetch updates from jira with my local datatime which is 10 hours ahead than UTC time that jira use. If I call with 10 hours earlier than mentioned time in call then it fetch latest update. But I don't know how to fix this is jira collector api
@tabladrum Can you please update about it
Thanks

**Comment by rvema** [comment]
@tomusaleem can you check the latest version of jira collector from [hygieia-feature-jira-collector](https://github.com/Hygieia/hygieia-feature-jira-collector)

**Comment by tomusaleem** [comment]
@rvema thanks for your response. 
I'm using latest version of jira-collector. I figured out the issue. It was local time zone and jira timezone mismatch. I sync my local timezone with jira timezone then jira collector started to get updated status of issue.

I have another issue. My jira board has some sub-task issue against each story. jira collector is fetching those issues also and putting in database. I can see in database but UI is not displaying those sun-task issues. UI displayed story issues only. Can you guide about this.
Thanks

**Comment by rvema** [comment]
> @rvema thanks for your response.
> I'm using latest version of jira-collector. I figured out the issue. It was local time zone and jira timezone mismatch. I sync my local timezone with jira timezone then jira collector started to get updated status of issue.
> 
> I have another issue. My jira board has some sub-task issue against each story. jira collector is fetching those issues also and putting in database. I can see in database but UI is not displaying those sun-task issues. UI displayed story issues only. Can you guide about this.
> Thanks

@Sbrenthughes any thoughts on this?
