### ISSUE TITLE
Jenkin is used as deployment tool

### ISSUE THREAD

**Issue by chethanbs** [capitalone/Hygieia#1334]
We are using jenkin as both build and deployment tool.
So is there anyway that I can configure jenkin as deployment tool in deploy widget and pull the details  into the dashboard?

**Comment by rob-miller-777** [comment]
There is a jenkins plugin which can report deployment status back to the API.  [Hygieia Publisher Plugin](https://github.com/capitalone/Hygieia/tree/master/hygieia-jenkins-plugin)

**Comment by chethanbs** [comment]
Thank you

**Comment by satishc1** [comment]
@chethanbs Please refer to https://github.com/capitalone/Hygieia/issues/884. Reopen if still an issue.

**Comment by chethanbs** [comment]
I am using groovy script for creating pipeline build.This plugin works with
groovy script as well?

**Comment by rob-miller-777** [comment]
It does, there is a script syntax generator for it.

**Comment by chethanbs** [comment]
One more thing.sorry for too many questions.

I have my Jenkins and Hygieia hosted on two different server.

The jenkin plugin needs to installed by manually uploading the file from
target folder.
  I have Hygieia core package on different server.

How do I communicate between two severs? Is there anyway to pull data about
deployment from other server?

**Comment by rob-miller-777** [comment]
To get it to work, you need to install the Hygieia Publisher Plugin on jenkins, and have the Hygieia API running somewhere.  It doesn't matter where the API is running as long as you have the url to the api.  After the Plugin is installed and the API is up, go to "Manage Jenkins", and then "Configure System".  Go down to the Hygieia section, and put the url for the API in there.  Click "Apply", and then test connection to see if it can hit the API properly.  These instructions should be in the link I referenced above as well.
