### ISSUE TITLE
Hygieia cost benefit!!

### ISSUE THREAD

**Issue by smsuresh** [capitalone/Hygieia#1336]
As a member of technology group, I realize the huge potential of Hygieia and its uses through out the delivery cycle.

But, Is there anyway I can link this to "Cost benefit" to my new management!! Who is purely a business person & looks only share values!!.

Basically I want to convince him for the time to enhance  this tool (with new collectors ) for integrating with other applications.

Please help.

**Comment by smsuresh** [comment]
@tabladrum

**Comment by satishc1** [comment]
@smsuresh @tabladrum You could point out Hygieia's benefit in terms of tracking code all the way from commit to production. If used with the right set of collectors it is a one-stop shop for tracking code quality from inception of a project to delivery. You could request @brennanananan @rob-miller-777 @MarkRx to give you more information on how their respective organizations have benefitted from using / contributing to Hygieia.

**Comment by tabladrum** [comment]
We have not done any cost benefit. It came out of DevOps strategy work. There are enough DevOps patterns available, in general, that makes a strong argument about a transparent and rapid feedback  mechanism. Hygieia addresses (tries to) this from Delivery Pipeline perspective.

**Comment by smsuresh** [comment]
Thankyou @satishc1 @tabladrum !!
@brennanananan @rob-miller-777 @MarkRx   - Please add if you find anything else shall be highlighted!!
