### ISSUE TITLE
publish docker images

### ISSUE THREAD

**Issue by jdamick** [capitalone/Hygieia#134]
Publish images to docker hub

**Comment by amitmawkin** [comment]
docker images are published here 

https://hub.docker.com/search/?q=capitaloneio&page=1&isAutomated=0&isOfficial=0&starCount=0&pullCount=0

closing the issue

**Comment by jdamick** [comment]
Please remove that, i'm working with dockerhub to get us access to the capitalone namespace..

**Comment by hughbrien** [comment]
Are you going to do a separate container for Mongo?

**Comment by hughbrien** [comment]
docker run -it -d  -p 3000:3000   --name hygieia-ui  capitaloneio/hygieia-ui  /bin/bash;
docker run -it -d   -p 8080:8080  --name hygieia-api  capitaloneio/hygieia-api  /bin/bash;

**Comment by hughbrien** [comment]
Where is all the code in the Containers. 

docker run -it -d -p 3000:3000 --name hygieia-ui capitaloneio/hygieia-ui /bin/bash;
docker run -it -d -p 8080:8080 --name hygieia-api capitaloneio/hygieia-api /bin/bash;

**Comment by amitmawkin** [comment]
Sorry Hugh was  busy , so could not respond to it earlier, 

What do you mean when you say Where is all the code in the containers?

**Comment by hughbrien** [comment]
Where in the file systems on the respective containers is the code installed? 

OR/AND

What are the instructions after starting the Containers?  

Do I hit a URL.  

Do I have to start a service? 

Where is the documentation for using them?

**Comment by jdamick** [comment]
sorry for the delayed response, please see: https://github.com/capitalone/Hygieia/blob/master/Setup.md

**Comment by tabladrum** [comment]
@jdamick @amitmawkin can we close this?

**Comment by amitmawkin** [comment]
yes the docker images are published under correct org
