### ISSUE TITLE
js error when click the save button

### ISSUE THREAD

**Issue by arthur657834** [capitalone/Hygieia#1344]
dashboard.js:29 Dashboard Object {id: "58f0bcebdce3b51308cbe45c", template: "capone", title: "ljtesthygieia", widgets: Array[5], owners: Array[1]…}
bower.js:15606 TypeError: Cannot read property '$setValidity' of undefined
    at config.js:99
    at processQueue (bower.js:18103)
    at bower.js:18119
    at Scope.$eval (bower.js:19401)
    at Scope.$digest (bower.js:19215)
    at Scope.$apply (bower.js:19509)
    at done (bower.js:13489)
    at completeRequest (bower.js:13698)
    at XMLHttpRequest.requestLoaded (bower.js:13626)
(anonymous) @ bower.js:15606
(anonymous) @ bower.js:12114
processQueue @ bower.js:18111
(anonymous) @ bower.js:18119
$eval @ bower.js:19401
$digest @ bower.js:19215
$apply @ bower.js:19509
done @ bower.js:13489
completeRequest @ bower.js:13698
requestLoaded @ bower.js:13626

anyone know?

**Comment by nireeshT** [comment]
@arthur657834  - refer https://github.com/capitalone/Hygieia/issues/1245

**Comment by nireeshT** [comment]
@arthur657834  - reopen if still issue

**Comment by arthur657834** [comment]
i had import the certificate，and i have the same error
