### ISSUE TITLE
Unable to link Hygieia containers to mongo DB due to authentication failure

### ISSUE THREAD

**Issue by SatwikBanerjee** [capitalone/Hygieia#1346]
Hi - Weirdly when I used the yml file most of the image names had to be changed to capitalone/hygieia-*
after the images were downloaded none of them can link to mongo DB due to authentication failure -

hygieia-github                         | Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=172.17.0.2:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='db', source='dashboard', password=<hidden>, mechanismProperties={}}}, caused by {com.mongodb.MongoCommandException: Command failed with error 18: 'Authentication failed.' on server 172.17.0.2:27017. The full response is { "ok" : 0.0, "errmsg" : "Authentication failed.", "code" : 18, "codeName" : "AuthenticationFailed" }}}]

Is anyone else facing this issue with the capitalone images? Else is there a password reset required in mongo DB?

**Comment by nireeshT** [comment]
@SatwikBanerjee  - Check if mongo image is created with source dashboard, user = db and password.

**Comment by SatwikBanerjee** [comment]
Yea thanks. Sorry I forgot to update that I resolved this from a different copy of the docker-compose file.
https://raw.githubusercontent.com/jdewinne/Hygieia/d323e08483c5a2a399f4cf4e846a79f37e883ee3/docker-compose.yml

This has the DB names. I am not sure why the main docker-compose file in this site is missing relevant details like image name, DB name.

This issue can now be closed.
