### ISSUE TITLE
Hygieia-publisher plugin Issue

### ISSUE THREAD

**Issue by ritusingh16** [capitalone/Hygieia#1349]
Followed all the step as mentioned in the following link
https://github.com/capitalone/Hygieia/tree/master/hygieia-jenkins-plugin

1. Installed plugin on Jenkins server  successfully
2. Global Level Configuration for the hygieia-publisher plugin in Jenkins is also successful
3. Job level configuration for hygieia publisher is also done, but after build in Jenkins no logs related with hygieia is present
Last few line of logs as follows:
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.487 s
[INFO] Finished at: 2017-04-21T03:59:53-04:00
[INFO] Final Memory: 29M/314M
[INFO] ------------------------------------------------------------------------
[JENKINS] Archiving /home/BWalton/.jenkins/workspace/Rally_Github_Jenkins_integration/pom.xml to com.sample.mvc/ems_db-master/1.0-SNAPSHOT/ems_db-master-1.0-SNAPSHOT.pom
[JENKINS] Archiving /home/BWalton/.jenkins/workspace/Rally_Github_Jenkins_integration/target/ems_db-master.war to com.sample.mvc/ems_db-master/1.0-SNAPSHOT/ems_db-master-1.0-SNAPSHOT.war
channel stopped
Collecting metadata...
Metadata collection done.
Finished: SUCCESS

**No sign of hygieia publisher task running at all.** 

Jenkins version : 2.32
hygieia-Jenkins plugin version : 2.0.5-SNAPSHOT
maven version : 3.21
java version : 1.8

**Any assistance is appreciated!!**

**Comment by nireeshT** [comment]
@ritusingh16  - have you configured Hygieia publisher settings in Jenkins job -> configure. If so, paste the screenshot, mask the confidential information if necessary.

**Comment by rob-miller-777** [comment]
What version of Java is your jenkins server running on? You can find this by going to "Manage Jenkins" then "System Information".  The reason I ask is because I had similar issues myself having a jenkins server running on java 7.  The plugin would throw unsupported major/minor version errors in jenkins log, but not the build logs, so it would freeze a "pipeline" job, and just wouldn't see anything in a normal jenkins job.

**Comment by ritusingh16** [comment]
@nireeshT - Yes all configuration is done 
PFA
[Global level Configuration.docx](https://github.com/capitalone/Hygieia/files/960412/Global.level.Configuration.docx)

Thanks for the reply

**Comment by ritusingh16** [comment]
@rob-miller-777 

You pointed out correctly, Jenkins server running on java 7

Thanks for the help.
