### ISSUE TITLE
team size metrics

### ISSUE THREAD

**Issue by jdamick** [capitalone/Hygieia#135]
Add the ability to track the team members, either just the number of members or names too as they change over time.  Also track when team members are on vacation / off the project (temporarily).

This will provide a way for the dashboard to plot the number of team members for a given sprint / release as another metric to feed into the project health.  

@tabladrum think this is of value to anyone?

**Comment by tabladrum** [comment]
I would like to put this out of Hygieia as there are similar work going on elsewhere.
