### ISSUE TITLE
Hygieia Authentication

### ISSUE THREAD

**Issue by montapas** [capitalone/Hygieia#1352]
Dear all,
Can I login in Hygieia without login prompt. I mean it will take my PC logged in user credential automatically and navigate to my dashboard page directly. 
Please help me.
With Regards,
Tapas

**Comment by nireeshT** [comment]
@montapas  - Hygieia is view only for all unless logged in as owner of dashboard to edit it. You can view all dashboards with out login by directly going to Hygieia home.

**Comment by satishc1** [comment]
@montapas SSO integration is not available yet, however ldap and ActiveDirectory support exists.

**Comment by vikramgudi89** [comment]
@satishc1 @nireeshT 
hey, I'm trying to integrate  the LDAP with Hygieia, it's not working,
is a change required in the code
