### ISSUE TITLE
ERROR o.s.b.c.e.tomcat.TomcatStarter - Error starting Tomcat context: org.springframework.beans.factory.BeanCreationException

### ISSUE THREAD

**Issue by stevenmherring** [capitalone/Hygieia#1355]
Running 'mvn clean package install' from the root dir. All builds return success. I can launch the UI with no issues.

Attempting to start the api from ../api/target with 'java -jar api.jar --spring.config.location=dashboard.properties'

I can't get the API to start up, first error is 
ERROR o.s.b.c.e.tomcat.TomcatStarter - Error starting Tomcat context: org.springframework.beans.factory.BeanCreationException

The log can be found here > [output.txt](https://github.com/capitalone/Hygieia/files/962783/output.txt)

Thanks!

**Comment by nireeshT** [comment]
@stevenmherring  - just try mvn clean install on root Hygieia. 
I see below error in your log 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webSecurityConfig':

**Comment by stevenmherring** [comment]
Unfortunately I get the same results

**Comment by dpost** [comment]
I'm getting the same thing as well trying to run the api in a docker container. Any update?

**Comment by nitin1706** [comment]
@stevenmherring : try using the complete command for running api: 
java -jar api.jar --spring.config.name=api --spring.config.location=dashboard.properties'

**Comment by nitin1706** [comment]
Use `mvn clean install package` on root Hygieia, and then run api using `java -jar /location/of/api.jar --spring.config.name=api --spring.config.location=/location/of/dashboard.properties` 
and then run UI by going to Hygieia/UI/target location -> `gulp serve` 

Build with the latest code using the command mentioned above.  Re-open if issue exists.
