### ISSUE TITLE
Jenkins Collector: 403 Forbidden error generated when jenkins.saveLog = true

### ISSUE THREAD

**Issue by canary6** [capitalone/Hygieia#1359]
The following error is generated when jenkins.saveLog = true in the applications.services file when the jenkins collector is run. In DefaultHudsonClient.java, when getLog() is invoked at line ~288, the credentials are not provided, resulting in the following error:

Client exception loading build details: 403 Forbidden.

This is with the credentials set in the application.services file.

**Comment by canary6** [comment]
This is with the credentials set in the application.services file.

**Comment by tabladrum** [comment]
We are going to remove that feature - a bad performance bottleneck. For now, please set saveLog to false;

**Comment by Sbrenthughes** [comment]
@canary6 - Please reopen if you have anymore issues.
