### ISSUE TITLE
LDAP integration does it support ldaps or https protocol

### ISSUE THREAD

**Issue by gokulknewt** [capitalone/Hygieia#1361]
@Team,

Could you please suggest me?
We are implementing the LDAP integration with hygieia dashboard. In application.properties file
Can we use ldaps or https protocol instead of ldap protocol.

Regards,
Gokul k

**Comment by satishc1** [comment]
@gokulknewt It supports both ldap and ldaps. For AD support you can try https://github.com/capitalone/Hygieia/pull/1374

**Comment by satishc1** [comment]
@gokulknewt Try latest codebase and reopen if still an issue.

**Comment by gokulknewt** [comment]
@Satishc1,
Thank you satish..One more quick clarification...
I taken the latest code.To connect the active directory our Active directory uname and paswword it will ask.For that how to define auth.ldapUserDnPattern from properties file.

LDAP directory located at below this conf..

**auth.ldapServerUrl=ldap://dc1.qcorpaa.aa.com:389
auth.ldapUserDnPattern= ???(We have a clarification on userdn pattern.Also how to define uname p/w here )**

**Comment by satishc1** [comment]
@gokulknewt comment out auth.ldapUserDnPattern. Only set  auth.ldapServerUrl and  auth.adDomain and auth.adRootDn

**Comment by gokulknewt** [comment]
@Satishc1, I have comment out the auth.ldapUserDnPattern. To connect the active directory we have to pass username and passowrd.Where we have to define and pass.Could you explore me?

**Comment by gokulknewt** [comment]
@Satishc1,Thanks for you support.Now we are able to connect the Active directory Using LDAPS proctocol.
Thank Much..:)

**Comment by satishc1** [comment]
@gokulknewt Good to know you are able to connect to AD using ldaps.

**Comment by 8500224323** [comment]
@satishc1 same problem for me
 I have comment out the auth.ldapUserDnPattern. 
"To connect the active directory we have to pass username and passowrd.Where we have to define and pass.Could you explore me?"

could you please comment on above double coted sentence

regards,
Chinna
