### ISSUE TITLE
Creating a collector for Teamforge

### ISSUE THREAD

**Issue by alagus84** [capitalone/Hygieia#1367]
I have been looking at GitLab to understand the implementation of the same and to adopt it for creating TeamForge Collector and I am successful I guess. I am able to successfully add data in collector_items collection and commits collection for type CollectorType "SCM" and CollectorName "TeamForge".

However, I am posing some challenges while trying to retrieve the data in the UI module for dashboard.

UI module or the clean method in CollectorTask queries component repository to get the collector items within the Component and checks for type SCM.

Could you please shed me some light on what this component is all about and how to add component with the collector item {name: "TeamForge", type: "SCM"} which I think is needed for my work.

**Comment by alagus84** [comment]
@satishc1 Sathish, could you please shed some light on the purpose of component collection and which module added entry into this collection? Or on the contrary if we have to manually insert data into this collection, how do I do that?

**Comment by nireeshT** [comment]
@alagus84  see if this helps https://github.com/capitalone/Hygieia/issues/820
