### ISSUE TITLE
Error Building Hygieia-Jenkins Plugin for .hpi file

### ISSUE THREAD

**Issue by kavalpatel15** [capitalone/Hygieia#1373]
Hello all,

I am trying to set up the hygieia jenkins plugin but everytime i run mvn clean package i am getting the following error:

 ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.341 s
[INFO] Finished at: 2017-05-08T09:54:06-04:00
[INFO] Final Memory: 42M/206M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.kohsuke:access-modifier-checker:1.11:enforce (default-enforce) on project hygieia-publisher: Access modifier checks failed. See the details above -> [Help 1]

Below is the full error which was generated using the -X option:
[error.txt](https://github.com/capitalone/Hygieia/files/983662/error.txt)

Thanks in advance

**Comment by nireeshT** [comment]
@kavalpatel15  maven version ?  workaround, you can download the dependency from https://mvnrepository.com/artifact/org.kohsuke/access-modifier-checker/1.11 and place it in .m2/repository/org/kohsuke and mvn clean package on hygieia-plugin.

**Comment by kavalpatel15** [comment]
my current maven version is 3.3.9. I will try with the workaround thank you!

**Comment by kavalpatel15** [comment]
I checked the .m2/repository/org/kohsuke direcory and it already had an access-modifier-checker/1.11 directory with the jar file in there. I replaced it with the one I downloaded from the mvnrepository website and I am still getting the same error:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.044 s
[INFO] Finished at: 2017-05-08T12:19:28-04:00
[INFO] Final Memory: 43M/193M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.kohsuke:access-modifier-checker:1.11:enforce (default-enforce) on project hygieia-publisher: Access modifier checks failed. See the details above -> [Help 1]
[ERROR]

**Comment by stevegal** [comment]
the issue seems to be the annotation in jenkins AbstractBuild that has 
```
 ((AbstractBuild) run).getChangeSets()
```
as this is marked with 
```
 @Restricted(DoNotUse.class) // for project-changes.jelly
```

I've got a commit that in-effect inlines this method in my local repo for both the ArtifactBuilder and BuildBuilder classes (see https://github.com/stevegal/Hygieia/commit/e822accc4c79fd4c050bf3b6d33876d95a83871b ) as well as adding the plugin into the main pom build.

**Comment by chethanbs** [comment]
Even I am facing the same issue while building the plugin.
@stevegal -Have you committed these changes to repository? So that I can try to build the plugin with your commits?

**Comment by stevegal** [comment]
I've got them in my fork - https://github.com/stevegal/Hygieia/tree/jenkinsPlugin

**Comment by kavalpatel15** [comment]
hey @stevegal thank you for your help. I was able to build the plugin successfully and it has generated the .hpi file!

**Comment by chethanbs** [comment]
Thank you Steve .I was able to build plugin successfully

**Comment by kavalpatel15** [comment]
Hey guys, 
I installed the .hpi file onto a jenkins machine and configured it according to the guide however, on the build console output I am not seeing any mention of the Hygieia plugin and there are no jobs listed on the Hygieia UI dashboard.

![jenkins build config](https://cloud.githubusercontent.com/assets/11862646/25871450/79c03264-34d5-11e7-870d-97bef43370b4.PNG)
[consoleText.txt](https://github.com/capitalone/Hygieia/files/987941/consoleText.txt)

**Comment by tabladrum** [comment]
Did you configure the global settings for the plugin?

**Comment by tabladrum** [comment]
@stevegal can you do a PR from your fork? Thanks!!!

**Comment by stevegal** [comment]
@tabladrum I'll cherry pick the commit tonight after work and create a branch for this PR. I'm working on publishing from the JenkinsPlugin with the raw results from jacoco/findbugs/pmd/checkstyle atm and it's kinda embedded in that.

**Comment by stevegal** [comment]
@tabladrum see https://github.com/capitalone/Hygieia/pull/1379

**Comment by kavalpatel15** [comment]
Yes i configured the global settings and when i run a curl command :
curl -X POST http://myserver2:3001/api/artifact -H 'Content-Type: application/json' --data '{ "artifactName": "Helloworld", "canonicalName": "Helloworld", "artifactGroup": "mygroup", "artifactVersion": "", "timestamp": 1494358825777, "metadata": { "buildUrl": "http://myserver:3001/jenkins/job/ajob/259/", "buildNumber" : 259, "jobName": "loancert_api_gradle_build", "jobUrl": "http://myserver:3001/jenkins/job/ajob/", "instanceUrl": "http://myserver:3001/jenkins/"} }'

something does appear in Mongo with this information but I cannot publish it on the build widget

**Comment by nireeshT** [comment]
@kavalpatel15  - In the screenshot above, configure publish deployment results with the same artifact information and run build. See if build jobs are displayed on UI.

**Comment by kavalpatel15** [comment]
Hey all,

I was able to fix this issue. It was due to some proxy issues.

Thanks all!
