### ISSUE TITLE
Build failure after pulling latest commits

### ISSUE THREAD

**Issue by Ramya126** [capitalone/Hygieia#1377]
@rob-miller-777   @satishc1  : I  pulled the recent commits yesterday(05/09) . Tests are failing when I build API code.

Here are the test failures : 
#1 : Running com.capitalone.dashboard.service.BuildServiceTest
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.023 sec <<< FAILURE! - in com.capitalone.dashboard.service.BuildServiceTest
search(com.capitalone.dashboard.service.BuildServiceTest)  Time elapsed: 0.022 sec  <<< ERROR!
java.lang.Error: Unresolved compilation problems: 
	QBuild cannot be resolved to a type
	QBuild cannot be resolved to a type

#2 : Running com.capitalone.dashboard.service.FeatureServiceImplTest
Tests run: 7, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.032 sec <<< FAILURE! - in com.capitalone.dashboard.service.FeatureServiceImplTest
testGetRelevantStories_Kanban(com.capitalone.dashboard.service.FeatureServiceImplTest)  Time elapsed: 0.004 sec  <<< ERROR!
java.lang.Error: Unresolved compilation problems: 
	QScopeOwner cannot be resolved to a type
	QScopeOwner cannot be resolved to a type

#3: Running com.capitalone.dashboard.service.UserInfoServiceImplTest
Tests run: 10, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE! - in com.capitalone.dashboard.service.UserInfoServiceImplTest
shouldPromoteExistingUserToAdmin(com.capitalone.dashboard.service.UserInfoServiceImplTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NullPointerException: null
	at com.capitalone.dashboard.service.UserInfoServiceImpl.promoteToAdmin(UserInfoServiceImpl.java:62)
	at com.capitalone.dashboard.service.UserInfoServiceImplTest.shouldPromoteExistingUserToAdmin(UserInfoServiceImplTest.java:128)

shouldRemoveAdminFromExistingUser(com.capitalone.dashboard.service.UserInfoServiceImplTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NullPointerException: null
	at com.capitalone.dashboard.service.UserInfoServiceImplTest.shouldRemoveAdminFromExistingUser(UserInfoServiceImplTest.java:168)

shouldNotDeleteLastAdmin(com.capitalone.dashboard.service.UserInfoServiceImplTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<com.capitalone.dashboard.auth.exceptions.DeleteLastAdminException> but was<java.lang.NoSuchMethodError>
	at com.capitalone.dashboard.service.UserInfoServiceImplTest.shouldNotDeleteLastAdmin(UserInfoServiceImplTest.java:140)

shouldNotRemoveAdminFromNonExistingUSer(com.capitalone.dashboard.service.UserInfoServiceImplTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<com.capitalone.dashboard.auth.exceptions.UserNotFoundException> but was<java.lang.NoSuchMethodError>
	at com.capitalone.dashboard.service.UserInfoServiceImplTest.shouldNotRemoveAdminFromNonExistingUSer(UserInfoServiceImplTest.java:153)

**Comment by satishc1** [comment]
@Ramya126 Latest commits?  Are you building from the latest master or are you trying to pull a PR in your build ?

**Comment by rob-miller-777** [comment]
Based on your errors, I would guess your core project is out of date.  Run a `maven clean install` on the entire project, or at least the core project before you trying building the api.

**Comment by Ramya126** [comment]
@rob-miller-777  That worked . Thanks for quick response.

**Comment by satishc1** [comment]
Closed.
