### ISSUE TITLE
artifactory UI widget

### ISSUE THREAD

**Issue by agsmorodin** [capitalone/Hygieia#1378]
Hi,

I successfully installed artifactory collector and it can retrieve data from artifactory.
But I am curious how can I configure/show artifactory related information in UI?
Probably I missed something but I can't find related widget. Please point me to right direction.

**Comment by nireeshT** [comment]
@agsmorodin  -There is no UI widget for binary artifacts collection. It is used internally to link deployments with commits/build in the product dashboard.
