### ISSUE TITLE
Teamcity Collector

### ISSUE THREAD

**Issue by cmdel** [capitalone/Hygieia#138]
Are there any plans to add a collector for Teamcity as a complement to Jenkins?

**Comment by amitmawkin** [comment]
We dont use teamcity and would have to rely on community to build one , If you intent to build a collector for TeamCity we can certainly help you if you have any questions regarding development on our Gitter chat channel.

**Comment by abhayshukla01** [comment]
Hi  I am planning to develop collector for Teamcity..what are the pre requisites I need to have? Can you guys guide me? You guys already have collector for certain tools...can those codes be reused for teamcity? or I have to design it from scratch..?

**Comment by abhayshukla01** [comment]
Hi @amitmawkin can you help me with my confusion

**Comment by tabladrum** [comment]
Copy Jenkins collector and start from there. The DefaultClient is where the Jenkins API calls are - you will need corresponding TeamCity APIs.

**Comment by abhayshukla01** [comment]
@tabladrum thank you sir. That is what I am doing. how can I get Teamcity APIs? can you please lemme know what changes need to be made in DefautClient for Teamcity and which other files from Jenkins collector need change?

**Comment by jagankalluri** [comment]
hello @abhayshukla01 ,

Were you able to get Teamcity working ? I am also interested in this and need some idea .

Jagan

**Comment by alexanikanov** [comment]
guys check this out https://github.com/alexanikanov/hygieia_teamcity_collector

**Comment by amitmawkin** [comment]
Wow Collector in python ... awesome. @mrpudn will be happy.

Submit a PR we can review it. Due to open architecture for collectors , they can be written in any programming language

**Comment by WillLuce** [comment]
Any news on this? My team is looking forward to using Hygieia, but need TeamCity!!

**Comment by rkatti** [comment]
any updates with team city collector ? We are looking for it too.
