### ISSUE TITLE
Deploy Collector for teamcity 

### ISSUE THREAD

**Issue by narayan1ap** [capitalone/Hygieia#1380]
We use teamcity for deployment and I wanted to know if it is possible to write a deploy collector for team city.  I am planning to start by copying udeploy code and modify the API calls according to team city. Is that correct ?

**Comment by nireeshT** [comment]
@narayan1ap  - Collectors design is generic across the application. You can refer other collectors to build new ones.

**Comment by gshiva** [comment]
See this Team City ?

#138
