### ISSUE TITLE
Hygieia API Layer Not connecting

### ISSUE THREAD

**Issue by sameervsarma** [capitalone/Hygieia#1384]
Hi ,

I have done the following steps in installing Hygieia in my AWS EC2 instance - ( Ubuntu Linux flavor):

1) Downloaded the package of Hygieia and have done mvn clean install package
2) Downloaded Mongo DB and installed it with username and  pwd.
3) Went to api folder - /target/api.jar and ran the command : 

java -jar api.jar --spring.config.location=<hygieialocation>/api/ --spring.config.name=dashboard.properties.
4) Went to UI folder and ran gulp serve

No errors were found in any of the above steps.
But in the hygieia dashboard it is showing API not connected.

PS: All the installations are done with root user , as localhost and default ports.

What can I do?

**Comment by satishc1** [comment]
@sameervsarma Refer to https://github.com/capitalone/Hygieia/issues/931

**Comment by satishc1** [comment]
Closed. Reopen if still an issue.
