### ISSUE TITLE
SCM gitlab collector is not working

### ISSUE THREAD

**Issue by saranyasasidharan** [capitalone/Hygieia#1393]
I have configured the scm gitlab collector. But the database is not updated with the data from my gitlab. Only the collector table has an entry for gitlab.
The error log is showing "c.c.d.c.GitlabGitCollectorTask - Failed to retrieve data, the repo or collector is most likey misconfigured: null, 400 BAD_REQUEST"

Also I am not able to configure gitlab in Hygieia Dashboard. The save button click in code repo configure widget is not working. 
My application.properties file is : 
dbname=dashboardb
dbhost=127.0.0.1
dbport=27017
dbusername=db
dbpassword=dbpass
gitlab.host=xx.xxx.xxx.xxx
gitlab.protocol=http
gitlab.port=8092
gitlab.selfSignedCertificate=false
gitlab.apiToken=myapitoken

**Comment by nireeshT** [comment]
@saranyasasidharan  - refer https://github.com/capitalone/Hygieia/issues/1318. 

Save button error, you see any error in browser console?

**Comment by nireeshT** [comment]
@saranyasasidharan  - For save button click, try running the scm collector and then configure scm widget in UI.

**Comment by saranyasasidharan** [comment]
Hi... It is working now. Thanks

**Comment by lyndomiao** [comment]
@nireeshT @saranyasasidharan Hi,what I am facing is that the gitlab scm collector shows data,but it only show commit data,doesn't show pulls and issues data.Do u know why?
