### ISSUE TITLE
UI/Angular App not loading

### ISSUE THREAD

**Issue by rob-miller-777** [capitalone/Hygieia#1394]
After pulling the latest code, the UI won't load, and the console is giving the following error. 
`Uncaught ReferenceError: jQuery is not defined
    at bower.js:82986
    at bower.js:82988
bower.js:6099 Uncaught Error: [$injector:modulerr] Failed to instantiate module hygieia-dashboard due to:
Error: [$injector:modulerr] Failed to instantiate module gridstack-angular due to:
Error: [$injector:nomod] Module 'gridstack-angular' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.11/$injector/nomod?p0=gridstack-angular
    at http://localhost:3000/bower_components/bower.js:1475:12
    at http://localhost:3000/bower_components/bower.js:3540:17
    at ensure (http://localhost:3000/bower_components/bower.js:3464:38)
    at module (http://localhost:3000/bower_components/bower.js:3538:14)
    at http://localhost:3000/bower_components/bower.js:6076:22
    at forEach (http://localhost:3000/bower_components/bower.js:1732:20)
    at loadModules (http://localhost:3000/bower_components/bower.js:6060:5)
    at http://localhost:3000/bower_components/bower.js:6077:40
    at forEach (http://localhost:3000/bower_components/bower.js:1732:20)
    at loadModules (http://localhost:3000/bower_components/bower.js:6060:5)
http://errors.angularjs.org/1.5.11/$injector/modulerr?p0=gridstack-angular&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'gridstack-angular'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.11%2F%24injector%2Fnomod%3Fp0%3Dgridstack-angular%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A1475%3A12%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A3540%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A3464%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A3538%3A14)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A6076%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A1732%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A6060%3A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A6077%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A1732%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A6060%3A5)
    at http://localhost:3000/bower_components/bower.js:1475:12
    at http://localhost:3000/bower_components/bower.js:6099:15
    at forEach (http://localhost:3000/bower_components/bower.js:1732:20)
    at loadModules (http://localhost:3000/bower_components/bower.js:6060:5)
    at http://localhost:3000/bower_components/bower.js:6077:40
    at forEach (http://localhost:3000/bower_components/bower.js:1732:20)
    at loadModules (http://localhost:3000/bower_components/bower.js:6060:5)
    at createInjector (http://localhost:3000/bower_components/bower.js:5982:19)
    at doBootstrap (http://localhost:3000/bower_components/bower.js:3216:20)
    at bootstrap (http://localhost:3000/bower_components/bower.js:3237:12)
http://errors.angularjs.org/1.5.11/$injector/modulerr?p0=hygieia-dashboard&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20gridstack-angular%20due%20to%3A%0AError%3A%20%5B%24injector%3Anomod%5D%20Module%20'gridstack-angular'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.11%2F%24injector%2Fnomod%3Fp0%3Dgridstack-angular%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A1475%3A12%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A3540%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A3464%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A3538%3A14)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A6076%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A1732%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A6060%3A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A6077%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A1732%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A6060%3A5)%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.11%2F%24injector%2Fmodulerr%3Fp0%3Dgridstack-angular%26p1%3DError%253A%2520%255B%2524injector%253Anomod%255D%2520Module%2520'gridstack-angular'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.5.11%252F%2524injector%252Fnomod%253Fp0%253Dgridstack-angular%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fbower.js%253A1475%253A12%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fbower.js%253A3540%253A17%250A%2520%2520%2520%2520at%2520ensure%2520(http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fbower.js%253A3464%253A38)%250A%2520%2520%2520%2520at%2520module%2520(http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fbower.js%253A3538%253A14)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fbower.js%253A6076%253A22%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fbower.js%253A1732%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fbower.js%253A6060%253A5)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fbower.js%253A6077%253A40%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fbower.js%253A1732%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fbower.js%253A6060%253A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A1475%3A12%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A6099%3A15%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A1732%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A6060%3A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A6077%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A1732%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A6060%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A5982%3A19)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A3216%3A20)%0A%20%20%20%20at%20bootstrap%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A3237%3A12)
    at http://localhost:3000/bower_components/bower.js:1475:12
    at http://localhost:3000/bower_components/bower.js:3540:17
    at ensure (http://localhost:3000/bower_components/bower.js:3464:38)
    at module (http://localhost:3000/bower_components/bower.js:3538:14)
    at http://localhost:3000/bower_components/bower.js:6076:22
    at forEach (http://localhost:3000/bower_components/bower.js:1732:20)
    at loadModules (http://localhost:3000/bower_components/bower.js:6060:5)
    at http://localhost:3000/bower_components/bower.js:6077:40
    at forEach (http://localhost:3000/bower_components/bower.js:1732:20)
    at loadModules (http://localhost:3000/bower_components/bower.js:6060:5)
http://errors.angularjs.org/1.5.11/$injector/modulerr?p0=gridstack-angular&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'gridstack-angular'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.11%2F%24injector%2Fnomod%3Fp0%3Dgridstack-angular%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A1475%3A12%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A3540%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A3464%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A3538%3A14)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A6076%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A1732%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A6060%3A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A6077%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A1732%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A6060%3A5)
    at http://localhost:3000/bower_components/bower.js:1475:12
    at http://localhost:3000/bower_components/bower.js:6099:15
    at forEach (http://localhost:3000/bower_components/bower.js:1732:20)
    at loadModules (http://localhost:3000/bower_components/bower.js:6060:5)
    at http://localhost:3000/bower_components/bower.js:6077:40
    at forEach (http://localhost:3000/bower_components/bower.js:1732:20)
    at loadModules (http://localhost:3000/bower_components/bower.js:6060:5)
    at createInjector (http://localhost:3000/bower_components/bower.js:5982:19)
    at doBootstrap (http://localhost:3000/bower_components/bower.js:3216:20)
    at bootstrap (http://localhost:3000/bower_components/bower.js:3237:12)
http://errors.angularjs.org/1.5.11/$injector/modulerr?p0=hygieia-dashboard&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20gridstack-angular%20due%20to%3A%0AError%3A%20%5B%24injector%3Anomod%5D%20Module%20'gridstack-angular'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.11%2F%24injector%2Fnomod%3Fp0%3Dgridstack-angular%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A1475%3A12%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A3540%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A3464%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A3538%3A14)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A6076%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A1732%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A6060%3A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A6077%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A1732%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A6060%3A5)%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.11%2F%24injector%2Fmodulerr%3Fp0%3Dgridstack-angular%26p1%3DError%253A%2520%255B%2524injector%253Anomod%255D%2520Module%2520'gridstack-angular'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.5.11%252F%2524injector%252Fnomod%253Fp0%253Dgridstack-angular%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fbower.js%253A1475%253A12%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fbower.js%253A3540%253A17%250A%2520%2520%2520%2520at%2520ensure%2520(http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fbower.js%253A3464%253A38)%250A%2520%2520%2520%2520at%2520module%2520(http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fbower.js%253A3538%253A14)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fbower.js%253A6076%253A22%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fbower.js%253A1732%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fbower.js%253A6060%253A5)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fbower.js%253A6077%253A40%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fbower.js%253A1732%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fbower.js%253A6060%253A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A1475%3A12%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A6099%3A15%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A1732%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A6060%3A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A6077%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A1732%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A6060%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A5982%3A19)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A3216%3A20)%0A%20%20%20%20at%20bootstrap%20(http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fbower.js%3A3237%3A12)
    at http://localhost:3000/bower_components/bower.js:1475:12
    at http://localhost:3000/bower_components/bower.js:6099:15
    at forEach (http://localhost:3000/bower_components/bower.js:1732:20)
    at loadModules (http://localhost:3000/bower_components/bower.js:6060:5)
    at createInjector (http://localhost:3000/bower_components/bower.js:5982:19)
    at doBootstrap (http://localhost:3000/bower_components/bower.js:3216:20)
    at bootstrap (http://localhost:3000/bower_components/bower.js:3237:12)
    at angularInit (http://localhost:3000/bower_components/bower.js:3122:5)
    at http://localhost:3000/bower_components/bower.js:34023:5
    at HTMLDocument.trigger (http://localhost:3000/bower_components/bower.js:4664:7)`

**Comment by rob-miller-777** [comment]
I wiped my npm/bower modules, and did a fresh npm/bower install, same issue.

**Comment by tabladrum** [comment]
can you try clear the browser cache?

**Comment by rob-miller-777** [comment]
Tried that, no change.

**Comment by rsans** [comment]
Pulling latest code loading UI for me, but login is not working. JWT token is not added to all http requests.

And CORS filter is not working. I removed the cors config and tried with this bean that worked for me.

package com.capitalone.dashboard.config;


import java.io.IOException;
import javax.servlet.Filter;
import javax.servlet.FilterChain;
import javax.servlet.FilterConfig;
import javax.servlet.ServletException;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

@Component
@Order(Ordered.HIGHEST_PRECEDENCE)
public class SimpleCORSFilter implements Filter {

    private final Logger log = LoggerFactory.getLogger(SimpleCORSFilter.class);

    public SimpleCORSFilter() {
        log.info("SimpleCORSFilter init");
    }

    @Override
    public void doFilter(ServletRequest req, ServletResponse res, FilterChain chain) throws IOException, ServletException {

        HttpServletRequest request = (HttpServletRequest) req;
        HttpServletResponse response = (HttpServletResponse) res;

        response.setHeader("Access-Control-Allow-Origin", "*"); //request.getHeader("Origin"));
        response.setHeader("Access-Control-Allow-Credentials", "true");
        response.setHeader("Access-Control-Allow-Methods", "POST, PUT, GET, OPTIONS, DELETE");
        response.setHeader("Access-Control-Max-Age", "3600");
        response.setHeader("Access-Control-Expose-Headers", "X-Authentication-Token, Authorization");
        response.setHeader("Access-Control-Allow-Headers", "Content-Type, Accept, X-Requested-With, remember-me, Authorization");

        chain.doFilter(req, res);
    }

    @Override
    public void init(FilterConfig filterConfig) {
    }

    @Override
    public void destroy() {
    }

}

I added .antMatchers("/login").permitAll() to WebSecurityConfig. 

I'm loading the api and the UI without docker. Springboot:run and gulp serve only.

**Comment by nireeshT** [comment]
@rob-miller-777 - workaround, try deleting gridstack-angular dependency from UI/bower.json, and run man clean install on root hygieia.

**Comment by tabladrum** [comment]
@nireeshT is that a fix (as in PR coming) or just trying out.

**Comment by nireeshT** [comment]
@tabladrum- gridstack dependency is part of appdynamics pr. It worked fine in my local, although it is not directly related to app dynamics widget, it is mostly to do with customize templates. just trying out to see if we get rid of error when gridstack is removed from bower.json

**Comment by rob-miller-777** [comment]
Tried removing the gridstack dependency, but didn't change anything. It looks like angular is trying to load in the "gridstack-angular" dependency, but can't find it.  I am doing some digging to see if it's just an issue here.  Everyone here is having the same problem.

**Comment by tabladrum** [comment]
@nireeshT I cloned fresh late last night and it was good. I know there were 2 PRs back to back on the appD changes. @rob-miller-777 did you clone in between the two.

**Comment by rob-miller-777** [comment]
Gonna close this down, I have narrowed the issue down to an internal registry problem.  Haven't figured out what specifically yet though.  Thanks for looking into this for me.

**Comment by rvema** [comment]
@rob-miller-777 I migrated from bower to npm using npm-wiredep and seeing this error . Can you let me know what you had to do to fix this issue?
