### ISSUE TITLE
lodash 4.x findWhere calls failing in latest build from master.

### ISSUE THREAD

**Issue by satishc1** [capitalone/Hygieia#1396]
lodash 4.x findWhere calls are failing in latest build from master.

**Comment by nireeshT** [comment]
@satishc1 @tabladrum  - Fix for this issue is available in PR https://github.com/capitalone/Hygieia/pull/1397
Lodash change log reference - https://github.com/lodash/lodash/wiki/Changelog#compatibility-warnings
