### ISSUE TITLE
"User already exists"

### ISSUE THREAD

**Issue by willuk2010** [capitalone/Hygieia#1401]
Hey,

built fresh today, hygieia-ui & hygieia-api just for a demo/test, inside dockers.

Strange issue though, no matter what user i enter in the sign up, i get "User already exists", the tick for the API appears to suggest the API is online (green tick).

I see the following request in the ui logs, 

10.7.11.100 - - [18/May/2017:14:55:40 +0000] "POST /api/registerUser HTTP/1.1" 422 0 "http://xxx.xxx.xxx.xxx:8088/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36" "-"

and, using chrome debug, i see

POST http://xxx.xxx.xxx.xxx:8088/api/registerUser 422 (Unprocessable Entity)

Any thoughts?

**Comment by willuk2010** [comment]
little more info i just saw this in the api logs, when i try and create a user.

2017-05-18 15:02:19,457 ERROR c.c.d.rest.RestApiExceptionHandler - base64-encoded secret key cannot be null or empty.
java.lang.IllegalArgumentException: base64-encoded secret key cannot be null or empty.

**Comment by MarkRx** [comment]
I think you are hitting this: #1207

**Comment by willuk2010** [comment]
Managed to fix this, by having to add 2 variables into my docker-compose.

AUTH_EXPIRATION_TIME
AUTH_SECRET
