### ISSUE TITLE
SSL Cert's with Docker

### ISSUE THREAD

**Issue by willuk2010** [capitalone/Hygieia#1404]
How do i import my self signed cert into the docker images?

using the jenkins collector, i get the following, is this because of the self signed SSL cert?

org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://jenkins-v2.xxxx.corp/api/json?tree=jobs[name,url,builds[number,url]]":sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by willuk2010** [comment]
Fixed it,  for both Jenkins and Gitlab collectors.

modified the Dockerfile to copy my cert into the docker as its built, and edited the shell scripts, to insert the cert into the keystore.

**Comment by jochenparm** [comment]
Hey @willuk2010 , could you share how you inserted the cert into the keystore?
I'm looking at the following page:
https://docs.oracle.com/javase/tutorial/security/toolfilex/rstep1.html

But it's not making sense to me
