### ISSUE TITLE
Adding Multiple Apis In Jenkins

### ISSUE THREAD

**Issue by kavitha0624** [capitalone/Hygieia#1410]
Hi Team,

We have hosted Hygieia on two different linux servers in our company network.
We have one Jenkins master, and we are using hygieia-jenkins plugin to get the data on Jenkins widget.
In the Jenkins master settings, api url for server 1 was given. Is it possible to give api links for both server1 and server 2 so that plugin can push the jenkins data to both the servers?

Please help

**Comment by satishc1** [comment]
@kavitha0624 We are planning to have a hygieia publisher endpoint at the job level in jenkins in addition to the endpoint in the global settings.

**Comment by kavitha0624** [comment]
@satishc1 - So, right now in Global settings, we can only specify one api right?

**Comment by satishc1** [comment]
@kavitha0624 Yes. right now in Global settings, we can only specify one api

**Comment by Satheesh-b** [comment]
@satishc1  Hi, 

I am too having the same issue. I want to send data from multiple(two) job to two different servers based on the job. 

Is the development in progress to accommodate the change? When can we expect the roll out. Please update.

**Comment by kavitha0624** [comment]
Hi Team,

Can any one please look into my issue 1439. I am waiting on this.
