### ISSUE TITLE
MongoDB Schema Documentation - Feature Collection

### ISSUE THREAD

**Issue by irvingoe** [capitalone/Hygieia#1411]
Hi team,
I'm looking for documentation regarding the schema structure, I'd like to explore a way to feed data into MongoDB using APIs that I already have developed for custom jenkins plugin.
I would only need to know where to dump my information, I am looking specifically for the Feature collection, I don't use Jira, Gitlab or VersionOne so I don't have any schema example.

If you don't have documentation could you provide me sample data that I can use as a reference and maybe I can figure out the relationships.

Thank you in advance!

**Comment by irvingoe** [comment]
@tabladrum any input here?

**Comment by mrpudn** [comment]
Hey @irvingoe, I don't think there's formal documentation, but you can have a look at the `Feature` model here:
https://github.com/capitalone/Hygieia/blob/master/core/src/main/java/com/capitalone/dashboard/model/Feature.java

There's also a swagger UI for the API hosted here (make sure the API is running):
http://localhost:8080/api/swagger/index.html

But, it looks like there's no POST or PUT endpoint for features, so you'll have to build a collector. You can use these ones as a reference:
https://github.com/capitalone/Hygieia/tree/master/collectors/feature

That should hopefully get you started.

**Comment by irvingoe** [comment]
@mrpudn thank you for that!
And yeah I guess I could dive into swagger and get some reference from there.
I'll give it a try!
