### ISSUE TITLE
Is it possible to use something other than cucumber for Functional Tests/Security Analysis?

### ISSUE THREAD

**Issue by hitorchi** [capitalone/Hygieia#1414]
![screen shot 2017-05-23 at 2 25 03 pm](https://cloud.githubusercontent.com/assets/16524900/26369811/ce70ba24-3fc3-11e7-9085-feb07dc71463.png)
 
I'm currently using Sonar for the Quality widget, and as I understand it Sonar fills in the following sections:
- Static Analysis
- Version
- Unit Tests
- Code Coverage

but you need the Jenkins Cucumber plugin to fill in the Security Analysis and Functional Tests section.

My question is if it is possible to use any other method of filling in the functional tests section as my organization doesn't use cucumber for testing (We don't currently care about the security analysis section at the moment)

**Comment by nireeshT** [comment]
@hitorchi  If your test case results are a cucumber format file, it is supported. #1161
Other formats is a wip.
