### ISSUE TITLE
Jenkins Build collector

### ISSUE THREAD

**Issue by Ishan1987** [capitalone/Hygieia#1416]
Hi,

When i am spinning hygieia instance using docker compose file, i am getting below highlighted error though i can see all the the jobs in drop down list in widget for the jenkins instance configured in docker compose file

**_ERROR c.c.d.collector.DefaultHudsonClient - Client exception loading build details: 403 Forbidden._**

Please let me know if you require more detail.

**Comment by nireeshT** [comment]
@Ishan1987  - go to  hygieia-jenkins-build-collector.properties file and set jenkins.saveLog= false.

**Comment by Ishan1987** [comment]
@nireeshT  I am still getting the same error post setting the variable  jenkins.saveLog to false inside the container and restarted the container.
the WARN  c.c.d.collector.DefaultHudsonClient - Credentials for the following url was not found. This could happen if the domain/subdomain/IP address in the build url returned by Jenkins and the Jenkins instance url in your Hygieia configuration do not match:
hygieia-jenkins-build   ERROR c.c.d.collector.DefaultHudsonClient - Client exception loading build details: 403 Forbidden. URL =

**Comment by Ishan1987** [comment]
@nireeshT  Please let me know if you need more detail to resolve above mentioned error.

**Comment by MarkRx** [comment]
Your properties isn't configured correctly. You need to make sure that the uri returned by jenkins rest calls (the one that is configured in global properties as the Jenkins host) is the exact same as what you are using for your jenkins.servers[x] in your config.

**Comment by Sbrenthughes** [comment]
Please reopen if issue is not resolved.
