### ISSUE TITLE
"Connection refused" when trying to configure cloud aws collector

### ISSUE THREAD

**Issue by meet101** [capitalone/Hygieia#1419]
issue 1
I am trying to configure AWS Cloud collector, below is my application.properties file. I have it running in EC2 box without IAM role. So, I am passing credentials through ~/.aws/credentials file with default profile. 
When i try to run collector, It started fine but when it's going to collect data at that time, it's throwing connection refused error. saying "unable to execute HTTP request" error as below,
can someone please help?

application.properties
dbhost=127.0.0.1

#Database Port - default is 27017
dbport=27017

#Database Username - default is blank
dbusername=admin

#Database Password - default is blank
dbpassword=admin

#Logging File location
logging.file=./logs/cloud.log

#Collector schedule (required)
aws.cron=0 0/5 * * * *

#AWS ValidTag Key - To look for tags that you expect on your resource
aws.validTagKey[0]=Application
aws.validTagKey[1]=Environment

#AWS Proxy Host
aws.proxyHost=

#AWS Proxy Port
aws.proxyPort=3333

#AWS Non Proxy
aws.nonProxy=xxx.xxx.xxx.xxx

#AWS Profile to be used if any
aws.profile=default

errors:
2017-05-24 21:25:00,180 INFO  com.amazonaws.http.AmazonHttpClient - Unable to execute HTTP request: Connection refused (Connection refused)
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_131]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_131]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_131]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_131]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_131]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_131]
        at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117) ~[httpclient-4.5.1.jar!/:4.5.1]at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304) ~[httpclient-4.5.1.jar!/:4.5.

question 2 - is there any dependency for AWS collector? Do we need to have configured deploy collector to use AWS collector?

**Comment by meet101** [comment]
during troubleshooting, I found a new error when I tried to use EC2-Role attached to instance. I am seeing error as below,

> ''2017-05-25 21:35:30,787 ERROR o.s.boot.SpringApplication - **Application startup failed
> org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'AWSCloudCollectorTask' defined in URL [jar:file:/opt/HygieiaMOD/Hygieia/collectors/cloud/aws/target/aws-cloud-collector-2.0.5-SNAPSHOT.jar!/com/capitalone/dashboard/collector/AWSCloudCollectorTask.class]:** Unsatisfied dependency expressed through constructor argument with index 3 of type [com.capitalone.dashboard.collector.AWSCloudClient]: Error creating bean with name 'defaultAWSCloudClient' defined in URL 

**My application.properties** 
dbname=hygieiadb
dbhost=127.0.0.1
dbport=27017
dbusername=admin
dbpassword=admin
logging.file=./logs/cloud.log
aws.cron=0 0/5 * * * *
aws.validTagKey[0]=Application
aws.validTagKey[1]=Environment
aws.profile=

can someone please help me to understand why am i getting this error? Am i missing anything in application.properties? what is parameter for **aws.nonProxy=xxx.xxx.xxx.xxx**  I am not behind the proxy. Do i have to use this parameter? 

Any help would be appreciated!

**Comment by satishc1** [comment]
@meet101 Are you sure your credentials file is being read ? Try running some aws cli s3 ls command to make sure your setup .aws/credentials setup is correct before launching the collector.

**Comment by meet101** [comment]
@satishc1 - Thanks for your comment. I tried aws cli to copy file to s3. It worked. I am thinking, i might be missing some field in aws.properties file. Can you please verify above file?

**Comment by meet101** [comment]
I see different error when i tried to use default aws credentials profile. please check errors in attached text file. Application startup is getting failed itself. 
Please advice!
here is my aws.properties
dbname=hygieiadb
dbhost=127.0.0.1
dbport=27017
dbusername=admin
dbpassword=admin
logging.file=./logs/cloud.log
aws.cron=0 0/3 * * * *
aws.validTagKey[0]=Environment
aws.validTagKey[1]=Application
aws.profile=default

[awscollectorissue.txt](https://github.com/capitalone/Hygieia/files/1045120/awscollectorissue.txt)

**Comment by meet101** [comment]
fixed. Something with .properties file. I had removed below three field from file. After adding back as empty. it works. 
aws.proxyHost=
aws.proxyPort=
aws.nonProxy=
