### ISSUE TITLE
github collector not able to fetch anything

### ISSUE THREAD

**Issue by ashu5993** [capitalone/Hygieia#1424]
Hi,
github collector throwing error :

404 Not Found:http://vchniladpsci-04.ad.infosys.com/api/v3/repos/s.com:8090/r/IVSBookStore_MySQL/commits?sha=matser&since=2017-05-26T12:20Z

pls help on this

**Comment by Sbrenthughes** [comment]
@ashu5993 can you post the full stacktrace?

**Comment by ashu5993** [comment]
[githuberror.txt](https://github.com/capitalone/Hygieia/files/1041321/githuberror.txt)

Hi here it is.

**Comment by ashu5993** [comment]
[application.properties.txt](https://github.com/capitalone/Hygieia/files/1041858/application.properties.txt)

here it is

**Comment by Sbrenthughes** [comment]
Have you tried setting up the widget and passing the username and pass there instead of in your properties file?

**Comment by ashu5993** [comment]
its giving error encypting password error.

**Comment by Sbrenthughes** [comment]
what command are you running for the collector?

**Comment by ashu5993** [comment]
java -jar target\github-scm-collector-2.5.0-SNAPSHOT.jar --spring.config.name=application --spring.config.location=application.properties

yes i have taken out at properties file and giving in ui

**Comment by Sbrenthughes** [comment]
@ashu5993 here are a couple of things I see

1)  Add the full path to the properties file. I would also suggest having a separate properties file for the collector
`java -jar target\github-scm-collector-2.5.0-SNAPSHOT.jar --spring.config.name=application --spring.config.location=full_path_to_file/application.properties`
**Example:**
`java -jar target\github-scm-collector-2.5.0-SNAPSHOT.jar --spring.config.name=github --spring.config.location=full_path_to_file/github.properties`

2) In your properties files there is no such thing as a `github.username=` so you'll need to remove that. 
3) The `github.apiKey=`is not the correct format.  See https://github.com/capitalone/Hygieia/tree/master/UI#encryption-for-private-repos and look at the section about `Encryption for private repos` for information how to set up the github.apiKey

**Comment by ashu5993** [comment]
Hi @Sbrenthughes  tried All options but still not able to fetch anything . still throwing error.
---------------
2017-06-22 15:00:00,028 INFO  c.c.d.collector.CollectorTask - Starting...
2017-06-22 15:00:00,037 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-06-22 15:00:00,092 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
null
2017-06-22 15:00:00,171 ERROR c.c.d.collector.DefaultGitHubClient - 404 Not Found:http://infygit.ad.infosys.com/api/v3/repos/it.ad.infosys.com/Ashutosh_Tiwari07/BookStoreApplication_v1.0/commits?sha=matser&since=2017-06-22T14:50Z
2017-06-22 15:00:00,171 INFO  c.c.d.collector.CollectorTask - Repo Count              1        0s
2017-06-22 15:00:00,174 INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2017-06-22 15:00:00,175 INFO  c.c.d.collector.CollectorTask - Finished                         0s

Please have a look in this .

**Comment by Sbrenthughes** [comment]
Can you post the updated properties file as well as the updated command used to run the collector?
I also updated my post above it should be `github.key=`.

**Comment by ashu5993** [comment]
Here they are :+1: 

properties-file :- 

# Database Name
dbname=admin

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
#dbreplicaset=false
#dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=db

# Database Password - default is blank
dbpassword=dbpass

# Logging File location
logging.file=./logs/github.log

# Collector schedule (required)
github.cron=0 0/5 * * * *

github.host=github.com
github.key=NIxRaHoaBHCMW4oxATGD5iCuGvQ3ZIAW

# Maximum number of days to go back in time when fetching commits
github.commitThresholdDays=315

#Optional: Error threshold count after which collector stops collecting for a collector item. Default is 2.
github.errorThreshold=2

monitor.proxy.host=10.74.91.103
monitor.proxy.type=http
monitor.proxy.port=80
monitor.proxy.username=Ashutosh_Tiwari07	
monitor.proxy.password=Ashu120517

updated commands -

java -jar target\github-scm-collector-2.5.0-SNAPSHOT.jar --spring.config.name=application --spring.config.location=D:\Hygieia\collectors\scm\github\target\application.properties

**Comment by Sbrenthughes** [comment]
https://github.com/capitalone/Hygieia/issues/1625

**Comment by Sbrenthughes** [comment]
Please reopen if you are still facing issues.

**Comment by Vikash-Ro** [comment]
Hey @Sbrenthughes, I followed all the steps and have successfully setup the scm collector, and it shows no errors while starting the collector too but it shows the total repo counts and all other data to be 0 
![Screenshot 2021-04-27 at 5 21 33 PM](https://user-images.githubusercontent.com/83011592/116236723-06b1d380-a77d-11eb-970d-ccde901524a8.png)

the application .properties file looks like: 

	# Database Name
	dbname=dashboarddb

	# Database HostName - default is localhost
	dbhost=localhost

	# Database Port - default is 27017
	dbport=27017
	server.contextPath=/github
	server.port=9082
	# MongoDB replicaset
	dbreplicaset=false
	dbhostport=[host1:port1,host2:port2,host3:port3]

	# Database Username - default is blank
	dbusername=

	# Database Password - default is blank
	dbpassword=
	
	# Proxy URL
	#github.proxy=
	
	# Proxy Port
	#github.proxyPort=
	
	# Proxy user if auth is required
	#github.proxyUser=
	
	# Proxy password if auth is required
	#github.proxyPassword=
	
	# Logging File location
	logging.file=./logs/github.log

	# Collector schedule (required)
	github.cron=0 0/2 * * * *

	github.host=api.github.com
	
	github.firstRunHistoryDays=60
	github.rateLimitThreshold=100
	github.graphqlUrl=https://api.github.com/graphql
	github.baseApiUrl=https://api.github.com/

	# Maximum number of previous days from current date, when fetching commits
	github.commitThresholdDays=50
	
	# A filter of commits with subject containing the pattern that will be filtered
	#github.notBuiltCommits[0]=(.)*(\\[maven-release-plugin\\])(.)*
	#github.notBuiltCommits[1]=(.)*(orion committed files to rewardsone-chef\\/environments\\/environments\\/rewards_sparkearnengine\\_)(.)*(json)

	# Optional: Error threshold count after which collector stops collecting for a collector item. Default is 2.
	github.errorThreshold=1000

	# This is the key generated using the Encryption class in core
	github.key=<my key here>

	# Personal access token generated from github and used for making authentiated calls
	github.personalAccessToken=<my token here>
	# Github repository Connect Timeout value in milliseconds, default value is 20000 (20s)
	github.connectTimeout=20000

	# Github repository Read Timeout value in milliseconds, default value is 20000 (20s) 
	github.readTimeout=60000
	
	github.commitPullSyncTime=10800000
	github.offsetMinutes=2
	github.fetchCount=25
	github.collectChangedReposOnly=false

	github.privateReposCollectionTime=7200000
	#github.searchCriteria=


and the UI result is as :
![Screenshot 2021-04-27 at 5 26 51 PM](https://user-images.githubusercontent.com/83011592/116237390-c3a43000-a77d-11eb-8c2b-2569fb239831.png)

Any insights would be much appreciated!
