### ISSUE TITLE
Product Dashboard doesn't show integration, pre-production and production stages

### ISSUE THREAD

**Issue by hitorchi** [capitalone/Hygieia#1426]
I'm currently using the Jenkin's Hygieia plugin to push data to the deploy widget of our team dashboard called "01 HD Pay" as seen below. I am using MSBuild to build the project during the integration phase.

Just to note, "HD1" is the integration phase, "stage" is the pre-production stage and "prod" is of course production stage. I have also set up the team dashboard's pipeline as well, so the product dashboard page should be working but isn't.

![screen shot 2017-05-26 at 1 54 04 pm](https://cloud.githubusercontent.com/assets/16524900/26506486/d7cc4f08-421a-11e7-8c0c-4515be68d8cc.png)

![screen shot 2017-05-26 at 1 50 26 pm](https://cloud.githubusercontent.com/assets/16524900/26506573/2440ae10-421b-11e7-93a9-4c318a9742a7.png)

![imageedit_1_2415763650](https://cloud.githubusercontent.com/assets/16524900/26507159/0e54f8ca-421d-11e7-81a6-0a2b1fdc6637.png)

I'm unsure of what the issue is, I've seen other issues posted that are similar but have yet to find a solution. This is what the product dashboard for "01 HD Pay" looks like at the moment, with HD1, stage and prod empty. 

![screen shot 2017-05-26 at 1 50 41 pm](https://cloud.githubusercontent.com/assets/16524900/26506651/62754e02-421b-11e7-837b-ab3b1cda4529.png)

Here are the plugin settings for all 3 of the Jenkins jobs, from top to bottom being HD1, then stage then prod. Has anyone experienced this issue before with MSBuild and using the Jenkin Hygieia plugin?

Do I have to run the stages HD1, stage and prod multiple times to get this up and running?

![screen shot 2017-05-26 at 2 02 10 pm](https://cloud.githubusercontent.com/assets/16524900/26506933/3571b200-421c-11e7-9d67-7885d714b7fd.png)

![screen shot 2017-05-26 at 2 02 19 pm](https://cloud.githubusercontent.com/assets/16524900/26506940/3b7599b4-421c-11e7-89bb-128e158f73c0.png)

![screen shot 2017-05-26 at 2 02 23 pm](https://cloud.githubusercontent.com/assets/16524900/26506943/3e6a930e-421c-11e7-872a-9077b7ee4b93.png)

**Comment by hitorchi** [comment]
Closing this issue as I've finally determined the issue. I need to use source code management on the Jenkins configuration menu to point to the target repo so that HD1, Stage and Prod can read the commits that are getting pushed down the pipeline.

**Comment by rsans** [comment]
Hi, can you post an image of the configuration? I have the same issue and I have source code origin configured in jenkins job.

![image](https://user-images.githubusercontent.com/1969636/27069213-1e872bf0-5014-11e7-9e2a-490137f431f5.png)

**Comment by hitorchi** [comment]
![example](https://user-images.githubusercontent.com/16524900/27085878-85133620-501e-11e7-9321-7f83d0d53c8d.jpg)

Here's what I have at the moment. I also noticed when trying to solve this issue that if your workspace has multiple projects within itself (i.e. There is more than one .git folder located throughout your project), there may be issues with the product dashboard detecting commits.

Can you post what your Hygieia publisher plugin looks like for that job? Does it look like mine?

**Comment by rsans** [comment]
Thanks.  The repository URL is still working. 

![image](https://user-images.githubusercontent.com/1969636/27089764-a1c07980-505b-11e7-9b27-6b33986ba34c.png)

**Comment by hitorchi** [comment]
Is your workspace located on a Linux node or a Windows node? If it's a Windows node, you need \ instead of /.

**Comment by rsans** [comment]
The workspace is located on Linux node. 

The team dashboard

![image](https://user-images.githubusercontent.com/1969636/27119841-be259886-50e1-11e7-880d-74a21f889e12.png)

Pipeline view

![image](https://user-images.githubusercontent.com/1969636/27119886-e431c338-50e1-11e7-83c1-87c5f0378e48.png)

The product view

![image](https://user-images.githubusercontent.com/1969636/27119949-197a631a-50e2-11e7-93f3-137c017b9564.png)


Jenkins pipeline

![image](https://user-images.githubusercontent.com/1969636/27119995-38aa7e32-50e2-11e7-9299-2d4b6e4e3339.png)


Artifact is generated and uploaded to nexus in BUILD stage.  Jobs named Update DevBoard only executes scripts that automates dashboard creation and updates widgets as pipeline view, monitor, etc

At dev_aws stage, the deploy application job executes a rundeck job to deploy artifact to his environment. Before this, create a dummy file with touch app-name and then execute hygieia publisher with this configuration:

![image](https://user-images.githubusercontent.com/1969636/27120111-9f1fa4bc-50e2-11e7-94a2-4d069c46b0e6.png)

At test_aws stage and live_aws stage jobs di the same but the environment names are TEST and LIVE

**Comment by rsans** [comment]
And the hygieia plugin global config 

![image](https://user-images.githubusercontent.com/1969636/27120292-43b3370a-50e3-11e7-970a-7b09bf0bb2cc.png)

**Comment by rsans** [comment]
![image](https://user-images.githubusercontent.com/1969636/27120350-78413350-50e3-11e7-80b3-36ec264ab5ef.png)

**Comment by hitorchi** [comment]
Just to make sure, you have have source control management pointing to your repo for your dev_aws and test_aws jobs correct?

Each job in Jenkins needs source control management configured and pointing to that one repo

**Comment by rsans** [comment]
Yes, all jobs point to the same git repository. But not master branch, each job uses the last commit id to checkout source.

**Comment by hitorchi** [comment]
Try pushing a fresh commit to the repo to see if it shows up in the commit box, then run the build step to see it moves into the build box

If that works, then run the dev_aws step and test_aws step to see if that fresh commit is moving from box to box.

If the fresh commit stops moving at a certain stage, tell me which one

**Comment by rsans** [comment]
The commit stops at build stage.

![image](https://user-images.githubusercontent.com/1969636/27135513-ee0fe15a-5118-11e7-907a-ce8f9b37b19d.png)

**Comment by hitorchi** [comment]
Can I see the console output of that build stage run? What is the Hygieia publisher plugin output?

**Comment by rsans** [comment]
jun 14, 2017 10:45:08 AM hygieia.builder.CommitBuilder buildCommits
INFORMACIÓN: Adding commit:null:null:50cab7b841608eddd8182a7f88129a75da51b871:Revert Spring version upgrade
jun 14, 2017 10:45:08 AM hygieia.builder.CommitBuilder buildCommits
INFORMACIÓN: Adding commit:null:null:e52ae5b36db303c6d521ab3675eec271b9ec84bc:Revert Spring version upgrade

**Comment by hitorchi** [comment]
Just to clarify, can you answer the previous question I asked?

Also, did you see anything that looks like "Hygieia: Published Deploy Data: Response Code: 201. Response Value= "59404513f4c94369ab89ca29" in your Jenkins console?

**Comment by rsans** [comment]
No lines with "Published Deploy Data" in jenkins.log master node

**Comment by hitorchi** [comment]
I'm assuming the dev_aws job was the one that failed to move the commit from the build box to the dev box on your product dashboard.

Can you send the full Jenkins console log of the dev_aws job?

**Comment by rsans** [comment]
Ok, at job log I found the Published Deploy Data

Rundeck execution #331855 finished in 13 minutes 13 seconds, with status : SUCCEEDED
Hygieia: Published Build Complete Data. Response Code: 201. Response Value= 5941263f302ada1b471dfff7
Hygieia Build Artifact Publisher - Looking for file pattern 'common-valuation-service' in directory /var/lib/jenkins/workspace/...
Hygieia Artifact Publisher: Processing  file: /var/lib/jenkins/workspace/....
Hygieia: Published Build Artifact Data. Filename=common-valuation-service, Name=common-valuation-service, Version=1.0-887, Group=com.xxx.common-valuation-service. Response Code: 201. Response Value= "59412b4d302ada1b471dfffe"
Hygieia Deployment Publisher - Looking for file pattern 'common-valuation-service' in directory /var/lib/jenkins/workspace/...
Hygieia Deployment Publisher: Processing  file: /var/lib/jenkins/workspace/...
Hygieia: Published Deploy Data: Response Code: 201. Response Value= "59412d24302ada1b471e0004"
Notifying upstream projects of job completion

**Comment by hitorchi** [comment]
Alright, so it seems Hygieia successfully detects the artifacts.

**Comment by rsans** [comment]
No, artifact is generated in build stage and uploaded to nexus. Other stages as dev_aws executes runeck job that download artifact from nexus. For the hygieia publisher I generate a dummy object with shell script  touch artifact-name"

**Comment by hitorchi** [comment]
Alright, I see. Can I see the workspace of your dev_aws job, specifically the directory that contains the .git folder?

**Comment by rsans** [comment]
![image](https://user-images.githubusercontent.com/1969636/27172200-aa033646-51b4-11e7-9497-11832f062d15.png)

**Comment by rsans** [comment]
In mongo db the pipeline collection only have commits for Build and Commit stages of product view.

![image](https://user-images.githubusercontent.com/1969636/27219411-ecb3c23a-5281-11e7-8e22-3da77e30e173.png)

Debuging the api, at pipeline object:

![image](https://user-images.githubusercontent.com/1969636/27219487-2a07fbc4-5282-11e7-8a7f-643e9e04204a.png)

**Comment by hitorchi** [comment]
<img width="920" alt="screen shot 2017-06-16 at 9 23 26 am" src="https://user-images.githubusercontent.com/16524900/27228411-80e51376-5275-11e7-8aab-16366ed4a471.png">

I have something similar, for some reason you seem to be missing artifacts. Are you sure you're publishing artifacts correctly?

**Comment by rsans** [comment]
I'm trying to get last commits from master and update jenkins plugin.

**Comment by rsans** [comment]
Ok, all up to date, but no news. Same problem.

I see at the log that hygieia publisher is executed before git clone....

Hygieia: Published Build Complete Data. Response Code: 201. Response Value= 594933c2302ada17a61893b4
[EnvInject] - Loading node environment variables.
Ejecutando remotamente en  slave-ip-11-183-66-35-5db5c3c3 en el espacio de trabajo /var/lib/jenkins/workspace/xxxx/yyyl-zzzg-api/zzzzzapi_DEPLOY_APPLICATION_DEV_AWS
Cloning the remote Git repository
Cloning repository ssh://git@stash.mycom:7999/key/xxxxl-zzzz-api.git

**Comment by rsans** [comment]
Here is de build in database searching for id of the jenkins job log: Hygieia: Published Build Complete Data. Response Code: 201. Response Value= 594933c2302ada17a61893b4

![image](https://user-images.githubusercontent.com/1969636/27340780-a76e1902-55db-11e7-96d0-366dbd6545fc.png)

**Comment by hitorchi** [comment]
Bizarre, it should be cloning the repo first before the Hygieia publisher plugin outputs its result. That is probably the main issue but I don't understand why a post-build action like Hygieia publisher would occur before the git cloning. 

Can you try adding the additional behaviour in source control manager to "Wipe out repository and clone"?

**Comment by rsans** [comment]
I'm using this option:

![image](https://user-images.githubusercontent.com/1969636/27369945-7f312f40-565a-11e7-8857-c45b6729359d.png)

**Comment by rsans** [comment]
And after all publishers I have:

![image](https://user-images.githubusercontent.com/1969636/27370172-aade1b0c-565b-11e7-8b85-a51c7c557f4a.png)

**Comment by rsans** [comment]
Added wipe out and same problem

Hygieia: Published Build Complete Data. Response Code: 201. Response Value= 594a16a3302ada17a61893e4
[EnvInject] - Loading node environment variables.
Ejecutando remotamente en  slave-ip-11-183-66-35-5db5c3c3 en el espacio de trabajo /var/lib/jenkins/workspace/key/xxx-yyyy-api/xxx-yyy-api_DEPLOY_APPLICATION_DEV_AWS
Wiping out workspace first.
Cloning the remote Git repository
Cloning repository ssh://git@stash.mycomp:7999/key/xxx-yyyy-api.git

![image](https://user-images.githubusercontent.com/1969636/27370977-199c8486-565f-11e7-8f4a-7835d1cd82c2.png)

**Comment by rsans** [comment]
Ok, after update hygieia publish plugin, no data is sent to hygieia api. Publisher ALWAYS is executed before  git clone. I will try to reinstall the plugin...

**Comment by rsans** [comment]
Reinstalled the plugin using last sources, same error

**Comment by rsans** [comment]
Modified publisher plugin and added some log lines. I see that only start method publish data to hygieia api. Method completed don't send data to the api.

![image](https://user-images.githubusercontent.com/1969636/27387714-c75849f4-5699-11e7-9df9-5e5cd3cc60c3.png)

**Comment by rsans** [comment]
Jenkins log shows nullPointerException at BuildBuilder.java line 100

![image](https://user-images.githubusercontent.com/1969636/27387914-4f5c6e3e-569a-11e7-9740-4f9842b2dd29.png)

**Comment by rsans** [comment]
The problem is that (AbstractBuild) run is null.  ¿Are you using last sources? Can you send me your .hpi file ?

**Comment by hitorchi** [comment]
Can you explain what you mean by last sources?

**Comment by rsans** [comment]
Last source code pushed to master.

**Comment by hitorchi** [comment]
I am, maybe it has something to do with how you build the Jenkins Hygieia publisher plugin?

**Comment by rsans** [comment]
mvn clean package

**Comment by hitorchi** [comment]
What maven version do you have?

**Comment by rsans** [comment]
3.3.9

**Comment by rsans** [comment]
Jenkins version 2.32.1

**Comment by hitorchi** [comment]
I have version 3.13.0 with Java 1.8 and Jenkins 2.46.2

**Comment by rsans** [comment]
Can you share your hpi file?

**Comment by rsans** [comment]
Thank ypu @hitorchi for your help. I solved the issue with this change.

![image](https://user-images.githubusercontent.com/1969636/27583326-4565d37c-5b34-11e7-8953-833fd69466b5.png)
