### ISSUE TITLE
How does Hygieia-Jenkins-Plugin store data in MongoDB?

### ISSUE THREAD

**Issue by HebbarA** [capitalone/Hygieia#1430]
We are using Hygieia-Jenkins-Plugin to get the Build, Artifact and Deploy results from Jenkins. 
Everything works fine but we wanted to know when and how does the Jenkins data gets inserted to MongoDB. Is it through Hygieia-Jenkins-Plugin but we dont see any save or insert function in Hygieia-Jenkins-Plugin source code. 

Can anyone help us know how it actually puts Jenkins build, artifact and deploy results to MongoDB.

**Comment by Sbrenthughes** [comment]
@HebbarA  see https://github.com/capitalone/Hygieia/tree/master/hygieia-jenkins-plugin
You will need a post build step to push your data to Hygieia. After it is pushed you will be able to select it from the widget.

**Comment by satishc1** [comment]
@HebbarA Its a rest call using jenkins.plugins.hygieia.DefaultHygieiaService

**Comment by HebbarA** [comment]
Thanks for the information. 

Currently the "**environment_components**" collection in **mongodb** contains deploy details, but it does not show the build number and in Hygieia Dashboard we find only the latest deploy (doesnot show Jenkins Job Build Number ). 
So in order to display build number on hygieia dashboard we are trying to insert the **build number** to "environment_components" collection in mongodb by altering hygieia-jenkins-plugin. 

Has anyone tried this out?. Any input would be helpful.
