### ISSUE TITLE
Deployment collector throwing error #1407

### ISSUE THREAD

**Issue by ashu5993** [capitalone/Hygieia#1436]
opening a new issue #1407 here as it is closed by collabrator.

Hi,

I have installed ssl certificate in JVM but still its throwing the same error.

**Comment by ashu5993** [comment]
can anyone help on this?

**Comment by nitin1706** [comment]
did you try this from #998 
`Try launching your jenkins collector specifying the location of your truststore.
-Djavax.net.ssl.trustStore=`

**Comment by nitin1706** [comment]
Re-open if issue still exists
