### ISSUE TITLE
Hygieia Integration with Artifactory

### ISSUE THREAD

**Issue by vmanojv** [capitalone/Hygieia#1441]
Hi Team

I have Jenkins Build job configured to deploy artifacts to Artifactory every 10 minutes. Configured Jenkins to point to Hygieia API and configured  Hygieia publisher in post build step.  Also start the Artifactory collector in Hygieia.

Below status of Artifactory collector:
2017-05-31 22:50:00,030 INFO  c.c.d.collector.CollectorTask - https://test-artifactory.mydomain.com/
2017-05-31 22:50:00,030 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-05-31 22:50:00,097 INFO  c.c.d.collector.CollectorTask - Fetched repos                    0s
2017-05-31 22:50:00,108 INFO  c.c.d.collector.CollectorTask - New repos               0        0s
2017-05-31 22:50:00,354 INFO  c.c.d.collector.CollectorTask - New artifacts           0        0s
2017-05-31 22:50:00,354 INFO  c.c.d.collector.CollectorTask - Finished                         0s

Can you please help me understand below queries. 

1. Though the artifact is getting deployed every minutes, its not reflecting in collector status, as show above.
2. Not getting the Artifactory status on the Dashboard.
3. Are we suppose to get the Artifact deploy status on Deploy widget?

Please let me know if any additional details required.

Thank You in advance.

Regards
Manoj

**Comment by MarkRx** [comment]
There currently is no UI for binary artifacts collection. At present that collection is only used by the product dashboard. As for not finding any artifacts it seems that you are not fetching any repositories. You need to be sure to set up the repositories to hit in the properties.

> # The repo to collect artifacts from (required) - Can provide multiple (comma separated for each server) 
> artifactory.repos[0]=prerelease,release

https://github.com/capitalone/Hygieia/tree/master/collectors/artifact/artifactory

You can turn on debug with this:

> logging.level.com.capitalone.dashboard.collector=DEBUG

**Comment by vmanojv** [comment]
Thanks Mark for the response. I have enabled the debug 
2017-06-07 01:50:00,385 DEBUG c.c.d.c.DefaultArtifactoryClient - Artifact at ./gs-maven-0.1.0.jar matched pattern 0
2017-06-07 01:50:00,385 DEBUG c.c.d.c.DefaultArtifactoryClient - Artifact at ./original-gs-maven-0.1.0.jar matched pattern 0

I am using default matching patterns:
artifactory.patterns[0]=(?<group>.+)/(?<module>[^/]+)/(?<version>[^/]+)/(?<artifact>\\k<module>)-\\k<version>(-(?<classifier>[^\\.]+))?(\\.(?<ext>.+))?

# Matches ivy files of the form [org]/[module]/[revision]/ivy-[revision](-[classifier]).xml
artifactory.patterns[1]=(?<group>.+)/(?<module>[^/]+)/(?<version>[^/]+)/(?<artifact>ivy)-\\k<version>(-(?<classifier>[^\\.]+))?\\.(?<ext>xml)

# Matches ivy artifact files of the form [org]/[module]/[revision]/[type]/[artifact]-[revision](-[classifier])(.[ext])
artifactory.patterns[2]=(?<group>.+)/(?<module>[^/]+)/(?<version>[^/]+)/(?<type>[^/]+)/(?<artifact>[^\\.-/]+)-\\k<version>(-(?<classifier>[^\\.]+))?(\\.(?<ext>.+))?

Can you please help me tweak the pattern match.

Also is there any pattern which can search for all artifacts. Say like:
artifactory.patterns[0]=(.*)

Regards
Manoj

**Comment by MarkRx** [comment]
That looks like it is working. Check your database - the binary_artifacts collection I believe - using a tool like robomongo.

You cannot use just .* because the collector needs to know how to extract group, module, version, etc information. That is done using named capture groups. You can create additional custom ones as needed. For example here is one that we use:

`artifactory.patterns[3]=(?<group>.+)/(?<buildnumber>\\d+)/([^/]+/)*(?<artifact>[^\\./]+)-(?<version>[^/]+)\\.(?<ext>(zip|dar))`

**Comment by nireeshT** [comment]
@vmanojv  Reopen if issue is not resolved
