### ISSUE TITLE
Gitlab collector : javax.net.ssl.SSLException: Unrecognized SSL message

### ISSUE THREAD

**Issue by prvnsinghal** [capitalone/Hygieia#1442]
when I am trying to run gitlab collector jar file then it is giving error:

> 2017-06-01 07:26:00,462 INFO  c.c.d.c.GitlabGitCollectorTask - Failed to retrieve data, the repo or collector is most likey misconfigured: https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.git, I/O error on GET request for "https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:80/api/v3/projects/Groupname%2FProjectname/repository/commits/?ref_name=develop&since=2017-05-18T07:26:00Z&per_page=100": Unrecognized SSL message, plaintext connection?; nested exception is javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?

Please help me on this

**Comment by prvnsinghal** [comment]
application.properties is given below:

> dbname=dashboarddb
> dbusername=dashboarduser
> dbpassword=dbpassword
> dbhost=127.0.0.1
> dbport=27017
> logging.file=./logs/gitlab.log
> gitlab.cron=0 0/1 * * * *
> gitlab.host=xyz.com
> gitlab.protocol=https
> gitlab.port=80
> gitlab.selfSignedCertificate=false
> gitlab.apiToken=xxxxxxxxxxxxxxxxxxxxxxx
> gitlab.commitThresholdDays=15
>

**Comment by prvnsinghal** [comment]
any solution guys???

**Comment by rob-miller-777** [comment]
Try making that selfSignedCertificate=true.

**Comment by prvnsinghal** [comment]
@rob-miller-777 i tried that way again, but no luck
giving same set of errors.

> GitlabGitCollectorTask - Failed to retrieve data, the repo or collector is most likey misconfigured: https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.git, I/O error on GET request for "https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:80/api/v3/projects/Groupname%2FProjectname/repository/commits/?ref_name=develop&since=2017-05-18T07:26:00Z&per_page=100": Unrecognized SSL message, plaintext connection?; nested exception is javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?

while I have imported all the certificates of Gitlab Server

**Comment by golokeshpatra45** [comment]
@prvnsinghal , is it a private repo ? or an enterprise level private repo ?

**Comment by prvnsinghal** [comment]
@golokeshpatra45 yes, It is enterprise private repo.
why??

**Comment by golokeshpatra45** [comment]
@prvnsinghal ,,
No worries ,
Go to Hygieia-Master -> UI and open README.md.
Scroll to the end and you will get,  Encryption for private repos

Now generate this key and add it to the properties file of both api and github i.e
Hygieia-master -> api -> target -> (properties file) -> key = (new generated private key )
Hygieia-master -> collectors ->scm -> github -> target -> open your properties file ->github.key = (new generated private key )

This key will help you encrypt your credentials .

Now run api then gulp serve then collectors.

**ask your IT to provide you with username and password to bypass the enterprise (GHE) login. GHE logins are different as compared to that of normal github logins as you enter your Windows login or LDAP or (many options). if you dont have such login then your collector should perform properly.

I had been unsuccessful in getting GHE populating my dashboard but now I have figured out. Hope you have got everything, any doubts do ask me .

**Comment by prvnsinghal** [comment]
@golokeshpatra45 
I tried this encryption for private repo. but could not get the data.

It is giving the same set of problems. please help me on this.

and yes we have configure LDAP for our gitlab, does it make any effect for authentication.

**Comment by golokeshpatra45** [comment]
@prvnsinghal , are you getting the same I/O get error ?

**Comment by rob-miller-777** [comment]
Think your issue comes from the protocol and port.  You currently have your protocol set to https, however you are using the standard http port of 80. Verify that both of those values are correct. I would guess that you can either remove the port altogether, or set it to 443, which is the standard https port.  Or if your server is on http, just change the protocol to http.

**Comment by Sbrenthughes** [comment]
@prvnsinghal Please reopen if you have any more issues.
