### ISSUE TITLE
Nullpointer error while running JIRA collector

### ISSUE THREAD

**Issue by seekdageek** [capitalone/Hygieia#1449]
Hi,

I am getting an Nullpointer error while running JIRA collector. 

Error is as below -

Caused by: java.lang.NullPointerException: null
	at java.io.File.<init>(File.java:277) ~[na:1.8.0_131]
	at org.stringtemplate.v4.STGroupDir.<init>(STGroupDir.java:53) ~[ST4-4.0.8.jar!/:4.0.8]
	at com.capitalone.dashboard.util.FeatureWidgetQueries.<init>(FeatureWidgetQueries.java:31) ~[jira-feature-collector.jar!/:2.0.5-SNAPSHOT]

I have built the JAR from the latest code taken from GitHub. I am running the collector using the command "java -jar jira-feature-collector.jar". I have attached the collector logs and collector configuration file herewith.

Would appreciate your help in this regard.

[jiracollector_log.txt](https://github.com/capitalone/Hygieia/files/1051292/jiracollector_log.txt)
[jira-feature-collector_properties.txt](https://github.com/capitalone/Hygieia/files/1051293/jira-feature-collector_properties.txt)

**Comment by irvingoe** [comment]
Hey I'm working on that collector right now, what's the command you are using to run it?
should be adding something like this after "java yourJar.jar" 
**--spring.config.name=jira-feature-collector --spring.config.location=src\main\resources**

**Comment by Sbrenthughes** [comment]
Try something like this `sudo java -jar <path to your jar file> --spring.config.name=jira-feature-collector --spring.config.location=<path to your prop file>`

**Comment by seekdageek** [comment]
Thanks a lot for your help @irvingoe and @Sbrenthughes I am able to run the collector now after adding the options mentioned by you.
