### ISSUE TITLE
Dashboard connectivity

### ISSUE THREAD

**Issue by Hima777** [capitalone/Hygieia#1452]
Hi I am able to run collectors , mngodb , api and UI successfully. Once the dashboard is up I am not able to see user details and also i am not able to create dashboard. The error i am getting is "Error creating dashboard , Change title and try again" . I have tried so many names but still I am facing this. Please help here as i didn't find any errors in logs...

**Comment by Sbrenthughes** [comment]
Are you able to create a user and login successfully?

**Comment by Hima777** [comment]
Hi,
Thank you for response.
I am able to create user and able to login. But while I am creating dashboard template we are getting above error. when we analyze with F12 we can see that it is giving unauthorized error. And we have changed the api port to 8090 and also we have changed the places in UI where 8080 has configured.

**Comment by nireeshT** [comment]
@Hima777  - share your properties file and api log.

**Comment by Hima777** [comment]
Properties file:
#dashboard.properties
dbname=dashboarddb
dbusername=dashboarduser
dbpassword=altria123
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017,127.0.0.1:27017,172.24.48.62:27017
server.contextPath=/api
server.port=8090
corsEnabled=false
auth.expirationTime=20

Api logs: Attaching the api log

[api_log.txt](https://github.com/capitalone/Hygieia/files/1056930/api_log.txt)

**Comment by nireeshT** [comment]
@Hima777  - which url is throwing unauthorized error

**Comment by Hima777** [comment]
@nireeshT  http://IP:3000/#/dashboard , I am trying to create dashboard once i am login but It is giving above error and it getting logout automatially

**Comment by nireeshT** [comment]
@Hima777  - Please rebase to latest code base

**Comment by nireeshT** [comment]
@Hima777  - Reopen if issue is not resolved.

**Comment by amoghntt** [comment]
HI I am getting similar error , even after changing the code.
Please give me a solution

**Comment by sachingupta771** [comment]
hi amoghntt
You can try the below method
cd <Hygieia_folder/UI>
 in gulpfile.js add port.
 
browserSync.init({
         port:80,
          server: {
              baseDir: hygieia.dist,
              startPath: '/',
              middleware: [proxyMiddleware]
          },
          ghostMode: ghostMode
      });

**Comment by amoghntt** [comment]
I tried it but still getting the same error "Error creating dashboard. Change title and try again." while creating new dashboard

**Comment by Hima777** [comment]
@amoghntt If you have mentioned **auth.expirationTime** in api property file, comment it. This has fixed the issue for me

Thanks,
Hima

**Comment by amoghntt** [comment]
Hi,
I do not have the auth.expiration time in my properties file.PLease find the details

Dashboard.properties
dbname=dashboarddb
#dbusername=[MogoDb Database Username, defaults to empty]
#dbpassword=[MongoDb Database Password, defaults to empty]
dbhost=localhost
dbport=27017

**Comment by amoghntt** [comment]
@Hima777  after changing the dashboard .properties file as per yours ..

my tomcat in api log is still showing connections as port 8080,But in properties file it is 8090.

My api log last few lines:
2017-08-15 11:28:43,843 INFO  o.a.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8080"]
2017-08-15 11:28:43,858 INFO  o.a.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-8080"]
2017-08-15 11:28:43,869 INFO  o.a.tomcat.util.net.NioSelectorPool - Using a shared selector for servlet write/read
2017-08-15 11:28:43,898 INFO  o.s.b.c.e.t.TomcatEmbeddedServletContainer - Tomcat started on port(s): 8080 (http)
2017-08-15 11:28:43,900 INFO  com.capitalone.dashboard.Application - Started Application in 11.335 seconds (JVM running for 12.308)
