### ISSUE TITLE
Docker & appdynamics

### ISSUE THREAD

**Issue by dsanchezseco** [capitalone/Hygieia#1454]
Currently appdynamics lacks of dockerfile and docker construction on the repo and therefore it breaks the build of `mvn docker:build`.

I solved temporally removing the two occurrences of         
```
<module>collectors/performance/appdynamics</module>
```
from the pom.xml on the root

**Comment by xiaods** [comment]
yes, same here.

**Comment by xiaods** [comment]
Hygieia publisher plugin is also not docker sub-directive

**Comment by MarkRx** [comment]
Please find the PR that added appD and tag the users here

**Comment by asg247** [comment]
PR #1674  has the changes to build docker image for appdynamics

**Comment by matthewbeasley** [comment]
PR #1674 and PR #1708 merged in. Please pull the latest code and try again. Your feedback is appreciated and desired.
