### ISSUE TITLE
Can we show the latest release on Hygieia Dashboard after build in Jenkins

### ISSUE THREAD

**Issue by prvnsinghal** [capitalone/Hygieia#1457]
if yes, 
can you please send me any link to do so.

Thanks in advance.

**Comment by satishc1** [comment]
@prvnsinghal Latest release of what?

**Comment by prvnsinghal** [comment]
for every build, It is releasing new version of Artifact in the target folder,
I want to show the latest version of module generated after Jenkins build on the Hygieia Dashboard.

**Comment by nireeshT** [comment]
@prvnsinghal  Not on build widget. When you deploy the same artifact to different environments, you can see that in Deploy widget when you click on each environment.

**Comment by nireeshT** [comment]
@prvnsinghal  Reopen if issue is not resolved.
