### ISSUE TITLE
Bitbucket cloud collector issue

### ISSUE THREAD

**Issue by meet101** [capitalone/Hygieia#1461]
@MarkRx  @mrpudn  @pxk5958 
I am having an issue while configuring bitbucket cloud private repo.
when i run the collector, I am getting below error,
```
2017-06-06 17:52:00,112 ERROR c.c.d.c.DefaultBitbucketCloudClient - 401 Unauthorized:
  https://bitbucket.org/api/2.0/repositories/cket.org/awsagero/testapi/commits?sha=master&since=2017-05-23T17:52Z
2017-06-06 17:52:00,114 INFO c.c.d.collector.CollectorTask - Repo Count 1 0s
2017-06-06 17:52:00,115 INFO c.c.d.collector.CollectorTask - New Commits 0 0s
2017-06-06 17:52:00,115 INFO c.c.d.collector.CollectorTask - Finished 0s
```
I did some research to find out why URL is saying Unauthorized. I have followed password encryption details provided on ReadME of UI Section.  Then i tried to check the URL by browsing it locally. It didn't work. I removed **/cket.org** After removing it. The new URL is https://bitbucket.org/api/2.0/repositories/awsagero/testapi/commits?sha=master&since=2017-05-23T17:52Z   It asked me for authentication, entered credentials and it worked. I got output as

{"pagelen": 30, "values": [{"hash": "bf9420418f08f9bf60d902e554ebb565ea2ab79c", "repository": {"links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/awsagero/testapi"}, "html": {"href": "https://bitbucket.org/awsagero/testapi"}, "avatar": {"href": "https://bitbucket.org/account/awsagero/avatar/32/"}}}}, "parents": [], "date": "2017-05-26T02:41:30+00:00", "message": "added all files\n", "type": "commit"}]}

I don't know, why in my URL it's adding /cket.org. can you please let me know how to remove it from URL. is it configured anywhere in DefaultBitBucketCloudClient? I am not adding it anywhere in bitbucket.properties file. 

here is my bitbucket.properties file
```properties
dbname=hygieiadb
dbhost=127.0.0.1
dbport=27017
dbusername=admin
dbpassword=admin
logging.file=./logs/bitbucket.log
git.cron=0 0/2 * * * *
git.host=bitbucket.org/
git.api=/api/2.0/repositories/
git.key=4DKrBLraYpKhC4pGJRCSRXMEcFekStx8
github.key=4DKrBLraYpKhC4pGJRCSRXMEcFekStx8
git.commitThresholdDays=15
git.pageSize=25
git.product=cloud
```
can some one please take a look into this and advice/suggest any solution?

Thank you.

**Comment by meet101** [comment]
I got it why URL is wrong, it was because of i had entered wrong url in UI widget. After fixing URL. but still after fixing URL, i am getting unauthorized 
```
2017-06-08 20:34:00,086 ERROR c.c.d.c.DefaultBitbucketCloudClient - 401 Unauthorized:https://bitbucket.org/api/2.0/repositories/awsagero/testapi/commits?sha=master&since=2017-06-08T20:22Z
2
```
Then i realize that i am getting errors in api section. When my bitbucket collector runs, i see an error on api as below,
```
2017-06-08 20:24:51,087 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [/api] threw exception
io.jsonwebtoken.SignatureException: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.
        at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:342) ~[jjwt-0.6.0.jar!/:0.6.0]
        at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:458) ~[jjwt-0.6.0.jar!/:0.6.0]
        at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:518) ~[jjwt-0.6.0.jar!/:0.6.0]

```
it looks like something wrong with encryption key i am using, what can be wrong? i make sure my key is correct, 
here is my api.properties file
```
dbname=hygieiadb
dbusername=admin
dbpassword=admin
dbhost=127.0.0.1
dbport=27017
key=4DKrBLraYpKhC4pGJRCSRXMEcFekStx8

```
can someone please help?, I have added same key in git.key and github.key

**Comment by sraghu-rs** [comment]
@meet101 - Can you please let me know what URL you put in the UI?

Currently i am also facing similar issue of URL getting added.

Did you added Repo URL as "**https://bitbucket.org/api/2.0/repositories/awsagero/testapi**" in UI?

for bitbucket.properties content as below (taken from your post)

git.host=bitbucket.org/
git.api=/api/2.0/repositories/

Regards,
Raghav

**Comment by sraghu-rs** [comment]
Never mind. I figured out the issue

**Comment by meet101** [comment]
Do you why am I getting this error about "JWT signature does not locally match locally computed signed"???? 
I am not using the URL in UI https://bitbucket.org/awsagero/testapi 

It worked for me. Now it's not adding URL as I mentioned above. Does my URL is correct? How did you fix it?

**Comment by sraghu-rs** [comment]
@meet101  - I am also facing similar error in api when i enter "key" attribute.

**Comment by meet101** [comment]
@sraghu-rs - can you tell me what URL are you using in UI? My URL is not working still. I am now trying with public repo to just make sure what is the issue. Public repo url is not working as well. If I put the correct Repo URL which is **https://awsagero@bitbucket.org/awsagero/test.git** 
then I am getting error  **404 Not Found:https://bitbucket.org/api/2.0/repositories/cket.org/awsagero/test/commits?sha=master&s                                                                     ince=2017-06-09T17:40Z as it is adding cket.org**

if i use **https://bitbucket.org/awsagero/test** URL in UI. it's not adding cket.org but still it's not working. what is correct URL?
Does anyone successfully integrated Bitbucket with hygieia??

**Comment by sraghu-rs** [comment]
@meet101  - I have done successful integration BitBucket Server with Hygieia. 

However, i am also struggling with BitBucket Cloud.

I am able to get the Repo count and commits from BitBucket cloud but dashboard doesn't display anything.

For the Repo URL i have used https://bitbucket.org/{user}/{repo}.git but this repo is public repo. 

At the end, i have to connect Private Repo and pull required information.
Now, i am getting error "JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted." when i use key and git.key attribute in properties file.

Not sure, is this a bug or missing something in the integration.

**Comment by sraghu-rs** [comment]
@meet101 - I was able to successfully integrate with BitBucket Private Repo. 

I have done below steps.

1. Logout from UI dashboard
2. Stop UI, and api
3. Generate key using 
java -jar <Hygieia folder>/core/target/core-2.0.5-SNAPSHOT.jar com.capitalone.dashboard.util.Encryption

4. Add the key to api.properties
key=WAFADdbmI3xArl2SXUmubdlK4CPyJWuK

5. Add the same key to BitBucket.properties file (to make sure, i have added both git.key and github.key)
**git.key=WAFADdbmI3xArl2SXUmubdlK4CPyJWuK
github.key=WAFADdbmI3xArl2SXUmubdlK4CPyJWu**K

6. Since my private key login depends upon SSO, i have to increase the field length of Repo username in the widget UI.
**UI\src\components\widgets\repo\config.html**

7. Start API
8. Start SCM collector job
9. start UI
10. Login to UI and configure repo widget
**Repo URL - https://bitbucket.org/{user}/{repo}.git**
_E.g- https://bitbucket.org/awsagero/test.git_

11. Enter the credentials of the Private Repo and save.
12. Once you enter the repo information, SCCM collector job will pick the repo URL and pull the information.
13. Refresh the dashboard to view the data.


Hope this helps.

Regards,
Raghav

**Comment by meet101** [comment]
@sraghu-rs  - Thank you for steps. I followed and stuck with 401 unauthorized error. can you do me a favor? can you share your bitbucket.properties file here? I just want to see, am i missing something there

**Comment by meet101** [comment]
@sraghu-rs - I got it work bit bucket cloud.  I had to change my repo password. It had special character. I didn't know it's not allowing special character. I changed it with number and alphabets. It worked. 
Do you have a special character in password? Do you know what changes do i need to make to allow special character?

Thanks for your help.

**Comment by sraghu-rs** [comment]
@meet101 - Glad to hear this. Yes, it has special characters like +_) and it worked.

**Comment by meet101** [comment]
@sraghu-rs - It worked for me also, with special character. Thanks again.

**Comment by email2niranjan** [comment]
@sraghu-rs 
I am facing similar issue... could you guys tell me how you worked around the special character password?
I mean.,. i dont want to change my password to remove special character (company policies)... just curious how you still got it worked with special character?
