### ISSUE TITLE
Display multiple Code Repo in one Dashboard

### ISSUE THREAD

**Issue by sraghu-rs** [capitalone/Hygieia#1468]
I have to collect the code commits from multiple Repositories under the same project and display in one dashboard. All Repositories BitBucket SCM.

Has anybody done this. Can suggestions please..

Regards,
Raghav

**Comment by sraghu-rs** [comment]
@MarkRx @satishc1 @tabladrum - Any suggestion.

**Comment by nireeshT** [comment]
@sraghu-rs  - multiple code repo feature is not available yet. Feel free to work on it, I would start with indexing the repo widgets and collect data as per the index and display back on UI.

**Comment by satishc1** [comment]
@sraghu-rs Refer to https://github.com/capitalone/Hygieia/issues/1064 and https://github.com/capitalone/Hygieia/issues/1241

**Comment by alihussainiF1** [comment]
I would like to also display all the repos in one dashboard can someone direct me to the place if the code exists (or we have to work on some modification on our own ?)
