### ISSUE TITLE
API compile fails a certain commit

### ISSUE THREAD

**Issue by edsyoo** [capitalone/Hygieia#1471]
After [this commit](https://github.com/capitalone/Hygieia/commit/d9c3af2a2efd7d8f48ca203b29db0236fd12802e), a `mvn install` for the api fails for me.  I've included the pertinent portion of the log, but let me know if I need to include more.  

As a further confusion, it fails on several Ubuntu servers I tested but it it compiles fine on my macbook (Sierra 10.12.5).

```Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.845 sec <<< FAILURE! - in com.capitalone.dashboard.auth.DefaultSecurityTest
registerUser(com.capitalone.dashboard.auth.DefaultSecurityTest)  Time elapsed: 0.052 sec  <<< FAILURE!
java.lang.AssertionError: Status expected:<200> but was:<401>
        at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:60)
        at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:89)
        at org.springframework.test.web.servlet.result.StatusResultMatchers$10.match(StatusResultMatchers.java:655)
        at org.springframework.test.web.servlet.MockMvc$1.andExpect(MockMvc.java:171)
        at com.capitalone.dashboard.auth.DefaultSecurityTest.registerUser(DefaultSecurityTest.java:87)

Running com.capitalone.dashboard.auth.ldap.LdapAuthenticationDetailsSourceTest```

**Comment by xiaods** [comment]
rebase and build again.

**Comment by edsyoo** [comment]
I am pulling from master branch and I also tried cloning the repo and running it again, but it still fails for me.  For reference, it did build on RH and my macbook.

**Comment by GooseYArd** [comment]
I hit the same problem building on a Debian Stretch system yesterday on the first build following cloning the repo.

**Comment by nitin1706** [comment]
Build from latest codebase. Re-open if still exists.

**Comment by neerajram** [comment]
Working on a CentOS machine now and facing this issue. Having the same error. 
Can someone tell me what is it related to? Is it a db config issue?

**Comment by neerajram** [comment]
The whole build is successful if I'm executing "mvn clean install package -DskipTests" command. But will there be any complications later?

**Comment by nitin1706** [comment]
@neerajram : I tried building latest codebase, it went through fine with no errors of test cases. 
If you are facing an error for test case, try getting latest codebase after re-base, if it is still there, you can skip it, it should not be any trouble later.

**Comment by neerajram** [comment]
@nitin1706 Can I ask what machine are u using? 
![error](https://user-images.githubusercontent.com/29804757/31097760-75ce3c2e-a78e-11e7-9637-2f44371924ce.JPG)

The error is:
`2017-10-02 16:25:15,045 INFO  o.s.t.w.s.TestDispatcherServlet - FrameworkServlet '': initialization completed in 2 ms
Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.137 sec <<< FAILURE! - in com.capitalone.dashboard.auth.DefaultSecurityTest
registerUser(com.capitalone.dashboard.auth.DefaultSecurityTest)  Time elapsed: 0.019 sec  <<< FAILURE!
java.lang.AssertionError: Status expected:<200> but was:<401>
        at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:60)
        at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:89)
        at org.springframework.test.web.servlet.result.StatusResultMatchers$10.match(StatusResultMatchers.java:655)
        at org.springframework.test.web.servlet.MockMvc$1.andExpect(MockMvc.java:171)
        at com.capitalone.dashboard.auth.DefaultSecurityTest.registerUser(DefaultSecurityTest.java:87)

`

**Comment by nitin1706** [comment]
It doesn't depend on machine. Make sure it has proxy setup. I just tried with the latest code base, it took some time to build, but it went through fine.

**Comment by kumaraqua** [comment]
I am having this issue too.. Double checked all the proxy settings.
