### ISSUE TITLE
Product Dashboard showing failed builds

### ISSUE THREAD

**Issue by narayan1ap** [capitalone/Hygieia#1472]
Product dashboard is showing builds as failed with red squares. But actually the builds are green. 
Also when I click on build widget in product dashboard pipeline, it shows the commit comments in red color. 

Any help is appreciated.

**Comment by nireeshT** [comment]
@narayan1ap  - share screenshot.

**Comment by nireeshT** [comment]
@narayan1ap  - Update to latest code base, rebuild plugin and install. Refer https://github.com/capitalone/Hygieia/issues/1512 .Reopen if issue is not resolved
