### ISSUE TITLE
Code Repo - Bitbucket Collector - Save button not working

### ISSUE THREAD

**Issue by clearn77** [capitalone/Hygieia#1474]
Hi Everyone,

I am facing below issue where I am not able to perform 'Save' operation in 'Configure' section of 'Code Repo' for Bitbucket . When I click on 'Save' button, system does not respond and it stays as it is.

From other threads, I found that api and collector needs to be run for this. I have executed both of them and both of them are running properly.

Could you please help me here?

I have pasted my properties file below for your reference:

- dbname=dashboarddb
- dbusername=dashboarduser
- dbpassword=dbpassword
- dbhost=localhost
- dbport=27017
- dbreplicaset=false
- dbhostport=localhost:27017
- server.contextPath=/api
- server.port=8080
- git.cron=0 0/5 * * * *
- git.host=bitbucket.company.com/
- logging.file=./logs/bitbucket.log
- git.api=/rest/api/1.0/
- git.key=H4p6cK4testetsteQitBEo+testetetetettetete
- git.commitThresholdDays=15
- git.pageSize=25
- git.product=server

**Comment by NeetiM** [comment]
@clearn77 : Please share the logs.

**Comment by nitin1706** [comment]
@clearn77 : this maybe due to the reason session logged out. try again by refresh and logging in again.

**Comment by nitin1706** [comment]
re-open with logs.
