### ISSUE TITLE
Jira MongoDB Collection Sample

### ISSUE THREAD

**Issue by irvingoe** [capitalone/Hygieia#1476]
Hi,
Can someone share with me the structure of how it looks the MongoDB collections with data from Jira?
I'm working on a customization for another feature collector but even though I have data in my db I don't get anything populated on my dashboard.

I'm looking for data from Feature, Scope and Team collections
I would like to understand what values is this collector (Jira) expecting.
This is an example of one document from my feature collection.
![image](https://user-images.githubusercontent.com/8560183/27102468-606f46da-5053-11e7-895e-e9f4bdc0cb47.png)

Thanks in advance guys!

**Comment by xiaods** [comment]
+1

**Comment by irvingoe** [comment]
I also tried to use the test data from the Jira collector but if I do that, I don't even get the current Iteration information so I am guessing that information is outdated, isn't it?

**Comment by irvingoe** [comment]
nvm I figured it out.

**Comment by Sandeep-Mandori** [comment]
what was the solution, if you can elaborate a bit, it may help many. Seems like i am having same issue.

**Comment by irvingoe** [comment]
Well, in my case it was 2 things (that I remember so far)
1. I registered my collector under a different name (than Jira) and that was causing an issue when showing it in the UI
2. The core project wasn't updated to reflect the new properties I added for the Feature model and I had to update it (core project) then update its dependency within the API project so the UI could finally pick the missing data

They put a bit of information around the schema here
http://capitalone.github.io/Hygieia/dbschema.html

But yeah basically is that if you make changes to a collector you gotta follow the chain
Collector > Core > API > UI
