### ISSUE TITLE
found api module Dockerfile missing a config

### ISSUE THREAD

**Issue by xiaods** [capitalone/Hygieia#1477]
for quick runing docker-compose demo, found the api logs raised error. so check the Dockerfile, found missing a config

ENV SPRING_DATA_MONGODB_PASSWORD=ENC(oMDFvt5wzfXx5pxgG2qgNw==)
ENV JASYPT_ENCRYPTOR_PASSWORD=hygieiasecret

and SPRING_DATA_MONGODB_PASSWORD should be generate again.

**Comment by matthewbeasley** [comment]
@xiaods - we've made some improvements in this area. Please pull the latest and try again.
