### ISSUE TITLE
org.jenkins-ci.plugins:hygieia-publisher:hpi:2.0.5-SNAPSHOT

### ISSUE THREAD

**Issue by xxlaila** [capitalone/Hygieia#1481]
[INFO] com.capitalone.dashboard:subversion-collector ...... SUCCESS [  1.272 s]
[INFO] com.capitalone.dashboard:gitlab-scm-collector ...... SUCCESS [  2.035 s]
[INFO] Hygieia Publisher Plugin ........................... FAILURE [  0.717 s]
[INFO] com.capitalone.dashboard:UI ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:08 min
[INFO] Finished at: 2017-06-16T16:18:30+08:00
[INFO] Final Memory: 118M/282M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project hygieia-publisher: Could not resolve dependencies for project org.jenkins-ci.plugins:hygieia-publisher:hpi:2.0.5-SNAPSHOT: Failure to find org.jenkins-ci.plugins:plugin:jar:2.0 in http://repo.jenkins-ci.org/public/ was cached in the local repository, resolution will not be reattempted until the update interval of repo.jenkins-ci.org has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hygieia-publisher

To this step, get through, how to get, ask you big gods

**Comment by irvingoe** [comment]
I'd recommend reading through #1219

**Comment by nireeshT** [comment]
@xxlaila  - reopen if issue is not resolved
