### ISSUE TITLE
Pom compilation error while installing latest Hygieia version

### ISSUE THREAD

**Issue by Ishan1987** [capitalone/Hygieia#1482]
I am getting below mentioned error while i was trying to install hygieia instance in linux OS.

Caused by: org.codehaus.plexus.util.xml.pull.XmlPullParserException: Expected root element 'project' but found 'html' (position: START_TAG seen ...OCTYPE html PUBLIC "//W3C//DTD HTML 4.01 Transitional//EN">\n<html>... @2:7)

[WARNING] 'parent.relativePath' of POM org.jenkins-ci.plugins:hygieia-publisher:2.0.5-SNAPSHOT (/opt/Hygieia-master/hygieia-jenkins-plugin/pom.xml) points at com.capitalone.dashboard:Hygieia instead of org.jenkins-ci.plugins:plugin, please verify your project structure @ line 15, column 13

Could you please provide me solution here?

**Comment by nireeshT** [comment]
@Ishan1987  - Paste your /hygieia-jenkins-plugin/pom.xml here

**Comment by Sbrenthughes** [comment]
@Ishan1987 Please reopen if you continue to experience the issue.
