### ISSUE TITLE
Upgrade apache commons-lang to latest version 3.6

### ISSUE THREAD

**Issue by chtompki** [capitalone/Hygieia#1485]
Pull request forthcoming. Documenting issue.

**Comment by chtompki** [comment]
Note anything using the package `org.apache.commons.lang.*` is quite old and *should* be upgraded to using `org.apache.commons.lang3` the 3.x line of commons-lang. Furthermore, this is generalized across all apache commons libraries, where the package gets versioned along with major version changes for the ability to consume two different major versions of a component. However, that is merely a mechanism for migration.

Thus all of these might be worth addressing:
https://github.com/capitalone/Hygieia/search?l=Java&q=org.apache.commons.lang.&type=&utf8=✓

**Comment by chtompki** [comment]
Why are we versioning jars independently in their individual components, and not in the parent? Couldn't' this cause notable classpath collisions?

**Comment by satishc1** [comment]
Closed.
