### ISSUE TITLE
In product dash board commit pipeline is not showing contents. 

### ISSUE THREAD

**Issue by narayan1ap** [capitalone/Hygieia#1487]
![image](https://user-images.githubusercontent.com/14268253/27254914-4556a996-53b0-11e7-9c9a-8e836a72348a.png)

The above one is team dashboard using github repo of hygieia . 

When I use this team in product dashboard, it shows nothing . 

![image](https://user-images.githubusercontent.com/14268253/27254918-723fb22c-53b0-11e7-97a8-51933719fccc.png)

**Comment by nireeshT** [comment]
@narayan1ap  are you using Jenkins Hygieia publisher plugin?

**Comment by narayan1ap** [comment]
No I am not using . Is it mandatory to use that plugin in order to show the contents of hygiene commit widget in product pipeline ?

**Comment by nireeshT** [comment]
@narayan1ap  - You have to configure build and code repo widgets to see the commits in prod dashboard.

**Comment by narayan1ap** [comment]
I debugged and found out that if the commit types are "merge" , it will not show . why is this behavior could you explain please. 
Also its event based. It happens only for the commits that occurred after setting the product dashboard. It does not fetch older commits. Any thoughts on this ?

**Comment by nireeshT** [comment]
@narayan1ap  rebase to latest code base and create product dashboard

**Comment by nireeshT** [comment]
@narayan1ap  Refer https://github.com/capitalone/Hygieia/issues/1512 . Reopen if issue is not resolved.
