### ISSUE TITLE
Sonar Collector only showing ncloc values

### ISSUE THREAD

**Issue by willuk2010** [capitalone/Hygieia#1490]
Hi, 

I have Sonar 6.3, latest Hygieia code, but it only appears to be pulling ncloc values, (that's all i see in Mongo db code_quality)

     - MONGO_PORT=tcp://hygieia-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=dashboard
      - SPRING_DATA_MONGODB_PASSWORD=dbpass
      - SONAR_CRON=0 * * * * *
      - SONAR_URL=http://uk-sonar.almuk.xxxxxxxxxx.corp
      - SONAR_METRICS=ncloc,line_coverage,violations,critical_violations,major_violations,blocker_violations,violations_density,sqale_index,test_success_density,test_failures,test_errors,tests
      - SONAR_VERSION=6.3
      - SONAR_USERNAME=xxxxx
      - SONAR_PASSWORD=xxxxx

If i go to the API in sonar, for the project in question, i get the following values.

https://uk-sonar.almuk.xxxxxxxxxx.corp/api/project_analyses/search?project=com.xxxxxxxx:dualadmin-api

{"paging":{"pageIndex":1,"pageSize":100,"total":4},"analyses":[{"key":"AVzLPVPwLmg51I2DfLPj","date":"2017-06-21T15:18:22+0000","events":[{"key":"AVzLPV_rLmg51I2DfLPu","category":"VERSION","name":"0.0.10-SNAPSHOT"}]},{"key":"AVzLMZpcLmg51I2DfLOs","date":"2017-06-21T15:07:10+0000","events":[{"key":"AVzLMaQxLmg51I2DfLPH","category":"QUALITY_GATE","name":"Green (was Red)","description":""}]},{"key":"AVzLKXsr8cqmUoHeyKgS","date":"2017-06-21T14:58:14+0000","events":[]},{"key":"AVzLJPK_8cqmUoHeyKdD","date":"2017-06-21T14:53:16+0000","events":[{"key":"AVzLJPzz8cqmUoHeyKf2","category":"QUALITY_GATE","name":"Red","description":"Reliability Rating > 3"}]}]}

Any ideas?

@nireeshT

**Comment by willuk2010** [comment]
to add, if i insert the test data (https://github.com/capitalone/Hygieia/blob/5bfb135d8a8cfe73dead7d1004454b19da711007/UI/src/test-data/ca_detail.json) then, it all displays as expected, so its definitely something to do with the collector not getting values back.

**Comment by willuk2010** [comment]
something else to add, if i change the sonar.metrics, to have say.. "quality_gate_details" first, instead of "ncloc", only "quality_gate_details" data is written into the code quality table..

It appears to be collecting data for only the first metric, and no more..

**Comment by AuditHawks** [comment]
Note that the properties need to be in this format:
```
# Sonar server(s) (required) - Can provide multiple
sonar.servers[0]=http://sonar.company.com
# Sonar version, match array index to the server. If not set, will default to version prior to 6.
sonar.versions[0]=6.31
# Sonar Metrics - Required. 
#Sonar versions lesser than 5.4
sonar.metrics[0]=ncloc,line_coverage,violations,critical_violations,major_violations,blocker_violations,violations_density,sqale_index,test_success_density,test_failures,test_errors,tests
#for Sonar 5.4 and above
sonar.metrics[0]=ncloc,violations,new_vulnerabilities,critical_violations,major_violations,blocker_violations,tests,test_success_density,test_errors,test_failures,coverage,line_coverage,sqale_index,alert_status,quality_gate_details
```

**Comment by willuk2010** [comment]
arrrrrrrrrrrrrg..

I'm using dockers, the issue is that the shell script to create the .properties is wrong (sonar-codequality-properties-builder.sh)!

Currently its,

#Sonar Metrics
sonar.metrics=${SONAR_METRICS:-ncloc,line_coverage,violations,critical_violations,major_violations,blocker_violations,sqale_index,test_success_density,test_failures,test_errors,tests}

Instead of

#Sonar Metrics
sonar.metrics**[0]**=${SONAR_METRICS:-ncloc,line_coverage,violations,critical_violations,major_violations,blocker_violations,sqale_index,test_success_density,test_failures,test_errors,tests}

Changed, and its working, thanks for pointing me in the right direction @AuditHawks
