### ISSUE TITLE
Jira collector 404 error

### ISSUE THREAD

**Issue by RameshMuthuraj** [capitalone/Hygieia#1497]
Error :- 
 No result was available from Jira unexpectedly - defaulting to blank response. The reason for this fault is the following:RestClientException{statusCode=Optional.of(404), errorCollections=[]}
2017-06-23 05:03:00,110 INFO  c.c.d.collector.CollectorTask - Project Data            0        0s
2017-06-23 05:03:00,113 ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
java.lang.NullPointerException: null

My property file:-
#PageSize
feature.pageSize=100

# api.query.folder=${base.config.dir}/jiraapi-queries
feature.queryFolder=jiraapi-queries
# Jira API Query file names (String template requires the files to have .st extension)
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo

#Jira Connection Details
######################
# Trending Query need Number of Days After today to filter out Sprints which ends in future.
# This will used to filter Kanban project which has 20 years of Sprints
feature.sprintDays=60
# Trending Query also need Number of Days prior to look for Sprints which has already Ended
feature.sprintEndPrior=7
######################
#Scheduled Job prior minutes to recover data created during execution time
feature.scheduledPriorMin=2
#Delta change date that modulates the collector item task (which should not see changes often)
feature.deltaCollectorItemStartDate=2008-01-01T00:00:00.000000

######################
#Spring Application Properties
spring.data.mongodb.database=dashboarddb
spring.data.mongodb.host=devops
spring.data.mongodb.port=27017
spring.data.mongodb.username=dashboarduser
spring.data.mongodb.password=XXXXXX

#Jira Connection Details
#feature.jiraProxyUrl=
#feature.jiraProxyPort=8081
feature.jiraBaseUrl=https://XXX.com/login.jsp?noSAML
feature.jiraCredentials=
feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=
# In Jira, general IssueType IDs are associated to various "issue"
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide the name value reference to your instance's IssueType for
# the lowest level of Issues (e.g., "user story") specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType Name
# listings via the following URI:
# https://[your-jira-domain-name]/rest/api/2/issuetype/.  It is listed as
# attribute "name" in the JSON response.
feature.jiraIssueTypeId=Story
# In Jira, your instance will have its own custom field created for "sprint" or "timebox" details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name <em>com.atlassian.greenhopper.service.sprint.Sprint</em>;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraSprintDataFieldName=customfield_10007
# In Jira, your instance will have its own custom field created for "super story" or "epic" back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (e.g., epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraEpicIdFieldName=customfield_10400

######################
#Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 * * * * *

#StartDate
feature.deltaStartDate=2015-03-01T00:00:00.000000
feature.masterStartDate=2008-01-01T00:00:00.000000

#Core Artifacts
# These arrays of status mappings must be completed in order for custom source system statuses to be providable by
# Hygieia.  Currently, Hygieia only maps to the following 3 status mappings:  to do, doing, and done.  You can find
# all available issue status mappings by going to your instance's version of the following API call:
# http://fake.jira.com/rest/api/2/status/.  Your statuses are listed in the JSON response as "name."
feature.todoStatuses[0]=
feature.doingStatuses[0]=
feature.doneStatuses[0]=

Please let me know what configuration i missed ?

**Comment by MarkRx** [comment]
What is the rest of the exception?

> 2017-06-23 05:03:00,113 ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
> java.lang.NullPointerException: null

**Comment by nitin1706** [comment]
can you please try with latest code and see if the issue still exists. I believe this has been resolved in latest code.

**Comment by Sbrenthughes** [comment]
Please reopen if this is still an issue.
