### ISSUE TITLE
Jira collector issue

### ISSUE THREAD

**Issue by RameshMuthuraj** [capitalone/Hygieia#1498]
Do we have any option for NO SAML authentication when we connect through JIRA

I have username & passwd though i have created Base64 encode using 
echo -n username:passwd base64

Now i can able to connect but it showing 404 error..Please met me know the sample properties file for this issue

**Comment by mashanm** [comment]
+ 1

**Comment by nitin1706** [comment]
are you still facing this? 
this maybe helpful: #1549

**Comment by nitin1706** [comment]
@RameshMuthuraj : are you still facing this issue?

**Comment by nitin1706** [comment]
@RameshMuthuraj : are you still facing this? Did you have a look the above mentioned issue.

**Comment by nitin1706** [comment]
Refer #1549. Re-open if issue not resolved
