### ISSUE TITLE
Hygieia Core collector 

### ISSUE THREAD

**Issue by RameshMuthuraj** [capitalone/Hygieia#1499]
Why do we need Core collector ? I m running JIRA,Bitbucket,AWS&Jenkins collector for creating new Dashboard

Is this really required to build the jar and deploy the server ? in that case how this will be helpful ?

**Comment by rob-miller-777** [comment]
It's not really a collector, it's a jar that all the collectors and api consume.  So it does need to be built, but not actually ran.  The pom's should probably be reorganized a bit so the core project doesn't look like a spring boot app.

**Comment by Sbrenthughes** [comment]
@RameshMuthuraj - Please reopen if you have anymore questions.
