### ISSUE TITLE
Performance Collector not showing data

### ISSUE THREAD

**Issue by ganeshmuralidhar** [capitalone/Hygieia#1500]
Reopening old issue:

https://github.com/capitalone/Hygieia/issues/1479

Last Comment : 
I left it for more than 30 mins and still do not see any metrics. Consider this request and can you please provide me below data:

What are the metrics you have in your AppDynamics dashboard?
What is the URL you mentioned in your Appd.properties file? (if you share a screenshot with details masked, it will be helpful)

**Comment by nireeshT** [comment]
@ganeshmuralidhar 

dbname=
dbhost=
dbport=
dbusername=
dbpassword=
logging.file=./logs/appd-collector.log

appdynamics.cron=1 * * * * *
appdynamics.instanceUrls=http://appdyn-**********.com
appdynamics.username=giveyourusername@Customer1
appdynamics.password=
appdynamics.dashboardUrl=http://appdyn-******.com/controller/#/location=APP_DASHBOARD&timeRange=last_15_minutes.BEFORE_NOW.-1.-1.15&application=%s&dashboardMode=force

**Comment by nireeshT** [comment]
@ganeshmuralidhar - issue resolved?

**Comment by ganeshmuralidhar** [comment]
Hi @nireeshT,

Sorry to say, but this is like the 3rd time I am asking if I get the list of metrics you added in your AppdDynamics dashboard and I still did not get that detail. And hence my answer would be the same that... i left it for more than 30 mins and I still do not see any data coming back to Hygieia. Hence, request you to please give me the below detail : 

--> What are the metrics you have in your AppDynamics dashboard?

**Comment by nireeshT** [comment]
@ganeshmuralidhar  - this is my mongo collection 

/* 1 */
{
    "_id" : ObjectId("592d577efba23cf18a60c1fd"),
    "_class" : "com.capitalone.dashboard.model.Performance",
    "collectorItemId" : ObjectId("58ee3b9da74dabc00816447d"),
    "timestamp" : NumberLong(1496143742077),
    "type" : "ApplicationPerformance",
    "metrics" : {
        "averageResponseTime" : NumberLong(1),
        "totalCalls" : NumberLong(240),
        "errorsperMinute" : NumberLong(0),
        "businessTransactionHealthPercent" : 1.0,
        "nodeHealthPercent" : 1.0,
        "violationObject" : [],
        "totalErrors" : NumberLong(0),
        "errorRateSeverity" : NumberLong(0),
        "responseTimeSeverity" : NumberLong(0),
        "callsperMinute" : NumberLong(16)
    }
}

if this is what you are asking for..

**Comment by ganeshmuralidhar** [comment]
I am afraid that is not what I am looking for. 

So, one of the parameters we are passing in Appd properties file is 'appdynamics.dashboardUrl'. You are giving the URL of a dashboard that you have setup on AppDynamics. I am asking what widgets and what metrics did you configure on that dashboard of AppDynamics. 

Like my dashboard if you see in my prev comment is configured to show Average Response time, calls per minute, etc.,

it would be great if you can give the snapshot of your dashboard from AppD.

**Comment by nireeshT** [comment]
@ganeshmuralidhar 
<img width="1171" alt="screen shot 2017-08-01 at 1 24 46 pm" src="https://user-images.githubusercontent.com/22962180/28838032-f4b5cf32-76bc-11e7-9c00-7b9050d58f0b.png">

**Comment by ganeshmuralidhar** [comment]
Thanks for the reply. So now that means, it is not the custom dashboards that are built but the application dashboard that need to be referred here. Well I did it and it's been 30 mins ever since and I do not see any data coming up still. Below are the snapshots.

If these help, please let me know what am I missing.

![apicollector_lastlog](https://user-images.githubusercontent.com/29456270/28858326-731c247e-776d-11e7-92c8-81ff60b4a926.png)
![appdcollector_lastlog](https://user-images.githubusercontent.com/29456270/28858327-731f3434-776d-11e7-9ff4-adec52fd46a8.png)
![dataonappddashboard](https://user-images.githubusercontent.com/29456270/28858328-7320850a-776d-11e7-8309-2be65f7a7d41.png)
![hygieiaperformancewidget_nodata](https://user-images.githubusercontent.com/29456270/28858329-73249744-776d-11e7-8793-f85febd4084a.png)
![appdproperties](https://user-images.githubusercontent.com/29456270/28858393-cacb623e-776d-11e7-9e82-aee12b0fe27f.png)

**Comment by nireeshT** [comment]
@ganeshmuralidhar  do you see performance collection in mongo.

**Comment by ganeshmuralidhar** [comment]
Not sure how to check that. Can you please guide me? Thanks! @nireeshT

**Comment by nireeshT** [comment]
@ganeshmuralidhar  - go to mongodb in terminal and search for performance collection with this 
db.getCollection('performance').find({})
It should give back results. You can also look via Robomongo.

**Comment by ganeshmuralidhar** [comment]
hey @nireeshT  - So after leaving the API, Performance collectors left for more than 30 mins, i see that i am not seeing any metrics on Mongo as well :(
here is the snapshot - 

![image](https://user-images.githubusercontent.com/29456270/29012727-7254502e-7b5b-11e7-85b1-35454e6a053e.png)

What am I doing wrong here?

**Comment by nireeshT** [comment]
@ganeshmuralidhar  -share  appdynamics collector log

**Comment by ganeshmuralidhar** [comment]
@nireeshT 
![image](https://user-images.githubusercontent.com/29456270/29015423-9a8835be-7b6b-11e7-844d-e857467dbdef.png)

**Comment by sanchitacool** [comment]
How to create bar chart  in hygieia for feature widget

**Comment by nireeshT** [comment]
@ganeshmuralidhar  - reopen if issue is not resolved
