### ISSUE TITLE
Product dashboard not showing environments. 

### ISSUE THREAD

**Issue by narayan1ap** [capitalone/Hygieia#1503]
Product dashboard only shows Commit and Build . I have already setup the Deploy widget . But still there is no widget in mongo team dashboard which has name "pipeline". 

I see that we add a pipeline widget in a test in PipelineServiceTest. 
But in real code its not happening. Can you point me the correct code to debug.

**Comment by narayan1ap** [comment]
Basically wanted to know who is creating "pipeline" widget in dashboard.

**Comment by nireeshT** [comment]
@narayan1ap  configure pipeline widget with environments listed. Check PipelineServiceImpl.java

**Comment by luweiyulin** [comment]
@narayan1ap  How can I show commit in my Product dashboard,it only shows  Build,Thank you very much .

**Comment by narayan1ap** [comment]
@luweiyulin  if you are using gitlab commit type will be merged. You have to allow merged types commit in the commit event listener.  Also once build is done commit will move to build and you will not see them in commit pipeline anymore.

**Comment by willuk2010** [comment]
@narayan1ap im using Gitlab, can you elaborate a bit more on enabling merged types in the commit event listener?

Cheers
Will

**Comment by luweiyulin** [comment]
@narayan1ap  Thanks ,but i am using SVN, How can I show commit in my Product dashboard?

**Comment by narayan1ap** [comment]
Open the file CommitEventListener.java
there you can see following line 
if (CommitType.New.equals(commit.getType())){


change it to .. 
 
if (CommitType.New.equals(commit.getType()) || CommitType.Merge.equals(commit.getType())) {

Build again using mvn clean install in the main Hygieia folder and rerun the scm collector.

**Comment by nireeshT** [comment]
@narayan1ap  - Refer https://github.com/capitalone/Hygieia/issues/1512 . Reopen if issue is not resolved.
