### ISSUE TITLE
Product dashboard without commits on environments after Build and Commit

### ISSUE THREAD

**Issue by rsans** [capitalone/Hygieia#1504]
Hi, I have a product view wich not shows any commit on environments after Build and Commit boxes.

This is the jenkins pipeline view, description of principal jobs and his hygieia publisher configuration:

![image](https://user-images.githubusercontent.com/1969636/27637688-e22aa1c4-5c10-11e7-9304-0794114f93f4.png)

And these are the team and product dashboards:

![image](https://user-images.githubusercontent.com/1969636/27637707-f5361334-5c10-11e7-9f2c-d922cc3466fa.png)

¿What I'm doing wrong?

**Comment by nireeshT** [comment]
@rsans  - Get the latest code base and do below steps 
1) Do a commit to github
2) Run build and deploy jobs (DEV,TEST,STAGE,PROD) which has Hygieia plugin configured.
3) In you team dashboard, reconfigure deploy widget and pipeline widget with DEV,TEST,STAGE.
4) Add team dashboard to product dashboard. 
5) Repeat steps 1 and 2 , refresh product dashboard. 

Jenkins version ?

**Comment by rsans** [comment]
Jenkins version 2.32.1

**Comment by nireeshT** [comment]
@rsans  - Reopen if issue is not resolved
