### ISSUE TITLE
Can't get jenkins build info when use jenkins build collector

### ISSUE THREAD

**Issue by wdquan1985** [capitalone/Hygieia#1506]
I can get jenkins build info when I run this collector in eclipse:
**2017-06-29 10:59:59,989 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2017-06-29 11:00:00,060 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-06-29 11:00:00,060 INFO  c.c.d.collector.CollectorTask - https://~~~~~~~~~.com/
2017-06-29 11:00:00,060 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-06-29 11:00:08,610 INFO  c.c.d.collector.CollectorTask - Fetched jobs                     8s
2017-06-29 11:00:08,625 INFO  c.c.d.collector.CollectorTask - New jobs                0        0s
2017-06-29 11:00:08,760 INFO  c.c.d.collector.CollectorTask - New builds              0        0s
2017-06-29 11:00:08,760 INFO  c.c.d.collector.CollectorTask - Finished                         8s**

But when I run this collector in Linux, it hangs and can't get any info.
**2017-06-28 22:45:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2017-06-28 22:45:00,033 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:6, serverValue:24}] to localhost:27017
2017-06-28 22:45:00,078 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-06-28 22:45:00,078 INFO  c.c.d.collector.CollectorTask - https://~~~~~~~~~~.com/
2017-06-28 22:45:00,078 INFO  c.c.d.collector.CollectorTask - -----------------------------------**

I have debuged this issue, when it get the job number, it hangs, getInstanceJobs(~~) --> getJobsCount(~~)-->makeRestCall(~~) -->rest.exchange(thisuri, HttpMethod.GET,
                    new HttpEntity<>(createHeaders(userInfo)),
                    String.class);

I don't know why because I have imported the SSL certificate, and there is no any info printed.

**Comment by nireeshT** [comment]
@wdquan1985  - set your log level to debug and share Jenkins build collector log

**Comment by wdquan1985** [comment]
@nireeshT , I have fixed this issue, the root cause is the proxy has not been configured, I add my proxy in the RestOperationsSupplier.java file.
public class RestOperationsSupplier implements Supplier<RestOperations> {
    @Override
    public RestOperations get() {
    	//bruce, add the proxy.
        SimpleClientHttpRequestFactory requestFactory = new SimpleClientHttpRequestFactory();
        Proxy proxy= new Proxy(Type.HTTP, new InetSocketAddress("my proxy", 8000));
        requestFactory.setProxy(proxy);
        return new RestTemplate(requestFactory);
    }
}

But why the RestTemplate don't print any info? It's difficult to find the root cause.
Is there any other way to configure the proxy? When I change the proxy, the above is a bad way.

**Comment by wdquan1985** [comment]
I have added one new property "jenkins.proxy" in the application.properties file, and changed the corresponding java code.

**Comment by wdquan1985** [comment]
@nireeshT , show we add this improvement in the master branch?

**Comment by wdquan1985** [comment]
I have made the following change.
1.Change the HudsonSettings.java file
Add a new property
        _private String proxy;
	public String getProxy() {
		return proxy;
	}

	public void setProxy(String proxy) {
		this.proxy = proxy;
	}_
2.Change the properties file.
Add a new propery "jenkins.proxy".
2.Change the RestOperationsSupplier.java file.
Add the proxy when create RestTemplate object if proxy has been configured.
_import java.net.InetSocketAddress;
import java.net.Proxy;
import java.net.Proxy.Type;
import com.capitalone.dashboard.util.Supplier;
import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.client.SimpleClientHttpRequestFactory;
import org.springframework.stereotype.Component;
import org.springframework.web.client.RestOperations;
import org.springframework.web.client.RestTemplate;

/**
 * Supplier that returns an instance of RestOperations
 */
@Component
public class RestOperationsSupplier implements Supplier<RestOperations> {
	
	private final HudsonSettings settings;
	
    @Autowired
    public RestOperationsSupplier(HudsonSettings settings) {
        this.settings = settings;
    }
    
    @Override
    public RestOperations get() {
        if (StringUtils.isNotEmpty(this.settings.getProxy())) {
        	String proxy = this.settings.getProxy();
        	String[] proxyArray = proxy.split(":");
        	SimpleClientHttpRequestFactory requestFactory = new SimpleClientHttpRequestFactory();
            
            if (proxy.length() == 1) {
            	requestFactory.setProxy(new Proxy(Type.HTTP, new InetSocketAddress(proxyArray[0], 80)));
			}else {
				requestFactory.setProxy(new Proxy(Type.HTTP, new InetSocketAddress(proxyArray[0], Integer.parseInt(proxyArray[1]))));
			}
            return new RestTemplate(requestFactory);
		}else {
			return new RestTemplate();
		}
    }
}_

**Comment by nireeshT** [comment]
@wdquan1985  Can you submit a PR with this change

**Comment by wdquan1985** [comment]
@nireeshT  I don't know the meaning of PR, the diff patch? 
[patch.zip](https://github.com/capitalone/Hygieia/files/1268931/patch.zip)

I don't know why the change in the application.properties can't be patched, I just add a new propery "jenkins.proxy=" in last part of this file.

**Comment by nitin1706** [comment]
@wdquan1985 : PR is Pull Request. Take a fresh checkout for code, make changes on that code base and submit a PR, it would be merged into code after passing the review.

**Comment by wdquan1985** [comment]
@nitin1706 : Thanks, I have submitted the PR https://github.com/capitalone/Hygieia/pull/1746
