### ISSUE TITLE
Not able to install Hygieia

### ISSUE THREAD

**Issue by amrita1-2** [capitalone/Hygieia#1507]
I already have an older version of Hygieia installled on my machine but since there are new updates which came in i tried to install a new version of Hygieia by checking it out from the GIT repo. but it is giving me the below error:

-bash-4.2$ **mvn clean install package**
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'parent.relativePath' of POM org.jenkins-ci.plugins:hygieia-publisher:2.0.5-SNAPSHOT (/opt/Hygieia/hygieia-jenkins-plugin/pom.xml) points at com.capitalone.dashboard:Hygieia instead of org.jenkins-ci.plugins:plugin, please verify your project structure @ line 15, column 13
[FATAL] Non-parseable POM /home/hygieia/.m2/repository/org/jenkins-ci/plugins/plugin/1.609.2/plugin-1.609.2.pom: Expected root element 'project' but found 'html' (position: START_TAG seen ...CTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">\n<html>... @2:7)  @ /home/hygieia/.m2/repository/org/jenkins-ci/plugins/plugin/1.609.2/plugin-1.609.2.pom, line 2, column 7
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead. @
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.jenkins-ci.plugins:hygieia-publisher:2.0.5-SNAPSHOT (/opt/Hygieia/hygieia-jenkins-plugin/pom.xml) has 1 error
[ERROR]     Non-parseable POM /home/hygieia/.m2/repository/org/jenkins-ci/plugins/plugin/1.609.2/plugin-1.609.2.pom: Expected root element 'project' but found 'html' (position: START_TAG seen ...CTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">\n<html>... @2:7)  @ /home/hygieia/.m2/repository/org/jenkins-ci/plugins/plugin/1.609.2/plugin-1.609.2.pom, line 2, column 7 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException
-bash-4.2$ Write failed: Connection reset by peer

Can any one please have a look at the error and let me know what needs to be done.

**Comment by nireeshT** [comment]
@amrita1-2  - clear home/hygieia/.m2/repository and do mvn clean install. It should bring back all dependencies.

**Comment by Sbrenthughes** [comment]
@amrita1-2  Please reopen if you are still experiencing this issues.

**Comment by sandipkarande** [comment]
I am getting similar kind of errors. Please suggest how to fix it. Will really appreciate quick response and help. Thanks
