### ISSUE TITLE
Hygieia Jenkins plugin - deploy data not published

### ISSUE THREAD

**Issue by srajendaran** [capitalone/Hygieia#1508]
Following are my jenkins plugin setup

![image](https://user-images.githubusercontent.com/14999950/27701828-bd60d400-5cc7-11e7-855a-02bf7e722233.png)

![image](https://user-images.githubusercontent.com/14999950/27701836-c90e1b96-5cc7-11e7-8d8f-24ffb670de11.png)

and the jenkins output says 
"Hygieia: Published Build Complete Data. Response Code: 201. Response Value= 59553541507093275c054169"

my database do not have data in environment_components

also when I went into Hygieia dashboard pipeline widget, I do not see any environemtn in the drop down

Any help in this regards will be much appreciated,

**Comment by srajendaran** [comment]
still not working. Any help would be much appreciated

**Comment by nireeshT** [comment]
@srajendaran  - artifact information and deployment results should have same values. I see different values for Artifact file name pattern and Artifact group.

**Comment by Sbrenthughes** [comment]
@srajendaran it looks like your Hygieia Server Url Port looks incorrect. 3000 is the port for the UI.

**Comment by sanchitacool** [comment]
How to create bar chart for issues in hygieia

**Comment by Sbrenthughes** [comment]
@srajendaran reopen if you are still facing issues.
