### ISSUE TITLE
Add a springboot application in Hygieia

### ISSUE THREAD

**Issue by golokeshpatra45** [capitalone/Hygieia#1509]
I have made a microservice using spring boot .
Now I want to run this spring boot application with Hygieia. 
How should i do it ?
(As of now, I am specifying server.port = in the properties file. So first I see on what port is Hygieia running, then specify the port and then run the sprinf boot application. )
how to connect this spring boot application with hygieia ?

**Comment by satishc1** [comment]
@golokeshpatra45 You should have your microservice write to the mongo database and read the data from hygieia's UI after modifying it.
