### ISSUE TITLE
Maven build breaks on master branch

### ISSUE THREAD

**Issue by roller1187** [capitalone/Hygieia#151]
It breaks here:

[ERROR] /home/jenkins/workspace/hygieia-api/api/src/main/java/com/capitalone/dashboard/service/AuthenticationServiceImpl.java:[81,52] error: cannot find symbol

This is line 81, and the method it's referring to is checkPassword:

        if (authentication != null && authentication.checkPassword(password)) {

**Comment by jdamick** [comment]
It looks like your common / core jar is old..make you mvn install it ..

**Comment by roller1187** [comment]
I'm using whatever you guys have listed in your build instructions to build this code which is a Maven project that Jenkins is building using:

package -pl UI docker:build

I'm not sure how I can be using an old common/core jar when I'm blowing away the Jenkins slave after each time a build runs. Is it possible that the POM.xml is out of date?

**Comment by jdamick** [comment]
i just fixed the issue on the master branch, maybe that was giving you trouble.. You may want to try from the latest code.

**Comment by joshku** [comment]
I am also having issues when I do a maven install. I created a brand new VM and installed the latest java jdk before running the maven install command

**Comment by jdamick** [comment]
closing issue - if it reoccurs please reopen
