### ISSUE TITLE
Getting warning when doing mvn clean and mvn clean install

### ISSUE THREAD

**Issue by seshudanda27** [capitalone/Hygieia#1511]
Hi 
I am getting following exception at the time of mvn install.
I am installing in centOS 6.6 version
JAVA - java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)

[WARNING] The POM for org.jenkins-ci.tools:maven-hpi-plugin:jar:1.106 is missing                                                                                        , no dependency information available
[WARNING] Failed to build parent project for org.jenkins-ci.plugins:hygieia-publ                                                                                        isher:hpi:2.0.5-SNAPSHOT
[WARNING]
[WARNING] Some problems were encountered while building the effective model for                                                                                         com.capitalone.dashboard:api:jar:2.0.5-SNAPSHOT
[WARNING] The expression ${version} is deprecated. Please use ${project.version}   
[log_1.txt](https://github.com/capitalone/Hygieia/files/1116896/log_1.txt)

**Comment by seshudanda27** [comment]
Added mvn packages log

[Mvn_packages.txt](https://github.com/capitalone/Hygieia/files/1116904/Mvn_packages.txt)

**Comment by nireeshT** [comment]
@seshudanda27  - do mvn clean install

**Comment by Sbrenthughes** [comment]
@seshudanda27  please reopen if you are still having issues.
