### ISSUE TITLE
issues in jenkins collector

### ISSUE THREAD

**Issue by vimalkrish** [capitalone/Hygieia#1514]
issue 1. when i stop and start the api and ui, after that when i click login button in UI, it is not showing me the signup page, instead of that it is showing Api connectivity with green tick mark.
i have attached the screen shot of it. please let me know how to fix it
<img width="1029" alt="screen shot 2017-06-27 at 1 04 24 pm" src="https://user-images.githubusercontent.com/18135787/27819388-a0409790-60b7-11e7-8688-e55aedf51830.png">

issue 2. In Jenkins widget, how to view the job metrics in graph format, how to choose the particular date, example if i want to see the metrics for a particular date (From date DD/MM - To date DD/MM)

**Comment by mdinuth** [comment]
Issue 1 : Clear browser cache or try in incognito/private browsing.

**Comment by Sbrenthughes** [comment]
@vimalkrish have you updated to the more recent code base?

**Comment by vimalkrish** [comment]
@Sbrenthughes I pulled the latest code last week

**Comment by doraemon0011** [comment]
@vimalkrish  - 
1) Clear browser cache or use incognito
2) Jenkins widget is configured to show metrics for last 15 days. No ways to configure date range through UI, instead set it programmatically in code.

**Comment by nireeshT** [comment]
@vimalkrish - reopen if issue is not resolved

**Comment by shubhamk0305** [comment]
Hi team,


Currently i am using Hygieia 3.0.2 version

I have configured the dashboard and configured the Jenkins widget and SVN widget in dashboard.
i can see count of data there,but not getting graph visual.


![Dashboard](https://user-images.githubusercontent.com/50317418/64677418-914e9d80-d488-11e9-9467-e69adc277360.PNG)

Thank You in advance
