### ISSUE TITLE
GitLab Failed to retrieve data

### ISSUE THREAD

**Issue by mdinuth** [capitalone/Hygieia#1516]
I'm receiving following error in GitLab collector when it is trying to fetch data from enterprise private GitLab repo.

> 2017-07-05 13:43:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Gitlab
> 2017-07-05 13:43:00,003 INFO  c.c.d.collector.CollectorTask - -----------------------------------
> 2017-07-05 13:43:00,003 INFO  c.c.d.collector.CollectorTask - Starting...
> 2017-07-05 13:43:00,003 INFO  c.c.d.collector.CollectorTask - -----------------------------------
> 2017-07-05 13:43:00,295 INFO  c.c.d.c.GitlabGitCollectorTask - Failed to retrieve data, the repo or collector is most likey misconfigured: https://git.xxxxxxx.com/xxx/xxx.git, 404 Not Found
> 2017-07-05 13:43:00,295 INFO  c.c.d.collector.CollectorTask - Repo Count              1        0s
> 2017-07-05 13:43:00,295 INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
> 2017-07-05 13:43:00,295 INFO  c.c.d.collector.CollectorTask - Finished                         0s

GitLab collector configurations are as below.

> dbname=dashboarddb
> dbhost=localhost
> dbport=27017
> dbreplicaset=false
> dbhostport=localhost:27017,127.0.0.1:27017,ip-172-31-26-184:27017
> dbusername=dashboarduser
> dbpassword=xxxxx
> logging.file=./logs/gitlab.log
> gitlab.cron=0 0/1 * * * *
> gitlab.host=git.xxxxxxx.com
> gitlab.protocol=https
> gitlab.port=443
> gitlab.selfSignedCertificate=false
> gitlab.apiToken=xxxxxxxxxxxxxxxxxxxx
> gitlab.commitThresholdDays=15

Provided GitLab urls and api tokens are correct. I tried with gitlab.selfSignedCertificate=true also, but no luck. Please help me to fix this.

**Comment by rob-miller-777** [comment]
Does the api token your providing have access to that repo?

**Comment by mdinuth** [comment]
Yes. API token is correct. I verified the token by taking a git pull as below.

> git clone https://gitlab-ci-token:<tokenxxx>@git.xxxxxxx.com/xxx/xxx.git

**Comment by rob-miller-777** [comment]
Is the repo nested inside multiple subgroups?

**Comment by mdinuth** [comment]
It is under xxx group. Not inside subgroups.

**Comment by mdinuth** [comment]
Found the route course to this issue. This is not a problem with Hygieia. The issue is with the GitLab configurations. 

To get commits from configured GitLab account, Hygieia GitLab collector calls https://git.company.com/api/v3/projects/namespace%2Fprojectname/repository/commits/?ref_name=branch&since=date&per_page=100. But to use namespace/projectname (with URL encoding it would be namespace%2Fprojectname) in the API call, GitLab Apache should be configured with **AllowEncodedSlashes NoDecode** to ensure that encoded slashes are not decoded but left in their encoded state. 
Ref: https://gitlab.com/gitlab-org/gitlab-recipes/commit/73abde7501b6cd128ce22ea9f82dc19fdc867c80

But when you are using an enterprise GitLab without no access to change GitLab server configurations, what would be the solution?
A simple hack would be, 
> get the GitLab project id and when configuring GitLab widget in Hygieia, provide the repo URL as https://git.xxxxxx.com/projectid.git.

**Comment by rob-miller-777** [comment]
Ah, haven't seen anyone with that issue before.  To make this work you would need to change a few things to allow either a project id, or namespace and project name.  One of the things I would like to change in the future is make the configuration more specific to what it's collecting from.  For github and gitlab, there is no need to put in the entire url, all you really need is the namespace and project, or the project id.  I imagine we request the url because that's what you would need for SVN, but it isn't a great user experience for git repos.

**Comment by jyotimittal01** [comment]
I am running into a similar issue https://github.com/capitalone/Hygieia/issues/2311 and this hack didnt work-

get the GitLab project id and when configuring GitLab widget in Hygieia, provide the repo URL as https://git.xxxxxx.com/projectid.git.

Please help
