### ISSUE TITLE
Sonar version 6.1 does not support /api/project_analyses/ but collector calls for it

### ISSUE THREAD

**Issue by LukeOfWales** [capitalone/Hygieia#1517]
Collector is configured to pull projects from a Sonar server running v6.1 - so this was specified in the properties file - also using the correct sonar.metrics line (for 5.4 & above).
The following was output when this was used:
![image](https://user-images.githubusercontent.com/6364902/27860954-b363b31a-6176-11e7-8238-f993ca8ac813.png)
Throwing a 404 looking for: 
http://{SonarServer}:9000/sonarqube/api/project_analyses/search?project={ProjectName}

After researching, I found that project_analyses is not used unti v6.3 - https://next.sonarqube.com/sonarqube/web_api/api/project_analyses

The version of Sonar I am using is 6.1 however, when I change to <6 in the properties file - the collector works as expected: 
![image](https://user-images.githubusercontent.com/6364902/27861130-65d06ab6-6177-11e7-9c74-237887f78855.png)

Is it possible to investigate this issue? 
As currently I am using what appears to be a pre v6 configuration on v6.1.
```
Hygieia version: 2.0.5
Sonar version: 6.1
```

Thanks

**Comment by pteichner** [comment]
```
Hygieia version: 2.0.5
Sonar version: 6.1
```

**Comment by asg247** [comment]
Tracking this with related issue #1704.
Closing this Issue.
