### ISSUE TITLE
API Build Error

### ISSUE THREAD

**Issue by camillone** [capitalone/Hygieia#153]
ibmadmin@paradigm:~/Hygieia/api$ mvn clean compile install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Building com.capitalone.dashboard:rest-api
[INFO]    task-segment: [clean, compile, install]
[INFO] ------------------------------------------------------------------------
[INFO] [clean:clean {execution: default-clean}]
[INFO] Deleting /home/ibmadmin/Hygieia/api/target
[INFO] Preparing pmd:check
[INFO] [pmd:pmd {execution: pmd}]
[WARNING] Unable to locate Source XRef to link to - DISABLED
[INFO] [pmd:check {execution: default}]
[INFO] 
[INFO] [jacoco:prepare-agent {execution: default}]
[INFO] argLine set to -javaagent:/home/ibmadmin/.m2/repository/org/jacoco/org.jacoco.agent/0.5.8.201207111220/org.jacoco.agent-0.5.8.201207111220-runtime.jar=destfile=/home/ibmadmin/Hygieia/api/target/jacoco.exec
[INFO] [resources:resources {execution: default-resources}]
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 1 resource
[INFO] [compiler:compile {execution: default-compile}]
[INFO] Compiling 64 source files to /home/ibmadmin/Hygieia/api/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] error: error reading /home/ibmadmin/.m2/repository/org/mongodb/mongo-java-driver/3.0.2/mongo-java-driver-3.0.2.jar; error in opening zip file
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Compilation failure
error: error reading /home/ibmadmin/.m2/repository/org/mongodb/mongo-java-driver/3.0.2/mongo-java-driver-3.0.2.jar; error in opening zip file

[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5 seconds
[INFO] Finished at: Tue Oct 27 10:31:51 EDT 2015
[INFO] Final Memory: 50M/878M
[INFO] -----------------------------------------------------------------------

**Comment by amitmawkin** [comment]
Nick,
Can you clear your .m2 folder and also go on an unrestricted internet connection , looks like running behind proxy is corrupting your build or hindering download of certain artifacts

error: error reading /home/ibmadmin/.m2/repository/org/mongodb/mongo-java-driver/3.0.2/mongo-java-driver-3.0.2.jar; error in opening zip file

**Comment by camillone** [comment]
ran for 90 sec :) "tail" of msgs below:

[INFO] [compiler:compile {execution: default-compile}]
[INFO] Compiling 64 source files to /home/ibmadmin/Hygieia/api/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] error: error reading /home/ibmadmin/.m2/repository/org/mongodb/mongo-java-driver/3.0.2/mongo-java-driver-3.0.2.jar; error in opening zip file
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Compilation failure
error: error reading /home/ibmadmin/.m2/repository/org/mongodb/mongo-java-driver/3.0.2/mongo-java-driver-3.0.2.jar; error in opening zip file

[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1 minute 28 seconds
[INFO] Finished at: Tue Oct 27 11:42:22 EDT 2015
[INFO] Final Memory: 55M/868M
[INFO] ------------------------------------------------------------------

**Comment by camillone** [comment]
I have not installed mongo java driver explicitly

**Comment by camillone** [comment]
Decided to go with Docker instructions, and my build progress is has fewer errors.
