### ISSUE TITLE
API Connectivity Error

### ISSUE THREAD

**Issue by NTDBANNU** [capitalone/Hygieia#1530]
**Whitelabel Error Page**

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Jul 12 20:13:10 PDT 2017
There was an unexpected error (type=Not Found, status=404).
No message available

**Comment by Sbrenthughes** [comment]
Can you post the stacktrace from API? In what order are you starting the DB/API/UI?

**Comment by satishc1** [comment]
@NTDBANNU Append /ping to the url that gave you the whitelabel error.  If response is true, your api server is running.

**Comment by aishwaryamv123** [comment]
I am facing similar issue, api log says connected to mongodb on port 27017, but localhost:8090/api/ping doesn't return true and give me a whitelabel error message page.
UI says red on api connectivity. It was working well earlier suddenly it isnt working, Can someone please help me with this/if any faced same ??
