### ISSUE TITLE
Product Dashboard broken

### ISSUE THREAD

**Issue by brajesheee** [capitalone/Hygieia#1539]
I installed the Hygieia using docker-compose cmd. API and UI is up but the Product Dashboard is broken in both chrome and opera browser

![image](https://user-images.githubusercontent.com/26609191/28290854-a73a76be-6b0d-11e7-9b46-89f0e9cd2905.png)

**Comment by nireeshT** [comment]
@brajesheee  rebase to latest code base, clear cache and reload. You can use incognito instead.

**Comment by brajesheee** [comment]
Just cleaned up all dockers and did the fresh install.. Now I do not see any home page .. it blank 

![image](https://user-images.githubusercontent.com/26609191/28486679-22f29a4a-6e4a-11e7-8a63-bc2ce1734831.png)

**Comment by brajesheee** [comment]
Its due to access issue.. Its working fine now.. Closing it.
