### ISSUE TITLE
Unable to run the maven integration test in the UI folder

### ISSUE THREAD

**Issue by joshku** [capitalone/Hygieia#154]
When running the command mvn clean package integration-test I get the following errors

Running 'gulp.js build --no-color' in /home/ibmadmin/Hygieia/UI
[ERROR] module.js:338
[ERROR]     throw err;
[ERROR]     ^
[ERROR] Error: Cannot find module 'mout/lang'
[ERROR]     at Function.Module._resolveFilename (module.js:336:15)
[ERROR]     at Function.Module._load (module.js:278:25)
[ERROR]     at Module.require (module.js:365:17)
[ERROR]     at require (module.js:384:17)
[ERROR]     at Object.<anonymous> (/home/ibmadmin/Hygieia/UI/node_modules/wiredep/node_modules/bower-config/lib/Config.js:1:74)
[ERROR]     at Module._compile (module.js:460:26)
[ERROR]     at Object.Module._extensions..js (module.js:478:10)
[ERROR]     at Module.load (module.js:355:32)
[ERROR]     at Function.Module._load (module.js:310:12)
[ERROR]     at Module.require (module.js:365:17)
[ERROR]     at require (module.js:384:17)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:53 min
[INFO] Finished at: 2015-10-28T23:51:02-04:00
[INFO] Final Memory: 17M/154M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.25:gulp (gulp build) on project UI: Failed to run task: 'gulp.js build --no-color' failed. (error code 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by tabladrum** [comment]
@joshku Can we close this issue?

**Comment by joshku** [comment]
Yes sure I will close this issue.

**Comment by saad-tariq-confiz** [comment]
how did you solve this issue?
