### ISSUE TITLE
Up-to-date DockeHub images

### ISSUE THREAD

**Issue by tsutsarin-fuib** [capitalone/Hygieia#1540]
Please, provide up-to-date and possibly automated builds of Docker images on DockerHub.

**Comment by xiaods** [comment]
we can use docker cloud to build update image.

**Comment by matthewbeasley** [comment]
@tsutsarin-fuib - automated pushes to Docker Hub will come in the near future. For now just run `mvn clean install docker:build` in the project root and you will get the latest images.
