### ISSUE TITLE
Chatops widget not populating any messages

### ISSUE THREAD

**Issue by vishwakhrushi** [capitalone/Hygieia#1543]
My chatops widget is blank and not populating any messages. I used api token with view message scope. It used to work before it stopped working ever since i upgraded to latest source code.

![image](https://user-images.githubusercontent.com/17056369/28328655-35be057a-6bb5-11e7-87c7-af9fb00b1a54.png)

**Comment by mshaw2** [comment]
I am also getting the same issue, did you get this resolved?
Please share the fix, we are stuck from past 2 days

**Comment by samyzemmouri** [comment]
do you manage to make it  work ?
