### ISSUE TITLE
Hygieia Jenkins Plugin configuration failes 

### ISSUE THREAD

**Issue by bseelam-hub** [capitalone/Hygieia#1544]
I have built the Hygieia Jenkins Plugin and when trying to configure in Jenkins>configure system it is getting failed . 

![image](https://user-images.githubusercontent.com/26402613/28370407-d98c71de-6cb7-11e7-8d23-3f9df86e1eb7.png)

**Comment by satishc1** [comment]
@bseelam-hub Port looks wrong. Default for api is 8080, unless you changed it to 3000

**Comment by bseelam-hub** [comment]
Hi satish

Thanks for replying .

i am talking about Hygieia UI Port i.e., 3000
Not the api port 8080

Thanks

Thanks and Regards
Brahma

**Comment by satishc1** [comment]
@bseelam-hub The jenkins plugin talks to the api .. and not the ui.  You have misconfigured the jenkins plugin to talk to the UI port. Change it to 8080 (or whatever port your api is running on)
