### ISSUE TITLE
Change the Port to other than 3000

### ISSUE THREAD

**Issue by bseelam-hub** [capitalone/Hygieia#1545]
Hi I want to run the Hygieia from different port other than 3000

**Comment by Sbrenthughes** [comment]
https://github.com/capitalone/Hygieia/pull/1532. try looking through this.

**Comment by bseelam-hub** [comment]
Hi I want to change the port from 3000 which is UI Port . Where do i change that ?

**Comment by satishc1** [comment]
@bseelam-hub https://github.com/capitalone/Hygieia/issues/1127

**Comment by mikequentel** [comment]
Perhaps in `gulfile.js` change this to specify port (eg `9999`)--I have not tried this, personally:
```
browserSync.init({
          port: 9999,
          server: {
              baseDir: hygieia.dist,
              startPath: '/',
              middleware: [proxyMiddleware]
          },
          ghostMode: ghostMode
      });
```
Got this tip from https://stackoverflow.com/questions/36950379/browser-sync-serve-command-with-different-port

**Comment by bseelam-hub** [comment]
My gulpfile.js looks like this after change . 

 browserSync.init({
          port: 8443,
          server: {
              baseDir: hygieia.dist,
              startPath: '/',
              middleware: [proxyMiddleware]
          },
          ghostMode: ghostMode
      });

and started the command with sudo gulp serve 
Still it is serving on default port 3000 .  

Any Help ?

**Comment by nireeshT** [comment]
@bseelam-hub  try 4000, clear browser cache and cookies or use incognito to launch UI. use gulp serve

**Comment by bseelam-hub** [comment]
Hey thanks it started working after I restarted the API service as well . Thanks very much
