### ISSUE TITLE
Hi, We are trying to run maven clean istall command but it is giving the bellow error.We have  taken the code base from this link "https://github.com/vvigreen981/Hygieia"

### ISSUE THREAD

**Issue by sai1408** [capitalone/Hygieia#1548]
C:\temp\Open Source Hygieia (Latest)\Hygieia-master>mvn clean install package
[INFO] Scanning for projects...
Downloading: http://repo.jenkins-ci.org/public/org/jenkins-ci/plugins/plugin/1.567/plugin-1.567.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'parent.relativePath' of POM org.jenkins-ci.plugins:hygieia-publisher:2.0.5-SNAPSHOT (C:\temp\Open Source Hygieia (Latest)\Hygieia-master\hygieia-jenkins-plugin\pom.xml) points at com.capitalone.dashboard:Hygieia instead of org.jenkins-ci.plugins:plugin, please verify your project structure @ line 15, column 13
[FATAL] Non-resolvable parent POM for org.jenkins-ci.plugins:hygieia-publisher:2.0.5-SNAPSHOT: Could not transfer artifact org.jenkins-ci.plugins:plugin:pom:1.567 from/to repo.jenkins-ci.org (http://repo.jenkins-ci.org/public/): Connect to repo.jenkins-ci.org:80 [repo.jenkins-ci.org/130.211.20.35] failed: Connection timed out: connect and 'parent.relativePath' points at wrong local POM @ line 15, column 13
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead. @
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.jenkins-ci.plugins:hygieia-publisher:2.0.5-SNAPSHOT (C:\temp\Open Source Hygieia (Latest)\Hygieia-master\hygieia-jenkins-plugin\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.jenkins-ci.plugins:hygieia-publisher:2.0.5-SNAPSHOT: Could not transfer artifact org.jenkins-ci.plugins:plugin:pom:1.567 from/to repo.jenkins-ci.org (http://repo.jenkins-ci.org/public/): Connect to repo.jenkins-ci.org:80 [repo.jenkins-ci.org/130.211.20.35] failed: Connection timed out: connect and 'parent.relativePath' points at wrong local POM @ line 15, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

C:\temp\Open Source Hygieia (Latest)\Hygieia-master>mvn clean install
[INFO] Scanning for projects...
Downloading: http://repo.jenkins-ci.org/public/org/jenkins-ci/jenkins/1.33/jenkins-1.33.pom
Downloading: https://repo.maven.apache.org/maven2/org/jenkins-ci/jenkins/1.33/jenkins-1.33.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'parent.relativePath' of POM org.jenkins-ci.plugins:hygieia-publisher:2.0.5-SNAPSHOT (C:\temp\Open Source Hygieia (Latest)\Hygieia-master\hygieia-jenkins-plugin\pom.xml) points at com.capitalone.dashboard:Hygieia instead of org.jenkins-ci.plugins:plugin, please verify your project structure @ line 15, column 13
[FATAL] Non-resolvable parent POM for org.jenkins-ci.plugins:plugin:1.567: Could not transfer artifact org.jenkins-ci:jenkins:pom:1.33 from/to repo.jenkins-ci.org (http://repo.jenkins-ci.org/public/): Connect to repo.jenkins-ci.org:80 [repo.jenkins-ci.org/130.211.20.35] failed: Connection timed out: connect @ org.jenkins-ci.plugins:plugin:1.567, C:\Users\n096451\.m2\repository\org\jenkins-ci\plugins\plugin\1.567\plugin-1.567.pom, line 4, column 11
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead. @

**Comment by DeepakYadav17** [comment]
It looks like you do not have connectivity to  http://repo.jenkins-ci.org/public and hence the required artifacts are not getting downloaded.

**Comment by nireeshT** [comment]
@sai1408  - Clean your .m2/repository and run mvn clean install. We recommend to get latest code form capitalone/master instead.

**Comment by Sbrenthughes** [comment]
@sai1408  please reopen if you have any more issues
