### ISSUE TITLE
Unable to encrypt passwords with special characters '$', while configuring Code Repo Dashboard

### ISSUE THREAD

**Issue by kumarvarun1252** [capitalone/Hygieia#1549]
I am trying to setup Code Repo Widget for GitHub. I get "Error encrypting password" when I use a special character $ in password field.

Steps:
Open "Configure Code Repo Widget"
Enter valid information
Enter a password with $ and Save

Actual Result:
'Error encrypting password' is being displayed

Expected Result:
All special characters should be allowed in password field and should be encrypted successfully

**Comment by Ragavendira1** [comment]
@kumarvarun1252

pls help me how to set up password encryption and decryption for private repo and where i need to setup in application.properties, etc. kindly share detailed steps.

regards,
ragav

**Comment by golokeshpatra45** [comment]
@kumarvarun1252 
No worries ,
Go to Hygieia-Master -> UI and open README.md.
Scroll to the end and you will get, Encryption for private repos

Now generate this key and add it to the properties file of both api and github i.e
Hygieia-master -> api -> target -> (properties file) -> key = (new generated private key )
Hygieia-master -> collectors ->scm -> github -> target -> open your properties file ->github.key = (new generated private key )

This key will help you encrypt & decrypt your credentials .

Now run api then gulp serve then collectors.

If You Are Using GHE - (Enterprise Github)
**ask your IT to provide you with username and password to bypass the enterprise (GHE) login. GHE logins are different as compared to that of normal github logins as you enter your Windows login or LDAP or (many options). if you dont have such login then your collector should perform properly.

I had previously been unsuccessful in getting GHE populating my dashboard but now I have figured out. Hope you have got everything, any doubts do ask me .

**Comment by kumarvarun1252** [comment]
@golokeshpatra45 thanks for the information. I don't see the error after setting up the encryption.

I guess the error message displayed "Error encrypting password" should be modified to something more descriptive and informative.
