### ISSUE TITLE
Can't seem to get test data to load.

### ISSUE THREAD

**Issue by htvan1** [capitalone/Hygieia#1554]
I first want to demo this to the team and then write a custom collector for our deploy manager. 

Guide seemed easy enough. 
MongoDB set up and user set up
API starts just fine though not hooked up to anything besides the mongo instance
UI layer set up
   I run with:    gulp serve --local true 
   Starts just fine, but no data anywhere. Everything is blank, search on the dashboards does nothing, and all the tabs do not have any data.   The log in doesn't work (not surprised as no ldap added).  API light is green but as I understand it, it should just be napping all the default test data.

Any pointers on what I am doing wrong would be much appreciated = ]

**Comment by nireeshT** [comment]
@htvan1  - start collectors (github,jenkins,jira,Sonar,.etc) to get data populated to mongo and to UI. You should be able to do standard login by adding below property in your api properties
auth.authenticationProviders=STANDARD
In standard login, you can signup and create users.

**Comment by htvan1** [comment]
Thanks, that definitely helped, I can log in and create empty boards.  I spun up a docker jira instance to connect to, so I could watch the data being pulled in.  After some set backs I got stuck on the team field... We are not using the Temp plug in.  I tried to make my own custom field one, and I get java.io.FileNotFoundException: http://localhost:[]/rest/tempo-teams/1/team  Any thoughts on that?
