### ISSUE TITLE
Understanding pushed and enabled in the collector_items table

### ISSUE THREAD

**Issue by Satheesh-b** [capitalone/Hygieia#1556]
What is the different between pushed and enabled in the collector_items table?

As far as I have seen, enabled true means those collector_items are configured in some dashboard.

But pushed also gives the same meaning that is being pushed via api. Can you please explain? @nireeshT @tabladrum @satishc1

**Comment by Satheesh-b** [comment]
Hi, Can anyone please clarify me about this two terms? @MarkRx @nireeshT

**Comment by satishc1** [comment]
@Satheesh-b 
enabled = added to a dashboard via component and is being collected
pushed = {true = pushed from jenkins hygieia plugin,
                 false = pulled by hygieia collector}

**Comment by Satheesh-b** [comment]
@satishc1 thank you.
