### ISSUE TITLE
error while running API "JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted."

### ISSUE THREAD

**Issue by kpal12** [capitalone/Hygieia#1564]
Hi Team , 

Can some one please help me getting the isssue resovled, I have tried everything which was suggested in old issue ticket created for the same , but still geeting the issue. The api says connected but i am geeting this error.

The set up was working fine and suddenly this issue cropped up. Please help in resloving this issue

**Comment by kpal12** [comment]
@tabladrum @satishc1  please help

**Comment by Sbrenthughes** [comment]
try - https://github.com/capitalone/Hygieia/issues/1518

**Comment by kpal12** [comment]
@Sbrenthughes  
Thanks a lot for helping me here. I got the cookies cleared and it works fine after that.

**Comment by Sbrenthughes** [comment]
@kpal12 No problem!

**Comment by sundeepk1** [comment]
cleaning of cookies is not working for me .. any suggestions

**Comment by Sbrenthughes** [comment]
Can you reach out via gitter? This issue has been closed.
