### ISSUE TITLE
LDAP authentication not working

### ISSUE THREAD

**Issue by edsyoo** [capitalone/Hygieia#1566]
I'm not sure if this the correct forum, but I figured I'd start here.

```
auth.authenticationProviders=LDAP,STANDARD
auth.ldapServerUrl=ldaps://company.com:636/
auth.ldapUserDnPattern=uid={0},c=us,ou=Users,o=company.com
```

The `uid` value is actually a serial number for the employee rather than the email address.  When using the serial number (instead of email) to try to login to the UI, I get the following error:

```
message=[LDAP: error code 53 - Unwilling To Perform]; nested exception is javax.naming.OperationNotSupportedException: [LDAP: error code 53 - Unwilling To Perform]; 
```

There is a `mail` value which is the email address, but using that in the `auth.ldapUserDnPattern` yields a different `cant' authenticate` error.

I've verified, using `ldapsearch`, that the `dn:` value should be something like the following:
`dn: uid=serial,c=us,ou=Users,o=company.com`

But I'm a bit lost as to if this would be able to work with the current code to authenticate using ldap authentication.

**Comment by nitin1706** [comment]
refer #1731
