### ISSUE TITLE
Delete dashboard should ask for confirmation

### ISSUE THREAD

**Issue by kumarvarun1252** [capitalone/Hygieia#1568]
Right now deleting a dashboard does not ask for a confirmation. It would be really helpful if there is a confirmation for delete dashboard. I accidentally clicked on the delete button and I couldn't get the dashboard back.

**Comment by nitin1706** [comment]
Good point, will have a look and put it to fix.

**Comment by nitin1706** [comment]
PR #1608

**Comment by nitin1706** [comment]
@Sbrenthughes : can you close this issue

**Comment by nitin1706** [comment]
@Sbrenthughes :  we can close this issue
