### ISSUE TITLE
Other Forms of Git

### ISSUE THREAD

**Issue by racorretjer** [capitalone/Hygieia#157]
If I wanted to use other frontends for git (say bitbucket, gforge, etc.), could I use your github collector plugin as-is, do I need to make a plugin for each of them based off yours, or just one for all of them?

**Comment by tabladrum** [comment]
I am not familiar with bitbucket api's. I am guessing that they will be similar but not exactly the same. I would just copy the github collector and make a "bitbucket" collector etc. Let me know if you run into any difficulty.

**Comment by tabladrum** [comment]
@racorretjer any updated on this? Have you created any bitbucket or such collectors?

**Comment by smsuresh** [comment]
Can we use "github" for  plain git installation on linux as well?!

**Comment by jimzucker** [comment]
Any git repo should work, are you getting an error?

**Comment by smsuresh** [comment]
No Error, but no reflection in dashboard either,  Infact When i click "save" the button looks irresponsive..
Tried many restarts as well.
Can you provide a sample URL for "plain git repo under a linux box"

**Comment by mrh666** [comment]
@jimzucker , I want to use git collector with Gitlab. Is there is any way to provide credentials (user/pass or key) for Gitlab?

**Comment by kramos** [comment]
We're also considering Gerrit.  /cc SachinKSingh28

@jimzucker did you get Gitlab working?

**Comment by tabladrum** [comment]
@kramos take a look at this branch: https://github.com/capitalone/Hygieia/tree/gerrit-integration
gerrit integration is in the works. Someone was testing it out. It has some limitations..

**Comment by jimzucker** [comment]
No, Ive only used it with github

Sent from my iPhone

On Jul 6, 2016, at 13:20, Markos <notifications@github.com<mailto:notifications@github.com>> wrote:


We're also considering Gerrit. /cc SachinKSingh28

@jimzucker<https://github.com/jimzucker> did you get Gitlab working?

-

**Comment by satishc1** [comment]
Closed. github, bitbucket public and private repos are supported. For other specific SCMs you'll need to create a collector.
