### ISSUE TITLE
JWT Token expiration time extension.

### ISSUE THREAD

**Issue by Satheesh-b** [capitalone/Hygieia#1575]
Hi,

As far now, the application logs out as per the expiration time specified in the application.properties.

Is there any possibility that the token expiration is extended or refreshed, so that the user is logged out even if he is using the application. We have to extend the expiration time of the token, if the request is given in the last 5 minutes(say). 

Will this be possible? @nireeshT @satishc1

**Comment by satishc1** [comment]
@Satheesh-b Not at the moment. Why not set the expiration time to one day ..instead of trying to extend it.
