### ISSUE TITLE
Sonar data is displaying data in Team Dashboard, but it is not displaying data in Product Dashboard

### ISSUE THREAD

**Issue by abhishekvats007** [capitalone/Hygieia#1579]
![untitled](https://user-images.githubusercontent.com/17519769/28780119-43f1f160-7623-11e7-96c6-76326b2f2afc.jpg)

![image](https://user-images.githubusercontent.com/17519769/28779945-9b0782cc-7622-11e7-99c0-63c0db9b3400.png)

I am using sonar 5.6

**Comment by tabladrum** [comment]
@nireeshT I think the UI graph as some javascript error.

**Comment by abhishekvats007** [comment]
@tabladrum Sonar data is coming. You can close now. Anyways thanks a lot !!
