### ISSUE TITLE
Docker Hygieia API Connectivity Issue 

### ISSUE THREAD

**Issue by NTDBANNU** [capitalone/Hygieia#1582]
I'm trying to use docker compose file but API is unable to connect with MongoDB due to the authentication issue. As anyone encountered the same
<img width="948" alt="dockercompose" src="https://user-images.githubusercontent.com/24846966/28807922-44bb57ee-762d-11e7-8d5d-7d3f84130c25.png">
 problem before.

**Comment by pedrocesar-ti** [comment]
https://github.com/capitalone/Hygieia/issues/999

**Comment by nitin1706** [comment]
@NTDBANNU : are you still seeing this issue?

**Comment by pedrocesar-ti** [comment]
@NTDBANNU I fixed this issue connecting to the MongoDB container and creating the user manually.

**Comment by nitin1706** [comment]
what mongo version are you using. Did you create a DB and switched to that DB on mongo instance to which you are connecting. also, share your properties file.

**Comment by nitin1706** [comment]
@NTDBANNU :   are you still seeing this issue? what mongo version are you using? Did you create a DB and switched to that DB on mongo instance to which you are connecting? also, share your properties file.

**Comment by nitin1706** [comment]
please reopen if this is still an issue
