### ISSUE TITLE
How do I get jwt auth to work for the API

### ISSUE THREAD

**Issue by htvan1** [capitalone/Hygieia#1583]
I was following info I found in: https://github.com/capitalone/Hygieia/issues/975

I want to use http://localhost:8080/api/deploy/
I just tried basic auth with the curl example, I kept getting jwt token malform.... which confused me.  I then tried to make the jwt follow a guide on how to put those together (first time using that type of token).  I am assuming the secret I am to use is whatever I set in dashboard.properties  auth.secret= 
For the second part of the jwt, I think the payload I just put user:myusername
Not sure if anything else was needed...or if that was even needed.

I keep getting "message":"JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted."   not sure what is going wrong.

Thanks.

**Comment by Sbrenthughes** [comment]
Have you tried https://github.com/capitalone/Hygieia/issues/1564

**Comment by Sbrenthughes** [comment]
Have you tried looking at https://github.com/capitalone/Hygieia/blob/gh-pages/pages/hygieia/api/api.md? Near the bottom it explains how to set up the token.

**Comment by Sbrenthughes** [comment]
@htvan1 Please reopen if you have any more issues.
