### ISSUE TITLE
Hygieia having problem with publishing the Unit Test Result using jenkins plugin 

### ISSUE THREAD

**Issue by jhansiabburu** [capitalone/Hygieia#1587]
![jenkins_publish_unit_test_result](https://user-images.githubusercontent.com/13124632/28937307-138998be-7850-11e7-92f8-e1402141ff28.png)

As shown in above screen shot, i configured Hygieia plugin to jenkins job and running and i am getting below error

**Hygieia Test Result Publisher - Looking for file pattern 'index.html' in directory /Users/jenkins/build/GMA-5-ANDROID-UNIT-TEST/app/build/reports/androidTests/connected/flavors/QA
13:00:16 Hygieia Test Publisher: Processing file: /Users/jenkins/build/GMA-5-ANDROID-UNIT-TEST/app/build/reports/androidTests/connected/flavors/QA/index.html
13:00:16 Hygieia Publisher: Error Parsing File: /Users/jenkins/build/GMA-5-ANDROID-UNIT-TEST/app/build/reports/androidTests/connected/flavors/QA/index.html
13:00:16 Hygieia: Published Test Data. Nothing to publish**

So please help me to resolve the issue

**Comment by stevegal** [comment]
My guess is the wrong file type. Junit reports are normally the xml format ones, not the HTML summary pages

**Comment by jhansiabburu** [comment]
if i gave the xml file format it is the same issue and the only way that i can collect the Junit test result is through sonar qube

**Comment by stevegal** [comment]
What were your new settings?

**Comment by jhansiabburu** [comment]
You need to upload the Junit test result to SonarQube server and when you configure the widget for SonarQube analysis in the dashboard, it will automatically show the JUnit test results there

**Comment by nireeshT** [comment]
@jhansiabburu  Can you change your xml file to json and upload to server.

**Comment by rajkumaradass** [comment]
@nireeshT  I have same requirement as described in this issue. If i try xml file to json and push it to hygieia, get below exception.  Could you please confirm if this way is verified earlier or the only option is to use SonarQube?

java.lang.ClassCastException: org.json.simple.JSONObject cannot be cast to org.json.simple.JSONArray
	at hygieia.builder.CucumberTestBuilder.getCapabilities(CucumberTestBuilder.java:101)
	at hygieia.builder.CucumberTestBuilder.buildTestResults(CucumberTestBuilder.java:91)
	at hygieia.builder.CucumberTestBuilder.<init>(CucumberTestBuilder.java:72)
	at jenkins.plugins.hygieia.workflow.HygieiaTestPublishStep$HygieiaArtifactPublishStepExecution.run(HygieiaTestPublishStep.java:199)
	at jenkins.plugins.hygieia.workflow.HygieiaTestPublishStep$HygieiaArtifactPublishStepExecution.run(HygieiaTestPublishStep.java:156)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:290)
