### ISSUE TITLE
GitHub Connector unable to connect to MongoDB

### ISSUE THREAD

**Issue by joshku** [capitalone/Hygieia#159]
I have Hygieia running on a VM and within the VM I used the docker-compose command to bring up the mongo, api and ui containers. They are all linked to each other and I am able to create a user online and to create a dashboard. When I did the `mvn install` within the GitHub collector directory it created a github collector jar file which I used the command `java -jar github-scm-collector-1.0.0.jar --spring.config.name=application` I created an application.properties file that is the same as the sample.properties file that was shown and I edited the file to have the mongodb credentials. When I run the java command I get the following errors:
2015-11-03 15:55:53,780 INFO  org.mongodb.driver.cluster - Exception in monitor thread while connecting to server 127.0.0.1:27017
com.mongodb.MongoSecurityException: Exception authenticating
	at com.mongodb.connection.NativeAuthenticator.authenticate(NativeAuthenticator.java:48) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.connection.InternalStreamConnectionInitializer.authenticateAll(InternalStreamConnectionInitializer.java:99) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.connection.InternalStreamConnectionInitializer.initialize(InternalStreamConnectionInitializer.java:44) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:115) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:127) ~[mongo-java-driver-3.0.2.jar!/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_85]
Caused by: com.mongodb.MongoCommandException: Command failed with error 18: 'auth failed' on server 127.0.0.1:27017. The full response is { "ok" : 0.0, "errmsg" : "auth failed", "code" : 18 }

I am not sure why I am unable to authenticate when I can use the mongo shell and use the exact same credentials and connect to the database. Is there something that I am missing?

**Comment by joshku** [comment]
Attached is my debug log

**Comment by mhedden** [comment]
Hi Josh,

I'm a new user of Hygieia so the recommendation I am about to make is unofficial support. At a quick glance it appears your issue may reside with utilizing --spring.config.name=application instead of --spring.config.name=application.properties. 

Please try using the full name of the properties file (and relative path if necessary).

**Comment by jdamick** [comment]
what version of mongo are you using?

**Comment by joshku** [comment]
I am using version 3.0.7

**Comment by jdamick** [comment]
I'm trying to reproduce the problem but not having any luck..

Couple questions to help me:

what does the log from mongo say? 

what does the user look like?

Login to mongo:
```
use admin
db.system.users.find()
```

It should look something like:
```
{ "_id" : "dashboard.db", "user" : "db", "db" : "dashboard", "credentials" : { "SCRAM-SHA-1" : { 
  "iterationCount" : 10000, "salt" : "xxxx", "storedKey" : "xxxx", "serverKey" : "xxxx" } }, 
  "roles" : [ { "role" : "readWrite", "db" : "dashboard" } ] }
```

**Comment by camillone** [comment]
{ "_id" : "dashboarddb.dashboarduser", "user" : "dashboarduser", "db" : "dashboarddb", "credentials" : { "SCRAM-SHA-1" : { "iterationCount" : 10000, "salt" : "JIb/8IWwhfg25lZSpKJizg==", "storedKey" : "7oMhUQMQUy6z3Jei8QkCiM4R0r0=", "serverKey" : "9oskPkz0AgXrwbRZjRnn9/AJc9o=" } }, "roles" : [ { "role" : "readWrite", "db" : "dashboarddb" } ] }
{ "_id" : "test.dashboarduser", "user" : "dashboarduser", "db" : "test", "credentials" : { "SCRAM-SHA-1" : { "iterationCount" : 10000, "salt" : "a181L4xwhq5K58sMQikMVw==", "storedKey" : "ozoEDITe90mAe6j1OeBsQf6Y3Ig=", "serverKey" : "RVwr9C8bzzghGE4ng7uQLbn72jU=" } }, "roles" : [ { "role" : "readWrite", "db" : "test" } ] }
{ "_id" : "dashboarddb.admin", "user" : "admin", "db" : "dashboarddb", "credentials" : { "SCRAM-SHA-1" : { "iterationCount" : 10000, "salt" : "LwoGMaTcLvfTft2nRncpvQ==", "storedKey" : "kSxA38oVYAGeksua9A495/m0RP0=", "serverKey" : "0tTDwy4P2/9FO20ocVree1fb1gE=" } }, "roles" : [ { "role" : "userAdmin", "db" : "dashboarddb" } ] }

**Comment by camillone** [comment]
Tue Nov  3 17:04:30.380 [Robomongo] SettingsManager initialized in /home/ibmadmin/.config/robomongo/robomongo.json
Tue Nov  3 17:04:30.380 [Robomongo] Settings saved to: /home/ibmadmin/.config/robomongo/robomongo.json
Tue Nov  3 17:05:17.571 [Robomongo] Settings saved to: /home/ibmadmin/.config/robomongo/robomongo.json
Tue Nov  3 17:05:17.572 [Robomongo] Connecting to localhost:27017...
Tue Nov  3 17:05:17.598 ERROR: [Robomongo] connect failed
Tue Nov  3 17:05:17.599 ERROR: [Robomongo] Unable to authorize
Tue Nov  3 17:05:45.714 [Robomongo] Settings saved to: /home/ibmadmin/.config/robomongo/robomongo.json
Tue Nov  3 17:05:45.715 [Robomongo] Connecting to localhost:27017...
Tue Nov  3 17:05:45.744 ERROR: [Robomongo] connect failed
Tue Nov  3 17:05:45.745 ERROR: [Robomongo] Unable to authorize
Tue Nov  3 17:06:29.631 [Robomongo] Settings saved to: /home/ibmadmin/.config/robomongo/robomongo.json
Tue Nov  3 17:06:29.632 [Robomongo] Connecting to 172.17.42.1:27017...
Tue Nov  3 17:06:29.654 ERROR: [Robomongo] connect failed
Tue Nov  3 17:06:29.655 ERROR: [Robomongo] Unable to authorize
Tue Nov  3 17:07:03.547 [Robomongo] Settings saved to: /home/ibmadmin/.config/robomongo/robomongo.json
Tue Nov  3 17:07:03.548 [Robomongo] Connecting to 172.17.42.1:27017...
Tue Nov  3 17:07:03.572 ERROR: [Robomongo] connect failed
Tue Nov  3 17:07:03.573 ERROR: [Robomongo] Unable to authorize
Tue Nov  3 17:09:22.755 [Robomongo] Settings saved to: /home/ibmadmin/.config/robomongo/robomongo.json
Tue Nov  3 17:09:22.756 [Robomongo] Connecting to 172.17.42.1:27017...
Tue Nov  3 17:09:22.779 ERROR: [Robomongo] connect failed
Tue Nov  3 17:09:22.784 ERROR: [Robomongo] Unable to authorize
Tue Nov  3 17:09:51.707 [Robomongo] Settings saved to: /home/ibmadmin/.config/robomongo/robomongo.json
Tue Nov  3 17:09:51.707 [Robomongo] Connecting to 172.17.42.1:27017...
Tue Nov  3 17:09:51.735 file [/home/ibmadmin/.robomongorc.js] doesn't exist
Tue Nov  3 17:10:00.400 [Robomongo] Settings saved to: /home/ibmadmin/.config/robomongo/robomongo.json
Tue Nov  3 17:10:00.400 [Robomongo] Connecting to 172.17.42.1:27017...
Tue Nov  3 17:10:00.425 file [/home/ibmadmin/.robomongorc.js] doesn't exist
Tue Nov  3 17:13:06.554 [Robomongo] Settings saved to: /home/ibmadmin/.config/robomongo/robomongo.json

**Comment by jdamick** [comment]
thanks - one more question, can you post your properties file (redact passwords please)

**Comment by joshku** [comment]
#Database Name
spring.data.mongodb.database=dashboarddb

#Database HostName - default is localhost
spring.data.mongodb.host=127.0.0.1

#Database Port - default is 27017
spring.data.mongodb.port=27017

#Database Username - default is blank
spring.data.mongodb.username=dashboarduser

#Database Password - default is blank
spring.data.mongodb.password=SOMEPASSWORD

#Collector schedule (required)
github.cron=0 0/5 * * * *

github.host=https://github.com/capitalone/Hygieia.git

#Maximum number of days to go back in time when fetching commits
github.commitThresholdDays=15

**Comment by jdamick** [comment]
Ok, i think i see the issue.. at some point the configuration was changed, looks like in pull #99 - so the docs are wrong...

here is my properties file, for example:

```
dbname=dashboard
dbhost=192.168.64.2
#Database Port - default is 27017
dbport=27017

#Database Username - default is blank
dbusername=db
#Database Password - default is blank
dbpassword=dbpass
# github
github.cron=0 0/5 * * * *
github.host=github.com
#Maximum number of days to go back in time when fetching commits
github.commitThresholdDays=15
```

I'd also make sure you mvn install the latest core library..   some of the log messages look like they are from an older version.

we need to change the version in the pom so this is obvious - i'll take that one.

**Comment by joshku** [comment]
I ran all this on a freshly made vm so my maven core libraries should be the latest. Once you push the updates for the versions in pom then I will pull the latest code and try to set everything up again

**Comment by jdamick** [comment]
agreed, thanks

**Comment by jdamick** [comment]
please take a look at the latest master

**Comment by joshku** [comment]
Great thanks a lot. I will pull the latest code and see if I am having issues

**Comment by camillone** [comment]
@jdamick Should I "mvn clean install package" immediately after "git clone <latest master>"?

**Comment by jdamick** [comment]
yes, i would

**Comment by joshku** [comment]
It looks like I am able to successfully connect to mongodb now. Looks like the updates as well as the change to the application.properties file was the way to fix it. I am also wondering if the documentation for the jenkins and UCD collectors are incorrect as well. What are the application.properties files supposed to look for those?

**Comment by jdamick** [comment]
Yup, they all need to be fixed - i'm going to open a new issue for those - thanks for confirming!

**Comment by jimzucker** [comment]
A gentle reminder to fix the README files also.

**Comment by Nandini-RL** [comment]
Is it mandatory to have a database by name 'dashboard' in MongoDB?
In fact once I created a DB called 'dashboard' in MongoDB then it started working. I was able to create the dasboard widgets.

So, the other names like 'dashboardb' or 'dashboarddb' will not work for creating dashboard widgets

So the sample properties files are misleading.

**Comment by joshku** [comment]
So you should really use `dashboarddb` BUT in all honesty you really just need to make sure you stick to one database name. If stick to one database name then you will be able to connect all your collectors and everything to that database and it will work.
