### ISSUE TITLE
How to create bar chart for issues in hygieia

### ISSUE THREAD

**Issue by sanchitacool** [capitalone/Hygieia#1593]

**Comment by sanchitacool** [comment]
Please provide me source code from github

**Comment by Sbrenthughes** [comment]
https://gionkunz.github.io/chartist-js/examples.html#stacked-bar

**Comment by sanchitacool** [comment]
I need to implement Stacked bar chart in Widget Feature, Please provide me code

**Comment by sanchitacool** [comment]
Need to implement Stacked bar chart in Widget Feature on the basis of issues like Done, Accepted. Please provide me code so that i can implement in my widget
