### ISSUE TITLE
BUG: Cannot access test data in UI

### ISSUE THREAD

**Issue by htvan1** [capitalone/Hygieia#1599]
Data does seem to get loaded from what I can tell when watching the calls back and forth. But something gets weird if you try and log in or create a user when using:  gulp serve --local true
Also the documentation does not state what the password is for user created in the test data: someuser

When it tries to authenticate on a log in, the header is missing. response.headers()['x-authentication-token'])  ...in fact no headers are set, the response looks completely different from the one you will see when you do not load with --local true. 
Logging in and creating a new user works fine with one's own data.

TypeError: response.headers is not a function
    at processResponse (authService.js:15)
    at processQueue (bower.js:28357)
    at bower.js:28373
    at Scope.$eval (bower.js:29655)
    at Scope.$digest (bower.js:29469)
    at Scope.$apply (bower.js:29763)
    at done (bower.js:23743)
    at completeRequest (bower.js:23952)
    at XMLHttpRequest.requestLoaded (bower.js:23880)
(anonymous) @ bower.js:25860
(anonymous) @ bower.js:22368
processQueue @ bower.js:28365
(anonymous) @ bower.js:28373
$eval @ bower.js:29655
$digest @ bower.js:29469
$apply @ bower.js:29763
done @ bower.js:23743
completeRequest @ bower.js:23952
requestLoaded @ bower.js:23880
XMLHttpRequest.send (async)
(anonymous) @ bower.js:23926
sendReq @ bower.js:23688
serverRequest @ bower.js:23483
processQueue @ bower.js:28357
(anonymous) @ bower.js:28373
$eval @ bower.js:29655
$digest @ bower.js:29469
$apply @ bower.js:29763
(anonymous) @ bower.js:38258
dispatch @ bower.js:5206
elemData.handle @ bower.js:5014

**Comment by Sbrenthughes** [comment]
https://github.com/capitalone/Hygieia/issues/1554 try looking at this.

**Comment by htvan1** [comment]
What nireeshT recommend  doesn't fix general issue with the test data provided, that does fix auth log in but not for --local true.  If I removed the true boolean from the log in/auth pages, this header issues goes away.  I log in with a user I have made and then new errors pop up.  I believe the data model for test data is not current or has not been updated to reflect changes at some point.  I worked through another data model issue, but then another one just popped up...So I just stopped trying to use it.  I believe the test data needs a close inspection and refreshing to match the current code base.

**Comment by htvan1** [comment]
@nireeshT  here is my issue. Let me know if you have any thoughts around it.

**Comment by nireeshT** [comment]
@htvan1  - Are you trying to create a new user from UI using signup option? what is the usecase? Do you see "authentication" collection in Mongo? share screenshots of error

**Comment by htvan1** [comment]
I originally assumed one needed to log in to see the dash boards, but as thats not the case.  Lets say that is working as intended and shift focus to this error: 
TypeError: Cannot read property 'name' of undefined
    at dashboardService.getDashboardTitle (dashboardValidationService.js:47)
    at processDashboardResponse (site.js:132)
    at processQueue (bower.js:28357)
    at bower.js:28373
    at Scope.$eval (bower.js:29655)
    at Scope.$digest (bower.js:29469)
    at Scope.$apply (bower.js:29763)
    at done (bower.js:23743)
    at completeRequest (bower.js:23952)
    at XMLHttpRequest.requestLoaded (bower.js:23880)

![screen shot 2017-08-30 at 10 39 08 am](https://user-images.githubusercontent.com/23086265/29886835-4ddd0692-8d70-11e7-8272-d62a8556e0fb.png)

**Comment by Sbrenthughes** [comment]
@htvan1 I am going to assume this issue was resolved via the merged PR. Please reopen if this is not the case
