### ISSUE TITLE
Blank api/dashboard

### ISSUE THREAD

**Issue by UsmanSheriff** [capitalone/Hygieia#1609]
This could be an old issue but its 1st time for me. Hope someone can help me here. Many thanks in advance. 

I followed the steps discussed in issue #260 and still hit with the blank api screen and All Dashboard displays "No Result" though I have started jar file from Hygieia/collectors/build/jenkins/target folder. This is the only collector I am using for time being.

Appreciate your timely response.

I have these warnings in api log
----------------------------------

07:12:39,108 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
07:12:39,108 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/opt/mount/apisrvc/Hygieia/api/target/api.jar!/lib/core-2.0.5-SNAPSHOT.jar!/logback.xml]
07:12:39,108 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/opt/mount/apisrvc/Hygieia/api/target/api.jar!/logback.xml]
2017-08-10 07:12:41,428 WARN  o.s.c.c.c.ConfigServicePropertySourceLocator - Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/application/default": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused)

![hygieia_build_result_4](https://user-images.githubusercontent.com/15108426/29160453-d84ff096-7de4-11e7-87a0-454bb1cf0c55.jpg)

Just in case, if you need my dashboard and application properties details for reference.

Dashboard Properties
--------------------
dbname=dashboard
dbusername=hyadmin
dbpassword=xxxxxx
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017,127.0.0.1:27017
server.contextPath=/api
server.port=8080
corsEnabled=false
auth.expirationTime=10

Application properties
----------------------
dbname=dashboard
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017,127.0.0.1:27017
dbusername=hyadmin
dbpassword=xxxxxx
jenkins.cron=0 0/5 * * * *
jenkins.pageSize=1000
jenkins.folderDepth=10
jenkins.servers[0]=https://myjenkin server:portnumber/
jenkins.usernames[0]=xxxxxxxxx
jenkins.apiKeys[0]=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
jenkins.saveLog=true

**Comment by UsmanSheriff** [comment]
Just in case adding properties details for your reference

Dashboard Properties
--------------------
dbname=dashboard
dbusername=hyadmin
dbpassword=xxxxxx
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017,127.0.0.1:27017
server.contextPath=/api
server.port=8080
corsEnabled=false
auth.expirationTime=10

Application properties
----------------------
# Database Name
dbname=dashboard

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
dbreplicaset=false
dbhostport=localhost:27017,127.0.0.1:27017

# Database Username - default is blank
dbusername=hyadmin

# Database Password - default is blank
dbpassword=xxxxxx

# Collector schedule (required)
jenkins.cron=0 0/5 * * * *

# The page size
jenkins.pageSize=1000

# The folder depth - default is 10
jenkins.folderDepth=10

# Jenkins server (required) - Can provide multiple
jenkins.servers[0]=https://myjenkin server:portnumber/


# Another option: If using same username/password Jenkins auth,
#   set username/apiKey to use HTTP Basic Auth (blank=no auth)
jenkins.usernames[0]=xxxxxxxxx
jenkins.apiKeys[0]=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# Determines if build console log is collected - defaults to false
jenkins.saveLog=true

**Comment by Sbrenthughes** [comment]
When you try to login do you have a green checkmark for the api connection?

**Comment by UsmanSheriff** [comment]
Yes. It is there.
![hygieia_build_result_5](https://user-images.githubusercontent.com/15108426/29173857-21e24754-7e17-11e7-92b2-d181bff8d38d.jpg)

**Comment by Sbrenthughes** [comment]
Try this on your browser` http://16.202.3.160:8080/api/ping`. What are your results?

**Comment by UsmanSheriff** [comment]
Returns "True"

**Comment by Sbrenthughes** [comment]
Can you try creating a dashboard?

**Comment by UsmanSheriff** [comment]
I am sorry. I do not know that step. How to create a dashboard?

**Comment by Sbrenthughes** [comment]
1)create a user
2) login
3) click the create dashboard button
4) enter information 
5 click save

**Comment by UsmanSheriff** [comment]
I already created an users name "usman" (I can see that in 3T UI). When I login I get this screen. It does not have any button other than "Login".
![hygieia_build_result_6](https://user-images.githubusercontent.com/15108426/29174744-d21244e2-7e19-11e7-89cc-b3deb11ae246.jpg)

**Comment by Sbrenthughes** [comment]
Do you have the latest Code from master?

**Comment by UsmanSheriff** [comment]
Yes. I used this command yesterday git clone https://github.com/capitalone/Hygieia.git and downloaded code

**Comment by nitin1706** [comment]
if you have already created users, you should be able to log in by clicking on 'Login' button and entering user credentials. If user doesn't exist, you can signup by clicking on 'Sign-up' option on the bottom of same screen. 

Once logged in, you will see username on top right corner, and on the same screen, you will see option to create a dashboard.

**Comment by UsmanSheriff** [comment]
@nitin1706, I don't see username. I see above said blank page saying "No results"

**Comment by nitin1706** [comment]
as from the screenshot you posted, you are not logged in. 
Do you get error when you click on that 'Login' button on top-right corner?

**Comment by UsmanSheriff** [comment]
@nitin1706 That's the screen come back after login. No I did not get any error on screen. Is there a way to find background error, if any?

**Comment by nitin1706** [comment]
ok. This doesn't show any error.

I tried to do something same, I see the similar screen when I am not logged in. I can just see existing dashboards available, but no option to create one. 

Maybe you can try to sign-up with a new username using sign-up screen.

**Comment by UsmanSheriff** [comment]
@nitin1706 After sign-up new user (sheriff) I am back to the same "No result" screen.

**Comment by UsmanSheriff** [comment]
Does mongo details given here helps to resolve this puzzle?

Time being I am using non authenticated mongo. Is that a constraint in Hygieia setup?

Created couple of users through the Hygieia login screen shown in below snap. After login it goes back to "No Result" screen. That is, I don't see Dashboard creation buttion.

![hygieia_build_result_7](https://user-images.githubusercontent.com/15108426/29179388-d93ae6c2-7e26-11e7-9ed9-828a037cc8c3.jpg)

**Comment by UsmanSheriff** [comment]
Any tips? Please share
I am unable to move beyond this page. I created couple of users from this screen. Login with that user brings back to this page. 

https://user-images.githubusercontent.com/15108426/29174744-d21244e2-7e19-11e7-89cc-b3deb11ae246.jpg

**Comment by nitin1706** [comment]
did you follow the setup instructions for running api and UI? Can you share what commands you used and in which order.

You can refer setup instruction from this page: https://github.com/capitalone/Hygieia/blob/master/Setup.md

You mentioned that you are using non authenticated mongo, however there is a mention of **dbpassword** in properties shared above.

**Comment by UsmanSheriff** [comment]
@NITIN1706, I mentioned security.authorizatin=disabled. i.e. Any mongo user can access any database. I followed below said steps. 

setup DB
Created new database "dashboard"
Created a user hyadmin under dashboard

This is my mongod.conf
systemLog:
  destination: file
  logAppend: true
  path: /opt/mount/apisrvc/mongodb/log/mongod.log
storage:
  dbPath: /opt/mount/apisrvc/mongodb/data/db1
  journal:
    enabled: true
processManagement:
  fork: true  # fork and run in background
  pidFilePath: /opt/mount/apisrvc/mongodb/mongod.pid  # location of pidfile
net:
  port: 27017
  bindIp: 127.0.0.1  # Listen to local interface only, comment to listen on all interfaces.

Build the entire application from root
change to directory /opt/mount/apisrvc/Hygieia
execute the following mvn clean install package
Build succeeds

Build the project/core
change to directory /opt/mount/apisrvc/Hygieia/core
execute mvn install
build succeeds

Build and run the API
change to directory /opt/mount/apisrvc/Hygieia/api
execute mvn install
build succeeds
execute 
nohup java -jar target/api.jar --spring.config.name=api --spring.config.location=dashboard.properties & >/dev/null
api monitoring starts

# This is my dashboard.properties for api
dbname=dashboard
dbusername=hyadmin
dbpassword=xxxxxxx
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017,127.0.0.1:27017
server.contextPath=/api
server.port=8080
corsEnabled=false
auth.expirationTime=10

Build and run the UI
change to directory /opt/mount/apisrvc/Hygieia/UI
execute mvn install
build succeeds
execute gulp serve
hygieia login page opens at localhost:3000

change to directory /opt/mount/apisrvc/Hygieia/collectors/build/jenkins
execute mvn install
build succeeds
execute 
nohup java -jar target/jenkins-build-collector-2.0.5-SNAPSHOT.jar --spring.config.name=application --spring.config.location=application.properties & >/dev/null
jenkins collector starts

My Jenkins application properties file
dbname=dashboard
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017,127.0.0.1:27017
dbusername=hyadmin
dbpassword=xxxxxxx
jenkins.cron=0 0/5 * * * *
jenkins.pageSize=1000
jenkins.folderDepth=10
jenkins.servers[0]=https://<Jenkins server>:<port number>/
jenkins.usernames[0]=<jenkins login ID>
jenkins.apiKeys[0]=<Key generated in jenkins server using Jenkins login ID>
jenkins.saveLog=true

Goto http://16.202.3.160:3000/#/
Click login button. It shows the signup page
Signup a new user. Then it takes me back to http://16.202.3.160:3000/#/ page
provide a new user and password, click signin. 
Then it takes me back to http://16.202.3.160:3000/#/ page

**Comment by nb1706** [comment]
Jenkins collector is not required for this functionality.

I tried to use similar properties and commands. It works well for me.

I get the this 'blank screen and no option to create dashboard' when I click on Hygieia button on top left corner without logging in. 
To Log-in, I clicked on button next to 'Login' text. and once logged in, I see create dashboard option.

**Comment by nitin1706** [comment]
Jenkins collector is not required for this functionality.

I tried to use similar properties and commands. It works well for me.

I get the this 'blank screen and no option to create dashboard' when I click on Hygieia button on top left corner without logging in.
To Log-in, I clicked on button next to 'Login' text. and once logged in, I see create dashboard option.

**Comment by UsmanSheriff** [comment]
@nitin1706 Could it be browser problem? I am using chrome. Even I tried with incognito mode (Shit+Ctrl+N) after clearing browser cache. Also, it is not working in IE.

**Comment by nitin1706** [comment]
from your screenshot posted in first comment, it seems like you were getting option to create a dashboard. Is this issue resolved?
<img width="684" alt="screen shot 2017-08-21 at 11 31 58 am" src="https://user-images.githubusercontent.com/26907838/29526740-9fd809fa-8664-11e7-8352-8956b561218e.png">

**Comment by Sbrenthughes** [comment]
@UsmanSheriff if you are still experiencing issues can you try a fresh install of Hygieia/Mongo and follow all the instructions posted? Specifically the mongo setup. Once you follow the instructions that are suggested create a new issue if you are still having problems.

**Comment by hemantanna555** [comment]
Hi,

I am facing exactly the same issue. Can somebody confirm if this was resolved and what steps were taken.

Everything worked fine yesterday but facing the same issue today. The login does not register inspite of seeing the username fed into the mongo db properly. 

Any help is appreciated. Could it be related to the security of mongodb and the expire time for JWT

**Comment by Sbrenthughes** [comment]
@hemantanna555 can you create a new issue. Post your properties file and logs of the issue.

**Comment by blasteravismaster** [comment]
+1

**Comment by sundeepk1** [comment]
this issue seems to be faced by many users . can someone from the Hygieia community guide in order to fix. I am willing to solve this, however, need guidance as to where to look for the problem. (very limited java knowledge)

**Comment by amorphis26** [comment]
Initial issue was caused by auth.expirationTime=10 , that is 10 milliseconds. Has to be set to a much larger value.
