### ISSUE TITLE
Instructions required for stash collector in Hygieia

### ISSUE THREAD

**Issue by pallavi-d** [capitalone/Hygieia#1610]
Can anyone please help on creating the stash collector in jira

**Comment by nitin1706** [comment]
@pallavi-d :  are you looking for Stash collector ? 
Stash collector has been rebranded as Bitbucket collector. 
Refer:  https://www.atlassian.com/software/bitbucket/server
https://github.com/capitalone/Hygieia/pull/189

Bitbucket Collector: https://github.com/capitalone/Hygieia/blob/gh-pages/pages/hygieia/collectors/scm/bitbucket.md
