### ISSUE TITLE
How to show record sTypeName from MongoDB

### ISSUE THREAD

**Issue by sanchitacool** [capitalone/Hygieia#1611]
![1](https://user-images.githubusercontent.com/29974254/29169304-0c6838f0-7df1-11e7-8974-a310c6ea6bf0.png)

How to pull record sTypeName like Story/Epic from MongoDB feature collection and display in feature widget. Not able to populate on Hygieia dashboard

**Comment by Sbrenthughes** [comment]
Check to see if it is being pulled already. If not add it to the query to be pulled. Once you do that you should be able to get the data on the UI to then display.

**Comment by pasan96** [comment]
@Sbrenthughes  Can you please explain further? sTypeName is not in the response from API end points..
