### ISSUE TITLE
Bitbucket collector - Not able to recognize repository 

### ISSUE THREAD

**Issue by NikhilYadavGIT** [capitalone/Hygieia#1622]
Hi,
I have configured bitbucket collector and while fetching the data from repository, it's not able to recognize repo....but this repository exist in project HYG (Whose PROJECT KEY is HYG01) 

Under bitbucket collector, Repo URL configured is as below -
https://bitbucket.org/HYG01/testrepository    (this works on hitting in UI)

Response in logs is as below after configuration -
Failed to obtain commits from -
https://bitbucket.org/rest/api/1.0/projects/HYG01/repos/testrepository/commits?until=master&limit=25
404 Not Found

Tried hitting this URL on UI as well but there also it's giving same error. Request you to please help on this one as I am stuck at this step. Thanks !!

Also, i tried by hitting URL directly with projectName as HYG instead of HYG01 - then too it's throwing same error - 404

**Comment by NikhilYadavGIT** [comment]
Hi @satishc1 @tabladrum @nireeshT - Could you please help on above error ?
/rest/api/1.0 is not able to recognise repository and giving 404 error.

**Comment by Sbrenthughes** [comment]
Can you try looking at https://github.com/capitalone/Hygieia/issues/1073?

**Comment by NikhilYadavGIT** [comment]
@Sbrenthughes - Hi...thanks that I already looked at and not having password encryption error but the problem is with rest api URL 1.0.
For me, rest API url looks ok but not exactly sure why it's giving 404 error.

https://bitbucket.org/rest/api/1.0/projects/HYG01/repos/testrepository/commits?until=master&limit=25

Any help would be appreciated ?

I am stuck at this.....Thanks !!

**Comment by nitin1706** [comment]
share your properties file and command used to run bitbucket collector.

**Comment by nitin1706** [comment]
re-open with properties file.
