### ISSUE TITLE
Jenkins plugin configuration error 

### ISSUE THREAD

**Issue by bseelam-hub** [capitalone/Hygieia#1630]
Hi , 
Successfully installed Hygieia and UI aslo coming up  But , when i am trying to configure the plugin under jenkins>managejenkins>configuresystem , facing the below issue when do test connection . 

my UI is accessible on 8081 port not on 3000 . 

Please suggest !!
![hygiei](https://user-images.githubusercontent.com/26402613/29398721-e042f4e2-8343-11e7-8c01-312d1979ecb4.png)

**Comment by Sbrenthughes** [comment]
Does http://IP:8081/api/ping in your web browser return true?

**Comment by bseelam-hub** [comment]
yes it returned true .

**Comment by bseelam-hub** [comment]
Can you please suggest anything ?

**Comment by Sbrenthughes** [comment]
https://github.com/capitalone/Hygieia/issues/380

**Comment by bseelam-hub** [comment]
Oh!!! It worked .. we just need to apply and test .. Weird !! 

Thanks for helping out .
