### ISSUE TITLE
Udeploy collector not showing up application metrics

### ISSUE THREAD

**Issue by ameetsvshah** [capitalone/Hygieia#1631]
We are not able to see any application metrics in udeploy widget.

UCD collector integration is successful as I am getting the list of applications from UCD.

But once we select the application and save we do not get any data.
We want to configure pipeline view also which we are not able to configure.

UCD version 6.2.4
Hygieia 2.0.5

**Comment by nireeshT** [comment]
@ameetsvshah  Follow https://github.com/capitalone/Hygieia/issues/1084 for updates

**Comment by nireeshT** [comment]
@ameetsvshah  - Reopen if issue not resolved
