### ISSUE TITLE
Git hub collector not collecting new commits

### ISSUE THREAD

**Issue by Amogh1995** [capitalone/Hygieia#1632]
My git hub collector is not collecting any new commits on my repository.

My log shows:
-----------------
2017-08-17 20:18:00,004 INFO  c.c.d.collector.CollectorTask - Starting...
2017-08-17 20:18:00,004 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-08-17 20:18:01,812 INFO  c.c.d.collector.CollectorTask - Repo Count              3        1s
2017-08-17 20:18:01,812 INFO  c.c.d.collector.CollectorTask - New Commits             0        1s
2017-08-17 20:18:01,812 INFO  c.c.d.collector.CollectorTask - Finished  

My git.properties file conatains:
#Database Name 
dbname=nttdb
 
#Database HostName - default is localhost
dbhost=localhost
 
#Database Port - default is 27017
dbport=27017
 
#Database Username - default is blank
dbusername=dashboarduser
 
#Database Password - default is blank
dbpassword=dbpassword
 

 
# Logging File location
logging.file=E:\Amogh NTT\Hygieia\collectors\scm\github\target\logs\github.log

# Collector schedule (required)
github.cron=0 0/1 * * * *

github.UserId=amogh1995
github.host=https://github.com
github.key=46QaAaE4+7lUXaHlQ/SoqHxrDQINc6gI

# Maximum number of days to go back in time when fetching commits
github.commitThresholdDays=90

#Optional: Error threshold count after which collector stops collecting for a collector item. Default is 2.
github.errorThreshold=10

**Comment by nitin1706** [comment]
can you check your api logs of there is any error.

**Comment by nireeshT** [comment]
@Amogh1995  - Increase your error threshold value to 100  and run again. 

github.errorThreshold=100

**Comment by nireeshT** [comment]
@Amogh1995  - Reopen if issue is not resolved
