### ISSUE TITLE
GitHub WebHook is not working 

### ISSUE THREAD

**Issue by bseelam-hub** [capitalone/Hygieia#1646]
HI i am trying setup the CodeRepo Widget  ? How can we do that  ? 
Should we run the collector in background to reflect the same in widget ?

**Comment by nitin1706** [comment]
In order to setup any widget, you need to run the corresponding collector first.

**Comment by nireeshT** [comment]
@bseelam-hub  Refer https://github.com/capitalone/Hygieia/blob/gh-pages/pages/hygieia/collectors/scm/github.md 

Run github collector , share logs if you see any error.
