### ISSUE TITLE
How to configure feature Widget ? 

### ISSUE THREAD

**Issue by bseelam-hub** [capitalone/Hygieia#1647]
How to Configure feature Widget ?

**Comment by bseelam-hub** [comment]
Any Help ?

**Comment by Sbrenthughes** [comment]
Can you explain more about what you are trying to do? Are you asking about the widget itself of the collector that pulls the data?

**Comment by nireeshT** [comment]
@bseelam-hub  - Refer 
JIRA - https://github.com/capitalone/Hygieia/blob/gh-pages/pages/hygieia/collectors/feature/jira.md
GitLab - https://github.com/capitalone/Hygieia/blob/gh-pages/pages/hygieia/collectors/feature/feature-gitlab.md 
Version One - https://github.com/capitalone/Hygieia/blob/gh-pages/pages/hygieia/collectors/feature/versionone.md
