### ISSUE TITLE
Unable to click Save on Code Repo Collector in UI

### ISSUE THREAD

**Issue by michaelsalvia** [capitalone/Hygieia#165]
Nothing shows in Network tab or Console in Chrome or Firefox.

**Comment by joshku** [comment]
I had the exact same issue until I realised that I need to get the GitHub code collector connected first. Make sure you execute that jar file first and configure it to point to github before you configure the code repo collector in the UI.

**Comment by tabladrum** [comment]
Yep. Will take this as an opportunity to update the documentation.

**Comment by michaelsalvia** [comment]
Thank you @joshku :+1:, I ended up getting there after a little bit :-).

Perhaps the front end should do a lookup to MongoDB to see if there is an active GitHub collector and if not show a informational message stating that there is no collectors available to configure.

@tabladrum Other than some small issues like this LOVING Hygieia! :heart:

**Comment by joshku** [comment]
I definately agree. It would be nice to have an alert message or something to let us know if there are no collectors connected right now.

**Comment by tabladrum** [comment]
Can you close this issue and open a specific one with the enhancement request?

**Comment by michaelsalvia** [comment]
Will do now!
