### ISSUE TITLE
Unbale to view test data for hygieia

### ISSUE THREAD

**Issue by tsr2017** [capitalone/Hygieia#1655]
I have configured hygieia but when I am trying to run it using 
 gulp serve --local true

But I cannot see any dashboards
<img width="1273" alt="screen shot 2017-08-23 at 5 25 50 pm" src="https://user-images.githubusercontent.com/31294059/29641217-2a7dbb6c-8828-11e7-9c47-637384e24fc6.png">

Do we need to create two different database in mongo DB.
I am following hygieia documentation in this they created dashboarddb.
I am confused in dashboard and dashboarddb.
Do we need to use same in dashboard.preperties and application.properties?

**Comment by nitin1706** [comment]
you don't need to create two different database, one database will work. You can name it as dashboarddb. and yes use same in dashboard.properties and application.properties

**Comment by tsr2017** [comment]
I have made correction in .properties file but I am still unable to view test data.

I am able to get data from Jenkins as well. I checked in db all job data is fetched but I am unable to view on UI.
Please guide

**Comment by tsr2017** [comment]
My issue got resolved.

**Comment by htvan1** [comment]
@tsr2017  How on earth did you get the test data to show up?  I run in to all sort of missing methods and data model issues.

**Comment by nireeshT** [comment]
@htvan1  - Create a new issue with details of error, we can troubleshoot the issue precisely.  I will close this issue.
