### ISSUE TITLE
Need information on Hygieia Setup

### ISSUE THREAD

**Issue by DevOps575** [capitalone/Hygieia#1660]
Guys,

I have to setup Hygieia for my project and want to run almost all collectors. Can you please help me to understand on how much resources we need? For example CPU, Storage, RAM etc..

It will help me to provision the box accordingly.

Thanks,
Sanjiv

**Comment by srinathanand** [comment]
The best way I would say to do it is through the docker-compose.yml file. Build the individual docker images and just do a "docker-compose up". Keep the docker-compose.yml file only for the db,API and UI layers and override it with a docker-compose.override.yml for the individual collectors. You might need to tweak the files a little bit to get it to work. It is not the most smoothest docker setup that I have seen.

**Comment by satishc1** [comment]
@DevOps575 
#805
#753
