### ISSUE TITLE
docker-compose problem, ERROR: Error: image library/hygieia-api:latest not found

### ISSUE THREAD

**Issue by ckmason** [capitalone/Hygieia#168]
Am I doing something wrong below?  I am trying to use the docker-compose.yml file I got from here: https://github.com/capitalone/Hygieia/blob/master/docker-compose.yml .

Carltons-MacBook-Pro:hygieia ckmason$ docker-compose up -d
Pulling mongodb (mongo:latest)...
latest: Pulling from library/mongo
1d53ee5b1800: Pull complete
74872ba2a3b0: Pull complete
258c8eb48222: Pull complete
952a583811c8: Pull complete
b60c8283e3a3: Pull complete
45a54dc4182c: Pull complete
d06d99c4cda4: Pull complete
cf72be04cee8: Pull complete
65bd2aff5776: Pull complete
7fc84e79bdf7: Pull complete
254a273043b4: Pull complete
89f506c965f6: Pull complete
1cf06764a987: Pull complete
768afca0afa4: Pull complete
0c4d5e1b10fa: Pull complete
61e706b78ea7: Pull complete
a276bab7ffde: Pull complete
Digest: sha256:45185e844bbdc5f2d6ab4e8910aff35871e68bbd32ae27c35c89876c9c8b9a42
Status: Downloaded newer image for mongo:latest
Creating mongodb
Pulling hygieia-api (hygieia-api:latest)...
Pulling repository docker.io/library/hygieia-api
ERROR: Error: image library/hygieia-api:latest not found

**Comment by roller1187** [comment]
Are you building the image locally with Maven? This image does not exist in the global Docker registry; that's what Docker is complaining about.

**Comment by ckmason** [comment]
Hi, right.  Yes joshku's pull request #169 was a big help.  I needed to update the docker-compose file to refer to them as capitaloneio/hygieia-api:latest and then I was able to make it work.  At least docker-compose would run fine.

**Comment by ckmason** [comment]
Are their plans to have "official" Hygieia Docker images in the public Docker registry?

**Comment by amitmawkin** [comment]
They are availlale under capitaloneio account we are in process of transitioning them to capitalone account.




AM
=======
804-229-3241

Sent with Good (www.good.com)


-----Original Message-----

**Comment by jdamick** [comment]
right, that's why i havent merged the pull request yet - we need to update to correct namespace

**Comment by ckmason** [comment]
OK, closing this issue. Thank for the info.
