### ISSUE TITLE
Build data is not showing up in Product Dashboard

### ISSUE THREAD

**Issue by shivam101992** [capitalone/Hygieia#1681]
I'm able to see build data in team dashboard but I don't see anything in Build column in Product dashboard.

Could you please help me with this? What am I missing here?

**Comment by nireeshT** [comment]
@shivam101992 - Provide environment details

Code Repo - Github/Subversion/..etc
Deploy Tool - Hygieia Jenkins Plugin/ UDeploy/ Rundeck /... etc
JDK Version -
Browser & Version -

Attach screenshots for team and product dashboard.

**Comment by shivam101992** [comment]
Code Repo - Github
Deploy Tool - Hygieia Jenkins Plugin
JDK Version - 1.8
Browser & Version - Google Chrome 60.0.3112.113

**Comment by nireeshT** [comment]
@shivam101992  does your build 5 have any commits ? if 5 shoiws no changes included in build, do a dummy commit and run build 6. Commits should be moved automatically to Build stage and will disappear in Commit stage.

**Comment by nireeshT** [comment]
@shivam101992  - reopen if issue is not resolved
