### ISSUE TITLE
Quality widget not showing data

### ISSUE THREAD

**Issue by anuradha92** [capitalone/Hygieia#1683]
![capture](https://user-images.githubusercontent.com/18590251/29808264-f7270138-8cb4-11e7-9cf8-312de169c3f6.PNG)
![capture1](https://user-images.githubusercontent.com/18590251/29808265-f7cf4870-8cb4-11e7-9742-f3692fdddb3b.PNG)
![capture3](https://user-images.githubusercontent.com/18590251/29808267-f9b7c752-8cb4-11e7-9999-d6e664f6b639.PNG)
![4](https://user-images.githubusercontent.com/18590251/29808273-fcaeaf52-8cb4-11e7-9dcf-7b1a38830a4f.PNG)
**my data base is showing the all data but my widget doesn't showing Security Scan & open source scan**

**Comment by nireeshT** [comment]
@anuradha92  - thats because there are no collector items with type "StaticSecurityScan"

**Comment by pasan96** [comment]
I have the same issue, there are collector items and everything for code quality in the DB :
![ui_widget](https://user-images.githubusercontent.com/19402786/29908961-6228612e-8e41-11e7-92b9-93163be28917.PNG)

![ui_widget config](https://user-images.githubusercontent.com/19402786/29908956-600073e6-8e41-11e7-96d5-f1663100bbc7.PNG)

![code_quality data](https://user-images.githubusercontent.com/19402786/29908954-5d70a4de-8e41-11e7-94b8-8a39c664a9fe.PNG)

![components](https://user-images.githubusercontent.com/19402786/29908951-5a403bc6-8e41-11e7-8e7b-febb6f208e5f.PNG)

![collector_item](https://user-images.githubusercontent.com/19402786/29908948-56ae3f80-8e41-11e7-94f6-4e41bd0923ae.PNG)

![collector](https://user-images.githubusercontent.com/19402786/29908940-4b0de022-8e41-11e7-88af-5749cb2f222d.PNG)

All the data is coming to the DB, just not showing on the UI widget.

**Comment by stevegal** [comment]
I wonder if you have 2 collector objects with the same resulting names and therefore picking up the wrong one. If you clear out your db and restart the collectors does the problem persist?

**Comment by pasan96** [comment]
I've tried clearing the code quality collection, which collection do I need to clear? collectors and components?

**Comment by nireeshT** [comment]
@pasan96  - can you send me your code_quality, components and collector_items for this use case.

**Comment by stevegal** [comment]
@pasan96 I'm trying to repeat now... I remember an issue I had before I PR'ed the collector into the repo where I had the wrong ID against the data... but I fixed that... then again... just resetting Hygieia up.

**Comment by stevegal** [comment]
@pasan96 think I've found it... the api now requires an instanceUrl and a projectId in the collector. I think it null pointers without that in place hence no data back. I'll try and figure out what they should be and add them.

**Comment by stevegal** [comment]
#1718 should fix

**Comment by pasan96** [comment]
@stevegal  It's working fine now, thanks :smile:

**Comment by anuradha92** [comment]
thanks @stevegal
