### ISSUE TITLE
Hygieia custom widget

### ISSUE THREAD

**Issue by tsr2017** [capitalone/Hygieia#1694]
I want to show jenkins's job email attachement content on hygieia dashboard.
What should be the approach?
Do I need to write custom collector for it.
I need to store data as well in Mongo DB.
Please guide if someone has any idea.

Thanks

@nireeshT @tabladrum @satishc1 @nitin1706 @MarkRx @rob-miller-777

**Comment by nireeshT** [comment]
@tsr2017  Provide use case. Build status email confirmation on Hygieia dashboard or on Build widget.

**Comment by tsr2017** [comment]
I have an email attachment for each jenkins build. I am able to get data from jenkins on dashboard.
I want to show attached file data as well on Hygieia dashboard and it is specific to each build.
I want to show this in a view which pops up when we click on build. If it is in the form of attachment then it will be ok. I need to preserve this data so I need to store it in mongo DB as well.

**Comment by nireeshT** [comment]
@tsr2017  you can have it in existing details page opened when clicked on specific build. You can load data to builds collections and read it from there .

**Comment by tsr2017** [comment]
How can I get emaill attachment there? Is there any way to attach that file in that page which is opened when we click on any specific build?

**Comment by tsr2017** [comment]
@nireeshT If I add one field in builds collection, Do I need to do some changes in code as well?

**Comment by nireeshT** [comment]
@tsr2017  - you need to find jenkins api which you can pull email data to hygieia, something like email-ext plugin.

**Comment by nireeshT** [comment]
@tsr2017  check this api if it is helpful to get email data 
https://wiki.jenkins.io/display/JENKINS/Remote+access+API

**Comment by tsr2017** [comment]
@nireeshT It seems I have to use this
http://jenkinsapi.readthedocs.io/en/latest/artifact.html
But to show this data on that page which opens when we click on build, Do I need to write some code?

**Comment by tsr2017** [comment]
@nireeshT One quick QQ is it good approach to customize collector according to requirement?

**Comment by tsr2017** [comment]
@nireeshT which editor are you using to compile hygieia code? Could you please help.
I have used java long time ago on eclipse. But for collector I will have to setup maven as well so wanted to started by right approach.

**Comment by nireeshT** [comment]
@tsr2017  using Intellij Idea, Eclipse is also equally good. :)

**Comment by tsr2017** [comment]
@nireeshT.
Thanks

Intellij Idea Open source will work?
I pinged you on gitter.

**Comment by nireeshT** [comment]
@tsr2017  it should work
