### ISSUE TITLE
Improving Image build process

### ISSUE THREAD

**Issue by pravsingh** [capitalone/Hygieia#1701]
First of all thank you committers for managing such beautiful and a complex project.
Came across to this recently and started playing with it. Have some minor feedbacks for the improvements however the major pain point I faced was rebuilding the whole application stack. Which takes quiet some time to finish given the size of the code base.

I have some idea of improving the build time.Its like this:
  Application is composed of building the api.jar and then docker image. What we can do is to separate out the these two steps. Once we do it, the framework part (mostly api.jar) will not be rebuild and instead can be pulled from the maven artifactory (or we can pull it from this gitrepo via maven build process). Now most of our efforts will be used in building the image and not the api.jar.

In case some users need to create custom collectors/connectors, they can easily do in the second maven based project which builds docker image by leveraging packages from api.jar.

The same refactoring can be done for UI.

Let me know what you guys feel about it. I would love to hear your wise feedbacks.

thanks.

**Comment by pravsingh** [comment]
Once everyone agrees to a common design, I would love to work on this enhancement.

**Comment by pravsingh** [comment]
FYI @tabladrum @amitmawkin

**Comment by matthewbeasley** [comment]
@pravsingh - we currently support building only pieces of Hygieia. In order to accomplish this, simply navigate to the directory of the component you would like to build (e.g api) and then run `mvn clean install` or `mvn clean install docker:build` if you want docker images. This will build only the desired module.
