### ISSUE TITLE
Sonar documentation is incorrect if you have v6.0 - v6.2  

### ISSUE THREAD

**Issue by htvan1** [capitalone/Hygieia#1704]
Could not get the data to populate on the UI...no errors in logs or console....super annoying.  I finally just decided to debugged the collector on my day off, for fun. 
Low and behold: /api/project_analyses/search?project used in DefaultSonar6Client does not appear in the API until 6.3 and the collector eats the error instead of letting you know.

Simple solution, just say your version is 5.9.  This switches the client to the older one. (well mostly populating.....the unit test stuff is not populating, but I am not sure if that is my sonarQB set up or another bug..will save that for the weekend.  If it turns out to be another bug will add info for that here)

Hope this helps others.

Also I won't be able to submit an update to the readme for sometime due to our review policy around committing to open sources.  If anyone else wants to do so, my thanks.

**Comment by nag10** [comment]
yes.. sonarqube collector not populating the data for 6+ versions.. 


![image](https://user-images.githubusercontent.com/12077661/30001299-4cabe1c8-90a7-11e7-95d0-368f91254e28.png)

**Comment by DeepakYadav17** [comment]
Yes, I am also seeing this behaviour for SonarQube version 6.2.

**Comment by nitin1706** [comment]
PR #1736

**Comment by Megha849** [comment]
This has been updated in the documentation in PR #1749 for code fix with PR #1736.

**Comment by htvan1** [comment]
Thanks @Megha849 !
