### ISSUE TITLE
Purpose of karma.conf.js in the UI folder

### ISSUE THREAD

**Issue by sraghu-rs** [capitalone/Hygieia#1705]
The UI folder has "karma.conf.js" karma configuration file. What is the purpose of this file? Does this file can be used for behavior-driven development testing of UI codes?

**Comment by kumarvarun1252** [comment]
@sraghu-rs I think karma.conf.js is for the UI unit tests. We are working on BDD test framework using cucumber & protractor. You should be able to reuse/develop UI Tests using that framework in some days
