### ISSUE TITLE
hygieia-jenkins-build container fails to start out of the box

### ISSUE THREAD

**Issue by anutting** [capitalone/Hygieia#1709]
After I get the mvn docker:build running successfully, I then run a docker-compose up
and the jenkins collector exits with code 137:
./jenkins-build-properties-builder.sh not found.

**Comment by nitin1706** [comment]
Can you share properties file? 
If you are using the same properties as you mentioned in #1707, jenkins-build-properties are not mentioned in there.

**Comment by anutting** [comment]
Thanks for your reply, but I actually just solved this problem by rebuilding the container using the command: `mvn clean package -pl collectors/build/jenkins docker:build`

The #1707 issue is really my main problem right now since it's so difficult to track down the cause.
