### ISSUE TITLE
Cannot reach the API from the UI when server.port is modified

### ISSUE THREAD

**Issue by juantoledo** [capitalone/Hygieia#1710]
Hello, 

I'm trying to launch the UI with an API port different from 8080 (ie 6666) with no success. I tried changing the api.config value in gulpfile.js and is not working, getting  API Connectivity in red. Any ideas? 

Thanks in advance

**Comment by nireeshT** [comment]
@juantoledo  - what did you specify in api properties file 
server.port=8080?

**Comment by juantoledo** [comment]
server.port=8050

**Comment by stevegal** [comment]
You may run into quite a lot of cors issues. I work around this by setting up an httpd service to act as a reverse proxy to api and hi so they all have the same server and port. Otherwise the api needs lots of changes to allow cors

**Comment by juantoledo** [comment]
Oh, that are bad news :(.

Thanks

**Comment by nireeshT** [comment]
@juantoledo  - Reopen if issue is not resolved

**Comment by nireeshT** [comment]
@juantoledo  - Reopen if issue is not resolved
