### ISSUE TITLE
getting connection timeout error for bitbucket collector

### ISSUE THREAD

**Issue by tsr2017** [capitalone/Hygieia#1713]
Is there any way to increase timeout duration?
I am getting connetion timeout error for bitbucket collector.

@nireeshT @satishc1 @tabladrum

**Comment by satishc1** [comment]
@tsr2017 Reduce the cron frequency of the collector or increase the timeout duration for bitbucket.

**Comment by tsr2017** [comment]
How to increase timeout duration for bitbucket?

**Comment by satishc1** [comment]
https://confluence.atlassian.com/bitbucketserverkb/how-do-i-change-the-default-session-timeout-779171650.html
