### ISSUE TITLE
Docker compose file shows all environment properties commented out for all collector? 

### ISSUE THREAD

**Issue by rajeshksingh15** [capitalone/Hygieia#1715]
Hello, 
Would like to know why Docker compose file shows all environment properties commented out for all collector? 
Where and which file need to modify/update for individual collector ? adding them in Docker compose will override individual docker file collectors ?   Pls advise. 
 
Below is an example of Jenkins-build-collector from docker compose. 
------------------
hygieia-jenkins-build-collector:
  image: hygieia-jenkins-build-collector:latest
  container_name: hygieia-jenkins-build
  volumes:
  - ./logs:/hygieia/logs
  links:
  - mongodb:mongo
  - hygieia-api
#  environment:
#Jenkins server (required) - Can provide multiple
#  - JENKINS_MASTER=ttp://jenkins.company.com
#If using username/token for api authentication (required for Cloudbees Jenkins Ops Center) see sample
#  - JENKINS_OP_CENTER=http://username:token@jenkins.company.com
#Another option: If using same username/password Jenkins auth - set username/apiKey to use HTTP Basic Auth (blank=no auth)
#  - JENKINS_USERNAME
#  - JENKINS_API_KEY
#  - JENKINS_CRON=0 0/5 * * * *
#Determines if build console log is collected - defaults to false
#  - JENKINS_SAVE_LOG=true

**Comment by asg247** [comment]
@rajeshksingh15 By default, Compose reads two files, a docker-compose.yml and an optional docker-compose.override.yml file. By convention, the docker-compose.yml contains your base configuration. The override file, overrides for existing configuration or adds new configuration.
You can create a docker-compose.override.yml and add the environment properties for Jenkins.

When  environment configuration is provided both in yml file and the Dockerfile ENV, the value from ENV will be applied.
