### ISSUE TITLE
How to debug Hygieia ? 

### ISSUE THREAD

**Issue by PradipRahulSJ** [capitalone/Hygieia#1722]
Hello all,

I've successfully set up Hygieia. Thanks.Now, I'd like to debug Hygieia from the controller to Angular. Please can someone advise how to start the server in debug mode and how to configure debugger in eclipse please ?

**Comment by nitin1706** [comment]
if you are using some IDE, you can launch API module as Java Application giving command arguments for properties name and location (same command that is used for running API module from console). For Angular, you can take help of developer tools in browser.

**Comment by dzoneuser** [comment]
Hi. I am using the ide:-STS for  Hygieia. I can run the application from command prompt successfully, But I wanted to debug from ide aswel. I tried debug as ->java application, but cudnt do it, as it is looking for a main-class. 
@nitin1706.  could you please elaborate the step, if possible with a screenshot?
