### ISSUE TITLE
Hygieia Bamboo Plugin for Product Dashboard

### ISSUE THREAD

**Issue by vedpune** [capitalone/Hygieia#1723]
Hello Everyone, 

Is there any support available for bamboo to push the data in DB like we have for jenkins, for product dashboard ?

**Comment by nireeshT** [comment]
@vedpune  - push based is not available yet. Instead you can use bamboo collector to pull data and same will reflect in product dashboard.

**Comment by nireeshT** [comment]
@vedpune  - reopen if issue is not resolved
