### ISSUE TITLE
sonar project not listed

### ISSUE THREAD

**Issue by equick** [capitalone/Hygieia#1726]
Hi  there,

We are using Sonar 5.6.6.

I'm trying to link up Sonar on our Hygieia dashboard but can't find our project in the widget dropdown list, eventhough it is available at `http://sonar_address:9000/sonar/overview?id=com.xxx.xxx.xxx%3Aartifact-name`

After digging into the code a bit, I see that the Sonar collector fetches projects from `http://sonar_address:9000/sonar/api/resources?format=json`

And when I goto that address, lo and behold our project is not there either.

My question is, how to I configure this project to show up under /api/resources?

Thanks,
Ed

**Comment by nitin1706** [comment]
Refer issue #1704.

**Comment by nitin1706** [comment]
this may help: #1704

**Comment by equick** [comment]
I think the other issue relates to higher versions of Sonar. The one we use is version 5.6.6. I have to specify this as 5.6 in the properties file below as the collector doesn't start with the extra digit.

```
# Database Name
dbname=dashboarddb

# Database HostName - default is localhost
#dbhost=localhost

# Database Port - default is 27017
#dbport=9999

# MongoDB replicaset
#dbreplicaset=[false if you are not using MongoDB replicaset]
#dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=dashboarduser

# Database Password - default is blank
dbpassword=xxxxxxxx

# Collector schedule (required)
sonar.cron=0 0/1 * * * *

sonar.username=xxxxxxxxx
sonar.password=xxxxxxxxx

# Sonar server(s) (required) - Can provide multiple
sonar.servers[0]=https://devsupport-sonar.it.global.snakeoil:9009/sonar
# Sonar version, match array index to the server. If not set, will default to version prior to 6.
sonar.versions[0]=5.6

# Sonar Metrics - Required.
#for Sonar 5.4 and above
sonar.metrics[0]=ncloc,violations,new_vulnerabilities,critical_violations,major_violations,blocker_violations,tests,test_success_density,test_errors,test_failures,coverage,line_coverage,sqale_index,alert_status,quality_gate_details
```

**Comment by nitin1706** [comment]
do you see any error in this collector log, if so, can you share the stack trace.

**Comment by equick** [comment]
There aren't any errors or Warnings in the collector log. That seems to be running as expected.

I can see my project under https://devsupport-sonar.it.global.snakeoil:9009/sonar/api/projects/index but not under https://devsupport-sonar.it.global.snakeoil:9009/sonar/api/resources?format=json

**Comment by nitin1706** [comment]
you may want to check sonar help, which can help you configure sonar to show metrics under the specified locations. for quick look, you can refer these:
1. check if these metrics show up under: **`api/projects/`** rather than **`api/resources/`**
2. https://stackoverflow.com/questions/44396930/sonarqube-web-api-api-resources-not-returning-all-projects
3. https://stackoverflow.com/questions/26620609/sonar-webservice-api-resources-endpoint-returns-no-metrics

**Comment by equick** [comment]
Thanks a lot. So it looks like I need the collector to fetch the projects from https://devsupport-sonar.it.global.snakeoil:9009/sonar/api/projects/index, extract the resource key there, and then fetch the metrics from eg, https://devsupport-sonar.it.global.snakeoil:9009/sonar/api/resources?resource=com.snakeoil.digital:artiname&metrics=ncloc,coverage

**Comment by equick** [comment]
This could probably be cleaned up but the following patch is working for me with Sonar 5.6 now. Instead of 498 projects, I receive around 9531 projects.
```
$ diff -u DefaultSonarClient.java.orig DefaultSonarClient.java
--- DefaultSonarClient.java.orig        2017-09-25 20:32:15.501017680 +0100
+++ DefaultSonarClient.java     2017-09-25 22:21:11.128801784 +0100
@@ -34,11 +34,13 @@
 public class DefaultSonarClient implements SonarClient {
     private static final Log LOG = LogFactory.getLog(DefaultSonarClient.class);

-    private static final String URL_RESOURCES = "/api/resources?format=json";
+    private static final String URL_PROJECTS = "/api/projects/index?format=json";
+    //private static final String URL_RESOURCES = "/api/resources?format=json";
     private static final String URL_RESOURCE_DETAILS = "/api/resources?format=json&resource=%s&metrics=%s&includealerts=true";

     private static final String DATE_FORMAT = "yyyy-MM-dd'T'HH:mm:ssZ";
     private static final String ID = "id";
+    private static final String FIVESIX_NAME = "nm";
     private static final String NAME = "name";
     private static final String KEY = "key";
     private static final String VERSION = "version";
@@ -65,7 +67,7 @@
     @Override
     public List<SonarProject> getProjects(String instanceUrl) {
         List<SonarProject> projects = new ArrayList<>();
-        String url = instanceUrl + URL_RESOURCES;
+        String url = instanceUrl + URL_PROJECTS;

         try {

@@ -75,7 +77,9 @@
                 SonarProject project = new SonarProject();
                 project.setInstanceUrl(instanceUrl);
                 project.setProjectId(str(prjData, ID));
-                project.setProjectName(str(prjData, NAME));
+                project.setProjectName(str(prjData, FIVESIX_NAME));
                 projects.add(project);
             }
```
