### ISSUE TITLE
UI docker does not reflect the new changes made to github private repo

### ISSUE THREAD

**Issue by vparupal** [capitalone/Hygieia#1728]
Hello,

I have been trying to use the docker to spin my UI for Hygieia. I was able to use the dashboard but the docker I am using now only has the public repository version and does not include the user credentialing for a private user.

please explain on how to proceed from here. Thes ticket number for the fix is #835 @satishc1 @tabladrum @pravsingh

**Comment by Sbrenthughes** [comment]
Are you running the github collector?

**Comment by vparupal** [comment]
I am using the git hub image available and it does not run into any error. with the present image we are only able to access the public repos, I was hoping that the image was updated so that it has the credentialing in ti to access private repos as well  @Sbrenthughes

**Comment by Sbrenthughes** [comment]
So when you add the credentials to the widget for the private repo and when the collector runs you are not seeing any issues in the logs?

**Comment by asg247** [comment]
@vparupal  you can set the user credential for github private repo on the Configure Code Repo Widget. You will also need to generate a secret key to encrypt the github password and add it to api.properties and github.properties or add them to docker-compose.yml

![key](https://user-images.githubusercontent.com/14249536/31396779-59e9f708-adb2-11e7-8700-5a845094d444.png)

**Comment by Sbrenthughes** [comment]
@vparupal If this is still an issue please reopen.
