### ISSUE TITLE
Hygieia-Jenkins plugin question

### ISSUE THREAD

**Issue by kavalpatel15** [capitalone/Hygieia#1738]
Hi all,
I had a question about the Hygieia-Jenkins plugin. During setup on the Jenkins machine you provide it with a Hygieia API url so the plugin knows where to push the data. I have multiple teams on a single jenkins machine and they each want to  stand up their own instance of the Hygieia Dashboard. Is there a way to provide multiple Hygieia API urls on one jenkins machine?

thanks!

**Comment by nitin1706** [comment]
@kavalpatel15 : what do you mean by own instance of Hygieia Dashboard. Do you mean own dashboard or own instance of Hygieia stack (api, DB, and UI).

**Comment by kavalpatel15** [comment]
They would like their own instance of the ygieia stack.

**Comment by nitin1706** [comment]
It will not be possible to send data to multiple Hygieia instances from same jenkins server. 
Hygieia-Jenkins plugin is configured at Jenkins server level and it can send data only to one Hygieia instance.
