### ISSUE TITLE
support mongo 2.6

### ISSUE THREAD

**Issue by jdamick** [capitalone/Hygieia#174]
Upgraded to use 3.0 in tests and SCRAM-SHA-1, but need to support legacy installations on 2.6 and MONGODB-CR.

**Comment by jdamick** [comment]
only supporting 3.0+

**Comment by yqbjtu** [comment]
@jdamick ,  I download the Hygieia.zip  on Nov 17, and use mongoDB 2.6.9,  although API/UI can work,  Jenkins collector works well, but there is no build job to select when configuring the build widget.   Could you give some tips?  upgrade the monogDB or other ways.  Thank you!
