### ISSUE TITLE
how to configure pipeline view in Hygieia?

### ISSUE THREAD

**Issue by tsr2017** [capitalone/Hygieia#1743]
What are the steps to configure pipeline view. It is not documented anywhere.
Please guide.

Thanks

@satishc1 @nireeshT @tabladrum

**Comment by tsr2017** [comment]
@satishc1 If I confifure jenkin's plugin w/Pipeline then will I be able to see pipeline view as well?
As mentioned here - 
http://www.capitalone.io/Hygieia/hygieia-jenkins-plugin.html#jenkins-20-w-pipeline

**Comment by nireeshT** [comment]
@tsr2017  - when you configure jenkins plugin -> post build actions -> Hygieia Publisher steps in jenkins deploy jobs, deploy artifact data is pushed to "Deploy" widget on team dashboard. Environments listed in Deploy widget are the ones listed in dropdown while configuring Pipeline.

**Comment by tsr2017** [comment]
Ok thanks @nireeshT.  Will look into this and get back to you If I face any issue.

**Comment by Sbrenthughes** [comment]
@tsr2017 Please reopen if you have any more issues.

**Comment by syedsfayaz** [comment]
@Sbrenthughes @nireeshT .   Please help.

1. I am not using any deployment tool like Xl deploy or U deploy for deployment. So I cannot configure these collectors.
2. We are using **jenkins** and **manual** process for all builds and deployments.
3. I am currently using **jenkins collector** to pull data to dashboard. But in this case I am not able to get data for pipeline. Do I need to configure "Jenkins Hyginea plugin" to configure pipeline?. Currently I don't see any data under pipeline widget. 

Note: I have added pipeline "feature.dynamicPipeline=enabled" but still i dont see any difference. 

![image](https://user-images.githubusercontent.com/26099918/38209442-4d09f69c-3669-11e8-910b-a292ff6fb566.png)

**Comment by syedsfayaz** [comment]
@rohit-rehan  In jenkins post build action you will need to configure all the details required. You can also confirm if the jenkins is pusing the data by manually loggin in to mongo DB or the api url and check if the data is present.

Note: Jenkins collector does not push all the data related to  particular job. Have you installed Hygieia jenkins plugin. 
https://github.com/Hygieia/Hygieia/tree/master/hygieia-jenkins-plugin

**Comment by syedafirdaus** [comment]
@syedsfayaz  please see my question https://github.com/Hygieia/Hygieia/issues/2105 here and advise.
