### ISSUE TITLE
Can we create service for gulp serve command

### ISSUE THREAD

**Issue by sanchitacool** [capitalone/Hygieia#1747]
Can we create service for gulp serve command so that its starts automatically without typing this command in command prompt

**Comment by nitin1706** [comment]
maybe you can create a bash script to execute this command.

**Comment by nitin1706** [comment]
Can you elaborate more on what you want to achieve? maybe you can create a bash script to execute this command.

**Comment by sanchitacool** [comment]
![1](https://user-images.githubusercontent.com/29974254/30966409-709eb33e-a476-11e7-8375-89bc97413eb8.png)

I want this type of service for gulp serve command so that no need to type this command on Command Prompt, its starts automatically as the windows service. For your reference attached Screenshot.

**Comment by nitin1706** [comment]
You can use a bash script which can help you achieve this, IMO, that would be easier to do. Or you can search for steps to create a service based on OS you are using.
