### ISSUE TITLE
AWS Cloud Collector not estimating cost

### ISSUE THREAD

**Issue by mcahill7** [capitalone/Hygieia#1751]
Right now I have the AWS Cloud Collector integration working and finding all ec2 instances however the estimated cost is $0. I'd really like to be able to use this feature. It looks like the logic that calculates the estimated cost is in the UI, is there further configuration that needs to happen to get the estimation to work?

**Comment by mcahill7** [comment]
Currently showing: Instance Count 824

   Running Count 493

   EC2 Cost/Month
   $0

   Utilization 2.8%

**Comment by matthewbeasley** [comment]
@mcahill7 - I believe we have since fixed this issue. Please pull the latest code and try again.
