### ISSUE TITLE
Dockern & Appdynamics

### ISSUE THREAD

**Issue by tsr2017** [capitalone/Hygieia#1754]
I am trying to Build Docker images and setup id for mongodb. I am following the hygieia documentation.

But when I run mvn docker:build
I am getting the error that **Hygieia/collectors/performance/appdynamics/docker does not exist** 

I checked there is no docker folder at this location on my mac.
How to resolve this?
@MarkRx , @nireeshT @satishc1

**Comment by tsr2017** [comment]
@MarkRx , @nireeshT @satishc1 . Any solution to resolve this error.
I built hygieia using **"mvn clean install package"**
before **mvn docker:build**

**Comment by asg247** [comment]
@tsr2017 PR #1674 has the changes to build docker image for appdynamics

**Comment by tsr2017** [comment]
@asg247 Has PR #1674 been merged into master? or Do I need to use different branch?

**Comment by asg247** [comment]
@tsr2017 PR has not been merged yet

**Comment by matthewbeasley** [comment]
@tsr2017 PR #1674, PR #1708 merged. Please pull the latest master and try again.
