### ISSUE TITLE
Dockerizing issue: User logs out within a minute in the UI

### ISSUE THREAD

**Issue by htvan1** [capitalone/Hygieia#1758]
JWTs are working fine. 
Variables are the same as when I was just doing compiled jars (works fine there)
AUTH_EXPIRATION_TIME=36000
My user gets logged out with a min or so of being connected.
No logs in the API output nor in the chrome console that says anything went wrong.

Anyone get this issue when switching to Docker?

**Comment by asg247** [comment]
@htvan1  increase the AUTH_EXPIRATION_TIME value to 720000.

**Comment by htvan1** [comment]
Thanks @asg247 !!! Worked like a charm.
