### ISSUE TITLE
Collector Permissions Documented?

### ISSUE THREAD

**Issue by anutting** [capitalone/Hygieia#1759]
Hi Everyone,

I've have my Hygieia environment up in running, now it's just a matter of configuring the collectors to work with our systems. I'm curious if there's any documentation on what the collectors actually need permissions-wise from their respective systems.

For example: My Jenkins collector has access to builds, but the log shows a 404 when accessing any information about those builds. When the Hygieia service account was created for using the Jenkins API, I did not know it needed those permissions. What else does the jenkins collector need access to?

It would be great if a contributor familiar with the collectors could document exactly what each collector is looking for when making API calls to those systems.

Thanks!

**Comment by rvema** [comment]
@anutting please gh-pages branch for each of the collectors, they should have the documentation. Closing this issue, please reopen is this is still happening.
