### ISSUE TITLE
Can we removed unconfigured widgets from Dashboard?

### ISSUE THREAD

**Issue by mrdmanohar** [capitalone/Hygieia#1761]
Hi,

  For our project , we don't need - Monitor & Deploy widgets from dashboard. Is there any way to remove them?

Thanks
Patil

**Comment by htvan1** [comment]
I was just going to go in the template and remove it in the code.  You can use the customize widget lay out but I am finding that super buggy.

**Comment by tabladrum** [comment]
@htvan1 can you point to the bugs around widget customization? Will help us to fix it. @nireeshT @satishc1

**Comment by nireeshT** [comment]
@mrdmanohar @htvan1  - Follow below steps 
1) Sign up as user - "admin"
2) Login as admin
3) Go to admin-> settings ( which is gear next to user name once logged in) 
4) Click Manage templates 
5) Create new template -> Name template and select widgets for template. In your case you can exclude Monitor and Deploy 
6) Save 
7) Go to Hygieia landing page-> Create new Dashboard 
8) Select From Templates option 
9) Select custom created template from drop down. 
10) Save dashboard. 

Let me know if you see any issues.

**Comment by htvan1** [comment]
@nireeshT 
I really like the idea of this feature, but I am finding a lot of bugs.  
2 issues can be seen here, widgets not sizing as I tell them to in the template and 2 of my widgets dont even show up...  If I do a standard size 3x3 and dont touch the layout it works BUT the widget info does not really fit in that space. 
![screen shot 2017-10-06 at 9 55 58 am](https://user-images.githubusercontent.com/23086265/31289231-ef98c696-aa7c-11e7-90cb-735217165b1c.png)
![screen shot 2017-10-06 at 9 56 28 am](https://user-images.githubusercontent.com/23086265/31289239-f45733ac-aa7c-11e7-9cf3-3edc3d655f27.png)
![screen shot 2017-10-06 at 9 57 16 am](https://user-images.githubusercontent.com/23086265/31289245-f7e84fd8-aa7c-11e7-8c02-314a8b4f1c80.png)

**Comment by nireeshT** [comment]
@htvan1  - resizing feature is work in progress. For now you can only select the widgets and choose its order.

**Comment by htvan1** [comment]
@nireeshT  the templates do not use those sizes.  Half of the widgets are too squished (thus messing with the charts), a nice mean time fix would be to make the default size of a given widget the same as the size in the cap one templates.

**Comment by nireeshT** [comment]
@htvan1  you can choose to create dashboard using templates(Capone template) instead of selecting widgets.

**Comment by htvan1** [comment]
@nireeshT  to my knowledge we can't remove a widget from a template on the UI.
We like the cap one template but do not use the monitor widget.  There is another template and it has a chat widget we do not use.   If you have an easy guide to modifying those templates in the code that would work for me too.

**Comment by nireeshT** [comment]
@htvan1 - as a quick workaround go to Capone.html and remove line of code containing <widget name =“monitor” >

**Comment by nireeshT** [comment]
@htvan1 containing widget name = monitor
