### ISSUE TITLE
Cannot create dashboard after logging in 

### ISSUE THREAD

**Issue by hemantanna555** [capitalone/Hygieia#1763]
The log in for me works fine, (atleast does not show any errors) and the entires are fed into mongodb. However, the top right hand corner still shows 'login' and not my username. And then I cannot see any option to create the dashboard. 
It all worked yesterday but unfortunately showed this strange behaviour today
<img width="1233" alt="screen shot 2017-10-04 at 12 03 15 pm" src="https://user-images.githubusercontent.com/32518985/31186247-1b9c62d4-a8fc-11e7-825b-e83f7991e772.png">

Here are my dashboard properties

dashboard.properties
dbname=dashboard
#dbusername=[MogoDb Database Username, defaults to empty]
#dbpassword=[MongoDb Database Password, defaults to empty]
dbhost=localhost
dbport=27017
#dbreplicaset=[false if you are not using MongoDB replicaset]
#dbhostport=[host1:port1,host2:port2,host3:port3]
#server.contextPath=[Web Context path if any]
server.port=8088
logRequest=false
logSplunkRequest=false
corsEnabled=false
#corsWhitelist=http://domain1.com:port,http://domain2.com:port
#version.number=@application.version.number@

auth.expirationTime=1000
#auth.secret=[Secret Key used to validate the JWT tokens]
#auth.authenticationProviders=[Authentication types you would like to enable, defaults to STANDARD, ex: STANDARD,LDAP]
#auth.ldapServerUrl=[LDAP Server Url, including port of your LDAP server]
#auth.ldapUserDnPattern=[LDAP User Dn Pattern, where the username is replaced with '{0}']

# LDAP Server Url, including port of your LDAP server
#auth.ldapServerUrl=[ldap://company.com:389]

# If using standard ldap
# LDAP User Dn Pattern, where the username is replaced with '{0}'
#auth.ldapUserDnPattern=[uid={0},OU=Users,dc=your,dc=company,dc=com]

# If using ActiveDirectory
# This will be the domain part of your userPrincipalName
#auth.adDomain=[company.com]
# This will be your root dn
#auth.adRootDn=[dc=your,dc=company,dc=com]
# This will be your active directory url (required for AD)
auth.adUrl=[Need an example]

#monitor.proxy.host=[hostname of proxy server]
#monitor.proxy.type=[http|socks|direct]
#monitor.proxy.port=[port enabled on proxy server]
#monitor.proxy.username=[proxy username]
#monitor.proxy.password=[proxy password]

Used this command to run the api 
java -jar api.jar --spring.config.location=dashboard.properties -Djasypt.encryptor.password=hygieiasecret

**Comment by hemantanna555** [comment]
I suspect something to do with the timeouts for jwt? 

I do see the api connectivity as successful

**Comment by hemantanna555** [comment]
<img width="1243" alt="screen shot 2017-10-04 at 12 07 34 pm" src="https://user-images.githubusercontent.com/32518985/31186444-aa934d9a-a8fc-11e7-915e-aed18451b35e.png">

**Comment by hemantanna555** [comment]
c.c.dashboard.auth.AuthProperties - No JWT expiration time found in configuration, setting to one day.

This seems to be an issue?

**Comment by Sbrenthughes** [comment]
You'll need:
`server.contextPath=/api`

You may have some trouble with changing the port to 8088. Is it possible to leave it at 8080 until we get it working?

**Comment by hemantanna555** [comment]
Thanks for the reply.

I changed it to 8088 hoping it will work there. Initial tries failed on
8080.

**Comment by Sbrenthughes** [comment]
Also, can you verify that 
` --spring.config.location=dashboard.properties`
is the actual path to your dashboard.properties file? For example,
` --spring.config.location=path_to_file/dashboard.properties`

**Comment by nireeshT** [comment]
@hemantanna555  - launch UI in chrome incognito and see if that fixes it

**Comment by hemantanna555** [comment]
Hi. Launched UI in every browser. Did not work.

My proerties file is in the same location as the api.

I am more inclined towards it being a JWt issue which expired after a day

**Comment by nireeshT** [comment]
@hemantanna555  - remove this attribute from prop file  or set it to high value. 

auth.expirationTime=1000

**Comment by hemantanna555** [comment]
Thank you. Will try that

**Comment by Sbrenthughes** [comment]
@hemantanna555 Any update on your issue?

**Comment by hemantanna555** [comment]
This works now. Thank you so much

**Comment by harish123321** [comment]
I tried without keeping that property but still I am getting the same error. can you please help me out.

**Comment by Sbrenthughes** [comment]
@harish123321 please open a new issue if you are experiencing issues
