### ISSUE TITLE
Bower Install Failing 

### ISSUE THREAD

**Issue by shabna96** [capitalone/Hygieia#1767]
I am getting the below error 
![image](https://user-images.githubusercontent.com/20172976/31281737-4c22adb8-aa7e-11e7-8051-38ade59712f9.png)
I have tried all solutions available over Stackoverflow or Issue #226 with no luck
I have another workspace with different branch and everything was working fine there,I was able to install bower and bring up the UI. Please help me understand why I am facing issue now.

**Comment by Sbrenthughes** [comment]
What command did you use?

**Comment by shabna96** [comment]
I used 'bower install'

**Comment by shabna96** [comment]
It is fixed with latest code,I was working with older version
