### ISSUE TITLE
API doesn't fetch sprint status data instantly - Feature

### ISSUE THREAD

**Issue by pasan96** [capitalone/Hygieia#1772]
When a sprint is started with the current date and time given for starting date/time in JIRA, the collector updates the issues in database including sprint start and end dates, but the API does not return that data. But when I start a sprint with a past date/time, it returns the data instantly. I assume that it's an issue with the API's date/time comparison..

**Comment by anuradha92** [comment]
I got the same error. in API  use the UTC time how to fix that. it's working after changing the time but its not the correct way.how to fix it?

**Comment by pasan96** [comment]
Found the reason, the JIRA API always sends UTC time, when the JIRA collector stores data in the DB it converts the time to local system's time. You can change that from the collector.
