### ISSUE TITLE
How to make  same widgets type  getting data separately 

### ISSUE THREAD

**Issue by samyzemmouri** [capitalone/Hygieia#1778]
I want to duplicate the build widget ( jenkins )  in the same dashboard but i want them to gather data separately. should i duplicate the same collector or i have to change the API too?!

**Comment by nitin1706** [comment]
As of now, this feature is not supported. Work on 'multiple widgets of same type' is in progress. It would be re-leased with main branch code in upcoming releases.

**Comment by samyzemmouri** [comment]
could you give me a  hint on how to do that ?
