### ISSUE TITLE
build the UI has error

### ISSUE THREAD

**Issue by yqbjtu** [capitalone/Hygieia#178]
when executing the mvn clean install package for the UI, it reports the following error:
78 silly gentlyRm purging /home/xx/Downloads/Hygieia-master/UI/node_modules/.bin/karma
79 verbose stack Error: EACCES, unlink '/home/xx/Downloads/Hygieia-master/UI/node_modules/.bin/karma'
79 verbose stack     at Error (native)
80 verbose cwd /home/xx/Downloads/Hygieia-master/UI
81 error Linux 3.19.0-25-generic
82 error argv "/home/xx/Downloads/Hygieia-master/UI/node/node" "/home/xx/Downloads/Hygieia-master/UI/node/node_modules/npm/bin/npm-cli.js" "install" "--color=false"
83 error node v0.12.0
84 error npm  v2.7.1
85 error path /home/xx/Downloads/Hygieia-master/UI/node_modules/.bin/karma
86 error code EACCES
87 error errno -13
88 error Error: EACCES, unlink '/home/xx/Downloads/Hygieia-master/UI/node_modules/.bin/karma'
88 error     at Error (native)
88 error  { [Error: EACCES, unlink '/home/xx/Downloads/Hygieia-master/UI/node_modules/.bin/karma']
88 error   errno: -13,
88 error   code: 'EACCES',
88 error   path: '/home/xx/Downloads/Hygieia-master/UI/node_modules/.bin/karma' }
89 error Please try running this command again as root/Administrator

When I use root,  the bower install will report
[INFO] --- frontend-maven-plugin:0.0.25:bower (bower install) @ UI ---
[INFO] Running 'bower install' in /home/xx/Downloads/Hygieia-master/UI
[ERROR] bower ESUDO         Cannot be run with sudo
[ERROR] 
[ERROR] Additional error details:
[ERROR] Since bower is a user command, there is no need to execute it with superuser permissions.
[ERROR] If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.
[ERROR] 
[ERROR] http://www.joyent.com/blog/installing-node-and-npm
[ERROR] https://gist.github.com/isaacs/579814
[ERROR] 
[ERROR] You can however run a command with sudo using --allow-root option
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27.945 s
[INFO] Finished at: 2015-11-23T13:27:00+08:00
[INFO] Final Memory: 20M/136M

**Comment by jdamick** [comment]
this on mac or linux?
