### ISSUE TITLE
importing BB projects into Hygieia team dashboard.

### ISSUE THREAD

**Issue by tpetrisk** [capitalone/Hygieia#1783]
Hi Team 

instead of going into the team dashboard and creating a new dashboard for each of my Bitbucket projects repo and branches. is there a automated way this can be done? if so how. 

Also are there any more detail documentation other that http://www.capitalone.io/Hygieia/getting_started.html that goes into more details? 

TIA 
Tim

**Comment by Megha849** [comment]
@tpetrisk Dashboard Configuration details are available at: http://www.capitalone.io/Hygieia/Introduction.html

**Comment by Sbrenthughes** [comment]
@tpetrisk along with Megha849 documentation link, we will be adding documentation how the ability to use the remote dashboard creation api, in the future. Stay tuned.
