### ISSUE TITLE
Docker-compose sonar collector fails - 'sonarCollectorTask':..  java.lang.NumberFormatException: For input string: ""

### ISSUE THREAD

**Issue by ionitadaniel19** [capitalone/Hygieia#1784]
Error : 
          | Caused by: java.lang.NumberFormatException: For input string: ""
hygieia-sonar-codequality                 |     at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
hygieia-sonar-codequality                 |     at java.lang.Integer.parseInt(Integer.java:592)
......
hygieia-sonar-codequality                 |     at org.springframework.scheduling.support.CronTrigger.<init>(CronTrigger.java:44)
hygieia-sonar-codequality                 |     at com.capitalone.dashboard.collector.CollectorTask.onStartup(CollectorTask.java:73)

Properties file generated in container is:

hygieia-sonar-codequality                 | #Database Name
hygieia-sonar-codequality                 | dbname=dashboarddb
hygieia-sonar-codequality                 |
hygieia-sonar-codequality                 | #Database HostName - default is localhost
hygieia-sonar-codequality                 | dbhost=172. ....
hygieia-sonar-codequality                 |
hygieia-sonar-codequality                 | #Database Port - default is 27017
hygieia-sonar-codequality                 | dbport=27017
hygieia-sonar-codequality                 |
hygieia-sonar-codequality                 | #Database Username - default is blank
hygieia-sonar-codequality                 | dbusername=db
hygieia-sonar-codequality                 |
hygieia-sonar-codequality                 |
hygieia-sonar-codequality                 | #Collector schedule (required)
hygieia-sonar-codequality                 | sonar.cron=0 /5 * * * *
hygieia-sonar-codequality                 |
hygieia-sonar-codequality                 | sonar.servers[0]=http://....
hygieia-sonar-codequality                 |
hygieia-sonar-codequality                 | #Sonar Authentication Username - default is blank
hygieia-sonar-codequality                 | sonar.username= ....
hygieia-sonar-codequality                 |
hygieia-sonar-codequality                 |
hygieia-sonar-codequality                 | #Sonar Metrics
hygieia-sonar-codequality                 | sonar.metrics[0]=ncloc,line_coverage,violations,critical_violations,major_violations,blocker_violations,sqale_index,test_success_density,test_failures,test_errors,tests
hygieia-sonar-codequality                 |
hygieia-sonar-codequality                 | #Sonar Version - see above for semantics between version/metrics
hygieia-sonar-codequality                 | sonar.versions[0]=5

**Comment by nitin1706** [comment]
please share your sonar properties file.

**Comment by ionitadaniel19** [comment]
Problem solved.
