### ISSUE TITLE
Disable authentication, or use local DB authentication instead of LDAP/AD?

### ISSUE THREAD

**Issue by maciejmakowski** [capitalone/Hygieia#1788]
I'm trying to get a local prototype going, and I'd prefer to either disable the authentication altogether, or have it at least running from the local database instead of LDAP/AD. Is that easily doable? Documented anywhere?

There's a signup screen in the UI, so I'm assuming this should work somehow?

![image](https://user-images.githubusercontent.com/1946435/31848064-70808872-b5de-11e7-893f-93dfafc65b19.png)

Thanks in advance for any pointers.

**Comment by maciejmakowski** [comment]
@satishc1, @amitmawkin - Could someone take a look please?

**Comment by maciejmakowski** [comment]
@nireeshT - can you maybe take a look?

**Comment by Sbrenthughes** [comment]
You can create a user for your local without using LDAP. Hygieia needs users to be able to create dashboards etc. Once you create a dashboard you can view the dashboard without logging in. I am not sure I understand what you are going for by disabling auth?

**Comment by maciejmakowski** [comment]
How do I go about creating an user? In the version that I have tried to get running, I don't see an option to create an user. Not a working one anyhow.

Or did you mean I should create an user straight through the database?

It was my impression that Hygieia mainly works via LDAP, and that's why I did not go down the path of creating (local) users any further.

Are there generally any docs that explain the setup / admin stuff in more detail?

**Comment by Sbrenthughes** [comment]
Are you not able to create a user using the sign up option from your create shot?

**Comment by maciejmakowski** [comment]
Nope, does not work. Just loops around doing nothing essentially, just displaying the error above.

Ok, so in general, this should "just work"?

I will have to go back and somehow get this thing to fire up again, cause I also tried to play with HygieiaLight (https://github.com/pravsingh/HygieiaLight/), and that seems to have broken everything to the point where I don't even get the login screen shown on the screenshot.

Are there any more comprehensive "admin docs" for this? Cause what I was able to find so far does not explain all that much, and is partially even flat out wrong / contradicting.

Also, if I may ask, do you work for Capital1, or are you at another company that is just using this?

**Comment by Sbrenthughes** [comment]
I don't see a username in the image above. We will be pushing out more technical docs over the coming weeks.

**Comment by maciejmakowski** [comment]
Yeah, I typed the username in, password too, and pressed "sign up". It looped around, wiped out the username, and said that the username is required.

Is the latest snapshot supposed to be stable? Cause that's what I was using. The latest release is quite old.

It would be helpful if you could get the latest stable version into docker, and have a docker compose along the lines of what HygieiaLight is offering.

**Comment by Sbrenthughes** [comment]
Is there any error in the API log when you try that. There are plans to get all the docker components updated.
