### ISSUE TITLE
I start API/UI/jenkins collector. but can find any build job in the dashboard build setting

### ISSUE THREAD

**Issue by yqbjtu** [capitalone/Hygieia#179]
in "Config Build widget"  ,can't find any build job, although my jenkins collector works well.

how to add a build job,  My api port is 8080 and its context is /api, but when I access to http://127.0.0.1:8080/api,  there is no any thing showing.

**Comment by hongluovz** [comment]
you possible can find something at Http://127.0.0.1:8080/api/dashboard. I found a json file when start api.jar from commandline.

However, when I started them via docker-compose, I can't get anything

**Comment by amitmawkin** [comment]
no response , assuming this issue does not exist anymore
