### ISSUE TITLE
Role based access in UI Dashboard

### ISSUE THREAD

**Issue by sraghu-rs** [capitalone/Hygieia#1790]
Is there anyway we can setup Role based access to Dashboard. Right now, people can see the dashboard/widgets without signup to dashboard.

We want to restrict the visibility of the dashboard/widgets based on Role like Product Manager, Team Lead, Developer and so on.

Is this something possible in Hygieia Dashboard?If yes, can you please guide me.

Regards,
Raghav

**Comment by nireeshT** [comment]
@sraghu-rs  - Only two roles available at present - ViewOnly and Owner. Admin and owner of dashboard can add multiple owners for a dashboard. If you want to restrict view for All Dashboards, you have to do a work around in code. 

In site.html add ng-show="ctrl.showAuthentication" on below LOC 

 <div class="gap" ng-show="ctrl.showAuthentication">
                            <div class="text-2x">All Dashboards</span></div>

**Comment by kagasa** [comment]
@nireeshT  --
the suggestion you had given is to add above code
Only two roles available at present - ViewOnly and Owner. Admin and owner of dashboard can add multiple owners for a dashboard. If you want to restrict view for All Dashboards, you have to do a work around in code.
In site.html add ng-show="ctrl.showAuthentication" on below LOC
works only when logout
If i create a new user with no access and after login he is able to see all dashboard in readonly mode
which i want to ristrict
pls your inputs on the same

**Comment by chaitanya4419** [comment]
Even i have the same requirement, 

I want to restrict few dashboard to only three users and other few dashboards to other 2 developers using concept like team or any other concept.

any idea ?
