### ISSUE TITLE
Error in pom.xml

### ISSUE THREAD

**Issue by Pikkurthi** [capitalone/Hygieia#1795]
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-pmd-plugin:3.6:check (execution: default, phase: validate)

<parent>
        <groupId>com.capitalone.dashboard</groupId>
        <artifactId>Hygieia</artifactId>
        <version>2.0.5-SNAPSHOT</version>
    </parent>

How to fix this issue?

**Comment by maciejmakowski** [comment]
is that from the command line or from your IDE?

**Comment by nireeshT** [comment]
@Pikkurthi  Please share complete log.

**Comment by hoanmac-wawanesa** [comment]
From the IDE.

**Comment by Sbrenthughes** [comment]
can you try from the command line and share the full log?

**Comment by Sbrenthughes** [comment]
Please reopen if still an issue.
