### ISSUE TITLE
https://github.com/capitalone/Hygieia/tree/master/BuildCollector  link does not exist

### ISSUE THREAD

**Issue by yqbjtu** [capitalone/Hygieia#180]
when click the jenkins from https://github.com/capitalone/Hygieia/blob/master/Setup.md, it will redirect to https://github.com/capitalone/Hygieia/tree/master/BuildCollector, but this page does not exist,  it shows 404 error,  Could anyone correct it?   Thank you

**Comment by amitmawkin** [comment]
We renamed few of our projects, and obviously the document update is lagging i wil fix it but the actual url is https://github.com/capitalone/Hygieia/tree/master/jenkins-build-collector

**Comment by amitmawkin** [comment]
fixed via PR #177
