### ISSUE TITLE
https://localhost:8080/api  giving error in Hygieia-jenkins plugin configuration

### ISSUE THREAD

**Issue by ameetsvshah** [capitalone/Hygieia#1810]
I am trying to set up the Hygieia-Jenkins plugin but 
Manage Jenkins > Configure System > Hygieia Publisher Settings
Hygieia Server URL is http://localhost:8080/api/ is giving failure on "Test Connection".
I have set the Proxy settings.
 When we hit this https://localhost:8080/api in browser getting the following error.
"Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Nov 02 09:20:02 EDT 2017
There was an unexpected error (type=Not Found, status=404).
No message available"

Can you please help here.
Thanks in advance.

**Comment by nireeshT** [comment]
@ameetsvshah  remove "/" at the end, use http://localhost:8080/api

**Comment by Sbrenthughes** [comment]
@ameetsvshah Please reopen if you are still having issues.

**Comment by aishwaryamv123** [comment]
I am facing similar issue, api log says connected to mongodb on port 27017, but localhost:8090/api/ping doesn't return true and give me a whitelabel error message page.
UI says red on api connectivity. It was working well earlier suddenly it isnt working, Can someone please help me with this/if any faced same ??

**Comment by Rajeswa** [comment]
@nireeshT,@tabladrum - I am facing issue in API - UI connectivity. API instance is running and am getting the response (response as true) when I hit http://localhost:8081/api/ping. I have deployed UI via gulp serve command and in the UI page its showing as no API connectivity. When I try to hit http://localhost:8081/api/dashboard, am getting empty json. From the API logs, I saw it has established connection to mongodb successfully. Can you help me to sort out this? 

I have built the entire project successfully that I have cloned from GitHub. Mongodb,npm,bower installation  -> successful. No error message in api log. 

GET method http://localhost:8081/api/authenticationProviders & http://localhost:8081/api/appinfo returns 404 page not found response
