### ISSUE TITLE
Question: Will using the Jenkins pull collector and push collector (plugin) together cause issues

### ISSUE THREAD

**Issue by kwhickey** [capitalone/Hygieia#1813]
I'm wondering if we need to chose _just one_ of the Jenkins collectors to use. We currently have a pull-based collector running, and we also have the Hygieia Jenkins Plugin on our Jenkins which is _pushing_ data to the Hygieia API.

_**Will having both collectors running at the same time cause problems with the data in mongo or with the widgets' interpretation of that data**_

If so, _**are there any features missing from the push-based collector that would make it incomplete to run on its own?**_ iow Does it matter which one you pick if you pick just one?

I'm mostly wondering if there are *known* issues when working with both. I've seen some issues when experimenting. 

One of the issues I have noticed is that Jenkins jobs will be _listed twice_ in the Jenkins widget, and you have to do some HTML inspection or trial-and-error to figure out which one you want.  

Also, there may have been some care needed when setting up the Product Dashboard, in that it needed to incorporate a Team Dashboard that was tracking a push vs. pull Jenkins collector, so that when it went and queried for commits, it was getting commits put into mongo by the right collector.
 
During demos, the pull collector also doesn't update very frequently if you're trying to demo the Product Dashboard's pipeline widget moving commits along.

FYI Some of the info about push/pull was gathered here: http://www.capitalone.io/Hygieia/hygieia-jenkins-plugin.html
Thanks.

**Comment by matthewbeasley** [comment]
@kwhickey - you can run one or the other or both. It doesn't matter.
