### ISSUE TITLE
Getting Error while building (mvn install)

### ISSUE THREAD

**Issue by gladsysamuel** [capitalone/Hygieia#1815]
INFO] com.capitalone.dashboard:versionone-feature-collector  SUCCESS [2.417s]
[INFO] com.capitalone.dashboard:gitlab-feature-collector . SUCCESS [3.078s]
[INFO] com.capitalone.dashboard:chat-ops-collector ....... SUCCESS [0.465s]
[INFO] com.capitalone.dashboard:appdynamics-performance-collector  SUCCESS [2.237s]
[INFO] com.capitalone.dashboard:bitbucket-scm-collector .. SUCCESS [2.015s]
[INFO] com.capitalone.dashboard:github-scm-collector ..... SUCCESS [2.148s]
[INFO] com.capitalone.dashboard:subversion-collector ..... SUCCESS [0.514s]
[INFO] com.capitalone.dashboard:gitlab-scm-collector ..... SUCCESS [2.479s]
[INFO] com.capitalone.dashboard:hpsm-cmdb-collector ...... SUCCESS [2.782s]
[INFO] com.capitalone.dashboard:nexus-iq-collector ....... SUCCESS [2.646s]
[INFO] Hygieia Publisher Plugin .......................... SUCCESS [23.528s]
[INFO] com.capitalone.dashboard:UI ....................... FAILURE [0.022s]
[INFO] com.capitalone.dashboard:ui-tests ................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3:03.684s
[INFO] Finished at: Fri Nov 03 07:27:21 EDT 2017
[INFO] Final Memory: 108M/785M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.29:install-node-and-npm (install node and npm) on project UI: The plugin com.github.eirslett:frontend-maven-plugin:0.0.29 requires Maven version 3.1.0 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginIncompatibleException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

Kindly Give steps to resolve  it.

**Comment by nireeshT** [comment]
@gladsysamuel  which version of maven you are running on ? use Maven 3.1.0 or higher

**Comment by Sbrenthughes** [comment]
Duplicate issue https://github.com/capitalone/Hygieia/issues/1817
