### ISSUE TITLE
How to Create Custom Collector Front End

### ISSUE THREAD

**Issue by Matt-Ackerman** [capitalone/Hygieia#1819]
Just curious if there is any documentation or tutorials for creating the front end portion of a custom collector (UI, Widget, Controller, data-factory, etc).

I currently have a custom collector that works properly and stores data in MongoDB but am having a tough time figuring out how to display that data on the dashboard.

I have looked through https://github.com/capitalone/Hygieia/issues/733 and other issues but nothing has helped.

Thanks!

**Comment by Matt-Ackerman** [comment]
😞

**Comment by Sbrenthughes** [comment]
Currently we do not have any tutorials on how to create widgets.
