### ISSUE TITLE
unable to build api jar

### ISSUE THREAD

**Issue by mallsjr** [capitalone/Hygieia#182]
Running the command "mvn install" to build the api jar gives the following error.

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:58 min
[INFO] Finished at: 2015-11-23T09:41:25-05:00
[INFO] Final Memory: 6M/15M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project api: Could not resolve dependencies fo
r project com.capitalone.dashboard:api:jar:1.5.0-SNAPSHOT: Could not find artifa
ct com.capitalone.dashboard:core:jar:1.5.0-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException

**Comment by amitmawkin** [comment]
you would need core first,  i would recommend you run the master pom with command
<code>mvn clean compile install package </code>
 in the root of the directory. Also make sure you have connection to the internet.

**Comment by mallsjr** [comment]
I just tried doing as you said and the build failed again. Can I not run
Hygieia from a windows machine?

On Mon, Nov 23, 2015 at 10:22 AM, Amit Mawkin <notifications@github.com>
wrote:

> you would need core first, i would recommend you run the master pom with
> command
> mvn clean compile install package
> in the root of the directory. Also make sure you have connection to the
> internet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/capitalone/Hygieia/issues/182#issuecomment-158966788>.
>



-- 
Michael Alls

**Comment by mallsjr** [comment]
While running the mvn clean compile install package command the build fails to compile the core due to test failures. Any idea what could be  causing the tests to fail?

**Comment by oshingc** [comment]
You have to run first core project with mvn install package then mvn install package at the level of Hygieia and then everything will work.

**Comment by tabladrum** [comment]
@mallsjr do you still have this issue? If not can you close this?

**Comment by amitmawkin** [comment]
no response, assuming the issue does not exist any more
