### ISSUE TITLE
Hygieia build publish not working with pipeline as code for failed builds

### ISSUE THREAD

**Issue by arjunnayak11** [capitalone/Hygieia#1820]
I am trying to include hygieia in the pipeline code to capture the build status. I noticed that It is displaying only the success results and not the failure ones. I also saw some other related issues in this community, has this issue been resolved ...?? Please let me know if there is a solution for this.

**Comment by nireeshT** [comment]
@arjunnayak11  Yes, it will show success and failure builds.
