### ISSUE TITLE
project UI: Failed to run task: 'gulp.js build' failed.

### ISSUE THREAD

**Issue by gladsysamuel** [capitalone/Hygieia#1826]
[INFO] Reactor Summary:
[INFO]
[INFO] com.capitalone.dashboard:Hygieia ................... SUCCESS [  0.611 s]
[INFO] com.capitalone.dashboard:core ...................... SUCCESS [ 18.028 s]
[INFO] com.capitalone.dashboard:api ....................... SUCCESS [ 15.469 s]
[INFO] com.capitalone.dashboard:api-audit ................. SUCCESS [  4.259 s]
[INFO] com.capitalone.dashboard:artifactory-artifact-collector SUCCESS [  3.201 s]
[INFO] com.capitalone.dashboard:bamboo-build-collector .... SUCCESS [  2.690 s]
[INFO] com.capitalone.dashboard:jenkins-build-collector ... SUCCESS [  3.478 s]
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SUCCESS [  2.784 s]
[INFO] com.capitalone.dashboard:jenkins-codequality ....... SUCCESS [  4.205 s]
[INFO] com.capitalone.dashboard:sonar-codequality-collector SUCCESS [  2.597 s]
[INFO] com.capitalone.dashboard:aws-cloud-collector ....... SUCCESS [  0.835 s]
[INFO] com.capitalone.dashboard:udeploy-deployment-collector SUCCESS [  2.702 s]
[INFO] com.capitalone.dashboard:xldeploy-deployment-collector SUCCESS [  3.357 s]
[INFO] com.capitalone.dashboard:jira-feature-collector .... SUCCESS [  5.634 s]
[INFO] com.capitalone.dashboard:versionone-feature-collector SUCCESS [  2.141 s]
[INFO] com.capitalone.dashboard:gitlab-feature-collector .. SUCCESS [  3.410 s]
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SUCCESS [  0.618 s]
[INFO] com.capitalone.dashboard:appdynamics-performance-collector SUCCESS [  2.643 s]
[INFO] com.capitalone.dashboard:bitbucket-scm-collector ... SUCCESS [  2.488 s]
[INFO] com.capitalone.dashboard:github-scm-collector ...... SUCCESS [  3.016 s]
[INFO] com.capitalone.dashboard:subversion-collector ...... SUCCESS [  1.037 s]
[INFO] com.capitalone.dashboard:gitlab-scm-collector ...... SUCCESS [  3.611 s]
[INFO] com.capitalone.dashboard:hpsm-cmdb-collector ....... SUCCESS [  3.137 s]
[INFO] com.capitalone.dashboard:nexus-iq-collector ........ SUCCESS [  2.571 s]
[INFO] Hygieia Publisher Plugin ........................... SUCCESS [ 22.015 s]
[INFO] com.capitalone.dashboard:UI ........................ FAILURE [ 16.155 s]
[INFO] com.capitalone.dashboard:ui-tests .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:14 min
[INFO] Finished at: 2017-11-08T06:41:48-05:00
[INFO] Final Memory: 156M/771M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.29:gulp (gulp build) on project UI: Failed to run task: 'gulp.js build' failed. (error code 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :UI

gulp.js build failed

**Comment by gladsysamuel** [comment]
Can somebody help with this.

**Comment by Sbrenthughes** [comment]
can you show the error log?

**Comment by gladsysamuel** [comment]
That issue is cleared now. 
Thanks.
![capture hygieia dashboard](https://user-images.githubusercontent.com/32176286/32784400-bef48e1e-c974-11e7-82a4-3045f24c20d6.PNG)

Hygieia Dashboard having issue. Login isn't coming.

**Comment by Sbrenthughes** [comment]
You have a issue for that open. We will respond when we can. Closing this one.

**Comment by Dhruva231** [comment]
How did you resolved the issue, I am also facing the same issue.

**Comment by gladsysamuel** [comment]
are you facing the gulp.js issue or hygieia dashboard issue?

**Comment by Dhruva231** [comment]
my dashboard says, api connected, even I ran collectors.. but collectors are not dispalying in dashboard.
please suggest me how to run collectors, I am getting [] symbols in <hostname: port num>/api/dashboard.

Please help me on this

**Comment by vwyuheng** [comment]
I am also facing the same issue. facing the gulp.js issue

**Comment by Sbrenthughes** [comment]
@Dhruva231 open an issue related to your problem. @vwyuheng can you post the log of the failure?
