### ISSUE TITLE
404 Error when fetching build details

### ISSUE THREAD

**Issue by ikfas** [capitalone/Hygieia#1827]
Hi! 
I configured my Db server, Api and UI and everything seems to work fine but when it tries to fetch data it keeps returning: 

ERROR c.c.d.collector.DefaultHudsonClient - Client exception loading build details: 404 Not Found. URL =http://localhost:8000/job/project/2/

I don't know why it tries to go to localhost:8000 even if I wrote the jenkins server address in the properties file : localhost:8080

Thanks for any help

**Comment by nireeshT** [comment]
@ikfas  share your jenkins properties file and cmd to run jenkins collector

**Comment by ikfas** [comment]
@nireeshT  Please find the application properties and the command. I run a Jenkins on localhost with port 8080, the Api with port 8000 , the DB with port 27017 and UI with port 3000

[application_properties.txt](https://github.com/capitalone/Hygieia/files/1455562/application_properties.txt)

I run the following command inside the folder Hygieia/collectors/build/jenkins/target: 

 java -jar jenkins-build-collector-2.0.4-SNAPSHOT.jar --spring.config.location=../application.properties

**Comment by Sbrenthughes** [comment]
Add this to your command
` -Dserver.port=8080`
that should change the port
