### ISSUE TITLE
Is there a tag for release 2.0.5?

### ISSUE THREAD

**Issue by clcain** [capitalone/Hygieia#1834]
I am looking for the code that was used for release 2.0.5, is that supposed to be tagged on this repository? I am looking at the Docker images on https://hub.docker.com/r/capitalone/hygieia-api/tags/, and it looks like 2.0.5 was tagged there 9 months ago but I'm not sure where the code for that is.

**Comment by matthewbeasley** [comment]
@clcain - We are currently working to revamp our Docker offering. Until we have completed that project we won't be updating our Docker Hub images. In the interim, please pull the latest master of this repo and run `mvn clean install docker:build` to get images. Let me know how that goes, your feedback is both desired and welcome.
