### ISSUE TITLE
Hygieia Dashboard is not displayed as expected.

### ISSUE THREAD

**Issue by gladsysamuel** [capitalone/Hygieia#1837]
![capture hygieia dashboard](https://user-images.githubusercontent.com/32176286/32782588-e9f22140-c96e-11e7-9768-41954aa163f5.PNG)

Even the sign up is not coming.

**Comment by Sbrenthughes** [comment]
Can you post your API properties?

**Comment by gladsysamuel** [comment]
dbname=dashboarddb
dbusername=dashboarduser
dbpassword=dbpassword
dbhost=127.0.0.1
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017,127.0.0.1:27017
server.contextPath=/api
server.port=8090
corsEnabled=false
auth.expirationTime=10

**Comment by gladsysamuel** [comment]
it says: -  It looks like you are trying to access MongoDB over HTTP on the native driver port.
What Is the issue?

**Comment by Sbrenthughes** [comment]
I see that. I wanted to check you api properties first. What command are you using to run mongo?

**Comment by gladsysamuel** [comment]
sudo systemctl start mongod

**Comment by Sbrenthughes** [comment]
http://www.capitalone.io/Hygieia/setup.html#database

**Comment by gladsysamuel** [comment]
I tried I in port 8080 also but again the same error.

**Comment by gladsysamuel** [comment]
can anybody help me with this issue?

**Comment by gladsysamuel** [comment]
![api running](https://user-images.githubusercontent.com/32176286/33116985-db67630a-cf8c-11e7-8587-3d8b8b4d8905.PNG)

**Comment by gladsysamuel** [comment]
api is up and running

**Comment by gladsysamuel** [comment]
For UI I gave gulp serve and dashboard is coming as I attached  the screenshot.

**Comment by Sbrenthughes** [comment]
Did you try the suggestions about Mongo?

**Comment by gladsysamuel** [comment]
yes I did . I changed the port to 8080. Still not working.

**Comment by Sbrenthughes** [comment]
Can you post your full API log output

**Comment by japm94** [comment]
Have you tried clearing a browser memory cache?

**Comment by matthewbeasley** [comment]
@gladsysamuel please follow up on some of the suggestions provided. If these don't resolve your issue. Reopen this ticket.
