### ISSUE TITLE
Unable to do mvn clean install package

### ISSUE THREAD

**Issue by Muraliece88** [capitalone/Hygieia#1845]
Am unable to build the package as it says the below errors in multiple files

[ERROR] symbol:   class ObjectId
[ERROR] location: interface com.capitalone.dashboard.service.FeatureService
[ERROR] /D:/Hygieia-master/Hygieia-master/api/src/main/java/com/capitalone/dashb
oard/service/FeatureService.java:[162,27] cannot find symbol
[ERROR] symbol:   class Feature

**Comment by subodhbattina** [comment]
1. Please do a "git pull" to ensure you have got everything latest from the repository.
2. And then do a maven clean build with -X option to enable debug logging so we have more information on the failure. Thanks !

**Comment by subodhbattina** [comment]
Muraliece88: Wanted to follow up and check if you are still facing this issue? Thanks !

**Comment by subodhbattina** [comment]
@Muraliece88: Since we didn't hear back from you, assuming your issue has been resolved. Closing this current issue. Thanks !
