### ISSUE TITLE
NPM install failed during Hygieia mvn build

### ISSUE THREAD

**Issue by hongluovz** [capitalone/Hygieia#185]
[INFO] --- frontend-maven-plugin:0.0.25:install-node-and-npm (install node and npm) @ UI ---
[INFO] Node v0.12.0 is already installed.
[INFO] Found NPM version 2.7.1
[INFO]
[INFO] --- frontend-maven-plugin:0.0.25:npm (npm install) @ UI ---
[INFO] Running 'npm install --color=false --proxy=http://my_id:my_pass@my_proxy:80' in /apps/opt/tools/new_hygieia/UI
[ERROR] npm ERR! Linux 3.10.0-229.7.2.el7.x86_64
[ERROR] npm ERR! argv "/apps/opt/tools/new_hygieia/UI/node/node" "/apps/opt/tools/new_hygieia/UI/node/node_modules/npm/bin/npm-cli.js" "install" "--color=false" "--proxy=http://my_id:my_pass@my_proxy:80"
[ERROR] npm ERR! node v0.12.0
[ERROR] npm ERR! npm  v2.7.1
[ERROR] npm ERR! code ENOSPC
[ERROR] npm ERR! errno -28
[ERROR]

**Comment by tabladrum** [comment]
@hongluovz I think your issue was resolved. Can you confirm?

**Comment by amitmawkin** [comment]
@hongluovz no response, hence closing this issue, please open another one if you encounter the same issue again
