### ISSUE TITLE
Hygieia dashboard - Quality Widget : "VIEW ALL” doesn't take to the sonar page

### ISSUE THREAD

**Issue by lenalevy** [capitalone/Hygieia#1851]
I have configure on Hygieia dashboard on “Configure Widget” Quality section.
I have choose Micro Service.
The Widget is presented , but once I'm clicked in "View all " option , it's open new page and I'm getting error "Componenet key <id> not found "
I'm understanding that the “VIEW ALL” should takes to the sonar page of respective MS
![soner error](https://user-images.githubusercontent.com/33826321/33020746-091b425c-ce08-11e7-9c45-b1a79a8f9dce.PNG)

**Comment by nireeshT** [comment]
@lenalevy  send screenshot of quality widget and the url it is taking to when clicked on "View ALL". if you see any error in console, share it.

**Comment by lenalevy** [comment]
I found the solution for this problem .
I have changed view.js under UI/src/components/widgets/codeanalysis
Fix : 
function processCaResponse(response) 

ctrl.reportUrl = response.reportUrl;       - orig code 
ctrl.reportUrl = caData.url;                          - my fix

Now it's working fine

**Comment by matthewbeasley** [comment]
@lenalevy - thanks for taking the time to post the solution!
