### ISSUE TITLE
API_HOST is hardcoded in Hygieia/UI/docker/conf-builder.sh

### ISSUE THREAD

**Issue by ibnjay** [capitalone/Hygieia#1856]
We have two Hygieia env deployed in our docker infra. This hardcoded value in conf-builder.sh prevents us from being able to provide different API_HOST env variable for the two deployment.

**Comment by matthewbeasley** [comment]
Hey ibnjay! I'm currently looking into this. Are you using legacy container linking?

**Comment by ibnjay** [comment]
@matthewbeasley Sorry didn't see that i already had a response. No not using legacy linking. Basically We launch the stack using docker-compose. Both instance of hygeia use the name network to expose frontend URLs. Using secrets we can configure API_HOST env for both stack differently. But the conf-builder.sh hard codes the value instead of just using the env variable. I suggest adding a check ```if API_HOST != null then export API_HOST=hygieia-api ``` Same thing for port.
