### ISSUE TITLE
AWS collector is picking up us-east-1 as its default region. 

### ISSUE THREAD

**Issue by rohit0503** [capitalone/Hygieia#1861]
After several tests I found out more things on Hygieia. It runs on EC2, CloudWatch and Autoscaling. It takes data from the billing dashboard on CloudWatch. The policy that is attached to the IAM role on Hygieia instance shows this dependency. As of now, our account default region for AWS billing is Virginia which is why it has to go there to get EC2 data.
How we can make our AWS collector to collect data from us-west-2 region

**Comment by rohit0503** [comment]
I have tried everything including aws.profiles  & IAM roles but no success. Please help

**Comment by yks0000** [comment]
+1 Facing same issue. 

Related issue https://github.com/capitalone/Hygieia/issues/1852#issuecomment-347026887

**Comment by yks0000** [comment]
I made local changes to Hygieia code to get it going (until it is being fixed) for the region I want to connect. 

Changes that we need to make it  are present in https://github.com/capitalone/Hygieia/issues/1852#issuecomment-347030067

**Comment by matthewbeasley** [comment]
@yks0000, @rohit0503 - please continue this discussion here: https://github.com/capitalone/Hygieia/issues/1852
