### ISSUE TITLE
Not able to get Application Name on deploy widget.

### ISSUE THREAD

**Issue by rohit0503** [capitalone/Hygieia#1862]
I configured three jobs with Dev, QA, Preprod which only do the job of fetching the repo from github and i have also defined everything (via Hygieia publisher) to get deploy results and i am getting it,
![image](https://user-images.githubusercontent.com/33894640/33120810-2f56ae92-cf99-11e7-9ac9-c026606e6f0c.png)

The console output is -
`Hygieia: Published Build Complete Data. Response Code: 201. Response Value= 5a1514c80db7b70625e306ec
Hygieia Deployment Publisher - Looking for file pattern 'tslint.json' in directory /var/lib/jenkins/workspace/rohit-dev
Hygieia Deployment Publisher: Processing  file: /var/lib/jenkins/workspace/rohit-dev/tslint.json
Hygieia: Published Deploy Data: Response Code: 201. Response Value= "5a1514cc0db7b70625e306ee"
Finished: SUCCESS`

and Dashboard output is-
![image](https://user-images.githubusercontent.com/33894640/33120966-9adbbd60-cf99-11e7-9339-7b068b1039a0.png)

![image](https://user-images.githubusercontent.com/33894640/33120984-a650a9f8-cf99-11e7-8adb-3a46a64d2f92.png)

But when i try to implement the same thing on another job with different Application Name which is building & deploying, then i am not getting the Application Name in the deploy dropdown. Below is te configuration -
![image](https://user-images.githubusercontent.com/33894640/33121381-8c1f6c44-cf9a-11e7-8705-1b7bd3453e6b.png)

Console output also shows less output that above test job -
`04:45:16 Hygieia: Published Build Complete Data. Response Code: 201. Response Value= 5a14addf0db7b70625e306ea
04:45:16 Hygieia Deployment Publisher - Looking for file pattern 'tslint.json' in directory /var/lib/jenkins/workspace/C2C-Digital-UI-Hertz-DEV
04:45:17 Finished: SUCCESS`

**Comment by subodhbattina** [comment]
@rohit0503 I was looking at the code base, and the API that seems to be called that populates applications is: "/collector/item/type/{collectorType}". Looking further, that API seems to be checking for a collector of type "Deployment" in the database, and using its collectorID to fetch data.
Have you run the UDeploy or the XLDeploy collector at all before doing whatever you are doing now?

**Comment by subodhbattina** [comment]
@rohit0503 : Since we didn't hear back from you, assuming this is resolved at your end, and so closing this issue. Thanks
