### ISSUE TITLE
require all dependency list

### ISSUE THREAD

**Issue by shendeam** [capitalone/Hygieia#187]
Hi,
Can you list all dependencies with their required version for building Hygieia. For Ex. maven=3.1.0

**Comment by amitmawkin** [comment]
minimum required is maven 3.3.3 rest all are covered in the various configuration such as npm modules etc and you would not need to worry about it

**Comment by shendeam** [comment]
Thanks...I realize that because I got errors in old maven version. Right now I am using mvn-3.3.3 and java-1.7.0_91
