### ISSUE TITLE
API connectivity Intermittent Issue

### ISSUE THREAD

**Issue by aishwaryamv123** [capitalone/Hygieia#1870]
I am facing similar issue, api log says connected to mongodb on port 27017, but localhost:8090/api/ping doesn't return true and give me a whitelabel error message page.
UI says red on api connectivity. It was working well earlier suddenly it isnt working, Can someone please help me with this/if any faced same ??

**Comment by matthewbeasley** [comment]
Hi aishwaryamv123! Will you post your properties settings as well as the api logs?

**Comment by matthewbeasley** [comment]
@aishwaryamv123 since I have not heard from you in 7 days I am going to close this issue.
