### ISSUE TITLE
SVNAuthenticationException: svn: E170001: Authentication required 

### ISSUE THREAD

**Issue by Ashissh021** [capitalone/Hygieia#1901]
Hi Team,

I am getting error while connecting Hygieia to svn though i had put the username and password correct.
Below is my property file.

#Database Name
  spring.data.mongodb.database=*******

#Database HostName - default is localhost
  spring.data.mongodb.host=localhost
  dbhost=localhost

#Database Port - default is 27017
  spring.data.mongodb.port=27017

#Database Username - default is blank
  spring.data.mongodb.username=*******

#Database Password - default is blank
  spring.data.mongodb.password=*******

#Collector schedule (required)
  subversion.cron=0 0/2 * * * *

#Shared subversion username and password
  subversion.username=prod\*****
  subversion.password=*****

#Maximum number of days to go back in time when fetching commits
  subversion.commitThresholdDays=5
 
Can any one please help me out.

Thanks
Ashish

**Comment by matthewbeasley** [comment]
@Ashissh021 - What error are you getting? Please post a screenshot of the error you are receiving.

**Comment by Ashissh021** [comment]
@matthewbeasley: Thanks i have updated the application property as below now its working fine.

#Database Name 
spring.data.mongodb.database=<mongo db name>

#Database HostName - default is localhost
spring.data.mongodb.host=localhost

#Database Port - default is 27017
spring.data.mongodb.port=27017

#Database Username - default is blank
spring.data.mongodb.username=d<mongo db username>

#Database Password - default is blank
spring.data.mongodb.password=<mongo db password>

dbname=<mongo db name>
dbhost=localhost
dbport=27017
dbusername=<mongo db username>
dbpassword=<mongo db password>

#Collector schedule (required)
subversion.cron=0 0/5 * * * *

#Shared subversion username and password
subversion.username=<svn user name>
subversion.password=<svn password>

#Maximum number of days to go back in time when fetching commits
subversion.commitThresholdDays=15

Thank you :)

**Comment by matthewbeasley** [comment]
@Ashissh021 I'm glad you got it working! Thank you for closing this issue.
