### ISSUE TITLE
IS there  a  function test  ,  integration (system) test  for hygieia ??  

### ISSUE THREAD

**Issue by samyzemmouri** [capitalone/Hygieia#1903]

**Comment by matthewbeasley** [comment]
@samyzemmouri - for general questions and operational support please go to [gitter.im](https://gitter.im/capitalone/Hygieia) and start a conversation there. As this is a general question and not an issue, per se, I am going to close this issue. I look forward to talking to you on [gitter.im](https://gitter.im/capitalone/Hygieia)
