### ISSUE TITLE
Hygieia and cloud bees jenkins collector issue

### ISSUE THREAD

**Issue by Ashissh021** [capitalone/Hygieia#1911]
I had configured hygieia and cloud bees jenkins in my local machine and have run the collectors in console but in UI dash board build widget is displaying the list but when i select any job it is throwing error saying unable to get the job details and returning json data.
I am connecting with api 

username: apitoken@jekins.com:port

Please help me out for this issue.

**Comment by matthewbeasley** [comment]
@Ashissh021 - please post a screenshot of the error being thrown.

**Comment by Ashissh021** [comment]
@matthewbeasle: it is working fine now below the property file have used and it is working fine now.
Thank you.

#Database Name 
spring.data.mongodb.database=<mongo db name>

#Database HostName - default is localhost
spring.data.mongodb.host=localhost

#Database Port - default is 27017
spring.data.mongodb.port=27017

#Database Username - default is blank
spring.data.mongodb.username=<mongo db username>

#Database Password - default is blank
spring.data.mongodb.password=<mongo db password>

dbname=<mongo db name>
dbhost=localhost
dbport=27017
dbusername=<mongo db username>
dbpassword=<mongo db password>

#Collector schedule (required)
jenkins.cron=0 0/1 * * * *

#Hudson server (required) - Can provide multiple (if you want to pull out more than one job from different folder
jenkins.servers[0]=<url for hygieia>
jenkins.servers[1]=<url for hygieia>
jenkins.servers[2]=<url for hygieia>


#jenkins user name (required)
jenkins.username=<jenkins user name>

#jenkins password (required) 
#fo api key click on user profile(your user name)->click on configure[left menu]-> click generate apikey or show api key token
jenkins.apiKey=<jenkins api key>

#Determines if build console log is collected - defaults to false
jenkins.saveLog=true

**Comment by Ashissh021** [comment]
so closing the issue now Thank you :+1:
