### ISSUE TITLE
Session Issue in Hygieia

### ISSUE THREAD

**Issue by Ashissh021** [capitalone/Hygieia#1913]
Hi Team,

I am getting one issue in dashboard and that seems to be with session or authentication, I am not sure why it is happening. Please find the issue details below.

I have created Hygieia dashboard and when I given the url(External URL) to one of my colleague to access it. It is behaving very strangely. He has signed up to the hygieia dashboard and then login in.
After login to hygieia he was able to see all the dashboard i have created but not able to change(select any jenkins, udeploy or svn) that is fine. but when i am doing any thing in my system he was able to see what i am doing it its like mirror image of my dashboard UI to him and he is keeping his hands free and able to see what exactly i am doing.

Can any one please help me out how to resolve this issue, any setup or any configuration needs to be changed.  Please help me for it.

Thanks,
Ashissh

**Comment by matthewbeasley** [comment]
@Ashissh021 - can you be more specific about the mirroring that was occuring? As in: what exactly was being mirrored? Dropdowns, etc or just changes you were making?

**Comment by Ashissh021** [comment]
@matthewbeasley - It is both change and drop down, Both are being mirrored.

**Comment by Ashissh021** [comment]
I am using gulp serve command to start UI

**Comment by matthewbeasley** [comment]
@Ashissh021 - gulp serve is really only intended to be for dev environments. If you are targeting a prod deployment then you should use a proper webserver (nginx or httpd). As a quick solution it seems you can just modify the gulpfile like [this](https://stackoverflow.com/questions/32510840/how-to-disable-cross-device-action-mirroring-functionality-of-browsersync-ghos)

**Comment by matthewbeasley** [comment]
@Ashissh021 - if this works for you please close this issue.

**Comment by Ashissh021** [comment]
@matthewbeasley - I will check and get back to you soon.

**Comment by Ashissh021** [comment]
@matthewbeasley- Thanks indeed for your help It is working fine for me now have made the changes to gulf file and now the mirror issue is resolved. :)
I will be closing the issue now.
