### ISSUE TITLE
How to Implement Single sign-on in Hygieia

### ISSUE THREAD

**Issue by ameetsvshah** [capitalone/Hygieia#1917]
We want to implement Single Sign-on for the LDAP users.
We have integrated LDAP with AD.
 
Can you give Sample configuration for these SSO properties. 

auth.userEid=[name of the header containing EID]
auth.userEmail=[name of the header containing user's email]
auth.userFirstName=[name of the header containing user's first name]
auth.userLastName=[name of the header containing user's last name]
auth.userMiddelInitials=[name of the header containing user's middle name]
auth.userDisplayName=[name of the header containing user's display name]

**Comment by matthewbeasley** [comment]
Set these properties:

```
auth.authenticationProviders=LDAP,STANDARD

auth.adUrl=ldaps://<some-ldap-server>
auth.adDomain=<ldap-domain>
auth.adRootDn=<dc config>

#Needed to query ldap
auth.ldapBindUser=
auth.ldapBindPass=

#SSO properties
auth.userEid=[name of the header containing EID]
auth.userEmail=[name of the header containing user's email]
auth.userFirstName=[name of the header containing user's first name]
auth.userLastName=[name of the header containing user's last name]
auth.userMiddelInitials=[name of the header containing user's middle name]
auth.userDisplayName=[name of the header containing user's display name]
```
