### ISSUE TITLE
Jenkins collector doubt

### ISSUE THREAD

**Issue by Ashissh021** [capitalone/Hygieia#1922]
Hi Team,

Have one doubt regarding Jenkins CI job and my doubts are:
1)  Can we have more than one CI jobs display in dashboard, What i mean is if I have two job for one folder can i have both the job display on the same time in dashboard (one dashboard can have multiple CI job display)?

2) Can we have user like admin in hygieia that can give the other user to access like user access privilege in hygieia?
3) Any support document for pipline dashboard and how to configure that.

please help me and do let me know if you need more explaination on it.

Thanks,
Ashissh

**Comment by ameetsvshah** [comment]
2. Can we have user like admin in hygieia that can give the other user to access like user access privilege in hygieia?

--> Sign up with username: admin and you will get few administrative options.

3.Any support document for pipeline dashboard and how to configure that.

--> Configure Deploy widget.
Once data is displayed in Deploy widget, In the Pipeline view, click the plus sign to add same environments in the deploy widget in pipeline view with related artifacts.

**Comment by matthewbeasley** [comment]
@Ashissh021 
1: we are currently working on this feature for all widgets. Should be released in the coming weeks / months
2: currently only the admin user has admin privileges. Access control is a commonly requested feature and may be something that becomes a priority in the near future.
3: Unfortunately no, at the time we do not have docs on individual widget configuration

We really appreciate your interest in this project, however this isn't an issue per se and for that reason I'm going to close this issue. If you would like to continue the discussion or would like more help with setting up Hygieia please hit us up on [gitter.im](https://gitter.im/capitalone/Hygieia)

**Comment by Ashissh021** [comment]
@matthewbeasley - Thanks indeed for your respond :) :+1:

**Comment by Ashissh021** [comment]
@matthewbeasley - 
3.Any support document for pipeline dashboard and how to configure that.
--> Configure Deploy widget.
Once data is displayed in Deploy widget, In the Pipeline view, click the plus sign to add same environments in the deploy widget in pipeline view with related artifacts.
===> for this I am not getting any value in (Map your environments to the following pipeline stages:)
please let me know if i need to do other setup for pipline job
