### ISSUE TITLE
Is there a way to configure dashboards in code? 

### ISSUE THREAD

**Issue by yatzek** [capitalone/Hygieia#1926]
I was wandering if it is possible to define dashboards in code so that they can be easily recreated when setting up a new instance?

**Comment by matthewbeasley** [comment]
@yatzek - no, but this is a really good idea and one that we might implement in the future.

**Comment by yatzek** [comment]
Please do, we are very keen on having all dashboards as code so that we can easily import/share/version them.

**Comment by Sbrenthughes** [comment]
You can actually do that via "/api/dashboard/remoteCreate". We are currently in the works for putting on documentation on how to use this. Stay tuned.
