### ISSUE TITLE
Does hygieia application have support for LTM load balancing and MongoDB for High availability

### ISSUE THREAD

**Issue by muthukamaraj** [capitalone/Hygieia#1928]
We need to implement LTM for hygieia servers and High availabilty for the mongo DB. Does Hygieia really support this feature, Also is there a document to do that. Please let us know

**Comment by matthewbeasley** [comment]
@muthukamaraj - I don't know what LTM is so I'm going to say 'no' on that one. For mongoDB we support replicasets.
