### ISSUE TITLE
Patch for 2.0.4 gitlab collector problem:  Slow GitLab server causes data collector socket read timeouts

### ISSUE THREAD

**Issue by dlydick** [capitalone/Hygieia#1930]
A slow GitLab server causes the Hygieia data collector to receive 'java.net.SocketTimeoutException' from the Spring socket logic.  This gets caught and rethrown as 'org.springframework.web.client.ResourceAccessException'.  This causes a stack trace in the collector.

Please find a TAR file attached with notes describing the problem in full as well as two patched source files and their originals plus two 'diff' views of the patch.

Here is the contents of those notes in full:
---
PATCH TO OVERCOME GITLAB SERVER REST API SOCKET READ TIMEOUT
============================================================

Trying to implement a GitLab data collector for this installation
of Hygieia had a rather interesting runtime problem.  The GitLab
the GitLab server could run quite slowly at time due to system
tuning problems.  Since a Gitlab server has a significant number
of processes running all the time, inter-process latency can be
signficant when other processing makes significant claims on
system resources such as memory and CPU time.  From a web browser,
the GitLab GUI would sometimes return an error 502 (bad gateway)
under these conditions.  From a REST API viewpoint, a socket read
timeout came back, generating the runtime exception
'java.net.SocketTimeoutException' event.  The Spring API translates
this into 'org.springframework.web.client.ResourceAccessException',
which may be caught by the invoking Java code at the point shown
below with a (++) marking.  The (---) marking shows the segment of
stack trace applicable to the patched code and creation and recovery
from the socket read timeout event:

2018-01-10 11:13:20,619 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler -
  Unexpected error occurred in scheduled task.

org.springframework.web.client.ResourceAccessException:
 I/O error on GET request for
"http://gitlab.company.com:80/api/v3/projects
/root%2Ftest-GITDATA/repository/commits
/?ref_name=master&since=2017-12-27T11:13:00Z&per_page=100":

Read timed out; nested exception is java.net.SocketTimeoutException:
 Read timed out
        at org.springframework.web.client.RestTemplate
          .doExecute(RestTemplate.java:580)
           ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]

        at org.springframework.web.client
          .RestTemplate.execute(RestTemplate.java:545)
           ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]

        at org.springframework.web.client.RestTemplate
          .exchange(RestTemplate.java:466)
            ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
---
        at com.capitalone.dashboard.collecteur.DefaultGitlabGitClient
          .makeRestCall(DefaultGitlabGitClient.java:92)
           ~[gitlab-git-collector-2.0.4.jar!/:2.0.4]

   (++) at com.capitalone.dashboard.collecteur.DefaultGitlabGitClient
          .getCommits(DefaultGitlabGitClient.java:69)
           ~[gitlab-git-collector-2.0.4.jar!/:2.0.4]

        at com.capitalone.dashboard.collecteur.GitlabGitCollectorTask
          .collect(GitlabGitCollectorTask.java:98)
           ~[gitlab-git-collector-2.0.4.jar!/:2.0.4]
---
        at com.capitalone.dashboard.collector.CollectorTask
          .run(CollectorTask.java:63) ~[core-2.0.4.jar!/:2.0.4]

        at org.springframework.scheduling.support
          .DelegatingErrorHandlingRunnable
          .run(DelegatingErrorHandlingRunnable.java:54)
           ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]

        at org.springframework.scheduling.concurrent
          .ReschedulingRunnable.run(ReschedulingRunnable.java:81)
           [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]

        at java.util.concurrent.Executors$RunnableAdapter
          .call(Executors.java:511) [na:1.8.0_144]

        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
           [na:1.8.0_144]

        at java.util.concurrent
          .ScheduledThreadPoolExecutor$ScheduledFutureTask
          .access$201(ScheduledThreadPoolExecutor.java:180)
           [na:1.8.0_144]

        at java.util.concurrent
          .ScheduledThreadPoolExecutor$ScheduledFutureTask
          .run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_144]

        at java.util.concurrent.ThreadPoolExecutor
          .runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_144]

        at java.util.concurrent.ThreadPoolExecutor$Worker
          .run(ThreadPoolExecutor.java:624) [na:1.8.0_144]

        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]

Caused by: java.net.SocketTimeoutException: Read timed out

        at java.net.SocketInputStream.socketRead0(Native Method)
           ~[na:1.8.0_144]

        at java.net.SocketInputStream
          .socketRead(SocketInputStream.java:116) ~[na:1.8.0_144]

        at java.net.SocketInputStream.read(SocketInputStream.java:171)
           ~[na:1.8.0_144]

        at java.net.SocketInputStream.read(SocketInputStream.java:141)
           ~[na:1.8.0_144]

        at org.apache.http.impl.io.SessionInputBufferImpl
          .streamRead(SessionInputBufferImpl.java:136)
           ~[httpcore-4.3.3.jar!/:4.3.3]

        at org.apache.http.impl.io.SessionInputBufferImpl
          .fillBuffer(SessionInputBufferImpl.java:152)
           ~[httpcore-4.3.3.jar!/:4.3.3]

        at org.apache.http.impl.io.SessionInputBufferImpl
          .readLine(SessionInputBufferImpl.java:270)
           ~[httpcore-4.3.3.jar!/:4.3.3]

        at org.apache.http.impl.conn.DefaultHttpResponseParser
          .parseHead(DefaultHttpResponseParser.java:140)
           ~[httpclient-4.3.6.jar!/:4.3.6]

        at org.apache.http.impl.conn.DefaultHttpResponseParser
          .parseHead(DefaultHttpResponseParser.java:57)
           ~[httpclient-4.3.6.jar!/:4.3.6]

        at org.apache.http.impl.io.AbstractMessageParser
          .parse(AbstractMessageParser.java:260)
           ~[httpcore-4.3.3.jar!/:4.3.3]

        at org.apache.http.impl.DefaultBHttpClientConnection
          .receiveResponseHeader(DefaultBHttpClientConnection.java:161)
           ~[httpcore-4.3.3.jar!/:4.3.3]

        at org.apache.http.impl.conn.CPoolProxy
          .receiveResponseHeader(CPoolProxy.java:153)
           ~[httpclient-4.3.6.jar!/:4.3.6]

        at org.apache.http.protocol.HttpRequestExecutor
          .doReceiveResponse(HttpRequestExecutor.java:271)
           ~[httpcore-4.3.3.jar!/:4.3.3]

        at org.apache.http.protocol.HttpRequestExecutor
          .execute(HttpRequestExecutor.java:123)
           ~[httpcore-4.3.3.jar!/:4.3.3]

        at org.apache.http.impl.execchain.MainClientExec
          .execute(MainClientExec.java:254)
           ~[httpclient-4.3.6.jar!/:4.3.6]

        at org.apache.http.impl.execchain.ProtocolExec
          .execute(ProtocolExec.java:195)
           ~[httpclient-4.3.6.jar!/:4.3.6]

        at org.apache.http.impl.execchain.RetryExec
          .execute(RetryExec.java:86)
           ~[httpclient-4.3.6.jar!/:4.3.6]

        at org.apache.http.impl.execchain.RedirectExec
          .execute(RedirectExec.java:108)
           ~[httpclient-4.3.6.jar!/:4.3.6]

        at org.apache.http.impl.client
          .InternalHttpClient.doExecute(InternalHttpClient.java:184)
           ~[httpclient-4.3.6.jar!/:4.3.6]

        at org.apache.http.impl.client.CloseableHttpClient
          .execute(CloseableHttpClient.java:82)
           ~[httpclient-4.3.6.jar!/:4.3.6]

        at org.springframework.http.client
          .HttpComponentsClientHttpRequest
          .executeInternal(HttpComponentsClientHttpRequest.java:91)
           ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]

        at org.springframework.http.client
          .AbstractBufferingClientHttpRequest
          .executeInternal(AbstractBufferingClientHttpRequest.java:48)
           ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]

        at org.springframework.http.client.AbstractClientHttpRequest
          .execute(AbstractClientHttpRequest.java:53)
           ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]

        at org.springframework.web.client.RestTemplate
          .doExecute(RestTemplate.java:569)
           ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        ... 15 common frames omitted

The patch provided here performs two actions on two files in the source
directory 'collectors/scm/gitlab/src/main/java/com/capitalone/dashboard
/collecteur' to patch the Hygieia 2.0.4 release branch:

(1)   DefaultGitlabGitClent.java:  Retry three times if this event
      arises as detected by catch(ResourceAccessException).  If
      detected, perform Thread.sleep() for RETRY_SLEEP_TIME_MS
      milliseconds between attempts.  If this Thread.sleep() is
      interrupted--which is most unlikely--a catch(InterruptedException)
      will retry the socket read without counting an additional retry.
      Once a valid socket read is detected or the retry count expires,
      continue with current processing.

(2)   GitlabGitCOllectorTask.java:  If no data is returned from the
      getCommits() method due to socket timeouts or simply no data to
      report, defer updating the Git 'repo' object with update times
      until that condition is known.  This way, if there is a problem
      with obtaining data during the initial attempt at data collector
      startup time, the 'firstRun' condition is preserved and the next
      scan cycle of the collector will request the larger amount from
      the 'firstRun' condtion.  If it is still not available, the next
      scan does the same thing until the GitLab server finally gives up
      and produces data.  This is likely to occur since system cacheing
      will make its memory and disk resources more quickly available
      on successive scans until finally data is returned, at least so I
      suggest and speculate. Once the 'firstRun' condition is satisfied,
      successive data collector scans will request incremental results
      per existing behavior.

RELATED DATA COLLECTOR ISSUES
=============================

It might be prudent for the other Git data collectors to investigate
whether or not this issue might affect them also.  If the GitHub
data collector were to be examined, an easy way to test it would be
to set both(?) the socket connect and read timeout down from 20,000ms
to 1ms.  This would guarantee the problem to exist.  I cannot
assume which one of the two timeouts is invoked but this would be an
easy test.  It SHOULD be the read operation, since the log message
said 'Read timed out'.  The 'java.next.SocketTimeoutException' would
most certainly occur on its first invocation.  If so, then this same
patch technique could be implemented to catch
'org.springframework.web.client.ResourceAccessException'.

All other Hygieia clients probably would stand an examination of their
read timeout conditions since the product is still quite new and usage
data from production conditions is not yet widely known.  I would
suggest that numerous other Hygieia data collector applications could
use the same scrutiny and possibly a similar approach to bolstering the
response of the application against socket read timeout conditions.

PATCH DATA AND REPORTS
======================

The following files are provided to describe and implement this patch:

notes.txt
---------
This text file.

gitlab-collector-raw.diff
-------------------------
Output of 'diff -r ORIG-src src' to show every change precisely,
including white space differences.

gitlab-collector-no-white-spc-diffs.diff
----------------------------------------
Output of 'diff -rbBw ORIG-src src' to show the same changes but
not include white space differences.

ORIG-src/2.0.4/collectors/scm/gitlab
/src/main/java/com/capitalone/dashboard
/collecteur/DefaultGitlabGitClient.java
---------------------------------------
Source code file 'DefaultGitlabClient.java' directly from 2.0.4 release.

ORIG-src/2.0.4/collectors/scm/gitlab
/src/main/java/com/capitalone/dashboard
/collecteur/GitlabGitCollectorTask.java
---------------------------------------
Source code file 'GitlabGitCollector.java' directly from 2.0.4 release.

src/2.0.4/collectors/scm/gitlab
/src/main/java/com/capitalone/dashboard
/collecteur/DefaultGitlabGitClient.java
---------------------------------------
Source code file 'DefaultGitlabClient.java' as modified for this patch.

src/2.0.4/collectors/scm/gitlab
/src/main/java/com/capitalone/dashboard
/collecteur/GitlabGitCollectorTask.java
---------------------------------------
Source code file 'GitlabGitCollector.java' as modified for this patch.

EOF

[hygieia-2.0.4-gitlab-patch-180109.tar.gz](https://github.com/capitalone/Hygieia/files/1620151/hygieia-2.0.4-gitlab-patch-180109.tar.gz)

**Comment by matthewbeasley** [comment]
@dlydick - could you update to the latest version of Hygieia (2.0.5) and create a PR for these changes?

**Comment by dlydick** [comment]
Please see the provided patch file.  The fix is very short and is supplied there in full.

**Comment by matthewbeasley** [comment]
@dlydick - I saw the included files. I just don't know why you did it this way instead of opening a PR.

**Comment by dlydick** [comment]
Sorry--I did not know what your process was.  Since I did find this issue reporting facility, I assumed this was the way to report issues and problems.  Problem Reporting == PR   ?  :)

Also, I am on a tight deadline to implement Hygieia and am using 2.0.4.  Unfortunately, I do not have the time to properly install and test this patch on the master branch for the upcoming 2.0.5 release.  So I submitted a patch for the released files instead.  I am, however, available to answer questions about the patch and issues surrounding it.

Thanks to all for the Hygieia product and the great ideas it is implementing!

**Comment by matthewbeasley** [comment]
@dlydick - PR == Pull Request.
To create one:
- fork this repo
- clone that fork
- make a new branch
- commit your changes
- push that branch
- go to github/your-fork
- press the 'create pull-request' button
et, viola -- you gotta PR

I'll implement your changes but, it might be a bit before it's merged since I'll have to set up gitlab for testing.

**Comment by dlydick** [comment]
I am going to submit a significant refinement to this patch that can refine the retry timing with config file settings.  Therefore, I am closing this one.
