### ISSUE TITLE
mvn clean gets failed during first setup 

### ISSUE THREAD

**Issue by devopsdeveloper** [capitalone/Hygieia#1934]
As per given document, have followed Step 1:

Step 1: Run Maven Build

In the command line/terminal, run the following command from the \Hygieia directory of your source code installation:

mvn clean install package

but it throws the code compilation error, 

![setup_issue](https://user-images.githubusercontent.com/10191262/34857811-d0dbfddc-f71a-11e7-8b47-b0429b6dac7c.png)

**Comment by matthewbeasley** [comment]
Hey @devopsdeveloper - what is your java version?

**Comment by devopsdeveloper** [comment]
Hi ... I am using JAVA1.8.0_144

**Comment by Sbrenthughes** [comment]
https://github.com/capitalone/Hygieia/issues/1964 try using a different version of java. Reopen if the issue persist.

**Comment by devopsdeveloper** [comment]
After changing version it's get resolved..thanks
