### ISSUE TITLE
API cannot be started: Trying to run Hygieia on Windows

### ISSUE THREAD

**Issue by Fairozz** [capitalone/Hygieia#1935]
Hi,

API startup failed with below error. Please help.

2018-01-11 22:38:41,077 ERROR o.s.boot.SpringApplication - Application startup failed org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor': Invocation of init method failed; nested exception is javax.validation.ValidationException: Unable to instantiate Configuration.

        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]

**Comment by matthewbeasley** [comment]
Hi @Fairozz - can you please provide me with:
1: your java + maven versions
2: The command used to start the api
3: Your properties file with your info redacted

**Comment by Fairozz** [comment]
1. 
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T03:58:1
3-04:00)
Maven home: C:\Fairoz\DevOpsDashboard\apache-maven-3.5.2-bin\apache-maven-3.5.2\
bin\..
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_151\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows server 2008 r2", version: "6.1", arch: "amd64", family: "windows"
2.
java -jar api.jar --spring.config.location=C:\Users\mohammed.fairoz\Hygieia\api\dashboard.properties -Djasypt.encryptor.password=hygieiasecret

3.
dbname=dashboarddb
dbusername=dashboarduser
dbpassword=dbpassword
dbhost=127.0.0.1
dbport=27017
server.contextPath=/api
server.port=8089
version.number=@application.version.number@

NOTE: I update the port in gulpfile.js to 8089

**Comment by matthewbeasley** [comment]
@Fairozz, I can't quite reproduce this as I don't have a windows server to test on. Will you post your entire api logs? Perhaps there are other hints there.

**Comment by Fairozz** [comment]
[devopsdashboard-api-2018-01-12.0.log](https://github.com/capitalone/Hygieia/files/1626616/devopsdashboard-api-2018-01-12.0.log)

Thank you so much for looking into it. I have attached the log. Let me know.

**Comment by matthewbeasley** [comment]
@Fairozz - awesome. thanks for posting your logs. I think what might be happening is that you've missed some required properties. Please add the following:
```
auth.expirationTime=60000000
auth.secret=hygieiasecret
auth.authenticationProviders=STANDARD
```

**Comment by Fairozz** [comment]
I updated that again now and tried. No luck - still the same. The latest log below. 
[Dashboard.api.log](https://github.com/capitalone/Hygieia/files/1626710/Dashboard.api.log)

**Comment by Fairozz** [comment]
Resolved!!!

I had two java versions installed 8.4 and 9.0.1 on my machine. 8.4 was used to build the jar. after uninstalling 9.0.1, I was able to start the API. 

Thank you so much for your help.
