### ISSUE TITLE
Using API to configure dashboard

### ISSUE THREAD

**Issue by saxenadeepakkumar** [capitalone/Hygieia#1939]
i am writing a shell script to automate configuration of dashboard at the time of deployment of Hygieia.

Could you guys help me to identified the api to configure dashboard?
I am able to create dashboard using api " http://hostname:port/api/dashboard". Different collectors are running and i want to configure widgets using API.

Thanks in Advance.
Please help.

**Comment by subodhbattina** [comment]
@saxenadeepakkumar 
I am not sure if the APIs support programmatic configuration of the widgets via API calls. But please feel free to look at the code repository, at the path "api/src/main/java/com/capitalone/rest". All the rest controllers are in there. You could look into the relevant controller depending on the widget you want to configure, and see if the API supports the "create" operation or not.

If you are interested in contributing and adding this capability though, we do encourage that. You would need to fork the master branch and incorporate your changes, and create a PR for review after you have thoroughly tested your changes. Thanks !

**Comment by Sbrenthughes** [comment]
See https://github.com/capitalone/Hygieia/issues/1926. Documentation is currently in the works.
