### ISSUE TITLE
UI cannot connect to API using Docker images

### ISSUE THREAD

**Issue by pversteijnen** [capitalone/Hygieia#1942]
I have a setup of Hygieia using the Docker containers provided. Using a docker-compose file I have a setup with (MongoDB, API, UI, GitHub Collector).

API -> MongoDB seems to work. Logs indicate a connection is made and API is started
Collector -> MongoDB seems to work. Logs indicate the collector is started successfull

UI -> API does not seem to work for some reason?

UI port 8090
API port 8080
MongoDB port 27017

`172.18.0.1 - - [16/Jan/2018:11:18:11 +0000] "GET /template-cache.js HTTP/1.1" 200 75719 "http://localhost:8090/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36" "-"
2018/01/16 11:18:11 [error] 9#9: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /api/dashboard HTTP/1.1", upstream: "http://127.0.0.1:8080/api/dashboard", host: "localhost:8090", referrer: "http://localhost:8090/"
2018/01/16 11:18:11 [warn] 9#9: *12 upstream server temporarily disabled while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /api/dashboard HTTP/1.1", upstream: "http://127.0.0.1:8080/api/dashboard", host: "localhost:8090", referrer: "http://localhost:8090/"
2018/01/16 11:18:11 [error] 9#9: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /api/dashboard HTTP/1.1", upstream: "http://127.0.0.1:8080/api/dashboard", host: "localhost:8090", referrer: "http://localhost:8090/"
2018/01/16 11:18:11 [warn] 9#9: *12 upstream server temporarily disabled while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /api/dashboard HTTP/1.1", upstream: "http://127.0.0.1:8080/api/dashboard", host: "localhost:8090", referrer: "http://localhost:8090/"
172.18.0.1 - - [16/Jan/2018:11:18:11 +0000] "GET /api/dashboard HTTP/1.1" 502 537 "http://localhost:8090/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36" "-"
172.18.0.1 - - [16/Jan/2018:11:18:11 +0000] "GET /assets/img/bg-forest.jpg HTTP/1.1" 200 319122 "http://localhost:8090/styles/dash.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36" "-"
172.18.0.1 - - [16/Jan/2018:11:18:11 +0000] "GET /assets/img/hygieia_w.png HTTP/1.1" 200 82363 "http://localhost:8090/styles/dash.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36" "-"
172.18.0.1 - - [16/Jan/2018:11:18:11 +0000] "GET /fonts/fontawesome-webfont.woff?v=4.2.0 HTTP/1.1" 200 65452 "http://localhost:8090/styles/dash.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36" "-"
172.18.0.1 - - [16/Jan/2018:11:18:11 +0000] "GET /favicon.ico HTTP/1.1" 200 3577 "http://localhost:8090/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36" "-"`

Any help would be great. Puzzling for several days, experimented a lot Googled a lot but not able to find the solution.

Kind regards,
Pieter

**Comment by pversteijnen** [comment]
What worked for me was in the UI configuring set the API with my external IP address. Some how this solved my issue of not connecting to the API (using Docker-Compose)
```
  # Hygieia UI layer
  hygieia-ui:
    image: pversteijnen/hygieia-ui
    container_name: hygieia-ui
    environment:
      - jasypt.encryptor.password=hygieiasecret
      - API_HOST=<your external IP>
      - API_PORT=8080
    ports:
      - "8090:80"
    links:
      - hygieia-api
```

This issue can be closed

**Comment by prateekasthana** [comment]
Hi pversteijnen, I am also Facing Same issue , 
The solution you suggested is not working for me.

**Comment by prateekasthana** [comment]
all Images are Up and Running Using docker Compose . 
But UI is not able to connect API . 

Below is the UI configuration :

 ui:
    build: UI
    image: hygieia-ui_ping
    depends_on:
      - api
    ports:
      - "3002:80"
    environment:
      - API_HOST=api
      - API_PORT=8080
    links:
      - api
