### ISSUE TITLE
CMDB UI Configuration

### ISSUE THREAD

**Issue by akshataj1** [capitalone/Hygieia#1943]
Hi, 
I am trying to run CMDB collector. While creating dashboard in Hygieia there is no option to configure CMDB widget. 
I also searched for existing UI for HPSM tool on Hygieia Dashboard but could not find.
Can anyone help me out with this?

**Comment by Sbrenthughes** [comment]
There is no widget. See this PR for information about the collector.https://github.com/capitalone/Hygieia/pull/1478
