### ISSUE TITLE
hygieia-publisher: Compilation failure

### ISSUE THREAD

**Issue by khurshid4** [capitalone/Hygieia#1945]
Hello @amitmawkin @tabladrum 

[INFO] Scanning for projects...
[WARNING] The POM for org.jenkins-ci.tools:maven-hpi-plugin:jar:1.106 is missing, no dependency information available
[WARNING] The POM for org.kohsuke.stapler:maven-stapler-plugin:jar:1.17 is missing, no dependency information available
[WARNING] Failed to build parent project for org.jenkins-ci.plugins:hygieia-publisher:hpi:2.0.5-SNAPSHOT
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.jenkins-ci.plugins:hygieia-publisher:hpi:2.0.5-SNAPSHOT
[WARNING] 'parent.relativePath' of POM org.jenkins-ci.plugins:hygieia-publisher:2.0.5-SNAPSHOT (D:\Temp Hygieia\Hygieia-master\hygieia-jenkins-plugin\pom.xml) points at com.capitalone.dashboard:Hygieia instead of org.jenkins-ci.plugins:plugin, please verify your project structure @ line 15, column 13
[WARNING] 'build.plugins.plugin.version' for com.spotify:docker-maven-plugin is missing. @ line 232, column 21
[WARNING] 'build.plugins.plugin.version' for org.jacoco:jacoco-maven-plugin is missing. @ line 214, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Hygieia Publisher Plugin 2.0.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ hygieia-publisher ---
[INFO] Deleting D:\Temp Hygieia\Hygieia-master\hygieia-jenkins-plugin\target
[INFO]
[INFO] --- maven-hpi-plugin:1.106:validate (default-validate) @ hygieia-publisher ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.0.1:enforce (enforce-maven) @ hygieia-publisher ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.0.1:display-info (display-info) @ hygieia-publisher ---
[INFO] Maven Version: 3.5.2
[INFO] JDK Version: 1.8.0_31 normalized as: 1.8.0-31
[INFO] OS Info: Arch: amd64 Family: dos Name: windows 8.1 Version: 6.3
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.0:prepare-agent (default) @ hygieia-publisher ---
[INFO] argLine set to "-javaagent:C:\\Users\\khurshid.khokhar\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.0\\org.jacoco.agent-0.8.0-runtime.jar=destfile=D:\\Temp Hygieia\\Hygieia-master\\hygieia-jenkins-plugin\\target\\jacoco.exec"
[INFO]
[INFO] --- maven-localizer-plugin:1.14:generate (default) @ hygieia-publisher ---
[INFO]
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ hygieia-publisher ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 9 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ hygieia-publisher ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 28 source files to D:\Temp Hygieia\Hygieia-master\hygieia-jenkins-plugin\target\classes
[INFO] /D:/Temp Hygieia/Hygieia-master/hygieia-jenkins-plugin/src/main/java/hygieia/builder/SonarBuilder.java: D:\Temp Hygieia\Hygieia-master\hygieia-jenkins-plugin\src\main\java\hygieia\builder\SonarBuilder.java uses or overrides a deprecated API.
[INFO] /D:/Temp Hygieia/Hygieia-master/hygieia-jenkins-plugin/src/main/java/hygieia/builder/SonarBuilder.java: Recompile with -Xlint:deprecation for details.
[INFO] /D:/Temp Hygieia/Hygieia-master/hygieia-jenkins-plugin/src/main/java/hygieia/utils/HygieiaUtils.java: Some input files use unchecked or unsafe operations.
[INFO] /D:/Temp Hygieia/Hygieia-master/hygieia-jenkins-plugin/src/main/java/hygieia/utils/HygieiaUtils.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- access-modifier-checker:1.12:enforce (default-enforce) @ hygieia-publisher ---
[INFO]
[INFO] --- maven-hpi-plugin:1.106:insert-test (default-insert-test) @ hygieia-publisher ---
[INFO]
[INFO] --- gmaven-plugin:1.5-jenkins-1:generateTestStubs (test-in-groovy) @ hygieia-publisher ---
[INFO] No sources found for Java stub generation
[INFO]
[INFO] --- maven-resources-plugin:2.5:testResources (default-testResources) @ hygieia-publisher ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ hygieia-publisher ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 9 source files to D:\Temp Hygieia\Hygieia-master\hygieia-jenkins-plugin\target\test-classes
[INFO] /D:/Temp Hygieia/Hygieia-master/hygieia-jenkins-plugin/target/inject-tests/InjectedTest.java: Some input files use unchecked or unsafe operations.
[INFO] /D:/Temp Hygieia/Hygieia-master/hygieia-jenkins-plugin/target/inject-tests/InjectedTest.java: Recompile with -Xlint:unchecked for details.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] error reading C:\Users\khurshid.khokhar\.m2\repository\org\jenkins-ci\main\jenkins-test-harness\1.609.2\jenkins-test-harness-1.609.2.jar; error in opening zip file
[ERROR] error reading C:\Users\khurshid.khokhar\.m2\repository\org\jenkins-ci\main\jenkins-war\1.609.2\jenkins-war-1.609.2-war-for-test.jar; error in opening zip file
[ERROR] error reading C:\Users\khurshid.khokhar\.m2\repository\org\jenkins-ci\main\jenkins-test-harness\1.609.2\jenkins-test-harness-1.609.2.jar; error in opening zip file
[ERROR] error reading C:\Users\khurshid.khokhar\.m2\repository\org\jenkins-ci\main\jenkins-war\1.609.2\jenkins-war-1.609.2-war-for-test.jar; error in opening zip file
[ERROR] /D:/Temp Hygieia/Hygieia-master/hygieia-jenkins-plugin/target/inject-tests/InjectedTest.java:[15,37] cannot find symbol
  symbol:   class PluginAutomaticTestBuilder
  location: package org.jvnet.hudson.test
[INFO] 5 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.224 s
[INFO] Finished at: 2018-01-18T19:40:14+05:30
[INFO] Final Memory: 64M/565M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:testCompile (default-testCompile) on project hygieia-publisher: Compilation failure: Compilation failure:
[ERROR] error reading C:\Users\khurshid.khokhar\.m2\repository\org\jenkins-ci\main\jenkins-test-harness\1.609.2\jenkins-test-harness-1.609.2.jar; error in opening zip file
[ERROR] error reading C:\Users\khurshid.khokhar\.m2\repository\org\jenkins-ci\main\jenkins-war\1.609.2\jenkins-war-1.609.2-war-for-test.jar; error in opening zip file
[ERROR] error reading C:\Users\khurshid.khokhar\.m2\repository\org\jenkins-ci\main\jenkins-test-harness\1.609.2\jenkins-test-harness-1.609.2.jar; error in opening zip file
[ERROR] error reading C:\Users\khurshid.khokhar\.m2\repository\org\jenkins-ci\main\jenkins-war\1.609.2\jenkins-war-1.609.2-war-for-test.jar; error in opening zip file
[ERROR] /D:/Temp Hygieia/Hygieia-master/hygieia-jenkins-plugin/target/inject-tests/InjectedTest.java:[15,37] cannot find symbol
[ERROR]   symbol:   class PluginAutomaticTestBuilder
[ERROR]   location: package org.jvnet.hudson.test
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**hygieia-jenkins-plugin is not build** 
**Please help me how to slove it.**
Configuration version
Java 1.8
Maven 3.5.2

I have also attached screen shot.

![image](https://user-images.githubusercontent.com/34913344/35102277-7b3d65b4-fc88-11e7-8b6b-a05a0f47c326.png)

**Comment by khurshid4** [comment]
Hello @all 
Please Help me, if you have any solution.

**Comment by subodhbattina** [comment]
@khurshid4 
It seems like, the maven dependency below in your local repository is missing, and therefore causing the build to fail.
"C:\Users\khurshid.khokhar.m2\repository\org\jenkins-ci\main\jenkins-test-harness\1.609.2\jenkins-test-harness-1.609.2.jar;"

Could you please:
1. Do a "git pull" to get the latest updates from the master
2. Delete everything under your C:\Users\khurshid.khokhar.m2\repository folder just in case, and then do
3. mvn clean install.

Hope this helps. Thanks !

**Comment by khurshid4** [comment]
@subodhbattina 

Thanks for response,
I have delete repository folder and also pull the latest updates project. But still not build.

**Comment by Sbrenthughes** [comment]
Are you behind a proxy? That could be one reason why your not able to get certain dependancies.

**Comment by sandipkarande** [comment]
I am facing similar issue. can some one what is the fix for this. @subodhbattina  @khurshid4  @jdamick @mspiegel

**Comment by rvema** [comment]
what is the issue you are facing? can you reach out to me in gitter? My id is @rvema

**Comment by sandipkarande** [comment]
> what is the issue you are facing? can you reach out to me in gitter? My id is @rvema

Thanks @rvema for quick response.

While excuting mvn clean install package , buid fails. It gives below error

[ERROR] Failed to execute goal on project hygieia-publisher: Could not resolve dependencies for project org.jenkins-ci.plugins:hygieia-publisher:hpi:2.1.3-SNAPSHOT: The following artifacts could not be resolved: org.jenkins-ci.main:jenkins-war:war:1.609.2, org.jenkins-ci.main:jenkins-war:jar:war-for-test:1.609.2: Could not transfer artifact org.jenkins-ci.main:jenkins-war:war:1.609.2 from/to repo.jenkins-ci.org (http://repo.jenkins-ci.org/public/): GET request of: org/jenkins-ci/main/jenkins-war/1.609.2/jenkins-war-1.609.2.war from repo.jenkins-ci.org failed: Premature end of Content-Length delimited message body (expected: 68976099; received: 33440096 -> [Help 1]

I understood that it is because of following files no more exists at respective locations. I checked by hitting those URL's in browser and download fails.
Downloading from central: https://repo.maven.apache.org/maven2/org/jenkins-ci/main/jenkins-war/1.609.2/jenkins-war-1.609.2.war
Downloading from central: https://repo.maven.apache.org/maven2/org/jenkins-ci/main/jenkins-war/1.609.2/jenkins-war-1.609.2-war-for-test.jar

Please suggest how to fix this. Will really appreciate your quick help. Thanks !!

**Comment by rvema** [comment]
@sandipkarande let me take a look and get back to you. I am unable to recreate this issue with my setup.
