### ISSUE TITLE
Unable to configure SCM widget

### ISSUE THREAD

**Issue by binnyg** [capitalone/Hygieia#1947]
https://stackoverflow.com/questions/48333466/hygieia-configure-gitlab-widget-under-scm

On a brand new Hygieia installation, I am unable to add Gitlab repo widget to the dashboard. Save button is calling the /widgets/repo/config.js:71 but it never seems to enters the if condition.

form.$valid evaluates to true
ctrl.collectors.length evalues to 0

if (form.$valid && ctrl.collectors.length) {
--
}

**Comment by subodhbattina** [comment]
@binnyg 
I think the issue may be that you have never run the Github collector even once before configuring the widget. And so the in the database there is no entry for the collector, and so the UI is failing.

Please run the Github collector once. 
From the path location "collectors/scm/github/target" under your hygieia installation:
Run the command: 
"java -jar ./github-scm-collector-2.0.5-SNAPSHOT.jar --spring.config.name=github --spring.config.location=<path to application.properties file>"

Make sure you have the following properties in your application.properties file.
These should be self-explanatory for the most part.
But if you do have any questions, please refer: http://www.capitalone.io/Hygieia/github.html

dbname=<database name>
dbhost=<database hostname>
dbport=<database port>
dbreplicaset=false
dbusername=<database username>
dbpassword=<database password>

logging.file=./logs/github.log
github.cron=0 0/5 * * * *
github.host=github.com
github.commitThresholdDays=15
github.errorThreshold=1
github.key=
github.personalAccessToken=

Any questions please let me know. Thanks !

**Comment by binnyg** [comment]
Thanks @subodhbattina 

I actually ran the collector and I have these two entries in the collectors collection.

{ "_id" : ObjectId("5a574b83fd409c0a83b3e36e"), "_class" : "com.capitalone.dashboard.model.Collector", "name" : "Product", "collectorType" : "Product", "enabled" : true, "online" : true, "errors" : [ ], "uniqueFields" : {  }, "allFields" : {  }, "lastExecuted" : NumberLong(0) }
{ "_id" : ObjectId("5a6873240f30ea2304953ad7"), "_class" : "com.capitalone.dashboard.model.Collector", "name" : "Gitlab", "collectorType" : "SCM", "enabled" : true, "online" : false, "errors" : [ ], "uniqueFields" : { "branch" : "", "url" : "" }, "allFields" : { "password" : "", "lastUpdate" : ISODate("2018-01-27T14:14:00.022Z"), "branch" : "", "userID" : "", "url" : "" }, "lastExecuted" : NumberLong("1517062440028") }

**Comment by Sbrenthughes** [comment]
1) navigate the the dashboard
2) click on the code repo widget
3) Select "Github" From the Repo Type selection 
4) Insert url/ Credentials
After clicking "Save" you don't see any errors on the page? What about in the API logs?

**Comment by binnyg** [comment]
No errors neither in the server console nor javascript errors in browser console

**Comment by Sbrenthughes** [comment]
When you go to the login page do you have a green check by the API? Have you taken the latest code?

**Comment by matthewbeasley** [comment]
@binnyg - I actually ran into the same issue when I first set up my local. It seems that the collector hasn't registered itself with the db yet. Try lowering your cron to something like `*/30 * * * * *` and re-run your collector. Check the logs of the collector to ensure that you are actually getting data. After an iteration or two you should be able to set up your widget.

**Comment by binnyg** [comment]
The code was about 3 weeks old, I will update again. I was able to run the Gitlab collector with necessary configuration. It is unable to retrieve repositories with my configuration.

2018-02-04 08:53:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Gitlab
2018-02-04 08:53:00,050 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-02-04 08:53:00,050 INFO  c.c.d.collector.CollectorTask - Starting...
2018-02-04 08:53:00,050 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-02-04 08:53:00,061 INFO  c.c.d.c.GitlabGitCollectorTask - []
2018-02-04 08:53:00,070 INFO  c.c.d.c.GitlabGitCollectorTask - []
2018-02-04 08:53:00,081 INFO  c.c.d.c.GitlabGitCollectorTask - list []
2018-02-04 08:53:00,082 INFO  c.c.d.collector.CollectorTask - Repo Count              0        0s
2018-02-04 08:53:00,082 INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2018-02-04 08:53:00,082 INFO  c.c.d.collector.CollectorTask - Finished                         0s

Configuration file:
[application.properties.txt](https://github.com/capitalone/Hygieia/files/1705622/application.properties.txt)

**Comment by binnyg** [comment]
How does it retrieve repositories? I was under impression that gitlab.apiToken will be used to gain access to private repositories. Is that accurate? I have a feeling I am doing something wrong with my configuration file.

**Comment by binnyg** [comment]
I got the latest code and was able to configure the gitlab collector. Thanks for the support.
