### ISSUE TITLE
Sonar Connection Failed. Response: 404 

### ISSUE THREAD

**Issue by AmeySuhasDhuri** [capitalone/Hygieia#1948]
Hi,
I have configure Hygieia Publiser in jenkins but only build widget data displayed on dashboard not getting data for quality and performance widget.
We are using sonarqube 6.7 to get the data for unit test and major minor issues but not displaying.
![image](https://user-images.githubusercontent.com/30716027/35151789-b314adb8-fd45-11e7-838b-ab915e26c4eb.png)
![image](https://user-images.githubusercontent.com/30716027/35152068-d957d3a0-fd46-11e7-9bdb-2983a39bd2d7.png)

Please help us to fix it.

**Comment by KN5028051** [comment]
@tabladrum please help to resolve mention issue.

**Comment by pversteijnen** [comment]
This issue is fixed in the latest merge. But the docker Container is not updated in the Docker Store/Hub. Is there no automated build/deploy process that does this after a merge to master?

**Comment by Sbrenthughes** [comment]
Not currently. We are working on a process to get the imagines updated. @KN5028051 Please reopen if your issues is not resolved.

**Comment by oscarr-reyes** [comment]
i also have this issue but i have hygieia installed from a clone download rather than a docker image
