### ISSUE TITLE
Docker containers are outdated

### ISSUE THREAD

**Issue by pversteijnen** [capitalone/Hygieia#1955]
Who is responsible for updating the Docker Images in the public registry? These Images in most cases are updated one year ago. Can someone please update the Containers with the latest Versions of Hygieia?

We are using the Docker-Compose Approach to Setup the Hygieia Environment but it is not helping to have one year old Images.

**Comment by matthewbeasley** [comment]
@pversteijnen - this is something we are working on. In the meantime, just clone the repo, run `mvn clean install docker:build` and you'll have updated images locally. From there you can push them to your own registry. Currently using our Docker images for production deployments is not recommended. Again, this is something that we are currently working on so stay tuned for a PR on this within the next couple months.
