### ISSUE TITLE
Compile Failure in api-audit

### ISSUE THREAD

**Issue by orsond** [capitalone/Hygieia#1964]
This is from cloning the project, master branch. If I replace the com.capitalone.dashboard.model.DashboardAuditModel.evaluatorMap() method with an empty map the project builds just fine. Once I revert the code it fails. I'm using:
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T02:58:13-05:00)
Maven home: C:\apache-maven-3.5.2\bin\..
Java version: 1.8.0_31, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_31\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project
 api-audit: Compilation failure
[ERROR] /c:/workspaceHygieia/Hygieia/api-audit/src/main/java/com/capitalone/dashboard/model/DashboardAudi
tModel.java:[40,43] incompatible types: inference variable V has incompatible bounds
[ERROR]     equality constraints: com.capitalone.dashboard.evaluator.Evaluator
[ERROR]     lower bounds: ? extends com.capitalone.dashboard.evaluator.Evaluator<? extends com.capitalone.dashboard.resp
onse.AuditReviewResponse<? extends java.lang.Enum<? extends java.lang.Enum<?>>>>,U

**Comment by Sbrenthughes** [comment]
Can you try switching to 1.8.0_66?

**Comment by orsond** [comment]
I switched to 1.8.0_162 and it worked just fine. It may be worth noting that there's a minimum java patch level for java 8 in the documentation.

**Comment by Sbrenthughes** [comment]
@orsond  Will do. We just found this issue shortly before you.
