### ISSUE TITLE
Issue in starting API

### ISSUE THREAD

**Issue by PriyankaSundar** [capitalone/Hygieia#1977]
I started hygieia API and it got started with the message " Tomcat started on port(s): 8080 (http)". But still it is not getting reflected in dashboard with green tick.

Attached screen shot for your reference
![hygieia](https://user-images.githubusercontent.com/21707237/35679916-c0fd3632-077e-11e8-8dc9-72c42078b3a2.PNG)

And when I check http://localhost:8080/api/ping in brower it is showing "true"

Is the issue with API connectivity or with UI?

**Comment by Sbrenthughes** [comment]
Your UI looks out of date. Have you taken the latest code base?
