### ISSUE TITLE
Facing issue in configuring collectors

### ISSUE THREAD

**Issue by PriyankaSundar** [capitalone/Hygieia#1978]
I have configured jenkins-build-collector and getting the values from jenkins in Eclipse.

Attached screenshot for your reference
![hygieia1](https://user-images.githubusercontent.com/21707237/35680199-a8d3338a-077f-11e8-8c29-d585e933e693.PNG)

But I dont see any options to configure Build widget in Hygieia dashboard. And also facing issues in creating new dashboard.

![hygieia3](https://user-images.githubusercontent.com/21707237/35680416-4da9f614-0780-11e8-9c8e-2ad38d3d6489.PNG)

**Comment by Sbrenthughes** [comment]
Can you paste the stack trace from your api logs?

**Comment by PriyankaSundar** [comment]
I have checked-in the latest code of Hygieia and now I can able to create my dashboard. Thanks for your help :)
