### ISSUE TITLE
For Hygieia 2.0 

### ISSUE THREAD

**Issue by softwareklinic** [capitalone/Hygieia#198]
For 2.0 i was looking @ the pulse and seems we are considering Influx v/s Graphite - Grafana and Graphite have great integration and grafana is a great dashboard... So, ideally you are addressing couple of things... keep the current hygieia dashboard - and those who want to chart out using grafana can do based on graphite... grafana also supports influx... but graphite is still better support for grafana...

**Comment by softwareklinic** [comment]
Any inputs --- I've used graphite and grafana - and they are made for each other.. influx db is great... but grafana UI is extremely slow - to work with when querying the influxDB objects... please check this out before you finalize on InfluxDB... graphite is much better integrated with grafana....

**Comment by tabladrum** [comment]
@softwareklinic Thanks for the input. For now we will stay the course of current Hygieia.
