### ISSUE TITLE
Question for Hygieia

### ISSUE THREAD

**Issue by Ashissh021** [capitalone/Hygieia#1984]
Hi Team,

I want to know how to setup ldap connection in hygieia. 

Please help me if it possible as  i am not finding a proper answer.

Thanks
Ashissh

**Comment by ameetsvshah** [comment]
Add the following properties in your api/dashboard.properties file with appropraite values of your LDAP server.

auth.authenticationProviders=[Authentication types you would like to enable, defaults to STANDARD, ex: STANDARD,LDAP]
auth.ldapServerUrl=[LDAP Server URL, including port of your LDAP server]
auth.ldapUserDnPattern=[LDAP User Dn Pattern, where the username is replaced with '{0}']

# LDAP Server URL, including port of your LDAP server
auth.ldapServerUrl=[ldap://company.com:389]

# If using standard LDAP
# LDAP User Dn Pattern, where the username is replaced with '{0}'
auth.ldapUserDnPattern=[uid={0},OU=Users,dc=your,dc=company,dc=com]

If you are using ActiveDirectory with LDAP add the following properties 

# If using ActiveDirectory
# This will be the domain part of your userPrincipalName
auth.adDomain=[company.com]
# This will be your root dn
auth.adRootDn=[dc=your,dc=company,dc=com]
# This will be your active directory URL (required for AD)
auth.adUrl=[Need an example]

Hygieia Doc Reference link : https://github.com/capitalone/Hygieia/blob/gh-pages/pages/hygieia/api/api.md

After adding the above properties just run the api jar again and you will get an option of LDAP on the UI with default STANDARD (local) login.

![image](https://user-images.githubusercontent.com/16320111/35844291-c1f61380-0b32-11e8-82af-fd3f0ffb4398.png)
