### ISSUE TITLE
I don't want to scan 5000 bamboo plans

### ISSUE THREAD

**Issue by Capone1983** [capitalone/Hygieia#1990]
Hi 

Is there a way i can only look at one bamboo plan with out the bamboo collector scanning the whole server?

**Comment by nireeshT** [comment]
@Capone1983  - try changing this value in prop file and point to bamboo project 

bamboo.servers[0]=http://bamboo.company.com

**Comment by Sbrenthughes** [comment]
Please reopen if this is not your solution.

**Comment by Capone1983** [comment]
If you want to only scan your Project in Bamboo you will need to change the code in DefaultBambooClient

private static final String JOBS_URL_SUFFIX = "rest/api/latest/plan?expand=plans&max-result=2000"
To
private static final String JOBS_URL_SUFFIX = "rest/api/latest/project/Projectkey?expand=plans";
