### ISSUE TITLE
Need help creating a script to auto add the hygieia publish step to jenkins jobs

### ISSUE THREAD

**Issue by dpyoung31** [capitalone/Hygieia#1992]
I've started working on a script to auto add the hygieia publisher build steps to Jenkins jobs. The below is what I have so far. The script works and will add the build step to the jobs. However, I am stuck on passing the right value to enable 'Publish Build Status' in the HygieiaPublisher contructor. If someone could help point me in the right direction that would be great

for (item in Hudson.instance.items) {
  if (item instanceof com.cloudbees.hudson.plugins.folder.Folder || item instanceof org.jenkinsci.plugins.workflow.job.WorkflowJob){
    println(item.name + " can't include, skipping")
  }else{
  notification = item.getPublishersList()
  if(notification.empty){
     println("$item.name doesn't have the hygieia plugin installed")
     hygieia = new jenkins.plugins.hygieia.HygieiaPublisher(null, null, null, null, null)
     item.getPublishersList().add(hygieia)
     item.save()
  }else{
    for(n in notification){
  		n = (String)n
  		if (n.contains("jenkins.plugins.hygieia.HygieiaPublisher")) {
    	println("$item.name does have the hygieia plugin installed")
  			}
        else if ((n.contains("jenkins.plugins.hygieia.HygieiaPublisher")) == false){
      		println("$item.name doesn't have the hygieia plugin installed")
    	}
    	}
  	}
  }
 
}

**Comment by nireeshT** [comment]
@dpyoung31  - possible values for build status in pipeline script 

hygieiaBuildPublishStep buildStatus: 'Success'
hygieiaBuildPublishStep buildStatus: 'InProgress'
hygieiaBuildPublishStep buildStatus: 'Failure'
