### ISSUE TITLE
api-audit : mvn docker:build failure

### ISSUE THREAD

**Issue by OualidBourgou** [capitalone/Hygieia#1994]
Hey there I have some issues, could you help please ? 

➜  Hygieia git:(master) mvn docker:build[INFO] Scanning for projects...
[WARNING] The POM for org.jenkins-ci.tools:maven-hpi-plugin:jar:1.106 is missing, no dependency information available
[WARNING] Failed to build parent project for org.jenkins-ci.plugins:hygieia-publisher:hpi:2.0.5-SNAPSHOT
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.capitalone.dashboard:api:jar:2.0.5-SNAPSHOT
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.capitalone.dashboard:api-audit:jar:2.0.5-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: javax.validation:validation-api:jar -> duplicate declaration of version 1.1.0.Final @ com.capitalone.dashboard:api-audit:[unknown-version], /Users/oualid/Pro/carrefour/vagrant/Hygieia/api-audit/pom.xml, line 252, column 21
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.hibernate:hibernate-validator:jar -> duplicate declaration of version (?) @ com.capitalone.dashboard:api-audit:[unknown-version], /Users/oualid/Pro/carrefour/vagrant/Hygieia/api-audit/pom.xml, line 257, column 21
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.google.code.gson:gson:jar -> duplicate declaration of version (?) @ com.capitalone.dashboard:api-audit:[unknown-version], /Users/oualid/Pro/carrefour/vagrant/Hygieia/api-audit/pom.xml, line 261, column 21
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.jenkins-ci.plugins:hygieia-publisher:hpi:2.0.5-SNAPSHOT
[WARNING] 'parent.relativePath' of POM org.jenkins-ci.plugins:hygieia-publisher:2.0.5-SNAPSHOT (/Users/oualid/Pro/carrefour/vagrant/Hygieia/hygieia-jenkins-plugin/pom.xml) points at com.capitalone.dashboard:Hygieia instead of org.jenkins-ci.plugins:plugin, please verify your project structure @ line 15, column 13
[WARNING] 'build.plugins.plugin.version' for com.spotify:docker-maven-plugin is missing. @ line 232, column 21
[WARNING] 'build.plugins.plugin.version' for org.jacoco:jacoco-maven-plugin is missing. @ line 214, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] com.capitalone.dashboard:Hygieia
[INFO] com.capitalone.dashboard:core
[INFO] com.capitalone.dashboard:api
[INFO] com.capitalone.dashboard:api-audit
[INFO] com.capitalone.dashboard:artifactory-artifact-collector
[INFO] com.capitalone.dashboard:bamboo-build-collector
[INFO] com.capitalone.dashboard:jenkins-build-collector
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector
[INFO] com.capitalone.dashboard:jenkins-codequality
[INFO] com.capitalone.dashboard:sonar-codequality-collector
[INFO] com.capitalone.dashboard:aws-cloud-collector
[INFO] com.capitalone.dashboard:udeploy-deployment-collector
[INFO] com.capitalone.dashboard:xldeploy-deployment-collector
[INFO] com.capitalone.dashboard:jira-feature-collector
[INFO] com.capitalone.dashboard:versionone-feature-collector
[INFO] com.capitalone.dashboard:gitlab-feature-collector
[INFO] com.capitalone.dashboard:chat-ops-collector
[INFO] com.capitalone.dashboard:appdynamics-performance-collector
[INFO] com.capitalone.dashboard:bitbucket-scm-collector
[INFO] com.capitalone.dashboard:github-scm-collector
[INFO] com.capitalone.dashboard:github-graphql-scm-collector
[INFO] com.capitalone.dashboard:subversion-collector
[INFO] com.capitalone.dashboard:gitlab-scm-collector
[INFO] com.capitalone.dashboard:hpsm-cmdb-collector
[INFO] com.capitalone.dashboard:nexus-iq-collector
[INFO] Hygieia Publisher Plugin
[INFO] com.capitalone.dashboard:UI
[INFO] com.capitalone.dashboard:ui-tests
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building com.capitalone.dashboard:Hygieia 2.0.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- docker-maven-plugin:0.4.10:build (default-cli) @ Hygieia ---
[INFO] Skipping docker build
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building com.capitalone.dashboard:core 2.0.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- docker-maven-plugin:0.4.10:build (default-cli) @ core ---
[INFO] Skipping docker build
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building com.capitalone.dashboard:api 2.0.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- docker-maven-plugin:0.4.10:build (default-cli) @ api ---
[INFO] Copying /Users/oualid/Pro/carrefour/vagrant/Hygieia/api/target/api.jar -> /Users/oualid/Pro/carrefour/vagrant/Hygieia/api/target/docker/hygieia/api.jar
[INFO] Copying /Users/oualid/Pro/carrefour/vagrant/Hygieia/api/docker/api-properties-builder.sh -> /Users/oualid/Pro/carrefour/vagrant/Hygieia/api/target/docker/api-properties-builder.sh
[INFO] Copying /Users/oualid/Pro/carrefour/vagrant/Hygieia/api/docker/Dockerfile -> /Users/oualid/Pro/carrefour/vagrant/Hygieia/api/target/docker/Dockerfile
[INFO] Copying /Users/oualid/Pro/carrefour/vagrant/Hygieia/api/docker/README.md -> /Users/oualid/Pro/carrefour/vagrant/Hygieia/api/target/docker/README.md
[INFO] Building image hygieia-api
Step 1/9 : FROM docker.io/openjdk:8-jre
 ---> c49bf7000580
Step 2/9 : MAINTAINER Hygieia@capitalone.com
 ---> Using cache
 ---> 217064df95d9
Step 3/9 : RUN mkdir /hygieia /hygieia/config
 ---> Using cache
 ---> a10bf43b84b9
Step 4/9 : COPY hygieia/ /hygieia
 ---> acfcdc5a22ba
Step 5/9 : COPY api-properties-builder.sh /hygieia/
 ---> 46d34539ae7e
Step 6/9 : WORKDIR /hygieia
 ---> 69ec2493dcd9
Removing intermediate container 4c23878350ab
Step 7/9 : VOLUME /hygieia/logs
 ---> Running in 42d29e79b35d
 ---> 6615651ba682
Removing intermediate container 42d29e79b35d
Step 8/9 : EXPOSE 8080
 ---> Running in e74a5707a3d9
 ---> ff92a4d72e7f
Removing intermediate container e74a5707a3d9
Step 9/9 : CMD ./api-properties-builder.sh &&  java -Djava.security.egd=file:/dev/./urandom -jar api.jar --spring.config.location=/hygieia/config/hygieia-api.properties
 ---> Running in 1de8a3bc26d5
 ---> 352bfaee9207
Removing intermediate container 1de8a3bc26d5
ProgressMessage{id=null, status=null, stream=null, error=null, progress=null, progressDetail=null}
Successfully built 352bfaee9207
Successfully tagged hygieia-api:latest
[INFO] Built hygieia-api
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building com.capitalone.dashboard:api-audit 2.0.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- docker-maven-plugin:0.4.10:build (default-cli) @ api-audit ---
[INFO] No resources will be copied, no files match specified patterns
[INFO] Copying /Users/oualid/Pro/carrefour/vagrant/Hygieia/api-audit/docker/api-audit-properties-builder.sh -> /Users/oualid/Pro/carrefour/vagrant/Hygieia/api-audit/target/docker/api-audit-properties-builder.sh
[INFO] Copying /Users/oualid/Pro/carrefour/vagrant/Hygieia/api-audit/docker/Dockerfile -> /Users/oualid/Pro/carrefour/vagrant/Hygieia/api-audit/target/docker/Dockerfile
[INFO] Copying /Users/oualid/Pro/carrefour/vagrant/Hygieia/api-audit/docker/README.md -> /Users/oualid/Pro/carrefour/vagrant/Hygieia/api-audit/target/docker/README.md
[INFO] Building image hygieia-apiaudit
Step 1/9 : FROM docker.io/java:openjdk-8-jdk
 ---> d23bdf5b1b1b
Step 2/9 : MAINTAINER Hygieia@capitalone.com
 ---> Using cache
 ---> 21093b96d01e
Step 3/9 : RUN mkdir /hygieia /hygieia/config
 ---> Using cache
 ---> 5c5f6b776e59
Step 4/9 : COPY hygieia /hygieia
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] com.capitalone.dashboard:Hygieia ................... SUCCESS [  0.916 s]
[INFO] com.capitalone.dashboard:core ...................... SUCCESS [  0.008 s]
[INFO] com.capitalone.dashboard:api ....................... SUCCESS [ 11.714 s]
[INFO] com.capitalone.dashboard:api-audit ................. FAILURE [  0.510 s]
[INFO] com.capitalone.dashboard:artifactory-artifact-collector SKIPPED
[INFO] com.capitalone.dashboard:bamboo-build-collector .... SKIPPED
[INFO] com.capitalone.dashboard:jenkins-build-collector ... SKIPPED
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SKIPPED
[INFO] com.capitalone.dashboard:jenkins-codequality ....... SKIPPED
[INFO] com.capitalone.dashboard:sonar-codequality-collector SKIPPED
[INFO] com.capitalone.dashboard:aws-cloud-collector ....... SKIPPED
[INFO] com.capitalone.dashboard:udeploy-deployment-collector SKIPPED
[INFO] com.capitalone.dashboard:xldeploy-deployment-collector SKIPPED
[INFO] com.capitalone.dashboard:jira-feature-collector .... SKIPPED
[INFO] com.capitalone.dashboard:versionone-feature-collector SKIPPED
[INFO] com.capitalone.dashboard:gitlab-feature-collector .. SKIPPED
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SKIPPED
[INFO] com.capitalone.dashboard:appdynamics-performance-collector SKIPPED
[INFO] com.capitalone.dashboard:bitbucket-scm-collector ... SKIPPED
[INFO] com.capitalone.dashboard:github-scm-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:github-graphql-scm-collector SKIPPED
[INFO] com.capitalone.dashboard:subversion-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:gitlab-scm-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:hpsm-cmdb-collector ....... SKIPPED
[INFO] com.capitalone.dashboard:nexus-iq-collector ........ SKIPPED
[INFO] Hygieia Publisher Plugin ........................... SKIPPED
[INFO] com.capitalone.dashboard:UI ........................ SKIPPED
[INFO] com.capitalone.dashboard:ui-tests .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.901 s
[INFO] Finished at: 2018-02-07T19:49:32+01:00
[INFO] Final Memory: 47M/739M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.10:build (default-cli) on project api-audit: Exception caught: COPY failed: stat /var/lib/docker/tmp/docker-builder357288815/hygieia: no such file or directory -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :api-audit

Configuration version
Docker version 17.09.0-ce, build afdb6d4
Maven 3.5.2
java version 1.8.0_25, vendor: Oracle Corporation

**Comment by matthewbeasley** [comment]
@OualidBourgou - I believe this is a java version issue. Try something like 1.8.0_141.

**Comment by OualidBourgou** [comment]
Yes thanks @matthewbeasley I have indeed changed the version of Java (for openjdk version "1.8.0_151") and it worked ! :)

**Comment by matthewbeasley** [comment]
@OualidBourgou - Awesome!
