### ISSUE TITLE
jira collector documentation 

### ISSUE THREAD

**Issue by tongqqiu** [capitalone/Hygieia#20]
Can you explain more about the jira collector configuration, especially the following part?

```
#In-built folder housing prepared REST queries (required)
feature.queryFolder=jiraapi-queries

#Jira API Query file names (String template requires the files to have .st extension) (required)
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo
```

**Comment by amp5208** [comment]
Yes - those are references to prepared ST query statements for Jira (you can review the queries at <strong>/src/main/resources/jiraapi-queries/</strong> ).  You should not have to modify those properties; simply leave them as noted your your above post.  Please note, some of these queries are not even being used at this time.

Let me know if you have any further questions regarding the feature collectors or their corresponding API endpoints.

**Comment by amitmawkin** [comment]
tongqqiu if you are satisfied with the response, please close this issue

**Comment by amitmawkin** [comment]
closed this issue accidently, I have reopened it

**Comment by amp5208** [comment]
@amitmawkin , given that we have provided an answer to this issue and the user @tongqqiu has not responded to your re-opening of the issue, kindly consider closing this.  @tongqqiu may open a new issue if difficulty of use is still present.

**Comment by amitmawkin** [comment]
thanks Arnie closing this issue ..
