### ISSUE TITLE
JenkinsCucumber does not pull any jobs

### ISSUE THREAD

**Issue by neetusanjay** [capitalone/Hygieia#200]
Jenkins cucumber collector is not pulling any jobs, though I have many jobs using cucumber plug-in. Any help will be greatly appreciated. 

![capture5](https://cloud.githubusercontent.com/assets/13186518/11707870/4cf5db98-9ed7-11e5-940b-1d24aa0eb5e5.JPG)

**Comment by mrpudn** [comment]
Closing this - please open a new issue if the problem persists
