### ISSUE TITLE
No Sprint data on Sprint end dates

### ISSUE THREAD

**Issue by e-macias** [capitalone/Hygieia#2008]
Hi,

On days the sprint ends, the feature widget for Jira displays all 0's for all values regardless if displaying hours, story points, or issue count. 

Is this expected behavior? I am not sure how sprint information is gathered, but the tickets still have the "Sprint" tag for the closed sprint. I would think that displaying sprint information (regarding story points open, in-progress, and closed) would still be useful on the days a sprint ends. After the end date, perhaps displaying all 0's might be appropriate, but before and including the end date, that information still seems valid to display. 

Any help would be greatly appreciated, thank you.

**Comment by e-macias** [comment]
Hi, @MarkRx @Sbrenthughes 

Just wondering if there are any possible insights into this? If this is expected behavior or not, many thanks. 

To give some details regarding the issue, below are some images that I hope help describe the problem I am facing. 

This is how the feature widget appears (on days the sprint ends):
![feature](https://user-images.githubusercontent.com/2696304/36559397-b3260c92-17c2-11e8-902a-7c0d1ccc832a.png)

And here is a ticket that is currently "in progress", tagged with the sprint that ended (note, the sprint that just ended, is "sprint 28"):
![sprint](https://user-images.githubusercontent.com/2696304/36559621-663690ae-17c3-11e8-9988-bf711abc60a6.png)

**Comment by e-macias** [comment]
After further investigation, it appears that the logic for determining what to send the UI is applied in the API layer, specifically [FeatureServiceImpl.java](https://github.com/capitalone/Hygieia/blob/master/api/src/main/java/com/capitalone/dashboard/service/FeatureServiceImpl.java#L451) calls [FeatureRepositoryImpl.java](https://github.com/capitalone/Hygieia/blob/master/core/src/main/java/com/capitalone/dashboard/repository/FeatureRepositoryImpl.java#L27) to construct a query string that will determine which features belong to the current sprint.

However, it is unclear what is meant by "**_any_**" in the following statement: "A feature is part of a scrum sprint if any of the following are true: -the feature has a sprint set that has start <= now <= end and end < EOT (9999-12-31T59:59:59.999999)". Where are the "break points" of the statement, to determine if "_any_" part is true? Because it seems as if "end < EOT" will always be true. 

Yet the UI is receiving no values from the API. Looking some of the rest responses:
```
{"result":{"openEstimate":0,"inProgressEstimate":0,"completeEstimate":0,"totalEstimate":0},"lastUpdated":1519422312519}
```
and 
```
{"result":[],"lastUpdated":1519422312519}
```

By editing [FeatureRepositoryImpl's query build](https://github.com/capitalone/Hygieia/blob/master/core/src/main/java/com/capitalone/dashboard/repository/FeatureRepositoryImpl.java#L36) to evaluate 'sSprintEndDate' as less than the current date (rather than _greater than_), I can see what appears to be proper end of Sprint handling (see image below). Looking at some responses now gives:
```
{"result":{"openEstimate":6,"inProgressEstimate":12,"completeEstimate":42,"totalEstimate":60},"lastUpdated":1519422317357}
```
and
```
{"result":[{"sEstimate":"0","sEpicName":"Technical Improvements","sEpicUrl":"https://jira.com ....} 
``` 

Therefore my question now becomes, how should end of Sprint be handled? Is the change I made the correct implementation to take, or would you advice a different approach? Thanks.

**Code change**: ```{'sSprintEndDate' : {$lt : '" + currentISODateTime + "'}}```


![feature_update](https://user-images.githubusercontent.com/2696304/36619111-74dcab90-18a2-11e8-9f1b-92c6d088b54b.png)

**Comment by MarkRx** [comment]
Data will not show up for sprints if the sprint is over. You could change your sprint end date to be 11:59:59 and it should continue to show up the day it "ends". 

If you were to make that proposed change then you would not see any data for active sprints as active sprints would be start date <= now <= end. What you have is start date <= now > end which does not make sense.

**Comment by e-macias** [comment]
@MarkRx, thanks for the response. I agree that my implementation is not the ideal solution. However, is there then a scenario where the "[ENDED]" tag will display?

In our current setup, there is usually about one to one-and-a-half days between sprints.

**Comment by MarkRx** [comment]
Currently it appears to only show active sprints. I suppose the query could be changed so as to pick up the last sprint even if it is ended.
