### ISSUE TITLE
Fix broken link - Gitlab documentation

### ISSUE THREAD

**Issue by binnyg** [capitalone/Hygieia#2010]
http://capitalone.github.io/Hygieia/gitlab.html

Below link points to a webpage with no information on generating the gitlab key.

Note: For information on generating your Gitlab key for private repos, refer to [Encryption of Private Repos](https://github.com/capitalone/Hygieia/blob/gh-pages/pages/hygieia/UI/ui.md#encryption-for-private-repos).

**Comment by Megha849** [comment]
@binnyg Refer to [Encryption of Private Repos](http://capitalone.github.io/Hygieia/setup.html#encryption-for-private-repos).
The link is now available in the [Gitlab](http://capitalone.github.io/Hygieia/gitlab.html) document as well.
