### ISSUE TITLE
"Global hygiea publisher settings" always returns true on Test connection with Invalid Urls

### ISSUE THREAD

**Issue by vignesh-paramasivam** [capitalone/Hygieia#2027]
I have installed the hygieia jenkins plugin using .hpi file, and in the jenkins configuration, i have provided the api url and did the test connection, where the connection returned Success.

But there is no data in the hygieia dashboard. So, i have modified the incorrect api url and verified and still it returned success, which is incorrect. Also, Testing the connection with empty url is also returning Success.

How this can be resolved and validated if it is working or not?

![image](https://user-images.githubusercontent.com/6512561/36199231-e9eda804-119e-11e8-82dd-6d543443e56b.png)

**Comment by tabladrum** [comment]
Just to confirm - did you "save" the change before testing? Jenkins config screens are little weird that way.

**Comment by vignesh-paramasivam** [comment]
Test connection worked on applying save to change changes.
Also, Test connection is getting Success for ports 3000(UI access) and 8080. Is this a right behavior?

**Comment by vignesh-paramasivam** [comment]
This is working thanks!
