### ISSUE TITLE
Should publish the JAR files as well for collector... 

### ISSUE THREAD

**Issue by softwareklinic** [capitalone/Hygieia#204]
There are still some compile/build issues with the Maven build due to protected / private access of certain methods...

**Comment by tabladrum** [comment]
@softwareklinic can you post the build error log?

**Comment by softwareklinic** [comment]
I just left comment on this issue where another user had exact same issue with protected vs private access of same method.

https://github.com/capitalone/Hygieia/issues/206

**Comment by tabladrum** [comment]
@softwareklinic this should be fine now. If you agree, lets close it.

**Comment by softwareklinic** [comment]
Yes closing
