### ISSUE TITLE
UI build failure on linux7/Centos7 

### ISSUE THREAD

**Issue by pk277** [capitalone/Hygieia#2040]
Getting below error while building Hygieia on linux7 and centos7.   Followed the steps mentioned on Hygieia docs. Not sure whats wrong. Any one  has ran into similar issue ? Please share if there is any fix to the below issue
Current node, npm and bower versions. 

node: v9.5.0
npm: 5.6.0
bower: 1.8.2

[INFO] Found proxies: []
[INFO] Running 'bower install' in /apps/Hygieia/UI
[ERROR] bower ESUDO         Cannot be run with sudo
[ERROR]
[ERROR] Additional error details:
[ERROR] Since bower is a user command, there is no need to execute it with superuser permissions.
[ERROR] If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.
[ERROR]
[ERROR] http://www.joyent.com/blog/installing-node-and-npm
[ERROR] https://gist.github.com/isaacs/579814
[ERROR]
[ERROR] You can however run a command with sudo using --allow-root option
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:04 min
[INFO] Finished at: 2018-02-18T07:52:39+00:00
[INFO] Final Memory: 17M/254M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.29:bower (bower install) on project UI: Failed to run task: 'bower install' failed. (error code 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[root@ip-172-31-83-135 UI]#

Thanks

**Comment by matthewbeasley** [comment]
@pk277 - what commands did you run exactly? It seems like from the errors logs that you ran `sudo bower install` -- try `bower install` instead.

**Comment by pk277** [comment]
@matthewbeasley 

 I was executing all the commands as root user. Now UI build is success with non root user. API, UI and mongoBD are up and now i am able to access dashboard through browser. Thanks much for yout help

Now i am trying to build the docket image for the UI using below command but  running into below issue. i verified no service is running on port 80.

FYI; I ran the command "mvn clean install docker:build" on /hygieia/UI directory as a non root user. Can you help figure out what is the issue here. 

[INFO] Copying /opt/Hygieia/UI/docker/default.conf -> /opt/Hygieia/UI/target/docker/default.conf
[INFO] Building image hygieia-ui
Feb 20, 2018 5:11:12 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: Permission denied
Feb 20, 2018 5:11:12 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->unix://localhost:80
Feb 20, 2018 5:11:12 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: Permission denied
Feb 20, 2018 5:11:12 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->unix://localhost:80
Feb 20, 2018 5:11:12 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: Permission denied
Feb 20, 2018 5:11:12 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->unix://localhost:80
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:01 min
[INFO] Finished at: 2018-02-20T17:11:12-06:00
[INFO] Final Memory: 31M/119M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.10:build (default-cli) on project UI: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: Permission denied -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException


Thanks

**Comment by matthewbeasley** [comment]
@pk277 - I've never seen this before. Try running without the container first. Run this sequence:
```bash
npm install
bower install
gulp serve
```
Your browser should open automatically to the UI. Let me know if this works and then we can take the next step.

**Comment by pk277** [comment]
@matthewbeasley 

I ran the commands successfully and i can see the UI loaded fine in browser. But when i try to build docker image foe the UI component i am running into above issue. 

Thanks

**Comment by matthewbeasley** [comment]
@pk277 - when you run commands like `docker ps` do you need sudo?

**Comment by pk277** [comment]
@matthewbeasley 
Sorry for the delay in reply. Yes docker ps requires sudo. After fixing the issue now i am able to build docker images.  Thanks much for all the help.
