### ISSUE TITLE
Pipeline widget

### ISSUE THREAD

**Issue by sachingupta771** [capitalone/Hygieia#2041]
hey, can someone pls help in configuring pipeline widget in hygieia , have read  many earlier issues but no one helped. 
i know that jenkins hygieia publisher plugin is to be used and configured in all jenkins jo we want to see in deploy wiget that would be further reflected in pipeline widget but still not able to setup it on my hygiea console.

getting following error in jenkins job while plugin tries to publish data
Hygieia: Failed Publishing Deploy Data:Response Code: 404. Response Value= <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /</pre>
</body>
</html>

**Comment by nireeshT** [comment]
@sachingupta771  Please share below details 
Jenkins version 
Jenkins job type - freestyle/pipeline
build artifact - Eg - *.war, * ear, *. jar .

share screenshot of freestyle job / pipelinescript. 
Jenkins console log. 
Please mask all the confidential information.

**Comment by nireeshT** [comment]
@sachingupta771  reopen if issue is not resolved
