### ISSUE TITLE
Bitbucket Collector

### ISSUE THREAD

**Issue by softwareklinic** [capitalone/Hygieia#205]
Bitbucket version in readme.md is 1.0 v/s in the bitbucket resources folder it is 2.0 - and that is really very confusing...also, you should provide some sample of Bitbucket or stash url that we could add to the dashboard... 1.0 and 2.0 urls looks  different and we are not getting the data from bitbucket as expected....

**Comment by hygieia** [comment]
@softwareklinic is this still an issue...?

**Comment by amitmawkin** [comment]
@softwareklinic is this still an issue?

**Comment by softwareklinic** [comment]
No - closing - we have these sorted out
