### ISSUE TITLE
Hygieia Question

### ISSUE THREAD

**Issue by Ashissh021** [capitalone/Hygieia#2053]
Hi Team,

Have few question about the hygieia and there widgets.
1) Can we customize the hygieia widgets (like for UCD it show me the components, environment and some property details) is this something possible?

2) Can we get some summery graph kind of things in dash board (like total no of application is X and total successful is Y and error out is Z) something like this?

3) Can we customize the collectors position in Dashboard?

4) Can we create a group login and later add user in that group and provide a limited access to that group?

Please help me out with above questions, and if it can be done, let me know the steps or procedure.

Thanks in Advance,
Ashish

**Comment by Sbrenthughes** [comment]
1) You can't really customize them any further than what you can now
2) We have a Exec dashboard coming that will give more details about dashboards etc
3) This is coming very soon. Along with the ability to have multiple same type widgets on the dashboard
4) There are no groups in Hygieia like this.

**Comment by Sbrenthughes** [comment]
Please close if this response gives you all the information you are looking for.

**Comment by AdinaNgr** [comment]
Hi, 
@Sbrenthughes regarding answer 3: when is that feature coming, can you give an estimate?
Thanks

**Comment by Sbrenthughes** [comment]
This is a WIP, contributions are always welcome to help speed it along!
