### ISSUE TITLE
Getting Errors Building Stash Collector

### ISSUE THREAD

**Issue by wflentje** [capitalone/Hygieia#206]
When I run the following:

mvn -Dpmd.failOnViolation=false install  -X

I am getting the following errors.  Any help appreciated.

[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/V808278/Downloads/Hygieia-master/Hygieia-master/stash-scm-coll
ector/src/main/java/com/capitalone/dashboard/collector/GitCollectorTask.java:[16
3,18] log(java.lang.String,long) in com.capitalone.dashboard.collector.GitCollec
torTask cannot override log(java.lang.String,long) in com.capitalone.dashboard.c
ollector.CollectorTask
  attempting to assign weaker access privileges; was protected
[ERROR] /C:/Users/V808278/Downloads/Hygieia-master/Hygieia-master/stash-scm-coll
ector/src/main/java/com/capitalone/dashboard/collector/GitCollectorTask.java:[16
7,18] log(java.lang.String,long,java.lang.Integer) in com.capitalone.dashboard.c
ollector.GitCollectorTask cannot override log(java.lang.String,long,java.lang.In
teger) in com.capitalone.dashboard.collector.CollectorTask
  attempting to assign weaker access privileges; was protected
[ERROR] /C:/Users/V808278/Downloads/Hygieia-master/Hygieia-master/stash-scm-coll
ector/src/main/java/com/capitalone/dashboard/collector/GitCollectorTask.java:[18
2,18] logBanner(java.lang.String) in com.capitalone.dashboard.collector.GitColle
ctorTask cannot override logBanner(java.lang.String) in com.capitalone.dashboard
.collector.CollectorTask
  attempting to assign weaker access privileges; was protected
[INFO] 3 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.400 s
[INFO] Finished at: 2015-12-10T13:33:43-07:00
[INFO] Final Memory: 29M/299M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.
1:compile (default-compile) on project stash-scm-collector: Compilation failure:
 Compilation failure:
[ERROR] /C:/Users/V808278/Downloads/Hygieia-master/Hygieia-master/stash-scm-coll
ector/src/main/java/com/capitalone/dashboard/collector/GitCollectorTask.java:[16
3,18] log(java.lang.String,long) in com.capitalone.dashboard.collector.GitCollec
torTask cannot override log(java.lang.String,long) in com.capitalone.dashboard.c
ollector.CollectorTask
[ERROR] attempting to assign weaker access privileges; was protected
[ERROR] /C:/Users/V808278/Downloads/Hygieia-master/Hygieia-master/stash-scm-coll
ector/src/main/java/com/capitalone/dashboard/collector/GitCollectorTask.java:[16
7,18] log(java.lang.String,long,java.lang.Integer) in com.capitalone.dashboard.c
ollector.GitCollectorTask cannot override log(java.lang.String,long,java.lang.In
teger) in com.capitalone.dashboard.collector.CollectorTask
[ERROR] attempting to assign weaker access privileges; was protected
[ERROR] /C:/Users/V808278/Downloads/Hygieia-master/Hygieia-master/stash-scm-coll
ector/src/main/java/com/capitalone/dashboard/collector/GitCollectorTask.java:[18
2,18] logBanner(java.lang.String) in com.capitalone.dashboard.collector.GitColle
ctorTask cannot override logBanner(java.lang.String) in com.capitalone.dashboard
.collector.CollectorTask
[ERROR] attempting to assign weaker access privileges; was protected
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal o
rg.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on p
roject stash-scm-collector: Compilation failure
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThre
adedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compila
tion failure
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(Abstrac
tCompilerMojo.java:858)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.ja
va:129)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:207)
        ... 20 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption

**Comment by softwareklinic** [comment]
You need to modify that line of code where the function is declared as private to protected... thats what its complaining about... this was our original issue as well, it worked after changing it from private to protected... since the parent is protected...

**Comment by softwareklinic** [comment]
[ERROR] /C:/Users/V808278/Downloads/Hygieia-master/Hygieia-master/stash-scm-coll
ector/src/main/java/com/capitalone/dashboard/collector/GitCollectorTask.java:[16
3,18] log(java.lang.String,long) in com.capitalone.dashboard.collector.GitCollec
torTask cannot override log(java.lang.String,long) in com.capitalone.dashboard.c
ollector.CollectorTask
attempting to assign weaker access privileges; was protected

**Comment by wflentje** [comment]
That fixed it thanks softwareklinic.  Changed 3 methods from private to protected.

    protected void log(String marker, long start) {
        log(marker, start, null);
    }

    protected void log(String text, long start, Integer count) {
        long end = System.currentTimeMillis();
        String elapsed = ((end - start) / 1000) + "s";
        String token2 = "";
        String token3;
        if (count == null) {
            token3 = StringUtils.leftPad(elapsed, 30 - text.length() );
        } else {
            String countStr = count.toString();
            token2 = StringUtils.leftPad(countStr, 20 - text.length() );
            token3 = StringUtils.leftPad(elapsed, 10 );
        }
        LOG.info(text + token2 + token3);
    }

    protected void logBanner(String instanceUrl) {
        LOG.info("------------------------------");
        LOG.info(instanceUrl);
        LOG.info("------------------------------");

**Comment by softwareklinic** [comment]
Great, we are probably just few steps ahead of where you are :) Our Jenkins collector is working and reflecting in dashboard... but Bitbucket - after fixing all issues, it is still not showing all the commits in past date... not as and when we are committing... looks like some issue around date / timestamp interpretation ... not sure at the moment... Bitbucket issues appear in dashboard but as if they happened in past... e.g. last month.. even though those check ins were done today...

**Comment by softwareklinic** [comment]
Let me know if you have your Jira collector working - we can share and learn how to get this up and running quickly... and i want to see how we can contribute to this repository... with documentation and fixes...

**Comment by wflentje** [comment]
I am in the same place, I got the Jenkins collector working today.  Thought Stash would be easier than Jira so after I get Stash working will focus on Jira.  

I can possibly contribute with startup scripts utilizing a single property file.  Will be engaged in this for a while.

**Comment by softwareklinic** [comment]
Great… wish you the best…

**Comment by jdamick** [comment]
strange.. those methods are protected: https://github.com/capitalone/Hygieia/blob/f578102901a5f03e3b683499b4c0513bb503d5b1/core/src/main/java/com/capitalone/dashboard/collector/CollectorTask.java#L117
Perhaps there is an out of date jar or it didnt get rebuit..

**Comment by softwareklinic** [comment]
I cloned the entire repo and built entire hygieia from the root folder ... built successfully 

![hygieia](https://cloud.githubusercontent.com/assets/7537289/11733446/09591b56-9f73-11e5-9cf4-5eba30ce901d.png)

**Comment by softwareklinic** [comment]
EXCEPT STASH COLLECTOR.. why did it not build stash collector... any changes required to the POM

**Comment by tabladrum** [comment]
Stash has not been included yet in master Pom. Will do it next week. Until then you can locally do so.

**Comment by softwareklinic** [comment]
Local build fails as below...

Keyurs-MacBook-Air:Hygieia FamilyMac$ cd stash-scm-collector/
Keyurs-MacBook-Air:stash-scm-collector FamilyMac$ ls -l
total 16
-rw-r--r--  1 FamilyMac  staff  1551 Dec 10 17:26 README.md
-rw-r--r--  1 FamilyMac  staff  2863 Dec 10 17:26 pom.xml
drwxr-xr-x  5 FamilyMac  staff   170 Dec 10 19:53 src
Keyurs-MacBook-Air:stash-scm-collector FamilyMac$ mvn clean install package
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building com.capitalone.dashboard:stash-scm-collector 1.5.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ stash-scm-collector ---
[INFO] 
[INFO] >>> maven-pmd-plugin:3.5:check (default) > :pmd @ stash-scm-collector >>>
[INFO] 
[INFO] --- maven-pmd-plugin:3.5:pmd (pmd) @ stash-scm-collector ---
[WARNING] Unable to locate Source XRef to link to - DISABLED
[INFO] 
[INFO] <<< maven-pmd-plugin:3.5:check (default) < :pmd @ stash-scm-collector <<<
[INFO] 
[INFO] --- maven-pmd-plugin:3.5:check (default) @ stash-scm-collector ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.720 s
[INFO] Finished at: 2015-12-10T20:31:11-06:00
[INFO] Final Memory: 26M/280M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.5:check (default) on project stash-scm-collector: You have 7 PMD violations. For more details see: /Users/FamilyMac/Desktop/Hygieia/stash-scm-collector/target/pmd.xml -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Keyurs-MacBook-Air:stash-scm-collector FamilyMac$ cd target
Keyurs-MacBook-Air:target FamilyMac$ ls
pmd.xml	site
Keyurs-MacBook-Air:target FamilyMac$ cat pmd.xml 
<?xml version="1.0" encoding="UTF-8"?>
<pmd version="5.3.2" timestamp="2015-12-10T20:31:11.107">
<file name="/Users/FamilyMac/Desktop/Hygieia/stash-scm-collector/src/main/java/com/capitalone/dashboard/collector/DefaultBitbucketClient.java">
<violation beginline="58" endline="163" begincolumn="16" endcolumn="9" rule="ExcessiveMethodLength" ruleset="Code Size" package="com.capitalone.dashboard.collector" class="DefaultBitbucketClient" method="getCommits" externalInfoUrl="http://pmd.sourceforge.net/pmd-5.3.2/pmd-java/rules/java/codesize.html#ExcessiveMethodLength" priority="3">
Avoid really long methods.
</violation>
<violation beginline="58" endline="163" begincolumn="16" endcolumn="9" rule="NPathComplexity" ruleset="Code Size" package="com.capitalone.dashboard.collector" class="DefaultBitbucketClient" method="getCommits" externalInfoUrl="http://pmd.sourceforge.net/pmd-5.3.2/pmd-java/rules/java/codesize.html#NPathComplexity" priority="3">
The method getCommits() has an NPath complexity of 768
</violation>
<violation beginline="206" endline="212" begincolumn="25" endcolumn="25" rule="NonStaticInitializer" ruleset="Design" package="com.capitalone.dashboard.collector" class="DefaultBitbucketClient" method="createHeaders" externalInfoUrl="http://pmd.sourceforge.net/pmd-5.3.2/pmd-java/rules/java/design.html#NonStaticInitializer" priority="3">
Non-static initializers are confusing
</violation>
</file>
<file name="/Users/FamilyMac/Desktop/Hygieia/stash-scm-collector/src/main/java/com/capitalone/dashboard/collector/DefaultStashClient.java">
<violation beginline="56" endline="160" begincolumn="16" endcolumn="9" rule="ExcessiveMethodLength" ruleset="Code Size" package="com.capitalone.dashboard.collector" class="DefaultStashClient" method="getCommits" externalInfoUrl="http://pmd.sourceforge.net/pmd-5.3.2/pmd-java/rules/java/codesize.html#ExcessiveMethodLength" priority="3">
Avoid really long methods.
</violation>
<violation beginline="56" endline="160" begincolumn="16" endcolumn="9" rule="NPathComplexity" ruleset="Code Size" package="com.capitalone.dashboard.collector" class="DefaultStashClient" method="getCommits" externalInfoUrl="http://pmd.sourceforge.net/pmd-5.3.2/pmd-java/rules/java/codesize.html#NPathComplexity" priority="3">
The method getCommits() has an NPath complexity of 768
</violation>
<violation beginline="203" endline="209" begincolumn="25" endcolumn="25" rule="NonStaticInitializer" ruleset="Design" package="com.capitalone.dashboard.collector" class="DefaultStashClient" method="createHeaders" externalInfoUrl="http://pmd.sourceforge.net/pmd-5.3.2/pmd-java/rules/java/design.html#NonStaticInitializer" priority="3">
Non-static initializers are confusing
</violation>
</file>
<file name="/Users/FamilyMac/Desktop/Hygieia/stash-scm-collector/src/main/java/com/capitalone/dashboard/collector/GitCollectorTask.java">
<violation beginline="92" endline="94" begincolumn="49" endcolumn="49" rule="AvoidDeeplyNestedIfStmts" ruleset="Design" package="com.capitalone.dashboard.collector" class="GitCollectorTask" method="clean" externalInfoUrl="http://pmd.sourceforge.net/pmd-5.3.2/pmd-java/rules/java/design.html#AvoidDeeplyNestedIfStmts" priority="3">
Deeply nested if..then statements are hard to read
</violation>
</file>
</pmd>
Keyurs-MacBook-Air:target FamilyMac$

**Comment by tabladrum** [comment]
hold tight... fixing it.

**Comment by amitmawkin** [comment]
maven goal install will fix it for building it locally while we release the new version in maven central
```
mvn clean compile install package

```

try it

**Comment by tabladrum** [comment]
@softwareklinic please check now. I have not done any functional testing as I dont have access to stash or bitbucket.

**Comment by softwareklinic** [comment]
Sure will respond back in few



Regards,
Keyur

On Dec 10, 2015, at 9:25 PM, tabladrum <notifications@github.com<mailto:notifications@github.com>> wrote:


@softwareklinic<https://github.com/softwareklinic> please check now. I have not done any functional testing as I dont have access to stash or bitbucket.

**Comment by softwareklinic** [comment]
Succeeded... 

[INFO] 
[INFO] --- spring-boot-maven-plugin:1.2.5.RELEASE:repackage (default) @ stash-scm-collector ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.550 s
[INFO] Finished at: 2015-12-10T21:49:35-06:00
[INFO] Final Memory: 39M/450M
[INFO] ------------------------------------------------------------------------

**Comment by softwareklinic** [comment]
There is still one question we have around the REST API implementation for Stash/Bitbucket --- is it based on Git.. since that is different from Bitbucket/stash... we were getting commits but they were being displayed under old dates even though we committed some code today...i will try out again after the latest compilation of the collector.

**Comment by softwareklinic** [comment]
What is the FORMAT of stash URL that we add to the Hygieia UI dashboard?

**Comment by papithag** [comment]
softwareklinic ... what is the format of stash url?

**Comment by satishc1** [comment]
The build should work fine with the latest codebase. Here are some example urls
ssh://git@company.com/project/repository.git
https://username@company.com/scm/project/repository.git
ssh://git@company.com/~username/repository.git
https://username@company.com/scm/~username/repository.git
