### ISSUE TITLE
Jira Collector Handling deleted features

### ISSUE THREAD

**Issue by sraghu-rs** [capitalone/Hygieia#2060]
The Jira collector is not able to identify and mark the jira ticket as "Deleted" in MongoDB if features are deleted in Jira. MongoDB has attribute "isDeleted" but it seems this attribute is not getting populated with correct value.
Does anyone has solution to handle such cases.

**Comment by subodhbattina** [comment]
@sraghu-rs : The JIRA collector as it stands today is setting the "isDeleted" value to "false" in the code. Its in the class StoryDataClientImpl.java -> method "processFeatureData()". 

But are you referring to the "status" of the ticket by any chance? The status is being set into "sStatus" property in the mongodb.

**Comment by subodhbattina** [comment]
@sraghu-rs : Since we didn't hear back from you, assuming you don't have anymore questions , closing this issue. Thanks.
