### ISSUE TITLE
Is integration Hygieia with Mendix Tool Possible ?

### ISSUE THREAD

**Issue by kushalvam** [capitalone/Hygieia#2061]
@satishc1 @Sbrenthughes 

Hello, 

We have requirement to collect data from Mendix Tool(
https://www.mendix.com/try-now/?utm_source=developers&utm_medium=community&utm_campaign=signup
)

Wanted to know if Hygieia can do it for us ? please guide

**Comment by kushalvam** [comment]
Hi @satishc1 @tabladrum 

Can you please guide me here.

**Comment by matthewbeasley** [comment]
@kushalvam - no we cannot do it for you. We do have a guide for you to do it yourself. If you get it working we'd love to see a PR from you http://capitalone.github.io/Hygieia/create_collector.html
