### ISSUE TITLE
Bean creating error while implementing controller for new collector

### ISSUE THREAD

**Issue by pallawisingh** [capitalone/Hygieia#2063]
Hi,

I am getting below error while creating and implementing new collector in hygieia.

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'almController' defined in file [D:\Eclipse\EWSHygieia\Hygieia-master\api\target\classes\com\capitalone\dashboard\rest\AlmController.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [com.capitalone.dashboard.repository.QCDefectCountRepository]: No qualifying bean of type [com.capitalone.dashboard.repository.QCDefectCountRepository] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.capitalone.dashboard.repository.QCDefectCountRepository] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency.

**Comment by Sbrenthughes** [comment]
What does your QCDefectCountRepository class look like?

**Comment by tabladrum** [comment]
These are querydsl classes. If you are adding new repositories in the core, generate sources (via Maven or your IDE) first.

**Comment by Sbrenthughes** [comment]
Please reopen of this is still an issue @pallawisingh

**Comment by yalalasai** [comment]
@tabladrum I did also add new repository in Core...from above I did understand that we should include our repository in POM.XML. If am wrong,can you please elaborate on how to generate source.
