### ISSUE TITLE
Question - Multiple same type widgets on a given dashboard

### ISSUE THREAD

**Issue by dardanbekteshi** [capitalone/Hygieia#2066]
Hi, 
I read in another issue  - #2053 it was mentioned that having the possibility to create multiple same type widgets on a dashboard "is coming very soon". I wanted to know, is there a date or a period when that feature will be implemented and pushed into master? @Sbrenthughes 
Thanks.

**Comment by Sbrenthughes** [comment]
It is a WIP. I believe there is some code already out there working towards this goal. Feel free to contribute to help speed the process along.
