### ISSUE TITLE
Twistlock Widget

### ISSUE THREAD

**Issue by jimmylin** [capitalone/Hygieia#2067]
Hello.  Love Hygieia.  We use Twistlock Container Security platform at our client site and have reached out to them to see if they would be interested in contributing a Twistlock Hygieia collector/widget.  Is there someone we could connect them with for a technical exchange to understand the best way to build out a new collector/widget?  Thank you!!!

**Comment by tabladrum** [comment]
Absolutely. Please send me your contact email : tapabrata.pal@capitalone.com

**Comment by flickerfly** [comment]
Did this ever happen? That sounds like a useful collector for us as well.

**Comment by rvema** [comment]
@flickerfly we could not prioritize the collector for twistlock, Please contribute back by building the collector for the same. Thanks
