### ISSUE TITLE
Hygiea Support for database other then MongoDB

### ISSUE THREAD

**Issue by siddharth271** [capitalone/Hygieia#2069]
Has anybody tried to hygieia with any other sql or non sql database?

**Comment by matthewbeasley** [comment]
There's an effort currently underway to support other databases but as of right now there's no timeframe for the release of this feature.

**Comment by dai-mk** [comment]
@matthewbeasley Your comment is two years old, has there been made progress in the area of alternative databases meanwhile or is MongoDB still the only supported database?

**Comment by rvema** [comment]
@dai-mk Its being worked on actively at the moment. Please see an update in the next couple of months.
