### ISSUE TITLE
hygieia-gitlab-scm-collector 401

### ISSUE THREAD

**Issue by 2804337402** [capitalone/Hygieia#2072]
2018-03-13 09:31:00,040 INFO  c.c.d.collector.CollectorTask - Repo Count              1        0s
2018-03-13 09:31:00,040 INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2018-03-13 09:31:00,040 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2018-03-13 09:32:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Gitlab
2018-03-13 09:32:00,002 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-03-13 09:32:00,002 INFO  c.c.d.collector.CollectorTask - Starting...
2018-03-13 09:32:00,002 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-03-13 09:32:00,049 INFO  c.c.d.c.GitlabGitCollectorTask - Failed to retrieve data, the repo or collector is most likey misconfigured: http://192.168.0.64:27528/kaiser/hygieia, 401 Unauthorized

docker-compose.override.yml
version: '3'
services:
  api:
    environment:
      - DB_DATABASE:dashboarddb
      - DB_HOST:192.168.0.65
      - DB_PORT:27017
      - DB_USERNAME:dashboarduser
      - DB_PASSWORD:dbpassword
    volumes:
      - ./logs:/hygieia/logs
  
  hygieia-sonar-codequality-collector:
    environment:
      - dbusername=dashboarduser
      - dbpassword=dbpassword
      - dbname=dashboarddb
      - MONGO_PORT=tcp://192.168.0.65:27017
      - SONAR_URL=http://192.168.0.65:9000
      - SONAR_CRON=0 * * * * *
      - SONAR_USERNAME=admin
      - SONAR_PASSWORD=admin
      - SKIP_PROPERTIES_BUILDER=false

  hygieia-github-scm-collector:
     environment:
      - dbusername=dashboarduser
      - dbpassword=dbpassword
      - dbname=dashboarddb
      - MONGO_PORT=tcp://192.168.0.65:27017
      - GITHUB_HOST=github.com
      - GITHUB_CRON=0 */1 * * * *
      - GITHUB_COMMIT_THRESHOLD_DAYS=60
      - GITHUB_ERROR_THRESHOLD=3
      - PERSONAL_ACCESS_TOKEN=fc7e8c726df4334633846b9830a447b4c093f8c4
      - SKIP_PROPERTIES_BUILDER=false
   
  hygieia-jenkins-build-collector:
     environment:
      - dbusername=dashboarduser
      - dbpassword=dbpassword
      - dbname=dashboarddb
      - MONGO_PORT=tcp://192.168.0.65:27017
      - JENKINS_CRON=0 */5 * * * *  
      - JENKINS_MASTER=http://192.168.0.65:11835  
      - SKIP_PROPERTIES_BUILDER=false 

  hygieia-gitlab-scm-collector:
    environment:
      - dbusername=dashboarduser
      - dbpassword=dbpassword
      - dbname=dashboarddb
      - MONGO_PORT=tcp://192.168.0.65:27017
      - GITLAB_HOST=192.168.0.64
      - GITLAB_PROTOCOL=http
      - GITLAB_PORT=27528
      - GITLAB_CRON=0 */1 * * * *
      - GITLAB_API_TOKEN=wNY-DBKm2izqx-uH3G5s
      - GITLAB_COMMIT_THRESHOLD_DAYS=20
      - SKIP_PROPERTIES_BUILDER=false
      
  hygieia-gitlab-feature-collector:
    environment:
      - dbusername=dashboarduser
      - dbpassword=dbpassword
      - dbname=dashboarddb
      - MONGO_PORT=tcp://192.168.0.65:27017
      - GITLAB_HOST=192.168.0.64
      - GITLAB_PROTOCOL=http
      - GITLAB_PORT=27528
      - GITLAB_CRON=0 */1 * * * *
      - GITLAB_API_TOKEN=wNY-DBKm2izqx-uH3G5s
      - GITLAB_COMMIT_THRESHOLD_DAYS=20
      - SKIP_PROPERTIES_BUILDER=false
docker-compose.yml
version: '3'
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "db-data:/data/db"
  
  api:
    image: hygieia-api
    depends_on:
      - db
    ports:
      - "8080:8080"
  
  ui:
    image: hygieia-ui
    depends_on:
      - api
    ports:
      - "3000:80"
  
  hygieia-sonar-codequality-collector:
    image: hygieia-sonar-codequality-collector
    depends_on:
      - db
   
  hygieia-github-scm-collector:
    image: hygieia-github-scm-collector
    volumes:
      - ./logs:/hygieia/logs
      - ./conf:/hygieia/config
    links:
      - db
      - api
  
  hygieia-jenkins-build-collector:
    image: hygieia-jenkins-build-collector
    volumes:
      - ./logs:/hygieia/logs
      - ./conf:/hygieia/config
    links:
      - db
      - api
      
  hygieia-gitlab-scm-collector:
    image: hygieia-gitlab-scm-collector
    volumes:
      - ./logs:/hygieia/logs
      - ./conf:/hygieia/config
    links:
      - db
      - api
      
  hygieia-gitlab-feature-collector:
    image: hygieia-gitlab-feature-collector
    volumes:
      - ./logs:/hygieia/logs
      - ./conf:/hygieia/config
    links:
      - db
      - api
    
volumes:
  db-data:

**Comment by 2804337402** [comment]
The problem has been solved

**Comment by Dinnerspy** [comment]
How did you resolve this issue.

**Comment by ykfq** [comment]
@2804337402 
How did you resolve this issue ？

**Comment by panshaobin** [comment]
How did you solve this problem?
