### ISSUE TITLE
Quality Widget Issues

### ISSUE THREAD

**Issue by jfreitas2015** [capitalone/Hygieia#2077]
Hello,
I've been trying to configure static analysis to the quality widget but so far without success. 

Our static analysis results is being generated through Eslint and the output is in checkstyle format. In our job we're publishing this checkstyle results using the checkstyle plygin and the results are available through Jenkins rest api.

The issue is that this data is not showing in our dashboard or in mongodb. I'm wodering how can I import checkstyle static analysis to hygieia.

Bellow some information about our environment:

**code quality properties:**
#pattern to find cucubmer reports
#jenkins-codequality.artifactRegex[0]=${JENKINS_CODEQUALITY_JSON_FILENAME:-test.xml}
jenkins-codequality.artifactRegex.junit=${JENKINS_CODEQUALITY_JUNIT_FILENAME:-TEST-.*\\.xml}
jenkins-codequality.artifactRegex.findbugs=${JENKINS_CODEQUALITY_FINDBUGS_FILENAME:-findbugsXml.xml}
jenkins-codequality.artifactRegex.pmd=${JENKINS_CODEQUALITY_PMD_FILENAME:-pmd.xml}
jenkins-codequality.artifactRegex.checkstyle=${JENKINS_CODEQUALITY_CHECKSTYLE_FILENAME:-checkstyle-result.xml}
jenkins-codequality.artifactRegex.jacoco=${JENKINS_CODEQUALITY_JACOCO_FILENAME:-jacoco.xml}

**checkstyle output through Jenkins Rest:**
<checkStyleResult _class='hudson.plugins.checkstyle.CheckStyleResult'>
    <module></module>
    <newSuccessfulHighScore>false</newSuccessfulHighScore>
    <newZeroWarningsHighScore>false</newZeroWarningsHighScore>
    <numberOfFixedWarnings>0</numberOfFixedWarnings>
    <numberOfHighPriorityWarnings>5</numberOfHighPriorityWarnings>
    <numberOfLowPriorityWarnings>0</numberOfLowPriorityWarnings>
    <numberOfNewWarnings>0</numberOfNewWarnings>
    <numberOfNormalPriorityWarnings>4</numberOfNormalPriorityWarnings>
    <numberOfWarnings>9</numberOfWarnings>
    <pluginResult>SUCCESS</pluginResult>
    <referenceBuild _class='hudson.model.FreeStyleBuild'>
        <number>25</number>
        <url>https://localhost/job/hygieia_test/25/</url>
    </referenceBuild>
    <successfulHighScore>0</successfulHighScore>
    <successfulSinceBuild>0</successfulSinceBuild>
    <successfulSinceDate>0</successfulSinceDate>
    <warning _class='hudson.plugins.checkstyle.parser.Warning'></warning>
    <warning _class='hudson.plugins.checkstyle.parser.Warning'></warning>
    <warning _class='hudson.plugins.checkstyle.parser.Warning'></warning>
    <warning _class='hudson.plugins.checkstyle.parser.Warning'></warning>
    <warning _class='hudson.plugins.checkstyle.parser.Warning'></warning>
    <warning _class='hudson.plugins.checkstyle.parser.Warning'></warning>
    <warning _class='hudson.plugins.checkstyle.parser.Warning'></warning>
    <warning _class='hudson.plugins.checkstyle.parser.Warning'></warning>
    <warning _class='hudson.plugins.checkstyle.parser.Warning'></warning>
    <warningsDelta>0</warningsDelta>
    <zeroWarningsHighScore>0</zeroWarningsHighScore>
    <zeroWarningsSinceBuild>0</zeroWarningsSinceBuild>
    <zeroWarningsSinceDate>0</zeroWarningsSinceDate>
</checkStyleResult>

**And here my quality widget:**
![2018-03-28_11-45-29](https://user-images.githubusercontent.com/11760329/38043815-ba13c3ac-327d-11e8-8fbe-191aa493315c.png)

note that unit test are working but not static analysis.

Let me know if you need any additional information.

**Comment by jfreitas2015** [comment]
Can anyone give me a clue about this ? :(

**Comment by nireeshT** [comment]
@jfreitas2015  Please share collector log

**Comment by nireeshT** [comment]
@jfreitas2015  Reopen if issue is not fixed.
