### ISSUE TITLE
Sonar collector doesn't collect all projects

### ISSUE THREAD

**Issue by magma7** [capitalone/Hygieia#2079]
I need help, in order to understand why sonar collector doesn't collect all sonar projects and put it to mongo db?

Sonar collector is fetching only partial projects, what can cause this issue? why is collector fetching only certain projects? 

application.properties:

[root@ilvpbg2707 target]# vim application.properties

    dbname=dashboarddb
    dbhost=localhost
    dbport=27017
    dbusername=dashboarduser
    dbpassword=dbpassword
    sonar.cron=0 0/5 * * * *
    sonar.servers[0]=http://illin5566:19090
    sonar.username=xxxxx
    sonar.apiKey=xxx
   dbreplicaset=false
   dbhostport=localhost:27017
   key=T67EnRMLjOUEJSXjhtqF6Smzq7Z5LEwT
   sonar.versions[0]=6.7
 sonar.metrics[0]=ncloc,violations,new_vulnerabilities,critical_violations,major_violations,blocker_violations,tests,test_success_density,test_errors,test_failures,coverage,line_coverage,sqale_index,alert_status,quality_gate_details

**Comment by nireeshT** [comment]
@magma7  Fixed in https://github.com/capitalone/Hygieia/pull/2092 . Please update code base and retry. Reopen if issue is not fixed.
