### ISSUE TITLE
Webhook/Event Strategy

### ISSUE THREAD

**Issue by davidhhessler** [capitalone/Hygieia#2086]
Is a plan to move from Scheduled Task-Based Collectors to a webhook / event strategy?  My group is currently building this off of a Fork, but we rather collaborate together

**Comment by tabladrum** [comment]
We want to support both - based on feedback received from multiple users. We do support Github hook and push from Jenkins. But I am looking at some options to go 100% push based. Would very much love to chat and collaborate. Please send me a contact to tapabrata.pal@capitalone.com.
