### ISSUE TITLE
CodeQuallity collector not being updated

### ISSUE THREAD

**Issue by josefarinna** [capitalone/Hygieia#2091]
Hello,

Seems that the CodeQuallity collector is not getting updated. I have the service running and the only way to update the information is to click on the widget configuration and press save without doing any changes.

**Comment by mhoffman78** [comment]
I was able to get the static analysis metrics to show up.  I had the wrong URL for Sonar Server, however I did notice the security data is not showing up.  I have added vulnerabilities and security_rating to the list of Sonar metrics in the application.properties, but still nothing  I am running version 5.6.6 of Sonar.  Any help would be appreciated

![static code](https://user-images.githubusercontent.com/36509786/38137904-9c564a82-33f5-11e8-8561-a089c6bcf8d1.PNG)

**Comment by nireeshT** [comment]
@mhoffman78 - Security tab is related to the metrics collected from Fortify collector and Open source scan metrics is collected from Nexus IQ. Tests tab is for functional tests which are integrated with Jenkins build via cucumber.json which are posted back to Hygieia in Tests tab.

**Comment by nireeshT** [comment]
@mhoffman78 Please reopen if issue is not resolved.

**Comment by josefarinna** [comment]
My issue is still there, the collector is working as expected, but the ui never get refreshed, only when I click on modify the plugin and then click on sabe (there is no need to modify anything) the information is refreshed.
