### ISSUE TITLE
Bitbucket Collector Properties 

### ISSUE THREAD

**Issue by Avfdo1994** [capitalone/Hygieia#2104]
What do I set for the following properties? 
git.host= 
git.api=
bitbucket.key=

**Comment by Dinnerspy** [comment]
Hi Avfdo1994, For git.host the value would be your BitBucket hostname or ip. For git.api it would the location of your api and for bitbucket.key it would be you key you generate from bit bucket. Here are a couple of links that should help explain.

http://capitalone.github.io/Hygieia/bitbucket.html

**Comment by nireeshT** [comment]
@Avfdo1994  Please reopen if issue is not resolved
