### ISSUE TITLE
Configure pipeline widget

### ISSUE THREAD

**Issue by syedsfayaz** [capitalone/Hygieia#2105]
We are not using any deployment tool in my organization. Can I create Pipeline just using Jenkins collector. 

I have Jenkins collector running. But I don't see any thing on  the pipeline widget. Do I need to install Hygieia  plugin to get the data or just the Jenkins collector will be able to pull data from Jenkins. Can you please share if we have any documentation to configure pipeline widget. 

![image](https://user-images.githubusercontent.com/26099918/38045404-852db596-3271-11e8-8e93-954bc2132cb8.png)

**Comment by nireeshT** [comment]
@syedsfayaz  you can use dynamic pipeline option set in api properties. You can set static values in there, but again that is all tied to deployment artifacts and environments deployed to .

**Comment by syedsfayaz** [comment]
@nireeshT Thanks for your reply. I don't see any info regarding dynamic pipeline option in api properties.
http://capitalone.github.io/Hygieia/api.html

Can you please share the properties i need to add to api properties file.

**Comment by nireeshT** [comment]
@syedsfayaz  add below prop in api.properties

feature.dynamicPipeline=enabled

**Comment by syedsfayaz** [comment]
@nireeshT Thanks for sharing the property. I will add it to the api property file.

**Comment by syedsfayaz** [comment]
@nireeshT .   Please help.

1. I am currently using **Jenkins collector** to pull data to dashboard. But in this case I am not able to get data for pipeline. Do I need to configure "Jenkins Hyginea plugin" to configure pipeline?. Currently I don't see any data under pipeline widget. 
2. I have created a sample pipeline job in Jenkins with stages for build/deploy to diff environments. But that's not reflecting on dashboard. I know I missing some thing but not sure what. 

Note: I have added pipeline "feature.dynamicPipeline=enabled" but still I dont see any difference. 

![image](https://user-images.githubusercontent.com/26099918/38209442-4d09f69c-3669-11e8-910b-a292ff6fb566.png)

**Comment by syedsfayaz** [comment]
@nireeshT I was able to configure the Pipeline. Thanks for your help.

**Comment by josefarinna** [comment]
Hi @syedsfayaz,
Could you please share what you did to configure it? I also tried but faced the same problem you had.

KR.

**Comment by syedsfayaz** [comment]
@josefarinna I believe the Build collector does not collect data for deployment dashboard. So i have added Jenkins Hyginea plugin. Then configure the post build notification to push data to Dashboard.

**Comment by nireeshT** [comment]
@syedsfayaz  Please reopen if issue is not resolved

**Comment by sachingupta771** [comment]
@syedsfayaz/ @nireeshT ,
can someone share the configurations performed in jenkins to run this pipeline widget

**Comment by syedsfayaz** [comment]
@sachingupta771   

This link has all the configurations needed for setting up pipeline widget.
Note:  With out deploy widget you cannot configure pipeline widget, as pipeline pulls data from deploy widget. 


http://capitalone.github.io/Hygieia/hygieia-jenkins-plugin.html

**Comment by sachingupta771** [comment]
@syedsfayaz,

Thanks, mate, I had already seen that link and applied all necessary configurations. but didn't know that deploy widget is the dependency here since I don't have any Xldeploy or Udeploy setup for it.
would try setting them up and then try again.

**Comment by syedsfayaz** [comment]
@sachingupta771   you don't need to setup XLdeploy or Udeploy for deploy widget if you are not using these tools in your environment. Jenkins Hygieie plugin can push deployment stats to Deploy widget.

**Comment by syedafirdaus** [comment]
Hi @syedsfayaz , I have configured as you mentioned in above comments. And i dont have a deploy tool. I use Jenkins to deploy using shell script. I have added deployment in post-build actions like below. Still I cannot see env in Hygieia pipeline view.
I have also set feature.dynamicPipeline=enabled in api properties file 
FYI all screenshots

Deploy widget
![image](https://user-images.githubusercontent.com/42797555/52769728-260a2d80-3057-11e9-944b-d318066170ab.png)

Pipeline

![image](https://user-images.githubusercontent.com/42797555/52769740-34584980-3057-11e9-9c00-dbb2e9c96437.png)

api.prop

dbname=dashboarddb
dbusername=dashboarduser
dbpassword=dbpassword
dbhost=127.0.0.1
dbport=27017
server.contextPath=/api
dbreplicaset=false
key=xxxxxxxxxxx
feature.dynamicPipeline=enabled

And my jenkins

![image](https://user-images.githubusercontent.com/42797555/52769801-610c6100-3057-11e9-8311-e1bdd1e48f07.png)



Please advise

**Comment by syedsfayaz** [comment]
@syedafirdaus  Can you try logging in to the MongoDB and Check if there is any data inserted in to the database.

**Comment by syedafirdaus** [comment]
@syedsfayaz  Its working now. Thanks for your response. 
Do you have any idea on my queries in this link? I am facing issues in jira collector. 
Please find my issues in the link https://github.com/Hygieia/Hygieia/issues/2667  and let me know if I could do anything to get data
