### ISSUE TITLE
Monitor Widget - what is the use/purpose?

### ISSUE THREAD

**Issue by softwareklinic** [capitalone/Hygieia#211]
Didn't get the purpose of the monitor widget... an example would be helpful...

**Comment by tabladrum** [comment]
This is going to be replaced with app performance monitoring - AppDynamics will be the first tool to be integrated - work in progress

**Comment by softwareklinic** [comment]
Sitespeed.io and some other open source tools are great that can probably be integrated as well...

**Comment by tabladrum** [comment]
Closing with this https://github.com/capitalone/Hygieia/issues/438
