### ISSUE TITLE
Write a custom collector and screen widget

### ISSUE THREAD

**Issue by spennec** [capitalone/Hygieia#2114]
Hello,

We are testing Hygieia in our infrastructure, and one question came to mind today: we have a private, closed-source component that we would like to add to the dashboards.

Is there a documentation, or do you have any advice, on how to add new collectors and widgets to Hygieia?

Thanks for your help,

Sébastien

**Comment by Megha849** [comment]
@spennec Refer to this document on creating a new collector: https://github.com/capitalone/Hygieia/blob/master/core/create_collector.md

**Comment by gdelafosse** [comment]
Is there a documentation for implementing a custom UI widget?

**Comment by Megha849** [comment]
@gdelafosse  We do not have documentation available on this right now. It will be available soon. The code for the widgets is available at: https://github.com/capitalone/Hygieia/tree/master/UI/src/components/widgets.
Hope this helps in the meantime.

**Comment by spennec** [comment]
Thanks a lot for those two links! :)
