### ISSUE TITLE
Hygieia is working fine and accessible locally but through external link Its inaccessible 

### ISSUE THREAD

**Issue by hrushie** [capitalone/Hygieia#2115]
My Hygieia is working fine since last 3 months and it is running on the mac servers. Until last week I was able to access it with localhost as well as the external link. Since last week I cannot access it with the external link, do I have to change something in the configuration files or in the mac security and the firewall settings?

Thanks

**Comment by nireeshT** [comment]
@hrushie  Nothing changed at configuration, are you using docker build ?

**Comment by matthewbeasley** [comment]
@hrushie - did you update Hygieia to cause this issue or did it just randomly pop up?

**Comment by hrushie** [comment]
Hi @nireeshT  and @matthewbeasley,

It was automatically popped up, but it is resolved now, my companies security policy is changed thats why they disabled 3000 port, I enabled it and I can able to access it.

We can close this ticket now.

Thanks

**Comment by matthewbeasley** [comment]
@hrushie - gotcha, thanks for closing this issue.
