### ISSUE TITLE
Jira Instance URL - / suffix

### ISSUE THREAD

**Issue by softwareklinic** [capitalone/Hygieia#212]
When we miss the trailing / in the lira url.. it malforms the url resulting into "there is a error connecting to the Jira query"...

It would be great if code can take care of such things..

**Comment by amitmawkin** [comment]
this will be fixed with how code handles a trailing / for a jira url.

**Comment by amp5208** [comment]
This was, indeed, fixed as of the following merged pull request:  https://github.com/capitalone/Hygieia/pull/284.  You should be able to close this issue.

**Comment by amp5208** [comment]
@amitmawkin / @tabladrum :  As mentioned above, this issue can be closed.
