### ISSUE TITLE
About the DB properties (Application.properties)

### ISSUE THREAD

**Issue by softwareklinic** [capitalone/Hygieia#213]
Looks like we have some mismatch or potential issue related to application.properties file... for db connection.. WHEN we tried using the sprint properties.... it never worked.... it worked after using dbname, dbusername,  etc... can we get this checked...

Using below in mongo config...
core/src/main/java/com/capitalone/dashboard/config/MongoConfig.java 
Showing the top match. Last indexed on Nov 4.

30	    private int port;
31	    @Value("${dbusername:}")
32	    private String userName;
33	    @Value("${dbpassword:}")

# Default server configuration values
dbname=dashboarddb
dbusername=dashboarduser
dbpassword=1qazxSw2
dbhost=127.0.0.1
dbport=11500
server.contextPath=/api
server.port=8080

======== OR =========

######################
#Spring Application Properties
spring.data.mongodb.database=dashboarddb
spring.data.mongodb.host=mongo host
spring.data.mongodb.port=11500
spring.data.mongodb.username=user
spring.data.mongodb.password=mongo password

**Comment by tabladrum** [comment]
We are following the first format...
dbname=dashboarddb
dbusername=dashboarduser
dbpassword=1qazxSw2
dbhost=127.0.0.1
dbport=11500
server.contextPath=/api
server.port=8080
