### ISSUE TITLE
Pipeline is not resetting the artifact number!

### ISSUE THREAD

**Issue by syedsfayaz** [capitalone/Hygieia#2132]
@nireeshT  The Pipeline is not resetting the artifact number.

Suppose the 1.3.1.jar is deployed and is successful it is shown on the Pipeline.
When a next version is pushed the old version is still showing on the Dashboard. Is there a way I can just get rid of the old version number.

![image](https://user-images.githubusercontent.com/26099918/38538770-1bc5c886-3c4a-11e8-873d-e1a8252ead61.png)

**Comment by nireeshT** [comment]
@syedsfayaz  I can give you are code work around 
 change below code in view.html (pipeline) 
<div class="pipeline-row clearfix" ng-repeat="unit in pipelineView.units track by $index">
<span ng-show="$last">
<div class="col-xs-3 col-md-2">
                <div class="row">
                    <div class="pipeline-unit-name dash-overflow">
                        {{unit.name}}
                    </div>
                </div>
            </div>
            <div class="col-xs-9 col-md-10">
                <div class="row">
                    <div class="col-xs-{{pipelineView.colGridSize}}" ng-repeat="key in pipelineView.environmentKeys">
                        <div class="pipeline-data-cell">
                            <span dash-status="false" ng-if="unit.environments[key].somethingDown"></span>

                            <div class="version">
                                {{::unit.environments[key].version}}
                            </div>
                            <div class="text-standard-date">
                                {{::unit.environments[key].lastUpdate | fromNow}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
</span>
This should display last element in collection .

**Comment by syedsfayaz** [comment]
Will this remove all the old build versions and just keep the latest?

**Comment by syedsfayaz** [comment]
Thank you I will try it out.

**Comment by syedsfayaz** [comment]
@nireeshT   The fix you sent is working., But its not resetting the color. 

If build number 1.4.1 failed. The status is red which is correct.
And next build 1.4.2 if successful the status of pipeline is still red and not green.

**Comment by nireeshT** [comment]
@syedsfayaz  change dash-status conditionally. Reopen if issue is not resolved.

**Comment by syedsfayaz** [comment]
@nireeshT  Can you please guide me how can I set the dash-status conditionally. I mean which code needs to be changed.
