### ISSUE TITLE
UI Bug - No dashboards displayed after clearing the filter, navigating through pagination

### ISSUE THREAD

**Issue by kumarvarun1252** [capitalone/Hygieia#2141]
**Steps to Reproduce**:
Login to Hygieia (Make sure there are several dashboards to see pagination)
Filter dashboards with a search string "Test" (or any string from ur existing dashboards)
Click on one of the results (This will open the dashboard with widgets)
Hit browser back button (This will take you back to home screen)
Click on the Next button from the pagination 

Actual Result: 
No dashboards are displayed. Verified on QA & prod environments. 

Expected Results:
All the dashboards should be displayed without any issues when navigated through pagination 

Attached screenshot for easy understanding
![ux bug - no dashboards display after clearing the filter](https://user-images.githubusercontent.com/8548710/38694560-d7da5cee-3e3e-11e8-999e-64f5906c5809.png)

**Comment by Sbrenthughes** [comment]
Nice catch!

**Comment by nireeshT** [comment]
@kumarvarun1252  Fixed .  Get latest code base .
