### ISSUE TITLE
Jira collector - "sTeamId" field from "feature" collection in MongoDB is missing

### ISSUE THREAD

**Issue by dardanbekteshi** [capitalone/Hygieia#2142]
We use the "Board as Team" in our company and I have set up the property in the properties file:
`feature.jiraBoardAsTeam=true`
I have also specified the TeamFieldName customfield to the one we use in our company:
`feature.jiraTeamFieldName=customfield_12300
`

This configuration seems to be correct since the "team" collection gets populated with the boards we have in our company. The problem appears in the "feature" collection in the database. In order to filter the widget information based on boards (or teams), there is the "sTeamId" field in this collection which should represent in which board a given issue belongs to. But, in my case, this field is always null. I have also tried to make an explicit JQL query to the Jira server and to inspect the JSON results and the Board/Team information is inexistent (i.e. null). 

`https://jira.my_company.com/rest/api/2/search?jql=updatedDate%3E%3D%272017-08-01%2019%3A23%27%20AND%20issueType%3D%27Story%27%20ORDER%20BY%20updated%20ASC&fields=*all%2C-comment%2C-watches%2C-worklog%2C-votes%2C-reporter%2C-creator%2C-attachment&maxResults=100&startAt=0
`
 
My jira.properties file:

```
feature.jiraBaseUrl=https://jira.my_company.com
feature.jiraQueryEndpoint=rest/api/2/
feature.jiraIssueTypeNames=Epic,Story,Bug,Task,Sub-task

logging.file=./logs/jira.log
feature.pageSize=5

feature.deltaStartDate=2017-12-12T00:00:00.000000
feature.masterStartDate=2017-12-12T00:00:00.000000
feature.deltaCollectorItemStartDate=2017-12-12T00:00:00.000000
feature.cron=0 * * * * *
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic

feature.jiraCredentials= <my jira credentials here>

feature.jiraSprintDataFieldName=customfield_10007
feature.jiraEpicIdFieldName=customfield_10008
feature.jiraStoryPointsFieldName=customfield_10005
feature.jiraTeamFieldName=customfield_12300
feature.jiraBoardAsTeam=true

```
**Do you have any idea why this might happen?**

**Comment by nireeshT** [comment]
@dardanbekteshi  check below jira props and change accordingly 


#####################################################################################################################
## JIRA collector properties
#####################################################################################################################
# Collector schedule (required)

# PageSize - Expand contract this value depending on Jira implementation's
# default server timeout setting (You will likely receive a SocketTimeoutException)
 feature.pageSize=100

# Delta change date that modulates the collector item task
# Occasionally, these values should be modified if database size is a concern
 feature.deltaStartDate=2016-03-01T00:00:00.000000
 feature.masterStartDate=2016-03-01T00:00:00.000000
 feature.deltaCollectorItemStartDate=2016-03-01T00:00:00.000000

# Chron schedule: S M D M Y [Day of the Week]
 feature.cron=0 * * * * *

# ST Query File Details - Required, but DO NOT MODIFY
 feature.queryFolder=jiraapi-queries
 feature.storyQuery=story
 feature.epicQuery=epic

# JIRA CONNECTION DETAILS:
# Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY
 feature.jiraProxyUrl=http://proxy.XXXXX.com
 feature.jiraProxyPort=

 # feature.jiraBaseUrl=https://jira.com/
 
 feature.jiraBaseUrl=https://jira-qa.kdc.capitalone.com/
 # feature.jiraBaseUrl=https://jira.kdc.capitalone.com/
 feature.jiraQueryEndpoint=rest/api/2/

# For basic authentication, requires username:password as string in base64
# This command will make this for you:  echo -n username:password | base64
 feature.jiraCredentials=
# OAuth is not fully implemented; please blank-out the OAuth values:
 feature.jiraOauthAuthtoken=
 feature.jiraOauthRefreshtoken=
 feature.jiraOauthRedirecturi=
 feature.jiraOauthExpiretime=

 feature.jiraIssueTypeNames=Story
 feature.jiraSprintDataFieldName=customfield_10007
 feature.jiraEpicIdFieldName=customfield_10003
 feature.jiraStoryPointsFieldName=customfield_10004
 feature.jiraTeamFieldName=customfield_11248
 feature.jiraBoardAsTeam=true

**Comment by nireeshT** [comment]
@dardanbekteshi  issue fixed?

**Comment by dardanbekteshi** [comment]
I just found out that the problem was not on the hygieia side but on the way how we use Jira at the company. Issues do not store information about boards so that is why sTeamId is missing. So yes, you can close the issue. Thanks!
