### ISSUE TITLE
Hygieia GitHub Code Repo

### ISSUE THREAD

**Issue by venkiradkris** [capitalone/Hygieia#2143]
Hi 
Hygieia GitHub Code Repo - Summary is showing the data.
ISSUES, PULLS AND COMMITS PER DAY is not showing the graph.
Please suggest.
Have attached Dashboard & Collector Snapshots.
Regards
Venkat
![githubissue](https://user-images.githubusercontent.com/22450284/38728587-ed788fae-3f2d-11e8-8c0f-0cb6b456ad43.jpg)
![githubcollector](https://user-images.githubusercontent.com/22450284/38728683-2bc0ee14-3f2e-11e8-8c70-77508aa928c4.jpg)

**Comment by venkiradkris** [comment]
Hi - Can anyone help? Thanks.

**Comment by venkiradkris** [comment]
Hi - today i don't see this issue. This is automatically working fine today. Please don't look into this issue. Thanks.

**Comment by panshaobin** [comment]
Have you ever encountered this problem?"401 Unauthorized",We didn't get the data,thank you!

**Comment by panshaobin** [comment]
![1528034190 1](https://user-images.githubusercontent.com/39650187/40887278-0467741e-6779-11e8-90b6-8aa787297534.jpg)
