### ISSUE TITLE
Hygieia Audit API

### ISSUE THREAD

**Issue by venkiradkris** [capitalone/Hygieia#2145]
Hi - Please help to understand the purpose of Audit API.
I am normally starting API and Dashboard.
If i start Audit API, i need to stop API since both are running on same port.
Is there any UI for Audit API?
Regards
Venkat

**Comment by nireeshT** [comment]
@venkiradkris  run audit-api on different port. That can be changed in apiaudit properties file. I use 8090 for audit-api and 8080 for api

**Comment by venkiradkris** [comment]
Hi - Fine. If Audit API runs in 8090, how to connect Audit API with dashboard? current dashboard is automatically connects with API only. Thanks.

**Comment by venkiradkris** [comment]
Hi - Can anyone help? Thanks.

**Comment by venkiradkris** [comment]
Hi - Any update/help? Thanks.

**Comment by fidelcoria-aa** [comment]
@venkiradkris so there is a collector named nfrr that calls api-audit endpoints and aggregates the JSON responses into mongoDB. 
I looked in the UI repo but I did not see a widget for audit. @nireeshT is audit widget on the roadmap?
