### ISSUE TITLE
Can't find cucumber.json when launching Jenkins-Cucumber Collector

### ISSUE THREAD

**Issue by develo55** [capitalone/Hygieia#2151]
Hello,
I'm setting up the Jenkins-Cucumber Collector and when I'm launching it, it can't find the cucumber.json.
For my project, the cucumber.json is located in: /target/cucumber/cucumber-report.json 
I tried many expressions in the jenkins-cucumber.cucumberJsonRegex property but It doesn't work.
Here is my cucumber.properties : 

# Database Name
                dbname=dashboarddb

                # Database HostName - default is localhost
                dbhost=localhost

                # Database Port - default is 27017
                dbport=27017

                # Database Username - default is blank
                dbusername=User

                # Database Password - default is blank
                dbpassword=dbpassword

                #Collector schedule (required)
                jenkins-cucumber.cron=0 0/1 * * * *

                #Jenkins server (required) - Can provide multiple
                jenkins-cucumber.servers[0]=http://myjenkins

                jenkins-cucumber.cucumberJsonRegex=${JENKINS_CUCUMBER_JSON_FILENAME:/target/cucumber/cucumber-report.json}

                #Another option: If using same username/password Jenkins auth - set username/apiKey to use HTTP Basic Auth (blank=no auth)
                jenkins-cucumber.username=myUsername
                jenkins-cucumber.apiKey=MyAPI

**Comment by develo55** [comment]
If it can help someone else, I did it with pushing cucumber results tests from jenkins using Hygieia Jenkisn plugin

**Comment by jyotimittal01** [comment]
@develo55  I have Katalon groovy/java tests with Json and xml test result file craeted. Can I still use this collector?
