### ISSUE TITLE
Product Dashboard

### ISSUE THREAD

**Issue by venkiradkris** [capitalone/Hygieia#2153]
Hi
[1] I can see only commit, build columns in product dashboard. How to get other columns?
[2] I can see Dev Ops Maturity Score as blank. Any idea how to get it?
Thanks and Regards
Venkat

**Comment by venkiradkris** [comment]
Hi - Any update/help? Thanks.

**Comment by nireeshT** [comment]
@venkiradkris  refer - https://github.com/capitalone/Hygieia/issues/1512

**Comment by nireeshT** [comment]
@venkiradkris  for your 2nd question refer this - https://github.com/capitalone/Hygieia/issues/2161 

Open new issue if you have more questions
