### ISSUE TITLE
Hygieia-Jenkins publisher question

### ISSUE THREAD

**Issue by email2niranjan** [capitalone/Hygieia#2169]
This is very basic question.
In this push based approach, I understand that we configure the Hygieia server where Jenkins needs to publish to. But it appears to be ONE static server value. Can the publish be done to a Hygieia host **dynamically** (mentioned as a parameter) as part of the publish code itself?

just curious

**Comment by nireeshT** [comment]
@email2niranjan  are you using free style or pipeline jobs.  Can you explain more on "ONE static server value". If you mean environment value like "DEV","QA"..etc, you can always pass dynamic variables in all fields.

**Comment by email2niranjan** [comment]
where am coming from is.. what if in our enterprise, we do not want to share the Hygieia host and we have separate hosts for each application

**Comment by nireeshT** [comment]
@email2niranjan  You should be able to pass a dynamic value via a build variable, I have not tried though. It should work.

**Comment by email2niranjan** [comment]
I learnt through other history posts/issues that this is not possible. Hence closing this ticket.
But I did find a way to use cURL POST commands to post statuses to apis. Hence closing this issue.
