### ISSUE TITLE
UI Build from docker - Save button - no action

### ISSUE THREAD

**Issue by softwareklinic** [capitalone/Hygieia#217]
Im not sure if its related to the UI code... or the config of the Stash collector or the URL in the UI...

but when i click on Save button for stash repo and branchl... it doesnt save and the overlay screen doesnt do any action...

![no-save](https://cloud.githubusercontent.com/assets/7537289/11763999/87038b54-a0e5-11e5-8ad4-7558c9efd672.png)

**Comment by tabladrum** [comment]
Either the API is not running or the collector was never run or both. Also make sure that the API and the collectors are configured to use the same database name etc.

**Comment by softwareklinic** [comment]
Ty will verify and let you know.



Regards,
Keyur

On Dec 12, 2015, at 5:06 PM, tabladrum <notifications@github.com<mailto:notifications@github.com>> wrote:


Either the API is not running or the collector was never run or both. Also make sure that the API and the collectors are configured to use the same database name etc.

**Comment by softwareklinic** [comment]
Api is running connecting to mongodb no errors, collector keeps showing 0 commits etc... But no errors. Need to look if db access is same for both.



Regards,
Keyur

On Dec 12, 2015, at 7:29 PM, Shah, Keyur <Keyur.Shah@one.verizon.com<mailto:Keyur.Shah@one.verizon.com>> wrote:

Ty will verify and let you know.



Regards,
Keyur

On Dec 12, 2015, at 5:06 PM, tabladrum <notifications@github.com<mailto:notifications@github.com>> wrote:


Either the API is not running or the collector was never run or both. Also make sure that the API and the collectors are configured to use the same database name etc.

**Comment by softwareklinic** [comment]
here are some additional information

COLLECTOR FOR STASH

ctTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHostNamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@546645, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@75e60744, socketFactory=javax.net.DefaultSocketFactory@2543c0b6, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2015-12-12 22:10:26,982 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:5, serverValue:37}] to localhost:27017
2015-12-12 22:10:26,983 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 0, 5]}, minWireVersion=0, maxWireVersion=3, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=579072}
2015-12-12 22:10:27,668 INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
2015-12-12 22:10:27,683 INFO  com.capitalone.dashboard.Application - Started Application in 5.585 seconds (JVM running for 7.315)
2015-12-12 22:11:00,006 INFO  c.c.d.collector.CollectorTask - Running Collector: Stash
2015-12-12 22:11:00,037 INFO  c.c.d.collector.CollectorTask - ------------------------------
2015-12-12 22:11:00,037 INFO  c.c.d.collector.CollectorTask - Starting...
2015-12-12 22:11:00,037 INFO  c.c.d.collector.CollectorTask - ------------------------------
2015-12-12 22:11:00,108 INFO  c.c.d.collector.CollectorTask - Repo Count         0        0s
2015-12-12 22:11:00,109 INFO  c.c.d.collector.CollectorTask - New Commits        0        0s
2015-12-12 22:11:00,109 INFO  c.c.d.collector.CollectorTask - Finished                    0s
2015-12-12 22:12:00,006 INFO  c.c.d.collector.CollectorTask - Running Collector: Stash
2015-12-12 22:12:00,011 INFO  c.c.d.collector.CollectorTask - ------------------------------

APPLICATION.PROPERTIES FOR COLLECTOR

#Database Name 
#spring.data.mongodb.dbname=dashboarddb
dbname=dashboarddb
#Database HostName - default is localhost
#spring.data.mongodb.dbhost=localhost
dbhost=localhost
#Database Port - default is 27017
#spring.data.mongodb.dbport=27017
dbport=27017
#Database Username - default is blank
#spring.data.mongodb.dbusername=dashboarduser
dbusername=dashboarduser
#Database Password - default is blank
#spring.data.mongodb.dbpassword=password1
dbpassword=password1

#Collector schedule (required)
git.cron=0 0/1 * * * *

#mandatory
git.host=http://localhost:7990/

#mandatory
git.api=/rest/api/1.0/
git.userName=admin
git.password=admin
#Maximum number of days to go back in time when fetching commits
git.commitThresholdDays=15
git.jpa.show-sql: true



API CONNECTION DETAILS TO DB

docker run -t -p 7080:8080 --name hygieia-api -e "SPRING_DATA_MONGODB_HOST=192.168.1.11" -e "SPRING_DATA_MONGODB_PORT=27017" -e "SPRING_DATA_MONGODB_USERNAME=dashboarduser" -e "SPRING_DATA_MONGODB_DATABASE=dashboarddb" -e "SPRING_DATA_MONGODB_PASSWORD=password1" -v /Users/FamilyMac/Hygieia/api/logs:/hygieia/logs -i capitaloneio/hygieia-api

**Comment by tabladrum** [comment]
Testing out with BitBucket now. Stay tuned.

**Comment by tabladrum** [comment]
Public bitbucket will not work.

**Comment by tabladrum** [comment]
Can you check your MongoDB if you have the a similar document (as below) in collector_item collection?

{
    "_id" : ObjectId("566ee0991ae7d52a83e9f003"),
    "_class" : "com.capitalone.dashboard.model.GitRepo",
    "enabled" : true,
    "collectorId" : ObjectId("566edf891ae7d52665542453"),
    "options" : {
        "scm" : "Stash",
        "branch" : "AppDynamics",
        "url" : "https://bitbucket.org/topopal/testrepo",
        "lastUpdate" : ISODate("2015-12-14T15:48:19.493Z")
    }
}

**Comment by softwareklinic** [comment]
We are using private bitbucket and stash servers… Not public…

**Comment by tabladrum** [comment]
Ok. I am installing BitBucket on my Mac right now to check it out.

**Comment by tabladrum** [comment]
@dianewalls how did your bitbucket server collector work? I see that the API to get commits is different for bitbucket server (example below)
http://localhost:7990/rest/api/1.0/projects/tes/repos/hygieia/commits

**Comment by tabladrum** [comment]
Ok. Stash and bit bucket collector has some problems. I tested it out with a trial version of bitbucket installed on my MacBook. Will push changes to a branch tonight.

**Comment by softwareklinic** [comment]
Ty



Regards,
Keyur

On Dec 14, 2015, at 5:20 PM, tabladrum <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok. Stash and bit bucket collector has some problems. I tested it out with a trial version of bitbucket installed on my MacBook. Will push changes to a branch tonight.

**Comment by tabladrum** [comment]
I studied stash and bitbucket end points and API responses. I am proposing that we have one single Git collector that will implement all flavors of git (hub, stash, bitbucket etc) and will be able to work in any of these "modes" via configuration (some properties may be). I think this is proposed earlier too. Thoughts?

**Comment by softwareklinic** [comment]
That would be great



Regards,
Keyur

On Dec 15, 2015, at 5:55 PM, tabladrum <notifications@github.com<mailto:notifications@github.com>> wrote:


I studied stash and bitbucket end points and API responses. I am proposing that we have one single Git collector that will implement all flavors of git (hub, stash, bitbucket etc) and will be able to work in any of these "modes" via configuration (some properties may be). I think this is proposed earlier too. Thoughts?

**Comment by jaspreetsinghmadan** [comment]
Hi,
I am facing the same issue with Stash collector. The collector doesn't throw any error but it neither give any data for repos, commits etc. I have set up a local stash server. 

![image](https://cloud.githubusercontent.com/assets/14577901/14320351/6013d730-fc32-11e5-8313-f5a5beaa7370.png)

Application.properties --
#Database Name 
spring.data.mongodb.database=dashboardb

#Database HostName - default is localhost
spring.data.mongodb.host=

#Database Port - default is 27017
spring.data.mongodb.port=

#Database Username - default is blank
spring.data.mongodb.username=db

#Database Password - default is blank
spring.data.mongodb.password=dbpass

#Collector schedule (required)
git.cron=0 0/5 * * * *

#mandatory
git.host=http://localhost:7990/

#mandatory
git.api=/rest/api/1.0/

#Maximum number of days to go back in time when fetching commits
git.commitThresholdDays=15

debug=true

**Comment by softwareklinic** [comment]
Did you check the stashcollector code - check the API URL for stash is different than git

	-	String queryUrl = apiUrl.concat("/commits?sha=" + repo.getBranch()
	+	String queryUrl = apiUrl.concat("/commits?until=" + repo.getBranch()

**Comment by jaspreetsinghmadan** [comment]
It is String queryUrl = apiUrl.concat("/commits?sha=" + repo.getBranch() in DefaultStashClient. Do i need to change it to String queryUrl = apiUrl.concat("/commits?until=" + repo.getBranch()?

**Comment by softwareklinic** [comment]
Yes. Also, if it is not a publicly accessible repo – you need to modify the client code to accept username/password from the properties file… just like what Jenkins collector does…

**Comment by jaspreetsinghmadan** [comment]
Moreover i think its not getting anything in 
`enabledRepos(collector)` 
`gitRepoRepository.findEnabledGitRepos(collector.getId())` is returning []
And that's why its not even making a call to getcommits.

**Comment by tabladrum** [comment]
Did you configure a repo in a dashboard?

**Comment by jaspreetsinghmadan** [comment]
Yes, it just show the modal window even after pressing save and nothing happens

**Comment by tabladrum** [comment]
Can you check if you have a Collector for this in Collector collection in MongoDB?

**Comment by jaspreetsinghmadan** [comment]
Nope...

{ "_id" : ObjectId("56c5beb0b0269915a0678bc9"), "_class" : "com.capitalone.dashb
oard.model.Collector", "name" : "Product", "collectorType" : "Product", "enabled
" : true, "online" : true, "lastExecuted" : NumberLong(0) }
{ "_id" : ObjectId("56caf4bc68673320bc736772"), "_class" : "com.capitalone.dashb
oard.model.HudsonCollector", "buildServers" : [ "http://localhost:9080" ], "nice
Names" : [ ], "name" : "Hudson", "collectorType" : "Build", "enabled" : true, "o
nline" : true, "lastExecuted" : NumberLong("1456170000077") }
{ "_id" : ObjectId("56cafa98686733222ce169f6"), "_class" : "com.capitalone.dashb
oard.model.SonarCollector", "sonarServers" : [ "http://localhost:9000" ], "name"
 : "Sonar", "collectorType" : "CodeQuality", "enabled" : true, "online" : true,
"lastExecuted" : NumberLong("1456170000665") }

**Comment by tabladrum** [comment]
Ok. I would run the collector once at least - that will create the Collector. 
Then your Save on the UI will work (assuming the API running).
The Save will create the CollectorItem.
So on.

**Comment by jaspreetsinghmadan** [comment]
I have followed these steps -
1) Run API
2) Run Collector
3) Run UI

The collector shows --
{ "_id" : ObjectId("56c5beb0b0269915a0678bc9"), "_class" : "com.capitalone.dashb
oard.model.Collector", "name" : "Product", "collectorType" : "Product", "enabled
" : true, "online" : true, "lastExecuted" : NumberLong(0) }
{ "_id" : ObjectId("56caf4bc68673320bc736772"), "_class" : "com.capitalone.dashb
oard.model.HudsonCollector", "buildServers" : [ "http://localhost:9080" ], "nice
Names" : [ ], "name" : "Hudson", "collectorType" : "Build", "enabled" : true, "o
nline" : true, "lastExecuted" : NumberLong("1456170000077") }
{ "_id" : ObjectId("56cafa98686733222ce169f6"), "_class" : "com.capitalone.dashb
oard.model.SonarCollector", "sonarServers" : [ "http://localhost:9000" ], "name"
 : "Sonar", "collectorType" : "CodeQuality", "enabled" : true, "online" : true,
"lastExecuted" : NumberLong("1456170000665") }
> db.collectors.find()
{ "_id" : ObjectId("56c5beb0b0269915a0678bc9"), "_class" : "com.capitalone.dashb
oard.model.Collector", "name" : "Product", "collectorType" : "Product", "enabled
" : true, "online" : true, "lastExecuted" : NumberLong(0) }
{ "_id" : ObjectId("56caf4bc68673320bc736772"), "_class" : "com.capitalone.dashb
oard.model.HudsonCollector", "buildServers" : [ "http://localhost:9080" ], "nice
Names" : [ ], "name" : "Hudson", "collectorType" : "Build", "enabled" : true, "o
nline" : true, "lastExecuted" : NumberLong("1456170000077") }
{ "_id" : ObjectId("56cafa98686733222ce169f6"), "_class" : "com.capitalone.dashb
oard.model.SonarCollector", "sonarServers" : [ "http://localhost:9000" ], "name"
 : "Sonar", "collectorType" : "CodeQuality", "enabled" : true, "online" : true,
"lastExecuted" : NumberLong("1456170000665") }

But still the save doesn't work.
![image](https://cloud.githubusercontent.com/assets/14577901/14354594/8935aea8-fcfb-11e5-8492-e1775fdc2faa.png)

**Comment by jaspreetsinghmadan** [comment]
{ "_id" : ObjectId("56c5beb0b0269915a0678bc9"), "_class" : "com.capitalone.dashb
oard.model.Collector", "name" : "Product", "collectorType" : "Product", "enabled
" : true, "online" : true, "lastExecuted" : NumberLong(0) }
{ "_id" : ObjectId("56caf4bc68673320bc736772"), "_class" : "com.capitalone.dashb
oard.model.HudsonCollector", "buildServers" : [ "http://localhost:9080" ], "nice
Names" : [ ], "name" : "Hudson", "collectorType" : "Build", "enabled" : true, "o
nline" : true, "lastExecuted" : NumberLong("1456170000077") }
{ "_id" : ObjectId("56cafa98686733222ce169f6"), "_class" : "com.capitalone.dashb
oard.model.SonarCollector", "sonarServers" : [ "http://localhost:9000" ], "name"
 : "Sonar", "collectorType" : "CodeQuality", "enabled" : true, "online" : true,
"lastExecuted" : NumberLong("1456170000665") }
> db.collectors.find()
{ "_id" : ObjectId("56c5beb0b0269915a0678bc9"), "_class" : "com.capitalone.dashb
oard.model.Collector", "name" : "Product", "collectorType" : "Product", "enabled
" : true, "online" : true, "lastExecuted" : NumberLong(0) }
{ "_id" : ObjectId("56caf4bc68673320bc736772"), "_class" : "com.capitalone.dashb
oard.model.HudsonCollector", "buildServers" : [ "http://localhost:9080" ], "nice
Names" : [ ], "name" : "Hudson", "collectorType" : "Build", "enabled" : true, "o
nline" : true, "lastExecuted" : NumberLong("1456170000077") }
{ "_id" : ObjectId("56cafa98686733222ce169f6"), "_class" : "com.capitalone.dashb
oard.model.SonarCollector", "sonarServers" : [ "http://localhost:9000" ], "name"
 : "Sonar", "collectorType" : "CodeQuality", "enabled" : true, "online" : true,
"lastExecuted" : NumberLong("1456170000665") }

**Comment by tabladrum** [comment]
Can you paste the documents from Collector collection?

**Comment by jaspreetsinghmadan** [comment]
{ "_id" : ObjectId("56c5beb0b0269915a0678bc9"), "_class" : "com.capitalone.dashb
oard.model.Collector", "name" : "Product", "collectorType" : "Product", "enabled
" : true, "online" : true, "lastExecuted" : NumberLong(0) }
{ "_id" : ObjectId("56caf4bc68673320bc736772"), "_class" : "com.capitalone.dashb
oard.model.HudsonCollector", "buildServers" : [ "http://localhost:9080" ], "nice
Names" : [ ], "name" : "Hudson", "collectorType" : "Build", "enabled" : true, "o
nline" : true, "lastExecuted" : NumberLong("1456170000077") }
{ "_id" : ObjectId("56cafa98686733222ce169f6"), "_class" : "com.capitalone.dashb
oard.model.SonarCollector", "sonarServers" : [ "http://localhost:9000" ], "name"
 : "Sonar", "collectorType" : "CodeQuality", "enabled" : true, "online" : true,
"lastExecuted" : NumberLong("1456170000665") }
> db.collectors.find()
{ "_id" : ObjectId("56c5beb0b0269915a0678bc9"), "_class" : "com.capitalone.dashb
oard.model.Collector", "name" : "Product", "collectorType" : "Product", "enabled
" : true, "online" : true, "lastExecuted" : NumberLong(0) }
{ "_id" : ObjectId("56caf4bc68673320bc736772"), "_class" : "com.capitalone.dashb
oard.model.HudsonCollector", "buildServers" : [ "http://localhost:9080" ], "nice
Names" : [ ], "name" : "Hudson", "collectorType" : "Build", "enabled" : true, "o
nline" : true, "lastExecuted" : NumberLong("1456170000077") }
{ "_id" : ObjectId("56cafa98686733222ce169f6"), "_class" : "com.capitalone.dashb
oard.model.SonarCollector", "sonarServers" : [ "http://localhost:9000" ], "name"
 : "Sonar", "collectorType" : "CodeQuality", "enabled" : true, "online" : true,
"lastExecuted" : NumberLong("1456170000665") }
>

**Comment by jaspreetsinghmadan** [comment]
{ "_id" : ObjectId("56c5beb0b0269915a0678bc9"), "_class" : "com.capitalone.dashb
oard.model.Collector", "name" : "Product", "collectorType" : "Product", "enabled
" : true, "online" : true, "lastExecuted" : NumberLong(0) }
{ "_id" : ObjectId("56caf4bc68673320bc736772"), "_class" : "com.capitalone.dashb
oard.model.HudsonCollector", "buildServers" : [ "http://localhost:9080" ], "nice
Names" : [ ], "name" : "Hudson", "collectorType" : "Build", "enabled" : true, "o
nline" : true, "lastExecuted" : NumberLong("1456170000077") }
{ "_id" : ObjectId("56cafa98686733222ce169f6"), "_class" : "com.capitalone.dashb
oard.model.SonarCollector", "sonarServers" : [ "http://localhost:9000" ], "name"
 : "Sonar", "collectorType" : "CodeQuality", "enabled" : true, "online" : true,
"lastExecuted" : NumberLong("1456170000665") }
> db.collectors.find()
{ "_id" : ObjectId("56c5beb0b0269915a0678bc9"), "_class" : "com.capitalone.dashb
oard.model.Collector", "name" : "Product", "collectorType" : "Product", "enabled
" : true, "online" : true, "lastExecuted" : NumberLong(0) }
{ "_id" : ObjectId("56caf4bc68673320bc736772"), "_class" : "com.capitalone.dashb
oard.model.HudsonCollector", "buildServers" : [ "http://localhost:9080" ], "nice
Names" : [ ], "name" : "Hudson", "collectorType" : "Build", "enabled" : true, "o
nline" : true, "lastExecuted" : NumberLong("1456170000077") }
{ "_id" : ObjectId("56cafa98686733222ce169f6"), "_class" : "com.capitalone.dashb
oard.model.SonarCollector", "sonarServers" : [ "http://localhost:9000" ], "name"
 : "Sonar", "collectorType" : "CodeQuality", "enabled" : true, "online" : true,
"lastExecuted" : NumberLong("1456170000665") }
>

**Comment by tabladrum** [comment]
I am not seeing the stash collector in there. Making sure you ran the stash collector and it didnt have any error

**Comment by jaspreetsinghmadan** [comment]
[collectors.txt](https://github.com/capitalone/Hygieia/files/208585/collectors.txt)

**Comment by jaspreetsinghmadan** [comment]
check this file. Sorry earlier It was not getting copied correctly.

**Comment by tabladrum** [comment]
You dont have a StashCollector - 
Can you see the log for stash collector?

**Comment by jaspreetsinghmadan** [comment]
[stash-collector-2016-04-07.0 - Copy.txt](https://github.com/capitalone/Hygieia/files/208602/stash-collector-2016-04-07.0.-.Copy.txt)

**Comment by tabladrum** [comment]
I am pretty sure (at this point) that you have two databases in MongoDB. One is the good one that is read by API and other collectors that you pasted above. I think your Stash Collector is configured to go to another database. Can you confirm
1. How many databases you have in Mongo
2. Properties file for the Stash Collector and your command line

**Comment by jaspreetsinghmadan** [comment]
BINGO.... Thanks a lot. Its working now.
The problem was it was referring to another db. 

Configuration was
#Database Name 
spring.data.mongodb.database=dashboardb

And i changed to 
#Database Name 
dbname=dashboardb

It worked fine.

**Comment by tabladrum** [comment]
:+1: 
Close this if you are good to now. 
Thanks

**Comment by jaspreetsinghmadan** [comment]
Awesome help...Quick response, i haven't such a quick response ever...
You people ROCK....
