### ISSUE TITLE
90 day pipeline health

### ISSUE THREAD

**Issue by venkiradkris** [capitalone/Hygieia#2173]
Hi
Is there any configuration/change i can make to reduce the number "90" to "5" or "10" days?
Regards
Venkat

**Comment by nireeshT** [comment]
@venkiradkris  yes there is a work around for that. Go to /product/view.js -> ctrl.load() and change the value of 90. 
Go to pipeline ServiceImpl and chnage PROD_COMMIT_DATE_RANGE_DEFAULT = 90 

build and restart

**Comment by venkiradkris** [comment]
Thanks. I will try and update.
