### ISSUE TITLE
Date label (X axes of chart) is not getting refreshed in chart displayed on Hygieia UI

### ISSUE THREAD

**Issue by sandip-1234** [capitalone/Hygieia#2177]
Hi,

   I have integrated hygieia with jenkins in my current project. All data are correct except date displayed as label in chart. Date only refreshed if i use press F5 key. Could you suggest what is the issue.

**You can see in below screen shoot that system date is 27-Apr(Pic-2) but in chart it is 25-Apr(Pic-1)**..

 Thank's in advance

 Sandip Sharma

![hygieia](https://user-images.githubusercontent.com/25976971/39359355-56defbc2-4a37-11e8-89ab-e4fcdf63b473.png)

**Comment by sandip-1234** [comment]
I am using a plugin here to display dates. These date are not getting refreshed. Following code are used to display date.

ctrl.combinedChartOptions = {
            plugins: [
                Chartist.plugins.gridBoundaries(),
                Chartist.plugins.lineAboveArea(),
                Chartist.plugins.pointHalo(),
                Chartist.plugins.ctPointClick({
                    onClick: showDetail
                }),
                Chartist.plugins.axisLabels({
                    stretchFactor: 1.4,
                    **axisX: {
                        labels: [
                            moment().subtract(14, 'days').format('MMM DD'),
                            moment().subtract(7, 'days').format('MMM DD'),
                            moment().format('MMM DD')
                        ]
                    }**
                }),
                Chartist.plugins.ctPointLabels({
                    textAnchor: 'middle'
                })
            ],

            showArea: false,
            lineSmooth: false,
            fullWidth: true,
            axisY: {
                offset: 30,
                showGrid: true,
                showLabel: true,
                labelInterpolationFnc: function (value) {
                    console.log(value);
                    return Math.round(value * 100) / 100;
                }
            }
        };

**Comment by matthewbeasley** [comment]
@sandip-1234 - you are using an old version on the application. Please pull the latest version.
