### ISSUE TITLE
Question about Hygieia

### ISSUE THREAD

**Issue by anayyadav** [capitalone/Hygieia#2182]
I have a question regarding Hygieia collectors that Suppose I want to create a collector and I'm successfully getting the data. 
Now what are the other steps, so that I can get the data on dashboard.
What are the files needs to be updated after creating the collector please explain me in detail step by step .

**Comment by nireeshT** [comment]
@anayyadav  refer https://github.com/capitalone/Hygieia/issues/2114

**Comment by nireeshT** [comment]
@anayyadav  reopen issue if it is not resolved
