### ISSUE TITLE
How we can add NEW widget in UI ?

### ISSUE THREAD

**Issue by sitharthan** [capitalone/Hygieia#2187]
Hi Everyone,

I want to add one more widget for displaying Defects list with ageing details. So how we can create new widget in Component folder? . Is there any command available? or we need to create manually for all files of component->Widgets folder.

![image](https://user-images.githubusercontent.com/6356904/39562893-9b5b7c1a-4ecb-11e8-96ca-cdbe8fe65e86.png)

Kindly please advise me . what can i do for that?.. Thanks in Advance

**Comment by sitharthan** [comment]
Could you please help on this one ? .. @tabladrum

**Comment by Sbrenthughes** [comment]
This is a manual step. There is no script to do this.

**Comment by sitharthan** [comment]
Thanks lot @Sbrenthughes .. now closing this issue :)
