### ISSUE TITLE
No data for cloud_subnetwork cloud_virtual_network

### ISSUE THREAD

**Issue by dzoneuser** [capitalone/Hygieia#2188]
Dear Team, I am new to Hygieia. I have setup Hygieia as per the documentation and I could start my application and see the dashboard successfully. I could see values coming for all widget items (say utilization, instances stoped, and so on.) except the IPUtilization widget. When i see the mongodb (after I ran AWS module)  i could see data for most of the documents except the cloud_subnetwork and cloud_virtual_network. Is this causing the issue?

Can anyone please assist me for populating IPUtilization widget ?
if I am still missing with anything? Anyfurther configuration to be made for this?

**Comment by subodhbattina** [comment]
@dzoneuser: Can you please share a screen shot of your dashboard+IPUtilization widget you are referring to? 
And when you say ran AWS module, do you mean the AWSCloudCollector? If so, please share your properties and also the log of you collector run. Thanks

**Comment by subodhbattina** [comment]
@dzoneuser: Since we didn't hear back from you, assuming this is resolved at your end, closing the issue for now.
