### ISSUE TITLE
how to debug hygieia application

### ISSUE THREAD

**Issue by dzoneuser** [capitalone/Hygieia#2189]
Dear Team , I have setup Hygieia in my system and able to see the dashboard in my browser.  I am using STS ide and for running the command (as mentioned in the documentation) i use windows-command prompt.

I wanted to see the application working in debug mode when i start any module (say for eg., i wanted to debug and see how data is collected and inserted while running the module:- Collector-AWS).

Could you please let  me know how would I debug the application -module  (or to run the application in debug mode and inspect values) inside IDE or any other way.

I tried the way {Debug as->Java Application} as mentioned in some other solutions but that dint work , as we need to provide the main-class for this method. 

kindly assist

**Comment by Sbrenthughes** [comment]
I use intelliJ  by creating a run/debug configuration and running in debug mode that way. I would suggest looking up how to run a spring boot application in your IDE. Once you can run it in your IDE then you can work on running in debug mode.
