### ISSUE TITLE
api-audit compile error

### ISSUE THREAD

**Issue by sraghu-rs** [capitalone/Hygieia#2198]
mvn install on "api-audit" is throwing compile error message on "DashboardAuditModel.java" source file.

**[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project api-audit: Compilation failure
[ERROR] /opt/Hygieia/Hygieia/api-audit/src/main/java/com/capitalone/dashboard/model/DashboardAuditModel.java:[43,43] incompatible types: inference variable V has incompatible bounds
[ERROR]     equality constraints: com.capitalone.dashboard.evaluator.Evaluator
[ERROR]     lower bounds: ? extends com.capitalone.dashboard.evaluator.Evaluator<? extends com.capitalone.dashboard.response.AuditReviewResponse<? extends java.lang.Enum<? extends java.lang.Enum<?>>>>,U**

can someone suggest the resolution.

**Comment by Sbrenthughes** [comment]
https://github.com/capitalone/Hygieia/issues/1964. Please reopen if this does not solve the problem
