### ISSUE TITLE
Failed with UI error 

### ISSUE THREAD

**Issue by trinathtiru** [capitalone/Hygieia#2200]
Hi,

I am trying to install the hygieia in my vm and aws machine but i am facing the below UI error.

can you please help me to sort it out this issue?
![image](https://user-images.githubusercontent.com/33506201/39908094-249fe738-550a-11e8-8734-c9da9ba9c276.png)

Thanks
Seenu

**Comment by cradules** [comment]
Hey,

I had same issue and I have solved it as fallow:

1. First step is to compile UI. 

cd /path/where/sourcecode/exist/UI
npm install gulp
npm install bower
npm install
bower install
mvn clean install package

2. Second step
cd /path/where/sourcecode/exist/
npm install bower
npm install
bower install
mvn clean install package

NOTE:

Dont run the compile under sudo/root. 
Create a user and compile the code under that user. 
Make sure you have installed  java 1.8 and nodejs ( I am using nodejs-10.x,.x)
Make sure all the files/folders has the owner the user you have created. 

I am building now a script to make full install and configuration for this dashboard. Soon is done I will share it.

**Comment by trinathtiru** [comment]
Hi @cradules,
Thanks for the great information.
My bad..! i tried with the root user in aws machine and stuck with this issue.
Now i will add the user to my machine and check.
Hope this time it will work well.

**Comment by trinathtiru** [comment]
Hi @cradules 
This time i tried with the new user and followed the above steps.
But, this time it fails with the step-bower install under hygieia/UI folder. 
![image](https://user-images.githubusercontent.com/33506201/39917989-ca983614-552c-11e8-8c43-f351d8a8145c.png)

Then i try to add the user with the below commands
/opt/hygieia/UI$ sudo chown -R $HYGIEIA:$HYGIEIA ~/.npm
/opt/hygieia/UI$ sudo chown -R $HYGIEIA:$HYGIEIA ~/.config

Please let me know how to proceed further?
Thanks In-advance
Seenu

**Comment by cradules** [comment]
You have run under root npm install and this creates a lot of issues. 

remove node js
install again nodejs
then delete the present source files 
clone the source again. Make sure you run git clone  under the user you have created
fallow exact the stepts I have given it to you above. First compile the UI then you go in root source path and compile again.

**Comment by trinathtiru** [comment]
Hi @cradules 

Thanks for the info. I have uninstalled all & trying to install the git from new user & its populating the below error.

hygieia@ip-172-31-20-194:~$ apt-get install git
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?

Can i use sudo now for this?

**Comment by trinathtiru** [comment]
I have created the user with the below command
adduser hygieia
passwd ******
furthermore, i have added the username in visudo file under group

# Allow members of group sudo to execute any command
%sudo   ALL=(ALL:ALL) ALL
hygieia ALL=(ALL:ALL) ALL

Please correct me if i am wrong?

**Comment by cradules** [comment]
Hi,

If you dont have git installed:

sudo apt-get install git
then
su - hygieia
Go to the location where you want to install the application and clone the repo locally:
git clone https://github.com/capitalone/Hygieia.git

cd Hygieia/UI
npm install gulp
npm install bower
npm install
bower install
mvn clean install package

Afer
cd Hygieia
npm install gulp
npm install bower
npm install
bower install
mvn clean install package

Good luck!

**Comment by trinathtiru** [comment]
Hi @cradules 

Thanks for the help. 
I tried with the above steps again in new aws linux machine but still facing the issue. 
Please find the below attachment with complete steps.

[hygieia.docx](https://github.com/capitalone/Hygieia/files/1999708/hygieia.docx)

Please correct me if i am wrong...?
Regards
Seenu

**Comment by trinathtiru** [comment]
Hi @cradules 
Thank you so much for the information.
It was successful with the above steps...

Furthermore, will dashboard.properties file generated by default?

**Comment by cradules** [comment]
No. You need to make it manually. Check the docs for how to.

**Comment by trinathtiru** [comment]
Hi @cradules,
Thanks again. 
I have installed the mongodb on my ubuntu machine using the below link.
https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/

After installation i just created the db and user using below steps
command :   $ mongo
               MongoDB shell version: 3.0.
               connecting to: test
               > use dashboarddb
                 switched to db dashboarddb
 > db.createUser(
                 {
                   user: "dashboarduser",
                   pwd: "dbpassword",
                   roles: [
                      {role: "readWrite", db: "dashboard"}
                           ]
                   })
        
       
                   Output similar to below should be seen in your mongo shell
                  
               Successfully added user: {
                 "user" : "dashboarduser",
                 "roles" : [
                 {
                   "role" : "readWrite",
                   "db" : "dashboard"
                 }
                 ]
}
Furthermore, In the dashboard. properties file i added the below details and try to run the api from api/target folder  but it's failing with authentication error.
dbname=dashboard
dbusername=dashboarduser
dbpassword=dbpassword

java -jar api.jar --spring.config.location=/usr/Hygieia/api/dashboard.properties -Djasypt.encryptor.password=hygieiasecret
Error:Authentication failure

Can you please help to fix this?

Regards
Seenu

**Comment by trinathtiru** [comment]
Hello @cradules 

com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='dashboarduser', source='dashboarddb', password=<hidden>, mechanismProperties={}}
        at com.mongodb.connection.SaslAuthenticator.authenticate(SaslAuthenticator.java:61) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.InternalStreamConnectionInitializer.authenticateAll(InternalStreamConnectionInitializer.java:99) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.InternalStreamConnectionInitializer.initialize(InternalStreamConnectionInitializer.java:44) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:115) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:127) ~[mongo-java-driver-3.0.2.jar!/:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
Caused by: com.mongodb.MongoCommandException: Command failed with error 18: 'Authentication failed.' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Authentication failed.", "code" : 18, "codeName" : "AuthenticationFailed" }
        at com.mongodb.connection.CommandHelper.createCommandFailureException(CommandHelper.java:168) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.CommandHelper.receiveCommandResult(CommandHelper.java:123) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.CommandHelper.executeCommand(CommandHelper.java:32) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.SaslAuthenticator.sendSaslContinue(SaslAuthenticator.java:99) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.SaslAuthenticator.authenticate(SaslAuthenticator.java:58) ~[mongo-java-driver-3.0.2.jar!/:na]
   
Regards
Seenu

**Comment by Sbrenthughes** [comment]
If you are not using the encryption piece then you need to remove `Djasypt.encryptor.password=hygieiasecret` from your command

**Comment by trinathtiru** [comment]
Hi @Sbrenthughes 

thanks for the information. i have created the new user with that my issue was resolved.

thanks @cradules  for the help
