### ISSUE TITLE
Dashboard UI - login page not loading

### ISSUE THREAD

**Issue by sushmaharish** [capitalone/Hygieia#2201]
Dashboard UI - login page not loading - when I click on login icon , it is redirecting to some other oage instead of login page, 
Please help
Hygieia home page:
![hygieia-home](https://user-images.githubusercontent.com/34368469/39993436-740aaa7a-5793-11e8-8500-0a64aee79276.png)

Redirected page:
![hygieia-login](https://user-images.githubusercontent.com/34368469/39993445-7ece09de-5793-11e8-99ca-adfadd93bf96.png)

**Comment by micahbhodge** [comment]
This is a recurring issue that causes us to constantly launch incognito windows to view dashboards. Is there a fix for this issue or is it an accepted behavior?
