### ISSUE TITLE
Springboot and maven dependencies error

### ISSUE THREAD

**Issue by AnanyaSreepathi** [capitalone/Hygieia#2204]
**I have a sample spring boot app to deploy in my system which is throwing me following error.I tried cleaning up the maven files from cache still struck with the issue. Can anyone help me with this. Following is the error I Get**

(Project build error: Non-resolvable parent POM for com.broad.gateway:com-
 gateway:0.0.1-SNAPSHOT: Could not transfer artifact 
 org.springframework.boot:spring-boot-starter-parent:pom:2.0.2.RELEASE from/to 
 central (https://repo.maven.apache.org/maven2): connect timed out and 
 'parent.relativePath' points at no local POM)

**Comment by AnanyaSreepathi** [comment]
No, as I said I am trying to run my sample app in my local but facing Maven POM error

**Comment by Sbrenthughes** [comment]
I apologize, "a sample spring boot app" is a bit confusing. I see now that you are trying to set up Hygieia locally. 

Are you running `mvn clean install` form the Hygieia root directory?

**Comment by AnanyaSreepathi** [comment]
I am sorry , could you tell me what do you mean by 'hygieia'? 
I downloaded a sample app from  (https://projects.spring.io/spring- boot/): which installed my dependencies required to run my springboot application. Now when I am trying to run that it is throwing following error

Project build error: Non-resolvable parent POM for com.broad.gateway:com-gateway:0.0.1-SNAPSHOT: Failure to transfer org.springframework.boot:spring-boot-starter-parent:pom:2.0.2.RELEASE from https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:2.0.2.RELEASE from/to central (https://repo.maven.apache.org/maven2): connect timed out and 'parent.relativePath' points at no local POM

**Comment by Sbrenthughes** [comment]
@AnanyaSreepathi  Closing this because your issue is not related to Hygieia.
