### ISSUE TITLE
Issue with the API

### ISSUE THREAD

**Issue by trinathtiru** [capitalone/Hygieia#2206]
Hello All,

i have installed the hygieia in my ubuntu machine and generated the jar file using below command.

mvn clean install package.

Now i am trying to start the UI using gulp serve from UI folder.
But i am stuck with the below image.

![image](https://user-images.githubusercontent.com/33506201/40100659-57470cce-5902-11e8-9285-ab3a8e7f34b4.png)

Can anyone guide me to fix this?

**Comment by nireeshT** [comment]
@trinathtiru  you tried launching http://localhost:3000 in browser

**Comment by trinathtiru** [comment]
Started working with the public Ip address..
@nireeshT  thanks for the help
