### ISSUE TITLE
Need a Step-by-step guide

### ISSUE THREAD

**Issue by softwareklinic** [capitalone/Hygieia#221]
Looks like this tool has great potential and it has caused some initial pain and frustration when trying out... There are some steps on how to build/install, configure docker container etc.. but what is missing is end-2-end configuration.. say for a given version of Jira, Jenkins, Stash, Sonar, etc... with URL examples, complete details on how to configure this tool... without missing any heartbeat

I have started to compile a word document with screenshots... and will try to post it here... but currently stuck with collectors not collecting and displaying data in UI except JENKINS... most stash/bitbucket/git/jira collectors are having some or the other issue.. most likely it is due to lack of knowledge or steps on how to configure those seamlessly.

**Comment by manishtyagi** [comment]
Can you please share the details of how you displayed Jenkins data? thanks!

**Comment by satishc1** [comment]
Refer to http://www.capitalone.io/Hygieia/ for detailed documentation. The "Getting started" section details the build instructions. The "Collectors" section lists details about the specific collectors and how to configure them.

**Comment by Mahendra1260** [comment]
I have Linux  server where I have build the Hygieia project which is successful. The Same server also has MongoDB installed and running fine.
While build UI layer, the documentation says Install on Mac or Install on Windows. Can I the build layer on the same server Linux, if yes, what are the steps for Linux.

**Comment by mrpudn** [comment]
Yes - you will need to install [`node.js`](https://nodejs.org/en/) on your linux server and the UI should build properly.

**Comment by sudha124** [comment]
i have nodejs installed on centos7 but its keep failing..

**Comment by mrpudn** [comment]
If you're continuing to have problems and you've tried the documentation that @satishc1 provided and nothing in an existing issue resolves your problem, then please create a new issue with logs and any other information for us to help with your problem.

**Comment by stefanmueller21** [comment]
@Mahendra1260 Do you have a high level documentation or something like step by step guide to install it on Linux?
