### ISSUE TITLE
Hygieia Dashboard issue:

### ISSUE THREAD

**Issue by venkataallu** [capitalone/Hygieia#2211]
Hygiea main dashboard  page is displaying, however Dashborads are not displaying.

got below errors while UI builds (however build was success)

[INFO] --- frontend-maven-plugin:0.0.29:install-node-and-npm (install node and npm) @ UI ---
[INFO] Found proxies: [optional{protocol='https', host='', port=3128}]
[INFO] Node v6.9.1 is already installed.
[INFO] NPM 2.14.15 is already installed.
[INFO]
[INFO] --- frontend-maven-plugin:0.0.29:npm (npm install) @ UI ---
[INFO] Found proxies: [optional{protocol='https', host=', port=3128}]
[INFO] Running 'npm install --https-proxy=
' in /appl/bamboo/freeware/hyieia_git/Hygieia/UI
[ERROR] npm WARN deprecated jade@1.8.2: Jade has been renamed to pug, please install the latest version of pug instead of jade
[ERROR] WARN engine karma@0.13.22: wanted: {"node":"0.10 || 0.12 || 4 || 5"} (current: {"node":"6.9.1","npm":"2.14.15"})
[ERROR] (node:61332) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[ERROR] npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[ERROR] npm WARN deprecated gulp-util@3.0.7: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[ERROR] npm WARN deprecated gulp-header@1.8.2: gulp-header 1.x is deprecated and will no longer be updated, please update to 2.x
[ERROR] npm WARN deprecated gulp-util@2.2.20: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[ERROR] npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[ERROR] npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[ERROR] npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[ERROR] npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[ERROR] npm WARN optional dep failed, continuing fsevents@1.2.4
[ERROR] npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated
[ERROR] npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
[ERROR] npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
[ERROR] npm WARN deprecated constantinople@3.0.2: Please update to at least constantinople 3.1.1
[ERROR] npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
[ERROR] npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
[ERROR] npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
[ERROR] npm WARN deprecated natives@1.1.3: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
[ERROR] npm WARN optional dep failed, continuing fsevents@1.2.4
[ERROR] npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
[INFO]
[INFO] > gifsicle@3.0.4 postinstall /appl/bamboo/freeware/hyieia_git/Hygieia/UI/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
[INFO] > node lib/install.js
[INFO]
[ERROR]   ⚠ tunneling socket could not be established, cause=socket hang up
[ERROR]   ⚠ gifsicle pre-build test failed
[ERROR]   ℹ compiling from source
[ERROR]   ✖ RequestError: tunneling socket could not be established, cause=socket hang up
[ERROR]     at ClientRequest.<anonymous> (/appl/bamboo/freeware/hyieia_git/Hygieia/UI/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/got/index.js:74:21)
[ERROR]     at ClientRequest.g (events.js:291:16)
[ERROR]     at emitOne (events.js:96:13)
[ERROR]     at ClientRequest.emit (events.js:188:7)
[ERROR]     at ClientRequest.onError (/appl/bamboo/freeware/hyieia_git/Hygieia/UI/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/caw/node_modules/tunnel-agent/index.js:178:21)
[ERROR]     at ClientRequest.g (events.js:291:16)
[ERROR]     at emitOne (events.js:96:13)
[ERROR]     at ClientRequest.emit (events.js:188:7)
[ERROR]     at TLSSocket.socketErrorListener (_http_client.js:310:9)
[ERROR]     at emitOne (events.js:96:13)
[INFO]
[INFO] > jpegtran-bin@3.2.0 postinstall /appl/bamboo/freeware/hyieia_git/Hygieia/UI/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
[INFO] > node lib/install.js

[INFO] > node lib/install.js
[INFO]
[ERROR]   ⚠ tunneling socket could not be established, cause=socket hang up
[ERROR]   ⚠ jpegtran pre-build test failed
[ERROR]   ℹ compiling from source
[ERROR]   ✖ RequestError: tunneling socket could not be established, cause=socket hang up
[ERROR]     at ClientRequest.<anonymous> (/appl/bamboo/freeware/hyieia_git/Hygieia/UI/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-build/node_modules/download/node_modules/got/index.js:74:21)
[ERROR]     at ClientRequest.g (events.js:291:16)
[ERROR]     at emitOne (events.js:96:13)
[ERROR]     at ClientRequest.emit (events.js:188:7)
[ERROR]     at ClientRequest.onError (/appl/bamboo/freeware/hyieia_git/Hygieia/UI/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-build/node_modules/download/node_modules/caw/node_modules/tunnel-agent/index.js:178:21)
[ERROR]     at ClientRequest.g (events.js:291:16)
[ERROR]     at emitOne (events.js:96:13)
[ERROR]     at ClientRequest.emit (events.js:188:7)
[ERROR]     at TLSSocket.socketErrorListener (_http_client.js:310:9)
[ERROR]     at emitOne (events.js:96:13)
[INFO]
[INFO] > optipng-bin@3.1.4 postinstall /appl/bamboo/freeware/hyieia_git/Hygieia/UI/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
[INFO] > node lib/install.js
[INFO]
[ERROR]   ⚠ tunneling socket could not be established, cause=socket hang up
[ERROR]   ⚠ optipng pre-build test failed
[ERROR]   ℹ compiling from source
[ERROR]   ✖ RequestError: tunneling socket could not be established, cause=socket hang up
[ERROR]     at ClientRequest.<anonymous> (/appl/bamboo/freeware/hyieia_git/Hygieia/UI/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/download/node_modules/got/index.js:74:21)
[ERROR]     at ClientRequest.g (events.js:291:16)
[ERROR]     at emitOne (events.js:96:13)
[ERROR]     at ClientRequest.emit (events.js:188:7)
[ERROR]     at ClientRequest.onError (/appl/bamboo/freeware/hyieia_git/Hygieia/UI/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/download/node_modules/caw/node_modules/tunnel-agent/index.js:178:21)
[ERROR]     at ClientRequest.g (events.js:291:16)
[ERROR]     at emitOne (events.js:96:13)
[ERROR]     at ClientRequest.emit (events.js:188:7)
[ERROR]     at TLSSocket.socketErrorListener (_http_client.js:310:9)
[ERROR]     at emitOne (events.js:96:13)
[INFO]
[INFO] > phantomjs@1.9.20 install /appl/bamboo/freeware/hyieia_git/Hygieia/UI/node_modules/karma-phantomjs-launcher/node_modules/phantomjs
[INFO] > node install.js
[INFO]
[INFO] Considering PhantomJS found at /appl/bamboo/phantomjs-1.9.8-linux-x86_64/bin/phantomjs
[INFO] Found PhantomJS at /appl/bamboo/phantomjs-1.9.8-linux-x86_64/bin/phantomjs ...verifying
[INFO] Writing location.js file

Can somebody help with this.

**Comment by venkataallu** [comment]
![image](https://user-images.githubusercontent.com/39357651/40154670-17026bac-59c2-11e8-9a91-c7c192085748.png)

**Comment by cradules** [comment]
I see you are using Bamboo to deploy it. " tunneling socket could not be established, cause=socket hang up' smells to me that you are behind a proxy. You have an connectivity issue there, proxy/firewall or some restrictions from Bamboo..

**Comment by nireeshT** [comment]
@venkataallu could be issue with npm version. Are you first time user?

**Comment by trinathtiru** [comment]
@venkataallu Please run the api command and then try to run gulp serve under UI folder.
API command:
java -jar api.jar --spring.config.location=/opt/hygieia/hygieia/dashboard.properties -Djasypt.encryptor.password=hygieiasecret

**Comment by matthewbeasley** [comment]
@venkataallu - please follow some of the previous suggestions
