### ISSUE TITLE
Api Connectivity Issue

### ISSUE THREAD

**Issue by trinathtiru** [capitalone/Hygieia#2212]
Hi All,

I am trying to connect the API. but i am facing the below error.

![image](https://user-images.githubusercontent.com/33506201/40155589-30bf284c-59b2-11e8-81ce-4974410e3083.png)

Can some one please help on this ?

**Comment by cradules** [comment]
Got same issue if I made the build on docker. Personally I gave up on docker  since has to many issues. If not docker installation and u made a standalone install, check if the api services are up, more exactly look for the port if is open and if it is check with telnet if accepting connections. This shouw that the dashboard cant connect to api

**Comment by trinathtiru** [comment]
Hi @cradules 

Thanks for the information.
I am doing this in linux box not in docker.Furthermore, i  have eneabled the ports that are looking but still facing the issue. Please find my dahboard.properties file.
dbname=dashboarddb
dbusername=dashboarduser
dbpassword=12345678
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=
server.contextPath=/api
server.port=8080
corsEnabled=false
corsWhitelist=
version.number=@application.version.number@

auth.expirationTime=6000000
auth.secret=

# LDAP Server Url, including port of your LDAP server
auth.ldapServerUrl=

# If using standard ldap
# LDAP User Dn Pattern, where the username is replaced with '{0}'
auth.ldapUserDnPattern=

# If using ActiveDirectory
# This will be the domain part of your userPrincipalName
auth.adDomain=
# This will be your root dn
auth.adRootDn=

monitor.proxy.host=
monitor.proxy.type=
monitor.proxy.port=8080
monitor.proxy.username=
monitor.proxy.password=

pageSize=10


key=

auth.userEid=
auth.userEmail=
auth.userFirstName=
auth.userLastName=
auth.userMiddelInitials=
auth.userDisplayName=

Also, Please find the below error message when i am giving gulp serve under hygieia/Ui folder

![image](https://user-images.githubusercontent.com/33506201/40164928-773fc6de-59d8-11e8-96d1-3a4511aa277a.png)

**Comment by trinathtiru** [comment]
Hi @cradules ,

My bad.. ! After restarting my AWS server i didnt restarted the API using below command
 java -jar api.jar --spring.config.location=/opt/hygieia/hygieia/dashboard.properties -Djasypt.encryptor.password=hygieiasecret


After restarting the API the issue got resolved.

Thanks again for the help @cradules
