### ISSUE TITLE
Bitbucket collector -- decryptedPassword issue

### ISSUE THREAD

**Issue by 0-d** [capitalone/Hygieia#2216]
I have a private repo on Bitbucket server (stash). I configured everything as described here: http://capitalone.github.io/Hygieia/setup.html#encryption-for-private-repos but still got 401 error, so I decided to investigate the case before posting a new issue.

I've added `LOG.debug("decryptedPassword: " + decryptedPassword);` to `DefaultBitbucketServerClient.java` and here's what I've seen in the log: 

```
DEBUG c.c.d.c.DefaultBitbucketServerClient - decryptedPassword: rd
```

Guess what? My password is `rd#SomeOtherSymbolsAndDigits`. Looks like the hashtag symbol `#` ruins the decryption process. Therefore I am forced to change password or use other credentials with no `#` in the password string.

Any suggestions how to fix this? I am not a java programmer so I can't fix it myself and I really don't want to change password on a technical login.

**Comment by Sbrenthughes** [comment]
Encryption and Decryption is handle via a Java library. Hygieia doesn't manage this.
