### ISSUE TITLE
Configure github widget

### ISSUE THREAD

**Issue by trinathtiru** [capitalone/Hygieia#2219]
Hello All,

I am trying to configure the github widget and facing the below error.

2018-05-18 06:25:21,614 ERROR o.s.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gitHubCollectorTask': Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]

Please find my application.properties file
 #database Name
dbname=dashboarddb

#Database HostName - default is localhost
dbhost=localhost

 # Database Port - default is 27017
dbport=27017

 # MongoDB replicaset
dbreplicaset=false
dbhostport=

 #Database Username - default is blank
dbusername=dashboarduser

  # Database Password - default is blank
dbpassword=12345678

 # Logging File location
logging.file=./logs/github.log

 # Collector schedule (required)
github.cron=0 0/5 * * * *

github.host=github.com

 # Maximum number of previous days from current date, when fetching commits
github.commitThresholdDays=15

 # Optional: Error threshold count after which collector stops collecting for a collector item. Default is 2.
github.errorThreshold=1

    # This is the key generated using the Encryption class in core
github.key=Uf+WzWQgaIre7y9gY442JgJzqpb7v/UrAMWEQG3TdG7iALPu7kYZNLna0Iuv12mW
3YotfHYDckfZn9qz7Wza7vVLQvV9534aJMREJEPkGBXPJEb2GxXqAm6iWPcIqsDg
ppSvRZ/eotSUQpF6gBekfeQaErDvpUuRZYx9UnYiU56A034PcxKjjY/TWWMm2Ait
KWtMoWCtOJN3xZrtkLcqvXExlpcVNH3lPeXlHgDo/AzSlHWyP/iL+79jKK0uLPQo
SlTKJnGymu5xciy0qeDTRZ0Dth5l8QP40sNwfD/czBTWXFWHbhXgSBsc4zbPsTbK
t15LHdgEFchrIEhi3YR4QhxdbMFeCCiH41aOMSHaVWTa0fedlXfa4v1qvhGZU1q3
sq8Hu65U3qI/VnlsvQQ+UT2vTlNPY0IB+OR0mrW1PuxoU2Kta1AD6xc1Q8pf5BnH
zqkQEJ70tqbMFI2crgGG7NAmCVTB88758Y537hNhb8xegvsYXv80HH9V8ziZ57L9
36h9RjFuDJIYszQeYfYuTYw2jwNhD5vvU8d1LIO758L7dsySEZFyQTKDaTBqPyjj
HLrTZNQD/8gqKQQc3Sz6hGkHmz7sXTMRdIA28IFt1jlqfSmH9kFe2lVpjxFQq1tI
BhXZs8tnJ+x41P3fviVuoOn4xQh7e/zfd0byQHzZ++aBa0BTCD19IDmy2RN6ukuC
nz1UbznoXYHudMXhiwOl/lduDTaxtT9CgwvovJl1Z9FMFDHmAgt5JEynqsBZVjj9
oAy2ZFyljpAT1B9UsJtagkLvNdlWw+38bcKQ/ufWFXAuaxMdlyd7DO9rWVkBLLeT
LwOkehsGDk2h1dJGRYgDO7cuXo/7SnpL9ckJbYmoGMSo93pUDKtXV0QnUH4HKXCe
QvdcR0WLa1yECRcKk6vsnDqP9gevNSn6CJd5ZXHFTAqBB0PRthISjuZonTC80L/E
9FfjgW8pB7nqkrEkLzR5qFlVCMxqIjM/YoZcKN/Ps0ehCwzTr6awK7LwpF5ObT4m
b437lKlVzKfl0QLW64OP59UuIb/ldI7GlsWwBigd9S3SOKoKZgM8KTqx6uHK01vd
L0vczDaDpifbgAk19fmX6cTZ8Rc2d6Mydw9hRcIzTkmaTl0wRq4/neF5zzUSGanr
5JpyosjEr6I0GtbaxiCXP9OPrRhDHWXTJrwNxB644lMp387Lp1y/YXVyVrvC8jnJ
Lndbj8L5dKJMfE46/wgPSa8QmEg2Q3tcOgn5oxFqjSAEKxH1yt5sa8fWYfC3DeF4
LLW+isipBby6KBguL+Wo+g1U7mLOWpXaE4+q0XmIfZEVB0no7qnrplPrgcvKVcUv
VuVBI2iVh+Dxw7qAe1CCZZEwwy9S3hNpV2qRn636cK+u3VjO53RZ5U8GdJYTiDHN
FJ+I+HsC786v5Vanxzlkr+xM2Uq/2DKvVe9crRGTlyXBScLIIWGd3i5g00Hbdfgk
vH1Hcv8DOUZcCEbz/bNS8lJ6jT2f8b+WxSYl4CKeLfW7LHTCuOJF4/vHCs7Xl8qr
i+ATLtyIQEn3ThGI43hta6u7J2Bp9odWx8IwuD4ie5CGa+r9xlq1CjkF7Hm24Nuv
u8lVIzY/DkOZfCDZcxim9JZkHc3gcrS3fTK4XejLwQA3ysX1jA9bV+h++Qql6zE5
rlOtp6ZCH1uPHULZKpuBicAa0Axnxky3njnYpCOvfaQ7yy2kMmWg27lXPZWl6ev6
nnkWJJtpkveWPSj/aRpAI1AXYv31b1elOu2y+hq0+sXL4qVnklOC9J/iP9eHDnqi
kiC9jiczR80JRDQBYxm5HPldaFLHPbNuFqG2WKXDDxYX3Ld5aWCdALXBEU5KotGk
Tc2YcjkG1pNPThHD2AV6H8t3/LsPR69TVDdbsPodDEQ0tN4UO07Ha8fvsDZUF/2Q
yTa8ZAeqEWwI0tN45Do/v6DhGa58Mf5Rn5U3Kxi9AqoIp6muPkaTit4yEO7qtlMJ
5zGA5dGufJQeFtmJDAwvtrHoO+5+hP7xzBLLduve1TuUSMncf59hJp0jCxD0VNkv
0BzPvLbXawDu+TnMwyq4tjWLditmB7N17u+iysKYAP0BOm7ZrSbSwKXOFPK+2gci
saB0uc4VrouMtRsBSazXtOmmBdjq1K08roTpgaqlOA9QURtyVnUOYjAgZLY6rl4j
NVnrX/+0H7ZUeEC6LSSzAyG9+9wa/cItw8h4ADr6qIUTTDrGlr+71ar6BGxFfrid
bAPRIJg+q9b9t/PDq63SjXv2zQQRll9eh/cI/GOClBorKLiCWBWC0OOsbTOV/T40
6960US93J+lrljhxrHf0JZBssycqqTqBJhQ0892kmdfIWG7YejTQvXwIZ+BxXnxc
vxPu2ApFamMsbdrTom+14fW0/Bjb3rxxSkmioBKrthcvXQsKTwvqJscP1jn18gYW
zJGAT5sBBoQDQfFtDtht+hL8+CJxctzfhcFJ6L7qR1hZZchVsZh41o0fh4FJk4Gz
5xJP8M29arNdElKhAdtDS/qBs7ZcKdw+BMzpwc1hx144Uj5EuhVJ/fB0PGiEbSRH
MUqKR5Dl8sK38Av7sXH3A+P0z4Z4uY2WA7Uv0naD2hi8W2xrzTBoU/eL73nSiM2e
mUuir1qm1pVgL+Pl83QDcPlsSiTKdwLcrSCXiJsg9QsC8/XfA+3uUFw99YLnL1yQ
q7B6XwH/oDo4gGO63sHoHldOlzI+o4r6OLeB5FnqHkJaEGlLc+NR1Q7okK5f5I64
KDBdnAqOAj3X+9+o5hDydJt9UF/UaV8o2nX+8gGYWfz4+VBtt5UPE30RC0pMdKDN
qIl6+ulQEJOz9Af2g56Nyan/yYClP1y0vdMXoJULCZClybw5Zg5WxFvmI3hI1J8j
HKHROQ8n6FX1SwVUY/jWcawkbQudHykVXQGsllOdipIPn1pCYBsQRb4L29Rd2nFd
J3C7RFCOqrFqRwa5dj/QANam9KYg+i4e//NTCttdJC3uqe+x2AXeJiysi6png5y5
w3SNatHuuyHslZrMKNqjmLQB6ufwJmPsTJX/OD7CTEtpUaCUgJOSpnDpgSaK8ccf

    # Personal access token generated from github and used for making authentiated calls
github.personalAccessToken=f3224263e43e8790f3fa77a20f1abb5162bb0564

**Comment by trinathtiru** [comment]
@matthewbeasley @nireeshT 
can you please help on this?

**Comment by nireeshT** [comment]
@trinathtiru send jar command used to run collector

**Comment by trinathtiru** [comment]
@nireeshT  Please find the below command
java -jar github-collector.jar --spring.config.name=github --spring.config.location=/usr/Hygieia/collectors/scm/github/application.properties

**Comment by trinathtiru** [comment]
@Megha849 @satishc1 can you please help on this

**Comment by Sbrenthughes** [comment]
Can you verify that the path to the properties file is correct?

**Comment by trinathtiru** [comment]
@Sbrenthughes yes its correct

**Comment by rvema** [comment]
@trinathtiru What was done to resolve this issue?

**Comment by Phoenix9032** [comment]
Hi ..can you please paste your API properties ? Is the key generated by core module  mentioned  in API properties as well ? Also ..I didn't use core module generated key at all and able to fetch data from GitHub .can you please comment out core module generated key and try out ?

**Comment by Phoenix9032** [comment]
I kept only the GitHub generated key

**Comment by trinathtiru** [comment]
@Phoenix9032 Please find the github application.property file
dbname=dashboarddb
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=
dbusername=dashboarduser
dbpassword=12345678
logging.file=./logs/github.log
# Collector schedule (required)
github.cron=0 0/5 * * * *
github.host=github.com
# Maximum number of previous days from current date, when fetching commits
github.commitThresholdDays=15
# Optional: Error threshold count after which collector stops collecting for a collector item. Default is 2.
github.errorThreshold=1
# This is the key generated using the Encryption class in core
github.key=rtkHFhahAiMmUaib/VdrxGQWp9OYp48y
#personal access token generated from github and used for making authentiated calls
github.personalAccessToken=

**Comment by Phoenix9032** [comment]
I am also new to this but I didnt use the core module generated key .I generated GitHub access token and used that value in the last variable in the properties file .

**Comment by trinathtiru** [comment]
@Phoenix9032 can i generate the personal access token and give a try?

**Comment by Phoenix9032** [comment]
Yes ..in absence of a better suggestion from others ...

**Comment by rvema** [comment]
@trinathtiru Are you sure your mongodb is running correctly? and the login credentials for MongoDB are correctly mentioned in the application properties .

Per the above conversation, I believe you are using the below command to bring up your application?
`java -jar github-collector.jar --spring.config.name=github --spring.config.location=/usr/Hygieia/collectors/scm/github/application.properties`

**Comment by nireeshT** [comment]
@trinathtiru @Phoenix9032 looks like there is lot of confusion going around with github.key and github.personalAccessToken 

github.key is value generated from core module. You can generate this key from UI as admin user.
1) create an admin user - useername - "admin" , password -"you can chose any password"
2) go to admin settings -> Generate Api token -> create new key by setting name  and expiration date.
<img width="536" alt="screen shot 2018-05-26 at 11 42 51 am" src="https://user-images.githubusercontent.com/22962180/40578486-6cbac84a-60da-11e8-88b9-149225534731.png">
 
3) Copy the generated key to github properties file  as github.key = "generated key".
4) Go to api.properties file, add property -> key = "generated key"
5) Generated key is used to encrypt password when you configure github repository for accessing private repos. Public repos will not require github.key or github.personalAccessToken. 

On the other hand, github.personal AccessToken is directly taken from github-> developer settings-> personalAccessToken. This value is used to access the private repos.

You can use either github.key or github.personalAccesstoken to access private repos and they are doing the same thing.

**Comment by matthewbeasley** [comment]
@trinathtiru - I think there's enough information here to answer your questions. Closing this issue. Open another if you have issues or additional questions.

**Comment by JULIANCHO923** [comment]
> @trinathtiru @Phoenix9032 looks like there is lot of confusion going around with github.key and github.personalAccessToken
> 
> github.key is value generated from core module. You can generate this key from UI as admin user.
> 
> 1. create an admin user - useername - "admin" , password -"you can chose any password"
> 2. go to admin settings -> Generate Api token -> create new key by setting name  and expiration date.
> 
> <img alt="screen shot 2018-05-26 at 11 42 51 am" width="536" src="https://user-images.githubusercontent.com/22962180/40578486-6cbac84a-60da-11e8-88b9-149225534731.png">
> 
> 1. Copy the generated key to github properties file  as github.key = "generated key".
> 2. Go to api.properties file, add property -> key = "generated key"
> 3. Generated key is used to encrypt password when you configure github repository for accessing private repos. Public repos will not require github.key or github.personalAccessToken.
> 
> On the other hand, github.personal AccessToken is directly taken from github-> developer settings-> personalAccessToken. This value is used to access the private repos.
> 
> You can use either github.key or github.personalAccesstoken to access private repos and they are doing the same thing.

...Hello!!

I don't know where i should copy the "generated key" into github

**Comment by linuer** [comment]
@JULIANCHO923 
you can do this 
![image](https://user-images.githubusercontent.com/24414009/55857467-d4d27200-5b9f-11e9-8b4a-a5bcfe66e69b.png)

**Comment by ARUPPIN** [comment]
Hi All,
Any update on this thread?

I am a newbie to Hygieia and its Setup. I was able to setup Hygieia-UI, Core and API. 
And I am facing issue while trying to Setup hygieia-github-scm-collector (Its not able to connect to repository and gives 0 enabledRepos).

Note that I followed Readme and connected to Public repo (And didn't give key, personalKey as I am connecting to Public repo), Please find my githib configs connecting to public repo ( https://github.com/Hygieia/Hygieia) as follows,

dbname=dashboarddb
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
dbusername=dashboarduser
dbpassword=dbpassword
github.proxy=

#Proxy Port
github.proxyPort=
github.proxyUser=
github.proxyPassword=

#Logging File location
logging.file=./logs/github.log

#Collector schedule (required)
github.cron=0 0/5

github.host=https://github.com/Hygieia/Hygieia

#Maximum number of previous days from current date, when fetching commits
github.commitThresholdDays=15
github.errorThreshold=1

#This is the key generated using the Encryption class in core
github.key=

#Personal access token generated from github and used for making authentiated calls
github.personalAccessToken=

**Comment by ARUPPIN** [comment]
And my logs are as follows,

2020-02-17 10:47:04,737 [main] INFO com.capitalone.dashboard.Application - Started Application in 11.205 seconds (JVM running for 12.401)
2020-02-17 10:48:00,001 [taskScheduler-1] INFO c.c.d.collector.CollectorTask - Running Collector: GitHub
2020-02-17 10:48:00,023 [taskScheduler-1] INFO c.c.d.collector.CollectorTask - -----------------------------------
2020-02-17 10:48:00,023 [taskScheduler-1] INFO c.c.d.collector.CollectorTask - Starting...
2020-02-17 10:48:00,028 [taskScheduler-1] INFO c.c.d.collector.CollectorTask - -----------------------------------
2020-02-17 10:48:00,075 [taskScheduler-1] INFO c.c.d.collector.CollectorTask - -----------------------------------
2020-02-17 10:48:00,075 [taskScheduler-1] INFO c.c.d.collector.CollectorTask - Get enabledRepos...
2020-02-17 10:48:00,080 [taskScheduler-1] INFO c.c.d.collector.CollectorTask - -----------------------------------
2020-02-17 10:48:00,083 [taskScheduler-1] INFO c.c.d.collector.CollectorTask - -----------------------------------
2020-02-17 10:48:00,090 [taskScheduler-1] INFO c.c.d.collector.CollectorTask - collector: 5e44b4a8b70a6f386485b4e8
2020-02-17 10:48:00,095 [taskScheduler-1] INFO c.c.d.collector.CollectorTask - -----------------------------------
2020-02-17 10:48:00,126 [taskScheduler-1] INFO c.c.d.collector.CollectorTask - -----------------------------------
2020-02-17 10:48:00,130 [taskScheduler-1] INFO c.c.d.collector.CollectorTask - repos: []
2020-02-17 10:48:00,136 [taskScheduler-1] INFO c.c.d.collector.CollectorTask - -----------------------------------
2020-02-17 10:48:00,151 [taskScheduler-1] INFO c.c.d.collector.CollectorTask - Repo Count 0 0s
2020-02-17 10:48:00,152 [taskScheduler-1] INFO c.c.d.collector.CollectorTask - New Commits 0 0s
2020-02-17 10:48:00,152 [taskScheduler-1] INFO c.c.d.collector.CollectorTask - New Pulls 0 0s
2020-02-17 10:48:00,155 [taskScheduler-1] INFO c.c.d.collector.CollectorTask - New Issues 0 0s
2020-02-17 10:48:00,156 [taskScheduler-1] INFO c.c.d.collector.CollectorTask - Finished 0s

Please let me know if I need to configure anything to get it working. Thanks in advance.

**Comment by ShachiRai1** [comment]
I am getting a similar issue with Bitbucket Collector. Getting repocount, commit count, pullcount as 0. Also the collector log does not show any error. On debugging, I saw enabledGitRepoSize is coming as 0. Any idea the method 'findEnabledGitRepos' in GitRepoRepository fetches which mongodb records? Also do we need to check anything in mongodb. Idont see any records in database from bitbucket collector. Below is my application.properties file for bitbucket collector. Please help
dbport=27017
dbreplicaset=false
dbhostport=127.0.0.1:27017
logging.file=./logs/bitbucket.log
git.cron=0 0/1
git.host=api.bitbucket.org/
git.username=XXXXX
git.password=XXXXXX
git.api=/api/2.0/repositories/
git.commitThresholdDays=15
git.pageSize=25
git.product=cloud
bitbucket.key=XXXX
git.key=XXXX
