### ISSUE TITLE
cant see anything under Repo Type

### ISSUE THREAD

**Issue by trinathtiru** [capitalone/Hygieia#2220]
Hi,

After installing i cant see anything under repo type. can anyone help on this to move further?

![image](https://user-images.githubusercontent.com/33506201/40220175-d425923a-5a95-11e8-8fa8-51019f909aa1.png)

**Comment by trinathtiru** [comment]
@matthewbeasley @nireeshT
can you please help on this?

**Comment by nireeshT** [comment]
@trinathtiru  you should run SCM collectors to see the list.

**Comment by trinathtiru** [comment]
@nireeshT I ran the below command
java -jar github-collector.jar --spring.config.name=github --spring.config.location=/usr/Hygieia/collectors/scm/github/application.properties
Please let me know how to proceed further

**Comment by cradules** [comment]
No idea what could be the problem, but if you can provide /usr/Hygieia/collectors/scm/github/application.properties configuration and maybe some data from logs regarding scm connection, might give us a clue what would be the issue.

**Comment by trinathtiru** [comment]
Hi @cradules,

Please find the below application.properties file configuration.

#database Name
dbname=dashboarddb
 # Database HostName - default is localhost
dbhost=localhost
                # Database Port - default is 27017
dbport=27017
                # MongoDB replicaset
dbreplicaset=false
dbhostport=
                # Database Username - default is blank
dbusername=dashboarduser
                # Database Password - default is blank
dbpassword=12345678
                # Logging File location
logging.file=./logs/github.log
                # Collector schedule (required)
github.cron=0 0/5 * * * *
github.host=github.com
                # Maximum number of previous days from current date, when fetching commits
github.commitThresholdDays=15
    # Optional: Error threshold count after which collector stops collecting for a collector item. Default is 2.
github.errorThreshold=1
    # This is the key generated using the Encryption class in core
github.key=Uf+WzWQgaIre7y9gY442JgJzqpb7v/UrAMWEQG3TdG7iALPu7kYZNLna0Iuv12mW
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx
    # Personal access token generated from github and used for making authentiated calls
github.personalAccessToken=f3224263e43e9790f3fa77a20f1abbXXXXXXXXXX

**Comment by trinathtiru** [comment]
Issue resolve after adding the secret key Thanks..! @cradules

**Comment by ARUPPIN** [comment]
Could you please let us know the resolution. I am pointing to Public repository in 'hygieia-scm-github-collector'. But its not able to get the Repo/Pulls/Commit count values correctly. 

I followed Readme and connected to Public repo (And didn't give key, personalKey as I am connecting to Public repo), Please find my githib configs connecting to public repo ( https://github.com/Hygieia/Hygieia) as follows,

dbname=dashboarddb
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
dbusername=dashboarduser
dbpassword=dbpassword
github.proxy=

#Proxy Port
github.proxyPort=
github.proxyUser=
github.proxyPassword=

#Logging File location
logging.file=./logs/github.log

#Collector schedule (required)
github.cron=0 0/5 * * * *

github.host=https://github.com/Hygieia/Hygieia

#Maximum number of previous days from current date, when fetching commits
github.commitThresholdDays=15
github.errorThreshold=1

#This is the key generated using the Encryption class in core
github.key=

#Personal access token generated from github and used for making authentiated calls
github.personalAccessToken=
