### ISSUE TITLE
Sonar collector authentication

### ISSUE THREAD

**Issue by 0-d** [capitalone/Hygieia#2224]
I am trying to collect data from SonarQube hosted server v6.7.1. I provided properties file as described here: http://capitalone.github.io/Hygieia/sonar.html but there's no clue about how to authenticate on the Sonar server. Our server requires auth to read any data.

I tried to generate api token and provide `sonar.servers[0]` as `https://api-token@sonar-server` or  `https://sonar-user:api-token@sonar-server` with no use:

`c.c.d.collector.DefaultSonar6Client - org.springframework.web.client.HttpClientErrorException: 401`

Curl, wget and powershell webrequests are all reporting status 200 with URL `https://api-token@sonar-server`. I examined `SonarCollector.java` in Hygieia project but found nothing except servers, versions, and metrics. 

Is there any way to authenticate the collector on a sonar server?

**Comment by rvema** [comment]
@0-d : Can you share the command to invoke Sonar Collector? Can you share the details of the property file for this collector?

**Comment by Sbrenthughes** [comment]
Checking out the sonar collector settings I was able to see that you should be able to do the following:
` sonar.username = `
    `sonar.password=`

**Comment by 0-d** [comment]
@Sbrenthughes it worked, thanks! 

Why is it not included in documentation?

**Comment by Sbrenthughes** [comment]
It will be updated soon.

**Comment by Sbrenthughes** [comment]
https://github.com/capitalone/Hygieia/pull/2241 For your reference

**Comment by ajayakumar-jayaraj** [comment]
@Sbrenthughes  I am facing same issue even i tried using sonar.username and password as advised here .
sonar.username=admin
sonar.password=******
2019-05-29 22:00:00,573 ERROR c.c.d.collector.DefaultSonar6Client - org.springframework.web.client.HttpClientErrorException: 401
2019-05-29 22:00:00,574 INFO c.c.d.collector.CollectorTask - Fetched projects 0 0s
2019-05-29 22:00:00,574 INFO c.c.d.collector.CollectorTask - New projects 0 0s
2019-05-29 22:00:00,627 INFO c.c.d.collector.CollectorTask - Updated 0 0s
2019-05-29 22:00:00,634 ERROR c.c.d.collector.DefaultSonar6Client - org.springframework.web.client.HttpClientErrorException: 401
2019-05-29 22:00:00,634 ERROR c.c.d.collector.SonarCollectorTask - org.springframework.web.client.HttpClientErrorException: 401
2019-05-29 22:00:00,634 INFO c.c.d.collector.CollectorTask - Finished 0s
^C2019-05-29 22:00:23,550 INFO o.s.c.a.AnnotationConfigApplicationContext - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@1b66dcf1: startup date [Wed May 29 21:55:18 EDT 2019]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@59444026
2019-05-29 22:00:23,558 INFO o.s.j.e.a.AnnotationMBeanExporter - Unregistering JMX-exposed beans on shutdown
2019-05-29 22:00:23,559 INFO o.s.j.e.a.AnnotationMBeanExporter - Unregistering JMX-exposed beans
2019-05-29 22:00:23,659 INFO o.s.s.c.ThreadPoolTaskScheduler - Shutting down ExecutorService 'taskScheduler'

**Comment by dwij2812** [comment]
@Sbrenthughes @rvema facing the same issue as mentioned by @ajayakumar-jayaraj when using sonar.username and sonar.password On Sonar Version 6.7.5, could you please check and provide a solution for the same

**Comment by rvema** [comment]
@Courtneyp123 can you help @dwij2812 on this issue?

**Comment by dwij2812** [comment]
@rvema the issue is solved, we need to change ```sonar,username``` to ```sonar.usernames``` and ```sonar.password``` to ```sonar.passwords``` in the ```application.properties``` file to make it work

**Comment by rvema** [comment]
Thanks for letting us know. @Courtneyp123 please check if the sonar collector documentation is accurate and update it accordingly

**Comment by dwij2812** [comment]
#3233

**Comment by ShachiRai1** [comment]
My sonar collector is working fine using username/password but I am getting error while I am giving only API token. Has anyone used it successfully ?
