### ISSUE TITLE
Maven Build Failure for SonarQUbe

### ISSUE THREAD

**Issue by trinathtiru** [capitalone/Hygieia#2232]
Please find the mvn build failure for the mvn install
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.911 s
[INFO] Finished at: 2018-05-23T09:42:11+00:00
[INFO] Final Memory: 16M/38M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sonar-codequality-collector: Could not resolve dependencies for project com.capitalone.dashboard:sonar-codequality-collector:jar:2.0.5-SNAPSHOT: Could not find artifact com.capitalone.dashboard:core:jar:2.0.5-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

@cradules @nireeshT Need help

**Comment by Sbrenthughes** [comment]
did you build the core module first?

**Comment by nireeshT** [comment]
@trinathtiru  do mvn clean install on /Hygieia

**Comment by matthewbeasley** [comment]
@trinathtiru - due to your silence, we're going to assume this resolved your issue.
