### ISSUE TITLE
API connectivity from UI - Whitelabel Error Page

### ISSUE THREAD

**Issue by SYN-jasicanagpal** [capitalone/Hygieia#2235]
Not able to connect to API from UI

on trying to hit http://localhost:8080/api/ping getting below error message :
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.
Wed May 23 23:43:56 CDT 2018
There was an unexpected error (type=Not Found, status=404).
No message available
![image](https://user-images.githubusercontent.com/2638266/40465038-419b35e8-5ee4-11e8-97cc-e65b242f558f.png)

Mongo DB is running and API is also running successfully.

**Comment by SYN-jasicanagpal** [comment]
I was able to solve it..

**Comment by Sbrenthughes** [comment]
Next time please close the issue.

**Comment by SYN-jasicanagpal** [comment]
In the recent git download the dashboard.properties is renames as application.properties but the help still says dashboard.properties. Renamed and repeated all the steps, it was successful.
