### ISSUE TITLE
Hygieia UI - Not getting username and password text box on screen and api connectivity failing

### ISSUE THREAD

**Issue by SYN-jasicanagpal** [capitalone/Hygieia#2236]
Hi,

I have successfully build the project, started mongo db, tomcat for api and UI. 

But on the UI on clicking on login button I don't see username and password textbox and api coonectivity shows Red.

**Comment by Sbrenthughes** [comment]
Open the UI in chrome incognito mode. Also, paste the error you get in the logs from the api

**Comment by matthewbeasley** [comment]
@SYN-jasicanagpal is this a duplicate of https://github.com/capitalone/Hygieia/issues/2235?

**Comment by SYN-jasicanagpal** [comment]
Thanks, the issue is solved now.
