### ISSUE TITLE
Hardcoded values for Sprint and Epic ID - Jira Feature Collector

### ISSUE THREAD

**Issue by softwareklinic** [capitalone/Hygieia#224]
StoryDataClientImpl.java

JSONArray sprint = (JSONArray) fields.get("customfield_10007");
String epicKey = TOOLS.sanitizeResponse(fields.get("customfield_10400"));

This values are different for different users of Jira and installations.. e.g. i have 10004, and 10006 respectively... some users have 10005 and 10006...

Can you please check?

Sanjay - thank you for pointing this out...

**Comment by amp5208** [comment]
This is correct and I am pushing this as a fix in the most recent pull request regarding Jira, which can be found here:  https://github.com/capitalone/Hygieia/pull/253.  I apologize for the inconvenience, and these values, as well as the Jira IssueType for "user story" will be configurable in the properties files.

**Comment by amp5208** [comment]
Fix is ready - pending merge of the above-noted pull request before closing this issue.  Once merged, please pull from master and use any new property file settings noted in the Feature content read-me's.

**Comment by amp5208** [comment]
This issue has been fixed.  @tabladrum or @amitmawkin , Please feel free to close this issue.

**Comment by oshingc** [comment]
I see the merge but the issue still open.

**Comment by amp5208** [comment]
Master should now have the ability to explicitly specify your Jira instance's custom values for the following fields:

<pre>
. . .
# In Jira, general IssueType IDs are associated to various "issue"
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a numerical ID reference to your instance's IssueType for
# the lowest level of Issues (e.g., "user story") specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType ID
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
feature.jiraIssueTypeId=7
# In Jira, your instance will have its own custom field created for "sprint" or "timebox" details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name <em>com.atlassian.greenhopper.service.sprint.Sprint</em>;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraSprintDataFieldName=customfield_10007
# In Jira, your instance will have its own custom field created for "super story" or "epic" back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (e.g., epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraEpicIdFieldName=customfield_10400
. . .
</pre>

This is noted in detail in the updated JiraFeatureCollector readme, as well as the sample property file within that source.  Please let me know if you are still seeing issues after updated your property files and rebuilding/redeploying with the new code.

**Comment by amp5208** [comment]
@tabladrum , if @oshingc confirms, this issue can be closed, as a previous merge resolved this issue.
