### ISSUE TITLE
Using deprecated sonar /api/resource

### ISSUE THREAD

**Issue by bbrower** [capitalone/Hygieia#2242]
As of Sonar 6.2 the /api/resource sonar qube is removed. There's various limits on this (500 projects fetch etc.) in previous versions (could only test with 5.6.7).

Proper channel would be to fetch via /api/projects.
See my example PR. It's a simple fix, but didn't go to far in modifying existing logic.

**Comment by nireeshT** [comment]
@bbrower  update to latest code base, issue fixed.
