### ISSUE TITLE
Demo Dashboard is Empty

### ISSUE THREAD

**Issue by Phoenix9032** [capitalone/Hygieia#2244]
Hi All ,

I have started my mongodb and able to collect data from Jenkins, github and jira . 

Now for a demo purpose I want to switch to demo dashboard and showcase the sample dashboards and I am getting them as empty . Can you please let me know , how to see data in demo dashboard ?

I am just doing gulp serve --local true

**Comment by Phoenix9032** [comment]
Hi all ..anyone faced similar issue or have any pointers ?

**Comment by Phoenix9032** [comment]
Hi All .. any idea .. need it for demo of the product ..

**Comment by Phoenix9032** [comment]
Dear Subodhbattina ..Yes I am able to do that for the real data ,no issues in that .
However it will take some time to make it fully functional . 

Hence in the mean time I wanted to use the demo dashboard option to show a product demo to my senior management to show the capability of the tool .
I have switched off all real connectors and just started the UI by gulp serve --local true 
The demo dashboard list shows but with empty data inside .What else I am supposed to do to see the data for TETRIS etc which is default.

**Comment by nireeshT** [comment]
@Phoenix9032  local test data is out-dated. I recommend configure widgets and work with own data.

**Comment by ykfq** [comment]
You can run an mongodb instance at another port except 27017 and change the propertes file , then you'll have a fresh new Dashboard and do whatever as you like.

**Comment by subodhbattina** [comment]
@Phoenix9032 : Assuming this issue is resolved at your end. Closing it out.
