### ISSUE TITLE
Doc Bug: Build Failure on UI goal w/ Maven 3.0.5

### ISSUE THREAD

**Issue by darkn3rd** [capitalone/Hygieia#2245]
## Summary

Build failure due to module not compatible with system Maven.  The documentation does not specify any version of Maven so I used the default.  Might want to make this clear in the docs, little to nothing on requirements.

## Configuration

* Ubuntu 14.04 Trusty Tahr (clean)
* Java 1.8.0_171-b11

## Steps

1. Install Oracle Java 1.8.0
2. Install Maven - `apt-get install maven`
3. cd /path/to/hygieia
4. `mvn clean install package`

## Expected Results

As per instructions, expected it to not error: http://capitalone.github.io/Hygieia/setup.html

If a particular version of Java and/or Maven are required, then expected this would be documented in setup.

## Actual Results

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21:48.570s
[INFO] Finished at: Mon May 28 00:55:05 UTC 2018
[INFO] Final Memory: 121M/241M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.29:install-node-and-npm (install node and npm) on project UI: The plugin com.github.eirslett:frontend-maven-plugin:0.0.29 requires Maven version 3.1.0 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginIncompatibleException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :UI
```

**Comment by Megha849** [comment]
@darkn3rd The document has been updated with the Maven version. Refer [#2250](https://github.com/capitalone/Hygieia/pull/2250).
