### ISSUE TITLE
Jenkis Build Collector with ldap user and token fails

### ISSUE THREAD

**Issue by xhostAB** [capitalone/Hygieia#2247]
Hi,
We have ldap authentication active on our Jenkins install (not using Jenkins local user db).
I'm trying to configure the jenkins build collector but it always fails with:

```
2018-05-28 10:30:00,225 INFO  c.c.d.collector.CollectorTask - Error getting jobs for: http://our.jenkins.server.tld:8080/ 0s
2018-05-28 10:30:00,228 ERROR c.c.d.collector.DefaultHudsonClient - client exception loading jobs
org.springframework.web.client.HttpClientErrorException: 401 Invalid password/token for user: myuser
```

Though, I can see all jobs when configuring the build widget.

The application.properties file:

```
dbname=dashboarddb
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017,127.0.0.1:27017,ip-10-100-9-120:27017
dbusername=dbuser
dbpassword=password
jenkins.cron=0 0/5 * * * *
jenkins.pageSize=1000
jenkins.folderDepth=10
jenkins.servers[0]=http://our.jenkins.server.tld:8080/
jenkins.usernames[0]=myuser
jenkins.apiKeys[0]=b344df0bfd19352f2a2cf4046eaa1745
jenkins.saveLog=false
jenkins.searchFields[0]= options.jobName
jenkins.searchFields[1]= niceName
```

Is it not possible to use an ldap accout with a token?

Thank you
Tomas

**Comment by nireeshT** [comment]
@xhostAB can you try this way 
jenkins.servers[0]=http://myuser:b344df0bfd19352f2a2cf4046eaa1745@our.jenkins.server.tld:8080/

remove 
jenkins.usernames[0]=myuser
jenkins.apiKeys[0]=b344df0bfd19352f2a2cf4046eaa1745

**Comment by Sbrenthughes** [comment]
We are working to move away from properties files as much as possible. Hopefully, in the near future, Hygieia would only need to know the db credentials via properties file or some other method. The rest of the properties would be stored in the database.
