### ISSUE TITLE
The deploy order published by Hygieia-Jenkins Plugin doesn't right

### ISSUE THREAD

**Issue by ykfq** [capitalone/Hygieia#2255]
I'm facing with a problem: 
  We had used the jenkins pipeline job to deploy our apps for a while, and these days I was trying to add the 
snippets generated by `Hygieia-Jenkins Plugin` to the pipeline code, and I was able to pubilsh the deploy steps to Hygieia Dashboard, however, the dashboard was red, and the deploy order wasn't right ether, see below:
 - jenkins pipeline steps
  ![image](https://user-images.githubusercontent.com/20741596/40772554-dccc9e62-64f2-11e8-8c05-cb180ef86c15.png)

- Hygieia dashboard widget
  ![image](https://user-images.githubusercontent.com/20741596/40772616-0acabfba-64f3-11e8-8e0a-3f3e4fac3e59.png)

Please help.

And there is an other question, as it is described here [Hygieia-Jenkins Plugin](https://capitalone.github.io/Hygieia/hygieia-jenkins-plugin.html), the `mvn clean package` will generate to files: `hygieia-publisher.hpi` and `hygieia-publisher.jar`, so, what's the use of `hygieia-publisher.jar`?  Or should it be used and how can I use it ?

Best regards & thanks a lot.

**Comment by ykfq** [comment]
I hava figure out why the widget is red.
The `hygieiaDeployPublishStep: Hygieia Deployment Publish Step` has many build status, when the deployment is success, we should publish `Success` from jenkins pipeline to hygieia.  
![image](https://user-images.githubusercontent.com/20741596/40779475-ba5c354e-6507-11e8-87be-04543aefc429.png)

**Comment by Sbrenthughes** [comment]
It would probably be nice to have some sort of order there.  I am going to close the issue since you seem to have it resolved.
