### ISSUE TITLE
Problems build api-audit with some jvms 

### ISSUE THREAD

**Issue by stevegal** [capitalone/Hygieia#2265]
Using Java 1.8 on a Mac, I cannot build api-audit. The model package contains a
‘’’
    public Map<AuditType, Evaluator> evaluatorMap() {
        return Collections.unmodifiableMap(Stream.of(
                new SimpleEntry<>(AuditType.CODE_REVIEW, codeReviewEvaluator),
                new SimpleEntry<>(AuditType.CODE_QUALITY, codeQualityEvaluator),
                new SimpleEntry<>(AuditType.STATIC_SECURITY_ANALYSIS, staticSecurityAnalysisEvaluator),
                new SimpleEntry<>(AuditType.LIBRARY_POLICY, libraryPolicyEvaluator),
                new SimpleEntry<>(AuditType.BUILD_REVIEW, buildEvaluator),
                new SimpleEntry<>(AuditType.TEST_RESULT, regressionTestResultEvaluator),
                new SimpleEntry<>(AuditType.PERF_TEST, performanceTestResultEvaluator))
                .collect(Collectors.toMap(SimpleEntry::getKey, SimpleEntry::getValue)));
    }’’’
That is causing a generics issue. If you use a more simple map, it build fine.

**Comment by matthewbeasley** [comment]
@stevegal - which map have you tried?

**Comment by stevegal** [comment]
I've fone a PR (https://github.com/capitalone/Hygieia/pull/2266) with the type 1 fix

**Comment by Sbrenthughes** [comment]
Closing this as you resolved the issue and created a pr
