### ISSUE TITLE
Sonar Collector not fetching data

### ISSUE THREAD

**Issue by NeomiS1993** [capitalone/Hygieia#2274]
I have tried to run the sonar collector jar . But am not getting any data from sonar ,getting 404 error. I am using sonar of version 6.7.1 . I  doubt whether the rest api url for sonar 6.7.1 is different or else does Hygieia sonar collector supports sonar of version 6.7.1 ?. Below is the error and the property file details i have used. Please help me to resolve the issue

**************************************************************************************************************
2018-06-08 09:30:00,012 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-06-08 09:30:00,024 ERROR c.c.d.collector.DefaultSonarClient - org.springframework.web.client.HttpClientErrorException: 404
2018-06-08 09:30:00,024 INFO  c.c.d.collector.CollectorTask - Fetched projects   0          0s
2018-06-08 09:30:00,024 INFO  c.c.d.collector.CollectorTask - New projects         0         0s
2018-06-08 09:30:00,026 INFO  c.c.d.collector.CollectorTask - Updated                 0        0s
2018-06-08 09:30:00,026 INFO  c.c.d.collector.CollectorTask - Finished                            0s
2018-06-08 09:31:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Sonar
2018-06-08 09:31:00,005 INFO  c.c.d.collector.CollectorTask - ### -------
**************************************************************************************************************

#Property File
dbname=dashboarddb

#Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
# dbreplicaset=[false if you are not using MongoDB replicaset]
dbreplicaset=false
dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=xxxxxxxx

# Database Password - default is blank
dbpassword=xxxxxxxx

sonar.username=xxxxx
sonar.passsword=xxxxx

# Collector schedule (required)
sonar.cron=0 0/1 * * * *

# Sonar server(s) (required) - Can provide multiple
sonar.servers[0]=http://xx.xx.xxx.xxx:9000

# Sonar version, match array index to the server. If not set, will default to version prior to 6.3.
sonar.versions[0]=6.7.1

# Sonar Metrics - Required.
# For Sonar version 6.3 and above
sonar.metrics=ncloc,violations,new_vulnerabilities,critical_violations,major_violations,blocker_violations,tests,test_success_density,test_errors,test_failures,coverage,line_coverage,sqale_index,alert_status,quality_gate_details

**Comment by nireeshT** [comment]
@NeomiS1993  use property key - sonar.metrics[0] instead

**Comment by NeomiS1993** [comment]
Thank you Nireesh . I was working with Hygieia-2.0.4 release version, in this version metrics is taken as String. In Hygieia master branch i can see latest commits where metrics is taken as List<String>. But while taking the SonarCollectorTask.java from Hygieia master branch it is showing error following class files are missing. I think com.cpaitlaone.dashboard.model for sonar collector is not updated. How can i get the updated one.
import com.capitalone.dashboard.model.CodeQuality;
import com.capitalone.dashboard.model.CollectorItemConfigHistory;
import com.capitalone.dashboard.model.CollectorItem;
import com.capitalone.dashboard.model.CollectorType;
import com.capitalone.dashboard.model.ConfigHistOperationType

**Comment by NeomiS1993** [comment]
@nireeshT Thanks it worked. I was working on Hygieia-2.0.4 release, in this version metrics field is a String. I have seen the new updates in Hygieia master , metrics is now List<String> and updations for sonar versions more than 6.x . I have updated with new code  and changed the property file , sonar.metrics to sonar.metrics[0]. Now its working fine.
