### ISSUE TITLE
gulp issue + api issue

### ISSUE THREAD

**Issue by itaimalek** [capitalone/Hygieia#2276]
Hi,
I installed with `mvn clean install package` , Build was successful with non-root user.
two issues I've encountered:
1. my api.properties file looks like:
```
server.contextPath=/api
server.port=8080
```
I successfully brought up the server with:
`java -jar ./api.jar --spring.config.name=api  --spring.config.location=./api.properties -Djasypt.encryptor.password=somesecret` 

from `api/target/`  directory.

but i get on `http://localhost:8080/api` the following:

> Whitelabel Error Page
> This application has no explicit mapping for /error, so you are seeing this as a fallback.
> Sun Jun 10 21:10:12 UTC 2018
> There was an unexpected error (type=Not Found, status=404).
> No message available
> 

don't get what went wrong here....

2. trying `gulp serve` from `UI` dir get me:
`-bash: gulp: command not found`

Although Build was successful here too:

> `[INFO] Scanning for projects...
> [INFO]
> [INFO] ------------------------------------------------------------------------
> [INFO] Building com.capitalone.dashboard:UI 2.0.5-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [INFO]
> [INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ UI ---
> [INFO] Deleting /home/galacoraldevops/Hygieia/UI/target
> [INFO]
> [INFO] >>> maven-pmd-plugin:3.6:check (default) > :pmd @ UI >>>
> [INFO]
> [INFO] --- maven-pmd-plugin:3.6:pmd (pmd) @ UI ---
> [INFO]
> [INFO] <<< maven-pmd-plugin:3.6:check (default) < :pmd @ UI <<<
> [INFO]
> [INFO] --- maven-pmd-plugin:3.6:check (default) @ UI ---
> [INFO]
> [INFO] --- jacoco-maven-plugin:0.7.6.201602180812:prepare-agent (default) @ UI ---
> [INFO] argLine set to -javaagent:/home/galacoraldevops/.m2/repository/org/jacoco/org.jacoco.agent/0.7.6.201602180812/org.jacoco.agent-0.7.6.201602180812-runtime.jar=destfile=/home/galacoraldevops/Hygieia/UI/target/jacoco.exec
> [INFO]
> [INFO] --- frontend-maven-plugin:0.0.29:install-node-and-npm (install node and npm) @ UI ---
> [INFO] Found proxies: []
> [INFO] Node v6.9.1 is already installed.
> [INFO] NPM 5.0.1 is already installed.
> [INFO]
> [INFO] --- frontend-maven-plugin:0.0.29:npm (npm install) @ UI ---
> [INFO] Found proxies: []
> [INFO] Running 'npm install --ignore-scripts' in /home/galacoraldevops/Hygieia/UI
> [INFO] up to date in 6.019s
> [INFO]
> [INFO] --- frontend-maven-plugin:0.0.29:bower (bower install) @ UI ---
> [INFO] Found proxies: []
> [INFO] Running 'bower install' in /home/galacoraldevops/Hygieia/UI
> [INFO]
> [INFO] --- frontend-maven-plugin:0.0.29:gulp (gulp build) @ UI ---
> [INFO] Running 'gulp.js build' in /home/galacoraldevops/Hygieia/UI
> [INFO] [21:21:50] Using gulpfile ~/Hygieia/UI/gulpfile.js
> [INFO] [21:21:50] Starting 'build'...
> [INFO] [21:21:50] Starting 'clean'...
> [INFO] [21:21:50] Finished 'clean' after 69 ms
> [INFO] [21:21:50] Starting 'assets'...
> [INFO] [21:21:50] Starting 'themes'...
> [INFO] [21:21:50] Starting 'fonts'...
> [INFO] [21:21:50] Starting 'js'...
> [INFO] [21:21:50] Starting 'views'...
> [INFO] [21:21:50] Starting 'test-data'...
> [INFO] [21:21:59] Finished 'assets' after 8.79 s
> [INFO] [21:21:59] Finished 'themes' after 8.79 s
> [INFO] [21:21:59] Finished 'test-data' after 8.84 s
> [INFO] [21:21:59] Finished 'views' after 8.98 s
> [INFO] [21:22:00] Finished 'js' after 9.09 s
> [INFO] [21:22:00] Finished 'fonts' after 9.57 s
> [INFO] [21:22:00] Starting 'html'...
> [INFO] [21:22:00] gulp-inject 1 files into index.html.
> [INFO] [21:22:00] gulp-inject 155 files into index.html.
> [INFO] [21:22:00] Finished 'html' after 209 ms
> [INFO] [21:22:00] Finished 'build' after 9.88 s
> [INFO]
> [INFO] --- maven-assembly-plugin:2.6:single (create-archive) @ UI ---
> [INFO] Building tar: /home/galacoraldevops/Hygieia/UI/target/UI-2.0.5-SNAPSHOT-src.tar.gz
> [INFO]
> [INFO] --- jacoco-maven-plugin:0.7.6.201602180812:report (report) @ UI ---
> [INFO] Skipping JaCoCo execution due to missing execution data file:/home/galacoraldevops/Hygieia/UI/target/jacoco.exec
> [INFO]
> [INFO] --- maven-install-plugin:2.5.2:install (default-install) @ UI ---
> [INFO] Installing /home/galacoraldevops/Hygieia/UI/pom.xml to /home/galacoraldevops/.m2/repository/com/capitalone/dashboard/UI/2.0.5-SNAPSHOT/UI-2.0.5-SNAPSHOT.pom
> [INFO] Installing /home/galacoraldevops/Hygieia/UI/target/UI-2.0.5-SNAPSHOT-src.tar.gz to /home/galacoraldevops/.m2/repository/com/capitalone/dashboard/UI/2.0.5-SNAPSHOT/UI-2.0.5-SNAPSHOT-src.tar.gz
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 22.245 s
> [INFO] Finished at: 2018-06-10T21:22:02+00:00
> [INFO] Final Memory: 28M/255M
> [INFO] ------------------------------------------------------------------------`

OS is : Centos7

any help is appreciated :)

**Comment by itaimalek** [comment]
Tried now on Ubuntu 16.04 - same results

**Comment by nireeshT** [comment]
@itaimalek try http://localhost:8080/api/ping 
Check if UI build is successful, that will get all node_module (gulp included). Go to UI folder and verify UI/node_modules has gulp dependencies.
run gulp -v

**Comment by itaimalek** [comment]
Build is successful on UI folder, but still error on `gulp` or `gulp -v`
for that matter.
Also npm or node doesn't work either, as a workaround I added their paths
to $PATH variable and I installed gulp with `npm install -g gulp` after
thatbI was able to do `gulp serve`
For api also build is successful http://localhost:8080/api/ping shows true.
But still I get that 404 message on
http://localhost:8080/ap <http://localhost:8080/api/ping>i

**Comment by itaimalek** [comment]
?

**Comment by Sbrenthughes** [comment]
If ` http://localhost:8080/api/ping` returns true, then you are good. I don't know what you expect from `http://localhost:8080/api`.

If you got the UI to run locally and you have the  ` http://localhost:8080/api/ping`. navigate to the UI login and see if you see a green checkmark or a red X

**Comment by Sbrenthughes** [comment]
Please follow the documentation link in my last post.
