### ISSUE TITLE
Hygiea installation in Ubuntu  : NPM Error

### ISSUE THREAD

**Issue by Phoenix9032** [capitalone/Hygieia#2278]
Hi All ,

I have installed git, Java 1.8 and Maven  and trying to install Hygieia in Ubuntu 16 .  

I am stuck with some error in npm and UI build is not success . I dont find any documentation for Ubuntu installation of Hygiea without docker ? Is it compatible?
What shall I do next ?

[INFO] Reactor Summary:
[INFO]
[INFO] com.capitalone.dashboard:Hygieia ................... SUCCESS [ 17.760 s]
[INFO] com.capitalone.dashboard:core ...................... SUCCESS [01:45 min]
[INFO] com.capitalone.dashboard:api ....................... SUCCESS [ 44.526 s]
[INFO] com.capitalone.dashboard:api-audit ................. SUCCESS [ 15.500 s]
[INFO] com.capitalone.dashboard:rally-collector ........... SUCCESS [  7.291 s]
[INFO] com.capitalone.dashboard:artifactory-artifact-collector SUCCESS [  5.189 s]
[INFO] com.capitalone.dashboard:bamboo-build-collector .... SUCCESS [  5.247 s]
[INFO] com.capitalone.dashboard:jenkins-build-collector ... SUCCESS [  6.256 s]
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SUCCESS [  4.840 s]
[INFO] com.capitalone.dashboard:jenkins-codequality ....... SUCCESS [  9.353 s]
[INFO] com.capitalone.dashboard:sonar-codequality-collector SUCCESS [  5.936 s]
[INFO] com.capitalone.dashboard:aws-cloud-collector ....... SUCCESS [  6.097 s]
[INFO] com.capitalone.dashboard:udeploy-deployment-collector SUCCESS [  5.640 s]
[INFO] com.capitalone.dashboard:xldeploy-deployment-collector SUCCESS [  4.633 s]
[INFO] com.capitalone.dashboard:jira-feature-collector .... SUCCESS [ 17.750 s]
[INFO] com.capitalone.dashboard:versionone-feature-collector SUCCESS [  6.875 s]
[INFO] com.capitalone.dashboard:gitlab-feature-collector .. SUCCESS [  6.874 s]
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SUCCESS [  1.245 s]
[INFO] com.capitalone.dashboard:appdynamics-performance-collector SUCCESS [  4.709 s]
[INFO] com.capitalone.dashboard:bitbucket-scm-collector ... SUCCESS [  5.449 s]
[INFO] com.capitalone.dashboard:github-scm-collector ...... SUCCESS [  5.193 s]
[INFO] com.capitalone.dashboard:github-graphql-scm-collector SUCCESS [  6.398 s]
[INFO] com.capitalone.dashboard:subversion-collector ...... SUCCESS [  4.848 s]
[INFO] com.capitalone.dashboard:gitlab-scm-collector ...... SUCCESS [  5.268 s]
[INFO] com.capitalone.dashboard:hpsm-cmdb-collector ....... SUCCESS [  5.223 s]
[INFO] com.capitalone.dashboard:nexus-iq-collector ........ SUCCESS [  4.390 s]
[INFO] com.capitalone.dashboard:score-collector ........... SUCCESS [  8.156 s]
[INFO] Hygieia Publisher Plugin ........................... SUCCESS [02:10 min]
[INFO] com.capitalone.dashboard:UI ........................ FAILURE [07:09 min]
[INFO] com.capitalone.dashboard:ui-tests .................. SKIPPED
[INFO] ------------------------------------------------------------------------

[INFO] Running 'npm install --ignore-scripts' in /home/ubuntu/Hygieia/UI
[ERROR] npm WARN deprecated jade@1.8.2: Jade has been renamed to pug, please install the latest version of pug instead of jade
[ERROR] npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[ERROR] npm WARN deprecated gulp-util@3.0.7: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[ERROR] npm WARN deprecated gulp-header@1.8.2: gulp-header 1.x is deprecated and will no longer be updated, please update to 2.x
[ERROR] npm WARN deprecated gulp-util@2.2.20: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[ERROR] npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated
[ERROR] npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[ERROR] npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[ERROR] npm WARN deprecated constantinople@3.0.2: Please update to at least constantinople 3.1.1
[ERROR] npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
[ERROR] npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[ERROR] npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
[ERROR] npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[ERROR] npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
[ERROR] npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
[ERROR] npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
[ERROR] npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
[ERROR] npm WARN notice [SECURITY] base64-url has the following vulnerability: 1 high. Go here for more details: https://nodesecurity.io/advisories?search=base64-url&version=1.2.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
[ERROR] npm WARN notice [SECURITY] request has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=request&version=2.67.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
[ERROR] npm WARN notice [SECURITY] uglify-js has the following vulnerability: 2 low. Go here for more details: https://nodesecurity.io/advisories?search=uglify-js&version=2.2.5 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
[ERROR] npm WARN notice [SECURITY] uglify-js has the following vulnerability: 2 low. Go here for more details: https://nodesecurity.io/advisories?search=uglify-js&version=2.4.15 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
[ERROR] npm WARN notice [SECURITY] concat-stream has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=concat-stream&version=1.5.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
[ERROR] npm WARN notice [SECURITY] request has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=request&version=2.36.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
[ERROR] npm WARN notice [SECURITY] request has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=request&version=2.40.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

**Comment by subodhbattina** [comment]
@Phoenix9032: 

Can you give these a shot, and see if it solves your issue.

1. Install NVM
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
2. Install node:
nvm install 8.9.1
3. And then do an "npm install" and see

**Comment by Phoenix9032** [comment]
Hey ..I did that ..and that resolved the issue ! 
But the two folders UI and UITESTS I did mvn clean package by specifically going inside that directory after installation .
Not sure what was the issue ? May be documentation need a little update ?

**Comment by subodhbattina** [comment]
@Phoenix9032: Glad the issue around "npm install" got resolved. 
Sorry, but I am not following your other questions around UI and UI-tests, can you please clarify?
Are you still having an issue?

**Comment by subodhbattina** [comment]
@Phoenix9032: Since we didn't hear back from you, assuming this is resolved and therefore closing the issue. Thanks.
