### ISSUE TITLE
Build Failure at gitlab-scm-collector

### ISSUE THREAD

**Issue by stangem** [capitalone/Hygieia#2280]
Hi!

So when I run "mvn clean install docker:build" It fails at Gitlab. I was having an issue before because I was trying to connect the gitlab collector to mongo but it was constantly giving me a "Mongo port not defined" even though it was defined in my docker-compose.override.yml So I tried rebuilding my collectors and this is what I am getting. 

Java version: "1.8.0_172"   

Reactor Summary:
[INFO] 
[INFO] com.capitalone.dashboard:Hygieia 2.0.5-SNAPSHOT .... SUCCESS [  2.828 s]
[INFO] com.capitalone.dashboard:core ...................... SUCCESS [ 42.813 s]
[INFO] com.capitalone.dashboard:api ....................... SUCCESS [ 34.863 s]
[INFO] com.capitalone.dashboard:api-audit ................. SUCCESS [ 18.981 s]
[INFO] com.capitalone.dashboard:artifactory-artifact-collector SUCCESS [ 11.467 s]
[INFO] com.capitalone.dashboard:bamboo-build-collector .... SUCCESS [ 12.415 s]
[INFO] com.capitalone.dashboard:jenkins-build-collector ... SUCCESS [ 12.375 s]
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SUCCESS [ 10.374 s]
[INFO] com.capitalone.dashboard:jenkins-codequality ....... SUCCESS [ 11.779 s]
[INFO] com.capitalone.dashboard:sonar-codequality-collector SUCCESS [ 10.218 s]
[INFO] com.capitalone.dashboard:aws-cloud-collector ....... SUCCESS [  1.435 s]
[INFO] com.capitalone.dashboard:udeploy-deployment-collector SUCCESS [ 10.201 s]
[INFO] com.capitalone.dashboard:xldeploy-deployment-collector SUCCESS [ 10.023 s]
[INFO] com.capitalone.dashboard:jira-feature-collector .... SUCCESS [ 16.223 s]
[INFO] com.capitalone.dashboard:versionone-feature-collector SUCCESS [ 11.772 s]
[INFO] com.capitalone.dashboard:gitlab-feature-collector .. SUCCESS [ 12.107 s]
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SUCCESS [  8.023 s]
[INFO] com.capitalone.dashboard:appdynamics-performance-collector SUCCESS [ 10.472 s]
[INFO] com.capitalone.dashboard:bitbucket-scm-collector ... SUCCESS [ 10.833 s]
[INFO] com.capitalone.dashboard:github-scm-collector ...... SUCCESS [  9.976 s]
[INFO] com.capitalone.dashboard:github-graphql-scm-collector SUCCESS [ 10.755 s]
[INFO] com.capitalone.dashboard:subversion-collector ...... SUCCESS [  8.024 s]
[INFO] com.capitalone.dashboard:gitlab-scm-collector ...... FAILURE [  0.836 s]
[INFO] com.capitalone.dashboard:hpsm-cmdb-collector ....... SKIPPED
[INFO] com.capitalone.dashboard:nexus-iq-collector ........ SKIPPED
[INFO] com.capitalone.dashboard:score-collector ........... SKIPPED
[INFO] Hygieia Publisher Plugin ........................... SKIPPED
[INFO] com.capitalone.dashboard:UI ........................ SKIPPED
[INFO] com.capitalone.dashboard:ui-tests 2.0.5-SNAPSHOT ... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:51 min
[INFO] Finished at: 2018-06-11T16:03:43-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:check (default) on project gitlab-scm-collector: You have 1 PMD violation. For more details see: /Users/stangem/dev/Hygieia-master/collectors/scm/gitlab/target/pmd.xml -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:check (default) on project gitlab-scm-collector: You have 1 PMD violation. For more details see: /Users/stangem/dev/Hygieia-master/collectors/scm/gitlab/target/pmd.xml
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: You have 1 PMD violation. For more details see: /Users/stangem/dev/Hygieia-master/collectors/scm/gitlab/target/pmd.xml
    at org.apache.maven.plugin.pmd.AbstractPmdViolationCheckMojo.executeCheck (AbstractPmdViolationCheckMojo.java:143)
    at org.apache.maven.plugin.pmd.PmdViolationCheckMojo.execute (PmdViolationCheckMojo.java:84)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]

**Comment by nireeshT** [comment]
@stangem update to latest code base and try. Check if you have any local code changes that triggered PMD violations under Gitlab-scm-collector/target/pmd.xml

**Comment by stangem** [comment]
@nireeshT Thank you for responding,
So I just re-cloned the master branch and tried rebuilding from the beginning and I'm still getting an error, Now when I run "mvn clean install docker:build" I get an error with Jenkins plugin.

Compilation failure: 
[ERROR] /Users/stangem/Hygieia-master/hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/workflow/HygieiaCodeQualityPublishStepExecutionTest.java:[60,42] cannot access jenkins.plugins.hygieia.workflow.HygieiaCodeQualityPublishStep.HygieiaCodeQualityPublisherStepExecution
[ERROR]   class file for jenkins.plugins.hygieia.workflow.HygieiaCodeQualityPublishStep$HygieiaCodeQualityPublisherStepExecution not found
[ERROR] /Users/stangem/Hygieia-master/hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/DefaultHygieiaServiceStub.java:[3,48] cannot find symbol
[ERROR]   symbol: class DefaultHygieiaService
[ERROR] /Users/stangem/Hygieia-master/hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/HygieiaPublisherStub.java:[3,43] cannot find symbol
[ERROR]   symbol: class HygieiaPublisher
[ERROR] /Users/stangem/Hygieia-master/hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/HygieiaPublisherStub.java:[5,33] cannot find symbol
[ERROR]   symbol:   class HygieiaBuild
[ERROR]   location: class jenkins.plugins.hygieia.HygieiaPublisherStub
[ERROR] /Users/stangem/Hygieia-master/hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/HygieiaPublisherStub.java:[5,57] cannot find symbol
[ERROR]   symbol:   class HygieiaTest
[ERROR]   location: class jenkins.plugins.hygieia.HygieiaPublisherStub
[ERROR] /Users/stangem/Hygieia-master/hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/HygieiaPublisherStub.java:[27,53] cannot find symbol
[ERROR]   symbol:   class HygieiaArtifact
[ERROR]   location: class jenkins.plugins.hygieia.HygieiaPublisherStub
[ERROR] /Users/stangem/Hygieia-master/hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/HygieiaPublisherStub.java:[5,113] cannot find symbol
[ERROR]   symbol:   class HygieiaSonar
[ERROR]   location: class jenkins.plugins.hygieia.HygieiaPublisherStub
[ERROR] /Users/stangem/Hygieia-master/hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/HygieiaPublisherStub.java:[5,137] cannot find symbol
[ERROR]   symbol:   class HygieiaDeploy
[ERROR]   location: class jenkins.plugins.hygieia.HygieiaPublisherStub
[ERROR] /Users/stangem/Hygieia-master/hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/HygieiaPublisherStub.java:[9,68] package HygieiaPublisher does not exist
[ERROR] /Users/stangem/Hygieia-master/hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/HygieiaPublisherStub.java:[11,17] cannot find symbol
[ERROR]   symbol:   class HygieiaService
[ERROR]   location: class jenkins.plugins.hygieia.HygieiaPublisherStub.DescriptorImplStub
[ERROR] /Users/stangem/Hygieia-master/hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/HygieiaPublisherStub.java:[18,16] cannot find symbol
[ERROR]   symbol:   class HygieiaService
[ERROR]   location: class jenkins.plugins.hygieia.HygieiaPublisherStub.DescriptorImplStub
[ERROR] /Users/stangem/Hygieia-master/hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/HygieiaPublisherStub.java:[22,39] cannot find symbol
[ERROR]   symbol:   class HygieiaService
[ERROR]   location: class jenkins.plugins.hygieia.HygieiaPublisherStub.DescriptorImplStub
[ERROR] /Users/stangem/Hygieia-master/hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/HygieiaPublisherStub.java:[33,50] cannot find symbol
[ERROR]   symbol:   class HygieiaBuild
[ERROR]   location: class jenkins.plugins.hygieia.HygieiaPublisherStub
[ERROR] /Users/stangem/Hygieia-master/hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/HygieiaPublisherStub.java:[39,49] cannot find symbol
[ERROR]   symbol:   class HygieiaTest
[ERROR]   location: class jenkins.plugins.hygieia.HygieiaPublisherStub
[ERROR] /Users/stangem/Hygieia-master/hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/workflow/HygieiaCodeQualityPublishStepExecutionTest.java:[13,31] cannot find symbol
[ERROR]   symbol:   class HygieiaPublisher
[ERROR]   location: package jenkins.plugins.hygieia
[ERROR] /Users/stangem/Hygieia-master/hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/workflow/HygieiaCodeQualityPublishStepExecutionTest.java:[14,31] cannot find symbol
[ERROR]   symbol:   class HygieiaResponse
[ERROR]   location: package jenkins.plugins.hygieia
[ERROR] /Users/stangem/Hygieia-master/hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/workflow/HygieiaCodeQualityPublishStepExecutionTest.java:[15,31] cannot find symbol
[ERROR]   symbol:   class HygieiaService
[ERROR]   location: package jenkins.plugins.hygieia
[ERROR] /Users/stangem/Hygieia-master/hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/workflow/HygieiaCodeQualityPublishStepExecutionTest.java:[42,13] cannot find symbol
[ERROR]   symbol:   class HygieiaCodeQualityPublishStep
[ERROR]   location: class jenkins.plugins.hygieia.workflow.HygieiaCodeQualityPublishStepExecutionTest
[ERROR] /Users/stangem/Hygieia-master/hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/workflow/HygieiaCodeQualityPublishStepExecutionTest.java:[56,13] cannot find symbol
[ERROR]   symbol:   class HygieiaService
[ERROR]   location: class jenkins.plugins.hygieia.workflow.HygieiaCodeQualityPublishStepExecutionTest
[ERROR] /Users/stangem/Hygieia-master/hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/HygieiaPublisherTest.java:[69,55] cannot find symbol
[ERROR]   symbol:   class HygieiaService
[ERROR]   location: class jenkins.plugins.hygieia.HygieiaPublisherTest
[ERROR] /Users/stangem/Hygieia-master/hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/HygieiaPublisherTest.java:[28,13] cannot find symbol
[ERROR]   symbol:   class HygieiaResponse
[ERROR]   location: class jenkins.plugins.hygieia.HygieiaPublisherTest
[ERROR] /Users/stangem/Hygieia-master/hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/HygieiaPublisherTest.java:[72,17] cannot find symbol
[ERROR]   symbol:   class HygieiaResponse
[ERROR]   location: class jenkins.plugins.hygieia.HygieiaPublisherTest.HygieiaServiceStub
[ERROR] /Users/stangem/Hygieia-master/hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/HygieiaPublisherTest.java:[79,16] cannot find symbol
[ERROR]   symbol:   class HygieiaResponse
[ERROR]   location: class jenkins.plugins.hygieia.HygieiaPublisherTest.HygieiaServiceStub
[ERROR] /Users/stangem/Hygieia-master/hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/HygieiaPublisherTest.java:[83,40] cannot find symbol
[ERROR]   symbol:   class HygieiaResponse
[ERROR]   location: class jenkins.plugins.hygieia.HygieiaPublisherTest.HygieiaServiceStub
[ERROR] /Users/stangem/Hygieia-master/hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/HygieiaPublisherTest.java:[87,16] cannot find symbol
[ERROR]   symbol:   class HygieiaResponse
[ERROR]   location: class jenkins.plugins.hygieia.HygieiaPublisherTest.HygieiaServiceStub
[ERROR] /Users/stangem/Hygieia-master/hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/HygieiaPublisherTest.java:[91,16] cannot find symbol
[ERROR]   symbol:   class HygieiaResponse
[ERROR]   location: class jenkins.plugins.hygieia.HygieiaPublisherTest.HygieiaServiceStub
[ERROR] /Users/stangem/Hygieia-master/hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/HygieiaPublisherTest.java:[99,16] cannot find symbol
[ERROR]   symbol:   class HygieiaResponse
[ERROR]   location: class jenkins.plugins.hygieia.HygieiaPublisherTest.HygieiaServiceStub
[ERROR] /Users/stangem/Hygieia-master/hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/HygieiaPublisherTest.java:[103,16] cannot find symbol
[ERROR]   symbol:   class HygieiaResponse
[ERROR]   location: class jenkins.plugins.hygieia.HygieiaPublisherTest.HygieiaServiceStub
[ERROR] /Users/stangem/Hygieia-master/hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/HygieiaPublisherTest.java:[107,16] cannot find symbol
[ERROR]   symbol:   class HygieiaResponse
[ERROR]   location: class jenkins.plugins.hygieia.HygieiaPublisherTest.HygieiaServiceStub

**Comment by matthewbeasley** [comment]
@stangem try just `mvn clean install` if that works then `docker-compose build`. If it doesn't work then please run `mvn clean install > out.txt` and post out.txt here so we can see full logs.
