### ISSUE TITLE
My own SCM Git Collector store on MongoDB, but doesn't show on UI

### ISSUE THREAD

**Issue by japm94** [capitalone/Hygieia#2281]
![screen shot 2018-06-12 at 02 23 22](https://user-images.githubusercontent.com/11621060/41271667-3409e81c-6de8-11e8-992d-931c9efe1621.png)

I've been tried discovery a solution, but no progress.

Please help me find a solution!

**Comment by Sbrenthughes** [comment]
We need to see logs from the github collector as well as your properties file.

**Comment by japm94** [comment]
![screen shot 2018-06-12 at 16 28 35](https://user-images.githubusercontent.com/11621060/41312543-b08f8750-6e5d-11e8-8450-1c2c8fe4dd5c.png)

The collector it is working fine.

application.properties
# Database Name
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# Database Password - default is blank
dbpassword=dbpassword

# Logging File location
logging.file=./logs/phabricator.log

# Collector schedule (required)
git.cron=0 * * * * *

# Mandatory parameters
git.host=pb-dc.alm-latam.accenture.com

#Phabricator API TOKEN
git.apiToken=xxxxxxxxxxxxxxxxxxxxxxxxxx

# Maximum number of days to go back in time when fetching commits
git.commitThresholdDays=15

# Page size for rest calls
# Only applicable to Bitbucket Server.
git.pageSize=25

**Comment by stevegal** [comment]
Not sure if it’s related, but I had a similar problem on the Jenkins code quality collector where I had to add 3 more things to the collector, instanceUrl, jobname and joburl ( not correct casing) see https://github.com/capitalone/Hygieia/blob/master/collectors/build/jenkins-codequality/src/main/java/com/capitalone/dashboard/collector/JenkinsCodeQualityCollector.java

You may not have this issue with your collector... but it’s worth a check

**Comment by Sbrenthughes** [comment]
Okay so you did get data. On the repo you are collecting from, with was the last commit?

**Comment by japm94** [comment]
I think so, when I execute `db.commits.find().pretty()` on mongo, returns the commits.

**Comment by nireeshT** [comment]
@japm94  Commits with in last 15 days ?

**Comment by japm94** [comment]
Yep

**Comment by japm94** [comment]
Guys, I solution the problem. Phabricator API return date in milliseconds, then I just multiplied by 1000. Thank you to who spent your time with me!
