### ISSUE TITLE
jira collector user permissions.

### ISSUE THREAD

**Issue by bimlendu** [capitalone/Hygieia#23]
What permissions are needed for the jira user.

I am trying to use a read-only kind of user but getting '403 Forbidden' error in the collector logs. 

Thanks.

**Comment by amp5208** [comment]
Thank you for reaching out.  A read-only user for Jira is enough to make the collector work, assuming that the user has enough access to see all projects.

However, a 403 Forbidden error would likely result from a malformed authentication structure.  For basic authentication, the syntax should be the following:  <em>username:password</em>, where the entire string, with the colon, is converted into 64-bit encoding.  Therefore, the auth string <em>username:password</em> would be converted into <strong>dXNlcm5hbWU6cGFzc3dvcmQ=</strong>, and added to the following property as thus:

<code>
feature.jiraCredentials=dXNlcm5hbWU6cGFzc3dvcmQ=
</code>

You can use a simple online tool to convert an auth string to 64-bit encoding, such as this one:  https://www.base64encode.org/

Please let me know if you have any questions or if you still have trouble authenticating.  You may also have to set your company's internal proxy, if Jira is hosted externally from your domain, which can be done in this format:

<code>
feature.jiraProxyUrl=http://proxy.com
</code>
<code>
feature.jiraProxyPort=9999
</code>

**Comment by amitmawkin** [comment]
Closing this issue as no response from issue creator since response was provided.
