### ISSUE TITLE
not able to run gulp serve command from UI module

### ISSUE THREAD

**Issue by irfanjs** [capitalone/Hygieia#2300]
Hello,
as per documentation, on UI module , we need to run the `gulp serve` command so that UI can be launched. but I am getting 

> command not found 

error. 
I have used `npm install --save gulp-install `
and the command was successful... 
can someone please suggest ... ? 

Regards

**Comment by nireeshT** [comment]
@irfanjs  please check if you have gulp installed in Hygieia/UI/node_modules

**Comment by Sbrenthughes** [comment]
https://github.com/capitalone/Hygieia/blob/gh-pages/pages/hygieia/UI/ui.md

> Step 3: Install Global Packages
> 
> Execute the following commands to install packages to the global node_modules directory:
> 
> npm install -g bower
> npm install -g gulp

**Comment by irfanjs** [comment]
thanks. 
i installed the gulp and now getting new error 

> [hygiea@Hygiea UI]$ gulp serve
> assert.js:269
>     throw err;
>     ^
> 
> AssertionError [ERR_ASSERTION]: Task function must be specified
>     at Gulp.set [as _setTask] (/home/hygiea/Hygieia/UI/node_modules/undertaker/lib/set-task.js:10:3)
>     at Gulp.task (/home/hygiea/Hygieia/UI/node_modules/undertaker/lib/task.js:13:8)
>     at Object.<anonymous> (/home/hygiea/Hygieia/UI/gulpfile.js:87:6)
>     at Module._compile (internal/modules/cjs/loader.js:702:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
>     at Module.load (internal/modules/cjs/loader.js:612:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:543:3)
>     at Module.require (internal/modules/cjs/loader.js:650:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at execute (/home/hygiea/node-v10.4.1-linux-x64/lib/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18)
>     at Liftoff.handleArguments (/home/hygiea/node-v10.4.1-linux-x64/lib/node_modules/gulp-cli/index.js:175:63)
>     at Liftoff.execute (/home/hygiea/node-v10.4.1-linux-x64/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:203:12)
>     at module.exports (/home/hygiea/node-v10.4.1-linux-x64/lib/node_modules/gulp-cli/node_modules/flagged-respawn/index.js:51:3)
>     at Liftoff.<anonymous> (/home/hygiea/node-v10.4.1-linux-x64/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:195:5)
>     at /home/hygiea/node-v10.4.1-linux-x64/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:165:9
> [hygiea@Hygiea UI]$
> 

> [hygiea@Hygiea UI]$ pwd
> /home/hygiea/Hygieia/UI
> [hygiea@Hygiea UI]$ ll
> total 288
> drwxr-xr-x.   2 hygiea hygiea     21 Jun 18 12:19 assembly
> drwxrwxr-x.  38 hygiea hygiea   4096 Jun 18 13:24 bower_components
> -rwxr-xr-x.   1 hygiea hygiea   1567 Jun 18 12:19 bower.json
> drwxrwxr-x.   8 hygiea hygiea    178 Jun 18 14:49 dist
> drwxr-xr-x.   2 hygiea hygiea     67 Jun 18 12:19 docker
> -rw-r--r--.   1 hygiea hygiea    289 Jun 18 12:19 Dockerfile
> drwxr-xr-x.   2 hygiea hygiea      6 Jun 18 12:19 etc
> -rwxr-xr-x.   1 hygiea hygiea   8627 Jun 18 12:19 gulpfile.js
> -rwxr-xr-x.   1 hygiea hygiea   2711 Jun 18 12:19 karma.conf.js
> drwxrwxr-x. 559 hygiea hygiea  16384 Jun 18 16:42 node_modules
> -rw-rw-r--.   1 hygiea hygiea    996 Jun 18 16:42 package.json
> -rw-rw-r--.   1 hygiea hygiea 215682 Jun 18 16:42 package-lock.json
> -rw-r--r--.   1 hygiea hygiea   4518 Jun 18 12:19 pom.xml
> -rw-r--r--.   1 hygiea hygiea    140 Jun 18 12:19 README.md
> drwxr-xr-x.   6 hygiea hygiea    119 Jun 18 12:19 src
> drwxrwxr-x.   3 hygiea hygiea     61 Jun 18 14:49 target
> drwxr-xr-x.   3 hygiea hygiea     45 Jun 18 12:19 test
> [hygiea@Hygiea UI]$
> 

is the issue in gulpfile.js file ? 
please suggest

**Comment by Sbrenthughes** [comment]
did you follow the next steps in the doc?

> **Install dependencies listed in package.json**
> npm install
> **Install dependencies listed in bower.json**
> bower install

**Comment by irfanjs** [comment]
thanks. 
i have following dependencies in package.json 

  "dependencies": {
    "browser-sync": "^2.24.4",
    "gulp-angular-templatecache": "^2.2.1",
    "gulp-change": "^1.0.0",
    "gulp-clean": "^0.4.0",
    "gulp-clean-css": "^3.9.4",
    "gulp-consolidate": "^0.2.0",
    "gulp-filter": "^5.1.0",
    "gulp-flatten": "^0.4.0",
    "gulp-htmlmin": "^4.0.0",
    "gulp-if": "^2.0.2",
    "gulp-inject": "^4.3.2",
    "gulp-install": "^1.1.0",
    "gulp-less": "^3.5.0",
    "gulp-order": "^1.1.1",
    "gulp-rename": "^1.3.0",
    "gulp-replace": "^1.0.0",
    "run-sequence": "^2.2.1",
    "wiredep": "^4.0.0"
  }

is there any command , i can install these dependencies in one go ?  OR i have to install one by one 
npm install browser-sync
and so on .. ?

**Comment by irfanjs** [comment]
again the same issue ... 

> [hygiea@Hygiea UI]$ npm install
> npm WARN ui@1.0.0 No repository field.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> audited 6027 packages in 6.198s
> found 10 vulnerabilities (5 low, 4 moderate, 1 high)
>   run `npm audit fix` to fix them, or `npm audit` for details
> [hygiea@Hygiea UI]$ npm update
> [hygiea@Hygiea UI]$ bower install
> [hygiea@Hygiea UI]$ gulp serve
> assert.js:269
>     throw err;
>     ^
> 
> AssertionError [ERR_ASSERTION]: Task function must be specified
>     at Gulp.set [as _setTask] (/home/hygiea/Hygieia/UI/node_modules/undertaker/lib/set-task.js:10:3)
>     at Gulp.task (/home/hygiea/Hygieia/UI/node_modules/undertaker/lib/task.js:13:8)
>     at Object.<anonymous> (/home/hygiea/Hygieia/UI/gulpfile.js:87:6)
>     at Module._compile (internal/modules/cjs/loader.js:702:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
>     at Module.load (internal/modules/cjs/loader.js:612:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:543:3)
>     at Module.require (internal/modules/cjs/loader.js:650:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at execute (/home/hygiea/node-v10.4.1-linux-x64/lib/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18)
>     at Liftoff.handleArguments (/home/hygiea/node-v10.4.1-linux-x64/lib/node_modules/gulp-cli/index.js:175:63)
>     at Liftoff.execute (/home/hygiea/node-v10.4.1-linux-x64/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:203:12)
>     at module.exports (/home/hygiea/node-v10.4.1-linux-x64/lib/node_modules/gulp-cli/node_modules/flagged-respawn/index.js:51:3)
>     at Liftoff.<anonymous> (/home/hygiea/node-v10.4.1-linux-x64/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:195:5)
>     at /home/hygiea/node-v10.4.1-linux-x64/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:165:9
> [hygiea@Hygiea UI]$
>

**Comment by irfanjs** [comment]
please suggest .. i am stuck

**Comment by Sbrenthughes** [comment]
what version of npm do you have

**Comment by irfanjs** [comment]
[hygiea@Hygiea UI]$ npm --version
6.1.0
[hygiea@Hygiea UI]$

**Comment by Sbrenthughes** [comment]
Can you come here. https://gitter.im/capitalone/Hygieia?source=all-rooms-list that way I can talk to you directly

**Comment by rvema** [comment]
@irfanjs What is the version of gulp? We should be using "gulp": "^3.9.1", we have seen issues with gulp 4 hence its recommended to use 3. https://github.com/gulpjs/undertaker/issues/54

**Comment by irfanjs** [comment]
I have referred the doc again. just ran the "mvn clean install " command in the Hygiea/UI folder and it was successful. 
I assume that , this maven command will install all the dependent binaries / libraries. ??
OR do I need to install gulp specifically using npm ?? though, it is not mentioned in the doc

**Comment by rvema** [comment]
@irfanjs mvn install automatically kicks off npm install check pom.xml

**Comment by irfanjs** [comment]
basically, I want to contribute to Hygiea project by means of code and documentation. I m building few connectors so might be someone interested...

**Comment by rvema** [comment]
@irfanjs Please go ahead :)

**Comment by irfanjs** [comment]
thanks :)
I filled up the form as individual contributor available from capitalOne and signed the agreement.
how can I modify the documentation now ?

**Comment by Sbrenthughes** [comment]
@Megha849

**Comment by irfanjs** [comment]
@Megha849 : can you please suggest ?

**Comment by sdevanayaka-auro** [comment]
1. Be sure that you have gulp and gulp.cmd (use windows search)
2. Copy the path of gulp.cmd (C:\Users\XXXX\AppData\Roaming\npm)
3. Add this path to the Path envirement variable or edit PATH environment variable and add %APPDATA%\npm

Reopen cmd.
Add %APPDATA%\npm to front of Path, not end of the Path.

Referece: https://stackoverflow.com/questions/24027551/gulp-command-not-found-error-after-installing-gulp
