### ISSUE TITLE
Hygieia collector for Selenium and CA Release Automation

### ISSUE THREAD

**Issue by vamshipriya** [capitalone/Hygieia#2303]
Hi Guys,

I'm looking for skeleton collector for Selenium and CA Release Automation. I need to display Selenium and CARA metrics on Hygieia dashboard.
Did any one custom designed a collector for both of them. If so can you please guide on how to build a collector for them.

Thanks.

**Comment by matthewbeasley** [comment]
@vamshipriya - @rvema answer should be what you need.
