### ISSUE TITLE
How to create collector for git server on Oracle Developer Cloud Service? 

### ISSUE THREAD

**Issue by yuhong02** [capitalone/Hygieia#2307]
There is no rest service expose for getting git server on Oracle Developer Cloud Service, only command line. In this case, how to create collector for git server on Oracle Developer Cloud Service?

**Comment by rvema** [comment]
@yuhong02 The github collector should work fine as long as there is connectivity between the collector instance and your git server on Oracle Developer cloud.

**Comment by matthewbeasley** [comment]
@yuhong02 - please follow @rvema suggestion. If it does not work for you please follow this guide http://capitalone.github.io/Hygieia/create_collector.html to create a custom collector.

**Comment by yuhong02** [comment]
thanks.
