### ISSUE TITLE
would like to join as contributor 

### ISSUE THREAD

**Issue by irfanjs** [capitalone/Hygieia#2309]
Hello,

Would like to join as contributor ... 
have signed the agreement as individual contributor. 
please let me know how to start contributing to code and documentation

@Megha849 : can you please take care of this ...?

Regards,

**Comment by Sbrenthughes** [comment]
If you want to contribute then just make PRs. I know @Megha849 with be pushing out documentation on how to create collectors, widgets etc, soon.

**Comment by irfanjs** [comment]
as of now, would like to contribute to documentations. i would like to modify the existing documentation page to reflect the correct installation steps. as a newbie, there are still certain confusion if someone reads the doc and follows the step by step instruction. 
as i am doing this first time, it is very valuable to really validate the current docs and update if any point is missing. i felt some points were missing so thinking to update docs.

regarding code, yes will create PRs

**Comment by matthewbeasley** [comment]
@irfanjs - as @Sbrenthughes mentioned, just submit a PR with the changes you want to make and we will have a conversation there.

**Comment by Megha849** [comment]
@irfanjs Refer to the [Contribution Guidelines](http://capitalone.github.io/Hygieia/create_collector.html) section in the documentation for information on contributing [new collectors](http://capitalone.github.io/Hygieia/create_collector.html), [widgets](http://capitalone.github.io/Hygieia/create_widget.html), and to the [documentation](http://capitalone.github.io/Hygieia/documentation.html).
