### ISSUE TITLE
Collector for pulling custom XML or HTML reports 

### ISSUE THREAD

**Issue by rajkumaradass** [capitalone/Hygieia#2318]
Is there any collector available for pulling custom XML or HTML test reports from a remote server(or jenkins) and display it to the hygieia dashboard.

Preferably if the XML format complies to certain format(like the one generated in JUnit). My requirement is to have get  custom XML test reports that are available in jenkins server(not as a cucumber report) to show it in hygieia dashboard. Currently one option for Junit test results is to upload them to SonarQube and get it. But some of my tests are not based on Junit and are created as custom XML format. How do i achieve it?

**Comment by matthewbeasley** [comment]
@rajkumaradass - no this does not exist currently. If you'd like to create this yourself here's a guide for how to do it: http://capitalone.github.io/Hygieia/create_collector.html

**Comment by prateekasthana** [comment]
Hi @rajkumaradass , Did you added this feature in Hygieia ?

**Comment by rajkumaradass** [comment]
@prateekasthana  - no.

**Comment by prateekasthana** [comment]
:( Ok . I was also looking for simile feature.
