### ISSUE TITLE
VersionOne Collector Issue - Pulling data on every call and duplicate the records into mongodb

### ISSUE THREAD

**Issue by aniketvsawant** [capitalone/Hygieia#232]
VersionOne collector is pulling data from version one everytime and every call. Because of which data duplicate and huge amount of data is getting inserted into the database. The correct behaviour should be to check for existing data. If data is already their into hygieia db then skip the insertion.
Please suggest. Does anyone facing this kind of issue. Any work around it ?

**Comment by hongluovz** [comment]
my jira collector also got duplicated projects/features in mongodb.

**Comment by gangadharahn** [comment]
Yes I am getting the same issue.Data mongo data is not updated in project list

**Comment by nireeshT** [comment]
@aniketvsawant  - which specific data from VersionOne is duplicated/inserted, is it at enterprise level (if you are seeing duplicated projects/teams ) or project-Feature level(if seeing duplicates in issues).

**Comment by tabladrum** [comment]
User the latest from master.
