### ISSUE TITLE
Functional Test results are not publishing properly from Jenkins plugin to Hygieia

### ISSUE THREAD

**Issue by venkateshmadala** [capitalone/Hygieia#2322]
Hi Team, I have integrated Jenkins with Hygieia with jenkins plugin. I am able to push the cucumber test results to Hygieia. The issue is I am able to see only 100% or 0% in UI i.e if all test cases are success then it is showing 100% in UI even 1 test case failure also it is showing 0%. I am not able to see any other results like 70%, 60% etc... can you please help me on this. 
![functionatest](https://user-images.githubusercontent.com/14547037/41963438-38c9d8e2-7a15-11e8-982f-12f4b40067d3.png)

 I observed in Hygieia UI we are not able to access Jenkins log i.e unable to click on Test job output.
![issue](https://user-images.githubusercontent.com/14547037/41963552-7a1d4bd0-7a15-11e8-9149-5063d60b9046.png)

**Comment by subodhbattina** [comment]
@venkateshmadala Do you see any logs messages at all from HygieiaPublisher? Are you using the CucumberTestBuilder?

**Comment by subodhbattina** [comment]
@venkateshmadala : Since we didn't hear back from you, assuming this issue is resolved at your end, and therefore closing this issue. Thanks
