### ISSUE TITLE
GitHub Blocked in the Organization any alternative

### ISSUE THREAD

**Issue by Phoenix9032** [capitalone/Hygieia#2323]

**Comment by Phoenix9032** [comment]
Hi ..my organization has a strict policy and has blocked GitHub .We have got one time permission to get the Hygieia software alone downloaded ..however the Bower and package json has tons of packages that needs to be installed from GitHub and looks like that's not an option ..is there a possibility to get the Hygieia installed and running in any alternate method ?

**Comment by matthewbeasley** [comment]
@Phoenix9032 - download and build Hygieia from outside your organizations network. Then move the completed artifacts. For the UI, tar up the dist folder. For the java application just move the jars. We currently don't have up-to-date build artifacts available.

**Comment by Phoenix9032** [comment]
That is really helpful suggestion ..thanks so much ..I will try and if some guidance need d might open up another thread
