### ISSUE TITLE
How to reduce API calls in Github collector

### ISSUE THREAD

**Issue by Booma-Baskaran** [capitalone/Hygieia#2324]
Hi,

We are running Github collector against Enterprise Github and we have a 5 mins cron. We have around 100 dashboards(repos) on bordered and it will be thousands of dashboards(repos) in the future. Enterprise Github reported that there are huge API calls due to collector. We would like to optimize the code. Appreciate your suggestions.

Thanks,
Booma Baskaran.

**Comment by rvema** [comment]
@Booma-Baskaran : We are working on a webhook (event push based) solution and will update you shortly. Currently work is in progress and we are working on solving the security issues around it. You should hear back in couple of weeks.

**Comment by Booma-Baskaran** [comment]
@rvema Thanks for the update.

**Comment by matthewbeasley** [comment]
@Booma-Baskaran - also make sure you are using the graphql version of the github collector

**Comment by Booma-Baskaran** [comment]
@matthewbeasley Thanks
