### ISSUE TITLE
Jira Api: How issues are linked to particular boards are fetched?

### ISSUE THREAD

**Issue by ArjunSreepad** [capitalone/Hygieia#2330]
Currently I have requirement to fetch all the issues related to particular board. Currently we have that option on Jira widget to select team & this field corresponds to "**jiraTeamFieldName**" field present in each issues
But my concern is what if a Jira issue is found on many boards, also I don't think mapping between board and issue is handled at issue end?
Thus please help me understand the structure if my understanding is wrong

**Comment by subodhbattina** [comment]
@ArjunSreepad : From the Jira Collector standpoint, when it pulls down issues, if the JSON response has the same issue listed "separately", mapped to two different teams, then it will get stored separately in the data base mapped out to the two different teams. The "feature" collection has a property called "sTeamID" thats maps the issue to a team.

**Comment by subodhbattina** [comment]
The way the collector stands as-of-now, it does not parse multiple team names on the response. It expects a single team name, which is what it maps the issue to.

**Comment by ArjunSreepad** [comment]
which field in the issue's response json holds the team details?

**Comment by subodhbattina** [comment]
@ArjunSreepad : Since we didn't hear back from you, assuming this issue is closed at your end. Closing this issue. Thanks
