### ISSUE TITLE
Jenkins build collector startup issue

### ISSUE THREAD

**Issue by fluidjeel** [capitalone/Hygieia#234]
The Jenkins build collector isnt starting and throwing Null Pointer exception, Attached is the error stack
[log.txt](https://github.com/capitalone/Hygieia/files/66012/log.txt)

Below is the app.props in text format

[application.txt](https://github.com/capitalone/Hygieia/files/66023/application.txt)

There is no authentication/authorization set.

I am using the latest 1.5.0 release

**Comment by tabladrum** [comment]
Stack trace indicating problem with cron string in the properties.

**Comment by fluidjeel** [comment]
@tabladrum - 

Is this incorrect? 

#Collector schedule (required)
jenkins.cron=0 0/1 * * * *

I have also tried with * * * * * *

**Comment by amitmawkin** [comment]
Looks like it is not finding the properties file whats your startup command?

**Comment by fluidjeel** [comment]
@amitmawkin , Thanks !! You were correct. I was passing application.properties instead of just the prefix
