### ISSUE TITLE
After running jira.jar file I was able to fetch data from Jira URL and populate it to mongodb.in mongodb under test and under feature all the stiories are there but while configuring jira feature widget I will get nothing in dropdown-plx help

### ISSUE THREAD

**Issue by kkkkk111** [capitalone/Hygieia#2344]

**Comment by subodhbattina** [comment]
@kkkkk111 : 
1. For the "Agile Content Tool Type"
Can you please run the below query against your mongoDB, and check if you have any collectors registered
```db.collectors.find({ "collectorType": "AgileTool" })```

2. For Project Names, please run the below query to check if you have any projects in the database:
```db.scope.find({"collectorId" : ObjectId({your collector id value})})```

3. For the Team Names, please run the below query to check if you have any teams in the database:
```db.team.find({"collectorId" : ObjectId({your collector id value})})```

**Comment by kkkkk111** [comment]
hi sir thanks a lot..
will you please help me for ldap configuration..for hygieia.
