### ISSUE TITLE
build failed with latest master branch

### ISSUE THREAD

**Issue by hongluovz** [capitalone/Hygieia#235]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /apps/opt/tools/hygieia/core/src/main/resources
[INFO] skip non existing resourceDirectory /apps/opt/tools/hygieia/core/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.0:compile (default-compile) @ core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 81 source files to /apps/opt/tools/hygieia/core/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /apps/opt/tools/hygieia/core/src/main/java/com/capitalone/dashboard/model/Component.java:[57,31] cannot find symbol
  symbol:   method replace(com.capitalone.dashboard.model.CollectorType,java.util.List<com.capitalone.dashboard.model.CollectorItem>)
  location: variable collectorItems of type java.util.Map<com.capitalone.dashboard.model.CollectorType,java.util.List<com.capitalone.dashboard.model.CollectorItem>>
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] com.capitalone.dashboard:Hygieia ................... SUCCESS [  0.883 s]
[INFO] com.capitalone.dashboard:core ...................... FAILURE [  7.283 s]
[INFO] com.capitalone.dashboard:api ....................... SKIPPED
[INFO] com.capitalone.dashboard:jenkins-build-collector ... SKIPPED
[INFO] com.capitalone.dashboard:sonar-codequality-collector SKIPPED
[INFO] com.capitalone.dashboard:subversion-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:github-scm-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:versionone-feature-collector SKIPPED
[INFO] com.capitalone.dashboard:udeploy-deployment-collector SKIPPED
[INFO] com.capitalone.dashboard:jira-feature-collector .... SKIPPED
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SKIPPED
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SKIPPED
[INFO] com.capitalone.dashboard:UI ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.554 s
[INFO] Finished at: 2015-12-17T18:53:39-05:00
[INFO] Final Memory: 35M/360M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.0:compile (default-compile) on project core: Compilation failure
[ERROR] /apps/opt/tools/hygieia/core/src/main/java/com/capitalone/dashboard/model/Component.java:[57,31] cannot find symbol
[ERROR] symbol:   method replace(com.capitalone.dashboard.model.CollectorType,java.util.List<com.capitalone.dashboard.model.CollectorItem>)
[ERROR] location: variable collectorItems of type java.util.Map<com.capitalone.dashboard.model.CollectorType,java.util.List<com.capitalone.dashboard.model.CollectorItem>>

**Comment by tabladrum** [comment]
Travis builds are passing - https://travis-ci.org/capitalone/Hygieia/builds 
Few questions: What's your java version? Did you see any maven dependency download error? If possible can you paste the top of the console log?

**Comment by hongluovz** [comment]
java -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

mvn clean install package
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 13 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] com.capitalone.dashboard:Hygieia
[INFO] com.capitalone.dashboard:core
[INFO] com.capitalone.dashboard:api
[INFO] com.capitalone.dashboard:jenkins-build-collector
[INFO] com.capitalone.dashboard:sonar-codequality-collector
[INFO] com.capitalone.dashboard:subversion-collector
[INFO] com.capitalone.dashboard:github-scm-collector
[INFO] com.capitalone.dashboard:versionone-feature-collector
[INFO] com.capitalone.dashboard:udeploy-deployment-collector
[INFO] com.capitalone.dashboard:jira-feature-collector
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector
[INFO] com.capitalone.dashboard:chat-ops-collector
[INFO] com.capitalone.dashboard:UI
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building com.capitalone.dashboard:Hygieia 1.5.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ Hygieia ---
[INFO]
[INFO] >>> maven-pmd-plugin:3.5:check (default) > :pmd @ Hygieia >>>
[INFO]
[INFO] --- maven-pmd-plugin:3.5:pmd (pmd) @ Hygieia ---
[INFO]
[INFO] <<< maven-pmd-plugin:3.5:check (default) < :pmd @ Hygieia <<<
[INFO]
[INFO] --- maven-pmd-plugin:3.5:check (default) @ Hygieia ---
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ Hygieia ---
[INFO] Installing /apps/opt/tools/Hygieia-master-latest/pom.xml to /apps/opt/home/oracle/.m2/repository/com/capitalone/dashboard/Hygieia/1.5.0-SNAPSHOT/Hygieia-1.5.0-SNAPSHOT.pom
[INFO]
[INFO] >>> maven-pmd-plugin:3.5:check (default) > :pmd @ Hygieia >>>
[INFO]
[INFO] --- maven-pmd-plugin:3.5:pmd (pmd) @ Hygieia ---
[INFO]
[INFO] <<< maven-pmd-plugin:3.5:check (default) < :pmd @ Hygieia <<<
[INFO]
[INFO] --- maven-pmd-plugin:3.5:check (default) @ Hygieia ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building com.capitalone.dashboard:core 1.5.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ core ---
[INFO]
[INFO] >>> maven-pmd-plugin:3.5:check (default) > :pmd @ core >>>
[INFO]
[INFO] --- maven-pmd-plugin:3.5:pmd (pmd) @ core ---
[WARNING] Unable to locate Source XRef to link to - DISABLED
[INFO]
[INFO] <<< maven-pmd-plugin:3.5:check (default) < :pmd @ core <<<
[INFO]
[INFO] --- maven-pmd-plugin:3.5:check (default) @ core ---
[INFO]
[INFO]
[INFO] --- apt-maven-plugin:1.1.3:process (default) @ core ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /apps/opt/tools/Hygieia-master-latest/core/src/main/resources
[INFO] skip non existing resourceDirectory /apps/opt/tools/Hygieia-master-latest/core/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.0:compile (default-compile) @ core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 81 source files to /apps/opt/tools/Hygieia-master-latest/core/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /apps/opt/tools/Hygieia-master-latest/core/src/main/java/com/capitalone/dashboard/model/Component.java:[57,31] cannot find symbol
  symbol:   method replace(com.capitalone.dashboard.model.CollectorType,java.util.List<com.capitalone.dashboard.model.CollectorItem>)
  location: variable collectorItems of type java.util.Map<com.capitalone.dashboard.model.CollectorType,java.util.List<com.capitalone.dashboard.model.CollectorItem>>
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] com.capitalone.dashboard:Hygieia ................... SUCCESS [  0.930 s]
[INFO] com.capitalone.dashboard:core ...................... FAILURE [  6.874 s]
[INFO] com.capitalone.dashboard:api ....................... SKIPPED
[INFO] com.capitalone.dashboard:jenkins-build-collector ... SKIPPED
[INFO] com.capitalone.dashboard:sonar-codequality-collector SKIPPED
[INFO] com.capitalone.dashboard:subversion-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:github-scm-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:versionone-feature-collector SKIPPED
[INFO] com.capitalone.dashboard:udeploy-deployment-collector SKIPPED
[INFO] com.capitalone.dashboard:jira-feature-collector .... SKIPPED
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SKIPPED
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SKIPPED
[INFO] com.capitalone.dashboard:UI ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.294 s
[INFO] Finished at: 2015-12-17T19:14:11-05:00
[INFO] Final Memory: 35M/360M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.0:compile (default-compile) on project core: Compilation failure
[ERROR] /apps/opt/tools/Hygieia-master-latest/core/src/main/java/com/capitalone/dashboard/model/Component.java:[57,31] cannot find symbol
[ERROR] symbol:   method replace(com.capitalone.dashboard.model.CollectorType,java.util.List<com.capitalone.dashboard.model.CollectorItem>)
[ERROR] location: variable collectorItems of type java.util.Map<com.capitalone.dashboard.model.CollectorType,java.util.List<com.capitalone.dashboard.model.CollectorItem>>
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :core

**Comment by amitmawkin** [comment]
Please make sure you have the latest fork or clone  of master...

**Comment by hongluovz** [comment]
I do have the latest master:
git remote show origin
* remote origin
  Fetch URL: https://github.com/capitalone/Hygieia
  Push  URL: https://github.com/capitalone/Hygieia
  HEAD branch: master
  Remote branches:
    AppDynamics    tracked
    cloud-changes  tracked
    gradle         tracked
    jdamick-gradle tracked
    local-test-fix tracked
    master         tracked
    readme-fixes   tracked
    sample-updates tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
[oracle@scsblnx-295720 Hygieia-master-latest]$ git pull
Already up-to-date.

**Comment by tabladrum** [comment]
Strange. I am thinking if you can delete your .m2/repository directory (keeping ay settings.xml) and do a mvn clean compile...

**Comment by tabladrum** [comment]
My bad... did I tell you we are using Java 7 or 8?

http://stackoverflow.com/questions/24290452/the-method-replacestring-arraylist-is-undefined-for-the-type-hashmap

**Comment by tabladrum** [comment]
Travis is building with Java 8.

**Comment by softwareklinic** [comment]
You need 1.8 on ur sandbox



Regards,
Keyur

On Dec 17, 2015, at 6:44 PM, hongluovz <notifications@github.com<mailto:notifications@github.com>> wrote:


I do have the latest master:
git remote show origin

 *   remote origin Fetch URL: https://github.com/capitalone/Hygieia Push URL: https://github.com/capitalone/Hygieia HEAD branch: master Remote branches: AppDynamics tracked cloud-changes tracked gradle tracked jdamick-gradle tracked local-test-fix tracked master tracked readme-fixes tracked sample-updates tracked Local branch configured for 'git pull': master merges with remote master Local ref configured for 'git push': master pushes to master (up to date) [oracle@scsblnx-295720 Hygieia-master-latest]$ git pull Already up-to-date.

**Comment by softwareklinic** [comment]
Its building successfully withJDK 8

But, still the stash collector seems - we need to build separately...

[INFO] 
[INFO] com.capitalone.dashboard:Hygieia ................... SUCCESS [  1.536 s]
[INFO] com.capitalone.dashboard:core ...................... SUCCESS [ 19.872 s]
[INFO] com.capitalone.dashboard:api ....................... SUCCESS [ 15.619 s]
[INFO] com.capitalone.dashboard:jenkins-build-collector ... SUCCESS [  4.561 s]
[INFO] com.capitalone.dashboard:sonar-codequality-collector SUCCESS [  1.944 s]
[INFO] com.capitalone.dashboard:subversion-collector ...... SUCCESS [  1.956 s]
[INFO] com.capitalone.dashboard:github-scm-collector ...... SUCCESS [  2.425 s]
[INFO] com.capitalone.dashboard:versionone-feature-collector SUCCESS [  4.269 s]
[INFO] com.capitalone.dashboard:udeploy-deployment-collector SUCCESS [  3.003 s]
[INFO] com.capitalone.dashboard:jira-feature-collector .... SUCCESS [  4.333 s]
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SUCCESS [  2.953 s]
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SUCCESS [  3.758 s]
[INFO] com.capitalone.dashboard:UI ........................ SUCCESS [05:16 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:24 min
[INFO] Finished at: 2015-12-17T22:01:50-06:00
[INFO] Final Memory: 148M/834M
[INFO] ------------------------------------------------------------------------
Keyurs-MacBook-Air:Hygieia FamilyMac$

**Comment by hongluovz** [comment]
switched to JDK 1.8 and it fixed the build issue. Thank you all.
