### ISSUE TITLE
not able to connect to bitbucket

### ISSUE THREAD

**Issue by monikanaagar** [capitalone/Hygieia#2350]
2018-07-11 16:59:51,680 ERROR c.c.d.rest.RestApiExceptionHandler - Failed to con
vert value of type [java.lang.String] to required type [org.bson.types.ObjectId]
; nested exception is org.springframework.core.convert.ConversionFailedException
: Failed to convert from type [java.lang.String] to type [@org.springframework.w
eb.bind.annotation.PathVariable org.bson.types.ObjectId] for value 'null'; neste
d exception is java.lang.IllegalArgumentException: invalid hexadecimal represent
ation of an ObjectId: [null]

can anyone please help suggest

**Comment by subodhbattina** [comment]
@monikanaagar: Can you please provide a little more context on what you are trying to do, and also please share the full log with enough detail if you could. Thanks

**Comment by subodhbattina** [comment]
@monikanaagar : Since we didn't hear back from you, assuming this issue is resolved at your end, closing the issue.
