### ISSUE TITLE
Some problems about UI'timeline

### ISSUE THREAD

**Issue by Piaoyzma** [capitalone/Hygieia#2352]
I have two questions, one about Chinese encoding (the log I submitted in gitlab is about Chinese, garbled when displayed in the UI), as shown in Figure 1;
 another problem, as shown in Figure 2, the time of code submission does not match the timeline shown in the UI, which is very confusing.

I checked the time of the system, the time of all the servers is synchronized, I don't know the cause of this problem, hope someone can know and help me.

![image](https://user-images.githubusercontent.com/29573171/42626025-d1bc21d0-85fb-11e8-9b0e-00ca46ff7cad.png)
![image](https://user-images.githubusercontent.com/29573171/42626351-ae4aef46-85fc-11e8-8482-be5747d46fdf.png)

In addition, the BUILD time of jenkins is not in line with the actual time, probably the same problem.

**Comment by subodhbattina** [comment]
@Piaoyzma : I just checked on a dashboard in our QA environment:
1. Went to the code repo widget, clicked on the commits to show the commits on the ui,
2. And then went to the repo url for the widget, and looked at the commits log, and the dates seem to align fine.

Could you please do the same, go to the repo url and cross check the commits dates again, and like wise for the your build jobs. Thanks.

**Comment by Piaoyzma** [comment]
@subodhbattina I will try again with another question, thank you for your answer.
