### ISSUE TITLE
Pipeline not showing data in hygieia dashboard

### ISSUE THREAD

**Issue by ham5768** [capitalone/Hygieia#2354]
Hi team,

I am using below configuration in jenkinsfile ( pipeline job) and i am not able to view any data in hygieia dashboard under the pipeline tab. Environment dropdown shows nothing!

stage ('hygieia'){
                steps {
				
                    hygieiaArtifactPublishStep artifactDirectory: 'D:/Jenkins/workspace/freestyle/' , artifactGroup: 'None', artifactName: '*.* ', artifactVersion: '1.0.0'
		    hygieiaDeployPublishStep applicationName: 'freestyle', artifactDirectory: 'D:/Jenkins/workspace/freestyle/', artifactGroup: 'None', artifactName: '*.*', artifactVersion: '1.0', buildStatus: 'InProgress', environmentName: 'test'
                      }
							}
                
}

Hygieia: Published Build Data For Deployment Publishing. Response Code: 201. Response Value= 5b4784f4221d226bc52461db
Hygieia Deployment Publisher - Looking for file pattern '*.*' in directory D:/Jenkins/workspace/freestyle
Hygieia Deployment Publisher: Processing  file: D:\Jenkins\workspace\freestyle\.git
Hygieia Deployment Publisher: Processing  file: D:\Jenkins\workspace\freestyle\README.md
Hygieia Deployment Publisher: Processing  file: D:\Jenkins\workspace\freestyle\.git\hooks\applypatch-msg.sample
Hygieia Deployment Publisher: Processing  file: D:\Jenkins\workspace\freestyle\.git\hooks\commit-msg.sample
Hygieia Deployment Publisher: Processing  file: D:\Jenkins\workspace\freestyle\.git\hooks\post-update.sample
Hygieia Deployment Publisher: Processing  file: D:\Jenkins\workspace\freestyle\.git\hooks\pre-applypatch.sample
Hygieia Deployment Publisher: Processing  file: D:\Jenkins\workspace\freestyle\.git\hooks\pre-commit.sample
Hygieia Deployment Publisher: Processing  file: D:\Jenkins\workspace\freestyle\.git\hooks\pre-push.sample
Hygieia Deployment Publisher: Processing  file: D:\Jenkins\workspace\freestyle\.git\hooks\pre-rebase.sample
Hygieia Deployment Publisher: Processing  file: D:\Jenkins\workspace\freestyle\.git\hooks\pre-receive.sample
Hygieia Deployment Publisher: Processing  file: D:\Jenkins\workspace\freestyle\.git\hooks\prepare-commit-msg.sample
Hygieia Deployment Publisher: Processing  file: D:\Jenkins\workspace\freestyle\.git\hooks\update.sample
Hygieia Deployment Publisher: Processing  file: D:\Jenkins\workspace\freestyle\src\Rectangle.java
Hygieia Deployment Publisher: Processing  file: D:\Jenkins\workspace\freestyle\src\Rectangulator.java
Hygieia: Published Deploy Data: Response Code: 201. Response Value= "5b4784fb221d226bc52461f8"
Hygieia: Published Deploy Data: Response Code: 201. Response Value= "5b4784fb221d226bc52461f9"
Hygieia: Published Deploy Data: Response Code: 201. Response Value= "5b4784fb221d226bc52461fa"

**Comment by Sbrenthughes** [comment]
It wouldn't be the full path `D:/Jenkins/workspace/freestyle/`. For example, if your artifact is `${WORKSPACE}/myartifact.jar` then you would do `artifactDirectory: '/'`

**Comment by ham5768** [comment]
Yea i could see few updates on dashboard. Question here.. I thought it would show different stages of Jenkinsfile Pipeline..  for ex: in my case i have two different stages named : "Build" & "Deploy"

stage ('Build'){
                
                steps {
                    hygieiaBuildPublishStep buildStatus: 'InProgress'
                      }
				}
            
             stage ('Deploy'){
                steps {
                    hygieiaDeployPublishStep applicationName: 'PublishInDashboard', artifactDirectory: 'D:/Jenkins/workspace/freestyle/', artifactGroup: 'None', artifactName: '*.java', artifactVersion: '1.1', buildStatus: 'InProgress', environmentName: 'QA'

                      }
				}

**Comment by Sbrenthughes** [comment]
So you need a `hygieiaDeployPublishStep ` for each stage DEV, QA, PROD, PERF, TEST, etc
