### ISSUE TITLE
not getting all project

### ISSUE THREAD

**Issue by monikanaagar** [capitalone/Hygieia#2355]
I am access below url but not getting complete of project

http://p-sonarqube.nl.eu.xxxxx.com:9000/

can anyobe help?

**Comment by Sbrenthughes** [comment]
Can you post post properties file and any error in logs?

**Comment by monikanaagar** [comment]
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
dbreplicaset=false
dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=

# Database Password - default is blank
dbpassword=

# Collector schedule (required)
sonar.cron=0 0/1 * * * *

# Sonar server(s) (required) - Can provide multiple

sonar.servers[0]=http://p-sonarqube.xx.eu.xx.com:9000/


sonar.versions[0]=6.7

# Sonar Metrics - Required. 

sonar.metrics[0]=ncloc,violations,new_vulnerabilities,critical_violations,major_violations,blocker_violations,tests,test_success_density,test_errors,test_failures,coverage,line_coverage,sqale_index,alert_status,quality_gate_details

**Comment by monikanaagar** [comment]
@Sbrenthughes  no error in collector log

**Comment by Sbrenthughes** [comment]
Is it possible credentials are required?

`sonar.username=`
`sonar.password=`

**Comment by monikanaagar** [comment]
we can close this issue.

**Comment by monikanaagar** [comment]
@Sbrenthughes  I have given 
sonar.username=
sonar.password=
in properties file 
now getting 404

**Comment by Sbrenthughes** [comment]
I am confused by the opening and closing of this issue. Is it resolved?

**Comment by monikanaagar** [comment]
It is resolved. thanks

**Comment by Sbrenthughes** [comment]
How did you resolve the issue?

**Comment by monikanaagar** [comment]
I have changed the url and provide user and passowrd in the properties files.

Without username n passowrd ,we are getting only public project not the private one

**Comment by Sbrenthughes** [comment]
Thank you!
