### ISSUE TITLE
some questions with gitlab collectors

### ISSUE THREAD

**Issue by Piaoyzma** [capitalone/Hygieia#2358]
Hi team,
I have some questions when I use gitlab collectors.I get the latest code，and the version of gitlab-scm-collector.jar is 2.0.5-SNAPSHOT。My application.properties is as follows：
![image](https://user-images.githubusercontent.com/29573171/42746765-1473d1c2-890c-11e8-8e44-60b077fc06a7.png)
But there are errors in the log as follow：
![image](https://user-images.githubusercontent.com/29573171/42746298-a849ae26-88c6-11e8-9119-ef9b47bce951.png)
I checked it many times and didn't find the reason. Then I tried to replace the jar version , using gitlab-scm-collector-2.0.4-SNAPSHOT, which worked.Application.properties has not changed.
![image](https://user-images.githubusercontent.com/29573171/42746435-49d29dca-88c7-11e8-9dad-bfbcd895599e.png)
![image](https://user-images.githubusercontent.com/29573171/42747278-5df5650c-890e-11e8-84a2-e9c24b95d77f.png)

The log is normal,and the data was also collected. But it only took effect in the first TeamDashboard. When I created a new TeamDashboard, I filled in the new gitlab repository address, but it didn't take effect. The data displayed was always the first gitlab repository.This is strange, I restarted the service, but it did not work. 
Please help me find a solution!

**Comment by subodhbattina** [comment]
@Piaoyzma : Can you please check if your second repository is enabled in the database?
Check in "collector_items" collection where "options.url" = the repo url you provided.

**Comment by subodhbattina** [comment]
@Piaoyzma : Wanted to touch base and check if you were able to followup on our last conversation?

**Comment by Piaoyzma** [comment]
@subodhbattina Sorry, I missed the reply. I checked out mongodb, I didn't find the reason, probably because I was not familiar with mongodb. I will take the time to try again, the problem is closed first, thank you very much for your reply.

**Comment by nurhannankhairi** [comment]
Hi. I've error 401 unauthorized.. I think because of gitlab host url as I'm using internal repo. could u provide me the sample?
