### ISSUE TITLE
Chatops build failing with compilation error

### ISSUE THREAD

**Issue by fluidjeel** [capitalone/Hygieia#236]
The chatOps collector is failing with pmd errors. I have skipped the pmd check and tried building , but i receive compilation error. Below is the error log:
[log.txt](https://github.com/capitalone/Hygieia/files/67034/log.txt)

**Comment by tabladrum** [comment]
Please build the whole project "Hygieia".
Or, "mvn clean install" on core and then build any individual collector/api.

**Comment by fluidjeel** [comment]
@tabladrum , Thanks for your input. The option1 of Builing the whole project worked.

However, the second option of building the core and then individually building the collectors fails for few collectors , like stash and chatops. 

Anyways, the first option of building the whole project serves the purpose of generating all the jars. So individual build failure shouldnt be an issue.
