### ISSUE TITLE
New Feature needed for Dashboard

### ISSUE THREAD

**Issue by softwareklinic** [capitalone/Hygieia#237]
While wanting to add couple of projects out of 100s of projects from the list... it especially hard to find the project that i was looking for...

We certainly need to have search box with autosuggest-refresh --- not just a dropdown for the widgets...

That will make the dashboard more user-friendly... for adding new projects/branches/builds etc...

**Comment by tabladrum** [comment]
Couldn't agree more. Thanks

**Comment by tabladrum** [comment]
Flagged as an enhancement.

**Comment by tabladrum** [comment]
Fixed in master now.
