### ISSUE TITLE
cannot proceed further with mvn clean install package

### ISSUE THREAD

**Issue by Mohitg06** [capitalone/Hygieia#2370]
Followed the steps mentioned http://capitalone.github.io/Hygieia/setup.html
while trying mvn clean install package- i get the below error:
Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?

I tried mvn clean install -DskipTests and I get below error:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project hygieia-publisher: Compilation failure
[ERROR] java.nio.file.NoSuchFileException: /Users/xx/xx/Hygieia/hygieia-jenkins-plugin/target/classes/META-INF/annotations/hudson.Extension
[ERROR] 

I will appreciate any help here
I am using java 10.0.1

**Comment by matthewbeasley** [comment]
@Mohitg06 - we support java 1.8.x

**Comment by Mohitg06** [comment]
@matthewbeasley , ok so I will have to downgrade to java 1.8 x correct?

**Comment by Sbrenthughes** [comment]
Yes..
