### ISSUE TITLE
Any plans for writing deploy collectors for Application Servers ( like Jboss,Weblogic,WAS)

### ISSUE THREAD

**Issue by muralikvns** [capitalone/Hygieia#2379]
Hi Team,

Any plans for writing collectors in deploy module for exclusively for Jboss,Weblogic,WAS. This will be helpful in capturing the server metrics/applications status

**Comment by rvema** [comment]
@muralikvns You are welcome to write one, Please follow the steps as in the documentation to create one. http://capitalone.github.io/Hygieia/create_collector.html

**Comment by rvema** [comment]
Closing this issue as the collector does not exist and need to be written if needed.
