### ISSUE TITLE
Do we want to move the project to gradle?

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#238]
I see there is a branch out that looks idle.  Is there an interest to move the project to gradle, I a willing to volunteer to do it if there is agreement from the project owner. (I can tackle it in Jan)

**Comment by tabladrum** [comment]
I want to move to gradle at some point after Jan. We are doing a major feature during Jan.

**Comment by jimzucker** [comment]
OK, let me know if you want me to work on it.  I have a lot of experience with gradle and I see the gradle.com guys frequently they are local so I dont expect hitting anything I can't overcome..

**Comment by tabladrum** [comment]
:+1:

**Comment by jimzucker** [comment]
A relevant article: http://gradle.org/migrating-a-maven-build-to-gradle/

**Comment by amitmawkin** [comment]
We had issues with grafle build in the past bad had to revert back , so for maven shops we would support both for sometime i.e. Maven and gradle

**Comment by jimzucker** [comment]
Well, I wouldn't recommend maintaining 2 build systems, thats too much overhead, I would stick with Mvn unless we could cut over directly.

Regarding the issues I could help solve them as we can get support directly from the Gradle team, in the unlikely situation it is required.  If we do move I can verify with them the build follows all best practices.

**Comment by amitmawkin** [comment]
closing this , as it's not an issue per se @jimzucker
