### ISSUE TITLE
Data is not coming inside product dashboard,however it is populating inside the deploy widget

### ISSUE THREAD

**Issue by thedevopsguru** [capitalone/Hygieia#2386]
I am facing issues while fetching the data inside the product dashboard. The data for commit,build,deploy(QA,PROD,Dev) is not coming at all. I am able to fetch the data for deployment under Deploy widget but that too is also not coming properly.
Please suggest how the data will populate inside the product dashboard.
I have attached the snapshot for the configurations.

**Here the data is coming as a blank for code,commit and other environments.**

![product_dashboard](https://user-images.githubusercontent.com/41733996/43515633-85523434-9572-11e8-89a3-87884b87446e.jpg)
![build_deploy_dashboard](https://user-images.githubusercontent.com/41733996/43515642-8e6a621c-9572-11e8-8dc5-089327a97561.jpg)
![jenkins_setup_hyg](https://user-images.githubusercontent.com/41733996/43515879-392f78e0-9573-11e8-94d5-501aa5f3f7d8.JPG)

![pipeline_data2](https://user-images.githubusercontent.com/41733996/43516077-f21e6668-9573-11e8-824a-836599fcbd9c.JPG)

![jenkins_setup_deployment](https://user-images.githubusercontent.com/41733996/43515880-3957cd54-9573-11e8-926a-7e538e5599ab.JPG)

**Comment by thedevopsguru** [comment]
Please suggest, I want the data inside the product dashboard.

**Comment by thedevopsguru** [comment]
Issue resolved by debugging.

**Comment by shardulsrivastava** [comment]
@thedevopsguru  what seemed to be the issue, i am also facing the same issue. In my case m not getting data in DEV ,STAG, PROD environments.however commit section has data

<img width="1235" alt="screen shot 2018-09-27 at 6 15 28 pm" src="https://user-images.githubusercontent.com/9951135/46139529-5d7f6580-c281-11e8-8ff6-74c334fa89ca.png">

**Comment by syedsfayaz** [comment]
@thedevopsguru @shardulsrivastava  I am seeing similar issue. It would have been better if you mentioned how you resolved the issue.

**Comment by rogerioagostinho** [comment]
@thedevopsguru @shardulsrivastava and @syedsfayaz I am facing same issue, just Commit holds data on Product dashboard, did you guys have Build and all the following environments filled up? If yes, what you done to have it working?

I do appreciate any direction.
