### ISSUE TITLE
Include Demo Dashboard

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#239]
Please consider adding a demo/default dashboard that all users can setup. for example:

Git - can be setup to point to this repo
JIRA - maybe configured for lira.atlassian.com (I think we can request a free open source JIRA project from Atlasssian, then we could configure DEMO data to show of the product)

Not sure about the other components yet, haven't reviewed them.

Another potential approach is to add a container with demo versions of all of the apps, might be interesting for continuous testing..

**Comment by tabladrum** [comment]
We are looking at it - looking for a free cloud environment :-)

**Comment by softwareklinic** [comment]
What kind of config?


Regards,
Keyur

On Dec 18, 2015, at 4:45 PM, tabladrum <notifications@github.com<mailto:notifications@github.com>> wrote:


We are looking at it - looking for a free cloud environment :-)

**Comment by jimzucker** [comment]
When somebody downloads rhe project it woukd be noce if they could have a fully workiinf demo dashboard

(Ie git configured with a githup project)

**Comment by jimzucker** [comment]
Here is how it looks using the demo data as described in Setup.md, for chat-ops I just pointed to my own hip chat, I have to see why JIRA is not working.

![screenshot 2016-02-09 10 39 48](https://cloud.githubusercontent.com/assets/14372687/12926762/c0036ed0-cf19-11e5-986b-b890e65caf3c.png)

**Comment by tabladrum** [comment]
Awesome!!!!!!!!
