### ISSUE TITLE
Udeploy json from mongodb 

### ISSUE THREAD

**Issue by cfmaley** [capitalone/Hygieia#240]
Could somebody who is using udeploy collector post the Json schema from the mongodb. 

I'm trying to hard code the data to demo to colleagues.

Thanks

**Comment by tabladrum** [comment]
I have a set of sample jsons in the udeploy collector project (in test)...

**Comment by cfmaley** [comment]
Thank you never thought to look there.


Chris

**Comment by tabladrum** [comment]
You will have to use those deploy api responses and can use the test classes (modify them locally) to actually create the MongoDB entries - there are relational id's with other core domain objects and so cant just copy from one database and put onto another.
