### ISSUE TITLE
mvn clean package fails for Jenkins plugin. Dependancy not hosted on Jenkins.CI

### ISSUE THREAD

**Issue by stphnwallace** [capitalone/Hygieia#2402]
**Failure to find com.capitalone.dashboard:core:jar:2.0.5-SNAPSHOT when compiling the Jenkins module**

mvn 3.5.4 + java 1.8 + Centos 7

Have done git clone of the repo, cd hygieia-jenkins. Trying to build the Jenkins module independently.

`mvn test` fails...

[ERROR] Failed to execute goal on project hygieia-publisher: Could not resolve dependencies for project org.jenkins-ci.plugins:hygieia-publisher:hpi:2.0.5-SNAPSHOT: Failure to find com.capitalone.dashboard:core:jar:2.0.5-SNAPSHOT in http://repo.jenkins-ci.org/public/ was cached in the local repository, resolution will not be reattempted until the update interval of repo.jenkins-ci.org has elapsed or updates are forced -> [Help 1]

The pom.xml file requires 2.0.5-SNAPSHOT for core and hpi elements. `mvn test -X` shows that the 2.0.5 version of the artefact doesn't seem to exist on jenkins-ci.

Changing 2.0.5-SNAPSHOT to 2.0.4 allows the build to complete, but not sure if it is responsible for the subsequent error.

i.e. It successfully pulls down from https://repo.jenkins-ci.org/webapp/#/artifacts/browse/tree/General/public/com/capitalone/dashboard/core/2.0.4

**HOWEVER**...we have a new error, which may or may not be related.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project hygieia-publisher: Compilation failure: Compilation failure: 
[ERROR] /home/ec2-user/Hygieia/hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/utils/CodeQualityMetricsConverter.java:[7,1] package com.capitalone.dashboard.model.quality does not exist
[ERROR] /home/ec2-user/Hygieia/hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/utils/CodeQualityMetricsConverter.java:[16,53] cannot find symbol
[ERROR]   symbol: class CodeQualityVisitor
[ERROR] /home/ec2-user/Hygieia/hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/utils/CodeQualityMetricsConverter.java:[41,23] cannot find symbol
[ERROR]   symbol:   class JunitXmlReport
[ERROR]   location: class jenkins.plugins.hygieia.utils.CodeQualityMetricsConverter
[ERROR] /home/ec2-user/Hygieia/hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/utils/CodeQualityMetricsConverter.java:[63,23] cannot find symbol
[ERROR]   symbol:   class FindBugsXmlReport
[ERROR]   location: class jenkins.plugins.hygieia.utils.CodeQualityMetricsConverter
[ERROR] /home/ec2-user/Hygieia/hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/utils/CodeQualityMetricsConverter.java:[146,23] cannot find symbol
[ERROR]   symbol:   class JacocoXmlReport
[ERROR]   location: class jenkins.plugins.hygieia.utils.CodeQualityMetricsConverter
[ERROR] /home/ec2-user/Hygieia/hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/utils/CodeQualityMetricsConverter.java:[207,23] cannot find symbol
[ERROR]   symbol:   class PmdReport
[ERROR]   location: class jenkins.plugins.hygieia.utils.CodeQualityMetricsConverter
[ERROR] /home/ec2-user/Hygieia/hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/utils/CodeQualityMetricsConverter.java:[252,23] cannot find symbol
[ERROR]   symbol:   class CheckstyleReport
[ERROR]   location: class jenkins.plugins.hygieia.utils.CodeQualityMetricsConverter
[ERROR] /home/ec2-user/Hygieia/hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/workflow/HygieiaCodeQualityPublishStep.java:[8,1] package com.capitalone.dashboard.model.quality does not exist
[ERROR] -> [Help 1]

I tried to do an `mvn clean package` within "core" first, which compiled successfully, but when I returned to try and build Jenkins...same error :(

Was going thru corp proxy, so also tried tethering to my phone for direct web access on another machine with diff o/s (MAC OSX) as follows. Looks like the same error?

05:10:08 {master} ~/git/personal/Hygieia/hygieia-jenkins-plugin$ mvn --version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T21:57:37+10:00)
Maven home: /opt/local/share/java/maven3
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre
Default locale: en_AU, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.4", arch: "x86_64", family: "mac"
05:10:14 {master} ~/git/personal/Hygieia/hygieia-jenkins-plugin$ 

...
ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project hygieia-publisher: Compilation failure: Compilation failure:
[ERROR] /Users/stephenwallace/git/personal/Hygieia/hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/utils/CodeQualityMetricsConverter.java:[136,90] incompatible types: java.lang.Object cannot be converted to java.lang.String
[ERROR] /Users/stephenwallace/git/personal/Hygieia/hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/utils/CodeQualityMetricsConverter.java:[137,97] incompatible types: java.lang.Object cannot be converted to java.lang.String
[ERROR] /Users/stephenwallace/git/personal/Hygieia/hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/utils/CodeQualityMetricsConverter.java:[194,48] incompatible types: java.lang.Object cannot be converted to java.lang.String
[ERROR] /Users/stephenwallace/git/personal/Hygieia/hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/utils/CodeQualityMetricsConverter.java:[194,86] incompatible types: java.lang.Object cannot be converted to java.lang.String
[ERROR] /Users/stephenwallace/git/personal/Hygieia/hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/utils/CodeQualityMetricsConverter.java:[196,50] incompatible types: java.lang.Object cannot be converted to java.lang.String
[ERROR] /Users/stephenwallace/git/personal/Hygieia/hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/utils/CodeQualityMetricsConverter.java:[196,100] incompatible types: java.lang.Object cannot be converted to java.lang.String
[ERROR] /Users/stephenwallace/git/personal/Hygieia/hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/utils/CodeQualityMetricsConverter.java:[196,140] incompatible types: java.lang.Object cannot be converted to java.lang.String

Would love to help, but I'm an automation dude, not a Java genius :(

**Comment by subodhbattina** [comment]
@stphnwallace : Please do the following again:

1. Remove the existing repository.
2. Do a fresh git clone of the hygieia repository again to get the latest copy.
3. Then cd into "core" and do "mvn clean install". This will install the core jar into your local repository.
4. And then cd into "hygieia-jenkins-plugin", and do "mvn clean install" or "mvn clean package". Thanks !

**Comment by subodhbattina** [comment]
@stphnwallace: Any updates on this at all from your end? thanks.

**Comment by battinasubodh** [comment]
@stphnwallace: Just following up again, do you have any updates at all on this? Thanks.

**Comment by subodhbattina** [comment]
@stphnwallace: Since I didn't hear back from you, I am assuming this issue is resolved at your end, and so closing this issue. Thanks !

**Comment by rvema** [comment]
This is a valid issue and will be fixed with PR #2507
