### ISSUE TITLE
how to config contaxt path for UI

### ISSUE THREAD

**Issue by baitiandi** [capitalone/Hygieia#2405]
currenly, i access http//:server:port/, but i want to access like http//:server:port/dev, so how to config contaxt path "dev" for UI. thanks a lot

**Comment by subodhbattina** [comment]
@baitiandi: Please excuse me, I didn't get a chance to follow up on this. Could you please let me know if your issue is solved based on the comments in my last post? Thanks

**Comment by subodhbattina** [comment]
@baitiandi:Any updates on this at all?

**Comment by battinasubodh** [comment]
@baitiandi: Wanted to check one last time again, if you have any updates on this at all. Thanks.

**Comment by subodhbattina** [comment]
@baitiandi: Since we didn't hear back from you, I am assuming this issue is resolved at your end, and so closing the issue. Thanks !
