### ISSUE TITLE
Build modifying 2 committed files  UI/src/app/index.less & UI/src/index.html

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#242]
Something in the build is incorrectly modifying these 2 files or perhaps these should not be in the repo, not sure, but it is really annoying I keep getting these in my status.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   ../UI/src/app/index.less
	modified:   ../UI/src/index.html

**Comment by amitmawkin** [comment]
These files are generated every time ui project is build as prt of gulp workflow
