### ISSUE TITLE
how do i create the encrypted id:passwd for JIRA

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#243]
can somebody help me and tell me how to encrypt my id:passd for the JIRA collector?

**Comment by softwareklinic** [comment]
https://www.base64decode.org/ -- this will help

**Comment by softwareklinic** [comment]
64
Bit encoding - https://www.base64decode.org/



Regards,
Keyur

On Dec 18, 2015, at 8:07 PM, Jim Zucker <notifications@github.com<mailto:notifications@github.com>> wrote:


can somebody help me and tell me how to encrypt my id:passd for the JIRA collector?

**Comment by amp5208** [comment]
If you are on a Mac, you can use the following command: <code>echo "username:password" | base64</code>

**Comment by jimzucker** [comment]
thanks we can close this.  I am putting these hints into the config files I am creating on #227
