### ISSUE TITLE
UDeploy Widget always empty

### ISSUE THREAD

**Issue by krishnakanthbn** [capitalone/Hygieia#245]
Hi,

I am able to build the UCD collector and run it. In the console, I got messages the "New Apps 4 0s....." which means it was able to connect to UCD server.

But when I configure the widget by selecting an application in UCD, the widget does not show up any data.

The application is run 3 times and has 5 components and 1 environment.

Please let me know what wrong I might be doing in the configuration. Thanks in advance.

I am using UCD 6.1.1.4 and latest Hygieia downloaded from GITHUB on 16th Dec 2015.

I observed that in MongoDB, I do not see any collection/table for UCD. I can see feature, scope, builds, code_quality, commits respective to the widgets but nothing for UCD, 

For your information, I was unable to connect to MongoDB through Robomongo. Hence I changed the schema version to 3 as per instructions in http://stackoverflow.com/questions/29006887/mongodb-cr-authentication-failed . I am not sure if this had any impact. I had setup Hygieia in September 2015 as well but even then UCD widget was empty, although MongoDB was using Schema version 3.

PLease help. Thanks in advance.

**Comment by tabladrum** [comment]
Can you confirm that UCD collector is running and logging any errors. If you find errors, can you paste them here (PLEASE take out any sensitive information from the JSON that you don't want to share such as internal ip, app name, server identities etc.)

If no error and assuming everything else is ok, I would like to see the output of these UCD api:
1. http://mycompany.ucd.com/rest/deploy/application  
this should list all 4 apps you have. Note down the ID of the app that you deployed and note
2. http://mycompay.ucd.com/rest/deploy/application/app_id/environments/false
this should list the environment(s) that your app is deployed. Note down the env id.
3. http://mycompay.ucd.com/rest/deploy/environment/env_id/resources
This should list all the resources (agents, components etc) that are attached to the environment along with their inventory (version etc)
4. http://mycompay.ucd.com/rest/deploy/environment/env_id/noncompliantResources
This should list all the resources that are not compliant with the desired state.

**Comment by krishnakanthbn** [comment]
Hi ,

Many thanks for quick response.

There is no error in the collector task console.

I am attaching the output for all four REST calls you have asked for.

I also was worrying because of no table related to UDeploy in MongoDB. Would this have any impact?

Thanks and Regards,

KrishnaKanth B N

**Comment by softwareklinic** [comment]
How many collectors entries do u have in Mongo



Regards,
Keyur

On Dec 19, 2015, at 10:41 PM, krishnakanthbn <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi ,

Many thanks for quick response.

There is no error in the collector task console.

I am attaching the output for all four REST calls you have asked for.

I also was worrying because of no table related to UDeploy in MongoDB. Would this have any impact?

Thanks and Regards,

KrishnaKanth B N

**Comment by krishnakanthbn** [comment]
Hi,

I have four collectors on Mongo. Below are the details.

/* 1 */
{
    "_id" : ObjectId("56750e8043e11b177082dc67"),
    "_class" : "com.capitalone.dashboard.model.HudsonCollector",
    "buildServers" : [
        "http://jenkinsserver:8085/"
    ],
    "name" : "Hudson",
    "collectorType" : "Build",
    "enabled" : true,
    "online" : true,
    "lastExecuted" : NumberLong(1450586700119)
}

/* 2 */
{
    "_id" : ObjectId("5675239843e11b31989c7015"),
    "_class" : "com.capitalone.dashboard.model.SonarCollector",
    "sonarServers" : [
        "http://sonarqubeserver:9001"
    ],
    "name" : "Sonar",
    "collectorType" : "CodeQuality",
    "enabled" : true,
    "online" : true,
    "lastExecuted" : NumberLong(1450586700281)
}

/* 3 */
{
    "_id" : ObjectId("5675271c43e11b3830fc558b"),
    "_class" : "com.capitalone.dashboard.model.Collector",
    "name" : "Subversion",
    "collectorType" : "SCM",
    "enabled" : true,
    "online" : true,
    "lastExecuted" : NumberLong(1450586700203)
}

/* 4 */
{
    "_id" : ObjectId("5675446843e11b2e4cd93bbe"),
    "_class" : "com.capitalone.dashboard.model.UDeployCollector",
    "udeployServers" : [
        "https://ucdserver:8444"
    ],
    "name" : "UDeploy",
    "collectorType" : "Deployment",
    "enabled" : true,
    "online" : true,
    "lastExecuted" : NumberLong(1450586700993)
}

Many thanks for quick response.

Thanks and Regards,

KrishnaKanth B N

**Comment by krishnakanthbn** [comment]
Dear All,

The data just started showing up on the dashboard now!

Earlier, in the application.properties file, I had given http://ucdserver:8080 (I was facing PKIX certificate handshake issue. So, I thought https may not work with the collector. I imported the certificate into my JVM and With http, it was able to pull applications and it also allowed me to select in widget. So, I thought, it would pull the subsequent details as well.) Now I have changed it to https://ucdserver:8444. It started showing up after 5-10 minutes.

I think this can be closed now. Please advise.

**Comment by softwareklinic** [comment]
Kudos



Regards,
Keyur

On Dec 19, 2015, at 11:09 PM, krishnakanthbn <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear All,

The data just started showing up on the dashboard now!

Earlier, in the application.properties file, I had given http://ucdserver:8080 (I was facing PKIX certificate handshake issue. So, I thought https may not work with the collector. I imported the certificate into my JVM and With http, it was able to pull applications and it also allowed me to select in widget. So, I thought, it would pull the subsequent details as well.) Now I have changed it to https://ucdserver:8444. It started showing up after 5-10 minutes.

I think this can be closed now. Please advise.

**Comment by tabladrum** [comment]
Seems the issue is resolved now.
