### ISSUE TITLE
Need clarification on SonarQube widget

### ISSUE THREAD

**Issue by krishnakanthbn** [capitalone/Hygieia#246]
Hi,

Request your help in understanding the parameters reported in SonarQube Code Quality widget.

1. In my dashboards, Rules Compliance always shows empty ('-'). Do we need any specific plugin on SonarQube to get this data? In SonarQube server as well, I do not see Rules Compliance metric.

2. Technical Debt shown on Hygieia dashboard and SonarQube dashboard are different. Does Hygieia pick value from any other metric in SonarQube? Because there is a huge difference the values shown in both dashboards. For example, 40 days in SonarQube is shown as 14 days and 1 day 6 hours is shown as 15 hours in Hygieia.

3. What is the source of SECURITY ANALYSIS data? How do we enable it?

4. What is the source of FUNCTIONAL TESTS data? How do we enable it?

Thanks in advance.

I am currently using SonarQube 4.5.1.

**Comment by tabladrum** [comment]
There has been some changes in latest SonarQube on some of the metrics. We will have to revisit some metrics. Some of the metrics are even removed. 

Security analysis: Currently it supports Fortify. We could not publish the collector as it uses some non-Open Source client libraries that comes with Fortify. Fortify's latest release now supports REST and we will rewrite the collector when we start using the latest version. In the mean time, if you are using Fortify and want to use this part of the dashboard, I can give you the collector code and you will have to build it by using those libraries. 

Functional Tests data are collected from Jenkins that kicks off Cucumber tests. For sample set up see https://github.com/capitalone/Hygieia/tree/master/jenkins-cucumber-test-collector

**Comment by vishalbisa** [comment]
Hi tabladrum,

Can you please share the collector code for fortify.

Thanks in advance

**Comment by papithag** [comment]
Hi tabladrum,
Can you share the updated algorithm for converting sqale_index to technical debt? 

I also see different values in sonarqube dashboard and hygieia dashboard.

Thanks!!!

**Comment by tabladrum** [comment]
@vishalbisa I can upload fortify collector on my personal github page. Is that okay?

**Comment by tabladrum** [comment]
@jimzucker Can you see if @papithag 's question above is resolved via your Sonar changes?

**Comment by jimzucker** [comment]
@tabladrum @papithag I think this should be closed, with a related change I removed the internal calc and we display the Tech Debt provided by Sonar with not modification now.

**Comment by vishalbisa** [comment]
Hi @tabladrum 

please upload the fortify collector to your personal github page and provide necessary permissions to access it, also can you please let me know which files (HP fortify) should be added in collector code as reference.

Thanks

**Comment by tabladrum** [comment]
https://github.com/tabladrum/fortify-collector
see the pom file and look for com.fortify group. You should have these jar 's from HP. You can install those in your company's maven repo or on your own laptop.

**Comment by vishalbisa** [comment]
Thanks @tabladrum

**Comment by ghouspasha** [comment]
@tabladrum : I am unable to find fortify jar files in maven public repository. Could you please give me the path to download these jars. 
 com.fortify:fortify-common:jar:4.30,
 com.fortify:fortify-crypto:jar:1.0,
 com.fortify:fortify-meta-api:jar:4.30,
 com.fortify:fortify-meta-impl:jar:4.30,
 com.fortify:fortify-public:jar:4.30, 
 com.sun.xml.wsit:xws-security:jar:1.3.1, 
 com.sun.xml.wsit:wsit-rt:jar:1.1, 
 com.fortify:wsclient:jar:4.30, 
 com.fortify:wsobject:jar:4.30,

**Comment by jimzucker** [comment]
@ghouspasha can you attach your full output of your build so we can see the error?

**Comment by ghouspasha** [comment]
Failed to execute goal on project fortify-collector: Could not resolve dependencies for project com.capitalone.dashboard:fortify-collector:jar:1.0: The following artifacts could not be resolved: com.capitalone.dashboard:core:jar:2.0.0-SNAPSHOT,
 com.fortify:fortify-common:jar:4.30,
 com.fortify:fortify-crypto:jar:1.0,
 com.fortify:fortify-meta-api:jar:4.30,
 com.fortify:fortify-meta-impl:jar:4.30,
 com.fortify:fortify-public:jar:4.30, 
 com.sun.xml.wsit:xws-security:jar:1.3.1, 
 com.sun.xml.wsit:wsit-rt:jar:1.1, 
 com.fortify:wsclient:jar:4.30, 
 com.fortify:wsobject:jar:4.30,
 serializer:serializer:jar:2.9.1:
 Could not find artifact com.capitalone.dashboard:core:jar:2.0.0-SNAPSHOT in nexus (http://gchbuild.ebiz.verizon.com/nexus/content/groups/public) 
 
@jimzucker

**Comment by ghouspasha** [comment]
Failed to execute goal on project fortify-collector: Could not resolve dependencies for project com.capitalone.dashboard:fortify-collector:jar:1.0: The following artifacts could not be resolved: com.capitalone.dashboard:core:jar:2.0.0-SNAPSHOT,
 com.fortify:fortify-common:jar:4.30,
 com.fortify:fortify-crypto:jar:1.0,
 com.fortify:fortify-meta-api:jar:4.30,
 com.fortify:fortify-meta-impl:jar:4.30,
 com.fortify:fortify-public:jar:4.30, 
 com.sun.xml.wsit:xws-security:jar:1.3.1, 
 com.sun.xml.wsit:wsit-rt:jar:1.1, 
 com.fortify:wsclient:jar:4.30, 
 com.fortify:wsobject:jar:4.30,
 serializer:serializer:jar:2.9.1:
 Could not find artifact com.capitalone.dashboard:core:jar:2.0.0-SNAPSHOT
@jimzucker

**Comment by jimzucker** [comment]
@ghouspasha  which branch are you building?

**Comment by ghouspasha** [comment]
I have taken the code for fortify collector and trying to build the same.. I don't have those artifacts..could you please tell me from where can I get those artifacts

**Comment by ghouspasha** [comment]
@jimzucker : com.fortify jar files are freeware or paid ones ??

**Comment by jimzucker** [comment]
@ghouspasha I think we need to wait for @tabladrum for this issue.  I am not sure which branch you are building, I dont have this collector in the branches I aw working on.

**Comment by tabladrum** [comment]
Fortify jars are available from the fortify installs. In other words they are commercially available jars. We can not distribute them.

**Comment by ghouspasha** [comment]
@tabladrum  Regarding HP Fortify Collector,Could you pls help me to 
1. how to get exact web service url for fortify
    fortify.server=http://myfortify/ssc/fm-ws/services    
2. is fortify a REST or SOAP service?

**Comment by arunmk108** [comment]
@tabladrum Can you please suggest if i want to use hygieia dashboard for fortify **v18.10**, what changes required to do in the below code? 
https://github.com/tabladrum/fortify-collector

..Arun Mulka

**Comment by amvda** [comment]
Hi, I'm currently trying to display metrics on my sonar widget. From checking on the DB, I don't see the following being populated:
1. new_violations
2. new_critical_violations
3. new_major_violations
4. new_blocker_violations

Can you please help me understand how I can achieve values on those specific fields?
Thanks.!
