### ISSUE TITLE
Chatops requires scope defined from HipChat

### ISSUE THREAD

**Issue by fluidjeel** [capitalone/Hygieia#248]
Hi,

This is more of an info required request than an issue. The chatops widget probably requires me to define the scope of the Integration. I believe this needs to be done on HipChat. As you had done your integration with HipChat can you please guide me the action that was taken from your end.

As per the readme, I have installed and ran the chatops jar, created a room in Hipchat, saved the integration for the room, and fetched the auth token for the Integration created for the room. Tested the integration by sending message from Integration to Hipchat.

Please let me know, what could be the issue in my case.

Thanks @amitmawkin , @tabladrum for all the responses to previous queries. 

Attached is the log and screenprint of the issue:

DATA GOT BACK:{"error":{"code":403,"message":"This action requires one of the following scopes: [u'view_messages']","type":"Forbidden"}}

![image](https://cloud.githubusercontent.com/assets/10943776/11937230/3d0d397c-a7d0-11e5-9a0b-da6a0e500e50.png)

**Comment by amitmawkin** [comment]
It looks to me your token does not have the necessary permissions assigned such as view messages  , also make sure you use V2 api token and not v1 token.

**Comment by fluidjeel** [comment]
@amitmawkin , exactly where is the option in Hipchat to assign permissions to a token. I believe it is defined in scope, but im not sure where/how I can modify it. I know this is more of a HipChat side of work but I couldnt find any clear instructions

**Comment by amitmawkin** [comment]
when you login in public hipchat  there are multiple ways to do it
if you are room admin you can go under GroupAdmin - API - Auth token and create a token there
if you are not an admin , after login go to rooms - click your room - > Click tokens and generate  a token with view-scope.

<img width="1135" alt="screen shot 2015-12-21 at 7 00 16 pm" src="https://cloud.githubusercontent.com/assets/6624821/11944656/bba22b36-a815-11e5-96be-0c465ac8a55e.png">

**Comment by fluidjeel** [comment]
@amitmawkin , thanks, I am a room admin (I created the room). But didnt find the the GroupAdmin Api option...

Anyways, i tried the second option and created a token with View Room scope. But i still got the same error.

I will try to find out the first option and try it out

**Comment by amitmawkin** [comment]
Here is how I tested it against public hipchat by generating a token by clicking link below
The v2 tokens are generated at https://www.hipchat.com/account/api under your account in HipChat. API v2 documentation is here. 
Hope this helps. Please close the issue if your problem is resolved

**Comment by fluidjeel** [comment]
Thanks for the inputs. It worked
