### ISSUE TITLE
Dockerize the application

### ISSUE THREAD

**Issue by sudarkoff** [capitalone/Hygieia#25]
Create `Dockerfile`'s for each individual service and `docker-compose.yml` for the entire app to spin the whole application with a single command: `docker-compose up`.

**Comment by amitmawkin** [comment]
Absolutely, we are in process of  building and releasing both to DHE, watch for announcements on our twitter handle @capitaloneio for it to become available, i have marked this as an enhancement request.

**Comment by msabramo** [comment]
:+1: to Dockerizing. This would make it much easier to get started.

**Comment by brianwallace** [comment]
+1

**Comment by pjaol** [comment]
I've just dockerized the API https://github.com/pjaol/Hygieia/tree/master/api
using spotify's docker maven plugin, if interested I can generate a pull request?

**Comment by jdamick** [comment]
closed by pull #129

**Comment by sudarkoff** [comment]
Sweet!
