### ISSUE TITLE
build collector NPE.

### ISSUE THREAD

**Issue by bimlendu** [capitalone/Hygieia#26]
Hi,

I am getting java.lang.NullPointerException errors on trying to start the hudson collector. Other collectors are working fine. But I am not able to get the jenkins collector to work.

```
2015-07-31 09:28:27,591 ERROR o.s.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hudsonCollectorTask': Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136) ~[spring-beans-4.1.4.RELEASE.jar!/:4.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408) ~[spring-beans-4.1.4.RELEASE.jar!/:4.1.4.RELEASE]
```

Full stacktrace of the error is here: https://gist.github.com/bimlendu/82a5be5606464fd17743

Thanks.

**Comment by amitmawkin** [comment]
can you provide your properties file for build collector here

**Comment by bimlendu** [comment]
Its same as in the readme.

```
spring.data.mongodb.database=dashboarddb
spring.data.mongodb.host=127.0.0.1
spring.data.mongodb.port=27017
spring.data.mongodb.username=dashboarduser
spring.data.mongodb.password=dA$hb0Ardu$eR
hudson.cron=0 0/5 * * * *
hudson.servers[0]=https://jenkins.host.com/
hudson.saveLog=true
```

**Comment by bimlendu** [comment]
Hi @amitmawkin , any help on this?

The hudson collector jar that gets built has following dependecy jars in lib:

```
[root@001 tmp]# ls lib/ | grep spring
spring-aop-4.1.4.RELEASE.jar
spring-beans-4.1.4.RELEASE.jar
spring-boot-1.2.1.RELEASE.jar
spring-boot-autoconfigure-1.2.1.RELEASE.jar
spring-boot-starter-1.2.1.RELEASE.jar
spring-boot-starter-data-mongodb-1.2.1.RELEASE.jar
spring-boot-starter-logging-1.2.1.RELEASE.jar
spring-context-4.1.4.RELEASE.jar
spring-core-4.1.4.RELEASE.jar
spring-data-commons-1.9.1.RELEASE.jar
spring-data-mongodb-1.6.1.RELEASE.jar
spring-expression-4.1.4.RELEASE.jar
spring-test-4.1.4.RELEASE.jar
spring-tx-4.1.4.RELEASE.jar
spring-web-4.1.0.RELEASE.jar
```

Do you think, the version of spring-web (4.1.0) is causing the issue. Most others are 4.1.4. Or this is acceptable?

**Comment by rogerwelin** [comment]
@bimlendu the prefix hudson in applications.properties is wrong. Use this instead:
Jenkins.cron=0 0/1 * * * *
Jenkins.servers[0]= https://jenkins.host.com/
Jenkins.saveLog=false

**Comment by amitmawkin** [comment]
Thanks , I have fixed the issue and corrected the case too, If you pull the latest changes
jenkins.cron=0 0/1 * * * *
jenkins.servers[0]= https://jenkins.host.com/
jenkins.saveLog=false

Let me know if this fixed it and you can close the issue

**Comment by amitmawkin** [comment]
Also updated readme.md to reflect the same

**Comment by bimlendu** [comment]
Thanks @rogerwelin and @amitmawkin . Jenkins collector is starting up ok now. Closing this issue.

**Comment by abhishek789** [comment]
Hi @rogerwelin and @amitmawkin 

Can you please have a look at issue "cannot run jenkins collector #1793" opened by me.
I am not able to run any collector and the java -jar command for the collector just does not get executed.
Could you please help!
It has been a week i am struggling now.

Thanks
Abhishek Somani
