### ISSUE TITLE
UI startup issue on AWS Linux

### ISSUE THREAD

**Issue by fluidjeel** [capitalone/Hygieia#264]
I have configured the Hygieia setup on the AWS linux. Following were the steps taken

NodeJs was installed from before hence skipped the brew installation

npm install -g bower
npm install -g gulp

npm install
bower install

I havent changed below from setup instructions as i coudnt understand what that means

Will need up update the ngFitText bower.json file to point to 'src/ng-FitText.js' instead of '/src/ng-FitText.js'

Next when i execute : gulp serve --local true

[ec2-user@dv-cnet-default-i-379a8df3 UI]$ gulp serve --local true i get the following error:

[log.txt](https://github.com/capitalone/Hygieia/files/80376/log.txt)

So I noticed setup instructions for MAC and Windows only, does that mean the MAC instruction will not work on AWS linux?

**Comment by fluidjeel** [comment]
@amitmawkin & @tabladrum , can you please comment on this

**Comment by amitmawkin** [comment]
are you still facing this issue?

**Comment by fluidjeel** [comment]
Yes, I haven't worked on this after I faced the issue.

**Comment by amitmawkin** [comment]
i think from the error logs looks like your bower dependencies are not downloaded correctly, would you clean the workspace and try again, also just try gulp serve

**Comment by jdamick** [comment]
i would delete the node_modules directory and npm install fresh..

**Comment by fluidjeel** [comment]
Thanks everyone fresh npm install worked.
