### ISSUE TITLE
modified:   UI/src/index.html

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#265]
Every time I build it shows up as modified, the build needs to be fixed or the file removed from the tree.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   UI/src/index.html

**Comment by amitmawkin** [comment]
This is how the gulp flow works when it builds your UI , it will regenerate the index.html and index.less every time to make sure any new bower dependency etc is picked up and not needed to be added manually.

**Comment by jimzucker** [comment]
Do we need the files in the source tree, its a pain to checkin and switch branches can you remove the files and add them to .gitignores?
