### ISSUE TITLE
Multiple branch/project view

### ISSUE THREAD

**Issue by softwareklinic** [capitalone/Hygieia#267]
Would it be possible in future release to track let us a dashboard where i can add multiple git/stash repos e.g.

Widget ROW 1 --> Stash project 1, Stash Project 2, Stash Project 3
Widget ROW 2 --> Jira project 1, Jira Project 2, Jira Project 3

**Comment by tabladrum** [comment]
Working on it.

**Comment by gnvsuneetha** [comment]
is this functionality available?

**Comment by amitmawkin** [comment]
Yes since 2.0 release

**Comment by gnvsuneetha** [comment]
Can you please tell me when is it going live

**Comment by gnvsuneetha** [comment]
Hi There,

I see that 2.0 version is live in Feb 2016. Could you please let me know
how do I upgrade it to 2.0 from 1.5.

I have custom code on top of Hygieia, so wondering how do I upgrade.

Thanks in advance.

Suneetha

**Comment by amitmawkin** [comment]
this is available since 2.0 release of Hygieia, hence closing this issue
