### ISSUE TITLE
Sonar collector is not working when Sonar needs authentication

### ISSUE THREAD

**Issue by gangadharahn** [capitalone/Hygieia#269]
Hi,

Sonar collector is not working when sonar need authentication. Its works fine if the sonar is not imposing the authentication.

In this situation Is there a way to connect to sonar from sonar collector by passing username and password and any keys??

**Comment by smsuresh** [comment]
@gangadharahn  Can you paste a sample .properties for SONAR
For me, its not connecting to sonar even when it doesnt require credential.

**Comment by gangadharahn** [comment]
@smsuresh Please find the .properties file for sonar.

#Database Name
spring.data.mongodb.database=dashboard

#Database HostName - default is localhost
spring.data.mongodb.host=localhost

#Database Port - default is 27017
spring.data.mongodb.port=27017

#Database Username - default is blank
spring.data.mongodb.username=

#Database Password - default is blank
spring.data.mongodb.password=

#Collector schedule (required)
sonar.cron=0 0/5 * * * *

#Sonar server(s) (required) - Can provide multiple
sonar.servers[0]=http://localhost:9000


#Sonar Metrics
sonar.metrics=ncloc,line_coverage,violations,critical_violations,major_violations,blocker_violations,sqale_index,test_success_density,test_failures,test_errors,tests

**Comment by smsuresh** [comment]
@gangadharahn Thankyou very much!!
It is working now!! :)

**Comment by smsuresh** [comment]
Now , need to configure for credential based authentication.

**Comment by subesokun** [comment]
Is there any progress on that topic? I've also a SonarQube server which requires authentication but so far there is no property like `sonar.user` and `sonar.password` I could set in the Sonar collector or?

**Comment by mshaw6** [comment]
Looking in the code , i found the solution.
Add these in the application.properties
sonar.username=
sonar.password=

**Comment by mrpudn** [comment]
Looks like multiple people have had this issue resolved - if it's still not working for you after trying the above, please create a new issue.

Thanks!

**Comment by vgandra** [comment]
Hello,

I'm getting below error when i configured sonar collecter, and not able to see the projects names in Configure Code Analysis Widget.

2017-05-22 16:17:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Sonar
2017-05-22 16:17:00,002 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
        at java.util.ArrayList.addAll(ArrayList.java:577) ~[na:1.8.0_131]
        at com.capitalone.dashboard.model.SonarCollector.prototype(SonarCollector.java:29) ~[sonar-codequality-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.SonarCollectorTask.getCollector(SonarCollectorTask.java:57) ~[sonar-codequality-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]

can anyone help on this???

Thanks!!!

**Comment by pteichner** [comment]
I put sonar.usernames[0]=user and sonar.passwords[0]=password in the config file but it's not working still getting 401

**Comment by dwij2812** [comment]
@pteichner use ```sonar.usernames=user``` and sonar.passwords=password``` instead it will work.

**Comment by rvema** [comment]
@pteichner and @dwij2812 the documentation for this sonar collector has been updateed by @Courtneyp123
