### ISSUE TITLE
Stash/Svn collector authentication

### ISSUE THREAD

**Issue by mfcarbo** [capitalone/Hygieia#270]
Hello, could someone provide an explanation of how the scm collectors get the user name and password to make requests to stash and svn please? Thanks!

**Comment by mfcarbo** [comment]
Unlike the other collectors, it appears the scm collectors use the id/pw of the user that created the dashboard. I am using the same id and password for the account in hygieia but still getting an unauthorized message. I have admin privs in stash.

**Comment by AdonisCelestine** [comment]
I am also stuck at the authentication part. @mfcarbo Did you manage to get further?

**Comment by mfcarbo** [comment]
@AdonisCelestine no, I did not go further. Storing our AD credentials (we use active directory authentication in stash) in mongodb is not a good option for us. If that is how hygieia is working.

**Comment by markpaychex** [comment]
I am also looking for an answer to this. Any updates?

**Comment by softwareklinic** [comment]
We
Modified the code internally for stash collector for:

1. To pass the username / password from properties file
2. To be able to point to any branch and not just the master




Sent from my iPhone

On Apr 4, 2016, at 12:49 PM, Mark <notifications@github.com<mailto:notifications@github.com>> wrote:


I am also looking for an answer to this. Any updates?

**Comment by tabladrum** [comment]
Great. Are you looking to submit a PR?

**Comment by softwareklinic** [comment]
Yes

Sent from my iPhone

On Apr 4, 2016, at 12:54 PM, tabladrum <notifications@github.com<mailto:notifications@github.com>> wrote:


Great. Are you looking to submit a PR?

**Comment by bimalvv** [comment]
@softwareklinic Did your changes merge to master?

**Comment by softwareklinic** [comment]
Bimal - if I cannot do it by tomorrow - will send you the fix

Sent from my iPhone

On Apr 10, 2016, at 6:28 AM, Bimal <notifications@github.com<mailto:notifications@github.com>> wrote:


@softwareklinic<https://github.com/softwareklinic> Did your changes merge to master?

**Comment by bimalvv** [comment]
@softwareklinic Thanks!

**Comment by AdonisCelestine** [comment]
@softwareklinic - Are your changes merged to master already.
If not is it possible for you share the code. Thanks in advance.

**Comment by Matschick** [comment]
I got the same problem. Can you provide us a help?

**Comment by oshingc** [comment]
Can you share the code please?

**Comment by satishc1** [comment]
Functionality merged in https://github.com/capitalone/Hygieia/pull/835
Refer to the "Encryption for private repos" section in the UI module readme.
