### ISSUE TITLE
Stash collector not working

### ISSUE THREAD

**Issue by papithag** [capitalone/Hygieia#272]
Stash collector not providing the commits as expected from Stash repository, results are not shown in Hygieia dashboard.
What is the repo URL format to configure in  Hygieia dashboard? Also what is the use of "git.api" property which is placed in application.properties?

Looking for the detailed configurations to get the exact results to be displayed in Hygieia dashboard.

**Comment by stein321** [comment]
hey @papithag , git.api determine which stash api you are using since there are different versions. I believe the most current one is " git.api=/rest/api/1.0/"

**Comment by bimalvv** [comment]
I am also facing the same issue. It is showing zero repo count and zero commits. When I debug the code, it was not going inside the for loop in GitCollectorTask class
`for (GitRepo repo : enabledRepos(collector)) {`

**Comment by satishc1** [comment]
@papithag @stein321 Refer https://github.com/capitalone/Hygieia/issues/676 . If still an issue, please reopen.
