### ISSUE TITLE
Urban Code Deployment Collector is not updating recent changes

### ISSUE THREAD

**Issue by papithag** [capitalone/Hygieia#273]
When deployment is done via Urban code process, I am not seeing recent changes in the Hygieia dashboard using udeploy-deployment-collector. 
Collector reflects only old change in the Hygieia dashboard. How to get all the recent changes in the dashboard?
I have provided Mongo Db configurations, cron value as "udeploy.cron=0 0/5 * * * * " and I am using only one deployment server which is also added in the application properties.

Is this known issue? Kindly help in resolving this.

**Comment by tabladrum** [comment]
Can you provide these information:
1. Did you build the latest collector?
2. Is your collector running?
3. Any error log from the collector.

**Comment by papithag** [comment]
Hi Tabladrum,

I am using the code which was downloaded 2 weeks before. Yes, my collector is running and I don't see any error in the log.

**Comment by tabladrum** [comment]
So you are running every 5 hrs? Sorry I always get confused with cron expression.

**Comment by papithag** [comment]
Cron is running every 5 mins
0 0/5 * * * *

**Comment by tabladrum** [comment]
@papithag can you please report on this issue?

**Comment by papithag** [comment]
@tabladrum , new code worked. Closing this issue
