### ISSUE TITLE
Need help running gulp serve

### ISSUE THREAD

**Issue by jamesjlee** [capitalone/Hygieia#277]
Hello Hygieia team,

I am trying to run the UI, but I am running into an issue with no error. Builds have succeeded, but when I run "gulp serve" or "gulp serve --local true", it never starts the 'watch' or the 'serve' process which is supposed to bring up the server on localhost:3000. Here's the output that I'm receiving after I run "gulp serve":
[output.txt](https://github.com/capitalone/Hygieia/files/92454/output.txt)

fyi: I am running on windows 8 and I am under a corporate firewall/proxy.

**Comment by javakthar** [comment]
@jamesjlee 
Hope you are doing the following steps. I had tough time setting up the dashboard. I deleted dashboarddb in mongodb and recreated them again. 
After this, 

Scaling Agile India
DevOps with Anadi Misra 


1. Build the entire application from root 
	change to directory D:\Hygieia-master 
	execute the following mvn clean install package 
	
2.change to directory D:\Hygieia-master\api
	execute java -jar target\api.jar --spring.config.name=api --spring.config.location=dashboard.properties
	api monitoring starts

3.change to directory D:\Hygieia-master\UI
	execute gulp serve
	hygieia login page opens at localhost:3000

4. change to directory D:\Hygieia-master\github-scm-collector
	execute java -jar target\github-scm-collector-1.5.0-SNAPSHOT.jar --spring.config.name=application --spring.config.location=application.properties 
	git scm collector monitoring starts

5. change to directory D:\Hygieia-master\jenkins-build-collector
	execute java -jar target\jenkins-build-collector-1.5.0-SNAPSHOT.jar --spring.config.name=application --spring.config.location=application.properties
	jenkins collector starts

6. change to directory D:\Hygieia-master\sonar-codequality-collector
	execute java -jar target\sonar-codequality-collector-1.5.0-SNAPSHOT.jar --spring.config.name=application --spring.config.location=application.properties
	Sonarqube collector starts

7. Signup on localhost:3000 

[property_files.txt](https://github.com/capitalone/Hygieia/files/97136/property_files.txt)

Regards

**Comment by jamesjlee** [comment]
Thanks for the help javakthar.

I found the issue. For some reason, the 'serve' command wasn't being run. I had to modify gulpfile and add it in the function runSequence:

gulp.task('build', function(callback) {
    runSequence('clean', ['assets', 'themes', 'fonts', 'js', 'views', 'test-data', 'serve'], 'html', callback);
});
