### ISSUE TITLE
Bower allow root

### ISSUE THREAD

**Issue by apb66** [capitalone/Hygieia#280]
When running mvn clean install package as sudo, I would get an error saying bower install cannot be run with sudo. I had to append --allow-root to the argument in /UI/pom.xml in order to get bower to install and the mvn clean install package to complete successfullly:

```xml
<execution>
    <id>bower install</id>
    <goals>
        <goal>bower</goal>
    </goals>
    <configuration>
        <arguments>install --allow-root</arguments>      <!-- added --allow-root to argument -->
    </configuration>
</execution>
```

**Comment by amitmawkin** [comment]
are you on ubuntu?

**Comment by apb66** [comment]
no, CentOS

**Comment by davenicoll** [comment]
I also had this problem. Thanks @apb66, this was the solution. Running Ubuntu 15.10.

**Comment by amitmawkin** [comment]
closing this issue thanks for the tip @apb66
