### ISSUE TITLE
Need help widgets

### ISSUE THREAD

**Issue by JulienAu** [capitalone/Hygieia#283]
Hello Hygieia team,

I am trying to put two "build" (jenkins) widgets into one Dashboard. How can i do that ? 

Thanks

**Comment by amitmawkin** [comment]
you would have to modify the templates to repeat as many widgets you want. at this moment that's the only way possible,

**Comment by JulienAu** [comment]
When i use this solution , and try to get data from API with "/api/build/?componentId=ID&max=1", I can get data from only one widget.

**Comment by vishalbisa** [comment]
Hi @amitmawkin / @JulienAu 

can you please refer to the issue #313 .

in short, we have created a 2 dropdowns for jenkins job and customized the widget to look like a table.
but we are unable to save in components collection in mongo DB, assuming that it might be a small code change as we are able to see the collector item id's in console.

Thanks,
Vishal

**Comment by JulienAu** [comment]
`    public void addCollectorItem(CollectorType collectorType, CollectorItem collectorItem) {
        // Currently only one collectorItem per collectorType is supported
         ...
    }`

" // Currently only one collectorItem per collectorType is supported"

Can you explain to me why , please ?

**Comment by vishalbisa** [comment]
Hi @JulienAu ,

you might have checked only for one collector item, but hygieia tool can support multiple collectorids.

please find below the code snippet, that needs to be added in config.js file 

`var CollectorItemIds = [];
// you can add multiple collector item id's
form.collectoritemid1
form.collectoritemid2

CollectorItemIds.push(CollectorItems1.id,CollectorItems2.id);

`
Thanks,
Vishal

**Comment by tabladrum** [comment]
@vishalbisa can you paste a screen shot? Would like to discuss if you can do a PR.

**Comment by vishalbisa** [comment]
@tabladrum 

Attached the screenshot and config.html and config.js

Thanks,

![image](https://cloud.githubusercontent.com/assets/16570454/13911092/0020b81c-ef52-11e5-9dae-bec4f088e45c.png)

[config.html.txt](https://github.com/capitalone/Hygieia/files/181702/config.html.txt)
[config.js.txt](https://github.com/capitalone/Hygieia/files/181701/config.js.txt)
[module.js.txt](https://github.com/capitalone/Hygieia/files/181703/module.js.txt)
