### ISSUE TITLE
Can we use Jira Collector against a Kanban board of multiples projects?

### ISSUE THREAD

**Issue by vram001** [capitalone/Hygieia#290]

**Comment by amp5208** [comment]
@vram001 , thank you for reaching out regarding your Jira Collector question.  Unfortunately, the Feature widget will only work for one project/scope at a time as it is currently designed.  You will need to make multiple dashboards for each "team" (project).

That being said, the recent back-end changes to the Jira feature content now allow you to configure workflow mapping for any statuses in your Jira instance, including Kanban fields.  Please look into taking advantage of this new feature.

**Comment by amp5208** [comment]
@tabladrum , This issue can be closed, as the user's direct question was answered.
