### ISSUE TITLE
Problems using Jira with Proxy

### ISSUE THREAD

**Issue by oshingc** [capitalone/Hygieia#292]
When the fields for use of proxy are not fill the collector still using the null at the fields and errors are printed
![logs](https://cloud.githubusercontent.com/assets/3100819/12648240/ea656416-c5a6-11e5-9d8e-6afee1dd981a.png)

**Comment by amp5208** [comment]
@oshingc , I see that you recently opened this issue, closed it, and reopened it:  Can I assume that you are still seeing this proxy issue with the Jira collector updates?  If so, I can submit a pull request to fix.

**Comment by oshingc** [comment]
Yes please :D

**Comment by amp5208** [comment]
Thank you for this!  Just made a pull request with a fix.  Please verify and let me know if you still see the issue form this pull:  https://github.com/capitalone/Hygieia/pull/293

**Comment by oshingc** [comment]
Ok, you're welcome.
