### ISSUE TITLE
Creation of Databases by each Project, how works?

### ISSUE THREAD

**Issue by oshingc** [capitalone/Hygieia#298]
I built Hygieia using an empty database, I started to check the population, I see the creation of the documents authentication, feature and scope are built in seconds but the documents collectors and collectors_item don't appear.
I have a question a little specific but which documents are built after run API Java Application and which after run JIRA-COLLECTOR Java Application, right now I only ran API.

Hope someone can help me.
Thanks a lot Hygieia Team.

**Comment by vishalbisa** [comment]
Hi @oshingc 

please find below information, hope this helps :

1) while you sign up for the dashboard authentication would create.
2) While you start the API the feature, scope are created.
3) once you start creating new dashboard dashboard item gets saved .
4) saving the widgets, components would created.
5) once you run the collector , collector would saved,
6) once you save any Job (JIRA-COLLECTOR ) in your case, it would create respective collections in collector items get saved in DB.

I havent ran the JIRA-COLLECTOR, but will let you know soon.

Thanks,
Vishal

**Comment by tabladrum** [comment]
@oshingc If your issue is resolved, can you close this?

**Comment by amitmawkin** [comment]
No response closing this issue
