### ISSUE TITLE
JIRA feature collector - build fails - files missing in latest version - urgent

### ISSUE THREAD

**Issue by papithag** [capitalone/Hygieia#300]
I pulled latest version from GIT and did a build, received this error - file missing. Please upload the file or help to resolve the issue.

ERROR :: 

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.569 s
[INFO] Finished at: 2016-01-30T14:53:41-05:00
[INFO] Final Memory: 38M/316M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project jira-feature-collector: Compilation failure: Compilation failure:
[ERROR] /opt/Hygieia-master/master/jira-feature-collector/src/main/java/com/capitalone/dashboard/collector/FeatureCollectorTask.java:[13,37] cannot find symbol
[ERROR] symbol:   class CoreFeatureSettings
[ERROR] location: package com.capitalone.dashboard.util
[ERROR] /opt/Hygieia-master/master/jira-feature-collector/src/main/java/com/capitalone/dashboard/collector/FeatureCollectorTask.java:[30,23] cannot find symbol
[ERROR] symbol:   class CoreFeatureSettings
[ERROR] location: class com.capitalone.dashboard.collector.FeatureCollectorTask
[ERROR] /opt/Hygieia-master/master/jira-feature-collector/src/main/java/com/capitalone/dashboard/collector/FeatureCollectorTask.java:[51,37] cannot find symbol
[ERROR] symbol:   class CoreFeatureSettings
[ERROR] location: class com.capitalone.dashboard.collector.FeatureCollectorTask
[ERROR] /opt/Hygieia-master/master/jira-feature-collector/src/main/java/com/capitalone/dashboard/client/story/StoryDataClientImpl.java:[26,38] cannot find symbol
[ERROR] symbol:   class FeatureStatus
[ERROR] location: package com.capitalone.dashboard.model
[ERROR] /opt/Hygieia-master/master/jira-feature-collector/src/main/java/com/capitalone/dashboard/client/story/StoryDataClientImpl.java:[31,37] cannot find symbol
[ERROR] symbol:   class CoreFeatureSettings
[ERROR] location: package com.capitalone.dashboard.util
[ERROR] /opt/Hygieia-master/master/jira-feature-collector/src/main/java/com/capitalone/dashboard/client/story/StoryDataClientImpl.java:[58,23] cannot find symbol
[ERROR] symbol:   class CoreFeatureSettings
[ERROR] location: class com.capitalone.dashboard.client.story.StoryDataClientImpl
[ERROR] /opt/Hygieia-master/master/jira-feature-collector/src/main/java/com/capitalone/dashboard/client/story/StoryDataClientImpl.java:[69,36] cannot find symbol
[ERROR] symbol:   class CoreFeatureSettings
[ERROR] location: class com.capitalone.dashboard.client.story.StoryDataClientImpl

**Comment by papithag** [comment]
Files are missing in latest version

class CoreFeatureSettings in package com.capitalone.dashboard.util
class FeatureStatus in package com.capitalone.dashboard.model

Build failure due to missing of these files

**Comment by apb66** [comment]
Same issue for me

**Comment by tabladrum** [comment]
Did you do build the JIRA collector separately? If yes, can you do ``mvn clean install`` on core project first?

**Comment by apb66** [comment]
@tabladrum what you suggested works, thanks! Now getting stuck on another issue - Fixed based on proxy issue #292 #293

**Comment by amp5208** [comment]
@apb66 , if you are having difficulty running the new versions of the Jira/VersionOne feature collector, please let me know.  The pull request fix that you are referring to allows the use of no proxy, unauthenticated proxy, and an authenticated proxy.  Also, there are additional properties required to be set at runtime with the Jira collector, which can be found below (from the README.md):

<pre>
# In Jira, general IssueType IDs are associated to various "issue"
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide the name value reference to your instance's IssueType for
# the lowest level of Issues (e.g., "user story") specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType Name
# listings via the following URI:
# https://[your-jira-domain-name]/rest/api/2/issuetype/.  It is listed as
# attribute "name" in the JSON response.
feature.jiraIssueTypeId=Story
# In Jira, your instance will have its own custom field created for "sprint" or "timebox" details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name <em>com.atlassian.greenhopper.service.sprint.Sprint</em>;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraSprintDataFieldName=customfield_10007
# In Jira, your instance will have its own custom field created for "super story" or "epic" back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (e.g., epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraEpicIdFieldName=customfield_10400

#Core Artifacts
# These arrays of status mappings must be completed in order for custom source system statuses to be providable by
# Hygieia.  Currently, Hygieia only maps to the following 3 status mappings:  to do, doing, and done.  You can find
# all available issue status mappings by going to your instance's version of the following API call:
# http://fake.jira.com/rest/api/2/status/.  Your statuses are listed in the JSON response as "name."
feature.todoStatuses[0]=
feature.doingStatuses[0]=
feature.doneStatuses[0]=
</pre>

**Comment by papithag** [comment]
@amp5208 , 
I was setting 50 as pagesize in property file as suggested to fix the time out exception.
Though property file value is 50, it carries 1000 in the code and provides time out exception

**Comment by amp5208** [comment]
@apb66 and @papithag :  The fixes have been re-merged to master as of https://github.com/capitalone/Hygieia/pull/322 pull request.  Please fetch from upstream and rebuild/deploy to verify that the pageSize property settings are included again.

**Comment by amp5208** [comment]
@tabladrum , This issue can be closed, as it was resolved in the merge mentioned above.

**Comment by tabladrum** [comment]
@papithag can you confirm and/or close this issue?

**Comment by papithag** [comment]
@tabladrum , Working fine, closing the issue
