### ISSUE TITLE
'View in Hudson' link does not work with collector in a container

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#302]
When running the collector in a container localhost is mapped to http://10.0.2.2 (this is how docker handles the special case of local host it it is natted to that address).

So the URLS from jerkins have to be adjusted to work in your locally browser by changing 10.0.2.2 back to localhost.

Note: the 'view test job' link in the jerkins-cucumber collector works.

![screenshot 2016-02-01 13 27 42](https://cloud.githubusercontent.com/assets/14372687/12731909/fc0485dc-c8e7-11e5-90f9-0078992ad3e0.png)
![screenshot 2016-02-01 13 27 54](https://cloud.githubusercontent.com/assets/14372687/12731913/ff86e876-c8e7-11e5-87b1-f173cf7a8422.png)

**Comment by vishalbisa** [comment]
Hi @jimzucker 

Have you tried adding an entry in host file in etc. for localhost mapping to 10.0.2.2
just a trail :)

Thanks,
Vishal

**Comment by jimzucker** [comment]
If I do that locally on my mac they will work. I have to fix the integration to map localhost->10.0.2.2, I have dont it other places.

**Comment by vishalbisa** [comment]
locally it worked :)

I haven't went through this scenario , may be the developers might have any clue on it.

**Comment by jimzucker** [comment]
the pulls to trunk and other merges lost some files, I am going to go through and make a fully working branch,then I will fix this next week.


On Feb 7, 2016, at 11:40 AM, vishalbisa <notifications@github.com<mailto:notifications@github.com>> wrote:


locally it worked :)

I haven't went through this scenario , may be the developers might have any clue on it.

**Comment by jimzucker** [comment]
I know whet is happenig, jenkins has hardcoded localhost in the urls it creates. I fixed it everywhere elae to mapp this to 10.0.2.2, seems i missed a place (you can see where i did this if you egrep for localhost or 10.0.2.2 in the collectors.

**Comment by tabladrum** [comment]
This is to do with jenkins configuration (jenkins -> manage jenkins -> configure jenkins). 
@jimzucker should we close this?

**Comment by jimzucker** [comment]
@tabladrum you an assign this to me I will retest, I think I have to make a change for it.

**Comment by tabladrum** [comment]
@jimzucker Somehow I cant assign it you. Let me know when you are done testing.

**Comment by jimzucker** [comment]
I just tested the use case on the current master build and it works OK.
