### ISSUE TITLE
'View in Hudson' link should be renamed to View in Jenkins

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#303]
Just for housekeeping we should rename the link.

**Comment by tabladrum** [comment]
Yes!

**Comment by vishalbisa** [comment]
Hi @jimzucker 

As a workaround you can modify the links in details.html file in Build widget to rename the link as View in Jenkins.

Thanks,
Vishal

**Comment by tabladrum** [comment]
the name actually comes from the collector name. Will change the collector name in the near future.

**Comment by vishalbisa** [comment]
Hi @tabladrum ,

Should we change it in the HudsonCollector.java file ?

```
public static HudsonCollector prototype(List<String> buildServers) {
        HudsonCollector protoType = new HudsonCollector();
        protoType.setName("Hudson"); // should we modify as Jenkins instead of hudson ?
        protoType.setCollectorType(CollectorType.Build);
        protoType.setOnline(true);
        protoType.setEnabled(true);
        protoType.getBuildServers().addAll(buildServers);
        return protoType;
```

Thanks,

**Comment by satishc1** [comment]
@jimzucker refer to https://github.com/capitalone/Hygieia/issues/784
