### ISSUE TITLE
Jira feature collector pageSize property ignored

### ISSUE THREAD

**Issue by xeon22** [capitalone/Hygieia#309]
When the property is set, it is essentially ignored and the default of 1000 is used.

**Comment by papithag** [comment]
same while I was executing as well... though I changed to 50 in properties file, it takes 1000 by default and hence timeout error

**Comment by amp5208** [comment]
@xeon22 & @papithag :  Thank you for informing me of this.  I will look into your issue and push a fix as soon as possible.

**Comment by amp5208** [comment]
@xeon22 and @papithag :  The fixes have been re-merged to master as of https://github.com/capitalone/Hygieia/pull/322 pull request.  Please fetch from upstream and rebuild/deploy to verify that the pageSize property settings are included again.

**Comment by amp5208** [comment]
@tabladrum , This issue was fixed in the above-mentioned pull request.  Please close if @xeon22 and @papithag have no concerns.

**Comment by papithag** [comment]
@tabladrum , @amp5208 , I have no issues, fix is working fine
