### ISSUE TITLE
jira-feature-collector: Allow for a custom timeout for large datasets

### ISSUE THREAD

**Issue by xeon22** [capitalone/Hygieia#310]
When the pageSize default is exceeded, the resulting payload can take longer than the default socket timeout of 20000ms.  Adjusting this default would help with the larger datasets coming back from jira.

The result of the default is a timeout exception:

`
No result was available from Jira unexpectedly - defaulting to blank response. The reason for this fault is the following:java.net.SocketTimeoutException
`

**Comment by amp5208** [comment]
@xeon22 , Actually, this would obviously be preferable. However, the collector is now using the <a href="https://marketplace.atlassian.com/plugins/com.atlassian.jira.jira-rest-java-client/server/overview" target="about:blank">JRJC</a>.  To my knowledge, the newest version of the JRJC does not have a timeout setting override.  If you know of an override option for this, outside of overriding the entire class, please let me know, and I will gladly update.

**Comment by amp5208** [comment]
@tabladrum , As mentioned in the above comment, socket timeout overrides are not an option for the Jira collector's JRJC.  However, using the default pageSize settings, implemented in a previous merge, will resolve this issue.  I recommend closing this issue, pending any further questions from @xeon22 .
