### ISSUE TITLE
Changes lost in merges from b93e6dd - Merge pull request #244 from jimzucker/collectors (11 days ago) jdamick

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#315]
If found we have lost changes in the merges to master after b93e6dd.

**git diff --summary b93e6dd..HEAD**
<img width="982" alt="screenshot 2016-02-08 08 12 47" src="https://cloud.githubusercontent.com/assets/14372687/12891488/14ab2d0c-ce3d-11e5-8e6a-2ff002d9264f.png">

Can you review how to correct master, I think the merges after this one have to be rolled back and redone.
<img width="1071" alt="screenshot 2016-02-08 08 12 27" src="https://cloud.githubusercontent.com/assets/14372687/12891483/0c672b1e-ce3d-11e5-868a-a6f61442719a.png">

**Comment by tabladrum** [comment]
Let me check.

**Comment by tabladrum** [comment]
Looks like this one was the bad one: 
https://github.com/capitalone/Hygieia/pull/293

**Comment by tabladrum** [comment]
@jimzucker can you verify if I revert #293 if your changes are back? I think they are. Wanted a second eye.

**Comment by jimzucker** [comment]
Yes this is it:
*   4bf717f - (HEAD -> master, upstream/master, origin/master, origin/HEAD) Merge pull request #293 from amp5208/master (6 days ago) Tapabrata "Topo" Pal
|\
| *   b497082 - Merge remote-tracking branch 'upstream/master' (7 days ago) amp5208

it is actually b497082 that deleted the files..

**Comment by tabladrum** [comment]
Done. Can you check?

**Comment by jimzucker** [comment]
I just did a diff against my feature branch and looks OK, the diff is what I expect the files I changed. FYI  I am going to rebase and submit a pull request to put my changes back.  I have created containers for more of the collectors and also fixed up the pom files so we can do a man docker:build from the root and also fixed sonar so  svn sonar:sonar works correctly.

➜  Hygieia git:(mergecollector) ✗ git diff --name-status HEAD..upstream/master
[cid:E786C1E4-B76D-402D-A214-2AC69D43C898]

On Feb 9, 2016, at 6:09 AM, tabladrum <notifications@github.com<mailto:notifications@github.com>> wrote:


Done. Can you check?

**Comment by jimzucker** [comment]
Looks OK now.
