### ISSUE TITLE
Go.cd Connector development information

### ISSUE THREAD

**Issue by aleitner** [capitalone/Hygieia#320]
Hey,

We are using your Hygieia dashboard with various collectors for obtaining useful metrics here at Equifax, and we decided that it would be useful to collect information from [GO.cd](https://www.go.cd/). I do not see any information on writing a custom connector in your documentation. 

What do I need to do to get a collector jar for taking information from Go, putting that information into mongo, and displaying this information on the UI?

Any and all help will be appreciated! Also Vijayaraj says hi.

Alexander Leitner

**Comment by tabladrum** [comment]
We are about to release Hygieia 2.0. With that we have a set of ingest api's that you can use to push data into Hygieia. We are going to release a Jenkins Hygieia Plugin along with that too.

**Comment by aleitner** [comment]
Any chance there will be documentation for writing a collector?

**Comment by tabladrum** [comment]
I think that the best way would be to copy an existing collector (such as Jenkins collector) and modify it. The main parts are in each collector module's collector package.

**Comment by tabladrum** [comment]
@aleitner let me know if you need further help.

**Comment by camechis** [comment]
I would be really interested in this

**Comment by elangesk** [comment]
@aleitner 

 We would like to implement Go.cd collector and put collector data in to mongo db and display information in UI.  If you had implement any thing on Go.Cd and ready to share, it will help to us.

Thanks in advance.

**Comment by satishc1** [comment]
@aleitner @elangesk Please refer https://github.com/capitalone/Hygieia/issues/1037 for info on how to create custom collectors.
