### ISSUE TITLE
Need help running JIRA collector

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#326]
Hi,

I have been trying to get the JIRA connector to work but I can't figure out why I get a 401 error.

Error:  **RestClientException{statusCode=Optional.of(401), errorCollections=[]} **
I verified the URL and Id/Password being pasted are correct in the browser. (FYI I am using the cloud versions of JIRA)

Can you give me a hint/pointer on how to debug this?

	public List<BasicProject> getJiraTeams() {
		Iterable<BasicProject> jiraRawRs = null;
		List<BasicProject> issues = new ArrayList<BasicProject>();
		if (client != null) {
			Promise<Iterable<BasicProject>> promisedRs = client.getProjectClient().getAllProjects(); 
			try {
//this is where i fail with 401 error
				jiraRawRs = promisedRs.claim();

				if (jiraRawRs != null) {
					issues = Lists.newArrayList(jiraRawRs);
				} else {
					issues = new ArrayList<BasicProject>();
				}
			} catch (Exception e) {
				issues = new ArrayList<BasicProject>();
				LOGGER.warn("No result was available from Jira unexpectedly - defaulting to blank response. The reason for this fault is the following:"
						+ e.getCause());
			}

**Comment by softwareklinic** [comment]
Using the clear text password for api key or the actual ali key



Regards,
Keyur

On Feb 10, 2016, at 7:25 PM, Jim Zucker <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I have been trying to get the JIRA connector to work but I can't figure out why I get a 401 error.

Error: *RestClientException{statusCode=Optional.of(401), errorCollections=[]} *
I verified the URL and Id/Password being pasted are correct in the browser. (FYI I am using the cloud versions of JIRA)

Can you give me a hint/pointer on how to debug this?

public List<BasicProject> getJiraTeams() {
    Iterable<BasicProject> jiraRawRs = null;
    List<BasicProject> issues = new ArrayList<BasicProject>();
    if (client != null) {


--> Promise> promisedRs = client.getProjectClient().getAllProjects();
try {
jiraRawRs = promisedRs.claim();
if (jiraRawRs != null) {
issues = Lists.newArrayList(jiraRawRs);
} else {
issues = new ArrayList();
}
} catch (Exception e) {
issues = new ArrayList();
LOGGER.warn("No result was available from Jira unexpectedly - defaulting to blank response. The reason for this fault is the following:"
+ e.getCause());
}

**Comment by jimzucker** [comment]
Hmm, I am not sure where to specify the api key, here is my properties file from the test instance of JIRA I created.. the login is jim:password

Sorry to be dense, can you give me the step by step to get this up and running?


➜  Hygieia git:(java18) ✗ cat /tmp/hygieia-jira-feature-collector.properties
#Database Name
database=dashboard

#Database HostName - default is localhost
dbhost=172.17.0.4

#Database Port - default is 27017
dbport=27017


#Database Username - default is blank
dbusername=db

#Database Password - default is blank
dbpassword=dbpass

#Collector schedule (required)
feature.cron=0 * * * * *

#Page size for data calls (Jira maxes at 1000)
feature.pageSize=1000

#In-built folder housing prepared REST queries (required)
feature.queryFolder=jiraapi-queries

#Jira API Query file names (String template requires the files to have .st extension) (required)
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo

#Jira Connection Details
feature.jiraProxyUrl=
feature.jiraProxyPort=

# Trending Query:  Number of days in a sprint (not-required)
feature.sprintDays=60

# Trending Query:  Length of sprint week (not-required)
feature.sprintEndPrior=7

#Scheduled Job prior minutes to recover data created during execution time (usually, 2 minutes is enough)
feature.scheduledPriorMin=2

#Delta change date that modulates the collector item task - should be about as far back as possible, in ISO format (required)
feature.deltaCollectorItemStartDate=2008-01-01T00:00:00.000000

#Jira Connection Details
feature.jiraBaseUrl=http://192.168.99.100:9200/
feature.jiraQueryEndpoint=rest/api/2/

#64-bit encoded credentials with the pattern username:password
#on a mac you con create them with : echo "username:password" | base64
#reference:  https://www.base64decode.org/
feature.jiraCredentials=amltOnBhc3N3b3JkCg==

#OAuth2.0 token credentials (currently not supported in this version)
feature.jiraOauthAuthtoken=sdfghjkl==
feature.jiraOauthRefreshtoken=sdfagheh==
feature.jiraOauthRedirecturi=uri.this.is.test:uri
feature.jiraOauthExpiretime=234567890987

#Start dates from which to begin collector data, if no other data is present - usually, a month back is appropriate (required)
feature.deltaStartDate=2015-03-01T00:00:00.000000
feature.masterStartDate=2008-01-01T00:00:00.000000

# In Jira, general IssueType IDs are associated to various "issue"
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a numerical ID reference to your instance's IssueType for
# the lowest level of Issues (e.g., "user story") specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType ID
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
feature.jiraIssueTypeId=7

# In Jira, your instance will have its own custom field created for "sprint" or "timebox" details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name com.atlassian.greenhopper.service.sprint.Sprint;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraSprintDataFieldName=customfield_10007

# In Jira, your instance will have its own custom field created for "super story" or "epic" back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (e.g., epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraEpicIdFieldName=customfield_10400

**Comment by softwareklinic** [comment]
Sure will check in few and get back



Regards,
Keyur

On Feb 10, 2016, at 9:18 PM, Jim Zucker <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmm, I am not sure where to specify the api key, here is my properties file from the test instance of JIRA I created.. the login is jim:password

Sorry to be dense, can you give me the step by step to get this up and running?

➜ Hygieia git:(java18) ✗ cat /tmp/hygieia-jira-feature-collector.properties
#Database Name
database=dashboard

#Database HostName - default is localhost
dbhost=172.17.0.4

#Database Port - default is 27017
dbport=27017

#Database Username - default is blank
dbusername=db

#Database Password - default is blank
dbpassword=dbpass

#Collector schedule (required)
feature.cron=0 * * * * *

#Page size for data calls (Jira maxes at 1000)
feature.pageSize=1000

#In-built folder housing prepared REST queries (required)
feature.queryFolder=jiraapi-queries

#Jira API Query file names (String template requires the files to have .st extension) (required)
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo

#Jira Connection Details
feature.jiraProxyUrl=
feature.jiraProxyPort=

Trending Query: Number of days in a sprint (not-required)

feature.sprintDays=60

Trending Query: Length of sprint week (not-required)

feature.sprintEndPrior=7

#Scheduled Job prior minutes to recover data created during execution time (usually, 2 minutes is enough)
feature.scheduledPriorMin=2

#Delta change date that modulates the collector item task - should be about as far back as possible, in ISO format (required)
feature.deltaCollectorItemStartDate=2008-01-01T00:00:00.000000

#Jira Connection Details
feature.jiraBaseUrl=http://192.168.99.100:9200/
feature.jiraQueryEndpoint=rest/api/2/

#64<https://github.com/capitalone/Hygieia/pull/64>-bit encoded credentials with the pattern username:password
#on a mac you con create them with : echo "username:password" | base64
#reference: https://www.base64decode.org/
feature.jiraCredentials=amltOnBhc3N3b3JkCg==

#OAuth2.0 token credentials (currently not supported in this version)
feature.jiraOauthAuthtoken=sdfghjkl==
feature.jiraOauthRefreshtoken=sdfagheh==
feature.jiraOauthRedirecturi=uri.this.is.test:uri
feature.jiraOauthExpiretime=234567890987

#Start dates from which to begin collector data, if no other data is present - usually, a month back is appropriate (required)
feature.deltaStartDate=2015-03-01T00:00:00.000000
feature.masterStartDate=2008-01-01T00:00:00.000000

In Jira, general IssueType IDs are associated to various "issue"
attributes. However, there is one attribute which this collector's
queries rely on that change between different instantiations of Jira.
Please provide a numerical ID reference to your instance's IssueType for
the lowest level of Issues (e.g., "user story") specific to your Jira
instance. Note: You can retrieve your instance's IssueType ID
listings via the following URI: https://[your-jira-domain-name]/rest/api/2/issuetype/

feature.jiraIssueTypeId=7

In Jira, your instance will have its own custom field created for "sprint" or "timebox" details,
which includes a list of information. This field allows you to specify that data field for your
instance of Jira. Note: You can retrieve your instance's sprint data field name
via the following URI, and look for a package name com.atlassian.greenhopper.service.sprint.Sprint;
your custom field name describes the values in this field:
https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]

feature.jiraSprintDataFieldName=customfield_10007

In Jira, your instance will have its own custom field created for "super story" or "epic" back-end ID,
which includes a list of information. This field allows you to specify that data field for your instance
of Jira. Note: You can retrieve your instance's epic ID field name via the following URI where your
queried user story issue has a super issue (e.g., epic) tied to it; your custom field name describes the
epic value you expect to see, and is the only field that does this for a given issue:
https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]

feature.jiraEpicIdFieldName=customfield_10400

**Comment by jimzucker** [comment]
@softwareklinic - any update?

**Comment by jimzucker** [comment]
HI, can I get some help wth this?    I have not been able to get JIRA to work.

Here are the current details:
1. This is how I created JIRA: 
docker create --restart=no --name "jira-server"  --publish "9200:8080" --env "CATALINA_OPTS= -Xms256m -Xmx512m" cptactionhank/atlassian-jira-software:latest

2. I updated my config file based on the log from the lira instance:
feature.jiraIssueTypeId=10001
feature.jiraSprintDataFieldName=customfield_10005
feature.jiraEpicIdFieldName=customfield_10003

3. This is what I get in my log of the Hygiena collector
2016-03-16 05:17:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2016-03-16 05:17:00,015 INFO  c.c.d.collector.FeatureCollectorTask - Starting Feature collection...
2016-03-16 05:17:00,026 INFO  c.c.d.c.team.TeamDataClientSetupImpl - Beginning collection of team data at Wed Mar 16 05:17:00 UTC 2016
2016-03-16 05:17:00,062 WARN  c.c.d.d.jira.JiraDataFactoryImpl - No result was available from Jira unexpectedly - defaulting to blank response. The reason for this fault is the following:RestClientException{statusCode=Optional.of(401), errorCollections=[]}
2016-03-16 05:17:00,062 ERROR c.c.d.c.team.TeamDataClientSetupImpl - The response from Jira was blank or non existant - please check your property configurations
2016-03-16 05:17:00,065 INFO  c.c.d.c.team.TeamDataClientSetupImpl - Process took :0.039186197 seconds to update
2016-03-16 05:17:00,069 INFO  c.c.d.c.p.ProjectDataClientSetupImpl - Beginning collection of project data at Wed Mar 16 05:17:00 UTC 2016
2016-03-16 05:17:00,099 WARN  c.c.d.d.jira.JiraDataFactoryImpl - No result was available from Jira unexpectedly - defaulting to blank response. The reason for this fault is the following:RestClientException{statusCode=Optional.of(401), errorCollections=[]}
2016-03-16 05:17:00,099 ERROR c.c.d.c.p.ProjectDataClientSetupImpl - The response from Jira was blank or non existant - please check your property configurations
2016-03-16 05:17:00,102 INFO  c.c.d.c.p.ProjectDataClientSetupImpl - Process took :0.032059929 seconds to update
2016-03-16 05:17:00,107 INFO  c.c.d.c.s.FeatureDataClientSetupImpl - Beginning collection of feature data at Wed Mar 16 05:17:00 UTC 2016
2016-03-16 05:17:00,134 WARN  c.c.d.d.jira.JiraDataFactoryImpl - No result was available from Jira unexpectedly - defaulting to blank response. The reason for this fault is the following:RestClientException{statusCode=Optional.of(401), errorCollections=[]}
2016-03-16 05:17:00,136 INFO  c.c.d.c.s.FeatureDataClientSetupImpl - Process took :0.028106076 seconds to update
2016-03-16 05:17:00,136 INFO  c.c.d.collector.FeatureCollectorTask - Feature Data Collection Finished

**Comment by tabladrum** [comment]
@amp5208 can you look at this?

**Comment by amp5208** [comment]
@jimzucker , Thank you for reaching out regarding your Jira collector question.  Currently, the implementation of JiraFeatureCollector only accepts a base64-encoded basic authentication string in the following format:  <strong>username:password</strong>.  This should be entered at the following property:  <code>feature.jiraCredentials=dXNlcm5hbWU6cGFzc3dvcmQK</code>

Currently, Jira authentication tokens are not accepted.  Please let me know if you have any additional questions.

**Comment by jimzucker** [comment]
@amp5208 i am using that format and i login but have not been able to figure out how to get this to work. I think upu are saying something is wrong with my properties?

**Comment by amp5208** [comment]
Yes:  You need to update your property files to be more like what is described at this current/open issue:  https://github.com/capitalone/Hygieia/issues/276#issuecomment-195399194

**Comment by amp5208** [comment]
@jimzucker , please let me know if you have resolved your issue.

**Comment by jimzucker** [comment]
@amp5208  yes I am still having an issue, I will document tomorrow exactly where it is occurring.

**Comment by amp5208** [comment]
@jimzucker , please provide details on your connectivity issue.

**Comment by tonyvilliams** [comment]
Ran into same issue.. Please advise if any progress...

**Comment by amp5208** [comment]
@tonyvilliams , Sorry to hear you are also having this issue.. @jimzucker or @tonyvilliams :  Just to validate, are you able to run the collectors _without_ using Docker? 😕   e.g.:

```bash
java -jar jira-feature-collector.jar --spring.config.name=jira-feature-collector --spring.config.location=$PROPERTY_PATH/jira-feature-collector.properties
```

If you have already validated the following, I start to think this is related to Docker:

 - Jira credentials are accurate and have permissions to read from all projects
 - Jira implementation is within a non-restricted region to your Hygieia implementation
 - Jira public certificate has been added to the Java keystore
 - The following properties have been configured based on your Jira implementation:

```bash
feature.jiraIssueTypeId=Story
feature.jiraSprintDataFieldName=customfield_10000
feature.jiraEpicIdFieldName=customfield_10001
```

**Comment by jimzucker** [comment]
@amp5208 I am testing now in Eclipse, so I think that takes docker out of the picture.  Reviewing today, it looks like my base64 creation of my id and password is adding a '\n' !  I am going to add a bit of code to trim this to make it more resilient..

**Comment by amp5208** [comment]
@jimzucker , Thank you for discovering this:  And also thank you in advance for the contribution 👍 !  @tabladrum :  Please review @jimzucker's contribution once it comes it; I expect a one or two line change for the string trimming.

@jimzucker :  Other than this, have we answered your configuration question?  Can this issue be closed after your impending code contribution?

**Comment by jimzucker** [comment]
@amp5208 lets keep this open until I get the darn thing running..

**Comment by jimzucker** [comment]
@amp5208 the /n was a problem but I fixed that and I still get a 401 error, line 249 gets the exceptions, any hints on how to debug this?
![screenshot 2016-05-18 13 04 48](https://cloud.githubusercontent.com/assets/14372687/15373213/4daecd92-1cf9-11e6-8e56-bb3ed9dfda2d.png)

**Comment by amp5208** [comment]
hmm... that line of code is resolving your authorization header and request body against Jira's API using the Jira SDK, "claiming" the response, treating it almost like a promise.  The only thing that would cause an HTTP 401: Unauthorized response here would be if your credentials are still not being mapped properly.  Have you tried debugging that ```client``` variable to expose your message header information?

I believe the problem is how you are establishing your authentication (i.e., what is being transformed and read from your property config), or your Jira implementation does not allow basic authentication (username:password).  Have you verified your Jira authentication capabilities with your Jira admin?

**Comment by jimzucker** [comment]
@amp5208 I stepped into the factory.createWithBasicHttpAuthentication to verify my credentials are OK and the URL is the correct https url..  I think I need a way to verify credentials are OK in the contractor JiraDataFactoryImpl so that we can give a clear error at that time.  I dont know the JIRA apis, do you have a suggestion ?

**Comment by jimzucker** [comment]
@amp5208 I saw a thread about installing the JIRA cert in the java keystore, that is what I think is wrong, researching it now...

**Comment by jimzucker** [comment]
@amp5208 no luck, I put this code in the constructor to ensure ids are correct, I think it has to do with certs or something, I haven't been able to figure it out yet.. any pointers?

jiraServerUri = new URI("https://stratengllc.atlassian.net");
client = factory.createWithBasicHttpAuthentication(jiraServerUri, "xxxx", "xxx");

**Comment by amp5208** [comment]
Not including the Jira certificate would cause problems, but not this one; I would expect it to throw x509 or PKIX Certificate errors at the Java runtime level.  You will need that installed to your Java keystore regardless, however.

Just to check my theory, can you try and cURL and authenticated Jira API request to your Jira implementation from your computer?  I believe that your command should ultimately look like this:

```bash
# 1) This will give the HTTP code response back; it will not return the actual message:
curl --cacert /path/to/your/jira/cert.pem -I -X GET --header "Content-Type: application/json" https://$JIRA_USER:$JIRA_PASS@stratengllc.atlassian.net/rest/api/2/issue/VALIDSTORY-12

# You may need to include the following parameter flag if your Jira certificate is signed using TLS:
--tlsv1

# 2) Then, try and run this version of the cURL command; let me know which one worked and which one did not:
curl --cacert /path/to/your/jira/cert.pem -I -X GET --header "Authorization: Basic [base64encoded_user:pass]" --header "Content-Type: application/json" https://stratengllc.atlassian.net/rest/api/2/issue/VALIDSTORY-12

# Note:  You may also have to included your proxy authorization header explicitly if behind an auth-proxy.  Here is the parameter syntax to add to the above calls:
--header "Proxy-Authorization: Basic [base64encoded_user:pass]"
```

It is worth mentioning that I also had trouble authenticating using the second option which uses an explicit authorization header.  The issue was related to Mac's implementation of base64, which seems to add something invisible to the ASCII result.  I would suggest re-validating your base64 _not_ use the base64 encoder on Mac.

If that gets denied for the same HTTP 401 error you were seeing in Hygieia, this is a large problem of your implementation of Jira not allowing for basic authentication.  You would ultimately have 2 options at that point:  1) Contact your Jira admin and ask them to enable _nosso_ option of authentication; 2) Update the JiraFeatureCollector to use token-based authentication (token or OAuth2.0).  The latter may be the only option.  Please let me know how this goes for you.

**Comment by jimzucker** [comment]
Thanks this strategy worked.  The real issue was I was passing emailaddress:password, seems the API requires you use the real userid, email does not work!


I will update the file with a good error message and submit it…


On May 19, 2016, at 9:36 AM, Arnold Pelka <notifications@github.com<mailto:notifications@github.com>> wrote:


Not including the Jira certificate would cause problems, but not this one; I would expect it to throw x509 or PKIX Certificate errors at the Java runtime level. You will need that installed to your Java keystore regardless, however.

Just to check my theory, can you try and cURL and authenticated Jira API request to your Jira implementation from your computer? I believe that your command should ultimately look like this:

# 1) This will give the HTTP code response back; it will not return the actual message:
curl --cacert /path/to/your/jira/cert.pem -I -X GET --header "Content-Type: application/json" https://$JIRA_USER:$JIRA_PASS@stratengllc.atlassian.net/rest/api/2/issue/VALIDSTORY-12<http://stratengllc.atlassian.net/rest/api/2/issue/VALIDSTORY-12>

# You may need to include the following parameter flag if your Jira certificate is signed using TLS:
--tlsv1

# 2) Then, try and run this version of the cURL command; let me know which one worked and which one did not:
curl --cacert /path/to/your/jira/cert.pem -I -X GET --header "Authorization: Basic [base64encoded_user:pass]" --header "Content-Type: application/json" https://stratengllc.atlassian.net/rest/api/2/issue/VALIDSTORY-12

# Note:  You may also have to included your proxy authorization header explicitly if behind an auth-proxy.  Here is the parameter syntax to add to the above calls:
--header "Proxy-Authorization: Basic [base64encoded_user:pass]"

It is worth mentioning that I also had trouble authenticating using the second option which uses an explicit authorization header. The issue was related to Mac's implementation of base64, which seems to add something invisible to the ASCII result. I would suggest re-validating your base64 not use the base64 encoder on Mac.

If that gets denied for the same HTTP 401 error you were seeing in Hygieia, this is a large problem of your implementation of Jira not allowing for basic authentication. You would ultimately have 2 options at that point: 1) Contact your Jira admin and ask them to enable nosso option of authentication; 2) Update the JiraFeatureCollector to use token-based authentication (token or OAuth2.0). The latter may be the only option. Please let me know how this goes for you.

**Comment by jimzucker** [comment]
see pull request #581

**Comment by amp5208** [comment]
Reviewing PR now.  Thank you for your patience and contribution!!

**Comment by amp5208** [comment]
For those that come here after the merged fix is implemented, it is important to note that the "ghost" ```\n``` return carriage that is included in a base64 encoded string on a Mac is avoidable easily by using the Mac implementation of ```echo``` correctly.  Instead of the following command:

```bash
echo username:password | base64
```

... Use this command:

```bash
echo -n username:password | base64
```

The ```-n``` option explicitly tells the Mac implementation of echo to not print the trailing new line character.

**Comment by shabna96** [comment]
Hi I am getting below error while trying to get projects data:
Jira Api Plugin : 3.0.0
Jira version:  7.3
The issue might be due to missing value like Url or Description of a project but is there any fix for this or workaround?It would be great if you can help with this.
 
RestClientException{statusCode=Optional.absent(), errorCollections=[]}
com.atlassian.jira.rest.client.internal.async.DelegatingPromise.claim(DelegatingPromise.java:47)
com.capitalone.dashboard.client.DefaultJiraClient.getProjects(DefaultJiraClient.java:152)
com.capitalone.dashboard.client.project.ProjectDataClientImpl.updateProjectInformation(ProjectDataClientImpl.java:58)
com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:113)
com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28)
com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63)
org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
java.util.concurrent.FutureTask.run(Unknown Source)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
java.lang.Thread.run(Unknown Source)
