### ISSUE TITLE
Build error for Hygieia project

### ISSUE THREAD

**Issue by BeenaMP** [capitalone/Hygieia#327]
I have done a mvn clean install package for Hygieia project and got the below error:Please help.

Downloading: https://repo.maven.apache.org/maven2/com/spotify/docker-maven-plugin/0.4.0/docker-maven-plugin-0.4.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] com.capitalone.dashboard:Hygieia ................... FAILURE [  1.335 s]
[INFO] com.capitalone.dashboard:core ...................... SKIPPED
[INFO] com.capitalone.dashboard:api ....................... SKIPPED
[INFO] com.capitalone.dashboard:jenkins-build-collector ... SKIPPED
[INFO] com.capitalone.dashboard:sonar-codequality-collector SKIPPED
[INFO] com.capitalone.dashboard:subversion-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:github-scm-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:versionone-feature-collector SKIPPED
[INFO] com.capitalone.dashboard:udeploy-deployment-collector SKIPPED
[INFO] com.capitalone.dashboard:jira-feature-collector .... SKIPPED
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SKIPPED
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SKIPPED
[INFO] com.capitalone.dashboard:UI ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.837 s
[INFO] Finished at: 2016-02-12T17:32:08+05:30
[INFO] Final Memory: 6M/17M

[ERROR] Plugin com.spotify:docker-maven-plugin:0.4.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for com.spotify:docker-maven-plu
ar:0.4.0: Could not transfer artifact com.spotify:docker-maven-plugin:pom:0.4.0 from/to central (https://repo.maven.apache.org/maven2): sun.security.validator.ValidatorEx
on: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
org.apache.maven.plugin.PluginResolutionException: Plugin com.spotify:docker-maven-plugin:0.4.0 or one of its dependencies could not be resolved: Failed to read artifact
iptor for com.spotify:docker-maven-plugin:jar:0.4.0

**Comment by jimzucker** [comment]
@BeenaMP - I believe the error is related to your build env,potentially your JAVA install.  The error is a connectivity issue between maven and the repo to download the plugins.  If you google "sun.security.validator.ValidatorEx
on: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"  you will find a bunch of hits related to this error, you will have to sift through them to fix your env.

**Comment by BeenaMP** [comment]
Thanks Jim.I succeeded from that steps.
