### ISSUE TITLE
Error after pull #329 - bower install fails

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#330]
I tried building after the #329 was merged and I get an error, I am trying to research it..

[INFO] --- frontend-maven-plugin:0.0.27:bower (bower install) @ UI ---
[INFO] Found proxies: []
[INFO] Running 'bower install' in /Users/jaz/work/Hygieia/UI
[INFO] bower bootstrap-sweetalert#~0.4.5           cached git://github.com/lipis/bootstrap-sweetalert.git#0.4.5
[INFO] bower bootstrap-sweetalert#~0.4.5         validate 0.4.5 against git://github.com/lipis/bootstrap-sweetalert.git#~0.4.5
[INFO] bower regression-js#~1.3.0                  cached git://github.com/Tom-Alexander/regression-js.git#1.3.0
[INFO] bower regression-js#~1.3.0                validate 1.3.0 against git://github.com/Tom-Alexander/regression-js.git#~1.3.0
[INFO] bower ng-sortable#~1.3.2                    cached git://github.com/a5hik/ng-sortable.git#1.3.2
[INFO] bower ng-sortable#~1.3.2                  validate 1.3.2 against git://github.com/a5hik/ng-sortable.git#~1.3.2
[INFO] bower dexie#~1.2.0                          cached git://github.com/dfahlander/dexie.js.git#1.2.0
[INFO] bower dexie#~1.2.0                        validate 1.2.0 against git://github.com/dfahlander/dexie.js.git#~1.2.0
[INFO] bower operative#~0.4.4                      cached git://github.com/padolsey/operative.git#0.4.4
[INFO] bower operative#~0.4.4                    validate 0.4.4 against git://github.com/padolsey/operative.git#~0.4.4
[INFO] bower angular-chartist.js#~3.3.13           cached git://github.com/paradox41/angular-chartist.js.git#3.3.13
[INFO] bower angular-chartist.js#~3.3.13         validate 3.3.13 against git://github.com/paradox41/angular-chartist.js.git#~3.3.13
[INFO] bower chartist#~0.4.3                       cached git://github.com/gionkunz/chartist-js.git#0.4.4
[INFO] bower chartist#~0.4.3                     validate 0.4.4 against git://github.com/gionkunz/chartist-js.git#~0.4.3
[INFO] bower chartist#~0.9.5                       cached git://github.com/gionkunz/chartist-js.git#0.9.5
[INFO] bower chartist#~0.9.5                     validate 0.9.5 against git://github.com/gionkunz/chartist-js.git#~0.9.5
[INFO] bower chartist#^0.9.0                       cached git://github.com/gionkunz/chartist-js.git#0.9.5
[INFO] bower chartist#^0.9.0                     validate 0.9.5 against git://github.com/gionkunz/chartist-js.git#^0.9.0
[ERROR] bower                                    ECONFLICT Unable to find suitable version for chartist
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] com.capitalone.dashboard:Hygieia ................... SUCCESS [  0.540 s]
[INFO] com.capitalone.dashboard:core ...................... SUCCESS [ 13.562 s]
[INFO] com.capitalone.dashboard:api ....................... SUCCESS [  8.318 s]
[INFO] com.capitalone.dashboard:jenkins-build-collector ... SUCCESS [  2.194 s]
[INFO] com.capitalone.dashboard:sonar-codequality-collector SUCCESS [  1.087 s]
[INFO] com.capitalone.dashboard:subversion-collector ...... SUCCESS [  0.967 s]
[INFO] com.capitalone.dashboard:github-scm-collector ...... SUCCESS [  1.306 s]
[INFO] com.capitalone.dashboard:versionone-feature-collector SUCCESS [  2.107 s]
[INFO] com.capitalone.dashboard:udeploy-deployment-collector SUCCESS [  1.806 s]
[INFO] com.capitalone.dashboard:jira-feature-collector .... SUCCESS [  5.207 s]
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SUCCESS [  1.778 s]
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SUCCESS [  0.824 s]
[INFO] com.capitalone.dashboard:UI ........................ FAILURE [  9.626 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 49.707 s
[INFO] Finished at: 2016-02-14T15:18:43-08:00
[INFO] Final Memory: 103M/1539M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.27:bower (bower install) on project UI: Failed to run task: 'bower install' failed. (error code 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :UI

**Comment by tabladrum** [comment]
Can you do a fresh clone into a clean folder? There is also one more thing to resolve. The jacoco version. We have to revert back the version - it was somehow failing on compilation. We look at it again tonight or tomorrow.

**Comment by jimzucker** [comment]
@tabladrum I found that adding a resolution for chartist solves it, see this thread: https://github.com/bower/bower/issues/866

I am not sure I picked the right version,but this will allow it to compile: 

  "resolutions": {
    "angular": "~1.3.4",
    "chartist": "~0.9.5"
  },
