### ISSUE TITLE
eclipse warnings cleanup - References to generic type (20 Cases)

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#349]
This one I think somebody more familiar with code should cleanup, preferably by setting the correct types, or as a last resort suppress the warning..

ResponseEntity is a raw type. References to generic type ResponseEntity<T> should be parameterized  DashboardController.java    /api/src/main/java/com/capitalone/dashboard/rest    line 56

ResponseEntity is a raw type. References to generic type ResponseEntity<T> should be parameterized  ServiceController.java  /api/src/main/java/com/capitalone/dashboard/rest    line 7

ResponseEntity is a raw type. References to generic type ResponseEntity<T> should be parameterized  ServiceController.java  /api/src/main/java/com/capitalone/dashboard/rest    line 91

Map.Entry is a raw type. References to generic type Map<K,V>.Entry<K,V> should be parameterized Dashboard.java  /core/src/main/java/com/capitalone/dashboard/model  line 89

Map.Entry is a raw type. References to generic type Map<K,V>.Entry<K,V> should be parameterized PipelineServiceImpl.java    /api/src/main/java/com/capitalone/dashboard/service line 205

Map is a raw type. References to generic type Map<K,V> should be parameterized  Dashboard.java  /core/src/main/java/com/capitalone/dashboard/model  line 84

Map is a raw type. References to generic type Map<K,V> should be parameterized  PipelineServiceImpl.java    /api/src/main/java/com/capitalone/dashboard/service line 106

List is a raw type. References to generic type List<E> should be parameterized  HudsonCollectorTaskTests.java   /jenkins-build-collector/src/test/java/com/capitalone/dashboard/collector   line 75

List is a raw type. References to generic type List<E> should be parameterized  PipelineServiceTest.java    /api/src/test/java/com/capitalone/dashboard/service line 70

HttpEntity is a raw type. References to generic type HttpEntity<T> should be parameterized  DefaultHudsonClientTests.java   /jenkins-build-collector/src/test/java/com/capitalone/dashboard/collector   line 105

HttpEntity is a raw type. References to generic type HttpEntity<T> should be parameterized  DefaultHudsonClientTests.java   /jenkins-build-collector/src/test/java/com/capitalone/dashboard/collector   line 105

HttpEntity is a raw type. References to generic type HttpEntity<T> should be parameterized  DefaultHudsonClientTests.java   /jenkins-build-collector/src/test/java/com/capitalone/dashboard/collector   line 119

HttpEntity is a raw type. References to generic type HttpEntity<T> should be parameterized  DefaultHudsonClientTests.java   /jenkins-build-collector/src/test/java/com/capitalone/dashboard/collector   line 119

HttpEntity is a raw type. References to generic type HttpEntity<T> should be parameterized  DefaultHudsonClientTests.java   /jenkins-build-collector/src/test/java/com/capitalone/dashboard/collector   line 133

HttpEntity is a raw type. References to generic type HttpEntity<T> should be parameterized  DefaultHudsonClientTests.java   /jenkins-build-collector/src/test/java/com/capitalone/dashboard/collector   line 133

HttpEntity is a raw type. References to generic type HttpEntity<T> should be parameterized  DefaultJenkinsClientTest.java   /jenkins-cucumber-test-collector/src/test/java/com/capitalone/dashboard/collector   line 74

HttpEntity is a raw type. References to generic type HttpEntity<T> should be parameterized  DefaultJenkinsClientTest.java   /jenkins-cucumber-test-collector/src/test/java/com/capitalone/dashboard/collector   line 74

HttpEntity is a raw type. References to generic type HttpEntity<T> should be parameterized  DefaultJenkinsClientTest.java   /jenkins-cucumber-test-collector/src/test/java/com/capitalone/dashboard/collector   line 88

HttpEntity is a raw type. References to generic type HttpEntity<T> should be parameterized  DefaultJenkinsClientTest.java   /jenkins-cucumber-test-collector/src/test/java/com/capitalone/dashboard/collector   line 88

Collection is a raw type. References to generic type Collection<E> should be parameterized  DefaultSubversionClient.java    /subversion-collector/src/main/java/com/capitalone/dashboard/collector  line 67

**Comment by jimzucker** [comment]
Mostly fixed with Merge pull request #396

One item remaining: 
Description	Resource	Path	Location	Type
Type safety: The method add(Object) belongs to the raw type ArrayList. References to generic type ArrayList<E> should be parameterized	DefaultUDeployClient.java	/udeploy-deployment-collector/src/main/java/com/capitalone/dashboard/collector	line 242	Java Problem

**Comment by nireeshT** [comment]
Fixed and merged.
