### ISSUE TITLE
Eclipse warnings cleanup - Resource leak (1 Case)

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#350]
This should be reviewed and addressed.

Resource leak: '<unassigned Closeable value>' is never closed	MarkdownTest.java	/core/src/test/java/com/capitalone/dashboard	line 63

**Comment by jimzucker** [comment]
@jdamick  - can you take a look at this one, it was introduced with your commit in Dec.

**Comment by tabladrum** [comment]
Merged.
