### ISSUE TITLE
PMD Warnings - Avoid catching NullPointerException; consider removing the cause of the NPE (14 cases)

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#352]
This needs input from the team, do we want to fix these or configure PMD to just ignore them?

Description Resource    Path    Location    Type
Avoid catching NullPointerException; consider removing the cause of the NPE.    FeatureServiceImpl.java /api/src/main/java/com/capitalone/dashboard/service line 77 PMD Marker

Avoid catching NullPointerException; consider removing the cause of the NPE.    FeatureServiceImpl.java /api/src/main/java/com/capitalone/dashboard/service line 119    PMD Marker

Avoid catching NullPointerException; consider removing the cause of the NPE.    FeatureServiceImpl.java /api/src/main/java/com/capitalone/dashboard/service line 172    PMD Marker

Avoid catching NullPointerException; consider removing the cause of the NPE.    FeatureServiceImpl.java /api/src/main/java/com/capitalone/dashboard/service line 180    PMD Marker

Avoid catching NullPointerException; consider removing the cause of the NPE.    FeatureServiceImpl.java /api/src/main/java/com/capitalone/dashboard/service line 190    PMD Marker

Avoid catching NullPointerException; consider removing the cause of the NPE.    FeatureServiceImpl.java /api/src/main/java/com/capitalone/dashboard/service line 202    PMD Marker

Avoid catching NullPointerException; consider removing the cause of the NPE.    FeatureServiceImpl.java /api/src/main/java/com/capitalone/dashboard/service line 255    PMD Marker

Avoid catching NullPointerException; consider removing the cause of the NPE.    FeatureServiceImpl.java /api/src/main/java/com/capitalone/dashboard/service line 308    PMD Marker

Avoid catching NullPointerException; consider removing the cause of the NPE.    FeatureServiceImpl.java /api/src/main/java/com/capitalone/dashboard/service line 361    PMD Marker

Avoid catching NullPointerException; consider removing the cause of the NPE.    FeatureServiceImpl.java /api/src/main/java/com/capitalone/dashboard/service line 415    PMD Marker

**Comment by jimzucker** [comment]
@tabladrum @jdamick  - What do we want to do with this category?  Maybe we should just disable it the PMD rules and allow it, seems like make-work to keep surpassing them, do you really want to re-write such code?

**Comment by tabladrum** [comment]
I really want @amp5208 fix this code.

**Comment by amp5208** [comment]
@tabladrum , I plan on it - however, further work on Hygieia was de-scoped based on my current capacity and priorities.  I am trying to get it back on my radar.  Feel free to speak with more about this offline.

**Comment by jimzucker** [comment]
@tabladrum  @amp5208  - I marked the all as: 
	@SuppressWarnings("PMD.AvoidCatchingNPE") // TODO: Avoid catching NullPointerException; consider removing the cause of the NPE

For now to clear up PMD and will leave this open for you to review.  FYI in total of 14 cases to review: (4 where previously suppressed)

/api/src/main/java/com/capitalone/dashboard/service/FeatureServiceImpl.java:	@SuppressWarnings("PMD.AvoidCatchingNPE") // TODO:...
./api/src/main/java/com/capitalone/dashboard/service/FeatureServiceImpl.java:	@SuppressWarnings("PMD.AvoidCatchingNPE") // TODO: Avoid catching NullPointerException; consider removing the cause of the NPE
./api/src/main/java/com/capitalone/dashboard/service/FeatureServiceImpl.java:	@SuppressWarnings("PMD.AvoidCatchingNPE") // TODO: Avoid catching NullPointerException; consider removing the cause of the NPE
./api/src/main/java/com/capitalone/dashboard/service/FeatureServiceImpl.java:	@SuppressWarnings("PMD.AvoidCatchingNPE") // TODO: Avoid catching NullPointerException; consider removing the cause of the NPE
./api/src/main/java/com/capitalone/dashboard/service/FeatureServiceImpl.java:	@SuppressWarnings("PMD.AvoidCatchingNPE") // TODO: Avoid catching NullPointerException; consider removing the cause of the NPE
./api/src/main/java/com/capitalone/dashboard/service/FeatureServiceImpl.java:	@SuppressWarnings("PMD.AvoidCatchingNPE") // TODO: Avoid catching NullPointerException; consider removing the cause of the NPE
./api/src/main/java/com/capitalone/dashboard/service/FeatureServiceImpl.java:	@SuppressWarnings("PMD.AvoidCatchingNPE") // TODO: Avoid catching NullPointerException; consider removing the cause of the NPE
./core/src/main/java/com/capitalone/dashboard/util/Encryption.java:@SuppressWarnings("PMD.AvoidCatchingNPE") // TODO: Avoid catching NullPointerException; consider removing the cause of the NPE
./udeploy-deployment-collector/src/main/java/com/capitalone/dashboard/collector/DefaultUDeployClient.java:    @SuppressWarnings("PMD.AvoidCatchingNPE")
./versionone-feature-collector/src/main/java/com/capitalone/dashboard/client/project/ProjectDataClientSetupImpl.java:@SuppressWarnings("PMD.AvoidCatchingNPE") // fixme
./versionone-feature-collector/src/main/java/com/capitalone/dashboard/client/story/FeatureDataClientSetupImpl.java:	@SuppressWarnings("PMD.AvoidCatchingNPE") // agreed, fixme
./versionone-feature-collector/src/main/java/com/capitalone/dashboard/client/story/StoryDataClientImpl.java:	@SuppressWarnings({"unchecked", "PMD.ExcessiveMethodLength", "PMD.AvoidCatchingNPE",
./versionone-feature-collector/src/main/java/com/capitalone/dashboard/client/team/TeamDataClientSetupImpl.java:	@SuppressWarnings("PMD.AvoidCatchingNPE")
./versionone-feature-collector/src/main/java/com/capitalone/dashboard/util/ClientUtil.java:	@SuppressWarnings("PMD.AvoidCatchingNPE")

**Comment by amp5208** [comment]
@jimzucker , Thank you for this.  I will be working on cleaning up existing code and PMD annotations next sprint (in 1.5 weeks from today).

**Comment by jimzucker** [comment]
closed by accident

**Comment by amp5208** [comment]
@jimzucker , thank you - keep this open.  I will be fixing these in our next iteration (0.5 weeks from now)

**Comment by nireeshT** [comment]
Fixed and merged as part of #606
