### ISSUE TITLE
PMD Warning - method search() has an NPath complexity of 264

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#356]
Description Resource    Path    Location    Type
The method search() has an NPath complexity of 264  TestResultServiceImpl.java  /api/src/main/java/com/capitalone/dashboard/service line 45 PMD Marker

**Comment by tabladrum** [comment]
@jimzucker can you confirm again if it is line#45? My IntelliJ doesn't complain.

**Comment by jimzucker** [comment]
Confirmed: Description	Resource	Path	Location	Type
The method search() has an NPath complexity of 264	TestResultServiceImpl.java	/api/src/main/java/com/capitalone/dashboard/service	line 45	PMD Marker

It is this method,     public DataResponse<Iterable<TestResult>> search(TestResultRequest request) {
as this is only a Test it might be OK to suppress it.
![screenshot 2016-03-18 16 23 06](https://cloud.githubusercontent.com/assets/14372687/13894519/c8dd2094-ed25-11e5-88f5-5f976967a3e4.png)
![screenshot 2016-03-18 16 22 47](https://cloud.githubusercontent.com/assets/14372687/13894521/cef7f972-ed25-11e5-943b-29eecb860c87.png)

**Comment by nireeshT** [comment]
Fixed in PR https://github.com/capitalone/Hygieia/pull/916
