### ISSUE TITLE
Unable to configure github collector

### ISSUE THREAD

**Issue by suniltantry** [capitalone/Hygieia#362]
Team,
Thank you for developing such a great tool, however, we are currently unable to configure GIT and JIRA collectors.

We have an git running on our corporate server and we get the below error, Can you kindly assist.?

2016-02-23 16:31:46,032 ERROR c.c.d.collector.DefaultGitHubClient - 403 Forbidden:https://github.xx.xx.xx..com/api/v3/repos/api/v3/repos/xxxxx/depscripts/commits?sha=Eod&since=2016-02-23T16:21Z
2016-02-23 16:50:02,224 INFO  c.c.d.collector.CollectorTask - Repo Count         1        2s
2016-02-23 16:50:02,224 INFO  c.c.d.collector.CollectorTask - New Commits        0        2s
2016-02-23 16:50:02,225 INFO  c.c.d.collector.CollectorTask - Finished                    2s

Please assist. Kindly let me know if you need further info.

Thanks,

**Comment by suniltantry** [comment]
All,
Is there a way we can pass github authentication information in the application.properties file?
Kindly assist.

**Comment by softwareklinic** [comment]
You should be able to.. If not its easy to modify code to accept it from properties file…

**Comment by bhoslepu** [comment]
I am using latest version of Hygieia and facing same issue of Forbidden access with GitHub private repository. Is there way to solve this??

**Comment by suniltantry** [comment]
Hi,
You need to add in your UserID and API key in application .properites file like below.

github.UserId=p710231
github.key=XXXXXXXXXXXXXXXXXXXXXXXXXXXc1

Then modify DefaultGitHubClient.java and force the response string to fetch the password from properties file

                                //ResponseEntity<String> response = makeRestCall(queryUrlPage, settings.getUserId(), decryptedPassword);
                                ResponseEntity<String> response = makeRestCall(queryUrlPage, settings.getUserId(), settings.getKey());


Thanks,

**Comment by bhoslepu** [comment]
Thanks.. Its working now. Only thing I have to declare function for getUserId.
