### ISSUE TITLE
Code collector widget showing different tech debt value

### ISSUE THREAD

**Issue by papithag** [capitalone/Hygieia#368]
Hello
I am using SonarQube for code quality and coverage, technical debt value is varying in Sonarqube dashboard and in Hygieia code collector widget.

Is there any fix around so that I can use in Hygieia dashboard code?

**Comment by jimzucker** [comment]
I ran a test using sonar 5.3 and the Hygieia code base and reproduced the issue.  It will need to be investigated.

Here is my review:
***Tech Debt: 6d on Hygieia and 15d in Sonar
% Coverage  - LGTM
#issues - LGTM


<img width="710" alt="screenshot 2016-02-25 16 47 29" src="https://cloud.githubusercontent.com/assets/14372687/13339701/7e72de7e-dbdf-11e5-95c1-cf0834ecffa1.png">

<img width="354" alt="screenshot 2016-02-25 16 41 55" src="https://cloud.githubusercontent.com/assets/14372687/13339647/172e195e-dbdf-11e5-8fe5-4dd372d0362c.png">
<img width="310" alt="screenshot 2016-02-25 16 41 47" src="https://cloud.githubusercontent.com/assets/14372687/13339649/1923f094-dbdf-11e5-9078-4c4380621d70.png">

<img width="1160" alt="screenshot 2016-02-25 16 41 20" src="https://cloud.githubusercontent.com/assets/14372687/13339650/192aeb2e-dbdf-11e5-8892-4525324ba7b8.png">

**Comment by papithag** [comment]
Hi @jimzucker , 
any update to this issue?

**Comment by jimzucker** [comment]
@papithag I took a look at the issue it the calc in the dashboard

There is a method, calculateTechnicalDebt.  I don think the calculation for Day and year are correct, the is what I see 

A day is counted as 1440 min, I think it should be 480.

Year is counted as 525600 minutes I think it should be 105,600 minutes. This is what I think it should be:
 Min 	          Hours 	     Days 	 Year 
 60.000 	         1.000 	     0.125 	 0.001 
 480.000 	          8.000 	     1.000 	 0.005   *assume a day == 8 hours
 105,600.000 	 1,760.000     220	 1.000  * assume a year is 220 workdays

I am testing the patch now...

**Comment by papithag** [comment]
Hi @jimzucker 
Awaiting for the fix :-)

**Comment by jimzucker** [comment]
To get the #s to tie to sonar I had to use 8.25 hours/day.

 Min 	          Hours 	     Days 	 Year 
 60    	         1.000 	     0.125 	 0.001 
 495 	          8.250 	     1.000 	 0.005   *assume a day == 8.25 hours
 113850 	          1,760           230	 1.000  * assume a year is 230 workdays in a year (46 weeks)

**Comment by papithag** [comment]
I am also working on the changes in my local as u suggested... Can u send me ur modified changes?

**Comment by jimzucker** [comment]
you can take a look at this branch:  git@github.com:jimzucker/Hygieia.git

I haven’t tested it yet I have to do that tomorrow…


On Feb 28, 2016, at 9:51 PM, papithag <notifications@github.com<mailto:notifications@github.com>> wrote:


I am also working on the changes in my local as u suggested... Can u send me ur modified changes?

**Comment by papithag** [comment]
Hi @jimzucker ,
I modified the code as you mentioned, still the values are not same in sonar and hygieia.
Hygieia shows tech debt (+1 or 2 days) higher than sonar.

Still need some tuning in the calculations

**Comment by jimzucker** [comment]
@papithag can you attach the following information:

1. Screen shots of what you see in your sonar & Hygieia (with and without the modification)
2. can you provide the output of this rest call, you may have to modify the <resource id> in the URL

http://<sonar host>:<port>/api/resources?format=json&resource=1&metrics=-ncloc,line_coverage,violations,critical_violations,major_violations,blocker_violations,sqale_index,test_success_density,test_failures,test_errors,tests&includealerts=true


Output looks like this: (we are interested in the list with key == sale_index

{"id":1,"key":"com.capitalone.dashboard:Hygieia","uuid":"AVMf6JQCcKPh5nAzLMVX","name":"com.capitalone.dashboard:Hygieia","scope":"PRJ","qualifier":"TRK","date":"2016-02-26T23:27:08+0000","creationDate":"2016-02-26T23:27:29+0000","lname":"com.capitalone.dashboard:Hygieia","version":"2.0.0-SNAPSHOT","description":"Spring Boot Starter Parent","msr":[
{"key":"tests","val":167.0,"frmt_val":"167","alert":null,"alert_text":null
{"key":"test_errors","val":0.0,"frmt_val":"0","alert":null,"alert_text":null},
{"key":"test_failures","val":0.0,"frmt_val":"0","alert":null,"alert_text":null},
{"key":"test_success_density","val":100.0,"frmt_val":"100.0%","alert":null,"alert_text":null},
{"key":"line_coverage","val":30.4,"frmt_val":"30.4%","alert":null,"alert_text":null},
{"key":"violations","val":783.0,"frmt_val":"783","alert":null,"alert_text":null},
{"key":"blocker_violations","val":1.0,"frmt_val":"1","alert":null,"alert_text":null},
{"key":"critical_violations","val":65.0,"frmt_val":"65","alert":null,"alert_text":null},
{"key":"major_violations","val":435.0,"frmt_val":"435","alert":null,"alert_text":null},
{"key":"sqale_index","val":7536.0,"frmt_val":"15d","alert":null,"alert_text":null}]}]

**Comment by jimzucker** [comment]
@papithag - I did some research today and it looks like we should use floor vs ceil on the resulting # of days.  In my test case I tied out. (the root cause issues was the divisor for minutes/day where off)

Here is my test case, you can see the UI ties to the values found in the rest call now.

![screenshot 2016-02-29 15 04 50](https://cloud.githubusercontent.com/assets/14372687/13412164/3642db1c-def6-11e5-9c6f-ce2d854b7649.png)

![screenshot 2016-02-29 15 04 38](https://cloud.githubusercontent.com/assets/14372687/13412181/43a31cf4-def6-11e5-9cb4-fef03f12b3ee.png)

**Comment by papithag** [comment]
Hi @jimzucker 
As per your recommended changes, I updated the code and finally added FLOOR method also.
I still see slight variations in the value

![image](https://cloud.githubusercontent.com/assets/14195791/13419203/3391b584-dfb7-11e5-8607-e2eaf254b6fc.png)

![image](https://cloud.githubusercontent.com/assets/14195791/13419222/4e8b127c-dfb7-11e5-9396-a41ed2751c8f.png)

Sonarqube dashboard has 12days where in Hygieia has 11days.

Updated code is this:
function calculateTechnicalDebt(value) {
            var factor, suffix;
            var hour = 60;
            var day = hour * 8.25;	
            var year = day * 230;	
            

            if (!value) return '-';
            if (value < day) {
                // hours
                factor = hour;
                suffix = 'h';
            } else if (value < year) {
                // days
                factor = day;
                suffix = 'd';
            } else {
                // years
                factor = year;
                suffix = 'y';
            }
            return Math.floor(value/factor) + suffix;
        }

**Comment by jimzucker** [comment]
Please make a day = hour * 8



Sent from my iPhone

On Feb 29, 2016, at 22:11, papithag <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @jimzucker<https://github.com/jimzucker>
As per your recommended changes, I updated the code and finally added FLOOR method also.
I still see slight variations in the value

[image]<https://cloud.githubusercontent.com/assets/14195791/13419203/3391b584-dfb7-11e5-8607-e2eaf254b6fc.png>

[image]<https://cloud.githubusercontent.com/assets/14195791/13419222/4e8b127c-dfb7-11e5-9396-a41ed2751c8f.png>

Sonarqube dashboard has 12days where in Hygieia has 11days.

Updated code is this:
function calculateTechnicalDebt(value) {
var factor, suffix;
var hour = 60;
var day = hour * 8.25;

var year = day * 230;

        if (!value) return '-';
        if (value < day) {
            // hours
            factor = hour;
            suffix = 'h';
        } else if (value < year) {
            // days
            factor = day;
            suffix = 'd';
        } else {
            // years
            factor = year;
            suffix = 'y';
        }
        return Math.floor(value/factor) + suffix;
    }


-

**Comment by papithag** [comment]
hi @jimzucker 
After making day =hour*8, Sonarqube and Hygieia dashboard are showing same values if Sonarqube has single value like 3d, 8d, 12d.... but if SonarQube has double values like 1d 3 h, then Hygieia dashboard shows +1 or 2 days.

![image](https://cloud.githubusercontent.com/assets/14195791/13496094/59e8ad36-e189-11e5-8b98-a2e7c17071fa.png)

![image](https://cloud.githubusercontent.com/assets/14195791/13496106/6d250002-e189-11e5-88ad-a03621ab7035.png)

I understand the technical debt method doesn't handle this type of values. Can we work on this as well ? :-)

**Comment by jimzucker** [comment]
@papithag I am not sure if we want to fix this as the dashboard is meant to be a radiator, and putting 2d 11h may require chasing the layout of the UI. 

@tabladrum let us know what you think...

@papithag  Can you run this (modify the hostname) so we can see what is returned by the JSON server as my 5.3 sonar is returning only in Days so I match exactly.

http://*dockerhost:9000*/api/resources?format=json&resource=1&metrics=-ncloc,line_coverage,violations,critical_violations,major_violations,blocker_violations,sqale_index,test_success_density,test_failures,test_errors,tests&includealerts=true

Also see I did a test hardcoding "10d 2h" to see how the UI behaves, I think we can pull the string from the JSON message, in this way it will match whatever Sonar tells us, I think that is the best we can do, if @tabladrum OK with the change.
{"key":"sqale_index","val":7536.0,"frmt_val": *"15d"* ,"alert":null,"alert_text":null}]}]

![screenshot 2016-03-04 16 36 13](https://cloud.githubusercontent.com/assets/14372687/13544275/0b6cc872-e229-11e5-8e96-58d72b19e2b5.png)

**Comment by jimzucker** [comment]
@papithag you can try the change I just pushed, but please send me the json output from your server if it doesn't match.

**Comment by papithag** [comment]
Hi @jimzucker 

Added the change and working as expected.
Checked for technical debt with the combination of hours, days + hours, mins alone... all are working fine.

Thanks a lot for the support
