### ISSUE TITLE
UI error

### ISSUE THREAD

**Issue by vishalbisa** [capitalone/Hygieia#373]
Hi @jimzucker / @tabladrum / @amitmawkin / @vtjiles / @johnkangcurd 
 
i am changes few UI file changes on the fly, but most of the time my gulp serve crashes with below error.

after undoing those changes also but it stills fails .

as a work around i need to delete the bower componets and re-install the UI components (npm install, bower install , gulp serve)
Error: 
 
events.js:141
      throw er; // Unhandled 'error' event
      ^
 
TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:167:9)
    at new Buffer (buffer.js:58:10)
    at DestroyableTransform._transform (D:\Hygieia\UI\node
_modules\wiredep\wiredep.js:135:23)
    at DestroyableTransform.Transform._read (D:\Hygieia\UI
\node_modules\wiredep\node_modules\through2\node_modules\readable-stream\lib\_st
ream_transform.js:184:10)
    at DestroyableTransform.Transform._write (D:\Hygieia\U
I\node_modules\wiredep\node_modules\through2\node_modules\readable-stream\lib\_s
tream_transform.js:172:12)
    at doWrite (D:\Hygieia\UI\node_modules\wiredep\node_mo
dules\through2\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (D:\Hygieia\UI\node_modules\wiredep\n
ode_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:227:5)
 
    at DestroyableTransform.Writable.write (D:\Hygieia\UI\
node_modules\wiredep\node_modules\through2\node_modules\readable-stream\lib\_str
eam_writable.js:194:11)
    at write (D:\Hygieia\UI\node_modules\gulp\node_modules
\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readabl
e.js:623:24)
    at flow (D:\Hygieia\UI\node_modules\gulp\node_modules\
vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable
.js:632:7)
 
D:\Hygieia\UI>

any comments please on how to resolve this issue.

**Comment by tabladrum** [comment]
Did you change anything in the code? What are those?

**Comment by vishalbisa** [comment]
Hi @tabladrum ,

i am working on chartist , changing the view.js file and .html files.

i have even observed that the index.html file size is 0 bytes.

Thanks,
Vishal

**Comment by vishalbisa** [comment]
As a work around, we are replacing the index.html file ...

but still i wonder even small changes are causing the gulp serve to fail and the index file size is reduced to 0. undoing the changes doesnt even work in this scenario.
