### ISSUE TITLE
About Artiactory, deployment, and test results

### ISSUE THREAD

**Issue by softwareklinic** [capitalone/Hygieia#382]
In the new dashboard where will we show the following data

1. artifact 
2. deployment (i guess widget exists)
3. test results

**Comment by softwareklinic** [comment]
Can someone respond to this one please...

**Comment by tabladrum** [comment]
Please see the Hygieia 2.0 documentation for reference: https://github.com/capitalone/Hygieia/blob/master/Hygieia2.md

Test Results:
- If you publish (via Jenkins hygieia plugin) the cucumber test results, you can select those jenkins jobs in your Quality widget: Functional Test: 
![image](https://cloud.githubusercontent.com/assets/6014941/13606509/287695ee-e51a-11e5-8379-e19aabb8fed2.png)

Deployment:
The widget already exist. Again, if you publish your deployment results via Jenkins plugin, they will show up in the deployment widget:

![image](https://cloud.githubusercontent.com/assets/6014941/13606605/8b34982a-e51a-11e5-820b-054129189adb.png)


Artifacts:
There is no separate widget for Artifact. However, if you publish Artifact info via Jenkins plugin, Hygieia will successfully link your code -> build -> artifact -> deployment "pipeline" in the Hygieia 2.0 product dashboard (see Hygieia 2.0 documentation)

**Comment by tabladrum** [comment]
@softwareklinic do you have more questions on this? If you want we can have an offline chat.

**Comment by softwareklinic** [comment]
Yes let's talk offline - I have something to share as well

Sent from my iPhone

On Mar 19, 2016, at 8:30 PM, tabladrum <notifications@github.com<mailto:notifications@github.com>> wrote:


@softwareklinic<https://github.com/softwareklinic> do you have more questions on this? If you want we can have an offline chat.
