### ISSUE TITLE
About web hook for Stash

### ISSUE THREAD

**Issue by softwareklinic** [capitalone/Hygieia#384]
Would the web hook work the same way for Stash as well?

**Comment by tabladrum** [comment]
Depends upon the payload. I don't know stash payload. Can you paste one?

**Comment by tabladrum** [comment]
@softwareklinic - stash push payload looks different. If you are going to use it, I might create an new end point. Let me know.

**Comment by softwareklinic** [comment]
Yes we are using stash for enterprise

Sent from my iPhone

On Mar 18, 2016, at 5:01 PM, tabladrum <notifications@github.com<mailto:notifications@github.com>> wrote:


@softwareklinic<https://github.com/softwareklinic> - stash push payload looks different. If you are going to use it, I might create an new end point. Let me know.

**Comment by tabladrum** [comment]
Are you looking to push from Stash to Hygieia?

**Comment by softwareklinic** [comment]
Yes - webhook would be great

Sent from my iPhone

On Mar 18, 2016, at 5:06 PM, tabladrum <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you looking to push from Stash to Hygieia?

**Comment by Sbrenthughes** [comment]
@tabladrum Please reopen if this is still a valid issue.
