### ISSUE TITLE
Allow Hygieia UI to see Hygieia Status and Critical Errors

### ISSUE THREAD

**Issue by tabladrum** [capitalone/Hygieia#388]
UI option should allow the user to view
- collector status, error
- api status, errors

**Comment by mdskd** [comment]
somewhat related; internally we have on our backlog to look at exception handling in Hygieia. anticipate more to come on it in 2017.

**Comment by Sbrenthughes** [comment]
We currently do this somewhat in the current dashboard. https://github.com/capitalone/Hygieia/pull/1765. More to come on the rest of this.
