### ISSUE TITLE
Hygieia 2.0 build issue

### ISSUE THREAD

**Issue by wflentje** [capitalone/Hygieia#394]
Am getting this when running clean build with fresh hygieia 2.0 download on rhel 7.x.  Any help appreciated.

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.709s
[INFO] Finished at: Thu Mar 03 12:10:11 EST 2016
[INFO] Final Memory: 28M/61M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project core: Fatal error compiling: invalid target release: 1.8 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project core: Fatal error compiling

**Comment by wflentje** [comment]
Need Java 1.8 .

**Comment by tabladrum** [comment]
Can you paste a little more of the stack trace? What's your JDK version?

**Comment by wflentje** [comment]
I was on 1.7, upgraded to 1.8 and worked fine.  Sorry did not do proper research before opening the issue.

**Comment by tabladrum** [comment]
np. let us know how the rest of it goes.
