### ISSUE TITLE
Jenkins collector does not support folders which will significantly reduce the usability of the collector. The collector is a preferred method over the Jenkins plugin for large deployments as the plugin requires modifying every job

### ISSUE THREAD

**Issue by camillone** [capitalone/Hygieia#399]
The Jenkins collector is unable to traverse within folders so it is unable to see any jobs within a folder. It marks the folder as a job within the Hygieia UI.

**Comment by tabladrum** [comment]
Are the jobs not being collected? Or are the folder organization is messed up?

**Comment by camillone** [comment]
It does not seem as though folders are working, but I'll get more details.

**Comment by tabladrum** [comment]
Send me the details when you get a chance.

**Comment by tabladrum** [comment]
@camillone Can you please send me more details on this?

**Comment by SachinKSingh28** [comment]
I have the similar problem. The Jenkins collector picks up the list of jobs which are at the top level. For instance, if I have got JobA, JobB, FolderA/AnotherJobA and FolderB/AnotherJobB then the Jenkins collector shows JobA, JobB, FolderA and FolderB in the list when configuring the widget.

**Comment by asperkins** [comment]
From what I can see the jenkins collector doesn't support recursive folder search. You can kind of work around this by creating multiple entries in the configuration, BUT we have an issue with this on our setup.

So, you could do this in the properties file
jenkins.servers[0]=http://jenkins.company.com/
jenkins.servers[1]=http://jenkins.company.com/FolderA
jenkins.servers[2]=http://jenkins.company.com/FolderB

You'll then get a list of jobs that are at the root, and in FolderA and Folder B.

A couple of issues with this tho. In our case the jobs are named the same...
jenkins.servers[0]=http://jenkins.company.com
jenkins.servers[0]=http://jenkins.company.com

**Comment by tabladrum** [comment]
I am aware that team target has enhanced the collector and will do a PR soon.

**Comment by sanjeevnewt** [comment]
@tabladrum any update on this one?

**Comment by tabladrum** [comment]
See this PR -> https://github.com/capitalone/Hygieia/pull/1038
