### ISSUE TITLE
signup attempt results in net ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by radkin** [capitalone/Hygieia#40]
Please help, stood up Hygieia, can't signup.

* maven "Reactor Summary" all are a SUCCESS
* mongodb "show dbs" has admin, local & test
* mongodb "show collections" indicates the following:

```bash
> show collections
system.indexes
system.users
system.version
> db.getCollection("system.users").find()
{ "_id" : "dashboarddb.dashboarduser", "user" : "dashboarduser", "db" : "dashboarddb", "credentials" : { "SCRAM-SHA-1" : { "iterationCount" : 10000, "salt" : "REDACTED==", "storedKey" : "REDACTED", "serverKey" : "REDACTED" } }, "roles" : [ ] }
```

* After a while there is more information that could be helpful

```bash
GET http://REDACTED:3000/browser-sync/browser-sync-client.1.7.3.js net::ERR_INCOMPLETE_CHUNKED_ENCODING
Error: [$compile:tpload] Failed to load template: app/dashboard/views/signup.html
http://errors.angularjs.org/1.3.17/$compile/tpload?p0=app%2Fdashboard%2Fviews%2Fsignup.html
    at REGEX_STRING_REGEXP (angular.js:63)
    at handleError (angular.js:16233)
    at processQueue (angular.js:13300)
    at angular.js:13316
    at Scope.$get.Scope.$eval (angular.js:14555)
    at Scope.$get.Scope.$digest (angular.js:14371)
    at Scope.$get.Scope.$apply (angular.js:14660)
    at done (angular.js:9734)
    at completeRequest (angular.js:9924)
    at XMLHttpRequest.requestError (angular.js:9875)
```

**Comment by amitmawkin** [comment]
Noel,
Do you have API layer running on a tomcat server listening on 8080 port.

**Comment by radkin** [comment]
Thanks.
API running in tomcat7 now, listening on port 8080. 
`Failed to load resource: the server responded with a status of 404 (Not Found)`

The only documentation I found for installation is https://github.com/capitalone/Hygieia/blob/master/Setup.md
Is that the right doc?

**Comment by radkin** [comment]
FYI, I tried installing nginx and added a location / for port 3000 so that any routes are pointing to the logical "assumed place". It still doesn't work, but the error changed
`WebSocket connection to 'ws://our-server/browser-sync/socket.io/?EIO=3&transport=websocket&sid=Q1t5RUCsMsAEJ6UxAAAF' failed: Error during WebSocket handshake: 'Connection' header value must contain 'Upgrade'`

**Comment by tabladrum** [comment]
Fixed now.
