### ISSUE TITLE
GitHub Enterprise collector does not support SAML authentication

### ISSUE THREAD

**Issue by camillone** [capitalone/Hygieia#400]
SAML authentication isn't really the correct term but the collector really doesn't support authentication. If a GHE instance is behind a firewall and is access controlled then the collector is unable to authenticate itself to grab the repo information. There is not way through the UI or through an environment variable to authenticate itself.

**Comment by tabladrum** [comment]
@camillone Need a little more on the auth. Is it GHE token based auth? Or userid/password based basic auth? In either case, is there an "admin" type of access that can read all repo? This will be easy to implement. The collector as of now can actually read a repo with user id/password based auth. We just need to change the UI and some API to accept the user id/password from the UI.

**Comment by Sbrenthughes** [comment]
Please reopen if this is still a valid issue.
