### ISSUE TITLE
GitHub Enterprise web hook does support pulling history so we cannot view historical data

### ISSUE THREAD

**Issue by camillone** [capitalone/Hygieia#402]
Hygieia is unable to pull the history of any repo through the webhook or the collector. This is a huge issue as when you first load the collectors, plugins and webhooks you can't see any data loading in the dashboard. You have to wait a while before information starts filling in.

**Comment by tabladrum** [comment]
You can run the collector and GitHub push together. After few days (say 14 days) you can stop the collector and not run anymore.

**Comment by indrgun** [comment]
@camillone I see that you can configure webhook for a private repo on Github Enterprise environment.  I am struggling to do that with Hygiea 2.0.  Is there specific configuration needed on the Hygiea application.properties?  The Github collector is working fine.

Thank you
