### ISSUE TITLE
No Ldap authentication support for the UI

### ISSUE THREAD

**Issue by camillone** [capitalone/Hygieia#403]
This application should be something that only allows employees of an organization to access. There should be a way to connect to the LDAP server to authenticate a user otherwise anybody with the url will be able to access Hygieia and there needs to be a greater degree of security.

**Comment by softwareklinic** [comment]
I'm going to request one of our team members to look @ hygieia code and see if they can contribute to LDAP integration

**Comment by vijayct2001** [comment]
Any updates plz?

**Comment by bjayagop** [comment]
Has any one tried LDAP authentication for Hygieia ? pls share some ideas/suggesstions around this topic.

**Comment by MarkRx** [comment]
We are working on it right now. Expect a PR soon. @pxk5958

**Comment by brennanananan** [comment]
@bjayagop I hope to have a PR in later this week to allow Hygieia to use LDAP authentication.

**Comment by tabladrum** [comment]
@MarkRx @brennanananan please coordinate. Thanks.

**Comment by MarkRx** [comment]
@pxk5958

**Comment by bjayagop** [comment]
Thanks Mark and brennan for update.

**Comment by brennanananan** [comment]
PR Can be found here: #958 
@MarkRx 
@bjayagop

**Comment by mdskd** [comment]
we (mostly @brennanananan and @rob-miller-777) have some work in progress presently building out a more full-fledged security solution. anticipate a new pull request in early 2017.

here's a [work in progress branch](https://github.com/StateFarmIns/Hygieia/tree/springSecurityIntegration)

**Comment by satishc1** [comment]
Closed.
