### ISSUE TITLE
Jenkins-build-collector not fetching build details for a given Job

### ISSUE THREAD

**Issue by manjunath2008** [capitalone/Hygieia#405]
Hi All,

I have configured the Jenkins-build-collector successfully and the collector is working fine. In the configure build widget, i am able to see list of Job's name. But when i select one of the job from that list and save it. The collector is not extracting build related details for the job configured. And when i check the log i see the following error.

2016-03-08 11:55:06,293 ERROR c.c.d.collector.DefaultHudsonClient - Malformed url for loading build detailsno protocol: jenkins.com/job/myjobname/98/. URL =jenkins.com/job/myjobname/98/

Thanks & Regards
Manjunath

**Comment by tabladrum** [comment]
Can you paste the properties file here? Remove sensitive info.

**Comment by tabladrum** [comment]
One more thing to check... Go to your Jenkins -> Manage Jenkins -> Configure Jenkins page.
Scroll down to Jenkins location section. Make sure you have the right URL of jenkins in there with http:// or https://. Example:

![image](https://cloud.githubusercontent.com/assets/6014941/13605025/92f3efea-e513-11e5-800b-c56e15167059.png)

**Comment by manjunath2008** [comment]
Hi, 
Really sorry for the late reply. Now it is working fine. The mistake was in Manage Jenkins -> Configure Jenkins , there was no protocol defined in jenkins Url. Once i made the changes, it is working fine. Thanks for the help.. Sorry once again for the late replay.

Regards
Manjunath.V
