### ISSUE TITLE
Jira Feature Collector - Failure to find jira-rest-java-client-core during mvn clean install package

### ISSUE THREAD

**Issue by gillianwilson** [capitalone/Hygieia#408]
Hi

I'm getting the following error when trying to run mv clean install package in the Hygieia checkout folder...any ideas?  
.
.
.
[INFO] com.capitalone.dashboard:Hygieia ................... SUCCESS [  1.070 s]
[INFO] com.capitalone.dashboard:core ...................... SUCCESS [ 21.409 s]
[INFO] com.capitalone.dashboard:api ....................... SUCCESS [ 11.150 s]
[INFO] com.capitalone.dashboard:jenkins-build-collector ... SUCCESS [  5.929 s]
[INFO] com.capitalone.dashboard:sonar-codequality-collector SUCCESS [  0.734 s]
[INFO] com.capitalone.dashboard:subversion-collector ...... SUCCESS [  0.847 s]
[INFO] com.capitalone.dashboard:github-scm-collector ...... SUCCESS [  1.688 s]
[INFO] com.capitalone.dashboard:versionone-feature-collector SUCCESS [  4.241 s]
[INFO] com.capitalone.dashboard:udeploy-deployment-collector SUCCESS [  1.902 s]
[INFO] com.capitalone.dashboard:jira-feature-collector .... FAILURE [  0.172 s]
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SKIPPED
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SKIPPED
[INFO] com.capitalone.dashboard:UI ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
.
.
.
[ERROR] Failed to execute goal on project jira-feature-collector: Could not resolve dependencies for project com.capitalone.dashboard:jira-feature-collector:jar:2.0.0-SNAPSHOT: Failure to find com.atlassian.jira:jira-rest-java-client-core:jar:3.0.0 in http://repository:8080/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of nexus has elapsed or updates are forced -> [Help 1]

**Comment by AdonisCelestine** [comment]
@gillianwilson

I have the same issue.
How did you resolve this? What was the cause.
