### ISSUE TITLE
Specifying subversion url

### ISSUE THREAD

**Issue by asperkins** [capitalone/Hygieia#41]
I can't seem to find where to specify the subversion url. The documentation mentions username, password, but nothing about the repo url.

**Comment by amitmawkin** [comment]
you need to specify Subversion URL in the config screen of the widget. Once that is stored in DB, the collectors pick it up and start collecting data in the background.

**Comment by asperkins** [comment]
I'll give that a try. I have the mongo and the api layer running, but haven't yet managed to get the UI running. So, I was firing up some collectors manually. Thank you for the help.

**Comment by amitmawkin** [comment]
make sure while you are building the project to be connected to internet and you should have a smooth go, Once the builds complete successfully please go to UI folder and run <code> gulp serve <gulp serve>, also do make sure that your api layer is running on tomcat and serving traffic on port 8080.

**Comment by asperkins** [comment]
I'm slowly getting there. I work at Fidelity. So you can imagine the challenge of having an instance connected to the internet. But I appear to be making better progress this morning. I appreciate the assistance.

**Comment by asperkins** [comment]
Ok. I have mongo, api layer on 8080, subversion collector, and UI all running now. The issue I'm currently having is that after I select repo type and enter the value for repo url via the UI it does nothing when I click save. No error message, dialog box just sits there. I select subversion as the repo type and enter a value like http://mysvnserver.foo.com:7804/svn/TPR/trunk/

**Comment by mgijsbertihodenpijl** [comment]
Hi,

Same issue here for github.

I have the api running on Tomcat 8080, client started. When I configure the repo widget and add a github repo and branch, and press save, the UI does nothing. No error message, dialog box stays open.

**Comment by tabladrum** [comment]
Can you verify is the api is running: localhost:8080/api/dashboard?

Thanks

**Comment by aleitner** [comment]
I am having this same issue at the moment. Nobody seems to have posted a solution above. 

I am running all the necessary components I assume:
**Mongo**
`mongodb/mongodb-linux-x86_64-3.0.8/bin/mongod --dbpath data/db/ --smallfiles &`
**API**
`java -jar api.jar --spring.config.location=dashboard.properties &`
**UI**
`gulp serve &`
**SVN**
`java -jar subversion-collector-1.5.0-SNAPSHOT.jar --spring.config.location=application.properties &`

According to mongo the collector, and api are all connected to the database successfully. 

My application.properties file is as such:
> #Database Name
> spring.data.mongodb.database=dashboarddb
> 
> #Database HostName - default is localhost
> spring.data.mongodb.host=127.0.0.1
> 
> #Database Port - default is 27017
> spring.data.mongodb.port=27017
> 
> #Database Username - default is blank
> spring.data.mongodb.username=dashboarduser
> 
> #Database Password - default is blank
> spring.data.mongodb.password=1qazxSw2
> 
> #SVN
> 
> #Collector schedule (required)
> subversion.cron=0 0/5 * * * *
> 
> #Shared subversion username and password
> subversion.username=user
> subversion.password=pass

# Steps to recreate issue 
1. I login and create a new Cap One template dashboard.
2. I click configure widget under the Code Repo section.
3. I select the Subversion option under the dropdown and I enter my subversion url in the text box.
4. I click Save.

When I click Save nothing happens. When I go to inspect element nothing is popping up in the console or network.

When I navigate to `/api/dashboard` resource I see the following response
> [{"id":"56a2560fb980ed625099528d","template":"capone","title":"mydashboard","application":{"name":"myapplication","components":> [{"id":"56a2560fb980ed625099528c","name":"myapplication","collectorItems":{}}]},"widgets":[],"owner":"alex"}]

**Comment by amitmawkin** [comment]
Can you update your properties to this format and run the collector again
dbname=
dbhost=
dbport=
dbusername=
dbpassword=
logging.file=./logs/subversion.log
subversion.cron=
subversion.username=
subversion.password=
subversion.commitThresholdDays=15

**Comment by aleitner** [comment]
Unfortunately that didn't resolve anything. I tried leaving all the fields specified blank, but java threw an error saying that it requires `subversion.cron` to be set:

> 2016-01-25 14:46:04,586 WARN  o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'subversionCollectorTask': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Cron expression must consist of 6 fields (found 0 in "")

When I set `subversion.cron` the jar starts up fine, but I'm still having the issue where the save button does not do anything.

**Comment by aleitner** [comment]
I changed the value of dbname in dashboard.properties to dashboard, and created a new dashboard in mongo. Everything is working perfectly fine now.
