### ISSUE TITLE
JIRA configuration only getting 1 sprint data

### ISSUE THREAD

**Issue by aleitner** [capitalone/Hygieia#413]
My Jira collector is pulling data from my JIRA instance, but it only is getting information from 1 of the 7 sprints. I'm not seeing anything in my application.properties file that would actually change what sprints are seen.

Do you know of any potential cause for this?

Here's my application.properties file

feature.cron=0/15 * * * * *

feature.pageSize=1000

feature.queryFolder=jiraapi-queries

feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo

feature.sprintDays=10
feature.sprintEndPrior=5

feature.scheduledPriorMin=2

feature.deltaCollectorItemStartDate=2016-01-01T00:00:00.000000

feature.jiraBaseUrl=http://**************************.com/jira/

feature.jiraProxyUrl=
feature.jiraProxyPort=

feature.jiraCredentials=******************************************
feature.jiraIssueTypeId=Story
feature.jiraSprintDataFieldName=customfield_10300
feature.jiraEpicIdFieldName=customfield_10601
feature.deltaStartDate=2016-01-01T00:00:00.000000
feature.masterStartDate=2016-01-01T00:00:00.000000
feature.todoStatuses[0]=To Do
feature.doingStatuses[0]=In Progress
feature.doingStatuses[1]=Code Review
feature.doingStatuses[2]=Merge to Mainline
feature.doneStatuses[0]=Done

**Comment by aleitner** [comment]
I verified that customfield_10300 is that for all sprints when going to /rest/api/2/issue/[some-issue-name] for an issue from each sprint. Still unsure why the dashboard is only displaying information for only 1 sprint. Any ideas?

**Comment by amp5208** [comment]
@aleitner , Thank you for your question.  The way the collectors for the Feature Widget are currently configured, it assumes the following Jira configuration:  1 active project (that would align to a "team"), 1 active sprint, and many issues-type-story aligned to that active sprint.  Is this your current configuration, or does this assumption not hold for your implementation of Jira?

**Comment by aleitner** [comment]
Our Jira is 1 active project, multiple teams, multiple sprints(1 for each team), and many issues assigned to each sprint.

So is the collector getting the data like so:
`for each feature.jiraEpicIdFieldName count all feature.jiraSprintDataFieldName with application.properties statuses`

some of them numbers aren't lining up correctly.

**Comment by amp5208** [comment]
There is a disparity in our current design assumptions and your implementation then, unfortunately.  Are you using a custom "Team" field to differential teams within the project?  If so, there is currently an open enhancement request on this particular item:  https://github.com/capitalone/Hygieia/issues/82.

Our current implementation is more like this:

<pre>
GIVEN: 1 active Jira project AND 1 active sprint
WHEN:  A feature widget is configured for a given project
THEN:  Data is displayed accumulating all active stories for a given project in the active
       sprint WHERE active sprint is operationally defined as any sprints on stories that
       have a start/end date which spans "now"
</pre>

Hope this helps.

**Comment by satishc1** [comment]
Closed. Use the latest codebase.
