### ISSUE TITLE
UI should support flexibility in widgets

### ISSUE THREAD

**Issue by camillone** [capitalone/Hygieia#415]
There are cases when you have one repo with multiple branches that you want to monitor and having to switch between dashboards just to monitor a different branch but using the same UCD environment and same Jenkins builds can be cumbersome. There should be a way to add more widgets onto the dashboard to monitor multiple branches or repos within a specific application dashboard.

**Comment by tabladrum** [comment]
This is a very valid ask.

**Comment by amitmawkin** [comment]
you can play around with the existing templates..:)

**Comment by tabladrum** [comment]
@camillone - can you propose some screen sketch as to how we want to visualize it?

**Comment by ray-yan** [comment]
Vote for this request, we have multiple repos all points to the same Jira project. It's better to provide a flexible way to manage widgets display. I know a template can be done, but it'd be great to get it done from the GUI.

**Comment by satishc1** [comment]
Closed. Being tracked in https://github.com/capitalone/Hygieia/pull/1143

**Comment by Sbrenthughes** [comment]
This is coming very soon.
