### ISSUE TITLE
Api.github.com assumes Pacific timezone

### ISSUE THREAD

**Issue by mitchmania** [capitalone/Hygieia#42]
When running the GitHubSourceCodeCollector, the API calls specify a time that is ten minutes in the past to get the most recent commits.  The timezone is not specified and Github.com's api.github.com assumes they are in Pacific time.  If your server's date is in Pacific time and you run the collector everything is ok.  Api.github.com allows you to specify a timezone on the end of your date BTW.

**Comment by tabladrum** [comment]
Under test.

**Comment by tabladrum** [comment]
Fixed.
