### ISSUE TITLE
Security issue connecting to Git

### ISSUE THREAD

**Issue by gillianwilson** [capitalone/Hygieia#426]
Hi

Ive set up Git collector but it's complaining about security.  Do I need to do anything with certificates to get it working?

```
2016-03-14 13:16:00,432 ERROR c.c.d.collector.DefaultGitHubClient - I/O error on
GET request for "https://bfs-eng-can05.kana-test.com/api/v3/repos/km/knowledge-
management-services/commits?sha=master&since=2016-03-14T13:06Z":sun.security.val
idator.ValidatorException: PKIX path building failed: sun.security.provider.cert
path.SunCertPathBuilderException: unable to find valid certification path to req
uested target; nested exception is javax.net.ssl.SSLHandshakeException: sun.secu
rity.validator.ValidatorException: PKIX path building failed: sun.security.provi
der.certpath.SunCertPathBuilderException: unable to find valid certification pat
h to requested target:https://bfs-eng-can05.kana-test.com/api/v3/repos/km/knowle
dge-management-services/commits?sha=master&since=2016-03-14T13:06Z


```

**Comment by tabladrum** [comment]
yes. you need to import the cert into the jvm.

**Comment by gillianwilson** [comment]
Thanks for your help.  I think I've got it imported now.  The error is no longer happening.  Instead however I am now getting:
`2016-03-14 18:57:00,495 ERROR c.c.d.collector.DefaultGitHubClient - null`

**Comment by tabladrum** [comment]
We haven't tested with Gitlab. Using the Github API's. 
Does Gitlab support Github Hook type of event publish? If yes, you can do that. 
See this: https://github.com/capitalone/Hygieia/blob/master/Hygieia2.md

**Comment by gillianwilson** [comment]
Ok thanks for your help.

I was able to add the hygieia webhook in my gitlab and test with a "Hook executed successfully" message.

However, still getting the same error of DefaultGitHubClient null.  Is there any other reason for this particular error message?  Or is it most likely a case of not supported?

**Comment by gillianwilson** [comment]
I've been looking into it further and think the issue is because it's looking for username and password.  Is there a property that needs defined for this?  Or an alternative means to pass in?

**Comment by tabladrum** [comment]
Right now there is not a way to pass in the userid/password. Part of the solution is there - i.e., the collector can use a userid password if it was configured on the UI. We have not made changes to UI to capture that yet. 

If Gitlab can use the Github webhook endpoint that we have in the API today, that will be a way to handle the situation.

**Comment by gillianwilson** [comment]
Thanks for the quick reponse...i'll have a look into what you suggest.

**Comment by satishc1** [comment]
@gillianwilson refer to https://github.com/capitalone/Hygieia/pull/835
