### ISSUE TITLE
Application components and environment details

### ISSUE THREAD

**Issue by DeepakA** [capitalone/Hygieia#431]
Hi 

I am planning to host the dashboard in Ubuntu. Can you please provide the details on the application components.

Also please let me know if can we host all the components on the server. Also let me if you have sizing details for the hosting server (CPU, Memory and Storage)\\

Thanks,
Deepak

**Comment by deepakasa** [comment]
Team, quick response will be much appreciated.

**Comment by tabladrum** [comment]
It will depend upon the amount of data you are expecting to store etc. 
Give me some estimate on (1) how many git repositories (2) how many total jenkins jobs sonar jobs etc and (3) How many people will be using the dashboard?

**Comment by deepakasa** [comment]
Thanks much for quick response.

The details are as follows: 
I am planning to host the dashboard in AWS using the Ubuntu for demonstration purposes. 
(1) Currently we don't have git repositories, we will use svn ( 2 repositories) and tfs ( 2 large collections)
(2) We are around 100+ Jenkins jobs,  around 25+ SonarCube analysis jobs, around 20+ IBM Appscan jobs.
(3) At this point am not sure how many people were using the dashboard. But # will be quite high around 25+ 
(4) Also if you have any consolidated How to for hosting end-to-end application (with validation mechanism for each components) will be much helpful.

**Comment by amitmawkin** [comment]
if you are hosting all of the layers of Hygieia on a single box with above mentioned load you are good in AWS with a m3-large. you should also be able to run collectors on the same box if you wish too.

**Comment by deepakasa** [comment]
Thanks all for your quick response. 

I will start working on this and get back to you soon (Already started ad installed the DB, UI and API, working on setting up collectors).

Couple of things to update to the setup.md & api configuration file are 
- I was new to Mongo DB and I was executing the create user query with the results part and it was throwing error, It took me some time to get to that.
- When trying to run api usin external property file, it was failing and trying to connect Mongo DB @port 11500 ( this was the default configuration in the git src code). Is it possible to update the properties to MongoDB defaults in the source code? If yes then please update the properties file.

**Comment by tabladrum** [comment]
@deepakasa It will be great if you can do a Pull Request with the setup.md etc changes that can help the other new users.

**Comment by tabladrum** [comment]
@deepakasa do a PR when you get a chance. Closing this for now.
