### ISSUE TITLE
Error build maven

### ISSUE THREAD

**Issue by benathmane** [capitalone/Hygieia#436]
Hello,

Whene i launch this "sudo mvn clean install package" into hygieia directory
i have this error : 
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] org.apache.maven.reporting.MavenReportException: Could not find resource 'null/pmd.xml'.
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.RuntimeException: org.apache.maven.reporting.MavenReportException: Could not find resource 'null/pmd.xml'.
	at org.apache.maven.plugin.pmd.PmdReport.canGenerateReport(PmdReport.java:267)
	at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:119)
	at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.forkProjectLifecycle(DefaultLifecycleExecutor.java:1211)

**Comment by tabladrum** [comment]
Do you need to do sudo?

**Comment by benathmane** [comment]
Command : sudo mvn clean install package

Stack :
[INFO] Reactor Summary:
[INFO] 
[INFO] com.capitalone.dashboard:Hygieia ................... SUCCESS [  1.414 s]
[INFO] com.capitalone.dashboard:core ...................... SUCCESS [ 41.952 s]
[INFO] com.capitalone.dashboard:api ....................... SUCCESS [ 13.557 s]
[INFO] com.capitalone.dashboard:jenkins-build-collector ... SUCCESS [  5.747 s]
[INFO] com.capitalone.dashboard:sonar-codequality-collector SUCCESS [  2.280 s]
[INFO] com.capitalone.dashboard:subversion-collector ...... SUCCESS [  4.183 s]
[INFO] com.capitalone.dashboard:github-scm-collector ...... SUCCESS [  3.037 s]
[INFO] com.capitalone.dashboard:stash-scm-collector ....... SUCCESS [  4.697 s]
[INFO] com.capitalone.dashboard:versionone-feature-collector SUCCESS [  6.783 s]
[INFO] com.capitalone.dashboard:udeploy-deployment-collector SUCCESS [  5.202 s]
[INFO] com.capitalone.dashboard:jira-feature-collector .... SUCCESS [ 12.841 s]
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SUCCESS [  5.381 s]
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SUCCESS [  2.105 s]
[INFO] com.capitalone.dashboard:UI ........................ FAILURE [ 22.055 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:11 min
[INFO] Finished at: 2016-03-18T16:50:08+01:00
[INFO] Final Memory: 84M/368M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.27:bower (bower install) on project UI: Failed to run task: 'bower install' failed. (error code 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :UI

**Comment by amitmawkin** [comment]
look at this issue https://github.com/capitalone/Hygieia/issues/280

they did the same for resolving this

**Comment by tabladrum** [comment]
@benathmane closing this. If you run into issues, open a new one or re-open this one.
