### ISSUE TITLE
Java Problem: The expression of type Collection needs unchecked conversion to conform to Collection (2 cases)

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#440]
Description	Resource	Path	Location	Type
Type safety: The expression of type Collection needs unchecked conversion to conform to Collection<ObjectId>	CollectorServiceTest.java	/api/src/test/java/com/capitalone/dashboard/service	line 36	Java Problem
Type safety: The expression of type Collection needs unchecked conversion to conform to Collection<SVNLogEntry>	DefaultSubversionClient.java	/subversion-collector/src/main/java/com/capitalone/dashboard/collector	line 71	Java Problem

**Comment by satishc1** [comment]
Fixed.
