### ISSUE TITLE
Java Error: Type safety: Unchecked cast from Object to Map (2 cases)

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#441]
Remaining after cleanup merged:

Description Resource    Path    Location    Type
Type safety: Unchecked cast from Object to Map<String,String>   Dashboard.java  /core/src/main/java/com/capitalone/dashboard/model  line 84 Java Problem
Type safety: Unchecked cast from Object to Map<String,String>   PipelineServiceImpl.java    /api/src/main/java/com/capitalone/dashboard/service line 106    Java Problem

**Comment by nireeshT** [comment]
Fixed in PR https://github.com/capitalone/Hygieia/pull/916
