### ISSUE TITLE
Code Repo - Github Collector - Save button not working

### ISSUE THREAD

**Issue by VVasanth** [capitalone/Hygieia#443]
Hi Everyone,

I am facing below issue where I am not able to perform 'Save' operation in 'Configure' section of 'Code Repo'. When I click on 'Save' button, system does not respond and it stays as it is. 

From other threads, I found that api and collector needs to be run for this. I have executed both of them and both of them are running properly.

Could you please help me here?

I have pasted my properties file below for your reference:

#Database Name
spring.data.mongodb.database=dashboarddb

#Database HostName - default is localhost
spring.data.mongodb.host=127.0.0.1

#Database Port - default is 27017
spring.data.mongodb.port=27017

#Database Username - default is blank
spring.data.mongodb.username=db

#Database Password - default is blank
spring.data.mongodb.password=dbpass

#Collector schedule (required)
github.cron=0 0/5 * * * *

github.host=https://github.com/

#Maximum number of days to go back in time when fetching commits
github.commitThresholdDays=15

Command that I use to execute the github collector jar is:

java
 -jar target\github-scm-collector-2.0.0-SNAPSHOT.jar --spring.config.name=github
 --spring.config.location=D:\Hygieia\Hygieia-Hygieia-2.0.0\Hygieia-Hygieia-2.0.0
\github-scm-collector\github.properties

Appreciate your help!

Thanks.
V.Vasanth

**Comment by tabladrum** [comment]
@VVasanth Follow this property files format

   #Database Name 
    database=dashboarddb

    #Database HostName - default is localhost
    dbhost=10.0.1.1

    #Database Port - default is 27017
    dbport=9999

    #Database Username - default is blank
    dbusername=db

    #Database Password - default is blank
    dbpassword=dbpass

    #Collector schedule (required)
    github.cron=0 0/5 * * * *

    github.host=github.com

    #Maximum number of days to go back in time when fetching commits
    github.commitThresholdDays=15

**Comment by VVasanth** [comment]
@tabladrum - Thanks for the input!!

I am able to get the github details and closing this ticket.

**Comment by GPreksha** [comment]
Hi, I am unable to save button is not working in code repo.  Api and collectors are UP and RUNNING

The properties files is placed on  C:Hygieia-master\collectors\scm\github\target



#Database Name
database=dashboarddb

#Database HostName - default is localhost
dbhost=10.0.1.1

#Database Port - default is 27017
dbport=27017

#Database Username - default is blank
dbusername=

#Database Password - default is blank
dbpassword=

#Collector schedule (required)
github.cron=0 0/5 * * * *

github.host=github.com

#Maximum number of days to go back in time when fetching commits
github.commitThresholdDays=15



Please help to resolve it.

**Comment by GPreksha** [comment]
Hi, The  save button is not working in code repo. I filled in all the details

Repo type= GitHub
Repo URL=https://github.com/capitalone/Hygieia.git
Branch= master


Api and collectors are UP and RUNNING

The properties files is placed on C:Hygieia-master\collectors\scm\github\target

#Database Name
database=dashboarddb

#Database HostName - default is localhost
dbhost=10.0.1.1

#Database Port - default is 27017
dbport=27017

#Database Username - default is blank
dbusername=

#Database Password - default is blank
dbpassword=

#Collector schedule (required)
github.cron=0 0/5 * * * *

github.host=github.com

#Maximum number of days to go back in time when fetching commits
github.commitThresholdDays=15

Please help to resolve it.
