### ISSUE TITLE
Sonar Critical: Printf-style format strings should not lead to unexpected behavior at runtime 1

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#446]
File:DefaultSonarClient.java 
Line:83

    public CodeQuality currentCodeQuality(SonarProject project) {
>>>        String url = String.format(  project.getInstanceUrl() + URL_RESOURCE_DETAILS, project.getProjectId(), sonarSettings.getMetrics());

        try {

**Comment by satishc1** [comment]
Fixed.
