### ISSUE TITLE
Sonar Critical: Throwable.printStackTrace(...) should not be called

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#447]
File: Encryption.java
Line: 129

Snippet:
        } catch (EncryptionException e) {
            e.printStackTrace();

**Comment by tabladrum** [comment]
See https://github.com/capitalone/Hygieia/pull/449

**Comment by tabladrum** [comment]
Merged.

**Comment by jimzucker** [comment]
@tabledrum - thanks for fixing it, i ddint mean to create work for youbinwas opening tickets for changes i was going to do this week to cleanup sonar errrors(critical & blockers)
