### ISSUE TITLE
ProjectNameList under Team Name

### ISSUE THREAD

**Issue by sibaom** [capitalone/Hygieia#456]
Hi All,
[Hygieia.docx](https://github.com/capitalone/Hygieia/files/184078/Hygieia.docx)

I need something like this.in hygieia dashboard in feature widget.
If one will click on Team Name then Respective project Name will populate on another dropdown list bellow to team name drop down list .
Can you please give some information about this.The data is pull out from version one.
How to develop this kind of thing ,Is there any api is there which I can use.Please also let me know what UI changes should I need to do here.

In my approach my i m writing it in mongo java driver in API collector  to pull out data but its showing error. 
Thanks and Reagrds,
Siba Prasad

**Comment by nireeshT** [comment]
@sibaom  - Feature widget is now having the Project name and Team name drop downs when collecting data from Version One.  Rebase to the latest code base and check if this feature is applicable to you. Reopen the case if issue is not resolved.
