### ISSUE TITLE
I am having trouble getting the custom field value for "feature.jiraEpicIdFieldName". I ran the rest api against a jira issue that has super issue as EPIC. Please help here.

### ISSUE THREAD

**Issue by roykaushik07** [capitalone/Hygieia#460]
I am having trouble getting the custom field value for "feature.jiraEpicIdFieldName". I ran the rest api against a jira issue that has super issue as EPIC. Please help here.

**Comment by tabladrum** [comment]
@amp5208 - can you please take a look?

**Comment by amp5208** [comment]
@roykaushik07 , Thank you for reaching out regarding the jiraEpicIdFieldName.  To get this field name, you have to perform the following API actions manually against your Jira instance, using a sample Jira issue that has a super issue as Epic, as you have indicated:

```
# In Jira, your instance will have its own custom field created for "super story" or "epic" back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (e.g., epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraEpicIdFieldName=customfield_10400
```

Essentially, you have to use the Jira API to look up an existing issue that has a super issue tied to it, then Ctrl-F on the output for that super issue reference; the resulting field's name (usually starting with "customfield_") is the value that needs to be placed on this property.  This field ID is different for every installation of Jira, and different on most regions, given your internal Jira deployment plan.

The documentation above can be found as comments in the embedded properties file sample.  Let me know if you are still having this issue after trying to acquire the epic field name using the above instructions.  Note:  This question was also raised and answered in the following comment within an open GitHub issue; linking for clarity:  https://github.com/capitalone/Hygieia/issues/276#issuecomment-172060522

**Comment by smsuresh** [comment]
@roykaushik07  Better copy the result of the above mentioned URL into some json editor & navigate/search. You can easily find the value.

**Comment by amp5208** [comment]
@roykaushik07 , @smsuresh  is correct:  That is the best option for retrieving the value at this time:  Save the output from the Jira response to a JSON file, use a JSON linter to format or "beautify" the JSON, and look for the field name and value pair.

**Comment by satishc1** [comment]
Closed. Reopen if there are any problems. Use latest codebase and follow cleanup instructions provided in https://github.com/capitalone/Hygieia/pull/1137.
