### ISSUE TITLE
About sitespeed.io integration

### ISSUE THREAD

**Issue by softwareklinic** [capitalone/Hygieia#463]
I have a suggestion - I'm aware that the collector for appdynamics is being developed... but that is a paid product... and ofcourse there would be companies using the product... but there are lot of companies using open source products as well e.g. sitespeed.io... 

Sitespeed.io already has a plugin for Jenkins and it gives great length of details related to web page performance... we should see the hygieia publisher plugin can push this data directly to the performance widget...

**Comment by tabladrum** [comment]
See: https://github.com/capitalone/Hygieia/issues/438
Keeping both together.
