### ISSUE TITLE
stash only shows one commit!!

### ISSUE THREAD

**Issue by kv113813** [capitalone/Hygieia#470]
Hi All,

Stash only shows one commit on code repo:
I using below properties..
 - STASH_HOST=gitscm.com/
  - STASH_API=git.api=/rest/api/1.0/
  - STASH_CRON:-0 * * * * *
  - git.commitThresholdDays=30
  - git.firstRunHistoryDays=30
  - git.jpa.show-sql=true

code repo type=stash
code repo url= https://gitscm.com/projects/projectname/repos/demo.git
branch=master

**Comment by tabladrum** [comment]
Can you curl the stash api and see the result?

**Comment by kv113813** [comment]
I did curl, it gives all available commit details. UI shows only one commit
(curl -L https://gitscm.com/rest/api/1.0/projects/TOOL/repos/devopsdemo/commits)

**Comment by kv113813** [comment]
Please help me in fixing this

**Comment by tabladrum** [comment]
@softwareklinic @srid99 I think you are using stash. Did you see this in your instance?

**Comment by kv113813** [comment]
Please give your suggestions

**Comment by aryasunny** [comment]
@tabladrum @kv113813 I am getting the same issue when I am using bitbucket. It shows only one commit.

Were you able to get a solution for this ??

**Comment by MarkRx** [comment]
Try it now. PR #631 may have fixed this.

**Comment by satishc1** [comment]
@kv113813 Try with the latest codebase. Reopen if still an issue.
