### ISSUE TITLE
Issue reporting Jira Collector Stats

### ISSUE THREAD

**Issue by gillianwilson** [capitalone/Hygieia#471]
Hi

I've got my Jira collector running, and mapped the status' in my customised Jira worksflow etc. 
I can select my Jira project from the DB drop down. 
I can see the Dashboard listing the current active Sprint (with correct name) but the stats aren't reporting correctly.

Total = 60 (but i can't see how that matches anything in my Sprint)
WIP = 0
Done = 0
No Features listed under In Progress

Some thoughts:
1. Should this be the numeric ID or the name string? **feature.jiraIssueTypeId=**
2. Do issues need to have a specific Jira field present?  I've configured customised screens for my issues with only specific fields that I wanted.
3. Any other ideas of what I could check?

Thanks for your help in advance

**Comment by aryasunny** [comment]
@gillianwilson  
Can you please share your properties file.

#Jira API Query file names (String template requires the files to have .st extension) (required)
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo

What I am able to understand is that JIRA collector requires --> 
story.st, epic.st, projectinfo.st, memberinfo.st, sprintinfo.st, teaminfo.st, trendinginfo.st

And in each of these files, it requires a query. What kind of query is needed in each of these files.

Thanks

**Comment by amp5208** [comment]
@aryasunny , @gillianwilson :  Thank you for reaching out.  @aryasunny has already asked this question on the following post, which I will follow-up on:  https://github.com/capitalone/Hygieia/issues/497.  Please look to that post for further details.

**Comment by 415DomSmith** [comment]
@amp5208 Hey Arnold, 

I followed your response in #497, and it didn't address the question posted here. 

I was wondering if you can clarify where the JIRA API Query file names are being declared, how they are used, and what kind of query they need?

I couldn't find these files in the Hygieia file structure, or reference to them in the Jira API documentation... so maybe I'm misunderstanding how this info is being used.

I'm running in to issues querying data from an enterprise instance of Jira ran on a private node, and i'm wondering if these are at least part of the reason.

**Comment by amp5208** [comment]
@415DomSmith , Thank you for clarifying.  The API query files are embedded in source and do not need to be modified.

Your connectivity issues are more likely related to your configuration of the following properties:

<pre>
. . .
# In Jira, general IssueType IDs are associated to various "issue"
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a numerical ID reference to your instance's IssueType for
# the lowest level of Issues (e.g., "user story") specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType ID
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
feature.jiraIssueTypeId=Story
# In Jira, your instance will have its own custom field created for "sprint" or "timebox" details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name com.atlassian.greenhopper.service.sprint.Sprint;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraSprintDataFieldName=customfield_11112
# In Jira, your instance will have its own custom field created for "super story" or "epic" back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (e.g., epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraEpicIdFieldName=customfield_11111
. . .
</pre>

You may also reference more information on this configuration at the following issue comment:  https://github.com/capitalone/Hygieia/issues/276#issuecomment-172060522.  Please validate the above configurations and provide some log output for me to further debug.

**Comment by 415DomSmith** [comment]
@amp5208 Thanks Arnold,

Looks like i've got everything connected now, except for populating the sEvaluate field in MongoDB, and thus being able to display the score properly on the widget.

I understand that the way my companies Jira is set up (using a customfield instead of the out of the box field) is preventing sEvaluate from being updated.

But otherwise, it looks like everything is working.

**Comment by amp5208** [comment]
@415DomSmith , definitely understand your company's need - as mentioned, we have foreseen this need and we have an enhancement on the issue backlog to fix this.  Thank you for reaching out, and I hope you look forward to our future enhancements!

@tabladrum / @jdamick :  This issue has been resolved; please close this issue at your earliest convenience.

**Comment by MarkRx** [comment]
Issue #673. See if latest code with PR #682 fixed.

**Comment by satishc1** [comment]
Closed. Reopen if there are any problems. Use latest codebase and follow cleanup instructions provided in https://github.com/capitalone/Hygieia/pull/1137.
