### ISSUE TITLE
DB Setup alternatives

### ISSUE THREAD

**Issue by mcloud42** [capitalone/Hygieia#472]
Did anyone tried to setup Hygieia with an alternative database (non MongoDB)? Appreciate suggestion on alternatives.

**Comment by tabladrum** [comment]
We haven't tried with any other. 
Can be an interesting addition.

**Comment by softwareklinic** [comment]
is it generic enough to plug-in any other DB... or does the code have any dependency on mongo... if not - then we can try out some of the other options..

**Comment by tabladrum** [comment]
There is a MongoConfig class in the core. There are other springframework.data.mongodb imports in the code.

**Comment by sibaom** [comment]
I am also trying to implement MySql in hygieia  for one of my requirement. 
so instead of spring data mongo query is it possible to write named queries and different service 
in a collector?

**Comment by tabladrum** [comment]
I don't using RDBMS is a good choice for this.

**Comment by sibaom** [comment]
Hi ,

But if some project usings mysql and if suppose if we are trying to display the data in hygieia 
as a bar chart or line chart.so is that suitable.can you please say the reason why its not possible to 
configure with other db.is it performance over head or something other.
please give your response its something that i am looking for.
Thanks

**Comment by sajithmajeed** [comment]
Hello all

Do we know if there was any conclusion on this. Does Hygieia supports other non SQL databases ? Please update if there are any other databases supported.

Thanks

**Comment by satishc1** [comment]
We are hoping to get a PR contribution for this. Refer to https://github.com/capitalone/Hygieia/issues/929
