### ISSUE TITLE
Hygieia API list

### ISSUE THREAD

**Issue by harishamrale** [capitalone/Hygieia#475]
Hi, I am looking for Hygieia REST API list and each API purpose and syntax to call.
Please help me to get complete Hygieia api list with their description.

**Comment by tabladrum** [comment]
We have put swagger in. However, we hit a spring fox bug. Opened a ticket with Spring. In the mean time, you will probably have to look at the api controller and other codes.

**Comment by satishc1** [comment]
@harishamrale  Refer to https://github.com/capitalone/Hygieia/pull/453 You can pull up the swagger api and look at details for each RestController.
