### ISSUE TITLE
API to support other CI systems than Jenkins

### ISSUE THREAD

**Issue by binkley** [capitalone/Hygieia#480]
Do you have plans to support other CI systems than Jenkins?  Examples: Go, TeamCity.

The issue title includes "API" to cover either you building out that support, or providing an API for others to hook into Hygieia with alternate CI systems.

The HudsonClient interface in the build collector is, obviously, specific to Jenkins.

**Comment by tabladrum** [comment]
The API supports a data push from another CI. Our Jenkins plugin uses that API. We were trying to get swagger implemented for API documentation but got stuck with a spring bug. I can post the details of the API and a sample JSON a little later.

**Comment by tabladrum** [comment]
API end point to post build 
http://<hygieia>/api/build

Sample JSON:
``
{
  "number": "68",
  "buildUrl": "http://localhost:8082/job/Hygieia-Common/68/",
  "jobName": "Hygieia-Common",
  "buildStatus": "SUCCESS",
  "startTime": 1459463955301,
  "jobUrl": "http://localhost:8082/job/Hygieia-Common/",
  "instanceUrl": "http://localhost:8082/",
  "niceName": "LocalTopoJenkins",
  "endTime": 1459463964259,
  "duration": 8958,
  "sourceChangeSet": [
    {
      "scmRevisionNumber": "1edeba7c859a45d2a41b087a37505e58aca6893c",
      "scmCommitLog": "Added test line",
      "scmAuthor": "topo.pal",
      "scmCommitTimestamp": -1,
      "numberOfChanges": 1
    }
  ]
}
``

**Comment by ianceicys** [comment]
Definitely helpful. I am looking to hook into VSTS (Visual Studio Team Services) Build. https://msdn.microsoft.com/en-us/library/vs/alm/build/vs/define-build?f=255&MSPPError=-2147217396

**Comment by mrpudn** [comment]
We also support Bamboo now:
https://github.com/capitalone/Hygieia/tree/master/collectors/build/bamboo

**Comment by gshiva** [comment]
See this Team City ?

https://github.com/capitalone/Hygieia/issues/138
