### ISSUE TITLE
Why we need docker to run  API ,MongoDB and UI 

### ISSUE THREAD

**Issue by harishamrale** [capitalone/Hygieia#481]
HI,As per the installation instructions there is a docker to run API ,MongoDB and UI components.
I like to know why we are using docker here ,please help to understand .

**Comment by tabladrum** [comment]
Docker is an option. You do not need to.
You can always do the usual way as mentioned in the setup.

**Comment by softwareklinic** [comment]
We have found docker to be useful - especially if I have other teams who want to try out - they can just pull the image and get going quickly...

**Comment by tabladrum** [comment]
Closing this.
