### ISSUE TITLE
Sonar Credentials

### ISSUE THREAD

**Issue by emoshaya-cognito** [capitalone/Hygieia#482]
How does the sonar collector connect to our sonarqube server without credentials? When do you setup the username and password for sonar?

**Comment by tabladrum** [comment]
We do not support (yet) auth based collector for sonar. 
Will take this as an enhancement.

**Comment by subesokun** [comment]
Created PR to add sonar basic auth support but so far no feedback #512

**Comment by amitmawkin** [comment]
we will review it tomorrow, thanks for your cooperation

**Comment by satishc1** [comment]
Closed per comment by subesokun.
