### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by aryasunny** [capitalone/Hygieia#485]
I downloaded the source and imported all the projects as maven projects in eclipse.
After building them using Java 8, I get compilation errors where in few classes are not being available.

1) Qbuild.Java - 
2) QCodeQuality - com.capitalone.dashboard.model.QCodeQuality
3) QCommit - com.capitalone.dashboard.model.QCommit;
4) QScopeOwner
5) QTestResult

Am I missing any jar from the classpath ?? Confused.

Thanks

**Comment by tabladrum** [comment]
If you are building the modules independently, please make sure that you do a "mvn clean install" on Core module first.

**Comment by aryasunny** [comment]
Thanks for replying debabrata. 

I am getting an error on core module -->
"You need to run build with JDK or have tools.jar on the classpath". 

I have JDK1.8 added to the build path and i have tools.jar in the lib folder of my java installation. 
I went ahead and even added tools.jar to the classpath as an external jar but still that error persists.

I chose to ignore the error and ran a mvn clean install on core module, the build was a success.

But i still have 2 missing classes for the api module  --> 
1) QScopeOwner
2) QTestResult

Thanks

**Comment by aryasunny** [comment]
Thanks Topo. Was able to figure this out.
