### ISSUE TITLE
Hygieia build failed - api jar

### ISSUE THREAD

**Issue by MahaSannasi** [capitalone/Hygieia#486]
[INFO] Compiling 69 source files to C:\hygieia\api\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] \hygieia\api\src\main\java\com\capitalone\dashboard\request\WidgetReques
t.java:[104,27] error: cannot find symbol
[ERROR] \hygieia\api\src\main\java\com\capitalone\dashboard\request\WidgetReques
t.java:[120,27] error: cannot find symbol
[ERROR] \hygieia\api\src\main\java\com\capitalone\dashboard\service\DashboardSer
viceImpl.java:[107,39] error: cannot find symbol
[INFO] 3 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] com.capitalone.dashboard:Hygieia ................... SUCCESS [  8.828 s]
[INFO] com.capitalone.dashboard:core ...................... SUCCESS [ 30.829 s]
[INFO] com.capitalone.dashboard:api ....................... FAILURE [ 12.172 s]
[INFO] com.capitalone.dashboard:jenkins-build-collector ... SKIPPED
[INFO] com.capitalone.dashboard:sonar-codequality-collector SKIPPED
[INFO] com.capitalone.dashboard:subversion-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:github-scm-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:versionone-feature-collector SKIPPED
[INFO] com.capitalone.dashboard:udeploy-deployment-collector SKIPPED
[INFO] com.capitalone.dashboard:jira-feature-collector .... SKIPPED
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SKIPPED
[INFO] com.capitalone.dashboard:jenkins-test-result-collector SKIPPED
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SKIPPED
[INFO] com.capitalone.dashboard:stash-scm-collector ....... SKIPPED
[INFO] com.capitalone.dashboard:lisa-sv-collector ......... SKIPPED
[INFO] com.capitalone.dashboard:UI ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:01 min
[INFO] Finished at: 2016-04-08T04:52:59-07:00
[INFO] Final Memory: 53M/335M
[INFO] ------------------------------------------------------------------------

**Comment by tabladrum** [comment]
Can you do a fresh clone and try again?

**Comment by MahaSannasi** [comment]
I have done that.. 

[INFO] Running 'bower install' in C:\hygieia\UI
[ERROR] bower alasql#^0.2.4          ENOTFOUND Package alasql not found
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] com.capitalone.dashboard:Hygieia ................... SUCCESS [  1.717 s]
[INFO] com.capitalone.dashboard:core ...................... SUCCESS [ 13.427 s]
[INFO] com.capitalone.dashboard:api ....................... SUCCESS [  7.976 s]
[INFO] com.capitalone.dashboard:jenkins-build-collector ... SUCCESS [  6.947 s]
[INFO] com.capitalone.dashboard:sonar-codequality-collector SUCCESS [  2.459 s]
[INFO] com.capitalone.dashboard:subversion-collector ...... SUCCESS [  2.376 s]
[INFO] com.capitalone.dashboard:github-scm-collector ...... SUCCESS [  3.157 s]
[INFO] com.capitalone.dashboard:versionone-feature-collector SUCCESS [  6.245 s]

[INFO] com.capitalone.dashboard:udeploy-deployment-collector SUCCESS [  1.943 s]

[INFO] com.capitalone.dashboard:jira-feature-collector .... SUCCESS [  6.943 s]
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SUCCESS [  3.637
 s]
[INFO] com.capitalone.dashboard:jenkins-test-result-collector SUCCESS [  2.210 s
]
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SUCCESS [  4.635 s]
[INFO] com.capitalone.dashboard:stash-scm-collector ....... SUCCESS [  3.539 s]
[INFO] com.capitalone.dashboard:lisa-sv-collector ......... SUCCESS [  3.752 s]
[INFO] com.capitalone.dashboard:UI ........................ FAILURE [06:00 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:14 min
[INFO] Finished at: 2016-04-11T06:48:39-07:00
[INFO] Final Memory: 81M/422M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.25:
bower (bower install) on project UI: Failed to run task: 'bower install' failed.
 (error code 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :UI

**Comment by tabladrum** [comment]
@MahaSannasi Do you still have the issue? If not can you close this?
