### ISSUE TITLE
Dashboard.properties is to be present at what path ??

### ISSUE THREAD

**Issue by aryasunny** [capitalone/Hygieia#489]
When we say that API layer will need a properties file called dashboard.properties.

At what location it expects this property file to be present at ??

Thanks

**Comment by deepakasa** [comment]
Any name is fine. If you have your own then specify it in the command line as specified in the documentation.

https://github.com/capitalone/Hygieia/tree/master/api

**Comment by aryasunny** [comment]
This is what i did. I created a dashboard.properties file with the content

# dashboard.properties
dbname=dashboard
dbusername=db
dbpassword=dbpass
dbhost=localhost
dbport=27017

And placed this in the target folder of api module and then ran the command 
java -jar api.jar --spring.config.location="C:\Users\saryan2\Desktop\Hygieia-master\api\target\dashboard.properties"

Now even though i have mentioned port to be used as 27017. I am getting an error 

Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches PrimaryServerSelector. Client view of cluster state is {typ
e=UNKNOWN, servers=[{address=127.0.0.1:33333, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.
net.ConnectException: Connection refused: connect}}]

Why it is trying to connect to port 33333 when I have mentioned 27017 in the properties file :( :(

**Comment by deepakasa** [comment]
I have faced the same issue earlier... Update the property file @following location and rebuild Api and execute the command. The default properties file has the value of 3333

./src/main/resources/application.properties

**Comment by aryasunny** [comment]
So basically, configuration are being read from application.properties and not from dashboard.properties file. Then whats the point of command taking path of dashboard.properties ??

Thanks for the help Deepak. 

I have one more question. Do we need to do anything with the docker thing ?? Now I am opening this URL --> http://127.0.0.1:8080/api/dashboard and all i get is a blank page with []

I believe that should be it... right ?? 
These are basically REST APIs to pull data from MongoDB and to be shown on UI. So above URL will anyways not give anything as there is no data in my database right now. Is my understanding correct ??

**Comment by deepakasa** [comment]
It does read from the dashboard.properties or custom properties file. Its up to you if you would like to explore docker image 
For Dashboard to run 
Mongod needs to running
API needs to be running (its already up and running)
Dashboard UI needs to running ( from UI directory run the command gulp serve)
refer to the documentation for more details: https://github.com/capitalone/Hygieia/tree/master/UI

**Comment by aryasunny** [comment]
Ok thanks. One more thing. 
Collectors module basically would pull data from multiple tools and insert into mongoDB right ??

So for dashboard to show anything, shouldn't the collectors be up and running ??

I have MongoD running already but it doesn't have nay data right now.

Am I understanding this right ??

Thanks

**Comment by deepakasa** [comment]
Yes, Collectors needs to up and running for you to use the collector data in the dashboard. Please go through collector documentation.

**Comment by aryasunny** [comment]
I am trying to set-up the UI module and when I run the command --> bower install from the GIT shell, it gives me an error --> bower ENOENT        No bower.json present

I can see there is a bower.json that is present under UI project but not under the root (i.e project).

**Comment by aryasunny** [comment]
ran all this from inside UI module. Was able to get the UI working.

**Comment by aryasunny** [comment]
deepak, i am very new to front-end development. So wanted to ask you this.
is the front end developed in AngularJS ??
