### ISSUE TITLE
Clarification needed on the technology being used for hygieia

### ISSUE THREAD

**Issue by aryasunny** [capitalone/Hygieia#490]
Is there a document that clearly explains the technology/tools being used in hygieia.

My understanding is that 
There is a collector that runs and collects stats and inserts into MongoD.
A rest API is used to fetch this data from the MongoD
AngularJS is being used in UI module which invokes the REST APIs to render the view.
(Question - why installation of NodeJS is a requirement for UI module)

Is there any document that explains the code flow starting from collector to REST API to the AngularJS view rendering.

P.S - I am newbie in this world of Spring,AngularJS and related technologies.

**Comment by softwareklinic** [comment]
I created a presentation about it for internal audience - will eliminate proprietary stuff and share.

**Comment by tabladrum** [comment]
@aryasunny Please see the video for a quick reference.
@softwareklinic Looking forward to the presentation. Thanks!!!!

**Comment by aryasunny** [comment]
Topo,

I did see the video but this is the part I am confused about.
AngularJS is being used in UI module which invokes the REST APIs to render the view.
(Question - why installation of NodeJS is a requirement for UI module)

**Comment by tabladrum** [comment]
Need npm to build the package.

**Comment by softwareklinic** [comment]
Check my fork until the PR is approved softwareklinic/hygieia

**Comment by thotanarendranathreddy** [comment]
To run Angular JS we need Node JS
