### ISSUE TITLE
Hygieia Dashboard build is failed 

### ISSUE THREAD

**Issue by MahaSannasi** [capitalone/Hygieia#493]
Hi ,

Please anyboby help me on this 

[INFO] Node v0.12.0 is already installed.
[INFO] Found NPM version 2.7.1
[INFO]
[INFO] --- frontend-maven-plugin:0.0.25:npm (npm install) @ UI ---
[INFO] Running 'npm install --color=false --proxy=http://mahals:***@proxy.ebiz.
erizon.com:80' in C:\hygieia\UI
[ERROR] npm WARN package.json karma-phantomjs-launcher@0.1.4 No README data
[INFO]
[INFO] --- frontend-maven-plugin:0.0.25:bower (bower install) @ UI ---
[INFO] Running 'bower install' in C:\hygieia\UI
[ERROR] bower angular-animate#~1.3.4 ENOTFOUND Package angular-animate not foun

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] com.capitalone.dashboard:Hygieia ................... SUCCESS [  1.329 s]
[INFO] com.capitalone.dashboard:core ...................... SUCCESS [ 11.318 s]
[INFO] com.capitalone.dashboard:api ....................... SUCCESS [  6.407 s]
[INFO] com.capitalone.dashboard:jenkins-build-collector ... SUCCESS [  4.959 s]
[INFO] com.capitalone.dashboard:sonar-codequality-collector SUCCESS [  3.047 s]
[INFO] com.capitalone.dashboard:subversion-collector ...... SUCCESS [  2.016 s]
[INFO] com.capitalone.dashboard:github-scm-collector ...... SUCCESS [  2.875 s]
[INFO] com.capitalone.dashboard:versionone-feature-collector SUCCESS [  4.894 s

[INFO] com.capitalone.dashboard:udeploy-deployment-collector SUCCESS [  1.672 s

[INFO] com.capitalone.dashboard:jira-feature-collector .... SUCCESS [  5.589 s]
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SUCCESS [  3.25
 s]
[INFO] com.capitalone.dashboard:jenkins-test-result-collector SUCCESS [  1.922
]
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SUCCESS [  4.078 s]
[INFO] com.capitalone.dashboard:stash-scm-collector ....... SUCCESS [  2.779 s]
[INFO] com.capitalone.dashboard:lisa-sv-collector ......... SUCCESS [  2.969 s]
[INFO] com.capitalone.dashboard:UI ........................ FAILURE [ 24.796 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:25 min
[INFO] Finished at: 2016-04-08T07:31:06-07:00
[INFO] Final Memory: 85M/437M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.25
bower (bower install) on project UI: Failed to run task: 'bower install' failed
 (error code 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swi
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please re
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureEx
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the comman

[ERROR]   mvn <goals> -rf :UI

C:\hygieia>
C:\hygieia>
C:\hygieia>cd UI

C:\hygieia\UI>mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building com.capitalone.dashboard:UI 1.5.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ UI ---
[INFO]
[INFO] >>> maven-pmd-plugin:3.5:check (default) > :pmd @ UI >>>
[INFO]
[INFO] --- maven-pmd-plugin:3.5:pmd (pmd) @ UI ---
[INFO]
[INFO] <<< maven-pmd-plugin:3.5:check (default) < :pmd @ UI <<<
[INFO]
[INFO] --- maven-pmd-plugin:3.5:check (default) @ UI ---
[INFO]
[INFO] --- frontend-maven-plugin:0.0.25:install-node-and-npm (install node and
pm) @ UI ---
[INFO] Node v0.12.0 is already installed.
[INFO] Found NPM version 2.7.1
[INFO]
[INFO] --- frontend-maven-plugin:0.0.25:npm (npm install) @ UI ---
[INFO] Running 'npm install --color=false --proxy=http://mahals:***@proxy.ebiz.
erizon.com:80' in C:\hygieia\UI
[ERROR] npm WARN package.json karma-phantomjs-launcher@0.1.4 No README data
[INFO]
[INFO] --- frontend-maven-plugin:0.0.25:bower (bower install) @ UI ---
[INFO] Running 'bower install' in C:\hygieia\UI
[ERROR] bower operative#~0.3.1       ENOTFOUND Package operative not found
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27.969 s
[INFO] Finished at: 2016-04-08T07:31:54-07:00
[INFO] Final Memory: 20M/181M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.25
bower (bower install) on project UI: Failed to run task: 'bower install' failed
 (error code 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swi
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please re
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureEx
eption

**Comment by anadimisra** [comment]
I faced same issue, was building Hygieia-2.0.0 tag

**Comment by sibaom** [comment]
Before Build you should install Node 5.0 and 
run the command 
1.npm install -g bower and npm install -g gulp on command line as administrator.
2.npm install and bower install on UI root package.
run this -git config --global url."https://".insteadOf git://   on git then
bower install on UI package.
If you are facing problem then run npm clean chache first then run the above command.

**Comment by MahaSannasi** [comment]
Yeah I have done the steps which you mentioned and executed the "Bower install"


C:\hygieia\UI>bower install
bower ENOTFOUND     Package angular-ui-router not found

C:\hygieia\UI>cd node_modules

C:\hygieia\UI\node_modules>cd bower

C:\hygieia\UI\node_modules\bower>cd bin

C:\hygieia\UI\node_modules\bower\bin>bower install
bower ENOENT        No bower.json present

C:\hygieia\UI\node_modules\bower\bin>


Please tell what is missing here

**Comment by MahaSannasi** [comment]
but json file is there in the directory and their content is 


#!/usr/bin/env node

require('../lib/bin/bower');

**Comment by sibaom** [comment]
I think its not appropriate bower.json file.
{
  "name": "devops-dashboard",
  "version": "0.0.0",
  "dependencies": {
    "modernizr": "~2.8.3",
    "angular-animate": "~1.3.4",
    "angular-sanitize": "~1.3.4",
    "angular-route": "~1.3.4",
    "angular-cookies": "~1.3.4",
    "angular": "~1.3.4",
    "angular-ui-router": "~0.2.13",
    "angular-bootstrap": "~0.12.0",
    "angular-validation-match": "~1.5.0",
    "bootstrap-sweetalert": "~0.4.5",
    "operative": "~0.4.4",
    "angular-chartist.js": "~3.3.13",
    "chartist": "~0.9.5",
    "moment": "~2.9.0",
    "lodash": "~2.4.1",
    "components-font-awesome": "~4.2.0",
    "bootstrap": "~3.3.2",
    "hygieia-jstz-detect": "~1.0.5",
    "dexie": "~1.2.0",
    "ng-sortable": "~1.3.2",
    "regression-js": "~1.3.0"
  },
  "devDependencies": {
    "angular-mocks": "~1.3.4"
  },
  "resolutions": {
    "angular": "~1.3.4",
    "chartist": "~0.9.5"
  },
  "overrides": {
    "components-font-awesome": {
      "main": [
        "css/font-awesome.css",
        "fonts/*"
      ]
    },
    "regression-js" : {
      "main": [
        "src/regression.js"
      ]
    },
    "bootstrap": {
      "dependencies": {}
    },
    "chartist": {
      "main": [
        "./dist/chartist.js"
      ]
    }
  }
}


This is the actual bower file.I think there is a problem in installation procedure.of node,npm.Please try to clean cache.and go through the installation procedure step by step.Its working in my case

**Comment by sibaom** [comment]
try to run the command bower install in git.after enable the proxy.like  C:\hygieia\UI> bower install

**Comment by tabladrum** [comment]
@sibaom I think you are right... this seems like proxy related issue.

**Comment by tabladrum** [comment]
@MahaSannasi can we close this?

**Comment by trinathtiru** [comment]
Hello, i got the same error and i am doing this in my aws maching and trying to add the proxy details in setting.xml file based on the below url
http://capitalone.github.io/Hygieia/proxyauthentication.html

can u please guide me what details need to be added in the setting.xml file?

**Comment by rvema** [comment]
@trinathtiru : The change in settings.xml is required only if you are behind a proxy. Is that applicable for you?
