### ISSUE TITLE
Jenkins Plugin 

### ISSUE THREAD

**Issue by sibaom** [capitalone/Hygieia#494]
Hi,
I want to see all project names from jenkins in hygieia dashboard.So can you please say which plugin 
available from hygieia to see all projects in a drop down.I searched in hygieia-jenkins-plugin and jenkins-build-collector but unable to find such api  which give the information about projects from jenkins and also let me know how the jenkins plugin works to pull out information  in hygieia. 

Thanks and Regads,
Siba Prasad

**Comment by tabladrum** [comment]
Jenkins plugin is to push build, artifact, test etc information to Hygieia.
To get ALL projects, the collector needs to be run.

**Comment by sibaom** [comment]
if I hit my jenkins api -https://<jenkins......>/api/json?pretty=true
"jobs" : [
    {
      "name" : "ALM-VersionOne-IntegrationTool",
      "url" : "https://<       >/ALM-VersionOne-IntegrationTool/",
      "color" : "blue"
    },
    {
      "name" : "Archive",
      "url" : "https://<    >/job/Archive/"
    },
    {
      "name" : "BIS",
      "url" : "https://< >/job/BIS/"
    },
    {
      "name" : "BIS-Authentication",
      "url" : "https://<   >/job/BIS-Authentication/",
      "color" : "blue"
    },
    {
      "name" : "BIS-BatchCryptography",
      "url" : "https://<   >/job/BIS-BatchCryptography/",
      "color" : "blue"
    }
This type of json is coming but what suppose if i want to read projects which is under [Jobs-Archive,BIS,Authentication]
Like[ collecor-data.js- /api/collector/item/type/ ]if i hit then project list is coming.but in my case i want to see internal projects which linked to the root project.

Please give your suggestion

**Comment by sibaom** [comment]
and collector is also running in my machine @tabladrum

**Comment by tabladrum** [comment]
I am not sure if I understand what you are trying to do. Can you join the gitter chat?

**Comment by sibaom** [comment]
I joined gitter chat with same user name.
one more query is,in jnekins project configuration time under Post-build Actions>HygieiaPublish
1.Publish Build Status
2.Publish Artifact Information-Artifact Directory,Artifact Filename pattern,Artifact Group,ArtifactVersion
3.Publish Sonar Analysis
4.Publish Deployment Results
5.Publish Test Results
these options are coming so what kind of information should I give?
please suggest.

**Comment by tabladrum** [comment]
See this > https://github.com/capitalone/Hygieia/issues/502

**Comment by tabladrum** [comment]
Refer to issue# 502.
