### ISSUE TITLE
[ERROR] bower lodash#~2.4.1          ENOTFOUND Package lodash not found

### ISSUE THREAD

**Issue by MahaSannasi** [capitalone/Hygieia#495]
Please help on this

[ERROR] npm WARN package.json karma-phantomjs-launcher@0.1.4 No README data
[INFO]
[INFO] --- frontend-maven-plugin:0.0.25:bower (bower install) @ UI ---
[INFO] Running 'bower install' in C:\hygieia\UI
[ERROR] bower lodash#~2.4.1          ENOTFOUND Package lodash not found
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] com.capitalone.dashboard:Hygieia ................... SUCCESS [  1.281 s]
[INFO] com.capitalone.dashboard:core ...................... SUCCESS [ 12.923 s]
[INFO] com.capitalone.dashboard:api ....................... SUCCESS [  6.968 s]
[INFO] com.capitalone.dashboard:jenkins-build-collector ... SUCCESS [  6.299 s]
[INFO] com.capitalone.dashboard:sonar-codequality-collector SUCCESS [  3.094 s]
[INFO] com.capitalone.dashboard:subversion-collector ...... SUCCESS [  2.531 s]
[INFO] com.capitalone.dashboard:github-scm-collector ...... SUCCESS [  3.067 s]
[INFO] com.capitalone.dashboard:versionone-feature-collector SUCCESS [  6.170 s]

[INFO] com.capitalone.dashboard:udeploy-deployment-collector SUCCESS [  1.828 s]

[INFO] com.capitalone.dashboard:jira-feature-collector .... SUCCESS [  6.538 s]
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SUCCESS [  3.114
 s]
[INFO] com.capitalone.dashboard:jenkins-test-result-collector SUCCESS [  2.031 s
]
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SUCCESS [  4.093 s]
[INFO] com.capitalone.dashboard:stash-scm-collector ....... SUCCESS [  2.917 s]
[INFO] com.capitalone.dashboard:lisa-sv-collector ......... SUCCESS [  2.938 s]
[INFO] com.capitalone.dashboard:UI ........................ FAILURE [ 42.594 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:50 min
[INFO] Finished at: 2016-04-11T02:27:01-07:00
[INFO] Final Memory: 88M/436M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.25:
bower (bower install) on project UI: Failed to run task: 'bower install' failed.
 (error code 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :UI

**Comment by sibaom** [comment]
run npm install and bower install in UI root package.
build core then build hygieia package again

**Comment by tabladrum** [comment]
@MahaSannasi is your question is answered, can you close this?

**Comment by satishc1** [comment]
@MahaSannasi If this is still an issue, try adding a .bowerrc and run mvn again. https://github.com/capitalone/Hygieia/issues/823
