### ISSUE TITLE
Instructions for stash-scm-collector

### ISSUE THREAD

**Issue by aryasunny** [capitalone/Hygieia#496]
Are there any instructions available for stash-scm-collector ??

I am assuming that it would need application.properties file to run but what exactly are the tokens in that property file that this collector would be looking for ??

Thanks

**Comment by softwareklinic** [comment]
# Default server configuration
debug=true
spring.jpa.show-sql: true
# Default server configuration values

server.contextPath=/api
server.port=${PORT:0}
#server.port=${PORT:0}

# dashboard.properties
#dbhost= xxxxxxxxxx
dbhost= localhost
dbport= 27017
dbname= 
dbusername= 
dbpassword= 

#Collector schedule (required)
git.cron=0 0/1 * * * *


#mandatory
git.host = https://xxxx.xxxxxx.com/

#mandatory
git.api=/rest/api/1.0/

#Maximum number of days to go back in time when fetching commits
git.commitThresholdDays=15

#Credentials should be enter in the UI. Is not necessary.
#git.user=
#git.password=

**Comment by aryasunny** [comment]
Keyur,

For the property, git.api.

 /rest/api/1.0/, Is this an api exposed by stash ??

Shall i simply replace this as a value for this property

Source code of hygieia has /!api/2.0/repositories/ as value for this property.

Will either work ??

Thanks

**Comment by softwareklinic** [comment]
You need to make code change to read these properties inside the client code in collector

Sent from my iPhone

On Apr 11, 2016, at 2:59 PM, aryasunny <notifications@github.com<mailto:notifications@github.com>> wrote:


Keyur,

For the property, git.api.

/rest/api/1.0/, Is this an api exposed by stash ??

Shall i simply replace this as a value for this property

Source code of hygieia has /!api/2.0/repositories/ as value for this property.

Will either work ??

Thanks

**Comment by aryasunny** [comment]
I thought these properties are already being read and that is why we need to furnish these properties values to make the code work.

What is this git api being used for ??
source code has host as bitbucket.org and git.api as /!api/2.0/repositories/
So what i believe is that there is an api being exposed here --> bitbucket.org/!api/2.0/repositories/ which is being used inside the code.

so I i replace the value of host property from bitbucket.org to my internal bitbucket server then this URL --> MyinternalBitBucket/!api/2.0/repositories/ will not make any sense. then do i have to write an api that would do the same work as this api --> /!api/2.0/repositories/

**Comment by aryasunny** [comment]
This is what I am doing
I am giving the repository URL for my internal bitbucket server and a corresponding branch name.

I am getting connection timeout on that URL. Now this URL when I am trying to access through my browser it asks me for an username and password.But inside the code I am not giving any username or password. So will we get a connection timeout in this case because username and password was not provided.

And I really don't see this git.host and git.api being used anywhere.

Thanks

**Comment by aryasunny** [comment]
@softwareklinic will you have time to provide some help here

**Comment by softwareklinic** [comment]
Yes I will send out changes tonight - I may not have time to PR - but will upload the code and send you the link - which you can test / merge / PR

Sent from my iPhone

On Apr 11, 2016, at 8:10 PM, aryasunny <notifications@github.com<mailto:notifications@github.com>> wrote:


@softwareklinic<https://github.com/softwareklinic> will you have time to provide some help here

**Comment by aryasunny** [comment]
thanks keyur, I understand that you are writing some code for support for authentication.

But can you spare 2 minutes to answer this question of mine, it will help me understand the flow of the code. I will really appreciate that.

What is this git api being used for ??
source code has host as bitbucket.org and git.api as /!api/2.0/repositories/
So what i believe is that there is an api being exposed here --> bitbucket.org/!api/2.0/repositories/ which is being used inside the code.

so I i replace the value of host property from bitbucket.org to my internal bitbucket server then this URL --> MyinternalBitBucket/!api/2.0/repositories/ will not make any sense.
then do i have to write an api that would do the same work as this api --> /!api/2.0/repositories/

**Comment by aryasunny** [comment]
@softwareklinic @tabladrum - Need your help

I was looking into the code and found that there is a Rest service call being made to this URL --> https://<hostname provided in properties file>/<api provided in properties file>/reponame

So is this a REST api provided by bitbucket to give the stats of the repository provided in reponame ??

And so I can assume that my internal bitbucket server also will have this API exposed ??

**Comment by tabladrum** [comment]
I am not familiar with bitbucket api. I would google it up unless @softwareklinic knows it for sure.

**Comment by aryasunny** [comment]
thanks for replying. If this is not an api exposed by bitbucket, then how are we gathering stats of the repository to show on dashboard.

Sorry for asking so many questions

**Comment by aryasunny** [comment]
it does actually
https://developer.atlassian.com/static/rest/bitbucket-server/4.0.0/bitbucket-build-rest.html

**Comment by aryasunny** [comment]
@softwareklinic @tabladrum  - any suggestions/answer for the question

If this is not an api exposed by bitbucket, then how are we gathering stats of the repository to show on dashboard.

**Comment by aryasunny** [comment]
@softwareklinic @tabladrum - any insights into --> how are we gathering stats of the bitbucket repository to show on dashboard. What is the service that is giving us the stats for dashboard.

I created a repository on bitbucket, but when i use the below URL, I get "404 not found"
https://bitbucket.org/rest/api/1.0/aryasunny/renewal/commits?sha=feature/develop&since=2016-0
4-12T21:08Z

**Comment by softwareklinic** [comment]
Give me few - will get back

Sent from my iPhone

On Apr 12, 2016, at 9:33 PM, aryasunny <notifications@github.com<mailto:notifications@github.com>> wrote:


@softwareklinic<https://github.com/softwareklinic> @tabladrum<https://github.com/tabladrum> - any insights into --> how are we gathering stats of the bitbucket repository to show on dashboard. What is the service that is giving us the stats for dashboard.

I created a repository on bitbucket, but when i use the below URL, I get "404 not found"
https://bitbucket.org/rest/api/1.0/aryasunny/renewal/commits?sha=feature/develop&since=2016-0
4-12T21:08Z

**Comment by aryasunny** [comment]
Was able to make the bitbucket collector work

This has to be the properties in properties file

#mandatory
git.host=api.bitbucket.org
#mandatory
git.api=/2.0/repositories/

And had to made one change in the clientcode for bitbucket collector.

**Comment by tabladrum** [comment]
Sounds like we should have a separate bit bucket collector? Or should stash collector be able to handle it via properties configuration?

**Comment by softwareklinic** [comment]
I will check it out at our end.

**Comment by softwareklinic** [comment]
Most likely it is just properties… not a whole lot – since – it’s a natural progression of stash --> bitbucket

**Comment by aryasunny** [comment]
@tabladrum @softwareklinic 
for me, the stash-scm collector itself worked. We have client code for both stash and bit-bucket both in stash collector module itself

When working with stash I had to place @component annotation in class DefaultStashClient.java
When working with bit-bucket then, I had to place @component annotation in class DefaultBitbucketClient.java

and had to make small code change in both of these client files.

But it would be a good idea to have separate collector for bit-bucket. Will make things bit clear.

**Comment by tabladrum** [comment]
@aryasunny Can you do a PR for a new BitBucketCollector? Unless there is a smart way to handle the annotation? @softwareklinic - thoughts?

**Comment by aryasunny** [comment]
@tabladrum  I am too new for this thing. I would need some time before I can get a good handle on this to do a PR. Will keep you posted.

**Comment by aryasunny** [comment]
closing this issue. Will work on getting the code ready for PR
