### ISSUE TITLE
Need more information on Hygieia-jenkins Plugin configuration

### ISSUE THREAD

**Issue by gangadharahn** [capitalone/Hygieia#502]
Hi Team,

I am trying to setup the Hygieia-Jenkins Plugin. I am able to update the Jenkins with HPI file and able to see the post build configuration settings. but i am not sure what needs to be filled in the testxt boxes for for  Publish Artifact Information and Publish Deployment Results.

Could you please help me with this information.

1.Publish Artifact Information(Artifact Directory,Artifact Filename pattern,Artifact Group,ArtifactVersion)
2.Publish Deployment Results(Artifact Directory, Artifact File Name Pattern, Artifact Group,ArtifactVersion

Thanks
Ganga

**Comment by softwareklinic** [comment]
Check add build step

Sent from my iPhone

On Apr 13, 2016, at 6:56 AM, gangadharahn <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Team,

I am trying to setup the Hygieia-Jenkins Plugin. I am able to update the Jenkins with HPI file and able to see the post build configuration settings. but i am not sure what needs to be filled in the testxt boxes for for Publish Artifact Information and Publish Deployment Results.

Could you please help me with this information.

1.Publish Artifact Information(Artifact Directory,Artifact Filename pattern,Artifact Group,ArtifactVersion)
2.Publish Deployment Results(Artifact Directory, Artifact File Name Pattern, Artifact Group,ArtifactVersion

Thanks
Ganga

**Comment by tabladrum** [comment]
Artifact Directory - with respect to your workspace, where the artifacts (such as .jar) file are
Artifact Filename pattern - "*.jar" for example
Artifact Group - com.capitalone.dashboard for example
Artifact Version - "2.0.0" for example

**Comment by tabladrum** [comment]
Closing this as the question is answered.
