### ISSUE TITLE
Hygieia 2.0 with jdk 1.7 - what features would not work?

### ISSUE THREAD

**Issue by mcloud42** [capitalone/Hygieia#503]
I have Hygieia 2.0 version with jdk 1.7 (got the version before you upgraded to jdk 1.8) and had it working with Sonar, Subversion and Jenkins collectors.
I was wondering what features of Hygieia 2.0 would not work with jdk 1.7? Can I dockerize it with jdk 1.7?
It will really help me plan when I need to go to jdk 1.8? Appreciate your feedback.

**Comment by tabladrum** [comment]
There are some java 1.8 language features used in core package and else where. Sorry !

**Comment by tabladrum** [comment]
Closing this as the question is answered.
