### ISSUE TITLE
Request:  Feature Widget does not support Jira Kanban

### ISSUE THREAD

**Issue by amp5208** [capitalone/Hygieia#505]
**Narrative:**

As a user of the Jira Feature Widget, I want to be able to use the Feature widget for Kanban boards, so that my Kanban teams can better understand where they are currently regarding intent.

**Acceptance Criteria:**
- [x] Kanban (sprintless) boards in Jira show valid data on the Hygieia Feature Widget

**Use Case:**

```
GIVEN:  A sprintless Jira Kanban board
WHEN:  An issue type story is created with Remaining Estimate filled out
THEN:  The issue type story shows up in the Hygieia Feature Widget with the Remaining Estimate values
```

**Comment by amp5208** [comment]
@tabladrum , updated with full customizability requests from user @rashisaxena and @aleitner

**Comment by rashisaxena** [comment]
thanks @amp5208 

let me know when you want me to test the branch :)

**Comment by amp5208** [comment]
@rashisaxena , just an update:  We should be bringing in this work next week; I will let you know when our iteration is complete. :)

**Comment by rashisaxena** [comment]
Thanks Arnold :) Let me know when can I test.

Cheers,
Rashi

**Comment by rashisaxena** [comment]
Hi Arnold,

Any updates on this please?

Regards,
Rashi

**Comment by amp5208** [comment]
@rashisaxena , Thank you for checking back in.  There were a couple of small design changes that had to be made to the UI before completing this issue, which I have been working on in development.  However, I am currently at OSCON in Austin, TX, and will likely not be able to commit further work until after the convention.  For current status, feel free to look at my fork:  https://github.com/amp5208/Hygieia

**Comment by amp5208** [comment]
@rashisaxena , Please see my referenced pull request, #606 , and review at your leisure.  Your validation would be incredibly beneficial.

**Comment by rashisaxena** [comment]
Hi Arnold,

Thankyou for the update, really appreciate.

Could you please tell me how to proceed with testing, has this been merged
to master or released, if yes what is the tag name i have to checkout.

sorry not much familer with github pull requests.

Regards,
Rashi

**Comment by amp5208** [comment]
@rashisaxena , it was just merged today into the mainline, actually.  Please just pull from master and validate that you are able to see your Kanban and Scrum iterations separately in Jira/VersionOne.

**Comment by rashisaxena** [comment]
thanks Arnold.

I have compiled it and took the jar, started the collector, now its failing
at

 Unexpected error in Jira paging request of java.lang.RuntimeException
[java.net.SocketTimeoutException]

**Comment by rashisaxena** [comment]
also when i built and compiled from master branch i got this

[ERROR] Error: ENOENT: no such file or directory, lstat
'/data/data/rashi/Hygieia/UI/src/template-cache.js'
[ERROR]     at Error (native)
[ERROR]     at Object.fs.lstatSync (fs.js:887:18)
[ERROR]     at DestroyableTransform.TransformStream [as _transform]
(/data/data/rashi/Hygieia/UI/node_modules/gulp-angular-templatecache/node_modules/gulp-header/index.js:38:12)
[ERROR]     at DestroyableTransform.Transform._read
(/data/data/rashi/Hygieia/UI/node_modules/gulp-angular-templatecache/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
[ERROR]     at DestroyableTransform.Transform._write
(/data/data/rashi/Hygieia/UI/node_modules/gulp-angular-templatecache/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
[ERROR]     at doWrite
(/data/data/rashi/Hygieia/UI/node_modules/gulp-angular-templatecache/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
[ERROR]     at writeOrBuffer
(/data/data/rashi/Hygieia/UI/node_modules/gulp-angular-templatecache/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
[ERROR]     at DestroyableTransform.Writable.write
(/data/data/rashi/Hygieia/UI/node_modules/gulp-angular-templatecache/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
[ERROR]     at write
(/data/data/rashi/Hygieia/UI/node_modules/gulp-concat/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
[ERROR]     at flow
(/data/data/rashi/Hygieia/UI/node_modules/gulp-concat/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)

**Comment by amp5208** [comment]
@rashisaxena , Thank you for looking into this - I will verify and reply with any additional / new steps for building/running.

**Comment by rashisaxena** [comment]
Please let me know the next steps.

My organization is waiting for jira collector to work, thats the only thing
left. :)

**Comment by satishc1** [comment]
Closed.
