### ISSUE TITLE
Jenkins plugin compatible with Jenkins Pipeline

### ISSUE THREAD

**Issue by asperkins** [capitalone/Hygieia#511]
Are there plans to make the jenkins plugin compatible with Jenkins Pipeline?
https://github.com/jenkinsci/pipeline-plugin/blob/master/COMPATIBILITY.md

Having said that, I would actually prefer a non plugin method of publishing build data from the Jenkins Pipeline DSL, even if it's simple curl via the shell command.

**Comment by tabladrum** [comment]
Doing a curl is definitely an option. We have swagger documents available - even thought we hit a swagger/spring-fox bug that does not list all the APIs. You can look at the /api/build api and POST the right JSON.

**Comment by asperkins** [comment]
Thank you. I'll take a look.

**Comment by u506301** [comment]
@tabladrum Do you have any plans to release official support/features for Jenkins pipeline jobs? We work exclusively with these job types and would like to see whether we should wait for an updated build or start customizing our own installation.

**Comment by tabladrum** [comment]
We have started using the pipeline too and yes, we will need to have that too. Any help would be greatly appreciated too.

**Comment by imranaali** [comment]
@asperkins were you able to publish Jenkins Pipeline results into Hygieia dashboard if yes i would appreciate if you could share the approach.

Regards
Imran

**Comment by neilhunt1** [comment]
This would be awesome if it could be included. Jenkins Pipeline jobs are front-and-center in Jenkins 2.0 and appears to be the primary focus of Jenkins jobs going forward.

**Comment by MarkRx** [comment]
@pxk5958

**Comment by pxk5958** [comment]
@tabladrum can i work on it?

**Comment by tabladrum** [comment]
@pxk5958 +100. That will be fantastic. I went half way and then got side tracked.

**Comment by satishc1** [comment]
Closed. Use latest codebase for jenkins pipeline support.
