### ISSUE TITLE
gulp build step failing - Hygieia-2.0.0

### ISSUE THREAD

**Issue by gitrishi** [capitalone/Hygieia#526]
I am new to gulp build system and need a help in getting this issue resolved.

Build from source (Hygieia-Hygieia-2.0.0)  is failing with this error - 

Do we have CI workflow where I can fetch prebuilt tarball? or check the current build status?

---------------------------------

[INFO] --- frontend-maven-plugin:0.0.27:gulp (gulp build) @ UI ---
[INFO] Running 'gulp.js build --no-color' in /home/etmon/Hygieia-Hygieia-2.0.0/UI
[INFO] [17:27:39] Using gulpfile /home/etmon/Hygieia-Hygieia-2.0.0/UI/gulpfile.js
[INFO] [17:27:39] Starting 'build'...
[INFO] [17:27:39] Starting 'clean'...
[INFO] [17:27:39] Finished 'clean' after 14 ms
[INFO] [17:27:39] Starting 'assets'...
[INFO] [17:27:39] Starting 'themes'...
[INFO] [17:27:39] Starting 'fonts'...
[INFO] [17:27:39] Starting 'js'...
[INFO] [17:27:39] Starting 'views'...
[INFO] [17:27:39] Starting 'test-data'...
[ERROR]
[ERROR] events.js:141
[ERROR]       throw er; // Unhandled 'error' event
[ERROR]       ^
[ERROR] Error: Parse Error: <widget name="chatops" widget-title="ChatOps"</widget>
[ERROR]                 </div>
[ERROR]                 <div class="col-sm-6 col-md-12">
[ERROR]                     <widget name="deploy"></widget>
[ERROR]                 </div>
[ERROR]             </div>
[ERROR]         </div>
[ERROR]     </div>
[ERROR]
[ERROR]     <div class="container-fluid" widget-container dashboard="ctrl.dashboard" ng-if="!template.widgetView">
[ERROR]         <div class="col-xs-12">
[ERROR]             <widget name="pipeline" widget-title="Delivery Pipeline"></widget>
[ERROR]         </div>
[ERROR]     </div>
[ERROR]
[ERROR]
[ERROR]
[ERROR] </div>
[ERROR]     at new HTMLParser (/home/etmon/Hygieia-Hygieia-2.0.0/UI/node_modules/gulp-htmlmin/node_modules/html-minifier/src/htmlparser.js:236:13)
[ERROR]     at minify (/home/etmon/Hygieia-Hygieia-2.0.0/UI/node_modules/gulp-htmlmin/node_modules/html-minifier/src/htmlminifier.js:861:3)
[ERROR]     at Object.exports.minify (/home/etmon/Hygieia-Hygieia-2.0.0/UI/node_modules/gulp-htmlmin/node_modules/html-minifier/src/htmlminifier.js:1216:10)
[ERROR]     at objectAssign.fileName (/home/etmon/Hygieia-Hygieia-2.0.0/UI/node_modules/gulp-htmlmin/index.js:22:39)
[ERROR]     at module.exports (/home/etmon/Hygieia-Hygieia-2.0.0/UI/node_modules/gulp-htmlmin/node_modules/tryit/tryit.js:8:9)
[ERROR]     at minifyHtml (/home/etmon/Hygieia-Hygieia-2.0.0/UI/node_modules/gulp-htmlmin/index.js:21:9)
[ERROR]     at Transform.htmlminTransform [as _transform] (/home/etmon/Hygieia-Hygieia-2.0.0/UI/node_modules/gulp-htmlmin/index.js:51:7)
[ERROR]     at Transform._read (/home/etmon/Hygieia-Hygieia-2.0.0/UI/node_modules/gulp-htmlmin/node_modules/readable-stream/lib/_stream_transform.js:159:10)
[ERROR]     at Transform._write (/home/etmon/Hygieia-Hygieia-2.0.0/UI/node_modules/gulp-htmlmin/node_modules/readable-stream/lib/_stream_transform.js:147:83)
[ERROR]     at doWrite (/home/etmon/Hygieia-Hygieia-2.0.0/UI/node_modules/gulp-htmlmin/node_modules/readable-stream/lib/_stream_writable.js:313:64)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 35.450 s
[INFO] Finished at: 2016-04-25T17:27:40-04:00
[INFO] Final Memory: 23M/189M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.27:gulp (gulp build) on project UI: Failed to run task: 'gulp.js build --no-color' failed. (error code 1) -> [Help 1]

Thanks.

**Comment by tabladrum** [comment]
Can you take the master branch? Thanks.

**Comment by gitrishi** [comment]
sure, let me try it out. Thanks.

**Comment by gitrishi** [comment]
Build is successful with master branch and I just noticed the travis CI link.
For some reason release version is broken.

Thanks for your help.
