### ISSUE TITLE
Issue in using Hygieia 1.3.0 version !

### ISSUE THREAD

**Issue by AtulKamra** [capitalone/Hygieia#536]
I downloaded the below mentioned Hygieia relase.
https://github.com/capitalone/Hygieia/releases
Non Docker version / Binaries in Nexus Central version 1.3.0 source.zip for windows.

I am struggling to know what all steps we need to use for installing the Hygieia if we want to use it for dashboarding purpose. Already installed the MangoDB and it's client. Created a new db, user and pwd. Already compiled the api using "mvn install" command and created dashboard.properties file having information for MangoDB database. While running it using jar command it is giving me error api.jar file not found.

I am not sure about the steps and sequence to follow for using Hygieia for dashboard purpose. I mean do we need to compile api 1st then UI etc. Can you provide clear steps and usage of all modules please?

**Comment by tabladrum** [comment]
I would take the latest from master. And follow the exact steps. Note that mvn install will put the JAR in your local maven repo (/.m2/) and in the /target/ folder.

**Comment by satishc1** [comment]
@AtulKamra Follow steps listed in http://www.capitalone.io/Hygieia/getting_started.html . Run "mvn clean install package" from the root of Hygieia.
