### ISSUE TITLE
Where to change the Web URL from localhost:3000 to something like abc.com

### ISSUE THREAD

**Issue by gangadharahn** [capitalone/Hygieia#539]
Hi Team,

Can you please let me know where to configure the Hygieia web URL??

Thanks,
Ganga

**Comment by tabladrum** [comment]
You can do redirect on the apache server. Or can change this file (needs rebuild of UI): gulpfile.js.

**Comment by gangadharahn** [comment]
Thank you...

I will go for redirect from Apache server...
