### ISSUE TITLE
Git Metrics - Additional Views into Pulls/Issues/Contributor/Releases metrics

### ISSUE THREAD

**Issue by thummalapalli** [capitalone/Hygieia#541]
Using Hygiea as one tool across your enterprise for single view into your env, you can measure your progress for SDLC for your projects projects hosted on GIT.  Metrics such as Pulls created by day, or Issues, average times resolving issues/PRs, Top contributors, their ORGs (external data integration -interfaces will be provided along with a sample implementation) to measure how much of the contributions are coming from your own enterprise versus the rest  - and such. Please feel free to offer more ideas as you see or partner with us to implement this. There is a Pull Request (#540) open on which the development is happening. The PR work is complete and is awaiting approval by repo owners. The size of the work is pretty significant - so there might be a slight delay in approvals for the merge request.

Hygieia provides hooks into GIT as well along with Subversion and others but what this PR aims to do is explain that hook - which is just Commits for now - into multiple Views that would include developers, pulls, issues, organizational structures of our org, and metrics around repos. Also, one of the changes that’s introduced with this PR is to take the git org name as input instead of git repo name. Basically hit git against an org name and provide metrics against all repos of that org combined. Where applicable, the repo name is shown as well on the screens however.  In the very near future, we will actually take in Collection of org names and provide a roll view that’s applicable at higher levels - subject to app owner's interest.

Here are the same screen shots of the template - with more widgets to come and UI enhancement to show detailed view on click - each of these widgets would take org name as input - for now.
<img width="1172" alt="screen shot 2016-05-17 at 1 15 20 pm" src="https://cloud.githubusercontent.com/assets/16050334/15331949/af8dd850-1c31-11e6-909b-8e6221fbdb80.png">
<img width="1174" alt="screen shot 2016-05-17 at 1 15 37 pm" src="https://cloud.githubusercontent.com/assets/16050334/15331951/b295b46e-1c31-11e6-853e-56eae1e517c3.png">

Now - what do we want to know from GI. These are what I thought made sense the most
- Who is providing the code - meaning which developer or LOB is providing the code so that sort of helps you organize your teams accordingly. May be you want to see how your internal orgs are getting comfortable contributing to other repos of ANOTHER org, or how teams from outside of your department are contributing to your repos etc.  May be the word that we might be looking for is “InnerSourcing” and this helps managers observe the metrics on how this inner sourcing is going - it’s similar to you contributing to open source but here you are contributing to apps outside of your area - may be that’s your passion or hobby or strong point etc - what ever the case may be - your org would still benefit b/c you will end up breaking your organization silo’s
- Secondly -From git, You may want to know how your development pipe line is looking. Are PRs aging appropriately, are issues getting CLOSED promptly -What are the issues or PRs that took the longest - What are the issues that are still open for the longest etc

We can also add which developer from your org is contributing to what repo - but that may be a stretch at this time. There may be other metrics that I can’t think of at the moment - but here’s a little mention about the data. Well, GIT is your source for code data but the other important element is - developer data. In my case, I have some API’s which would provide me the people data such as Name, Manager, Business leads, IT leads etc and for every pull or issues that the collector pulls for that day/run, it uses these APIs to find that data and store them. That’s important b/c people change departments and it’s important to capture those contributor metrics right at that time. If you org has datasources that would keep such snapshot data, then you don’t need to implement that but if you don’t, you need to implement an interface that I included in this PR and I also checked in a Default Dummy client that you can use as a reference. 

Now, let’s get to the sample widgets this issue (PR #540) would be solving for.

These would tell you who your top contributors are so you can tell how you need to configure your team - may be call them a loosely configured team called “core committers” - or core developers etc - this is where you look for that. If you want to see which Line of Business or department or exec is contributing to your apps, this is here you look.  This is for the last 90 days - and 90 days should be a good measure of sustained and latest interest of others in your apps.
<img width="1334" alt="contribuitionsbydeveloperandlob" src="https://cloud.githubusercontent.com/assets/16050334/15324299/e8b79058-1c13-11e6-8eb8-d5fe17e3d5c1.png">
<img width="1342" alt="contributionsbymanagerarea" src="https://cloud.githubusercontent.com/assets/16050334/15324314/f2309abc-1c13-11e6-801f-f9c03ced4aef.png">

These four will give us a glimpse of trend of interest of PRs and Issues on your apps. A downward trend shows declining intent or upward trend shows you the increasing interest.The number of distinct developers in the first half of the quarter to the same on the second half shows how the developer base is expanding. The more the merrier. In this chart, we seem to have the almost equal number of distinct developers working on this organization - if are actually working on expanding this - you need to see more count of (distinct) developers on the last 45 days than the first 45 days of the 90 day period you are looking for.

<img width="1341" alt="pullspipeline" src="https://cloud.githubusercontent.com/assets/16050334/15324351/17e4d2d2-1c14-11e6-958d-c930c349fde7.png">
<img width="1344" alt="issuepipeline" src="https://cloud.githubusercontent.com/assets/16050334/15324357/1e933c18-1c14-11e6-84af-abb56fbcedc4.png">

The next two shows us the “aging chart of PRs and issues” -  You can see the top 5 in the table below.This is basically the days between closing or merging and opening of a PR or an issue divided by number that are closed that day. A good source of info for those looking to find why the pipeline isn't fast enough - or what PRs/issue are taking the longest.
<img width="1338" alt="agingofprsandissues" src="https://cloud.githubusercontent.com/assets/16050334/15324427/6a008f02-1c14-11e6-82dd-606f4342656b.png">

Click on each of the chart points to see what there are - or the table below shows the top 5 any way.
<img width="1307" alt="clickonidatapointstogetdetails" src="https://cloud.githubusercontent.com/assets/16050334/15324437/71b55ade-1c14-11e6-82ac-be49b599c1ad.png">

The last one is the Commit - actually this came out of the box - I didn’t do any changes here - it is just telling me there is some sustained action going on in the apps. 
<img width="848" alt="commits" src="https://cloud.githubusercontent.com/assets/16050334/15324493/a4c54ee8-1c14-11e6-9a7f-4c5e01c19191.png">

You can click on each of the chart points to see what those commit are

![Uploading CommitsDetails.png…]()

Now - this is more like a beginning of what I think we can add to this - the entries that are commented (below pic) are what I think should be added to give us additional metrics into finding what your most popular repo is, where your developers are contributing to from with in your orgs, latest pulls by repo etc.
<img width="887" alt="gittemplate" src="https://cloud.githubusercontent.com/assets/16050334/15324964/9ae5b69a-1c16-11e6-9f02-728ec7cea7dd.png">

I focussed mainly on the UI to convey what I added - but I added just two domain objects in Core and two JPA finders in api - and corresponding methods on GIT Collector.   What I am requesting is an acceptance of this PR so I can start working on one widget at a time - and even come back and refactor the code to see if we some how reuse the code more efficiently etc. 

Please review PR#540 where I implemented what I presented above and merge

**Comment by tabladrum** [comment]
See this PR https://github.com/capitalone/Hygieia/pull/1157
