### ISSUE TITLE
Issues in installing

### ISSUE THREAD

**Issue by dineshbabu01** [capitalone/Hygieia#542]
Hi, I am facing the below issue when trying to run "mvn -X clean install package". Please find the details below,
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T09:41:47-07:00)
Maven home: /usr/local/apache-maven-3.3.9
Java version: 1.8.0_71, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.71-1.b15.el6_7.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "2.6.32-573.18.1.el6.x86_64", arch: "amd64", family: "unix"

[INFO] Scanning for projects...
[DEBUG] Using transporter WagonTransporter with priority -1.0 for https://repo.maven.apache.org/maven2
[DEBUG] Using connector BasicRepositoryConnector with priority 0.0 for https://repo.maven.apache.org/maven2
Downloading: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-dependencies/1.2.5.RELEASE/spring-boot-dependencies-1.2.5.RELEASE.pom
[DEBUG] Writing tracking file /root/.m2/repository/org/springframework/boot/spring-boot-dependencies/1.2.5.RELEASE/spring-boot-dependencies-1.2.5.RELEASE.pom.lastUpdated
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.springframework.boot:spring-boot-starter-parent:[unknown-version]: Could not transfer artifact org.springframework.boot:spring-boot-dependencies:pom:1.2.5.RELEASE from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: unknown error @ org.springframework.boot:spring-boot-starter-parent:[unknown-version], /root/.m2/repository/org/springframework/boot/spring-boot-starter-parent/1.2.5.RELEASE/spring-boot-starter-parent-1.2.5.RELEASE.pom, line 4, column 10
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.springframework.boot:spring-boot-starter-parent:[unknown-version]: Could not transfer artifact org.springframework.boot:spring-boot-dependencies:pom:1.2.5.RELEASE from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: unknown error @ org.springframework.boot:spring-boot-starter-parent:[unknown-version], /root/.m2/repository/org/springframework/boot/spring-boot-starter-parent/1.2.5.RELEASE/spring-boot-starter-parent-1.2.5.RELEASE.pom, line 4, column 10

Any help on this will be greatly appreciated.

**Comment by dineshbabu01** [comment]
My pom.xml,

[root@lpdospwa00347 Hygieia-master]# cat pom.xml
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns="http://maven.apache.org/POM/4.0.0"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
<modelVersion>4.0.0</modelVersion>

  <groupId>com.capitalone.dashboard</groupId>
  <artifactId>Hygieia</artifactId>
  <packaging>pom</packaging>
  <version>2.0.0-SNAPSHOT</version>
  <name>${project.groupId}:${project.artifactId}</name>

<parent>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-parent</artifactId>
<version>1.2.5.RELEASE</version>
<relativePath/>
</parent>

<properties>
<spring-data-releasetrain.version>Gosling-RELEASE</spring-data-releasetrain.version>
<mongodb.version>3.0.2</mongodb.version>
<mongo>3.0.2</mongo>
<spring.version>4.1.7.RELEASE</spring.version>
<jackson.version>2.5.0</jackson.version>
<guava.version>16.0.1</guava.version>
<pmd.version>3.6</pmd.version>
<jacoco.version>0.7.6.201602180812</jacoco.version>
<joda-time.version>2.7</joda-time.version>
<joda-convert.version>1.8.1</joda-convert.version>
</properties>
  <licenses>
    <license>
      <name>The Apache License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>

  <developers>
    <developer>
      <name>Amit Mawkin</name>
      <email>amit.mawkin@capitalone.com</email>
      <organization>CapitalOne</organization>
      <organizationUrl>http://www.capitalone.com</organizationUrl>
    </developer>
    <developer>
   <name>Tapabrata Topo Pal</name>
   <email>tapabrata.pal@capitalone.com</email>
   <organization>CapitalOne</organization>
   <organizationUrl>http://www.capitalone.com</organizationUrl>
 </developer>
  </developers>

  <scm>
    <connection>scm:git:https://github.com/capitalone/Hygieia.git/</connection>
    <developerConnection>scm:git:https://github.com/capitalone/Hygieia.git/</developerConnection>
    <url>https://github.com/capitalone/Hygieia.git</url>
  </scm>

<distributionManagement>
    <snapshotRepository>
      <id>ossrh</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </snapshotRepository>
    <repository>
      <id>ossrh</id>
      <url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
    </repository>
  </distributionManagement>


<build>
<plugins>
<plugin>
<groupId>com.spotify</groupId>
<artifactId>docker-maven-plugin</artifactId>
<configuration>
<skipDockerBuild>true</skipDockerBuild>
</configuration>
<executions>
<execution>

<goals>
<goal>build</goal>
</goals>
</execution>
</executions>
</plugin>
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-pmd-plugin</artifactId>
<version>${pmd.version}</version>
<configuration>
<excludeRoots>
<excludeRoot>${project.basedir}/target/generated-sources/java</excludeRoot>
</excludeRoots>
<rulesets>
<ruleset>${project.parent.basedir}/pmd.xml</ruleset>
</rulesets>
</configuration>
<executions>
<execution>
<phase>validate</phase>
<goals>
<goal>check</goal>

</goals>
</execution>
</executions>
</plugin>
</plugins>
<pluginManagement>
<plugins>
<plugin>
<groupId>com.spotify</groupId>
<artifactId>docker-maven-plugin</artifactId>
<version>0.4.0</version>
</plugin>
<plugin>
<groupId>org.codehaus.mojo</groupId>

<artifactId>sonar-maven-plugin</artifactId>
<version>3.0.1</version>
</plugin>
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-compiler-plugin</artifactId>
<version>3.5.1</version>
<configuration>
<source>1.8</source>
<target>1.8</target>
</configuration>
</plugin>

<plugin>
<groupId>org.jacoco</groupId>
<artifactId>jacoco-maven-plugin</artifactId>
<version>${jacoco.version}</version> 
<executions>
    <execution>
<goals>
    <goal>prepare-agent</goal>
</goals>
    </execution>
    <execution>
<id>report</id>
<phase>verify</phase>
<goals>
    <goal>report</goal>
</goals>
    </execution>
</executions>
</plugin>
</plugins>
</pluginManagement>
</build>

     <profiles>
<profile>
<id>defaultBuild</id>
<activation>
<activeByDefault>true</activeByDefault>
</activation>
<modules>
<module>core</module>
<module>api</module>
<module>jenkins-build-collector</module>
<module>sonar-codequality-collector</module>
<module>subversion-scm-collector</module>
<module>github-scm-collector</module>
<module>stash-scm-collector</module>
<module>versionone-feature-collector</module>
<module>udeploy-deployment-collector</module>
<module>jira-feature-collector</module>
<module>jenkins-cucumber-test-collector</module>
<module>chat-ops-collector</module>
<module>UI</module>
</modules>
<build>
<pluginManagement>
<plugins>
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-compiler-plugin</artifactId>
<version>3.5.1</version>
<configuration>
<source>1.8</source>
<target>1.8</target>
</configuration>
</plugin>
</plugins>
</pluginManagement>
</build>
</profile>

<profile>
<id>release</id>
<modules>
<module>core</module>
<module>api</module>
<module>jenkins-build-collector</module>
<module>sonar-codequality-collector</module>
<module>subversion-scm-collector</module>
<module>github-scm-collector</module>
<module>versionone-feature-collector</module>
<module>udeploy-deployment-collector</module>
<module>jira-feature-collector</module>
<module>jenkins-cucumber-test-collector</module>
<module>chat-ops-collector</module>
</modules>
<build>
<plugins>
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-compiler-plugin</artifactId>
<version>3.5.1</version>
<configuration>
<source>1.8</source>
<target>1.8</target>
</configuration>
</plugin>
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-source-plugin</artifactId>
<version>2.2.1</version>
<executions>
<execution>
<id>attach-sources</id>
<goals>
<goal>jar-no-fork</goal>
</goals>
</execution>
</executions>
</plugin>
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-javadoc-plugin</artifactId>
<version>2.9.1</version>
<executions>
<execution>
<id>attach-javadocs</id>
<goals>
<goal>jar</goal>
</goals>
</execution>
</executions>
</plugin>
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-gpg-plugin</artifactId>
<version>1.5</version>
<executions>
<execution>
<id>sign-artifacts</id>
<phase>verify</phase>
<goals>
<goal>sign</goal>
</goals>
</execution>
</executions>
</plugin>
</plugins>
</build>

</profile>
</profiles>

</project>

**Comment by dineshbabu01** [comment]
[pom.txt](https://github.com/capitalone/Hygieia/files/251538/pom.txt)

**Comment by tabladrum** [comment]
Are you behind a proxy?

**Comment by dineshbabu01** [comment]
Yes, I am behind a proxy. I have also set http_proxy

**Comment by tabladrum** [comment]
Did you set the proxy in settings.xml for Maven?

**Comment by dineshbabu01** [comment]
yeah i did that as well... attaching the file for your reference.
[settings.txt](https://github.com/capitalone/Hygieia/files/252541/settings.txt)

**Comment by tabladrum** [comment]
Looks like you proxy settings are commented out.

**Comment by dineshbabu01** [comment]
hi, i am a newbie... Apologies for my ignorance. I don't see that commented out. Can you tell me how you are saying it is commented out and how to fix it? thanks for your help

**Comment by ananddave123** [comment]
I get the following error for "core" when i try to build the Hygieia project. all the rest components build fails

[INFO] --- apt-maven-plugin:1.1.3:process (default) @ core ---
[ERROR] execute error
org.apache.maven.plugin.MojoExecutionException: You need to run build with JDK or have tools.jar on the classpath.If this occures during eclipse build make sure you run eclipse under JDK as well
