### ISSUE TITLE
400 error using Hygieia API from local

### ISSUE THREAD

**Issue by jas5843** [capitalone/Hygieia#548]
We are currently experiencing a problem pushing test information from our local to Hygieia using the API in the Hygieia readme. The Hygieia plugin has been downloaded and fully configured and after running the Jenkins job that runs the test (and should then push the info to Hygieia), the output shows that it is finding the json on our local, but it is unable to push the information to Hygieia due to a 400 error (output is below). 

We have also tried accessing the api from our browsers and are seeing errors there as well (tried from multiple computers).

`
1 scenario ([32m1 passed[0m)
3 steps ([32m3 passed[0m)
0m22.387s
[CucumberReportPublisher] Compiling Cucumber Html Reports ...
[CucumberReportPublisher] Copying all json files from: C:\tests to reports directory: C:\...\builds\6\cucumber-html-reports
[CucumberReportPublisher] Found 1 json files.
[CucumberReportPublisher] 1. Found a json file: cucumber_report.json
[CucumberReportPublisher] Generating HTML reports
Hygieia: Failed Publishing Build Complete Data. Response Code: 400. 
Hygieia Test Result Publisher - Looking for file pattern '*.json' in directory C:\...\workspace
Hygieia Test Publisher: Processing file: C:\Users\oay495\.jenkins\jobs\ND Test Job GIT\workspace\cucumber_report.json
Hygieia: Failed Publishing Test Data. Response Code: 400. 
Finished: SUCCESS
`

**Comment by tabladrum** [comment]
Please make sure that you test connection after configuring the Jenkins global config. It should say success.

**Comment by jas5843** [comment]
When testing the connection we get a failure, but no other information is provided (i.e. no reason for failure). How can we troubleshoot that?

**Comment by jas5843** [comment]
Wrong api url was provided in the global configuration.

**Comment by swathireddy2808** [comment]
we had an issue with api connectvity i tried everything as on the hygieia document , the hygieia dashboard is up but no api connectivity.. even when i commit gulp serve i had an errors, 
![runing api with nohup](https://cloud.githubusercontent.com/assets/20541078/17027958/f61954d6-4f33-11e6-8413-8fd26964453c.JPG)
could any one help with the issue please..

can check the attcahments 
![hygieia page](https://cloud.githubusercontent.com/assets/20541078/17027895/cc5157de-4f33-11e6-9007-da354645e2a5.JPG)
![gulp serve errors](https://cloud.githubusercontent.com/assets/20541078/17027908/d4e06cd2-4f33-11e6-9481-fda277320a3a.JPG)
