### ISSUE TITLE
Hygieia-stash authentication problem

### ISSUE THREAD

**Issue by Matschick** [capitalone/Hygieia#550]
Hi, 
I tried to connect Hygieia to Bitbucket and therefore I used the stash-collector. 
I always get this error:
`GET request for "myURL.com" resulted in 401 (Unauthorized); invoking error handler`
 I tried to hardcode my login-values in the code but it dont work. 
Can somebody help? Is there a possibility to provide basic authentication with the stash collector ?

**Comment by oshingc** [comment]
Hi.
I wonder if ... did someone solve this problem?

**Comment by raynaya** [comment]
They use some key for login . I also wasnt able to make it work and did a small workaround for this . Add the below code in your class DefaultBitbucketServerClient.java after line no 96.

```
if (decryptedPassword.equals("")) {
        decryptedPassword = "Yourpassword";
        repo.setUserId("YourUsername");
      }
```

But ofcourse not a nice way . Better understand how the key works.

**Comment by MarkRx** [comment]
See #664. There currently is not a way to set this up in the UI.

**Comment by satishc1** [comment]
@Matschick Functionality merged in https://github.com/capitalone/Hygieia/pull/835
Refer to the "Encryption for private repos" section in the UI module readme.
