### ISSUE TITLE
Jira Collector NPE

### ISSUE THREAD

**Issue by Matschick** [capitalone/Hygieia#555]
I tried to include our JIRA to Hygieia Dashboard. But I always get a NPE in Jira-Collector.

This is the log-file:

```
hygieia-jira | 2016-05-10 08:27:06,304 ERROR c.c.d.c.s.FeatureDataClientSetupImpl - Unexpected error in Jira paging request of java.lang.NullPointerException
hygieia-jira | [null]
```

And the docker-compose settings:

```
hygieia-jira-feature-collector:
image: hygieia-jira-feature-collector:latest
container_name: hygieia-jira
volumes:
 - ./logs:/hygieia/logs
links:
 - mongodb:mongo
 - hygieia-api
environment:
  - JIRA_BASE_URL=https://our-jira.com/tracker/base64
  - JIRA_CREDENTIALS=b2ZhMmFidDpibsdfGlkbWlsdfzYWfsfdub37527lpbmc=
  - JIRA_ISSUE_TYPE_ID=267
  - JIRA_SPRINT_DATA_FIELD_NAME=customfield_14290
  - JIRA_EPIC_FIELD_NAME=customfield_15590
```

**Comment by tabladrum** [comment]
@amp5208 help!

**Comment by amp5208** [comment]
@Matschick , Thank you for reaching out regarding your JiraFeatureCollector issue.  It appears that you are missing several properties that should be passed through as environment variables for this to run in Docker.  Also, one of your properties is incorrect.

As of the incorrect property, _JIRA_ISSUE_TYPE_, this should be a string variable (non-oblique ID).  For issue-type-story, it should be just <code>Story</code>

Also, you appear to be missing overrides for, at minimum, the field mapping properties.  Full explanation for using field mappings and examples can be found at this issue's comment:  https://github.com/capitalone/Hygieia/issues/276#issuecomment-196324494

**Comment by satishc1** [comment]
Closed.
