### ISSUE TITLE
Cannot access api from UI

### ISSUE THREAD

**Issue by kyosong** [capitalone/Hygieia#56]
when I use gulp serve to bring up UI, after i sign in, i cannot create a new dashboard, and found the following exception. Actually, my api is installed in tomcat with port 8080. 

I didn't see any documentation for this portion in the github, did I miss anything? 

http://localhost:3000/api/dashboard/mydashboard/kyosong Failed to load resource: the server responded with a status of 404 (Not Found)

![image](https://cloud.githubusercontent.com/assets/5901392/9217491/c7b3c2fe-40fa-11e5-9531-91b840febdc8.png)

**Comment by amitmawkin** [comment]
kyosong,
Looks like the api layer has not started correctly, You can do a test to see if the api layer has loaded correctly http://localhost:8080/api/dashboard to see if your browser returns a JSON back.
Do send us a screen shot of the response of above .

**Comment by kyosong** [comment]
Thanks Amit, I found the Dashboard_pro has not been set properly under my zsh. When I switch to bash, it works fine now. 

Let's close the issue.
