### ISSUE TITLE
issue in retrieving sprint info for jira collector

### ISSUE THREAD

**Issue by bhartikukreja2015** [capitalone/Hygieia#563]
@tabladrum  Is there any proper format for creating query for sprintInfo.st file

**Comment by tabladrum** [comment]
@amp5208 - help!

**Comment by amp5208** [comment]
@bhartikukreja2015 , Thank you for reaching out regarding your JirFeatureCollector question.  To answer your direct question, there is no need to modify or change the embedded sprintInfo.st query template file.  Instead, you have to ensure that the following Jira custom field property declarations match your Jira implementation:

```properties
# In Jira, general IssueType IDs are associated to various "issue"
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a numerical ID reference to your instance's IssueType for
# the lowest level of Issues (e.g., "user story") specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType ID
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
feature.jiraIssueTypeId=Story
# In Jira, your instance will have its own custom field created for "sprint" or "timebox" details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name com.atlassian.greenhopper.service.sprint.Sprint;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraSprintDataFieldName=customfield_10007
# In Jira, your instance will have its own custom field created for "super story" or "epic" back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (e.g., epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraEpicIdFieldName=customfield_10400
```

This question has also been answer in more detail at the following issue:  https://github.com/capitalone/Hygieia/issues/266#issuecomment-172063603 .  Additionally, I am currently building a feature to further enable Kanban iterations (or lack thereof) in Hygieia.  Status on this can be found here:  https://github.com/capitalone/Hygieia/issues/505

Please let me know if you are still having issues after verifying your custom field configurations.

**Comment by ghouspasha** [comment]
@amp5208 there is no such sprintInfo.st file embedded in the module, my requirement is  to track the no of tasks inside the a sprint and classify them as done or inprogress.
I dont find any of the sprintInfo methods of FeatureCollectorRepository interface being called anywhere.
Could you pls help me out on this !!!

**Comment by amp5208** [comment]
@ghouspasha , thank you for clarifying.  In that case, you should redeploy Hygieia with the following configuration:

```bash
feature.jiraIssueTypeId=Sub-Task
```

Then you will need to use the built-in APIs for Hygieia to query active teams/projects and their respective issue-type-subtasks.  If your business need for analytics is greater than what the API currently handles, please either contribute back to the API, or simply use the MongoDB connection directly.  A sample API call that will give you valid data is as follows: [http://localhost:3000/api/iteration/12345?component=57279032bc7cec1c6131933f](http://localhost:3000/api/iteration/12345?component=57279032bc7cec1c6131933f)

Regarding the _storyInfo.st_ file, I apologize for the confusion:  The feature collectors use certain string template files for prepared queries to MongoDB, one of which is not storyInfo.st.

Regardless, you will not be able to query MongoDB directly for sprint/iteration data, as it is combined with issue-type-story/subtask data.  I will also note, this product was only tested using issue-type-story data, or custom fields that are story-like; I am unsure of the exact behavior as it works with other issue types configured.

Please let me know if you have any additional questions regarding the feature widget.

**Comment by satishc1** [comment]
Closed. Reopen if there are any problems. Use latest codebase and follow cleanup instructions provided in https://github.com/capitalone/Hygieia/pull/1137.
