### ISSUE TITLE
Test Type Dropdown not working with latest version of Jenkins

### ISSUE THREAD

**Issue by jas5843** [capitalone/Hygieia#566]
We are trying to use the plugin on a local instance of Jenkins. We have the latest version of Jenkins 1.651.1 installed. After installing the HPI file from Nexus, we are able to add the plugin to our Jenkins job. However, when we attempt to configure the plugin, the "Test Type" field is not enabled and does not provide a drop down to select values.

**Comment by tabladrum** [comment]
Which version of Java are you running your Jenkins on?

**Comment by jas5843** [comment]
JDK 1.7.0_21

**Comment by jas5843** [comment]
Fixed by downloading Java 1.8.
