### ISSUE TITLE
Some new incorrect MVN setting introduced

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#567]
I will clean these up:

Description	Resource	Path	Location	Type
Duplicating managed version 1.1.1 for json-simple	pom.xml	/stash-scm-collector	line 114	Maven pom Loading Problem
Overriding managed version 4.1.7.RELEASE for spring-web	pom.xml	/stash-scm-collector	line 108	Maven pom Loading Problem

**Comment by tabladrum** [comment]
@jimzucker Thanks!
