### ISSUE TITLE
default port

### ISSUE THREAD

**Issue by tonyvilliams** [capitalone/Hygieia#580]
We have our apps hosted on custom ports, i.e. not default 80 or 443.
example https://jira:8090 & https://stash:9090

We were not able to make connection from the respective apps after deploying the Jar files. 
So after a reading the code for Hygieia, understood that it connects to the respective apps/websites only on default ports and any other custom ports are not processed even after mentioning in application.properties file. 

please suggest if any additional config changes needed to get the connection up and running.  or any other work arounds to fix this.

**Comment by satishc1** [comment]
@tonyvilliams Please post the error / exception that you are seeing in the collector log.

**Comment by satishc1** [comment]
Hygieia has different collectors for talking to different apps like jira, stash, github etc. Every collector has a properties file that defines connection settings for the app it collects from. If you have defined the connection settings properly it should talk to the app. Let us know if there are exceptions in the collector log.

Closed. Reopen if still an issue.
