### ISSUE TITLE
Stash collector using wrong rest url

### ISSUE THREAD

**Issue by asperkins** [capitalone/Hygieia#583]
When the stash collector runs I'm seeing 

WARN  o.s.web.client.RestTemplate - GET request for "https://itec-stash.fmr.com/rest/api/1.0/scm/plxxxxxx/plxxxxxxap0xxxx-abcd/commits?sha=master&since=2016-05-20T21:20Z" resulted in 404 (2501); invoking error handler
ERROR c.c.d.c.DefaultBitbucketClient - 404 2501:https://itec-stash.fmr.com/rest/api/1.0/scm/plxxxxxx/plxxxxxxap0xxxx-abcd/commits?sha=master&since=2016-05-20T21:20Z

This doesn't appear to be the correct rest url based on stash docs. It should be something like

/rest/api/1.0/projects/plxxxxxx/repos/plxxxxxxap0xxxx-abcd/commits/?until=master

My config for the collector

#Database Name
database=dashboard
#Database HostName - default is localhost
dbhost=172.17.0.4
#Database Port - default is 27017
dbport=27017
#Database Username - default is blank
dbusername=db
#Collector schedule (required)
git.cron=0 0/5 * * * *
    #mandatory
git.host=itec-stash.fmr.com/
git.api=/rest/api/1.0/
#Maximum number of days to go back in time when fetching commits
git.commitThresholdDays=15

**Comment by sibaom** [comment]
yes for me also for different host and api its not working and showing 404 when collector runs.Unable to find new commits

**Comment by sibaom** [comment]
For statsh  you need to form proper host and api and change your DefaultBitbucketClient accordingly.
Because in hygieia they have it for Bitbucket server so for your host and api you need little bit modification.In my case its working fine.

**Comment by sibaom** [comment]
the URL like bellow-
https://*****/stash/rest/api/1.0/projects/<projectname>/repos/<branchname>/commits?sha=master&since=2016-05-24T10:27Z        
api should be-stash/rest/api/1.0   take proper sub string in DefaultBitbucketClient @asperkins

**Comment by sibaom** [comment]
https://*****/stash/rest/api/1.0/projects/repos/commits?sha=master&since=2016-05-24T10:27Z

**Comment by sibaom** [comment]
the URL like bellow-
https://*****/stash/rest/api/1.0/projects/repos/commits?sha=master&since=2016-05-24T10:27Z

api should be-stash/rest/api/1.0 take proper sub string in DefaultBitbucketClient @asperkins

**Comment by asperkins** [comment]
I'm using Atlassian Stash v3.10.2. Is this compatible?

**Comment by sibaom** [comment]
yes

**Comment by asperkins** [comment]
Are you saying that I need to modify the java code to fix the rest URL used? I had assumed there was some way to get the collector to use the defaultstashclient, which I also assumed would work.

**Comment by asperkins** [comment]
Btw, does the stash collector support authentication? If so, how to configure it?

**Comment by MarkRx** [comment]
Take a look at #609

**Comment by asperkins** [comment]
Thank you. I'll close this issue and follow 609. Cheers.
