### ISSUE TITLE
JIRA collector

### ISSUE THREAD

**Issue by dineshbabu01** [capitalone/Hygieia#589]
My company uses story point estimation and doesn't use the standard time estimate fields. I tried changing the collector to look for the custom field, but got the below errors when i run the collector. 

-Unexpected error caused while mapping data from source system to local data store.
For Input string: "Issuerfield(id=customfield_10002,name=Story Points,type=null, value=3.0)

Have anyone tried to change the setting to work for StoryPoint estimation?

Any help on this will be greatly appreciated?

**Comment by MarkRx** [comment]
This is actually on my list of things to do for my company. I'll have a PR for it within a few weeks.

**Comment by MarkRx** [comment]
PR #682 added this feature.

**Comment by satishc1** [comment]
Closed per comment above.
