### ISSUE TITLE
Hygieia 2.0 product dashboard

### ISSUE THREAD

**Issue by git4giri** [capitalone/Hygieia#604]
Hi,

I've successfully installed Hygieia 2.0 and all the collectors are working fine and the changes are reflecting correctly in normal team dashboard. But issue with the product dashboard, it's showing the commits flow only in the **Commits** and **Build** columns, other than that all the deployment stages [ **Dev, QA, Int, Perf, Prod** ] are empty... no any information. 
See attached screenshot
![image](https://cloud.githubusercontent.com/assets/12898310/15680272/b3f04738-2772-11e6-9c86-ac05536d4648.png)

I didn't get any clue how to resolve that, can you please help me out on this issue.

**Comment by git4giri** [comment]
Hi Tapabrata,
here is the answers...
1. UrbanCode Deploy as deployment tool
2. I've configured the deployment widget and there all the information showing perfect in team dash.
3. Yes I configured the team pipeline and here is the issue as I told earlier... it's not showing any info for deployment stages.

**Comment by tabladrum** [comment]
Can you share screen shots of the Deployment widget and the Pipeline?

**Comment by git4giri** [comment]
![ss1](https://cloud.githubusercontent.com/assets/12898310/15775500/cce9e076-299f-11e6-9d1e-aee88cae2e4b.png)
![ss2](https://cloud.githubusercontent.com/assets/12898310/15775510/d8f0770e-299f-11e6-9f87-b538e45310c0.png)

**Comment by git4giri** [comment]
Hi Tapabrata,
Thank you so much for the quick response, above are the screenshots of Deployment widget and the Pipeline of a DEMO project. Here is the team dashboard screenshot of that...

![ss3](https://cloud.githubusercontent.com/assets/12898310/15775666/caffed0e-29a0-11e6-8d6b-03a769b7da7e.png)

**Comment by tabladrum** [comment]
Ok. So I think I know what is missing. Before that, let me explain the links that happens in Hygieia.
Code commits are from Github or Svn etc. 
Builds are from Jenkins and that produces a ChangeSet and Hygieia captures - this change sets matched with commits determine which commits are in Build stage.
The Jenkins build produces artifacts with version number that are deployed to environments such as Dev, QA etc. Hygieia needs to know the artifacts with version number produced in Jenkins build job. That's why the Hygieia Jenkins plugin is there to push that information to Hygieia. 

I think it is also possible to do the same using Jenkins collector, except, the collector needs to know what artifacts information to pull as Jenkins workspace will have everything.

Did you install the Hygieia Jenkins plugin in your jenkins? See the readme under Jenkins plugin page.

**Comment by git4giri** [comment]
Yes, I've installed the Jenkins plugin also...
![ss4](https://cloud.githubusercontent.com/assets/12898310/15786064/2c302706-29d8-11e6-8934-23b45ac7e3b7.png)

![ss5](https://cloud.githubusercontent.com/assets/12898310/15786076/38edd47a-29d8-11e6-8b1e-1aacb2ac7ca4.png)
but I have tried this too for the project.... still no joy
Maybe I've filled wrong info there... can you please elaborate what details I need to put here... thanks

**Comment by tabladrum** [comment]
Assuming you have a jar file say myapp-2.0.1.jar that gets built in your jenkins job and the jar file is created in jenkins workspace/target folder, these are the possible values:
Artifact Directory: /target
File name pattern: *.jar
Artifact group: com.mycompany.app
Artifact version: <optional> - the plugin can exract the version from the jar file name. If the jar file name does not have the version, enter the version number here.

**Comment by git4giri** [comment]
Hi, 
It's a dynamic web project and after build it's generating a .ear file as a build artifact, so now what would be the **Artifact group** ?

**Comment by git4giri** [comment]
I've tried this plugin option too... but no success, 
If possible, we can meet over a **skype** meeting and I'll share my screen with you and we'll try to find out solution of this issue.
Or else tell me what information do you need to sort out the issue. ...thanks

**Comment by tabladrum** [comment]
skype like call would be good. What's your contact info?

**Comment by git4giri** [comment]
yep,
I'm working from India and I'm available during 2PM to 11PM IST.
My skype ID:subrgiri
Let me know your skype id and availability... will setup a meeting in common availability time

**Comment by git4giri** [comment]
Hey, what about the meeting? Please...

**Comment by tabladrum** [comment]
Hi.. it appears that I can't use Skype on my laptop or phone. Can you send me your email id ? Mine is tapabrata.pal@capitalone.com

**Comment by git4giri** [comment]
Hi Tapabrata,
I have a Zoom account, if possible we can meet over zoom meeting also, please confirm and tell me your availability, I'll send meeting invitation to above email...

**Comment by git4giri** [comment]
Hi, please confirm, really want to solve the issue...

**Comment by ashnaa** [comment]
I am also facing the same issue . If we can have a call or a skype to do this. My deployment tool is octopus and I am getting Commit and Build data in product dashboards, but other environments are not getting populated. I had confugured the pipeline view in team dashboards as well

**Comment by praveenkanna** [comment]
@git4giri is this issue resolved ?? i'm still facing this issue. I have created a pipeline and i have 2 environments tried all the above steps.. no luck !! please let me know if it done.

**Comment by tabladrum** [comment]
@satishc1 @praveenkanna may be a good idea to get on a Google Chat.

**Comment by satishc1** [comment]
@git4giri @praveenkanna @ashnaa @tabladrum 
Please refer https://github.com/capitalone/Hygieia/issues/884 for info on configuring the pipeline. 

If that doesn't help you can ping us on gitter.im and we can try and setup a time for google chat.

**Comment by praveenkanna** [comment]
I dont have any problem in configuring team dashboard.. Even though i have
a pipeline setup i m not able to see anything in product dashboard..

**Comment by praveenkanna** [comment]
@satishc1 I dont have any problem in configuring team dashboard.. Even though i have
a pipeline setup i m not able to see anything in product dashboard..

**Comment by ShraddhaPandya** [comment]
Same problem in our implementation. Pipeline is fine but everything goes into Build. @satishc1  @tabladrum could you please tell what is the resolution?

**Comment by tabladrum** [comment]
@ShraddhaPandya @satishc1 @nireeshT Let's plan for a google hangout.

**Comment by shilpsl1** [comment]
Hi @ShraddhaPandya @satishc1 @nireeshT 
I am facing issue in Product Dashboard. I can see pipeline view but nothing comes up in product dashboard environment.
Posted issue in #1165
Could you please help me if you know any solution. Thanks!!!

**Comment by ShraddhaPandya** [comment]
@tabladrum, @satishc1  Thanks, I can do it later this week if you have some time!

**Comment by git4giri** [comment]
Hi all, 
The dashboard issue is not resolved for me.
@tabladrum can you please arrange a meeting and show us all how to resolve this.

**Comment by smsuresh** [comment]
Hello Everyone!  
Please invite me as well, for the google hangout!!
Same issue for me also!

**Comment by smsuresh** [comment]
It works for me, Thankyou!

**Comment by praveenkanna** [comment]
@smsuresh can u please explain how it works now..

**Comment by praveenkanna** [comment]
@tabladrum can we do it on coming monday ?  I really wanted to know y it was not working for me and what mistake i m doing !!

**Comment by smsuresh** [comment]
@praveenkanna Can you please show your error..

**Comment by shilpsl1** [comment]
@smsuresh 
we are not able to view environment pipeline in Product Dashboard, that is the issue we are facing. how did you fix it ? below is the screen shot of Product Dashboard.
![5ef23e3a5373d0d3](https://cloud.githubusercontent.com/assets/24657895/23068819/19eabd9a-f4f3-11e6-8a32-36d8f97fa412.jpg)
![7059b5b1d356b53c](https://cloud.githubusercontent.com/assets/24657895/23068827/21e2736c-f4f3-11e6-8cc0-99d3d7711063.jpg)

**Comment by smsuresh** [comment]
@shilpsl1  Sorry , I was referring to Deploy widget & Pipeline  not product dashboard,
for product dashboard even I've the same issue.
I believe that work is still in-progress.. not sure

**Comment by bsalmi** [comment]
@tabladrum, @praveenkanna Please keep me posted on this if any news on the product pipeline.
Thx.

**Comment by nireeshT** [comment]
@bsalmi @smsuresh  @shilpsl1  @praveenkanna @git4giri @ShraddhaPandya update to latest code base and check new product dashboard. Reopen if still issue.

**Comment by kagasa** [comment]
@git4giri @tabladrum @ashnaa @praveenkanna  - Please confirm if issue related to product dashboard for environment details after setting up team dashboard and pipleline view for deply collecor is resolved or not yet ?? 

Also i am not getting commit data for svn collector under prodcut dashboard . Any views on the same pls ??

Regards,
Gaurav
