### ISSUE TITLE
Browser sync issue

### ISSUE THREAD

**Issue by adityasood** [capitalone/Hygieia#611]
The browser ins Machine A is reflecting text typed in Machine B and vice versa. Also a log out by user X in Machine A causes logout to user Y in machine B.

**Comment by amitmawkin** [comment]
it is  a feature of browser sync for testing and not a bug and should happen only in your development machine while developing and testing,  so can you post a video or something to see if this happens across different machines  , it should not happen in different machine ,

**Comment by adityasood** [comment]
Hi Amit,

We are accessing the same URL in a different machine and that is when we are facing the above issue. Also it would be of great help if you can tell me how can I toggle the browser sync option.

**Comment by sthatip** [comment]
@adityasood  are you using gulp command to host the UI? A proper way to host the UI is node index.js --api apiserver:port.

**Comment by adityasood** [comment]
@sthatip thank you will try this :)

Closing this as i found the way to toggle this.

There is a node module Browser_Sync in the node-modules folder. In this gt to Default_Config. You can toggle the ghost-mode property here.
