### ISSUE TITLE
Jira properties builder instructions wrong for jiraIssueTypeId

### ISSUE THREAD

**Issue by MarkRx** [capitalone/Hygieia#623]
jira-properties-builder.sh says this:

```
# In Jira, general IssueType IDs are associated to various "issue"
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a numerical ID reference to your instance's IssueType for
# the lowest level of Issues (e.g., "user story") specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType ID
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
feature.jiraIssueTypeId=${JIRA_ISSUE_TYPE_ID:-7}
```

It defaults to 7 which made me place in our jira instance's value (6). However it did not work as it was placing empty Feature objects in the database. After looking further the code appears to be looking for a string that is returned from the API such as "Story"
```
if (TOOLS.sanitizeResponse(issueType.getName())
							.equalsIgnoreCase(super.featureSettings.getJiraIssueTypeId()))
```

It looks like the readme file is correct in that it has feature.jiraIssueTypeId=Story. The default value for the properties file is incorrect and misleading.

**Comment by tabladrum** [comment]
@amp5208 - please take a look.

**Comment by amp5208** [comment]
@MarkRx , Thank you for reaching out regarding your JiraFeatureCollector question.  Firstly, that bash script for Docker was not created by me - I now see that it needs to be updated.  I will send a pull request shortly to ensure that the property file is correct.

In the meantime, you are correct - that configuration is not right.  If in your instance an issue of type story is a different ID, you should actually put the **name** of the ID into that config property.  e.g, if issue type story's ID is 6, put in its name, "Story" into that property.  You can see details of this in our updated README:  https://github.com/capitalone/Hygieia/blob/master/jira-feature-collector/README.md

Please let me know if you have any further issues.
