### ISSUE TITLE
Collector as a service

### ISSUE THREAD

**Issue by bimalvv** [capitalone/Hygieia#625]
Hi,
I am trying to create a new collector and is it possible to exposed as a service. My idea is that one og my process will invoke this service and insert the data into MongoDB.

Thanks
Bimal

**Comment by tabladrum** [comment]
If you want to "push" data into hygieia, all you need is the corresponding API. Share your use case and we can collaborate on the design.

**Comment by bimalvv** [comment]
Thanks @tabladrum 

My requirement is to have a service to store the data. Because it is on demand, means whenever I have some data I need to store in MongoDb and I would like to have a service in API project to display in UI.

I have a process which will invoke the collector/data collector service to persist the data. Later user can configure the UI widget to display the data.

Please let me know if you are looking for more details.

Thanks,
Bimal

**Comment by bimalvv** [comment]
One more question regarding the relationship. When I create a new collector, which are the  documents/tables I need to care about?.
I am getting an issue in error in below mentioned service call in dashboard-data.js

`var route = widgetId ?
$http.put(dashboardRoute + '/' + dashboardId + '/widget/' + widgetId, widget) :
$http.post(dashboardRoute + '/' + dashboardId + '/widget', widget);
`
Thanks,
Bimal

**Comment by sthatip** [comment]
@bimalvv A collector is a micro service to "pull" the data from data source (e.g. Stash,SubVersion) and push to mongodb. so depending on the source, you may or may not be able to reuse existing model classes and may need to add new ones to core, api and collector projects. Hope it helps.

**Comment by tabladrum** [comment]
Collectors are the microservices such as github collector or jenkins collector etc.
CollectorItems are documents like Jenkins jobs, Github Repo etc. These point to the Collector.
The documents such as Builds, Commit etc has references to corresponding CollectorItems.

Dashboard document has Widget that has ComponenId.
Component document has a set of collector items.
