### ISSUE TITLE
Single UI Instance for all user 

### ISSUE THREAD

**Issue by kv113813** [capitalone/Hygieia#627]
I am experiencing a issue in session, when a user login into dashboard with his credential and other also getting login with there but one can almost control the page
It seems cookies are not handled and single instance of UI getting for all not creating other for other user.
Steps to reproduce:
- Login as anybody.
- In another machine access /site directly.
- You share the logged in user session.

**Comment by kv113813** [comment]
@tabladrum @amitmawkin ...I am experiencing a issue in session, when a user login into dashboard with his credential and other also getting login with there but one can almost control the page
It seems cookies are not handled and single instance of UI getting for all not creating other for other user.
Steps to reproduce:

    Login as anybody.
    In another machine access /site directly.
    You share the logged in user session

I am not running in docker, just gulp serve and java -jar for collectors. Is the above due to this??

**Comment by amitmawkin** [comment]
We have not seen this behavior , the cookie is local to a user machine... Can you show me screen recording or something of the behavior

**Comment by sthatip** [comment]
@kv113813 I think you the UI you are using is launched using gulp serve option which has browsersync enabled and it syncs all login sessions no matter which pc. try hosting the UI using node index.js --api myhygieiaApiServer:Port

**Comment by kv113813** [comment]
@SanthiSridharan Can you explain little more on "UI using node index.js --api myhygieiaApiServer:Port". How should I do it?

**Comment by kv113813** [comment]
@sthatip @amitmawkin  Can you explain little more on "UI using node index.js --api myhygieiaApiServer:Port". How should I do it?

**Comment by kv113813** [comment]
@sthatip Thanks we got the possible solution with your hint.
@amitmawkin It is due to gulp serve, you can simulate it. run api as java -jar in your local and UI as gulp serve. Now login in your local and ask other guy to run with your ip:port and observe the behavior. Both try to use same time the browser, also /site is directly accessible.

**Comment by javakthar** [comment]
@kv113813  can you please explain how you have resolved this issue, we too are facing similar issue. It would be really helpful if you can tell the steps you have used to fix this.

**Comment by kv113813** [comment]
@javakthar Sorry for delayed response. Except Development you should not use gulp serve. If you do not want to use docker setup, set up a nginx and deploy dist/ files. Refer UI docker script does pretty much same thing what you need to do without docker.

**Comment by JloginGit123** [comment]
I am getting error following error when run node index.js --api localhost:8080 command.

I have build the UI project then running this command.
Please help.
D:\DE\Hygieia-master\Hygieia-master\UI>node index.js --api localhost:8080
module.js:457
    throw err;
    ^

Error: Cannot find module 'D:\DE\Hygieia-master\Hygieia-master\UI\index.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by kv113813** [comment]
ok..Follow dockerfile UI steps and run nginx, deploy UI/dist for
production. For Development, do gulp serve.

**Comment by JloginGit123** [comment]
Thank you for your reply. I have deployed my UI at tomcat server with port 8080.
and running api as service with port 8081. But My UI is going to connect api http://localhost:8080/api. I could not understand how to deploy api.jar in tomcat.

I also tried to hardcore api url in gulffile.js file. In that case I am geeting Cross ref error.

Please help.
