### ISSUE TITLE
CloudVolumeRepository.java is causing issue in API project

### ISSUE THREAD

**Issue by sthatip** [capitalone/Hygieia#640]
below line in CloudVolumeRepository.java seems to be causing issues in API service start up.
Collection<CloudVolumeStorage> findByAttachInstancesIn(List<String> attachInstances);

Error I was getting was 'property attach not found'. It seems to be Spring Data JPA related and I had to add this annotation to temporarily satisfy the build, not sure if the query result is same.
@Query(value = "{ 'attachInstances' : {$in: ?0 }}")

Anyone else has this issue?

**Comment by tabladrum** [comment]
that's odd!

**Comment by tabladrum** [comment]
Can you paste a little more of the stack trace?

**Comment by sthatip** [comment]
reverted my change today to reproduce the issue and give you stack trace but now I do not see it. closing this for now and will watch out.
