### ISSUE TITLE
SVN authetication issue

### ISSUE THREAD

**Issue by dkpurushothaman** [capitalone/Hygieia#641]
when try to connection subverion repository am getting the authentication error , but same credentials am using in the eclipse as well as tortoise SVN client which is working fine.

do i need configure any additional in the application properties or another place.

**Comment by tabladrum** [comment]
Do you have these properties in there?
`subversion.username=<userid>`
`subversion.password=<password>`

**Comment by sthatip** [comment]
similar issue with Stash-SCM-collector, getting a 401 unauthorized error. I added a git.key in application.properties and gave my 64 bit encoded username:password but did not help. I don't see any documentation on this in readme.md.

**Comment by dkpurushothaman** [comment]
i have  both the properties in place.
#Shared subversion username and password
subversion.username=*****
subversion.password=*****

**Comment by dkpurushothaman** [comment]
am getting below error
svn e170001 negotiate authentication failed 'no valid credentials provided' svnkit1.8.7

**Comment by mcloud42** [comment]
See if you need to change http-auth-types=Basic from http-auth-types=basic in the servers file of your user's subversion folder located in %APPDATA%\Roaming\Subversion

Take a note of case difference in Basic and basic

**Comment by satishc1** [comment]
Functionality merged in https://github.com/capitalone/Hygieia/pull/835
Refer to the "Encryption for private repos" section in the UI module readme.
