### ISSUE TITLE
fortify collector issue

### ISSUE THREAD

**Issue by dkpurushothaman** [capitalone/Hygieia#642]
I have build fortify collector successfully , when try to execute the jar in the command line am getting the error

application startup failed org.springframework.beans.factory.BeanCreationException. error creating bean with name 'defaultFortifyCollectorTask' : invocation of the init method failed.

**Comment by tabladrum** [comment]
This indicates that you need to provide the correct path for the properties file.

**Comment by dkpurushothaman** [comment]
thanks for update again i have build its working fine, i need some clarification regarding fortify 

i have fortify static code analyzer in my local as well as remote machine , its desktop application .how to access the fortify details.

**Comment by tabladrum** [comment]
If you are running fortify on your desktop, the url to that should be something like http://localhost/ssc

**Comment by dkpurushothaman** [comment]
its a static code analyzer, we are not running any server

**Comment by tabladrum** [comment]
Which version is it? I am not aware of a non-server based (or local) Fortify static code analyzer. Can you send me a link to the product page?

**Comment by satishc1** [comment]
Closed due to inactivity.
