### ISSUE TITLE
hard coded jenkins tree urls causing issues

### ISSUE THREAD

**Issue by sthatip** [capitalone/Hygieia#646]
In 1.0 version, treeapiurl and apiUrl were in HudsonSettings file but now they are hardcoded as _CHANGE_SET_ITEMS_TREE_ and _BUILD_DETAILS_TREE_ variables in DefaultHudsonClient class. Any particular reason this change was made? My Jenkins instance returns 500 error in getBuildDetails() because of timestamp field in change set.

**Comment by amitmawkin** [comment]
can you please provide the stack trace and version of your Jenkins instance.

**Comment by sthatip** [comment]
Jenkins version 1.611
HttpServerError 500 is reproducible with a standalone REST client GET request. Removing _timestamp_ from the below URL fixes the issue for me.

http://server:port/job/jobName/jobNumber/api/json?tree=number,url,timestamp,duration,building,result,culprits[fullName],changeSet[items[user,author[fullName],revision,id,msg,timestamp,date,paths[file]],revisions[module,revision]]

**Comment by nireeshT** [comment]
@sthatip  we are unable to reproduce the issue. We tried with Jenkins ver. 2.19.2 and latest Hygieia code base. Please try the same and reopen if you still have issues.
