### ISSUE TITLE
base URL not defaulting to index.html

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#651]
I saw something odd today when I went to localhost:8088/ I got a blank page but http://localhost:8088/index.html worked.

**Comment by tabladrum** [comment]
for the ui?

**Comment by satishc1** [comment]
@jimzucker Is this still a problem ?

**Comment by jimzucker** [comment]
I will have to retest.

**Comment by tabladrum** [comment]
closing it for now.
