### ISSUE TITLE
create ID that is too short to login

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#653]
I was able to create an id 'jim' but I get an error the id is too short when I try to login, I think our rules for id/pwd length are not aligned on all screens.

**Comment by amitmawkin** [comment]
should be minimum 6 characters , i will check

**Comment by tabladrum** [comment]
@amitmawkin did you get a chance to check?

**Comment by Sbrenthughes** [comment]
The rules for the sign up page now reflect what is on the login page.
