### ISSUE TITLE
how does the github collectors get is credentials?

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#654]
I need to understand how the collector gets its credentials so I can debug it. (I thought I saw a thread on this recently but cannot find it)

I changed to docker mac native version and now I get:

2016-06-25 02:02:00,760 ERROR c.c.d.collector.DefaultGitHubClient - 403 Forbidden:https://api.github.com/repos/capitalone/Hygieia/commits?sha=master&since=2016-06-25T01:52Z
2016-06-25 02:02:00,939 ERROR c.c.d.collector.DefaultGitHubClient - 403 Forbidden:https://api.github.com/repos/capitalone/Hygieia/commits?sha=hygieiacloud2.1&since=2016-06-25T01:52Z
2016-06-25 02:02:01,088 ERROR c.c.d.collector.DefaultGitHubClient - 403 Forbidden:https://api.github.com/repos/capitalone/Hygieia/commits?sha=hyg&since=2016-06-25T01:52Z
2016-06-25 02:02:01,216 ERROR c.c.d.collector.DefaultGitHubClient - 403 Forbidden:https://api.github.com/repos/capitalone/Hygieia/commits?sha=Hygieiacloud2.1&since=2016-06-25T01:52Z
2016-06-25 02:02:01,366 ERROR c.c.d.collector.DefaultGitHubClient - 403 Forbidden:https://api.github.com/repos/capitalone/Hygieia/commits?sha=hygieia2.1&since=2016-06-11T02:02Z

**Comment by MarsDominion** [comment]
Here's a writeup I did yesterday on getting the github working w/ private repos.

Once the instance is up, you can configure a github repository, but only works out of the box with public repositories.  In order to configure it to use private repositories, some additional steps are necessary.

Prior to building the applicaiton, you need to add an encryption key to the github-properties-builder.sh file.  You can variableize it by adding the following line to the config file:

	github.key=${GITHUB_KEY}
	
Then you can pass it is wht the -e parameter when you launch the docker container:

	docker run -d --link=mongo -e "MONGO_PORT=tcp://mongo:27017" -e "GITHUB_KEY=j8HWwu+zbnZSg0bC1WsOJYldemGFI3ol" --name github-collector -i hygieia-github-scm-collector:latest

You then need to use the encryption key to generate an encrypted password to put into mongo db:

	db.collector_items.update(
     	         {"options.url":"https://github.com/<company>/<repo>"},
        	      {$set: {"options.userID": "<account>", "options.password": 	"<encrypted password>"}}
             )
    
As I was doing my research, I came across a forked project of Hygieia that had a [handy tool](https://github.com/pjaol/Hygieia/tree/tools_no_docker/tools) for generating the key and encyrpting.  This was probably the best resource for setting it up that I had found in general.

After doing all of this, I still wasn't able to see the data.  After digging around, it seems that it only tries to get the history data on the first run, so if it ran for the first time before I was able to add the account and password, I wouldn't see the historical data.  To fix that, I just reset the lastUpdated field to zero and it picked everything up on the next run.

	db.collector_items.update({
		"options.url": "https://github.com/blackbaud/devops"
		}, {
	 	$set: {  "lastUpdated": NumberLong(0) }
		})

Anyways, that's what I have, hope it helps.

**Comment by jimzucker** [comment]
Thanks I will look at this tomorrow but I am using a public GITHUB branch (actually the Hygieia/master)  it worked with my old docker VM but when I moved to the new 1.12 docker for mac installation I started getting the Forbidden error but am not sure how it worked in the first place to debug it..


On Jun 25, 2016, at 7:55 PM, Mark Honomichl <notifications@github.com<mailto:notifications@github.com>> wrote:


Here's a writeup I did yesterday on getting the github working w/ private repos.

Once the instance is up, you can configure a github repository, but only works out of the box with public repositories. In order to configure it to use private repositories, some additional steps are necessary.

Prior to building the applicaiton, you need to add an encryption key to the github-properties-builder.sh file. You can variableize it by adding the following line to the config file:

github.key=${GITHUB_KEY}


Then you can pass it is wht the -e parameter when you launch the docker container:

docker run -d --link=mongo -e "MONGO_PORT=tcp://mongo:27017" -e "GITHUB_KEY=j8HWwu+zbnZSg0bC1WsOJYldemGFI3ol" --name github-collector -i hygieia-github-scm-collector:latest


You then need to use the encryption key to generate an encrypted password to put into mongo db:

db.collector_items.update(
             {"options.url":"https://github.com/<company>/<repo>"},
              {$set: {"options.userID": "<account>", "options.password":    "<encrypted password>"}}
         )


As I was doing my research, I came across a forked project of Hygieia that had a handy tool<https://github.com/pjaol/Hygieia/tree/tools_no_docker/tools> for generating the key and encyrpting. This was probably the best resource for setting it up that I had found in general.

After doing all of this, I still wasn't able to see the data. After digging around, it seems that it only tries to get the history data on the first run, so if it ran for the first time before I was able to add the account and password, I wouldn't see the historical data. To fix that, I just reset the lastUpdated field to zero and it picked everything up on the next run.

db.collector_items.update({
    "options.url": "https://github.com/blackbaud/devops"
    }, {
    $set: {  "lastUpdated": NumberLong(0) }
    })


Anyways, that's what I have, hope it helps.

**Comment by jimzucker** [comment]
Hi,

I tried running on my PC and I get an error..  Looks like I have to wait for the throttle to reset on github



2016-06-26 03:38:00,006 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-06-26 03:38:00,674 ERROR c.c.d.collector.DefaultGitHubClient - 403 Forbidden:https://api.github.com/repos/capitalone/Hygieia/commits?sha=master&since=2016-06-26T03:28Z<http://api.github.com/repos/capitalone/Hygieia/commits?sha=master&since=2016-06-26T03:28Z>
2016-06-26 03:38:00,792 ERROR c.c.d.collector.DefaultGitHubClient - 403 Forbidden:https://api.github.com/repos/capitalone/Hygieia/commits?sha=hygieiacloud2.1&since=2016-06-26T03:28Z<http://api.github.com/repos/capitalone/Hygieia/commits?sha=hygieiacloud2.1&since=2016-06-26T03:28Z>
2016-06-26 03:38:00,911 ERROR c.c.d.collector.DefaultGitHubClient - 403 Forbidden:https://api.github.com/repos/capitalone/Hygieia/commits?sha=hyg&since=2016-06-26T03:28Z<http://api.github.com/repos/capitalone/Hygieia/commits?sha=hyg&since=2016-06-26T03:28Z>
2016-06-26 03:38:01,038 ERROR c.c.d.collector.DefaultGitHubClient - 403 Forbidden:https://api.github.com/repos/capitalone/Hygieia/commits?sha=Hygieiacloud2.1&since=2016-06-26T03:28Z<http://api.github.com/repos/capitalone/Hygieia/commits?sha=Hygieiacloud2.1&since=2016-06-26T03:28Z>
2016-06-26 03:38:01,039 INFO  c.c.d.collector.CollectorTask - Repo Count              5        1s
2016-06-26 03:38:01,039 INFO  c.c.d.collector.CollectorTask - New Commits             0        1s
2016-06-26 03:38:01,040 INFO  c.c.d.collector.CollectorTask - Finished                         1s
^C
➜  Hygieia git:(master) curl https://api.github.com/repos/capitalone/Hygieia/commits\?sha\=master\&since\=2016-06-26T03:28Z
{
  "message": "API rate limit exceeded for 66.234.203.212. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
➜  Hygieia git:(master)


On Jun 25, 2016, at 7:55 PM, Mark Honomichl <notifications@github.com<mailto:notifications@github.com>> wrote:


Here's a writeup I did yesterday on getting the github working w/ private repos.

Once the instance is up, you can configure a github repository, but only works out of the box with public repositories. In order to configure it to use private repositories, some additional steps are necessary.

Prior to building the applicaiton, you need to add an encryption key to the github-properties-builder.sh file. You can variableize it by adding the following line to the config file:

github.key=${GITHUB_KEY}


Then you can pass it is wht the -e parameter when you launch the docker container:

docker run -d --link=mongo -e "MONGO_PORT=tcp://mongo:27017" -e "GITHUB_KEY=j8HWwu+zbnZSg0bC1WsOJYldemGFI3ol" --name github-collector -i hygieia-github-scm-collector:latest


You then need to use the encryption key to generate an encrypted password to put into mongo db:

db.collector_items.update(
             {"options.url":"https://github.com/<company>/<repo>"},
              {$set: {"options.userID": "<account>", "options.password":    "<encrypted password>"}}
         )


As I was doing my research, I came across a forked project of Hygieia that had a handy tool<https://github.com/pjaol/Hygieia/tree/tools_no_docker/tools> for generating the key and encyrpting. This was probably the best resource for setting it up that I had found in general.

After doing all of this, I still wasn't able to see the data. After digging around, it seems that it only tries to get the history data on the first run, so if it ran for the first time before I was able to add the account and password, I wouldn't see the historical data. To fix that, I just reset the lastUpdated field to zero and it picked everything up on the next run.

db.collector_items.update({
    "options.url": "https://github.com/blackbaud/devops"
    }, {
    $set: {  "lastUpdated": NumberLong(0) }
    })


Anyways, that's what I have, hope it helps.

**Comment by tabladrum** [comment]
We have a backlog item (for long) to allow user to enter id/pwd in the UI and store them along with the widget config. The backend work is done. Need to finish off the UI work and that way you wont need the extra step.

**Comment by dinukool** [comment]
Any ETA for this roll out (user to enter id/pwd in the UI)  pls confirm ?

**Comment by tabladrum** [comment]
Under test by @satishc1

**Comment by dinukool** [comment]
Hi Satish @satishc1 any update on this testing or ETA for roll-out? kindly confirm Thanks!

**Comment by satishc1** [comment]
@dinukool Getting close... Should be available early next week.

**Comment by satishc1** [comment]
Fixed.

**Comment by holmesmi** [comment]
That sounds really useful -- is there any chance that the docker images (https://hub.docker.com/r/capitalone/hygieia-ui/) will be updated with this? Trying to build Hygieia behind our corporate firewall is just way too painful.

**Comment by vparupal** [comment]
Hello @satishc1  just checking in if the docker image has been updated? @holmesmi please let me know if you have an docker already in use.
