### ISSUE TITLE
Gradle Support

### ISSUE THREAD

**Issue by kamal2222ahmed** [capitalone/Hygieia#655]
We use only internal repositories and gradle. Would it be possible to convert the maven project to gradle ? as i am getting error:

 mvn clean install package
[INFO] Scanning for projects...
Downloading: http://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/1.2.5.RELEASE/spring-boot-starter-parent-1.2.5.RELEASE.pom
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.capitalone.dashboard:Hygieia:2.0.2-SNAPSHOT (/home/ec2-user/Hygieia/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:1.2.5.RELEASE from/to central (http://repo.maven.apache.org/maven2): Connection to http://repo.maven.apache.org refused and 'parent.relativePath' points at wrong local POM @ line 10, column 10: Connection timed out -> [Help 2]

**Comment by tabladrum** [comment]
Use a settings file in your .m2 repo to point to your internal maven repo. That will work.

**Comment by tabladrum** [comment]
We want to move to gradle when we get some breathing space :-) Will stick to maven for next few months.

**Comment by kamal2222ahmed** [comment]
now i get : mvn clean install package
[INFO] Scanning for projects...
Downloading: http://10.103.135.40:8080/nexus/content/repositories/thirdparty/org/springframework/boot/spring-boot-starter-parent/1.2.5.RELEASE/spring-boot-starter-parent-1.2.5.RELEASE.pom
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.capitalone.dashboard:Hygieia:2.0.2-SNAPSHOT (/home/ec2-user/Hygieia/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact org.springframework.boot:spring-boot-starter-parent:pom:1.2.5.RELEASE in nexus (http://10.103.135.40:8080/nexus/content/repositories/thirdparty) and 'parent.relativePath' points at wrong local POM @ line 10, column 10 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException


with the settings.xml 

```
<settings>
  <!-- the path to the local repository - defaults to ~/.m2/repository
         -->
  <!-- <localRepository>/path/to/local/repo</localRepository>
         -->
    <mirrors>
    <mirror> <!--Send all requests to the public group -->
      <id>nexus</id>
      <mirrorOf>*</mirrorOf>
      <url>http://10.103.135.40:8080/nexus/content/repositories/thirdparty</url>
    </mirror>
  </mirrors>
  <activeProfiles>
    <!--make the profile active all the time -->
    <activeProfile>nexus</activeProfile>
  </activeProfiles>

  <pluginGroups>
    <pluginGroup>org.sonatype.plugins</pluginGroup>
  </pluginGroups>

  <servers>
    <server>
      <id>nexus</id>
      <username>admin</username>
      <password>admin123</password>
    </server>
  </servers>
</settings>
```
