### ISSUE TITLE
Required Java Version?

### ISSUE THREAD

**Issue by MarkRx** [capitalone/Hygieia#658]
Hello,

What is the minimum java version required to run Hygieia? CommitEventListenerTest is using lambda expressions so I assume this means java 8. I so I think it should be documented in the setup instructions.

https://github.com/capitalone/Hygieia/blob/master/Setup.md

**Comment by tabladrum** [comment]
Yes. Needed Java 8. Thanks for pointing it out. Will update the Setup.

**Comment by tabladrum** [comment]
https://github.com/capitalone/Hygieia/pull/661

**Comment by abhishek789** [comment]
I am using jdk9 and when i am running the mvn install clean package command after cloning the hygieia code, i am getting below error-

[ERROR] Failed to execute goal com.mysema.maven:apt-maven-plugin:1.1.3:process (default) on project core: java.lang.RuntimeException: java.lang.NoClassDefFoundError: javax/annotation/Generated: javax.annotation.Generated -> [Help 1]

Is it related to my java version?
Please help!

**Comment by reddyj863** [comment]
I have the same issue has abhishek789, I tried it with multiple java versions and servers, nothing works I am stuck here.
