### ISSUE TITLE
VersionOne Collector

### ISSUE THREAD

**Issue by j9s3** [capitalone/Hygieia#659]
I can't get the VersionOne collector to work properly.

With the most recent commit: 
I get something like this:
![image](https://cloud.githubusercontent.com/assets/20175388/16398166/a32e60e0-3c7d-11e6-8edc-b8a3ea0663fb.png)
ERROR c.c.d.rest.RestApiExceptionHandler - null
java.lang.NullPointerException: null
    at com.capitalone.dashboard.service.DashboardServiceImpl.get(DashboardServiceImpl.java:51).....

With release 2.0.0, the widget looks better, but is missing features in progress for most of the teams.

**Comment by tabladrum** [comment]
@amp5208 please take a look.

**Comment by tabladrum** [comment]
Can you provide a little more of the stack trace? Does seem to be config issue.

**Comment by amp5208** [comment]
@j9s3 :  This appears to be a configuration issue.  Please provide your current configuration for the following property (read my notes and example below):

```properties
# In Jira, your instance will have its own custom field created for "super story" or "epic" back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (e.g., epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraEpicIdFieldName=customfield_10400
```

**Comment by satishc1** [comment]
@j9s3 Is this still an issue ?

**Comment by satishc1** [comment]
@j9s3 Closed. Reopen if still an issue.

**Comment by zerolaser** [comment]
@satishc1 yes It is still an issue. please re-open the ticket.  I ran into the same issue. it was pulling the kanban results but no scrum results at all.
