### ISSUE TITLE
Cannot use build collector with username and password

### ISSUE THREAD

**Issue by kyosong** [capitalone/Hygieia#66]
Our jenkins is being set up with no readonly if there is no login. I didn't see any usename and password to configure in the application.properties file. 

Can it be added?

**Comment by amitmawkin** [comment]
The current version of collector only supports Jenkins Jobs that have allowed anonymous uset to read the job without logging in. We can consider this an enhancement and work upon it, it's not trivial

**Comment by tabladrum** [comment]
@kyosong: if your Jenkins is locked down, is there a regulatory reason? If yes, would it be okay for the dashboard to show the build results, change set etc?

**Comment by kyosong** [comment]
@tabladrum we are using enterprise cloudbee for build, the cloudbee team are managing all access. So far, i cannot see build results and change set things. 

![image](https://cloud.githubusercontent.com/assets/5901392/9265722/ddb41070-4269-11e5-9738-aa301a66b72a.png)

**Comment by tabladrum** [comment]
With the current version, you can pass in the userid/token to jenkins via the configuration in jenkins collectors config file:
jenkins.server[0]=https://user:token@myjenkins.com
