### ISSUE TITLE
Jenkins Hygieia Plugin - Capturing Sonar Custom Metrics

### ISSUE THREAD

**Issue by rohans84** [capitalone/Hygieia#660]
As of now, the jenkins hygieia plugin captures a predefined set of metrics from sonar. I was thinking to make it customizable so that if an app is using custom measures / metrics in Sonar - the jenkins plugin for hygieia can capture those as well and persist in mongodb. Any thoughts on it?
The two options available are:
1. Take the sonar metrics list from the jenkins job configuration
2. Take the sonar metrics list from global config in Jenkins for Hygieia.

Any thoughts where this would work the best?

**Comment by tabladrum** [comment]
I would add as much data as possible (keeping it generic) and store it in Hygieia. What would be some examples of custom metrics?

**Comment by rohans84** [comment]
Custom metric could be anything like a textual metric or a numeric measure that is instrumented by a custom sonar plugin. These metrics are captured by developing a custom sonar plugin.

For example, we can have a custom sonar plugin that inspects gulpfile.js to determine different gulp plugins used. This will be captured on every sonar analysis by the plugin and updated to sonar database.

I am not sure if we would need to capture these custom metrics into hygieia database as well, but there could be Hygieia widgets that could display these custom metrics for more customized look n feel.

**Comment by satishc1** [comment]
@rohans84 Can you close this if its fixed ? thanks.

**Comment by satishc1** [comment]
Closed.
