### ISSUE TITLE
Does Hygieia 2.0 can support Enterprise Mongo DB?

### ISSUE THREAD

**Issue by oshingc** [capitalone/Hygieia#662]
I wonder if there's no problem with Hygieia 2.0 to use Enterprise Mongo DB...

**Comment by tabladrum** [comment]
Don't think that there will be any issue. If you face any roadblock we would like to know about it.

**Comment by oshingc** [comment]
Oh ok, I'll try using Enterprise Mongo DB and let's see! 
Thanks @tabladrum

**Comment by tabladrum** [comment]
Closing this. If you run into any issues, please reopen this create a new one.

**Comment by oshingc** [comment]
I have this error:
![errormdb](https://cloud.githubusercontent.com/assets/3100819/16504612/7b362434-3ede-11e6-9576-94dc37564311.jpg)

**Comment by oshingc** [comment]
@tabladrum Have you had this issue?

**Comment by tabladrum** [comment]
Is this reproducible?
