### ISSUE TITLE
Bitbucket Private Repo

### ISSUE THREAD

**Issue by HananNaguib** [capitalone/Hygieia#664]
Hello,

I want to setup Hygieia UI to contact bitbucket, but our repos are private, I can see userID and Password in the java files,

However I don't know how to pass it using ENV variables in Docker or properties file

**Comment by MarkRx** [comment]
I don't see a way to do it in the UI. Here is how you can do it manually:

1. Create/generate a 24 character key (in this example 'abcdefghijklmnopqrstuvwx')
2. Obtain the base64 string of that key
> echo -n abcdefghijklmnopqrstuvwx | base64
> YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4
3. Put that value in your properties file (git.key=YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4). There is no environment variable for it so you will have to override the docker-compose command and point to a custom volume with your settings file
4. Obtain the hex string of that key
> echo -n abcdefghijklmnopqrstuvwx | hexdump -e '16/1 "%02x"'
> 6162636465666768696a6b6c6d6e6f707172737475767778
5. Generate an encrypted password string using tripple DES. The  options your jvm uses may vary. Mine defaulted to using DESede/ECB/PKCS5Padding.
> echo -n password | openssl enc -des-ede3 -K 62636465666768696a6b6c6d6e6f707172737475767778 -base64
> 61orEO2iB8UVQI1v4VgFow==
6. Find your database GitRepo record
> db.getCollection('collector_items').find({'_class': 'com.capitalone.dashboard.model.GitRepo'})
7. Add the following to the options json:
```
userID: "myusername"
password: "61orEO2iB8UVQI1v4VgFow=="
```

**Comment by satishc1** [comment]
Functionality merged in https://github.com/capitalone/Hygieia/pull/835
Refer to the "Encryption for private repos" section in the UI module readme.
