### ISSUE TITLE
Memory Leak 

### ISSUE THREAD

**Issue by sibaom** [capitalone/Hygieia#665]
Hi ,
When all collectors running then its taking lot of memory.Is there any way to optimize
Spring boot application or Collector .I tried to increase the heap and RAM but its not working.
Please give any suggestion so that the collector will run with minimal memory space.
I checked memory usage with java JConsole Tool.

Thanks,

**Comment by tabladrum** [comment]
@amitmawkin can you publish our own setup here? Thanks

**Comment by amitmawkin** [comment]
M3 XLarge in AWS will do for you .... if you are running everything on a single box,

my advice to deploy the app as per the layer and you can go smaller

**Comment by sibaom** [comment]
Thanks @amitmawkin
