### ISSUE TITLE
upsertCloudInstanceObject complexity of 503316480	CloudInstanceServiceImpl.java

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#669]
This method should be reviewed by the owner.

Description Resource    Path    Location    Type
The method upsertCloudInstanceObject() has an NPath complexity of 503316480 CloudInstanceServiceImpl.java   /api/src/main/java/com/capitalone/dashboard/service line 116    PMD Marker

**Comment by tabladrum** [comment]
Are these coming up in your eclipse? My intelliJ doesn't complain :-)

**Comment by jimzucker** [comment]
Yes, take a look:
<img width="1381" alt="screenshot 2016-07-01 08 02 50" src="https://cloud.githubusercontent.com/assets/14372687/16526282/4820432c-3f65-11e6-9224-7e30fa42b9c2.png">

**Comment by satishc1** [comment]
Add PMD Marker plugin in IntelliJ to see these warnings.

**Comment by nireeshT** [comment]
Fixed in PR https://github.com/capitalone/Hygieia/pull/916
