### ISSUE TITLE
Getting started guide

### ISSUE THREAD

**Issue by jdamick** [capitalone/Hygieia#67]
Based on the feedback from #52 need to create a simplified and straightforward step by step getting started guide.

**Comment by msabramo** [comment]
:+1:

**Comment by tabladrum** [comment]
Working on it. Should be up here by Friday 8/14

**Comment by tcrall** [comment]
Any news on this?  Would be very helpful - am spending my day trying to install Hygieia.

**Comment by amitmawkin** [comment]
please join our glitter chat we should be able to get you up and running, meanwhile more helpful documentation is getting generated with feedback from community. 
Also would like to know which step you are stuck with

**Comment by tcrall** [comment]
That would be great - I'm not familiar with glitter chat, can you point me in the right direction?

I've downloaded v 1.2.0 and I *think* I've run the maven build correctly - trying to figure out if there's something I need to do to actually start the process/service?  Does it have its own bundled tomcat or should I be putting in my apache web directory?  Basically, if I've built it correctly, how do I launch it?

**Comment by radkin** [comment]
I'm stuck on the signup step: ref https://github.com/capitalone/Hygieia/issues/40

**Comment by amitmawkin** [comment]
Noel looks like api layer is not running for you. If your api is running on a tomcat server at port 8080 please paste output of url
http://<hostname:8080>/api/dashboard

**Comment by radkin** [comment]
The above URL is a 404. Using tomcat7 the war has exploded successfully and logs for tomcat indicate the following:
`<my ip address> - - [21/Aug/2015:19:46:48 +0000] "GET /api/dashboard HTTP/1.1" 404 994`
output from the browser is this

```bash
HTTP Status 404 - /api/dashboard

type Status report

message /api/dashboard

description The requested resource (/api/dashboard) is not available.

Apache Tomcat/7.0.28
```

**Comment by amitmawkin** [comment]
this means that the api is not running correctly. Can you check based on API readme.md that you have also set up and environment property DASHBOARD_PROP and have the relevant properties set.

**Comment by mtrujBAH** [comment]
Im having a similar issue as radkin, although when I go to 8080/api/dashboard I get a blank page. In the tomcat logs the requests have 404 errors. I have the environment property set up and all.

**Comment by radkin** [comment]
Used git to pull the latest version including new documentation. Learned a few things along the way
* The java jdk looks like it needs to be 1.8 and possibly Oracle, but not sure. 
* The README.md documentation for us is closer to a running Hygieia suite of apps.
* Once again, the UI runs fine, the API has the following issue:

*note* it says it starts up jetty with "BUILD SUCCESSFUL", etc. but it's not listening.
```bash
2015-08-24 20:50:22,556 WARN  o.s.w.c.s.AnnotationConfigWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'featureServiceImpl' defined in file [/home/m673639/Hygieia/api/build/classes/main/com/capitalone/dashboard/service/FeatureServiceImpl.class]: Unsatisfied dependency expressed through constructor argument with index 2 of type [com.capitalone.dashboard.repository.FeatureRepository]: : Error creating bean with name 'featureRepository': Invocation of init method failed; nested exception is com.mongodb.CommandFailureException: { "serverUsed" : "localhost:27017" , "ok" : 0.0 , "errmsg" : "not authorized on dashboard to execute command { createIndexes: \"feature\", indexes: [ { name: \"sId\", ns: \"dashboard.feature\", key: { sId: 1 } } ] }" , "code" : 13}; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'featureRepository': Invocation of init method failed; nested exception is com.mongodb.CommandFailureException: { "serverUsed" : "localhost:27017" , "ok" : 0.0 , "errmsg" : "not authorized on dashboard to execute command { createIndexes: \"feature\", indexes: [ { name: \"sId\", ns: \"dashboard.feature\", key: { sId: 1 } } ] }" , "code" : 13}
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:751) ~[spring-beans-4.1.0.RELEASE.jar:4.1.0.RELEASE]
```
it looks to be a permissions issue in mongoDB; however, I am a mongo noob .. so not sure exactly what we need to do. What I show in mongoDB is this

```bash
`> db.getCollection("system.users").find()
{ "_id" : "dashboarddb.dashboarduser", "user" : "dashboarduser", "db" : "dashboarddb", "credentials" : { "SCRAM-SHA-1" : { "iterationCount" : 10000, "salt" : "<super secret>", "storedKey" : "<super secret>", "serverKey" : <super secret>" } }, "roles" : [ ] }
```

I tried entering "dashboarduser" and "dashboarddb" in the sample.properties file, but it didn't work. The contents is listed here

```bash
#Database Name - default is test
spring.data.mongodb.database=dashboarddb

    #Database HostName - default is localhost
#spring.data.mongodb.host=10.0.1.1

    #Database Port - default is 27017
#spring.data.mongodb.port=9999

    #Database Username - default is blank
spring.data.mongodb.username=dashboarduser

    #Database Password - default is blank
#spring.data.mongodb.password=

    #Collector schedule (required)
#Jenkins.cron=0 0/5 * * * *
#github.cron=0 0/5 * * * *
#sonar.cron=0 0/5 * * * *
#udeploy.cron=0 0/5 * * * *
#subversion.cron=0 0/5 * * * *
#feature.cron=0 0/5 * * * *

    #Hudson server (required) - Can provide multiple
#Jenkins.servers[0]=http://hudson.company.com

    #Determines if build console log is collected - defaults to false
#Jenkins.saveLog=true
```

It is likely a password reset could fix this ... not sure.

**Comment by tabladrum** [comment]
The above stack trace tells me that the properties file was not set using the DASHBOARD_PROP environment variable. You can set this in setenv.sh in tomcat.

**Comment by radkin** [comment]
Got a step closer, after setting the DASHBOARD_PROP and running `./gradlew :UI:run`
I get this on the dashboard page (API)
```bash
HTTP ERROR: 503

Problem accessing /api/dashboard. Reason:

    Service Unavailable
Powered by Jetty://
```
It's running and listening now
```bash
tcp        0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN      1893/mongod
tcp        0      0 127.0.0.1:44527         0.0.0.0:*               LISTEN      2755/java
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      2755/java
tcp6       0      0 :::3000                 :::*                    LISTEN      2828/gulp
```
One small problem I had is that I didn't notice the one little line that said "press any button to stop" in the middle of tons of verbose text that spews out with the debug option. I was accidentally stopping our Jetty "run" even when there was no ERROR for about ten minutes there. It's a silly thing, but might be useful to someone who is just starting out as they could spend a lot more time fumbling on that.

**Comment by amitmawkin** [comment]
I think we can close this issue now, we have provided a lot of guidance on how to get started, docker containers for quick running of api and ui layer. Guidance to set mongodb database

**Comment by gituseranh** [comment]
Nice discussion and useful documentation. In many places, we are requird to specify the proxy id/pwd if our computer is located behind an authenticated corporate proxy: eg, 
export HTTPS_PROXY=http://companyId:yourPassword@your.proxy.domain.name:8080

Has anyone tried using encrypted password - how to replace 'yourPassword' with an encrypted password?

**Comment by Chris147uk** [comment]
Was the outcome of this the current set up instructions? or is there another guide that I can follow to set up? I'm currently trying to follow - https://hygieia.github.io/Hygieia/setup.html
