### ISSUE TITLE
updateSubnetworkObject() has an NPath complexity of 65536	CloudSubnetServiceImpl.java

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#670]
Please review the implimentation of this method.

Description Resource    Path    Location    Type
The method updateSubnetworkObject() has an NPath complexity of 65536    CloudSubnetServiceImpl.java /api/src/main/java/com/capitalone/dashboard/service line 96 PMD Marker

**Comment by nireeshT** [comment]
Fixed in PR https://github.com/capitalone/Hygieia/pull/916
