### ISSUE TITLE
getEstimate() has an NPath complexity of 240	FeatureServiceImpl.java

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#671]
Review required of this methods implementation.

Description Resource    Path    Location    Type
The method getEstimate() has an NPath complexity of 240 FeatureServiceImpl.java /api/src/main/java/com/capitalone/dashboard/service line 237    PMD Marker

**Comment by MarkRx** [comment]
Working on code that has a bunch of perf, robustness, and bug fixes. Will be fixed with it. https://github.com/paychex/Hygieia/tree/jira

**Comment by nireeshT** [comment]
Fixed in PR https://github.com/capitalone/Hygieia/pull/916
