### ISSUE TITLE
CloudConfig override both equals() and hashCode()	

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#672]
update required, probably should add tests for a change like this..

Description Resource    Path    Location    Type
Ensure you override both equals() and hashCode()    CloudConfig.java    /core/src/main/java/com/capitalone/dashboard/config/collector   line 128    PMD Marker

**Comment by nireeshT** [comment]
Fixed in PR https://github.com/capitalone/Hygieia/pull/916
