### ISSUE TITLE
Confusion on Jira Time Tracking

### ISSUE THREAD

**Issue by MarkRx** [capitalone/Hygieia#673]
Hello,

The current jira implementation seems to pull time tracking data from the "timetracking" field in the REST json response for Stories. This seems strange as time tracking shouldn't be done on stories directly but instead on sub-tasks since stories are abstractions that use abstract measurements (story points). In our system stories do not have time tracking so that field is always empty. As a result the jira widget is always reporting 0 for todo/in progress/done. It does have some fields that appear to be aggregates of sub-task timings (like "aggregatetimespent" in seconds) but those only show up if sub tasks are actually created.

So questions:

1. Why does the current implementation pull time tracking information from stories?
2. Does someone have an example of a system that is currently using the jira collector?

If the current reporting behavior is intentional then I was thinking I would make a code change to allow users to configure the widget to report on either hours or story points. I'm not quite sure what fields to pull for hourly estimates though due to what I mentioned above.

**Comment by tabladrum** [comment]
@MarkRx: full discloser - we have limited expertise on Jira. Sounds like you are deeper into Jira understanding than we are. Propose a PR and we can collaborate. THANKS!

**Comment by jimzucker** [comment]
@MarkRx  @tabladrum JIRA will normally sum all the children onto the parent so pulling from there should be OK.  I think the salient point is you may want 'story points' vs hours, I would think most people want the 'Story Points' but some of us use hours. So maybe in the pull request to give a choice would be good..

**Comment by MarkRx** [comment]
@tabladrum @jimzucker @amp5208 Is there a team/company using the jira collector? It looks like the estimates for stories are based on issue.getTimeTracking().getRemainingEstimateMinutes(). If that corresponds to the remaining number of minutes a task has then that seems wrong. The UI would incorrectly report the in-progress hours value and the "done" value as those would constantly be changing when work is completed. For example, if I have (10, 12, 5) (todo, inprogress, done) and a task in progress goes from 5 hours remaining to 3 hours remaining I now have (10, 10, 5) instead of (10, 10, 7).

**Comment by MarkRx** [comment]
Here is what I might do:

For jira change sEstimate to use getOriginalEstimateMinutes(). Add a sStoryPoints field for story points and pull the value from a configurable field returned in the rest call. VersionOne will populate the sEstimate and sStoryPoints field with the same value. The UI will have a configuration for jira to specify a reporting metric of either hours or story points.

**Comment by MarkRx** [comment]
Experimenting with solution @ https://github.com/paychex/Hygieia/tree/feature/TAXSDLC-638

**Comment by MarkRx** [comment]
PR #682
