### ISSUE TITLE
Jira features without sprints default to KANBAN

### ISSUE THREAD

**Issue by MarkRx** [capitalone/Hygieia#678]
PR #606 added kanban support to the feature collector widget. For jira it looks like stories are defaulting to be kanban if they do not have a sprint associated to them. As a result stories that are on the backlog for teams that exclusively use scums are showing up as being part of a kanban sprint.

Not sure how to properly address the issue.

**Comment by tabladrum** [comment]
@MarkRx Noticed that too. The assumption may not be correct for everyone. Let me do some digging in.

**Comment by MarkRx** [comment]
Adding @amp5208 

I don't know if there is a way to programmatically determine the sprint type. In our system we have teams that use kanban by using really long single springs. There are other kanban teams that don't have any sprints period.

Not having a sprint cannot default to being kanban since in the context of a scrum team it means the story is on the backlog.

Perhaps the UI could be configurable.
- Kanban - all features for active sprints and stories without a sprint. Only show Total + WIP
- Scrum - all features for active sprints. Show total + WIP + Done
- Both - not sure this is a real use case. If it was there is overlap in the data above so not sure how it would work.

**Comment by amp5208** [comment]
@MarkRx :  I have reviewed this issue and the open issued tied to it for context.  I used the logic of sprint length to determine if a team was kanban or scrum, based on the assumption you mentioned above.  I am aware that this is not perfect logic; however, Jira does not provide a programatic way or built-in field that I can with 100% certainty confirm if a Jira board is, in fact, kanban or scrum.  Their API does not support this, based on my research.

As for your suggestion, the "both" use case is already covered.  If a Jira project has both Kanban and Scrum stories, the UI will switch between all available Scrum and Kanban boards within the Jira project.  Let me know if you need additional clarification.

**Comment by MarkRx** [comment]
Working on this now.

**Comment by MarkRx** [comment]
@amp5208 do you have teams that have both active scrum and active kanban sprints? Is the 'both' option needed?

I'm looking at changing the sprint type to be a configuration item that is set. As such it doesn't make sense to me for the 'both' case to remove sprint types if no iterations of the type are found. If one type doesn't exist but the user explicitly set it to 'both' then I would expect to see both regardless of if there is data or not.

Also in the collector I have to remove the fake KANBAN sprint data that is being attached to stories if no sprints are found. This is because not having a sprint does not imply KANBAN - it could simply be a backlog item. Instead of trying to deduce scrum/kanban it would be configured in the UI.

**Comment by MarkRx** [comment]
Which makes the most sense? @amp5208 @tabladrum 

1.
- Kanban: all features for active sprints and stories without a sprint
- Scrum: all features for active sprints
- Both:
    - Kanban: all features for stories without a sprint
    - Scrum: all features for stories in active sprints

This results in inconsistencies.

2.
- Kanban: all features without a sprint
- Scrum: all features for active sprints
- Both:
    - Kanban: all features for stories without a sprint
    - Scrum: all features for stories in active sprints

This results in consistency but teams that do kanban with a single super long sprint are not handled.

3.
- Kanban: all features without a sprint plus those in sprints that don't have an end date (or end far in the future)
- Scrum: all features for active sprints that have an end date
- Both:
    - Kanban: all features for stories without a sprint plus those in sprints that don't have an end date (or end far in the future) 
    - Scrum: all features for active sprints that have an end date

This allows for us to handle the kanban case that uses a single non-ending sprint.

4. Instead of configuring by kanban vs scrum, have a checkbox to include stories without active sprints.
When it is checked -> kanban (stories in active sprints + stories without a sprint)
When it is not checked -> scrum (stories in active sprints only)

This isn't as flexible.

**Comment by MarkRx** [comment]
WIP @ https://github.com/paychex/Hygieia/tree/feature/TAXSDLC-956

**Comment by tabladrum** [comment]
@amp5208 are you still working on Hygieia related stuff?

**Comment by MarkRx** [comment]
PR #903

**Comment by MarkRx** [comment]
Fixed in PR.
