### ISSUE TITLE
Hygieia dashboard to show jenkins multiple job build result

### ISSUE THREAD

**Issue by vijayct2001** [capitalone/Hygieia#679]
As of now am able to see single job build results in "build per day" dashboard. But how to configure hygieia dashboard to show multiple build jobs here.

**Comment by tabladrum** [comment]
The idea is to create a set of team/component dashboard where a component has a code repo, a build job etc. And then create a product dashboard where the component dashboards can be added. The product dashboard then will show the pipeline (code -> build -> deploy) of all components in 1 single view.

**Comment by vijayct2001** [comment]
Am okey to close this issue.

**Comment by satishc1** [comment]
Closed per comment above.
