### ISSUE TITLE
What does the monitor widget do?

### ISSUE THREAD

**Issue by MarkRx** [capitalone/Hygieia#681]
What does this widget do? The user has the ability to add messages and set some status label. It can also depend on other services. It all seems to be static.

I was expecting something that would monitor REST service endpoints. The monitor would periodically ping some endpoint to determine its health. I don't see anything in the code to do this.

What is the purpose of this widget?

**Comment by tabladrum** [comment]
In another two-three weeks this will be replaced by Performance Matrix widget (first version) - first version will have integration with AppDynamics.

**Comment by vijayct2001** [comment]
Dynatrace integration release date please?

**Comment by raynaya** [comment]
@tabladrum - Can you elaborate on what you mean when you say  " share service availability ".  Is it like monitoring things are up or down. Like health check ? If how does it work. Actually I want to have something like that.

**Comment by MarkRx** [comment]
@tabladrum what's the status on the AppD integration?

**Comment by satishc1** [comment]
@MarkRx For monitor widget https://github.com/capitalone/Hygieia/pull/1292
In regards to AppD integration we should be getting a PR soon.

**Comment by hameed-repository** [comment]
Hi can you please share us the status on AppD
