### ISSUE TITLE
Cucumber Collector API

### ISSUE THREAD

**Issue by mickfeech** [capitalone/Hygieia#684]
As it appears that the swagger documentation is still a work in progress.  What are the necessary parameters to post cucumber results against the API?  Just looking for an example of the JSON to post, similiar to #480 .  Thanks.

**Comment by amitmawkin** [comment]
Swagger should be availabke for you , if you are running the api you can reach it

**Comment by mickfeech** [comment]
How do I reach it?  All i'm getting is the JSON at http://localhost:3000/api/v2/api-docs

**Comment by tabladrum** [comment]
http://my.hygieia.com/api/swagger/index.html

**Comment by mickfeech** [comment]
Thanks
