### ISSUE TITLE
How do I collect data into the 'artifacts' collection?

### ISSUE THREAD

**Issue by MarkRx** [capitalone/Hygieia#685]
After reading and debugging through to code to find out why my product dashboard doesn't show QA - PROD data I found EnvironmentComponentEventListener which appears to associate commits to environments based on deployed components. I don't see any collector that puts data into that repository. The only entry-point I see is a rest API.

Is this an incomplete feature or am I missing something? Do I need to setup something to create these BinaryArtifacts for me?

**Comment by tabladrum** [comment]
Artifacts are created via Jenkins Plugin as of now. We had a collector for Nexus long ago but ran into severe performance issue with it. 

There are two use cases where the EnvironmentComponentListener is used - via the api (which is called from Jenkins plugin) OR the urbancode/xldeploy collectors.
