### ISSUE TITLE
Hygieia integration with chef. Possible?

### ISSUE THREAD

**Issue by parasbajaj** [capitalone/Hygieia#687]
Hi,

I would like to know if Hygieia with chef integration is possible. If it is please let me know.

**Comment by tabladrum** [comment]
I am aware that a team from another company has created this integration. Waiting on a PR from them.

**Comment by parasbajaj** [comment]
Please let me know if you get it.

**Comment by satishc1** [comment]
@parasbajaj https://github.com/RLIndia/Hygieia/tree/master/chef-collector
