### ISSUE TITLE
QA dashboard disappeared after couple of days

### ISSUE THREAD

**Issue by SudhaReddennagari** [capitalone/Hygieia#688]
Hi, I have created a dash board named 'Raksha'. But it got disappeared after couple of days, I do observe that the same thing happened with one of the other team in our ART.I am trying to find out the reason behind this.

**Comment by tabladrum** [comment]
Was your dashboard empty or somethings were configured?

**Comment by SudhaReddennagari** [comment]
I did have few widgets ( feature,code repo,Quality ) configured.

**Comment by satishc1** [comment]
Closed.
