### ISSUE TITLE
Functional Tests not showing

### ISSUE THREAD

**Issue by mickfeech** [capitalone/Hygieia#689]
The functional tests are not showing in the dashboard, even though there are entries in the database

![image](https://cloud.githubusercontent.com/assets/658759/16771583/088e8da0-481f-11e6-9049-89ccf7381c65.png)

`> db.test_results.find({})
{ "_id" : ObjectId("578504c5e8bdde72837da28e"), "_class" : "com.capitalone.dashboard.model.TestResult", "collectorItemId" : ObjectId("5784049fe8bdde72837da274"), "timestamp" : NumberLong(0), "executionId" : "2834", "buildId" : ObjectId("5783d4e0e8bdde72837da240"), "description" : "projects/webapp", "url" : "http://jenkins:8080/job/projects/job/webapp", "startTime" : NumberLong(1468277480), "endTime" : NumberLong(1468277600), "duration" : NumberLong(120), "failureCount" : 6, "successCount" : 210, "skippedCount" : 9, "totalCount" : 225, "unknownStatusCount" : 0, "type" : "Functional", "testCapabilities" : [ { "timestamp" : NumberLong(0), "startTime" : NumberLong(0), "endTime" : NumberLong(0), "duration" : NumberLong(0), "failedTestSuiteCount" : 0, "successTestSuiteCount" : 24, "skippedTestSuiteCount" : 0, "totalTestSuiteCount" : 24, "unknownStatusTestSuiteCount" : 0, "testSuites" : [ ] }, { "timestamp" : NumberLong(0), "startTime" : NumberLong(0), "endTime" : NumberLong(0), "duration" : NumberLong(0), "failedTestSuiteCount" : 1, "successTestSuiteCount" : 19, "skippedTestSuiteCount" : 2, "totalTestSuiteCount" : 22, "unknownStatusTestSuiteCount" : 0, "testSuites" : [ ] }, { "timestamp" : NumberLong(0), "startTime" : NumberLong(0), "endTime" : NumberLong(0), "duration" : NumberLong(0), "failedTestSuiteCount" : 0, "successTestSuiteCount" : 52, "skippedTestSuiteCount" : 0, "totalTestSuiteCount" : 52, "unknownStatusTestSuiteCount" : 0, "testSuites" : [ ] }, { "timestamp" : NumberLong(0), "startTime" : NumberLong(0), "endTime" : NumberLong(0), "duration" : NumberLong(0), "failedTestSuiteCount" : 0, "successTestSuiteCount" : 49, "skippedTestSuiteCount" : 0, "totalTestSuiteCount" : 49, "unknownStatusTestSuiteCount" : 0, "testSuites" : [ ] }, { "timestamp" : NumberLong(0), "startTime" : NumberLong(0), "endTime" : NumberLong(0), "duration" : NumberLong(0), "failedTestSuiteCount" : 4, "successTestSuiteCount" : 43, "skippedTestSuiteCount" : 7, "totalTestSuiteCount" : 54, "unknownStatusTestSuiteCount" : 0, "testSuites" : [ ] }, { "timestamp" : NumberLong(0), "startTime" : NumberLong(0), "endTime" : NumberLong(0), "duration" : NumberLong(0), "failedTestSuiteCount" : 1, "successTestSuiteCount" : 23, "skippedTestSuiteCount" : 0, "totalTestSuiteCount" : 24, "unknownStatusTestSuiteCount" : 0, "testSuites" : [ ] } ] }
{ "_id" : ObjectId("578504cce8bdde72837da28f"), "_class" : "com.capitalone.dashboard.model.TestResult", "collectorItemId" : ObjectId("5784049fe8bdde72837da274"), "timestamp" : NumberLong(0), "executionId" : "2835", "buildId" : ObjectId("5783d4e0e8bdde72837da240"), "description" : "projects/webapp", "url" : "http://jenkins:8080/job/projects/job/webapp", "startTime" : NumberLong(1468277480), "endTime" : NumberLong(1468277600), "duration" : NumberLong(120), "failureCount" : 6, "successCount" : 210, "skippedCount" : 9, "totalCount" : 225, "unknownStatusCount" : 0, "type" : "Functional", "testCapabilities" : [ { "timestamp" : NumberLong(0), "startTime" : NumberLong(0), "endTime" : NumberLong(0), "duration" : NumberLong(0), "failedTestSuiteCount" : 0, "successTestSuiteCount" : 24, "skippedTestSuiteCount" : 0, "totalTestSuiteCount" : 24, "unknownStatusTestSuiteCount" : 0, "testSuites" : [ ] }, { "timestamp" : NumberLong(0), "startTime" : NumberLong(0), "endTime" : NumberLong(0), "duration" : NumberLong(0), "failedTestSuiteCount" : 1, "successTestSuiteCount" : 19, "skippedTestSuiteCount" : 2, "totalTestSuiteCount" : 22, "unknownStatusTestSuiteCount" : 0, "testSuites" : [ ] }, { "timestamp" : NumberLong(0), "startTime" : NumberLong(0), "endTime" : NumberLong(0), "duration" : NumberLong(0), "failedTestSuiteCount" : 0, "successTestSuiteCount" : 52, "skippedTestSuiteCount" : 0, "totalTestSuiteCount" : 52, "unknownStatusTestSuiteCount" : 0, "testSuites" : [ ] }, { "timestamp" : NumberLong(0), "startTime" : NumberLong(0), "endTime" : NumberLong(0), "duration" : NumberLong(0), "failedTestSuiteCount" : 0, "successTestSuiteCount" : 49, "skippedTestSuiteCount" : 0, "totalTestSuiteCount" : 49, "unknownStatusTestSuiteCount" : 0, "testSuites" : [ ] }, { "timestamp" : NumberLong(0), "startTime" : NumberLong(0), "endTime" : NumberLong(0), "duration" : NumberLong(0), "failedTestSuiteCount" : 4, "successTestSuiteCount" : 43, "skippedTestSuiteCount" : 7, "totalTestSuiteCount" : 54, "unknownStatusTestSuiteCount" : 0, "testSuites" : [ ] }, { "timestamp" : NumberLong(0), "startTime" : NumberLong(0), "endTime" : NumberLong(0), "duration" : NumberLong(0), "failedTestSuiteCount" : 1, "successTestSuiteCount" : 23, "skippedTestSuiteCount" : 0, "totalTestSuiteCount" : 24, "unknownStatusTestSuiteCount" : 0, "testSuites" : [ ] } ] }
`

**Comment by tabladrum** [comment]
Do you have the API running? If yes, do you see any error? Also, you can see the api calls and status on the browser too. 

![image](https://cloud.githubusercontent.com/assets/6014941/16773352/a369262c-4825-11e6-99fd-064e3cbe947b.png)

**Comment by mickfeech** [comment]
Yes, the API is running, everything else that I have setup is bringing data back.  There are no errors generated from the API.  It's making the call but not returning the data.  I can see the componentId it's is searching for, which mongo collection is it looking for there?

![image](https://cloud.githubusercontent.com/assets/658759/16773588/74ac5600-4826-11e6-8e22-8f37a0921ea7.png)

**Comment by mickfeech** [comment]
I found where the componentId is and everything is matching up but it doesn't seem to be returning a result.

**Comment by tabladrum** [comment]
How did you get the JSON in the mongoDB? Through Jenkins Plugin or via the collector? In any case, it looks odd. The timestamp is 0.

**Comment by mickfeech** [comment]
I think I may have narrowed it down, but I need someone else to look at it.  The API for the tests wants the parameter type.  It looks like the UI is querying "types".  Either there's a translation I'm missing or the query isn't working as expected

Should this line be type and not types?  If I manually query with "types" the result is empty, if I query with type things return.

https://github.com/capitalone/Hygieia/blob/master/UI/src/components/widgets/codeanalysis/view.js#L32

![image](https://cloud.githubusercontent.com/assets/658759/16777039/03f173d6-4836-11e6-9ca2-9d9b2d524741.png)

**Comment by mickfeech** [comment]
@tabladrum The collector doesn't work for our situation as we are running WebDriverIO with a different reporter so I'm parsing the data and posting it to the 'quality/test' api

**Comment by tabladrum** [comment]
There are two missing pieces: the type and the timestamp. set the type to "Functional" and set the timestamp to the execution time (system time in milliseconds in your case).

**Comment by mickfeech** [comment]
I've dropped the contents and added a new entry with type (it was already set) and with the timestamp to no avail. 
```
> db.test_results.find({}, {timestamp: 1, type: 1}).pretty()
{
        "_id" : ObjectId("57852e05e8bdde72837da2b6"),
        "timestamp" : NumberLong(1468277480),
        "type" : "Functional"
}
```

 If I change the 
[view.js](https://github.com/capitalone/Hygieia/blob/master/UI/src/components/widgets/codeanalysis/view.js#L32) from types to type it finally displays on the UI but doesn't calculate percentages.

![image](https://cloud.githubusercontent.com/assets/658759/16777690/85fc2a18-4838-11e6-9e0b-bde032e28c23.png)

**Comment by tabladrum** [comment]
Here is part of one sample json from my local DB:
`
{
    "_id" : ObjectId("574b99c49456e3e945880d48"),
    "_class" : "com.capitalone.dashboard.model.TestResult",
    "collectorItemId" : ObjectId("574a0cc59456e3b51caee922"),
    "timestamp" : NumberLong(1464572356045),
    "executionId" : "163",
    "buildId" : ObjectId("574b99c19456e3e945880d47"),
    "description" : "Hygieia-Common-New-3",
    "url" : "http://localhost:8082/job/Hygieia-Common-New-3/",
    "startTime" : NumberLong(1464572353376),
    "endTime" : NumberLong(1464572355506),
    "duration" : NumberLong(2130),
    "failureCount" : 18,
    "successCount" : 4,
    "skippedCount" : 0,
    "totalCount" : 44,
    "unknownStatusCount" : 22,
    "type" : "Functional",
    "targetAppName" : "NewApp",
    "targetEnvName" : "Dev",
    "testCapabilities" : [ 
``

**Comment by tabladrum** [comment]
Do you have the parsing code on github? I can take a look.

**Comment by mickfeech** [comment]
Unfortunately, my custom collector/parser has too much proprietary data in it that would have to be scrubbed to make public at this time.

As previously mentioned, though, I now have the functional test displaying (after changing line 32 of the javascript), but it's not calculating the percentage.  Using your sample it was still not displaying until I changed the view.js file.

Before:
![image](https://cloud.githubusercontent.com/assets/658759/16778337/98041772-483b-11e6-95b5-a84ff7aaa79d.png)
After:
![image](https://cloud.githubusercontent.com/assets/658759/16778396/d6a4e7a4-483b-11e6-8c75-3aeb9d4c1771.png)

**Comment by tabladrum** [comment]
The API is designed to handle multiple types. The behavior that you mentioned is really odd. The search request object is below: 

'
public class TestResultRequest {
    @NotNull
    private ObjectId componentId;
    private Integer max;
    private Long startDateBegins;
    private Long startDateEnds;
    private Long endDateBegins;
    private Long endDateEnds;
    private Long durationGreaterThan;
    private Long durationLessThan;
    @Range(min = 0, max = 4)
    private Integer depth;
    private List<TestSuiteType> types = new ArrayList<>();

**Comment by tabladrum** [comment]
Can you compare your parsing code with this:

(https://github.com/capitalone/Hygieia/blob/master/hygieia-jenkins-plugin/src/main/java/hygieia/builder/CucumberTestBuilder.java)

**Comment by mickfeech** [comment]
I was using that as my guide already.  Here's the snippets of the parser.

https://gist.github.com/mickfeech/a33d30dad01d6cf3de0cad4ae74df0b0

**Comment by tabladrum** [comment]
Can you share the latest JSON from your DB?

**Comment by mickfeech** [comment]
Sure, here is one of the records.  https://gist.github.com/mickfeech/58ad7b22c5ca266f33cf14cf0cd5ead1

**Comment by tabladrum** [comment]
MongoDB is not liking the JSON. The NumberLong format is incorrect

"startTime" : NumberLong("1468278178000")

Should be "startTime" : NumberLong(1468278178000)

**Comment by tabladrum** [comment]
Checkout this modified json
https://gist.github.com/tabladrum/e70170ddb6ee60021cb23bf3240bb593

I had to change the collector item id. So change it back to what you had.
Two changes: (1) NumberLong format and (2) Add "type" to Capability too and set to Functional - I will see if we need multiple types in the same JSON and keep it only at the top level - but for now this is how it is :-(

**Comment by mickfeech** [comment]
Great.  Thanks, for what it's worth it appears setting the type to functional in the capability did the trick.  I'd suggest that if you do need the type in both layer of the JSON perhaps you throw an exception if the type of the capability isn't set.

**Comment by tabladrum** [comment]
Should we close this issue for now?

**Comment by mickfeech** [comment]
Absolutely.  Thanks for your assistance!
