### ISSUE TITLE
Question - Hygieia integration with Anthillpro and Rally

### ISSUE THREAD

**Issue by eldojoseph** [capitalone/Hygieia#690]
All,
I am working implementing Hygieia in my project. Is there a collector available for Anthillpro and Rally already? If not could someone help me to find some document on creating new collectors?

Thanks
Eldo

**Comment by tabladrum** [comment]
I am not aware of anyone working on AnthillPro collector. 
I have seen at least two forks of this project with some implementation of Rally collector. I should have bookmarked those!
