### ISSUE TITLE
Need the drop downs of  different Widget in Hygiea to be Searchable

### ISSUE THREAD

**Issue by amitmawkin** [capitalone/Hygieia#692]
As number of Jenkins instances and build jobs increase over time it becomes difficult to locate your build job while configuring the database.

- Below is an attempt to address this issue, and we will evolve it over time as we develop this more to suit the community needs

- Same thing has been applied for CodeAnalysis , Feature and Deploy widget.

![image](https://cloud.githubusercontent.com/assets/6624821/16806210/92b9a9ac-48e1-11e6-855b-b7345b483796.png)

**Comment by tabladrum** [comment]
💯

**Comment by amitmawkin** [comment]
This is resolved via https://github.com/capitalone/Hygieia/pull/693 , closing the issue
