### ISSUE TITLE
Performance Monitoring

### ISSUE THREAD

**Issue by blashmet** [capitalone/Hygieia#697]
Can Hygieia monitor SQL performance or alert when an environment goes down? (e.g., if the DEV environment goes down, "down" being defined in some way, e.g., a VM being down, not being able to query a certain db, not able to check in to TFS, etc.)

**Comment by tabladrum** [comment]
Not yet. In fact, Hygieia is purely a data collection place with UI. We are building an integration with Appdynamics and will extend that to other tools.

**Comment by satishc1** [comment]
Closing this.

**Comment by cherrera91** [comment]
when will AppDynamics collector will be available?
