### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by novetbstewart** [capitalone/Hygieia#699]
If i only intend to use the Jenkins and Sonarqube widget, do i still have to see the other empty widgets? I couldn't tell from the video posted on youtube. I'd like to just use those two only, but i'm afraid of spending the time to set it up and then find that the empty 4 widgets are sitting there idle.

Any information would be greatly appreciated.

**Comment by tabladrum** [comment]
You can create your own template. See https://github.com/capitalone/Hygieia/tree/master/UI/src/components/templates

Create your template and add here: https://github.com/capitalone/Hygieia/blob/master/UI/src/app/dashboard/controllers/createDashboard.js

        // TODO: dynamically register templates with script
        ctrl.templates = [
            {value: 'capone', name: 'Cap One', type: DashboardType.TEAM},
            {value: 'caponechatops', name: 'Cap One ChatOps', type: DashboardType.TEAM},
            {value: 'splitview', name: 'Split View', type: DashboardType.TEAM},
            {value: 'product-dashboard', name: 'Product Dashboard', type: DashboardType.PRODUCT}
        ];

**Comment by novetbstewart** [comment]
Great, i'll give this a shot, thank you.
