### ISSUE TITLE
More helpful error when NodeJS UI fails to connect to Java backend

### ISSUE THREAD

**Issue by msabramo** [capitalone/Hygieia#70]
Trying to spin it up and I'm only running the NodeJS backend. I wanted to see how it would fail if I didn't have the backend running so I could better understand what port the backend runs on and such. But the error is not so helpful:

```
[Proxy] { [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
```

I would love it if it would say what code is failing and what it's trying to connect to.

If you let me know where this might be happening, I could take a stab at a PR....

**Comment by hughbrien** [comment]
+1 or at least HIGHLIGHT the fact that the API needs be started.

**Comment by tabladrum** [comment]
Can we close this?

**Comment by tabladrum** [comment]
Not hearing about this issue any more. Closing. If someone sees this issue again, please add a new one.
