### ISSUE TITLE
Sonar Code Coverage is showing incorrect pie chart.

### ISSUE THREAD

**Issue by raynaya** [capitalone/Hygieia#701]
The actual values from db 

```
{
			"name" : "coverage",
			"value" : 96.5,
			"formattedValue" : "96.5%",
			"status" : "Ok"
		},
```

But in the UI its showing 0% coverage. Is this a known issue ?

**Comment by jimzucker** [comment]
No its not a know issue.  can you try and debug it, the code for creating the screen is in UI/src/components/widgets/codeanalysis/view.js

**Comment by raynaya** [comment]
I found the issue by looking at different db entries. If it is  `"name" : "coverage" `we are not displaying it . If its `"name" : "line_coverage"` then it is displayed. Which is fine I guess. 

But the real issue is once a projects sonar details are loaded in the db based on the metrics I had put in the properties file during the first run. Even if I change the property file to add new metrics at a later stage, its not loading the new metrics specified in the subsequent cron jobs.

**Comment by tabladrum** [comment]
If you change the properties file, you need to restart the collector. But your issue points to a good enhancement: Let the UI capture the things that we want to the sonar collector to capture.

**Comment by raynaya** [comment]
Yes. I restarted the collector. Even after that the previously collected stats in the db for a project  is not updated with the new metrics I have specified. 

Yes the UI modification will be really nice to have down the line.

**Comment by tabladrum** [comment]
Can you delete the existing DB record and re run the collector? The collector wont upsert a record if SONAR's api sends the same date time stamp for the latest scan. Or, you can run another scan instead and look for the new record.

**Comment by raynaya** [comment]
Ahh.  Makes sense.  Probably the data has not been updated in sonar since last scan. 

 For new scans the newly added metrics are coming as expected.
