### ISSUE TITLE
Hygieia dashboard issue with Internet Explorer

### ISSUE THREAD

**Issue by vijayct2001** [capitalone/Hygieia#703]
In Microsoft IE dashboard not showing jenkins output.
1. Builds per day - Line chart not showing.
2. Average build duration - Bar chart not  showing.
3. Latest Builds - No issues.
Please help me to resolve graph issues in Internet Explorer- v11.

**Comment by vijayct2001** [comment]
Yeah, Here i uploaded screenshot for your reference...
Error:   SCRIPT438: Object doesn't support property or method 'remove'
File: gridBoundaries.js, Line: 16, Column: 21

![image](https://cloud.githubusercontent.com/assets/11028464/16991357/db946194-4eb8-11e6-8543-befadba2a313.png)


![image](https://cloud.githubusercontent.com/assets/11028464/16991235/81ec977e-4eb8-11e6-874a-b6824b6730ca.png)

**Comment by tabladrum** [comment]
Which version of IE?

**Comment by vijayct2001** [comment]
Windows-7 with Internet Explorer- v11.0

**Comment by andyct** [comment]
I have similar IE issue. The charts are displayed fine on mozilla firefox and chrome. But it is not shown on IE v10 or 11. Any resolution, please share.

**Comment by chethanbs** [comment]
I have the same problem.Graph is not coming up on the dashboard.I am using IE.Please share your thoughts.

**Comment by princevijayakumar** [comment]
I have the same problem. Graph is not generated on the dashboard. Windows-7 with Internet Explorer- v11.0. please help me to resolve this issue

**Comment by satishc1** [comment]
Closed.
