### ISSUE TITLE
Installation Instructions for .net types.

### ISSUE THREAD

**Issue by novetbstewart** [capitalone/Hygieia#705]
Where is the full installation instructions?

`mvn clean package` isn't going to cut it, at least for me. I want to use the project, but for the average .net release/development person, there is quite the learning curve here.

I've run the maven command and it's successful. But then what? 
1. What folders do i take, where do i place them.
2. Where are the configuration files?
3. What third party software is required on the deployed system? Mongo? What else?

Maybe i've missed this, but i can't find full instructions anywhere. I just want to install this on a single windows server, not a docker image.

How does one go about that?

**Comment by tabladrum** [comment]
Check this and let me know: http://www.capitalone.io/Hygieia/

**Comment by novetbstewart** [comment]
That's a link to the main page with a video. But there are no step by step instructions. Any plans for that?

**Comment by satishc1** [comment]
@novetbstewart 
This should help. Let us know if there are any issues.
http://www.capitalone.io/Hygieia/getting_started.html
