### ISSUE TITLE
Method is not doing anything: private CloudVolumeAggregatedResponse aggregate

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#706]
@tabladrum  - Reviewing PMD warnings I found this method is not doing anything:
```java
private CloudVolumeAggregatedResponse aggregate(Collection<CloudVolumeStorage> volumes, CloudConfig config)
```
Clearing up the PMD warnings would be trivial but it looks ike there is a bigger issue here, either we can factor out the method or it needs to be fixed to do the right thing.  Right now it just created  an empty CloudVolumeAggregatedResponse object and returns it.

PMD Warnings that lead me to review this:
```
Description Resource    Path    Location    Type
Avoid unused local variables such as 'rd'.  CloudVolumeServiceImpl.java /api/src/main/java/com/capitalone/dashboard/service line 176    PMD Marker

Avoid unused method parameters such as 'config'.    CloudVolumeServiceImpl.java /api/src/main/java/com/capitalone/dashboard/service line 161    PMD Marker
```

**Comment by tabladrum** [comment]
Yeah. We are still developing on it. Will correct it ASAP.

**Comment by amitmawkin** [comment]
@tabladrum  please see this one

**Comment by satishc1** [comment]
@jimzucker Closed. Reopen if still an issue.
