### ISSUE TITLE
Incorrect Architecture Diagram on the home page?

### ISSUE THREAD

**Issue by RobertKelly** [capitalone/Hygieia#709]
Is the diagram referenced on the home page here: https://github.com/capitalone/Hygieia/blob/master/media/images/overview/2.png
Correct?
It shows the collectors talking to the ReST Api.  This has caused some confusion for new developers.  Is this correct?

**Comment by softwareklinic** [comment]
Yes.need to revise

**Comment by amitmawkin** [comment]
any updates on this @softwareklinic

**Comment by Megha849** [comment]
@RobertKelly @softwareklinic - The updated architecture diagram is available at: https://github.com/capitalone/Hygieia/blob/gh-pages/media/images/architecture.png
