### ISSUE TITLE
API connectivity issue

### ISSUE THREAD

**Issue by swathireddy2808** [capitalone/Hygieia#711]

**Comment by swathireddy2808** [comment]
hi,
i am trying with Hygieia dashboard, i got a Hygieia login page but unable to connect api..
according to errors i agve the execute permissions and tried it
re-created database

could any one help with this issue
![hygieia page](https://cloud.githubusercontent.com/assets/20541078/17034314/22ab404c-4f50-11e6-965f-2e68e88f6284.JPG)

**Comment by tabladrum** [comment]
can you hit the api with this: http://<your host>/api/ping

**Comment by amitmawkin** [comment]
no response.. hence closing this issue

**Comment by atul1989** [comment]
hello amin same issue i am also facing , after try to ping http://your.host/api/ping , nothing is coming into the screen

**Comment by atul1989** [comment]
how can resolve the api disconnectivity issue with UI
