### ISSUE TITLE
npm install fails in UI

### ISSUE THREAD

**Issue by vinaysingu2** [capitalone/Hygieia#715]
Hi,

I am trying to run npm install in the UI module and getting the following error:

> phantomjs@1.9.20 install /app/MasterTax/Hygieia/UI/node_modules/phantomjs
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v1.9.19/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /app/MasterTax/Hygieia/UI/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Using proxy http://singuvi:******@<proxy-url>:8080/
Receiving...

Error making request.
Error: tunneling socket could not be established, statusCode=407
    at ClientRequest.onConnect (/app/MasterTax/Hygieia/UI/node_modules/tunnel-agent/index.js:165:19)
    at ClientRequest.g (events.js:286:16)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:393:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)

Please report this full log at https://github.com/Medium/phantomjs
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN bl@0.7.0 requires a peer of stream-browserify@* but none was installed.
npm ERR! Linux 3.12.59-60.45-default
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.20 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.20 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/MasterTax/Hygieia/UI/npm-debug.log

I am behind a corporate proxy and have set the proxy correctly. There might still be a chance that the firewall is blocking the connection. Could it be the reason? Is there another way i could install phantomjs to bypass this issue?

Could someone please let me know what the issue could be and give me a possible resolution. Thanks in advance.

**Comment by tabladrum** [comment]
Try manually copying it to /app/MasterTax/Hygieia/UI/node_modules/phantomjs/phantomjs/

**Comment by vinaysingu2** [comment]
This issue was solved by installing phantomjs individually to the system using the .tar.bz2 file and then running the npm install. The installer used the phantomjs installation in the system and continued
