### ISSUE TITLE
Widget Customization..?

### ISSUE THREAD

**Issue by swathireddy2808** [capitalone/Hygieia#717]
Is thare any way to customise the widget on dashboard...?

When i am trying to check the UCD on dashboard it is not showing the proper information like how many deployments has taken and how long its been done?

Could any one help with this.

**Comment by tabladrum** [comment]
Good features to add. Look at https://github.com/capitalone/Hygieia/tree/master/UI/src/components/widgets/deploy

May need some api changes to return those values.

**Comment by c-sreenivasulareddy** [comment]
Any other widget examples to display trending chart?

**Comment by tabladrum** [comment]
You can take a look at the Cloud widget with some chart examples.

**Comment by c-sreenivasulareddy** [comment]
Thank You @tabladrum . Will look into it.
