### ISSUE TITLE
Custom Deploy Collector - Servers Online Issue

### ISSUE THREAD

**Issue by mickfeech** [capitalone/Hygieia#720]
I have a custom deploy collector the following is in the mongo data

```
{
	"_id": ObjectId("5796784b4b2f7fc86c2a3ce8"),
	"environmentID": "Environments/QA",
	"environmentName": "QA",
	"collectorItemId": ObjectId("57966a92d9846e0f6081f1c9"),
	"componentName": "app1",
	"componentVersion": "4",
	"servers": [{
		"name": "app1-4-hwmb6",
		"online": true
	}],
	"deployTime": NumberLong("1469479507907"),
	"environmentUrl": "https://server/console/project/app1-qa",
	"_class": "com.capitalone.dashboard.model.EnvironmentComponent",
	"componentID": "app1",
	"deployed": true,
	"asOfDate": NumberLong("1469479507907")
}
```

However the calls to the API is not returning servers.  What am I missing?
```
{
	"result": [{
		{
		"name": "QA",
		"url": "https://server/console/project/app1-qa",
		"units": [{
			"name": "app1",
			"version": "4",
			"deployed": true,
			"lastUpdated": 1469479507907,
			"servers": []
		}]
	}],
	"lastUpdated": 1469479507907
}
```

**Comment by tabladrum** [comment]
Which collection did you store it to?

**Comment by mickfeech** [comment]
I'm storing them in environment_components , I'm guess that's wrong since they aren't displaying :)

**Comment by tabladrum** [comment]
There are two collections for this . Try storing this way:

Collection: environment_component
{
    "_id" : ObjectId("56d9ec207fab7c452af8088c"),
    "_class" : "com.capitalone.dashboard.model.EnvironmentComponent",
    "collectorItemId" : ObjectId("56d825c07fab7c76a1453332"),
    "environmentName" : "QA",
    "environmentUrl" : "https://udeploy.com/#environment/945f5524-88e3-4fe2-a992-80871341e302",
    "componentName" : "app1.tar",
    "componentVersion" : "1.2.4.0",
    "deployed" : true,
    "deployTime" : NumberLong(1469479507907),
    "asOfDate" : NumberLong(1469479507907)
}



Collection: environment_status

{
    "_id" : ObjectId("56d9ec217fab7c452af8090c"),
    "_class" : "com.capitalone.dashboard.model.EnvironmentStatus",
    "collectorItemId" : ObjectId("56d825c07fab7c76a1453332"),
    "environmentName" : "QA",
    "componentName" : "app1.tar",
    "resourceName" : "app1-4-hwmb6",
    "online" : true
}
`

**Comment by mickfeech** [comment]
That did it.  Thanks. :)
