### ISSUE TITLE
Root project folder for bower installation

### ISSUE THREAD

**Issue by eldojoseph** [capitalone/Hygieia#724]
Can someone help me to find the root folder for execute below commands as part of Hygieia installation?
npm install
bower install

I tried above commands fromsnode folder,  npm install command gave no result and bower install command gave "ENOENT No bower.json present" error
Thanks
Eldo

**Comment by tabladrum** [comment]
UI folder.

Or you can do mvn clean package on the root Hygieia

**Comment by eldojoseph** [comment]
Thank you so much for the response. Do I need to copy "node-v6.3.1-win-x64" files to Hygieia-master or UI folder?

Thanks
Eldo

**Comment by tabladrum** [comment]
I would install node on my laptop - using brew (on Mac) or windows equivalent.

**Comment by eldojoseph** [comment]
I am working on windows machine. I followed below steps,
1. extracted node-v6.3.1-win-x64 to C:\Node\node-v6.3.1-win-x64 folder
2. Successfully executed below commands from C:\Node\node-v6.3.1-win-x64 folder
          npm install -g bower
           npm install -g gulp
3. moved back to C:\Hygieia\Hygieia-master folder where  I have Hygieia source code.
4. Tried to execute "npm install" and "bower install" commands. But got error " **is not recognized as an internal or external command**"

Could you please guide us?

Thanks
Eldo

**Comment by tabladrum** [comment]
can you go to root Hygieia and do "mvn clean package"?

**Comment by eldojoseph** [comment]
Thank you so much. I ran mvn clean package and it came out success. Do I need to execute above commands again? (I hope that will fail if I try). How can I access my UI now? what will be the default link?

Thanks
Eldo

**Comment by DeepakA** [comment]
http://localhost:3000/ is your default link. To start the application follow the steps
1. start mongo db
2. start API
3. start UI 

refer to the documentation for more details.
https://github.com/capitalone/Hygieia/blob/master/Setup.md

**Comment by eldojoseph** [comment]
Thank you so much Tapabrata and Deepak for all your support. We have started all process and UI is working fine  now.
