### ISSUE TITLE
How to add Rally collector.

### ISSUE THREAD

**Issue by rushsontakke** [capitalone/Hygieia#726]
I have sandbox URL for Rally to fetch the statistics for all User Stories and tasks related to my Jenkins or LARA profile.
What should I need to do to add new collector for achieving this approach.

**Comment by tabladrum** [comment]
You should be able to create a collector by copying the JIRA collector and "replace" the JIRA calls with Rally calls. I am sure you will run into some mismatch that you will need to design for. But thats the best way to start. 

You may find some unfinished work on this here: https://github.com/timgifford/Hygieia/tree/rally/rally-feature-collector

**Comment by rushsontakke** [comment]
Thank you so much
If you have any video or document for the code flow, so it will very helpful to create new collector.
Meanwhile I will go through another repo.

**Comment by gokulknewt** [comment]
**Hi Tapabrata,** 

       I have noticed few comments from Hygieia forum.We are not sure how to build the rally collector with dashboard.To integrate the rally-feature-collector with dashboard, What are the configuration steps we  suppose to make sure. Also we would like to know about Initail setup to proceed our implementation.
Can you please provide the steps?

Thanks and Regards,
**Gokul k**

**Comment by satishc1** [comment]
Closed.
