### ISSUE TITLE
subversion-collector application.properties file does not have repository URL

### ISSUE THREAD

**Issue by chethanbs** [capitalone/Hygieia#727]
I am trying to create application property file for subversion-collector.But I do not see repository URL mentioned in sample property file which is given on Git hub site .
( https://github.com/capitalone/Hygieia/tree/master/subversion-scm-collector).

Can anyone please tel me how do we connect to particular repository without mentioning repository URL in application.property file?

**Comment by tabladrum** [comment]
Thanks for pointing this out. Corrected: See this PR https://github.com/capitalone/Hygieia/pull/729

**Comment by chethanbs** [comment]
Thank you. 
I have created repository locally at windows machine and trying to connect with  Hygieia. I tried using "file:///C:/SVN" as subversion url but Hygieia is not accepting the url. Any advice?

**Comment by tabladrum** [comment]
Never tested this out on a local install of subversion. Can you paste any stack trace?

**Comment by chethanbs** [comment]
In the widget we have an option where we can enter subversion repository URL.

My local repository URL is "file:///C:/SVN/branches"

When I  try to enter this URL.It throws a message saying "In Valid URL". so I could not get any stack trace since its not even accepting the URL.It accepts only the repository URL"s which starts with HTTP protocol.

How do we get the details in the dashboard from the repository which I have maintained on my local machine(**file:///C:/SVN/branches**)?

Any help would be greatly helpful.

**Comment by nitin1706** [comment]
@chethanbs : can you try with the SVN host url instead of local setup.
