### ISSUE TITLE
  subversion collector

### ISSUE THREAD

**Issue by chethanbs** [capitalone/Hygieia#730]
I copied the Jar file in to a folder on my machine and executed the below command in that folder and it went fine.

java -JAR subversion-collector.jar	

I have created the application.properties file.where should I keep this file and how do I execute/make use of the file?

**Comment by tabladrum** [comment]
you can keep the properties file anywhere and use this command line to run the collector:

``
java -jar subversion-collector.jar --spring.config.name=subversion --spring.config.location=<full path to properties file> 
``

**Comment by lchase** [comment]
(from Spring Boot docs) The application will load properties from **application.properties** files in the following locations and add them to the Spring Environment:

1. A **/config** sub-directory of the current directory.
2. The current directory
3. A classpath **/config** package
4. The classpath root

You can be explicit as mentioned by tabladrum, these are just the default behaviors.

**Comment by satishc1** [comment]
Closed.
