### ISSUE TITLE
Product Dashboard - Values not appearing for Dev, QA , Int and Perf

### ISSUE THREAD

**Issue by getting2vinod** [capitalone/Hygieia#731]
I have build a collector for octopus deploy in the same lines as urbancode. I was able to get the deploy dashboard up. After configuring pipeline dashboard is  with mappings to the corresponding environments in the project, when the product dasboard is created the Dev, QA , Int and Perf sections are empty. I have deployed the jenkins plugin and it is running as a post build step. I have configured Hygeia in  jenkins to publish build and artifact information. After the run both Deployment and artificat Hygiea gives an ID and 201 created message. Are there any documents to help get the product dashboard setup. The current github readme looks like incomplete in the configuration section.

**Comment by tabladrum** [comment]
Will be happy to get on a call. Before that there are few things to check.
1. Are you publishing artifact with a group name? 
2. When you deploy, does the group name match with the group name when you published?

You can send me your contact info via this email: tapabrata.pal@capitalone.com and I can schedule a call.

**Comment by getting2vinod** [comment]
Thanks for taking this forward. Answer to your question
1. Are you publishing artifact with a group name?
Yes, I am including a group name for my Artifact.
2. When you deploy, does the group name match with the group name when you published?
I could not find a group name defined for octopus deploy. Let me include the jsons that get stored for both jenkins plugin and octopus collector

jenkins:

{
    "_id": ObjectId("579bb3cfede639066d7f7a29"),
    "_class": "com.capitalone.dashboard.model.BinaryArtifact",
    "timestamp": NumberLong("1469821855625"),
    "artifactName": "api.jar",
    "canonicalName": "api.jar",
    "artifactGroupId": "Dev",
    "artifactVersion": "1.0",
    "buildInfo": {
        "_id": ObjectId("579bb39fede639066d7f7a28"),
        "collectorItemId": ObjectId("579a7aafede639056e6f155c"),
        "timestamp": NumberLong("1469821903614"),
        "number": "6",
        "buildUrl": "http://localhost:8081/job/dashboard1/6/",
        "startTime": NumberLong("1469821855626"),
        "endTime": NumberLong("1469821903587"),
        "duration": NumberLong(47961),
        "buildStatus": "Success",
        "sourceChangeSet": []
    }
}

Octopus Collector - .environment_components

{
    "_id": ObjectId("579bb434ede6390672d0cfdf"),
    "_class": "com.capitalone.dashboard.model.EnvironmentComponent",
    "collectorItemId": ObjectId("57848cc5ede6395ac8130734"),
    "environmentID": "Environments-1",
    "environmentName": "Dev",
    "environmentUrl": "http://13.92.132.210//app#/environments/Environments-1",
    "componentID": "Projects-3",
    "componentName": "BrowserFileTransfer",
    "componentVersion": "0.0.1",
    "deployed": false,
    "deployTime": NumberLong("1466839438345"),
    "asOfDate": NumberLong("1466839438345")
}

Octopus Collector - environment_status

{
    "_id": ObjectId("579bb741ede6390672d0d1b4"),
    "_class": "com.capitalone.dashboard.model.EnvironmentStatus",
    "collectorItemId": ObjectId("57848cc5ede6395ac8130734"),
    "componentID": "Projects-3",
    "environmentName": "Dev",
    "componentName": "BrowserFileTransfer",
    "resourceName": "DevMachine",
    "online": true
} {
    "_id": ObjectId("579bb741ede6390672d0d1b5"),
    "_class": "com.capitalone.dashboard.model.EnvironmentStatus",
    "collectorItemId": ObjectId("57848cc5ede6395ac8130734"),
    "componentID": "Projects-3",
    "environmentName": "Stage",
    "componentName": "BrowserFileTransfer",
    "resourceName": "StageServer",
    "online": false
}


How do we connect these two models, or rather, what would be the link

**Comment by nireeshT** [comment]
@getting2vinod  - update to latest code base. Reopen if still issue.

**Comment by bhuranideepak82** [comment]
@getting2vinod  Anyway we can get this octopus collector?

**Comment by subi-kp** [comment]
@getting2vinod  Is there any chance of getting octopus collector? Sharing would be appreciated. If you don't like sharing in public, could you please share code with me through email ganapathi.kp128@gmail.com. Thanks in advance.

**Comment by georgejinu** [comment]
Hello @getting2vinod & @subi-kp, can you please help in sharing the octopus collector.

**Comment by georgejinu** [comment]
@tabladrum - do you have any idea about the octopus collector, is that anyone already created it?
