### ISSUE TITLE
How to build a custom collector

### ISSUE THREAD

**Issue by instigardo** [capitalone/Hygieia#733]
Hi,
I am working on building a collector, with some new collector type.
can you tell me what all needs to be configured, and is there any sample project?

**Comment by c-sreenivasulareddy** [comment]
Please go through below one

https://github.com/capitalone/Hygieia/blob/master/core/create_collector.md

**Comment by tabladrum** [comment]
Thanks @c-sreenivasulareddy

**Comment by tabladrum** [comment]
Close this?

**Comment by instigardo** [comment]
Thanks  @c-sreenivasulareddy 
I want to know, how to call it via api and display it on UI.

**Comment by tabladrum** [comment]
Depends upon if it is a new model that don't exist yet. If you can tell me what collector you are creating, I can precisely tell you what to do.

**Comment by instigardo** [comment]
it is a custom db collector, I created a new collector type.

**Comment by tabladrum** [comment]
ok. So, once you have a model, and a collector to store documents of that model type into MongoDB, you need new api(s) to expose the data. See the api module and pick any api as an example. Then in the UI module, you would create a new data factory in here https://github.com/capitalone/Hygieia/tree/master/UI/src/app/dashboard/core/data-factories

Next you will create the UI widget and consume the JSON response etc etc.

**Comment by instigardo** [comment]
ok I am able to collect data and store it in mongo, the UI data factory and other elements I have made, I need to know how to use api to create rest service.

**Comment by tabladrum** [comment]
Create a new controller in api/rest. Create a new service in api/service. Optionally create any custom request class in api/request. See examples of existing apis in those.

**Comment by instigardo** [comment]
thanks I ll work on it. :)

**Comment by satishc1** [comment]
Closed.

**Comment by smsuresh** [comment]
@tabladrum I want to create for HP ALM & ServiceNow, can you please share the details..

**Comment by golokeshpatra45** [comment]
@smsuresh , 
Do you have any documentation of how to create a new collector, Even I have to make some custom collectors for HP.
Please help me out ASAP.

**Comment by smsuresh** [comment]
@golokeshpatra45  I dont've any doc, but just need to refer jenkins cucumber & sonar collector.
Im almost done for ALM. Which one you are trying to build!!?

**Comment by golokeshpatra45** [comment]
@smsuresh 
I havent got the details of the custom collector yet but I will getting the details very soon.
Besides, my tech lead has asked me to use the github collector and remove the references (Github References).

Can we talk on PM or skype ?
Its kindda urgent ..

**Comment by ashwini1212** [comment]
I want implement HP ALM collector, please help me. I am new to Hygieia

**Comment by gopimanga** [comment]
I want to create a collector for Confluence tool.Can  you provide steps to configure this?

**Comment by manjunath1006** [comment]
Please help on, How to create a customs collector and widget for x-ray and selenium test results, and please let me know the procedure to follow. Thanks in Advance.

**Comment by rvema** [comment]
@manjunath1006 Please follow the instructions as in https://github.com/capitalone/Hygieia/blob/master/core/create_collector.md

**Comment by wwei1896** [comment]
hi，
the url:https://github.com/capitalone/Hygieia/blob/master/core/create_collector.md
can not find now. can you provide the new url for it?
thanks

**Comment by kmkalai** [comment]
> Depends upon if it is a new model that don't exist yet. If you can tell me what collector you are creating, I can precisely tell you what to do.

Hi, I am creating custom collector for GoCD. pls give your suggestion for this

**Comment by rvema** [comment]
@kmkalai i am not sure about gocd I believe its a build/pipeline tool if that being the case you may take jenkins build collector as reference for building one.

**Comment by magixsource** [comment]
https://hygieia.github.io/Hygieia/create_collector.html

**Comment by venkateshreddy53** [comment]
I want to create a custom collector for axivion, can you please share the details steps and configuration to create.
