### ISSUE TITLE
Need help in customising environment names under pipeline tab

### ISSUE THREAD

**Issue by suyash090889** [capitalone/Hygieia#734]
Hi,

Currently, the environments are kind of hardcoded as DEV, QA, INT, PERF and PROD under Configure Delivery Pipeline as shown in the attached screenshot. With our client we have different QA environments , INT environments, DEV environments, etc. So I just wanted to check whether can we have that screen display our environment names specifically instead of DEV, QA, INT, PERF and PROD? Can anyone help me to get to that particular .java file or any other file where these are hardcoded and can be changed as per our client use? I have cloned the repository in my local and can make the changes if I can get some help her so any help is much appreciated.
![screenshot-1](https://cloud.githubusercontent.com/assets/20794546/17339671/87e4a890-590a-11e6-9b94-5013fc899694.png)

@tabladrum - Sir, if you can help please?

Thanks,
SUYASH GUPTA.

**Comment by tabladrum** [comment]
Let me take a look. hold please :-)

**Comment by tabladrum** [comment]
You should be able to change code in these to files to achieve the same. Do a PR when you are done :-)

https://github.com/capitalone/Hygieia/blob/master/UI/src/components/widgets/pipeline/view.js
https://github.com/capitalone/Hygieia/blob/master/UI/src/components/widgets/pipeline/view.html

**Comment by MarkRx** [comment]
Are you doing a generic change so that the screen will be customizable or are you doing a forked build and hard coding in what you need? Having those be more customizable is on my list of things to do but if someone else does it I won't have to. Unfortunately I think it will require a lot of code changes as the product dashboard view will also have to be changed.

**Comment by tabladrum** [comment]
We could simply put the "names" of the mapped environments on the screen along with the hardcoded stages.

**Comment by MarkRx** [comment]
#989

**Comment by MarkRx** [comment]
PR #1020

**Comment by mrpudn** [comment]
Closing - please continue on #989 and #1020
