### ISSUE TITLE
UI - After refresh the dashboard the message You are not authorized is shown

### ISSUE THREAD

**Issue by oshingc** [capitalone/Hygieia#735]
I was logged in then i configured a collector and after refresh when i wanted to configured another, after click the icon of configure this was shown.
Here i have 3 messages because i clicked three times.
![messages](https://cloud.githubusercontent.com/assets/3100819/17419879/2ed05022-5a65-11e6-9e2d-b1dc2e7a90e5.png)

**Comment by tabladrum** [comment]
Seems like a bug :-(
