### ISSUE TITLE
Jenkin's build graphical view

### ISSUE THREAD

**Issue by chethanbs** [capitalone/Hygieia#737]
I am able to get build number details in the dashboard but I dont see the graph.

Could some one help me?

**Comment by tabladrum** [comment]
How many builds to you have?

**Comment by chethanbs** [comment]
I have totally 8 builds

**Comment by tabladrum** [comment]
can you paste a screen shot?

**Comment by chethanbs** [comment]
It works with chrome and Firefox browsers.Only problem with IE.

**Comment by tabladrum** [comment]
hmm... IE seems to be a problem. Need to figure out what the issue is - unfortunately I dont have access to a Windows PC :-(

**Comment by satishc1** [comment]
Closed.
