### ISSUE TITLE
In which collections is the deployment related data stored ? 

### ISSUE THREAD

**Issue by raynaya** [capitalone/Hygieia#739]
I am using Hygiea jenkins publisher plugin. The build related data is getting reflected in the dropdown. But the deployment data is not coming up in the teams dropdown for configuring deployment widget. So I wanted to check if the data was coming in the db correctly or not but couldn't figure out where it is getting stored ?

**Comment by tabladrum** [comment]
environment_component and environment_stage.

**Comment by raynaya** [comment]
I dont see any such collections in my db.  Do we need to run the deployment collector to use the Hygieia-jenkins-plugin for pushing deployment details to Hygieia ?
