### ISSUE TITLE
How to run the UI without browser sync.

### ISSUE THREAD

**Issue by rohitstatic** [capitalone/Hygieia#740]
Hi,

Is there a way to run the UI without `browser-sync`. Currently I run the UI via the command `gulp serve` at the project root. The problem is that this keeps the UI in sync on different machines i.e an action performed by a user on a machine is reflected for other users in all machines. 

How do I stop that from happening? Is there some other way to run the UI.

**Comment by mrpudn** [comment]
You can try something like [`http-server`](https://www.npmjs.com/package/http-server):
```bash
npm install -g http-server
```

The only thing is that `browser-sync` is configured to proxy requests to the API, so you'll have to figure that out, i.e. this section in the `gulpfile.js`:
```js
    /*
     * Location of your backend server
     */
    var proxyTarget = config.api || 'http://localhost:8080';

    var proxy = httpProxy.createProxyServer({
        target: proxyTarget
    });

    proxy.on('error', function(error, req, res) {
        res.writeHead(500, {
            'Content-Type': 'text/plain'
        });

        console.error(chalk.red('[Proxy]'), error);
    });

    /*
     * The proxy middleware is an Express middleware added to BrowserSync to
     * handle backend request and proxy them to your backend.
     */
    function proxyMiddleware(req, res, next) {
        /*
         * Proxy the REST API.
         */
        if (/^\/api\/.*/.test(req.url)) {
            proxy.web(req, res);
        } else {
            next();
        }
    }

    browserSync.init({
        server: {
            baseDir: hygieia.dist,
            startPath: '/',
            middleware: [proxyMiddleware]
        }
    });
```

**Comment by amitmawkin** [comment]
to run it in production you can copy the files in the UI/dist folder  to serve via any HTTP server such as apache or nginx , additionally you need to make sure that http server is able to connect to your api server in case they are on different machines.

**Comment by amitmawkin** [comment]
closing this question. Feel free to open or comment if it does not answer your query

**Comment by atul1989** [comment]
while running the hygiei dashboard it is giving me error , after configure all the hygieia componant 
API/Collectors/UI/, And did not confogured the proxy setting which last step 

so once i am trying to connect it connected but not able to perform any thing , Please suggest something

[Proxy] { [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
