### ISSUE TITLE
About Deploy Widgets

### ISSUE THREAD

**Issue by MojinLi** [capitalone/Hygieia#744]
I am a novice . I want to know if I can insert data in MongoDB , so that I can see the data in the DEPLOY Wedget. My collection is like this : 
![1](https://cloud.githubusercontent.com/assets/20530629/17549644/ca16debc-5f23-11e6-9503-55d08eb8db61.PNG)

1.I want to know if my collection name is wrong?
2.I want to know what the JSON like?

Can you give me some example about Feature and Deploy Collection?

I am not good at English , Hope you can understand what I mean.

Thanks very much.

**Comment by tabladrum** [comment]
Yes. The deployment information is managed in two different collections - environment_component and environment_stage.

**Comment by MojinLi** [comment]
@tabladrum   You've solved my problem. Thank you very much.
