### ISSUE TITLE
Docker Compose script not set up to be plug-and-play (yet) - need to change `image` or `build` directives

### ISSUE THREAD

**Issue by hangtwenty** [capitalone/Hygieia#749]
I'm finding the `docker-compose` script is not plug-and-play on v2.0.0. Is that expected?

Specifically this is what I'm running into:

```
$ docker-compose up
Pulling mongodb (mongo:latest)...
latest: Pulling from library/mongo
5c68a10e9f3f: Pull complete
0110f95fa9c8: Pull complete
0cba4a42bc41: Pull complete
a6eafd7fba3f: Pull complete
703d9d7e0e21: Pull complete
7a4b36461321: Pull complete
5b3580f1488d: Pull complete
913554e7fcc9: Pull complete
2f9b4a452eb8: Pull complete
Digest: sha256:e599c71179c2bbe0eab56a7809d4a8d42ddcb625b32a7a665dc35bf5d3b0f7c4
Status: Downloaded newer image for mongo:latest
Creating mongodb
Pulling hygieia-api (hygieia-api:latest)...
Pulling repository docker.io/library/hygieia-api
ERROR: Error: image library/hygieia-api not found
```

I realized this is just a small issue probably, so I tried...

``` diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 78e2137..b739942 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -8,7 +8,7 @@ mongodb:
    - ./mongo:/data/db:rw
   volume_driver: local
 hygieia-api:
-  image: hygieia-api:latest
+  image: capitalone/hygieia-api:latest
   container_name: hygieia-api
   ports:
   - "8080:8080"
@@ -17,7 +17,7 @@ hygieia-api:
   links:
   - mongodb:mongo
 hygieia-ui:
-  image: hygieia-ui:latest
+  image: capitalone/hygieia-ui:latest
   container_name: hygieia-ui
   ports:
   - "8088:80"
@@ -26,7 +26,7 @@ hygieia-ui:
```

and so on. But applying this change to some of the collectors did not work. First, the `versionone` collector. I don't use that so I just commented-out. But then `jira` collector isn't working, and I'd like to use that image. It doesn't seem like `hygieia-jira-feature-collector` is on https://hub.docker.com/.

I can't build them all with `docker-compose build`, and that seems like reasonable behavior ...

```
$ docker-compose build
mongodb uses an image, skipping
hygieia-api uses an image, skipping
hygieia-ui uses an image, skipping
hygieia-jenkins-build-collector uses an image, skipping
hygieia-subversion-scm-collector uses an image, skipping
hygieia-udeploy-collector uses an image, skipping
hygieia-chat-ops-collector uses an image, skipping
hygieia-github-scm-collector uses an image, skipping
hygieia-stash-scm-collector uses an image, skipping
hygieia-jira-feature-collector uses an image, skipping
hygieia-jenkins-cucumber-test-collector uses an image, skipping
hygieia-sonar-codequality-collector uses an image, skipping
```

... since indeed the `docker-compose.yml` is set up to refer to images.

I'm just thinking, for plug-and-play demos, it would be nice to grab Hygieia and "just" run `docker-compose` :)

To that end, maybe if they all say `image:`, they should all be on DockerHub ... else, maybe they should say `build:` and refer to the Dockerfiles within this repository. Once consistent, it would be easy to add reference to this in the README or documentation, as a way for someone to get up and running quickly.

Thoughts? Happy to contribute to a solution once I know the consensus.

**Comment by hangtwenty** [comment]
```
Containers: 11
 Running: 3
 Paused: 0
 Stopped: 8
Images: 17
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 138
 Dirperm1 Supported: true
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.12-boot2docker
Operating System: Boot2Docker 1.11.2 (TCL 7.1); HEAD : a6645c3 - Wed Jun  1 22:59:51 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: default
ID: UAOQ:DT74:42PW:EQ2A:RAAK:DKNH:6AUY:AFQQ:CXTQ:KTE5:TB3Y:UEWA
Debug mode (server): true
 File Descriptors: 27
 Goroutines: 66
 System Time: 2016-08-11T00:30:48.850282621Z
 EventsListeners: 1
 Init SHA1: 
 Init Path: 
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

**Comment by tatemz** [comment]
I also try this and it seems to be invalid on each 2.x.x release :(

**Comment by matthewbeasley** [comment]
@hangtwenty @tatemz - we have recently released the first in a series of updates to our docker setup. I believe this update solves the issue you were facing here. Please pull the latest version of Hygieia, give it a shot and let me know how it goes. Feel free to continue the discussion here or open a new issue if you run into any problems.
