### ISSUE TITLE
Jenkins dashboard issue

### ISSUE THREAD

**Issue by vijayct2001** [capitalone/Hygieia#752]
Hi Team,

One of my jenkins job have 369 builds. Also mongo db shows build history(screenshot attached)
But in my hygieia dashboard shows only 2 builds 368 & 369 information(screenshot attached). why?

Could you please help me to fix this issue.

-Vijay

![image](https://cloud.githubusercontent.com/assets/11028464/17696418/c7ca5646-63cb-11e6-96ef-702157fa9e9c.png)

![image](https://cloud.githubusercontent.com/assets/11028464/17696444/f7806240-63cb-11e6-8d16-ccc8de7bbef0.png)

**Comment by tabladrum** [comment]
By looking at your build start times - I think they are more than 14 days old and the dashboard shows build only for past 14 days.

**Comment by vijayct2001** [comment]
Yeah. I agree you can close this tkt.
