### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by chethanbs** [capitalone/Hygieia#755]
I have configured the dashboard with Jenkins,SVN and Sonar Cube.

Jenkin's,SVN and sonar are hosted on remote servers and I am accessing the data through hygieia dashboard which is configured on different remote server.

**we will have any impact on Jenkin's,SVN and Sonar servers performance since we are accessing the data through dashboard which is hosted on remote server?**

**Comment by amitmawkin** [comment]
Not clear on the question, are you asking whether hygieia will have any impact on your devops tools?
Hygieia dashboard does not pull data directly from your devops tools such as jenkins etc , it used collectors which runs in the background and pull data from your devops tools and store it in mongodb, which Hygieia UI access via api. Please refer to the architecture on the youtube video in README.MD file.

**Comment by amitmawkin** [comment]
Closing this issue now
