### ISSUE TITLE
api/artifact endpoint - what is it used for?

### ISSUE THREAD

**Issue by charleswisniewski** [capitalone/Hygieia#758]
Hello,
I am curious as to what the api/artifact endpoint is used for?

Where can I view this information in the dashboard?

Thank you!
Charles

**Comment by tabladrum** [comment]
The artifactory end point is used by Jenkins plugin - it helps create the linkage between code commits to what artifact gets built to where it is deployed.

**Comment by satishc1** [comment]
Closed.
