### ISSUE TITLE
Cannot use github collector

### ISSUE THREAD

**Issue by kyosong** [capitalone/Hygieia#76]
i am having issue to bring up the github collector. (btw, my password has some special character like *.) Not sure this caused the issue. 

One more thing, does it support git/stash? 

![image](https://cloud.githubusercontent.com/assets/5901392/9265898/5f984c62-426c-11e5-9535-1d1914f9e19d.png)

**Comment by tabladrum** [comment]
Looks like the properties file missing OR most probably is not passed in the command line per the document. 

https://github.com/capitalone/Hygieia/blob/master/GitHubSourceCodeCollector/README.md
OR
http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-external-config-application-property-files

**Comment by kyosong** [comment]
Thanks @tabladrum . Yes, it is fixed via link 1. I didn't find it in the setup.md.
