### ISSUE TITLE
Issues in accessing same screen by 2 different users simultaneously

### ISSUE THREAD

**Issue by raynaya** [capitalone/Hygieia#764]
If 2 different users are using the same screen simultaneously then the sessions are getting overlapped, one users activities are getting reflected on the other users screen. For e.g. if both are on dashboard and one clicks on new dashboard then the new dashboard setup popup is visible to the other as well.

**Comment by amitmawkin** [comment]
It is a browsersync feature which allows you to test the app on multiple browsers simultaneously. For any production use please copy the content of dist folder to any standard http server www directory for serving the content

**Comment by amitmawkin** [comment]
feel free to open issue if that does not help you
