### ISSUE TITLE
Hygieia bitbucket-scm-collector & JIRA issue

### ISSUE THREAD

**Issue by dinukool** [capitalone/Hygieia#765]
Build and run the API Sucess
Build  UI Sucess

Run UI using Docker run below Error.
Error Response from Daemon: Could not get container for Hygieia-api

**Comment by dinukool** [comment]
@amitmawkin @tabladrum Looking for your help

**Comment by mrpudn** [comment]
Could you show the result of `docker images`? That information might be helpful for debugging this.

**Comment by dinukool** [comment]
Thanks UI is fine now via gulp serve. but still JIRA widget is not visible on Dashbord

**Comment by dinukool** [comment]
@mrpudn @amitmawkin @tabladrum 

My Bitbucket has uid and pwd how to add the credentials in property file for (bitbucket-scm-collector)
