### ISSUE TITLE
is it possible to use CNAME (alias) for <host:port> for the UI via gulp.

### ISSUE THREAD

**Issue by rohitstatic** [capitalone/Hygieia#766]
Hi,

Is there a way i can hide the port from url and use cname (alias) instead. I could possibly do it by serving the UI via apache but am a bit skeptical lest it breaks any functionality

For instance, the UI comes up at `http://172.14.7.80:3000` . Is it possible to access it via `http://mycname.com`

What changes needs to be done in order to accomplish that.

Thanks.

**Comment by mrpudn** [comment]
Is this for local purposes or for hosting the dashboard for others?

If local, you can edit your hosts file to map a hostname (ie. `http://mycname.com`) to an IP address and port (ie. `http://172.14.7.80:3000`).

If you're hosting the dashboard for others, you'll need to set this stuff up via your hosting provider.

Hope that helps!

**Comment by rohitstatic** [comment]
Thanks, that helps.
