### ISSUE TITLE
Hygieia with Jenkins Pipeline Project

### ISSUE THREAD

**Issue by szabbas** [capitalone/Hygieia#767]
Need some help
Could you please let me know if we can configure Hygieia with Jenkins pipeline project
When I install the plugin I can see the option in 'POST Build Action' for the freestyle/maven project.So I can configure from there
But unable to do the same if working as a pipeline projects.
Do we have any option to integrate Hygieia and if 'yes' do we any document or video to work on it? And if 'No' then do we have plan to integrate the same for pipeline project?

**Comment by tabladrum** [comment]
We do have a backlog item to make this work for pipeline project. We are going to work on this within the next few weeks.

**Comment by timeapen** [comment]
Great!  We are looking forward to this as well.

**Comment by RevaSawant** [comment]
@tabladrum , can we have updates on this please?Thank you.

**Comment by vikasm47** [comment]
@tabladrum @amitmawkin : any updates on above, we also have similar requirement ? Thanks

**Comment by anurag111527** [comment]
Hi, we have been working on POST build action and we tried doing with groovy.
we used a step method:
step ([$class: 'hygieia', publishBuildData:true])
and the build failed returning the below erroe mesage
"no known implementation of interface jenkins.tasks.SimpleBuildStep is named hygieia"
>>need lead.. TIA

**Comment by tabladrum** [comment]
It does not have pipeline support yet. Work in Progress. Lack of enough documentation makes things hard.

**Comment by timeapen** [comment]
@tabladrum, any update?

**Comment by tabladrum** [comment]
Halfway through.

**Comment by swathireddy2808** [comment]
Hi,
have you started working on pipelines.?

If yes please , help us with the issue
we have been working on POST build action and we tried doing with groovy.
we used a step method:
step ([$class: 'hygieia', publishBuildData:true])
and the build failed returning the below error message
"no known implementation of interface jenkins.tasks.SimpleBuildStep is named hygieia"

**Comment by szabbas** [comment]
Any update on this...???

**Comment by satishc1** [comment]
@szabbas Should work with the latest codebase. Download and try it out.

**Comment by luweiyulin** [comment]
@szabbas Hello,I met the same problem with you,I updated code is 201702.
 Did you solve the problem when you update all the code?
Can you tell me your specific version of the JDK?
