### ISSUE TITLE
Issue in connecting to Github

### ISSUE THREAD

**Issue by Sriharsha1693** [capitalone/Hygieia#768]
ERROR c.c.d.collector.DefaultGitHubClient - I/O error on GET request for "https://api.github.com/repos/capitalone/Hygieia/commits?sha=master&since=2016-08-24T18:30Z":This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server; nested exception is java.net.UnknownHostException: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server:https://api.github.com/repos/capitalone/Hygieia/commits?sha=master&since=2016-08-24T18:30Z

When I try to manually access the service using the same URL from a browser, am able to get the response

**Comment by Sriharsha1693** [comment]
Below is the application properties file

#Database Name 
database=dashboard

#Database HostName - default is localhost
dbhost=127.0.0.1

#Database Port - default is 27017
dbport=27017

#Database Username - default is blank
dbusername=db

#Database Password - default is blank
dbpassword=dbpass

#Collector schedule (required)
github.cron=0 0/5 * * * *

github.host=github.com

#Maximum number of days to go back in time when fetching commits
github.commitThresholdDays=15

**Comment by Sriharsha1693** [comment]
Repo Count              1        0s
New Commits           0        0s
Finished                               0s

Is the result it is showing

**Comment by tabladrum** [comment]
Are you behind a proxy?

**Comment by Sriharsha1693** [comment]
Yes tabladrum.

Ca you please let me know, if I have to set my proxy settings in any configuration

**Comment by tabladrum** [comment]
@amitmawkin might have solved this in the past. Not sure about the details. But from the collector code perspective, it does not support proxy at this point. Please open an issue so that we can keep track.

**Comment by Sriharsha1693** [comment]
@amitmawkin can you please let us know, how it can be solved

**Comment by amitmawkin** [comment]
@Sriharsha1693  use -D flags to pass your proxy information when you start the github collector

**Comment by Saravanavel04** [comment]
@amitmawkin will you give more details to resolve this issue.?

**Comment by huylv1** [comment]
you can set proxy for OkHttp like this:
Proxy proxyTest = new Proxy(Proxy.Type.HTTP,new InetSocketAddress("proxy", proxyPort));
OkHttpClient.Builder builder = new OkHttpClient.Builder().proxy(proxyTest);
  OkHttpClient client = builder.build();

**Comment by nitin1706** [comment]
Refer: https://gist.github.com/evantoli/f8c23a37eb3558ab8765
https://stackoverflow.com/questions/783811/getting-git-to-work-with-a-proxy-server
