### ISSUE TITLE
Question, were the QClasses are generated?

### ISSUE THREAD

**Issue by oshingc** [capitalone/Hygieia#769]
This is just a question, hope you can help me. :D

**Comment by tabladrum** [comment]
You can use maven to generate this classes from the core module - modern IDEs will allow you to do this from a "right click"

**Comment by AndrewOrr** [comment]
I found this and am hoping that we can get a more in depth answer. How does mvn know to generate this class?

**Comment by tabladrum** [comment]
It's Java 6 APT: See this snippet in core's pom.xml:
            <plugin>
                <groupId>com.mysema.maven</groupId>
                <artifactId>apt-maven-plugin</artifactId>
                <version>1.1.3</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>process</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>target/generated-sources/java</outputDirectory>
                            <processor>org.springframework.data.mongodb.repository.support.MongoAnnotationProcessor
                            </processor>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

**Comment by AndrewOrr** [comment]
Thanks for getting back to me so quickly. Will mysema look for some type of annotation to know when to build commit or any of the other q classes?

**Comment by AndrewOrr** [comment]
It seems that querydsl is looking for an @entity to indicate which q classes to generate. We would like to add a new q class but can't figure out how to generate it.

**Comment by satishc1** [comment]
Closed.
