### ISSUE TITLE
Build issue - Master branch

### ISSUE THREAD

**Issue by bjayagop** [capitalone/Hygieia#770]
Hi,

I have attempted to build the master branch of Hygieia. Maven build fails with below error message,

Downloading: http://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/1.2.5.RELEASE/spring-boot-starter-parent-1.2.5.RELEASE.pom
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.capitalone.dashboard:Hygieia:2.0.2-SNAPSHOT (C:\Users\jay\git\Hygieia\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:1.2.5.RELEASE from/to central (http://repo.maven.apache.org/maven2): Connection to http://10.254.96.30:83 refused and 'parent.relativePath' points at wrong local POM @ line 10, column 10: Connection timed out: connect -> [Help 2]

Please suggest to resolve.

**Comment by satishc1** [comment]
Appears to be a network proxy issue. If your intranet is blocking certain sites, try running the build on an external network initially so you can get all the maven downloads.

**Comment by bjayagop** [comment]
Thanks for suggestion. There was some proxy entries which I have commented to resolve the issue related to proxy.

All the packages were built sucessfully except UI. 

Getting [ERROR] npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\jay\AppData\Roaming\npm-cache\lodash.isobject\2.4.1\package\package.json.210157745' -> 'C:\Users\jay\AppData\Roaming\npm-cache\lodash.isobject\2.4.1\package\pack

See full error output below.

Done. Phantomjs binary available at C:\Users\jay\git\Hygieia\UI\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\lib\phantom\phantomjs.exe
[ERROR] npm WARN optional dep failed, continuing imagemin-jpegtran@4.3.2
[ERROR] npm WARN optional dep failed, continuing imagemin-optipng@4.3.0
[ERROR] npm WARN optional dep failed, continuing imagemin-gifsicle@4.2.0
[ERROR] npm ERR! Windows_NT 10.0.10586
[ERROR] npm ERR! argv "C:\\Users\\jay\\git\\Hygieia\\UI\\node\\node.exe" "C:\\Users\\jay\\git\\Hygieia\\UI\\node\\node_modules\\npm\\bin\\npm-cli.js" "install"
[ERROR] npm ERR! node v5.4.1
[ERROR] npm ERR! npm  v2.14.15
[ERROR] npm ERR! path C:\Users\jay\AppData\Roaming\npm-cache\lodash.isobject\2.4.1\package\package.json.210157745
[ERROR] npm ERR! code EPERM
[ERROR] npm ERR! errno -4048
[ERROR] npm ERR! syscall rename
[ERROR] 
[ERROR] npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\jay\AppData\Roaming\npm-cache\lodash.isobject\2.4.1\package\package.json.210157745' -> 'C:\Users\jay\AppData\Roaming\npm-cache\lodash.isobject\2.4.1\package\package.json'
[ERROR] npm ERR!     at Error (native)
[ERROR] npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\Users\jay\AppData\Roaming\npm-cache\lodash.isobject\2.4.1\package\package.json.210157745' -> 'C:\Users\jay\AppData\Roaming\npm-cache\lodash.isobject\2.4.1\package\package.json']
[ERROR] npm ERR!   errno: -4048,
[ERROR] npm ERR!   code: 'EPERM',
[ERROR] npm ERR!   syscall: 'rename',
[ERROR] npm ERR!   path: 'C:\\Users\\jay\\AppData\\Roaming\\npm-cache\\lodash.isobject\\2.4.1\\package\\package.json.210157745',
[ERROR] npm ERR!   dest: 'C:\\Users\\jay\\AppData\\Roaming\\npm-cache\\lodash.isobject\\2.4.1\\package\\package.json',
[ERROR] npm ERR!   parent: 'lodash.keys' }
[ERROR] npm ERR! 
[ERROR] npm ERR! Please try running this command again as root/Administrator.
[ERROR] 
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     C:\Users\jay\git\Hygieia\UI\npm-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] com.capitalone.dashboard:Hygieia ................... SUCCESS [  8.046 s]
[INFO] com.capitalone.dashboard:core ...................... SUCCESS [02:36 min]
[INFO] com.capitalone.dashboard:api ....................... SUCCESS [ 44.326 s]
[INFO] com.capitalone.dashboard:jenkins-build-collector ... SUCCESS [ 17.762 s]
[INFO] com.capitalone.dashboard:sonar-codequality-collector SUCCESS [  4.367 s]
[INFO] com.capitalone.dashboard:subversion-collector ...... SUCCESS [  7.476 s]
[INFO] com.capitalone.dashboard:github-scm-collector ...... SUCCESS [  7.247 s]
[INFO] com.capitalone.dashboard:bitbucket-scm-collector ... SUCCESS [ 13.393 s]
[INFO] com.capitalone.dashboard:versionone-feature-collector SUCCESS [ 20.016 s]
[INFO] com.capitalone.dashboard:udeploy-deployment-collector SUCCESS [ 10.810 s]
[INFO] com.capitalone.dashboard:xldeploy-deployment-collector SUCCESS [ 10.933 s]
[INFO] com.capitalone.dashboard:jira-feature-collector .... SUCCESS [ 38.360 s]
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SUCCESS [ 10.992 s]
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SUCCESS [  4.006 s]
[INFO] com.capitalone.dashboard:aws-cloud-collector ....... SUCCESS [  9.696 s]
[INFO] com.capitalone.dashboard:UI ........................ FAILURE [14:12 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20:21 min
[INFO] Finished at: 2016-08-25T22:46:50+05:30
[INFO] Final Memory: 72M/403M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.29:npm (npm install) on project UI: Failed to run task: 'npm install' failed. (error code -4048) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :UI

Any suggestion to resolve ?

**Comment by tabladrum** [comment]
[ERROR] npm ERR! Please try running this command again as root/Administrator.
[ERROR] 

Looks like some write permission error to some directory on Windows?

[ERROR] npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\jay\AppData\Roaming\npm-cache\lodash.isobject\2.4.1\package\package.json.210157745' -> 'C:\Users\jay\AppData\Roaming\npm-cache\lodash.isobject\2.4.1\package\package.json'

**Comment by satishc1** [comment]
@bjayagop On windows you could click Start->Run. Type in cmd and right click on the command prompt and Run as administrator. Then run the maven commands in this command prompt. If it doesn't work, please reopen.

**Comment by bjayagop** [comment]
Changing proxy and import of ssl Certs from  maven & atlassian repos  in
jvm resolved all build issues.

**Comment by kirhie** [comment]
Me too getting the npm install error..not able to build UI. @bjayagop : Can you please let me know what steps you followed to resolve the issue. New to hygieia and maven.

Thanks in advance.
