### ISSUE TITLE
Can someone explain the stats that are displayed on pipleine 2.0 dashboard.

### ISSUE THREAD

**Issue by raynaya** [capitalone/Hygieia#771]
Like I understand that the pipeline is trying to show code progression but apart from that I see a lot of other stats like the commits marked in green and red what do they signify and then we have a time shown like days hours mins and a average that comes up.

**Comment by Megha849** [comment]
@raynaya Please refer to the following image for details about the stats in the pipeline:
https://github.com/capitalone/Hygieia/blob/gh-pages/media/images/h2-commit-stage.png
