### ISSUE TITLE
view.js 'Use Strict' Does not load Jira widget in Safari

### ISSUE THREAD

**Issue by desertblade** [capitalone/Hygieia#773]
In UI view.js 'Use Strict' is defined in javascript.  This causes an error on the Jira plugin so it does not render.

Error in console:
SyntaxError: Strict mode does not allow function declarations in a lexically nested statement.     View.js:243

In function isInArray. 

Simple fix was remove 'Use Strict' from view.js, which is really just masking the issue.

**Comment by tabladrum** [comment]
Can you do a PR? Thanks

**Comment by desertblade** [comment]
Do you want me to remove Use Strict or rewrite the function to by strict complaint?

**Comment by satishc1** [comment]
@desertblade Closed.
