### ISSUE TITLE
do we have anthillpro collector available? is anyone working on it by any chance?

### ISSUE THREAD

**Issue by mgatgit** [capitalone/Hygieia#774]

**Comment by mgatgit** [comment]
@amitmawkin @tabladrum

**Comment by tabladrum** [comment]
Not that we know of.

**Comment by mgatgit** [comment]
Ok can you please share inputs on how to build custom collectors

**Comment by tabladrum** [comment]
See here: https://github.com/capitalone/Hygieia/blob/master/core/create_collector.md
Let me know how it goes.

**Comment by tabladrum** [comment]
I don't think we are going to create anthill pro collector as the product may be replaced by urbancode product line.
