### ISSUE TITLE
Commit details not coming into Prod

### ISSUE THREAD

**Issue by raynaya** [capitalone/Hygieia#778]
I have a bamboo collector which I have written. Also for some applications I am using the  Hygieia Jenkins plugin to report the build details. The build details are getting reported correctly in the application dashboard for both the different type of collectors. But in the pipeline view the build details pushed using the Jenkins plugin is missing. All other stats are coming correctly. 

Note : I haven't configured Sonar for these applications yet. ( Don't think it should cause this issue)

I have tried the Jenkins collector and the result is the same. Any idea what can cause this issue and where to start debugging from ?

**Comment by tabladrum** [comment]
Do you have the Code Repo configured>

**Comment by raynaya** [comment]
Thanks! I got the problem. Data issue .. But I have a bunch of questions regarding the pipeline based on my understandings -

1. If I am pushing the Artifact information using the Jenkins deployment plugin after the build is complete and incidentally that build fails. Then during the next build the change-sets of the previous failed build doesnt get reflected in the artifact information. Just to elaborate if a, b commits where in the first build and the build fails. Next time I build again and this time commit - c also comes. And an artifact is generated . The data that is published in hygieia about the artifact only includes c and not a,b. But the build has information about a and b as a result in the pipeline a and b never moves forward.

2. My build server doesn't have very old builds. But my source code repository has information some 5 months back. So in the pipeline view I am having code as old as 129 Days old which hasn't moved to build. Shouldn't we ignore so old commits data ?

3. Is there any minimum no of commits that we need before we show the stage in pipeline. For a certain pipeline I have mapped Prod and also I can see Artifacts and commits in Prod in the pipelines collection. But the Prod stage is empty. Isn't showing any data.

**Comment by raynaya** [comment]
@tabladrum Any thoughts on the above.

**Comment by tabladrum** [comment]
Can you see if your issue is fixed with this? https://github.com/capitalone/Hygieia/pull/789

**Comment by satishc1** [comment]
@raynaya Closed. Reopen if still an issue.
