### ISSUE TITLE
Hygieia publisher results not able to view

### ISSUE THREAD

**Issue by Saravanavel04** [capitalone/Hygieia#779]
Dear Team,

I'm using Hygieia publisher in my Jenkins job.

Once the build is done, I'm not able to see the build results in Hygieia.

Please help here.

Thanks in advance.

Thanks,
Saravana

**Comment by tabladrum** [comment]
Please check a few things:
1. In your jenkins build console log you see something like this: "Hygieia: Published Build Complete Data. Response Code: 201. Response Value= 57b5cce4b9ee71229d93e0a4"
2. You have the result in the "builds" collection as well as the job in "collector_item" collection.

**Comment by Saravanavel04** [comment]
Hi Tabladrum,

I’m using Jenkins 2.6 and there is no log like “Hygieia: Published Build complete data”.

Is it work with Jenkins 2.6.?

Also I’m not able to those values in the builds collection.

Please help here.

Thanks,
Saravana

**Comment by tabladrum** [comment]
I just now tested with Jenkins 2.7.2 and it works. Can you paste your job config screen where you set Hygieia? and also, see if you have any error in Jenkins System log and Hygieia API.

**Comment by Saravanavel04** [comment]
Dear Tabladrum,

Thanks for the response.

Now I’m facing issues in the Jira and Udeploy collectors.

I have attached the logs of the same.

Please help here in resolving.

Thanks and regards,
Saravanakumar Velusamy
Infosys Tools Group<http://toolsgroup/>
M: +91 8123996501
www.infosys.com<http://www.infosys.com/>
[cid:image003.png@01D1DE98.28936A80]<http://idp/>

**Comment by satishc1** [comment]
@Saravanavel04 Closed. Reopen it still an issue.
