### ISSUE TITLE
Passwords stored in clear

### ISSUE THREAD

**Issue by aconrad** [capitalone/Hygieia#78]
https://crackstation.net/hashing-security.htm

**Comment by tabladrum** [comment]
The only place we have a password concept is the dashboard owner. Our initial version did not even have that - we believe all the information that are displayed on the dashboard should be transparent to everyone. The problem that we ran into was that PersonA could modify PersonB's dashboard. So, we introduced the owner concept just to make sure that does not happen.

Having said that, I already pushed some new API's and Encryption classes and am working on allowing real passwords (such as jenkins, jira passwords etc) to be stored encrypted.

**Comment by msabramo** [comment]
Which passwords are we talking about and where are they stored?

**Comment by tabladrum** [comment]
Not storing any yet other than "dashboard owner".

**Comment by jdamick** [comment]
closing with pull
