### ISSUE TITLE
Jira widget in dashboard

### ISSUE THREAD

**Issue by vikasm47** [capitalone/Hygieia#781]
Hi, I am unable to find Jira widget in Hygieia dashboard, I have created application.properties file inside target folder and executed the command "java -jar jira-feature-collector.jar" and logs are also showing right data, but unable to configure it into dashboard. Can anyone help me how to see this in dashboard.
![dashboard](https://cloud.githubusercontent.com/assets/21235049/18123287/dd20b772-6f8a-11e6-99a2-692c90a4ffea.PNG)

**Comment by kh77** [comment]
It is CapOne template LoL

**Comment by vikasm47** [comment]
@kh77 : can you please help me in configuring Jira widget in above dashboard, I am unable to find any options here

**Comment by vikasm47** [comment]
@amitmawkin @tabladrum

**Comment by kh77** [comment]
skypeid: kazimhussain77

**Comment by tabladrum** [comment]
When you create a new dashboard, select the "CapOne" template. 
You will have option to set up "Feature" widget.
