### ISSUE TITLE
Actually it's not issue...it's new feature request you can say

### ISSUE THREAD

**Issue by ShrikrishnaSable** [capitalone/Hygieia#785]
As you are using most of the open source tools in this hygieia Dashboard, Why don't you integrate open source tools like rundeck for deployment?
As if you provide all open source tool integrations from build to deploy status management then it will be very helpful for startups. or if you can provide any end point(plug) where contributor able to write his custom integration for the tool he require. that will be great!!!

Still It's really a very good effort, we appreciate it...

Thanks!!!!

**Comment by tabladrum** [comment]
It will be good to integrate RunDeck too. Currently for deployment we integrated with a commercial tool and also Jenkins. There are API's exposed too to publish deployment data from any tool to Hygieia - I know of one company using the APIs from their custom built deployment tool.

**Comment by raynaya** [comment]
@tabladrum  : do we have the api's endpoints documented anywhere ?

**Comment by ShrikrishnaSable** [comment]
Wow, that's great but If you can shade little light on integration end points through docs then that will be really helpful..
Thanks!!!!

**Comment by amitmawkin** [comment]
Swagger is already integrated, you can see all the endpoints.

**Comment by mrpudn** [comment]
You should be able to get to the swagger UI here:
[http://localhost:8080/api/swagger/index.html](http://localhost:8080/api/swagger/index.html)

**Comment by mrpudn** [comment]
We can keep this issue open for discussion, but I'd like to request that you rename it with a more descriptive name for tracking purposes :)

Thanks!

**Comment by jmcshane** [comment]
Thanks @mrpudn, see issue #1008.

**Comment by mrpudn** [comment]
Cool, I'll close this one and we'll continue on #1008 - thanks!
