### ISSUE TITLE
[ERROR] npm WARN package.json zeppelin-web@0.0.0 No license field.

### ISSUE THREAD

**Issue by sanmanu** [capitalone/Hygieia#788]
Hi All,

I am using ubuntu 16.01 with hadoop 2.6 , spark 2.0 and scala 2.11.4
When installing zeppelin 0.6.1 I am getting the above error for zeppelin web gui
below is the maven install error 
Running 'npm install --color=false' in /home/ds/ds/zeppelin-0.6.1/zeppelin-web
[ERROR] npm WARN package.json zeppelin-web@0.0.0 No license field.
Failed to run task: 'npm install --color=false' failed. (error code 1) -> [Help 1]

**Comment by amitmawkin** [comment]
Does this have to do anything with Hygieia

**Comment by amitmawkin** [comment]
Not related to Hygieia
