### ISSUE TITLE
Able to access dashboards with the links without logging in.

### ISSUE THREAD

**Issue by raynaya** [capitalone/Hygieia#790]
Is that a bug or as per design ? For Team dashboard it looks fine as we are not able to edit the dashboard without logging in. But for Product dashboard we are able to edit/add/delete with just the link and not logging in.

**Comment by amitmawkin** [comment]
its intended, so anybody can share dashboard with anybody without a login

**Comment by amitmawkin** [comment]
I will close this issue

**Comment by raynaya** [comment]
@amitmawkin : thanks for the clarification. But shouldn't we restrict editing the product dashboard ?

**Comment by amitmawkin** [comment]
you cannot edit..., most probably you are logged in

**Comment by amitmawkin** [comment]
or try editing

**Comment by raynaya** [comment]
I am able to .. with the link to the "Product/Pipeline" dashboard. not the team one.

**Comment by amitmawkin** [comment]
Let me investigate.

**Comment by asg247** [comment]
@raynaya I don't see this issue. Can you please confirm if you are still able to edit Product dashboard without logging in.

**Comment by asg247** [comment]
Closing this issue please re-open with screen shots if it still exists.
