### ISSUE TITLE
Default docker values out-of-sync

### ISSUE THREAD

**Issue by MarkRx** [capitalone/Hygieia#796]
PR #787 renamed the database to 'dashboarddb' from 'dashboard'. This has exposed an issue with the properties generators for docker that use 'database' instead of 'dbname' as the database property name. The property generator files need to be updated to allow docker-compose to set the name of the database. Their default values should also be updated.

MongoConfig uses 
`dbname:dashboarddb`
properties-builders (except for api) use something like this:
`database=${HYGIEIA_API_ENV_SPRING_DATA_MONGODB_DATABASE:-dashboard}`

Tagging @amitmawkin

**Comment by amitmawkin** [comment]
The  name got changed in SETUP.md for the documentation part. I don't think that should affect the docker stuff anyways, the sample property file in the mark down is for folks who are not using docker.

**Comment by MarkRx** [comment]
It does. MongoConfig defaults to 'dashboarddb'. There is no way to change that with docker-compose because it only has properties to set 'database'. Hence there is no way to make hygieia use an existing database named 'dashboard'

**Comment by amitmawkin** [comment]
Oh ok I see what you are saying, will make the change back to revert in the default properties @satishc1 @MarkRx @tabladrum

**Comment by amitmawkin** [comment]
@MarkRx try the latest commit and let me know if issue still exists

**Comment by MarkRx** [comment]
That fixes it but now the documentation is out of sync as it still refers to 'dashboarddb' along with 'dashboarduser' and 'dbpassword'

**Comment by matthewbeasley** [comment]
@MarkRx - we have recently released the first in a series of updates to our docker setup. This update includes updated the db setup to reflect the db user / pass that is listed in the docs.
