### ISSUE TITLE
NPE in jenkins collector

### ISSUE THREAD

**Issue by MarkRx** [capitalone/Hygieia#799]
JSONArray remoteUrls = (JSONArray) ((JSONObject) action).get("remoteUrls");
                for (Object urlObj : remoteUrls) {

remoteUrls isn't always specified in an action. It depends on the actions class.

> 2016-09-08 08:38:11,714 ERROR c.c.d.collector.DefaultHudsonClient - Unknown error in getting build details. URL=http://myurl/job/myjob/166/
> java.lang.NullPointerException: null
>         at com.capitalone.dashboard.collector.DefaultHudsonClient.getGitRepoBranch(DefaultHudsonClient.java:277) ~[jenkins-build-collector-2.0.2-SNAPSHOT.jar!/:2.0.2-SNAPSHOT]
>         at com.capitalone.dashboard.collector.DefaultHudsonClient.addChangeSets(DefaultHudsonClient.java:245) ~[jenkins-build-collector-2.0.2-SNAPSHOT.jar!/:2.0.2-SNAPSHOT]
>         at com.capitalone.dashboard.collector.DefaultHudsonClient.getBuildDetails(DefaultHudsonClient.java:183) ~[jenkins-build-collector-2.0.2-SNAPSHOT.jar!/:2.0.2-SNAPSHOT]
>         at com.capitalone.dashboard.collector.HudsonCollectorTask.addNewBuilds(HudsonCollectorTask.java:193) [jenkins-build-collector-2.0.2-SNAPSHOT.jar!/:2.0.2-SNAPSHOT]
>         at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:95) [jenkins-build-collector-2.0.2-SNAPSHOT.jar!/:2.0.2-SNAPSHOT]
>         at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:32) [jenkins-build-collector-2.0.2-SNAPSHOT.jar!/:2.0.2-SNAPSHOT]

Example rest response:
```
{
	"_class": "hudson.model.FreeStyleBuild",
	"actions": [
		{
			"_class": "hudson.model.CauseAction"
		},
		{
			
		},
		{
			"_class": "hudson.plugins.git.util.BuildData",
			"lastBuiltRevision": {
				"SHA1": "e7271e9c39688e03801371eb7f328ca66f3fbd48",
				"branch": [
					{
						"SHA1": "e7271e9c39688e03801371eb7f328ca66f3fbd48",
						"name": "refs/remotes/origin/master"
					}
				]
			},
			"remoteUrls": [
				"https://username@myurl.com/scm/~username/project.git"
			]
		},
		{
			"_class": "hudson.plugins.git.GitTagAction"
		},
		{
			
		},
		{
			
		},
		{
			
		},
		{
			
		},
		{
			"_class": "org.jenkinsci.plugins.buildenvironment.actions.BuildEnvironmentBuildAction"
		}
	],
	"building": false,
	"duration": 91711,
	"number": 188,
	"result": "SUCCESS",
	"timestamp": 1471870832800,
	"url": "http://myurl:8080/job/myjob/188/",
	"changeSet": {
		"_class": "hudson.plugins.git.GitChangeSetList",
		"items": [
			{
				"_class": "hudson.plugins.git.GitChangeSet",
				"timestamp": 1471870814000,
				"author": {
					"fullName": "Doe, John"
				},
				"date": "2016-08-22 09:00:14 -0400",
				"id": "e7271e9c39688e03801371eb7f328ca66f3fbd48",
				"msg": "my message",
				"paths": [
					{
						"file": "a changed file"
					},
					{
						"file": "another changed file"
					}
				]
			}
		],
		"kind": "git"
	},
	"culprits": [
		{
			"fullName": "Doe, John"
		}
	]
}
```

Tagging @tabladrum 
PR #789

**Comment by tabladrum** [comment]
https://github.com/capitalone/Hygieia/pull/800

**Comment by MarkRx** [comment]
Fixed
