### ISSUE TITLE
Jenkins job listing but build details not displayed in the build section

### ISSUE THREAD

**Issue by elangesk** [capitalone/Hygieia#802]
**Just changed color of build section after selected Jenkins job name** 
![jenkins](https://cloud.githubusercontent.com/assets/17324051/18354619/4020de40-75b4-11e6-927d-c8d319d7b0db.PNG)

but Jenkins job are running properly as below :

![jenkins_job](https://cloud.githubusercontent.com/assets/17324051/18354816/fceebcae-75b4-11e6-89bc-ff8ef3e0b133.PNG)

Need your support to move froward. Any thing want to be taken care..

**Comment by elangesk** [comment]
Also I debug build widget and able to find response data objects, but build dash board not render the data as excepted. Please find the below image : 

![build_widget_debug](https://cloud.githubusercontent.com/assets/17324051/18392295/48f46aa2-767f-11e6-8c03-62fa5e34d476.PNG)

Kindly need your inputs to overcome this blocker.

**Comment by mrpudn** [comment]
Hmm, judging by your research, this seems to be a UI bug - I'm out of town for a few days, but I'll look into this when I get back, unless it gets resolved before then.

**Comment by elangesk** [comment]
I solved the issue execute by mvn clean install and cleaned mongo DB schema.
