### ISSUE TITLE
System requirment

### ISSUE THREAD

**Issue by eldojoseph** [capitalone/Hygieia#805]
Can someone provide me minimal system requirements to run Hygieia with all collectors running?

**Comment by MarkRx** [comment]
You might want at a bare minimum 4G of ram. I would suggest 6-8Gb for a real instance. Initially my vagrant vm worked with 2 but it wasn't enough and it caused docker containers to crash. A decent cpu would be good as you will have a lot of containers running.

**Comment by eldojoseph** [comment]
Thank you Mark
