### ISSUE TITLE
Quieter builds

### ISSUE THREAD

**Issue by mrpudn** [capitalone/Hygieia#807]
When you do a `mvn clean install`, there are TONS of info-level and debug-level messages. Most of the time, you're really only ever looking for warn-level and error-level messages. This makes it hard to tell if anything out of the ordinary happened during a build (and it's a heck of a lot of text to try and parse through).

Even running maven in quiet-mode (i.e. `mvn clean install -q`) doesn't work completely - the source of the problem seems to stem from each application's logging configuration. Ideally, you'd give maven a command-line arg to increase the verbosity of a build (maybe only for Travis builds and if you're actually interested in info/error-level messages for something). By default, the amount of messages displayed during a build would be kept to an absolute minimum.

Thoughts?

I think I've gotten this working on a previous project just by changing configurations for logback, etc., so I could give it a shot if you guys think it's a good idea.

**Comment by Sbrenthughes** [comment]
If you want to make a PR with this ability we would be glad to take a look.
