### ISSUE TITLE
Hygieia Jenkins plugin

### ISSUE THREAD

**Issue by anurag111527** [capitalone/Hygieia#808]
Hi,
My Hygieia widgets works fine except Build widget. The widget shows all my projects in the drop down list, but it sdoes not show the builds.
![capture01](https://cloud.githubusercontent.com/assets/20580134/18438121/06cf6ac2-78ce-11e6-8f90-f29fa7a96232.PNG)
![capture02](https://cloud.githubusercontent.com/assets/20580134/18438120/06ab91b0-78ce-11e6-853a-7ffdae2bfe1c.PNG)

Thanks

**Comment by tabladrum** [comment]
After the initial config (i.e., selecting the job).. wait for a few minutes (depending upon the collector cron setting) for the Collector to catch up.

**Comment by anurag111527** [comment]
thanks for replying. I configured for every 4min and its been more than 2 days now.
![image](https://cloud.githubusercontent.com/assets/20580134/18439623/1d164f20-78d4-11e6-8585-fb2dba71faf5.png)

Thanks

**Comment by satishc1** [comment]
@anurag111527 Set the log level to DEBUG for your collector. Is it connecting to the right jenkins server ? Are there any errors in the log ? Reopen if still an issue.
