### ISSUE TITLE
hygieia-jenkins-plugin build fails

### ISSUE THREAD

**Issue by anurag111527** [capitalone/Hygieia#809]
when I am trying to build this plug-in gives me a build failure message. i tried changing the snapshot from 1.3 to 1.4. gives me same error message. need assistance please. 

INFO] Building Hygieia Publisher Plugin 1.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.540 s
[INFO] Finished at: 2016-09-12T20:09:42-04:00
[INFO] Final Memory: 19M/225M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project hygieia-publisher: Could not resolve dependencies for project org.jenkins-ci.plugins:hygieia-publisher:hpi:1.4-SNAPSHOT: Failed to collect dependencies at com.capitalone.dashboard:core:jar:2.0.2-SNAPSHOT: Failed to read artifact descriptor for com.capitalone.dashboard:core:jar:2.0.2-SNAPSHOT: Failure to find com.capitalone.dashboard:Hygieia:pom:2.0.2-SNAPSHOT in http://repo.jenkins-ci.org/public/ was cached in the local repository, resolution will not be reattempted until the update interval of repo.jenkins-ci.org has elapsed or updates are forced -> [Help 1]

**Comment by tabladrum** [comment]
Failing because of Core 2.0.2 - this is already published in maven central!! Will check again.

Try "mvn clean install" on the root Hygieia project and then build this plugin. That should work.

**Comment by anurag111527** [comment]
it worked!!! thanks
