### ISSUE TITLE
NPE in CommitEventListener (bitbucket collector)

### ISSUE THREAD

**Issue by MarkRx** [capitalone/Hygieia#810]
A commit type field was added to SCM.java but is never set for non github collectors. This results in an NPE at CommitEventListener.java ~40

`if (commit.getType().equals(CommitType.New)) {`

Looks like it broke from PR #612. Tagging @tabladrum 

> java.lang.NullPointerException: null
>         at com.capitalone.dashboard.event.CommitEventListener.lambda$onAfterSave$0(CommitEventListener.java:40) ~[core-2.0.2-SNAPSHOT.jar!/:2.0.2-SNAPSHOT]
>         at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[na:1.8.0_101]
>         at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_101]
>         at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[na:1.8.0_101]
>         at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_101]
>         at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_101]
>         at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:1.8.0_101]
> 
> ```
>     at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:1.8.0_101]
>     at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_101]
>     at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[na:1.8.0_101]
>     at com.capitalone.dashboard.event.CommitEventListener.onAfterSave(CommitEventListener.java:39) ~[core-2.0.2-SNAPSHOT.jar!/:2.0.2-SNAPSHOT]
>     at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:92) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>     at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:33) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>     at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
> ```

**Comment by tabladrum** [comment]
Yep. On it.

**Comment by MarkRx** [comment]
Was fixed as part of a PR a while ago.
