### ISSUE TITLE
github collector losing commits

### ISSUE THREAD

**Issue by sans-sense** [capitalone/Hygieia#811]
https://github.com/capitalone/Hygieia/blob/master/collectors/scm/github/src/main/java/com/capitalone/dashboard/collector/DefaultGitHubClient.java#L101 checks for commits 10 minutes prior to now (10 is hardcoded here, setLastUpdated is done in the collectorTask), this means if the cron frequency is anything like 20 minutes, we may lose out on a lot of data. This will also hit us in case the collectors are restarted after the first run for any noticeable time.

**Comment by Sbrenthughes** [comment]
Please update to the latest code base and reopen if this is still an issue.
