### ISSUE TITLE
hygieia-jenkins plugin

### ISSUE THREAD

**Issue by anurag111527** [capitalone/Hygieia#814]
Hi,
    Couple of questions. After the .hpi is uploaded in jenkins, instructions to enter integration token and Hygieia server URL were given, which i dint not understand. i added /api to my Hygiea dashboard URL and that didnt bring up any thing.
![image](https://cloud.githubusercontent.com/assets/20580134/18484205/7ece1c3e-79b5-11e6-8421-624383ed919f.png)

secondly what is the integration token and where can i get it from.

thanks

**Comment by tabladrum** [comment]
Currently the integration token not been implemented. 
Once you have set the Hygieia API url set, "Apply" the config and then "Test Connection". If it says "Success", you can now create a job and publish events to Hygieia.

**Comment by anurag111527** [comment]
thank you once again for your responnse. This where i am stuck.. how do i set my API url.
apologies if I am being dumb!!
