### ISSUE TITLE
Connection refused Error in Github collector

### ISSUE THREAD

**Issue by bjayagop** [capitalone/Hygieia#817]
Hi,

I am facing connection refused error when running git-hub collector as below

I/O error on GET request for "https://api.github.com/repos/capitalone/Hygieia/commits?sha=master&since=2016-08-31T12:00Z":Connect to api.github.com:443

Any idea to resolve this ?
Thanks
Jay

**Comment by satishkrishnamurthy** [comment]
Hi,
did you fix this?I am facing the same issue.

**Comment by bjayagop** [comment]
Hi,

It's resolved by opening firewall to url api.git hub. Com.
