### ISSUE TITLE
Request:  Jira Collector needs a dynamic option for setting "team" fields

### ISSUE THREAD

**Issue by amp5208** [capitalone/Hygieia#82]
**Narrative:**

The current Jira collector only considers "teams" to be the Jira Project ~~; likewise, Jira only considers the out-of-the-box "Remaining Estimate" field for estimates.~~  Although this may be the case for most flat organizations, larger organizations may require a custom field option for setting Teams; respectively, the out of the box estimates field does not work for everyone.  I would suggest allowing a user to configure custom to their own process a field that sets where "Team" data exists~~; likewise, this should also exist for estimates.~~

**Acceptance Criteria:**
- [ ] Teams are configurable at runtime for the Jira Feature Collector, and thus configurable for the end-user on the widget display from drop-down filters
- [x] ~~Estimate fields are configurable at runtime for the Jira Feature Collector, and thus display on the widget for the end-user~~

**Use Case:**

```
# Teams
GIVEN the Hygieia Feature Widget
WHEN a user configures the widget for his/her team
THEN the "teams" available are from the custom organization configured by the specific implementation of Jira and the Hygieia Dashboard for his/her org needs
```

~~# Estimates
GIVEN:  A Jira Board configured with custom Estimate fields
WHEN:  An issue type story is created using a customized Estimate field
THEN:  The issue type story's Estimate value is applied to a running implementation of Hygieia's Feature Widget IF the custom Estimate field is mentioned at runtime.~~

**Comment by tabladrum** [comment]
@amp5208  can we close this?

**Comment by amp5208** [comment]
No - This enhancement request has not yet been implemented, nor evaluated and tagged by your team.  Please evaluate for business need and label as an enhancement for prioritization.

**Comment by amp5208** [comment]
@tabladrum , updated with full customizability requests from user @rashisaxena and @aleitner

**Comment by 415DomSmith** [comment]
@amp5208 I came across this issue when trying to implement the Jira module for my company. I was curious if this has been given more consideration or is in some sort of priority que?

I was going to attempt to implement this for our own internal use, but if it's in the pipeline for being addressed, I'll focus my attention elsewhere. 

Thanks guys!

**Comment by amp5208** [comment]
@415DomSmith , This is actually on a priority queue within our company, specifically on me.  However, you are more than welcome to implement at least the second bullet and commit it back to our code base in a pull request; just be sure to fill out the required CLA:  https://docs.google.com/forms/d/19LpBBjykHPox18vrZvBbZUcK6gQTj7qv1O5hCduAZFU/edit

**Comment by amp5208** [comment]
@tabladrum :  @MarkRx's pull request, https://github.com/capitalone/Hygieia/pull/682, resolved one of the acceptance criteria for this enhancement issue.  I have updated the content of this enhancement to reflect the resolved content.

**Comment by MarkRx** [comment]
#974 adds ability to select teams, projects, or both
