### ISSUE TITLE
U deploy build time is not correct

### ISSUE THREAD

**Issue by swathireddy2808** [capitalone/Hygieia#821]
Hi, 
when we are trying to build a job on U deploy and test it ,evrything is fine on the hygieia dashboard but the time of the build is not same as time showing on udeploy build history.

Can someone help us with the issue to check any clock settings, that give accurate or correct time.

your help would be appriciated.

thank you.

**Comment by MarkRx** [comment]
This might be the same as #869.

**Comment by MarkRx** [comment]
Can you see if the latest code fixes this?

**Comment by tabladrum** [comment]
@swathireddy2808 can you give a little more details? how off is the clock? Attached is what I have as test and it is correct. 
![image](https://cloud.githubusercontent.com/assets/6014941/20678049/4bbe1f30-b563-11e6-8cc2-4989a6be7728.png)

**Comment by satishc1** [comment]
@swathireddy2808 Please try with latest codebase and re-open if still an issue.
