### ISSUE TITLE
Unable to install Hygieia

### ISSUE THREAD

**Issue by spower1** [capitalone/Hygieia#823]
When i execute maven command, i got error from bower connecting through proxy. After several attempts, found out, i need to create .bowerrc file with all the info under Hygieia/UI.

**Comment by mrpudn** [comment]
You shouldn't need to do that. Make sure you have your `HTTP_PROXY` and `HTTPS_PROXY` environment variables set if you're behind a web proxy.

i.e. `HTTP_PROXY=http://<username>:<password>@<proxy-host>:<port>`

**Comment by satishc1** [comment]
@spower1 @mrpudn I needed a .bowerrc file via proxy as well even though I had the HTTP_PROXY and HTTPS_PROXY vars set for my shell.
