### ISSUE TITLE
github-scm-collector -- URL is getting appended with api and Error

### ISSUE THREAD

**Issue by dinukool** [capitalone/Hygieia#827]
2016-09-15 12:12:00,763 ERROR c.c.d.collector.DefaultGitHubClient - I/O error on GET request for "https://api.github.com/repos/capitalone/Hygieia/commits?sha=master&since=2016-09-15T12:02Z"

App.prop

#Database Name
dbname=dashboard
#Database HostName - default is localhost
dbhost=XX.XXX.XX.XXX
#Database Port - default is 27017
dbport=27017
#Database Username - default is blank
dbusername=db
#Database Password - default is blank
dbpassword=dbpass
#Collector schedule (required)
github.cron=0 0/1 * * * *
github.host=github.com/testk1/game-of-life.git
#Maximum number of days to go back in time when fetching commits
github.commitThresholdDays=55

![image](https://cloud.githubusercontent.com/assets/21200506/18557718/15bf10b0-7b3e-11e6-9448-7c7925dbc941.png)

**Comment by dinukool** [comment]
Need your help @MarkRx

**Comment by tabladrum** [comment]
This is the right URL. Are you behind a proxy?

**Comment by dinukool** [comment]
yes @tabladrum . but why it is appending the api prefix on collector logs?

https://**api**.github.com/repos/

2016-09-15 12:12:00,763 ERROR c.c.d.collector.DefaultGitHubClient - I/O error on GET request for "https://api.github.com/repos/capitalone/Hygieia/commits?sha=master&since=2016-09-15T12:02Z"

**Comment by tabladrum** [comment]
That is the API url of github.

**Comment by dinukool** [comment]
How to edit that ? where is it populating from?

**Comment by tabladrum** [comment]
The collector code has logic to use the right API for github.com

**Comment by dinukool** [comment]
will the bitbucket-scm-collector work with private repo? sample URL below. Pls confirm
https://myorg.com/scm/vol/dev_integration.git

**Comment by satishc1** [comment]
Functionality merged in https://github.com/capitalone/Hygieia/pull/835
Refer to the "Encryption for private repos" section in the UI module readme.
