### ISSUE TITLE
Bug: Commits in the pipeline only show up in the last configured environment

### ISSUE THREAD

**Issue by MarkRx** [capitalone/Hygieia#828]
Documenting this so it doesn't get forgotten about / lost...

This is due to the EventComponentEventListener being triggered on any environment_component that is saved. The XLD collector is resaving environment_components even if they have not changed. Not sure if the UDeploy collector is doing this too. As a result commits are being added to every environment in a pipeline which causes hygieia to interpret them as always being promoted to the last environment.

Code:

```
                if (!compList.isEmpty()) {
                    List<EnvironmentComponent> existingComponents = envComponentRepository
                            .findByCollectorItemIdAndEnvironmentID(application.getId(), environmentId);
                    envComponentRepository.delete(existingComponents);
                    envComponentRepository.save(compList);
                }
```

**Comment by nireeshT** [comment]
@MarkRx  Update to latest code base and try with new plugin
