### ISSUE TITLE
Rally Collector not working and Error creating bean with name 'rallyCollectorTask' defined

### ISSUE THREAD

**Issue by elangesk** [capitalone/Hygieia#829]
I am getting below issue while build rally-feature-collector : 

> org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'rallyCollectorTask' defined in file [C:\Users\ekanagaraj\Hygieia-master\rally-feature-collector\target\classes\co\leantechniques\hygieia\rally\collector\RallyCollectorTask.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.springframework.scheduling.TaskScheduler]: : No qualifying bean of type [org.springframework.scheduling.TaskScheduler] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.scheduling.TaskScheduler] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: 

Could you please provide to fix this issue and move forward.

**Comment by MarkRx** [comment]
Annotate RallyCollectorTask with @Component.

Spring components: http://www.techferry.com/articles/spring-annotations.html

**Comment by elangesk** [comment]
Hi MarkRx, 
Thanks for your quick response. I did the step already the code snippet as below : 

```
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.TaskScheduler;
import org.springframework.stereotype.Component;

@Component
public class RallyCollectorTask extends CollectorTask<RallyFeatureCollector> {
....
}
```

**But this issue I am facing from 2 days. Could you please share your integration experience to fix the issue and work Hygieia with Rally.**

**Comment by tabladrum** [comment]
Where is Rally collector BTW?

**Comment by elangesk** [comment]
I got from https://github.com/timgifford/Hygieia/tree/rally/rally-feature-collector and start integrate with hygieia

**Comment by elangesk** [comment]
Since properties starts with rally, I have changed RallySettings @ConfigurationProperties in to  (prefix = "rally"). But issue to build with rally collector.

`import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.stereotype.Component;

@Component
//@ConfigurationProperties(prefix = "feature")
@ConfigurationProperties(prefix = "rally")
public class RallySettings {
    private String cron;

    public String getCron() {
        return cron;
    }

    public void setCron(String cron) {
        this.cron = cron;
    }
}`

If you provide solution, most appreciate to achieve rally integration.

**Comment by mrpudn** [comment]
Since you got this collector from a fork and not this repo, you should seek help from the owner of the fork - we probably won't be able to help you here :P

**Comment by elangesk** [comment]
@timgifford 
Please look on the issue and provide help to solve the issue.

**Comment by timgifford** [comment]
@elangesk My fork is not production ready in any way and should NOT be used. I was experimenting with how to integrate Rally into Hygieia, but didn't get the code into a working or configurable state. I have since abandoned these changes. Feel free to take my changes and modify them as you wish.

I would recommend this issue be closed.

**Comment by timgifford** [comment]
I'm not clear on your questions. Here are all the changes I made at the time (it very old....1213 commits behind capitalone:master)

https://github.com/capitalone/Hygieia/compare/master...timgifford:rally

It looks like it requires your Rally credentials to be set as Environment variables: "RALLY_USERNAME" and "RALLY_PASSWORD".

https://github.com/capitalone/Hygieia/compare/master...timgifford:rally#diff-c53e0d4b6a01e1245c378850236ad65cR5

**Comment by elangesk** [comment]
@timgifford 
Thanks for your reply, Let me explain my case :

I taken latest master and integrated on subversion , Jenkins and sonar collectors successfully. 
Now I am staring to implement Rally on top that. So I taken your folder "rally-feature-collector" alone and integrating. 

Just I want to know from you as you implemented rally stuff, that pull data from rallyAPI, get stored in mongoDB and render in feature widget in Hygieia. 

Because from your experience, I can get some inputs and so that able to proceed fast implementation.

Once again thanks a lot for your great support in advance.

**Comment by gokulknewt** [comment]
Hi Tim Gifford, 
       I have noticed few comments from Hygieia forum.We are not sure how to build the rally collector with dashboard.To integrate the rally-feature-collector with dashboard, What are the configuration steps we  suppose to make sure.Also we would like to know about Initail setup to proceed our implementation.
Can you please provide the steps?
Thanks and Regards,
Gokul k

**Comment by timgifford** [comment]
@gokulknewt I'm not longer working on this. It was a solution i worked on for a couple days, but it was not finished. I expect it would not work and I have abandoned it.  I'm sure Hygieia has documentation on how to create plugins. That is where you should look for help.

Good luck!

**Comment by elangesk** [comment]
@mrpudn 
   Please see above reply from the owner of the fork. Could you please send any document or steps to integrate Rally collector wit hygieia. 

  If you provide inputs on this, really helps to improve hygieia usage and value added.

**Comment by mrpudn** [comment]
Moved to #950
