### ISSUE TITLE
Is Email functionality can be integrated with Hygieia?

### ISSUE THREAD

**Issue by AkhileshKJ** [capitalone/Hygieia#833]
Hi, We are trying to use Hygieia dashboard with SVN for first time.So do not have much idea, hence this might a stupid question:
Q: Based on the details that we have in DB for SVN, can we configure anything in Hygieia to send mails for  SVN details as report.
Or please let me know if we have any script available separately that we use to get the details and send the report.
Thanks !
-Akhilesh

**Comment by satishc1** [comment]
@AkhileshKJ You could do an svn post-commit hook to send an email and provide the hygieia dashboard url within it. You could add email functionality within hygieia by changing some code in the svn collector, but you would need to think about what causes the email to be triggered.
