### ISSUE TITLE
Jenkins collector defaults to localhost 

### ISSUE THREAD

**Issue by bjayagop** [capitalone/Hygieia#834]
Jenkins collector overrides the hostname setting in application.properties and defaults to localhost. As a result it fails to connect to Jenkins host for accessing build info with api calls.

application.properties

```
# Database Name
dbname=dashboard
# Database HostName - default is localhost
dbhost=localhost
# Database Port - default is 27017
dbport=27017
# Database Username - default is blank
dbusername=dashboarduser
# Database Password - default is blank
dbpassword=dbpassword

# Collector schedule (required)
jenkins.cron=0 0/5 * * * *
jenkins.servers[0]=http://jenkinshost:8989
```

Error from collector logs below

```
2016-09-16 15:05:01,171 ERROR c.c.d.collector.DefaultHudsonClient - Client exception loading build details: I/O error on GET request for "http://localhost:8989/job/testbuild/24/api/json?tree=number,url,timestamp,duration,building,result,culprits[fullName],changeSet[items[user,author[fullName],revision,id,msg,timestamp,date,paths[file]],kind,revisions[module,revision]],actions[lastBuiltRevision[SHA1,branch[SHA1,name]],remoteUrls]":Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect. URL =http://localhost:8989/job/testbuild/24/
```

Any clue to resolve ?

**Comment by jimzucker** [comment]
You want to set JIRA_BASE_URL to your JIRA server, to get lira to work you actually want to set all of these variables to the correct value for you instance. if you are using the docker compose you can put this entry with modified values in docker-compose.override.yml.

hygieia-jira-feature-collector:
  environment:
  - JIRA_BASE_URL=https://stratengllc.atlassian.net/
  - JIRA_CREDENTIALS=xxxxxxxxxxxxxxxxx
  - JIRA_ISSUE_TYPE_ID=10200
  - JIRA_SPRINT_DATA_FIELD_NAME=customfield_10007
  - JIRA_EPIC_FIELD_NAME=customfield_10008

**Comment by bjayagop** [comment]
I am facing issues with Jenkins collector. Jenkins collector defaults to localhost always causing failures in api request to jenkin host.

Please suggest.

**Comment by mrpudn** [comment]
As @jimzucker said:
>> You want to set JIRA_BASE_URL to your JIRA server

You'll have to edit your `.properties` file for the JIRA collector to point to your server

**Comment by bjayagop** [comment]
How is JIRA_BASE_URL related to Jenkins collector ? The issue is in Jenkins collector and NOT in JIRA.

Pls suggest.

**Comment by mrpudn** [comment]
Oh, sorry - sometimes all of this stuff just blends together, haha.

Are you running the collector in docker? It looks like there's a few things that might be the culprit

**Comment by satishc1** [comment]
@bjayagop You might be missing this --spring.config.name=jenkins while you are running the jenkins collector .. or you might have set it to hudson.  Reopen if still an issue.
