### ISSUE TITLE
Validate Code Repo settings and display status to the user.

### ISSUE THREAD

**Issue by satishc1** [capitalone/Hygieia#836]
There is currently no validation when saving repo settings from the config screen. Add a status to the dialog box to validate the repo URL, SSL, Auth and display an error to the user on the Config screen if not properly setup.

**Comment by golokeshpatra45** [comment]
I am working with an enterprise/Private github Repo, but I am getting an error - 401 Unauthorized . Please help.....

![image](https://cloud.githubusercontent.com/assets/26374269/26617556/5544e23e-45f3-11e7-84db-fd9ff6e9d93f.png)

The dashboard looks like

![image](https://cloud.githubusercontent.com/assets/26374269/26617585/791ce440-45f3-11e7-9f67-1c72446b5721.png)

**Comment by nitin1706** [comment]
@golokeshpatra45 : try with latest codebase. Refer #883, #908. Open a new issue if see this error.
