### ISSUE TITLE
How to create custom widget

### ISSUE THREAD

**Issue by drewkhoury** [capitalone/Hygieia#837]
Hi.

Is there documentation (or can you help show me how to) create my own custom widget to add to the dashboard? A hello world would be a good start.

**Comment by sibaom** [comment]
Hi ,
You can create your custom widget for that you need to change all angular config file as well as the restpoint you need to enable.please contact sibapr30@gmail.com.looking for the same.

**Comment by satishc1** [comment]
Look at these 2 issues for a starting point on creating custom collectors and widgets.
https://github.com/capitalone/Hygieia/issues/733
https://github.com/capitalone/Hygieia/issues/717

**Comment by monabhardwaj** [comment]
Hello! I'm new to Hygieia and currently attempting to create a custom github collector. I have gone through various articles on the same but weren't of much help on the beginner level. It would be invaluable for me if could extend any advice or sample projects on how you got your custom collector working. Thank You!

**Comment by senapatirupen** [comment]
Is there any sample UI widget is available
