### ISSUE TITLE
Class cast exception in Jenkins collector

### ISSUE THREAD

**Issue by bjayagop** [capitalone/Hygieia#839]
Getting this error when running Jenkins collector
java.lang.ClassCastException: org.json.simple.JSONArray cannot be cast to org.json.simple.JSONObject

Any clue ?

**Comment by jimzucker** [comment]
@bjayagop can you let us know:

1. what version of Jenkins you are using
2. are you running as a jar or wth docker
3. what env variables are you setting
4. please attach the full stack trace.

**Comment by tabladrum** [comment]
Can you put the line numbers in the stack trace?

**Comment by satishc1** [comment]
@bjayagop Closed. Use the latest codebase. Reopen if still an issue.
