### ISSUE TITLE
Request:  Build Widget Should Flag Yellow on Yellow Builds

### ISSUE THREAD

**Issue by amp5208** [capitalone/Hygieia#84]
<strong>Business Need</strong>

As a DevOps engineer, I need to see the Build widget on Hygieia display as a block "Yellow" warning on Yellow statuses in Jenkins and Hudson, not just "Red," so that I can more clearly understand what the true status is of my builds

<strong>Acceptance Criteria</strong>
<pre>
GIVEN the Hygieia Build Widget
WHEN a Jenkins OR Hudson job is Yellow
THEN the Hygieia Build Widget displays as block "Yellow" status warning (not "Red")
</pre>

**Comment by yqbjtu** [comment]
@amitmawkin ,  Do you know what the default admin user/password?  When i open http://xxxx:3000, I can signup a new user, but Does it has admin user by default?  For When I start the API and Jenkins collector,  I can't config the "config the build widget" for there is no any build job.  Thank you!

**Comment by amitmawkin** [comment]
@yqbjtu just create a user with userid admin, when you login with admin next time, you will be able to modify any dashboard or delete one's you don't own.

**Comment by yqbjtu** [comment]
@amitmawkin ,   Thanks!  I have already created some users.   When I start the API and Jenkins collector, I can't config the "config the build widget" for there is no any build job. Do you know how to resolve this?    My jenkins works well,  and Jenkins collector can get some new jobs, but can't get new builds although there is some new builds.  Thank you!

**Comment by vishalbisa** [comment]
Hi @yqbjtu 

Can you paste the application.properties file, any API/collector errors might help to investigate further.

Thanks

**Comment by satishc1** [comment]
Closed. Please follow https://github.com/capitalone/Hygieia/issues/680
