### ISSUE TITLE
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.29:bower (bower install) on project UI: Failed to run task: 'bower install' failed

### ISSUE THREAD

**Issue by upendram91** [capitalone/Hygieia#842]
```
[INFO] Running 'bower install' in C:\...\Hygieia\UI
[ERROR] module.js:327
[ERROR]     throw err;
[ERROR]     ^
[ERROR]
[ERROR] Error: Cannot find module 'mout'
[ERROR]     at Function.Module._resolveFilename (module.js:325:15)
[ERROR]     at Function.Module._load (module.js:276:25)
[ERROR]     at Module.require (module.js:353:17)
[ERROR]     at require (internal/module.js:12:17)
[ERROR]     at Object.<anonymous> (C:\Users\upendra\Documents\GitHub\Hygieia\UI\node_modules\bower\lib\bin\bower.js:4:12)
[ERROR]     at Module._compile (module.js:397:26)
[ERROR]     at Object.Module._extensions..js (module.js:404:10)
[ERROR]     at Module.load (module.js:343:32)
[ERROR]     at Function.Module._load (module.js:300:12)
[ERROR]     at Module.require (module.js:353:17)
```

**Comment by pnadimpalli** [comment]
I have the similar error while running on Windows.

 --- frontend-maven-plugin:0.0.29:bower (bower install) @ UI ---
 Found proxies: []
 Running 'bower install' in C:\Users\user\git\Hygieia\UI
] module.js:327
]     throw err;
]     ^
]
] Error: Cannot find module 'q'
]     at Function.Module._resolveFilename (module.js:325:15)
]     at Function.Module._load (module.js:276:25)
]     at Module.require (module.js:353:17)
]     at require (internal/module.js:12:17)
]     at Object.<anonymous> (C:\Users\user\git\Hygieia\UI\node_modules\bower\lib\bin\bower.js:3:9)
]     at Module._compile (module.js:397:26)
]     at Object.Module._extensions..js (module.js:404:10)
]     at Module.load (module.js:343:32)
]     at Function.Module._load (module.js:300:12)
]     at Module.require (module.js:353:17)
 ------------------------------------------------------------------------
 Reactor Summary:

**Comment by mrpudn** [comment]
The `q` module should definitely exist. Please check your network and proxy settings (if you're behind a proxy) and try again.

**Comment by satishc1** [comment]
@upendram91 Delete C:\...\Hygieia\UI\node_modules and C:\...\Hygieia\UI\bower_components.
Run mvn package inside C:\...\Hygieia\UI on a network which is not restricted by proxy.
