### ISSUE TITLE
Jenkins build collector api key or username passoword?

### ISSUE THREAD

**Issue by summit123** [capitalone/Hygieia#847]
Hi,
On the properties file for the jenkins build collector, we don't use any API keys. What are other ways of authentication? Can it collect using username/password combination?

# Jenkins server (required) - Can provide multiple
jenkins.servers[0]=http://jenkins.company.com

# If using username/token for api authentication
#   (required for Cloudbees Jenkins Ops Center) see sample
jenkins.servers[1]=http://username:token@jenkins.company.com

# Another option: If using same username/password Jenkins auth,
#   set username/apiKey to use HTTP Basic Auth (blank=no auth)
jenkins.username=
jenkins.apiKey=

Thanks 
Sam G

**Comment by shakunnag** [comment]
Not sure but still posting. Were you able to complete this? I started with hygieia today only and just wondering where do I provide Jenkins/sonar/JIRA password?
