### ISSUE TITLE
docker image for UI layer

### ISSUE THREAD

**Issue by summit123** [capitalone/Hygieia#848]
Hello,
I am able to run docker process for mongodb and API and they do not stop until the process is killed. But the docker run for UI layer is only running after giving the command but the process is killed after exiting. The command I used:
sudo docker run -t -p 8088:80 --name hygieia-ui --link hygieia-api -i hygieia-ui:latest

The API connectivity is good and UI is also good.

**Comment by mrpudn** [comment]
Try:
```bash
sudo docker run -d \
  -p 8088:80 \
  --name hygieia-ui \
  --link hygieia-api \
  -i hygieia-ui:latest
```

The `-d` flag should run the container in daemon mode, so the terminal should give you back your shell session.

**Comment by summit123** [comment]
worked!! Thanks for your assistance :)
