### ISSUE TITLE
Request:  The Feature Widget should be Interactive

### ISSUE THREAD

**Issue by amp5208** [capitalone/Hygieia#85]
<strong>Business Need</strong>

As a DevOps engineer, I want to be able to interact with the Feature widget on the Hygieia Dashboard in a meaningful way, so that I can get more detail into my agile content going through my pipeline.

<strong>Acceptance Criteria</strong>

<pre>
GIVEN a configured Hygieia Feature Widget
WHEN certain progress values for an Agile team and sprint are unfavorable
THEN the Hygieia Feature Widget flags "Yellow" and/or "Red" depending on severity

GIVEN a configured Hygieia Feature Widget
WHEN the Widget is clicked
THEN the user is sent to a DevOps-configured web page (e.g., the content management source system or another tool that aggregates/analyzes Agile data)
</pre>

**Comment by tabladrum** [comment]
Other changes may solve for this. Closing this.
