### ISSUE TITLE
Can I use Product View without having deploy collector?

### ISSUE THREAD

**Issue by oshingc** [capitalone/Hygieia#855]
Hi team, I wonder if is there an option to show the group data on the product dashboard from MongoDB but without having deploy collector? :c

**Comment by tabladrum** [comment]
You would need deployment data. Jenkins plugin can publish deployment data from your deployment jobs on Jenkins.

**Comment by oshingc** [comment]
@tabladrum 
I have jenkins jobs but that can only populate the Build Stage.
How can I populate data for the stages DEV, QA, INT, PERF ?
![ppp](https://cloud.githubusercontent.com/assets/3100819/19123884/474e527c-8af6-11e6-956e-3eb4c4402804.png)

Thanks in advance :D

**Comment by satishc1** [comment]
@oshingc Closed . https://github.com/capitalone/Hygieia/issues/884

**Comment by HygieiaUser** [comment]
Hello Team. Need some help with product dashboard. We are not using any deployment collector. With Jenkins collector we are not getting the branches as (Dev, QA ..) in our product dashboard.
Can you please let us know is there any configuration settings  we need to do for achieving this?Thanks in advance

**Comment by nireeshT** [comment]
@HygieiaUser  - install hygieia-jenkins publisher plugin and configure post build actions in your jenkins jobs for all environments. Plugin will push deployment data to Mongo and deploy widget in you dashboard will display your job names. Follow https://github.com/capitalone/Hygieia/tree/master/hygieia-jenkins-plugin
Once deploy widget is configured, configure pipeline widget and then you should see all the information on product dashboard.
