### ISSUE TITLE
Stash password encryption error

### ISSUE THREAD

**Issue by adityacs** [capitalone/Hygieia#856]
I am using stash and have configured bitbucket collector for it. When I give the password in UI and save it says "**error encrypting password**".  Please help me on this
![capture](https://cloud.githubusercontent.com/assets/7681197/18742894/2815a40e-80d4-11e6-8299-2241a11b3e93.PNG)

**Comment by sanjeevnewt** [comment]
@adityacs Read section "Encryption for private repos" under UI module

**Comment by adityacs** [comment]
@sanjeevnewt Could you please tell me the steps to follow after generating the key. The documentation is not quiet clear. "key=" should be added where?

**Comment by adityacs** [comment]
Can someone please help me on this?.

**Comment by tabladrum** [comment]
@satishc1

**Comment by satishc1** [comment]
@adityacs 

"key="  should be added to api.properties
AND depending on which collector you are running add it to the appropriate collector. For github add this
"github.key=" should be added to github.properties

**Comment by dinukool** [comment]
Now Stash will connect to Private repo's ? kindly confirm?

https://stash.myorg.com/projects/

@satishc1

**Comment by satishc1** [comment]
@dinukool I have tested it with github, but it should work with stash also. Try it out and let us know if you run into issues.

**Comment by anuragmishracrest** [comment]
@satishc1 Do I have to specify my github username and password in github collectors properties file before generating key using core.

2nd you have mentioned api.properties but in your repo api.properties is not present 
does it mean application.properties

**Comment by anuragmishracrest** [comment]
@satishc1 will this work if repo is have 12 factor authentication enabled ?

**Comment by zaitsxl** [comment]
I wonder why this param is not mentioned in any collector settings template file
