### ISSUE TITLE
SCM collector for Enterprise Git Repository Management

### ISSUE THREAD

**Issue by summit123** [capitalone/Hygieia#859]
Hi, Does Hygieia scm collector support Git Repository managed for enterprise powered by Atlassian Stash? The domain is not www.github.com or www.mystash.com. If supported, which collector to use? Stash?

Thanks for your help

**Comment by MarkRx** [comment]
Use the bitbucket collector. Stash was rebranded as bitbucket not too long ago.

**Comment by summit123** [comment]
Thanks MarkRx for the reply!! on the application.properties file though, what does it mean by git api? Following is the structure of my scm url: will it require any kind of api authentication for bitbucket? The scm site listens at regular port 443 and ssh configured at 2599.
# mandatory:
git.host=abcode.web.cde.com/
git.api=???

Thanks

**Comment by MarkRx** [comment]
The default value for that is /rest/api/1.0/
It is the base path to the rest api.

**Comment by summit123** [comment]
@MarkRx Thanks for your reply! 
Our instance of Enterprise Bitbucket is very large. Does Hygieia have any known issues with large number of repositories as far as performance/stress testing is concerned?

Thanks

**Comment by tabladrum** [comment]
There is a performance concern in any kind of collection process. Our Github collection process runs quite fast though and we do have a huge number of repos. One thing to keep an eye on - the rate limit (if you have any) on the BitBucket server. We (as an alternative) use GitHub hook too. There is no hook implementation for Bitbucket yet. Looking for a contrib. It can be almost a copy-paste of the Github hook. Here is the controller code: https://github.com/capitalone/Hygieia/blob/master/api/src/main/java/com/capitalone/dashboard/rest/ZCommitController.java

**Comment by summit123** [comment]
Thanks @tabladrum @MarkRx. I am trying to find information regarding bitbucket collector. Our repos are private. I am not able to successfully connect to bitbucket repo. Is the collector able to connect with private repositories? Thanks in advance!!
My docker-compose.yml:

hygieia-bitbucket-scm-collector:
  image: hygieia-bitbucket-scm-collector:latest
  container_name: hygieia-bitbucket
  volumes:
  - ./logs:/hygieia/logs
  links:
  - mongodb:mongo
  - hygieia-api
  environment:
    #mandatory
  - BITBUCKET_HOST=https://mybitbuckethost.com/
  - BITBUCKET_API=/rest/api/1.0/projects/<project>/repos/<repository>
  - BITBUCKET_CREDENTIALS=d2cwNTQYWkxMiE=
  - BITBUCKET_CRON=0 0/5 * * * *
  - BITBUCKET_PRODUCT=Cloud

#Maximum number of days to go back in time when fetching commits. Only applicable to Bitbucket Cloud.
  - BITBUCKET_COMMIT_THRESHOLD_DAYS=15

#Page size for rest calls. Only applicable to Bitbucket Server.
  - BITBUCKET_PAGE_SIZE=25

**Comment by Sbrenthughes** [comment]
Please reopen if this is still a valid issue after updating to latest code.
