### ISSUE TITLE
Prod stage in product dashboard shows up empty

### ISSUE THREAD

**Issue by pxk5958** [capitalone/Hygieia#861]
The requests to retrieve data for the pipeline in Product dashboard page is as follows:
`GET /api/pipeline/?beginDate=1473870563954&collectorItemId=57d96a5546e0fb000f005bd1&endDate=1473870623961 HTTP/1.1`

The beginDate parameter above is being set to the last request's timestamp in UI/src/components/widgets/product/js/commit-data.js:44
`// if we already have made a request, just get the delta
if (lastRequest) {
    dateBegins = lastRequest.timestamp;
}`

But these timestamps are being used to filter out commits outside these timestamps' bounds in Prod stage in api/src/main/java/com/capitalone/dashboard/service/PipelineServiceImpl.java:84
`if(!isBetween(commit.getProcessedTimestamps().get(stage.name()), lowerBound, upperBound)){
    commitIterator.remove();
}`

As a result, usually all the commits are filtered out if there are no commits since the page was last loaded (lastRequest).

@vtjiles @johnkangcurd

**Comment by nireeshT** [comment]
@pxk5958  - Update to the latest code and configure product dashboard.  Reopen if issue is not fixed.
