### ISSUE TITLE
facing issue with hygieia maven build

### ISSUE THREAD

**Issue by Samriddhi1** [capitalone/Hygieia#863]
@tabladrum 

Hi Tabladrum

I am trying to make the Hygieia instance up on a VM over a CentOS 7.0 base OS. While giving the command "mvn clean install package" in root.I am facing the following error: 

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 44.444 s
[INFO] Finished at: 2016-09-23T11:28:20+00:00
[INFO] Final Memory: 40M/117M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.
17:test (default-test) on project core: There are test failures.
[ERROR]
[ERROR] Please refer to /home/ibmcloud/Hygieia-2.0.0/core/target/surefire-report
s for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :core
```

To this error, i found a solution given by you, which says, we need to got to "core" and run mvn install package first and then run mvn clean install package form the root. I even tried to implement the same but faced the following error: 

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 23.214 s
[INFO] Finished at: 2016-09-23T11:30:32+00:00
[INFO] Final Memory: 35M/91M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.
17:test (default-test) on project core: There are test failures.
[ERROR]
[ERROR] Please refer to /home/ibmcloud/Hygieia-2.0.0/core/target/surefire-report
s for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
```
Can you please   @@help..It's very urgent for me to get the issue resolved.! :(

**Comment by mrpudn** [comment]
Can you please share the test report at:
`/home/ibmcloud/Hygieia-2.0.0/core/target/surefire-reports`

**Comment by Samriddhi1** [comment]
Hi Zach,

Thanks for attending my issue. Somehow.I am able to execute the project. I 
am now facing an issue while i am trying to execute the jar files of all 
the collectors.
I ll post the error that I am facing:


While executing the api.jar file using the command : java -jar 
target\api.jar --spring.config.name=api 
--spring.config.location=dashboard.properties   , I get the following 
logs:

 :: Spring Boot ::        (v1.2.5.RELEASE)

2016-09-27 10:29:23,677 INFO  com.capitalone.dashboard.Application - 
Starting Ap
plication v2.0.0-SNAPSHOT with PID 4670 
(/home/ibmcloud/Hygieia-2.0.0/api/target
/api.jar started by root in /home/ibmcloud/Hygieia-2.0.0/api)
2016-09-27 10:29:23,757 INFO 
o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationCo
ntext - Refreshing 
org.springframework.boot.context.embedded.AnnotationConfigEmb
eddedWebApplicationContext@4a9effa2: startup date [Tue Sep 27 10:29:23 UTC 
2016]
; root of context hierarchy
2016-09-27 10:29:26,188 INFO 
o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - J
SR-330 'javax.inject.Inject' annotation found and supported for autowiring
2016-09-27 10:29:26,250 INFO  o.h.validator.internal.util.Version - 
HV000001: Hi
bernate Validator 5.1.3.Final
2016-09-27 10:29:26,903 INFO  o.s.b.c.e.t.TomcatEmbeddedServletContainer - 
Tomca
t initialized with port(s): 8080 (http)
2016-09-27 10:29:27,223 INFO  o.a.catalina.core.StandardService - Starting 
servi
ce Tomcat
2016-09-27 10:29:27,225 INFO  o.a.catalina.core.StandardEngine - Starting 
Servle
t Engine: Apache Tomcat/8.0.23
2016-09-27 10:29:27,487 INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - 
Initializing
Spring embedded WebApplicationContext
2016-09-27 10:29:27,487 INFO  o.s.web.context.ContextLoader - Root 
WebApplicatio
nContext: initialization completed in 3730 ms
2016-09-27 10:29:27,740 INFO  c.c.dashboard.config.MongoConfig - 
Initializing Mo
ngo Client server at: localhost:27017
2016-09-27 10:29:27,867 INFO  org.mongodb.driver.cluster - Cluster created 
with
settings {hosts=[localhost:27017], mode=SINGLE, 
requiredClusterType=UNKNOWN, ser
verSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2016-09-27 10:29:27,900 INFO  c.c.dashboard.config.MongoConfig - 
Connecting to M
ongo: Mongo{options=MongoClientOptions{description='null', 
readPreference=primar
y, writeConcern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, 
codecRegistr
y=org.bson.codecs.configuration.ProvidersCodecRegistry@f0b59a60, 
minConnectionsP
erHost=0, maxConnectionsPerHost=100, 
threadsAllowedToBlockForConnectionMultiplie
r=5, serverSelectionTimeout=30000, maxWaitTime=120000, 
maxConnectionIdleTime=0,
maxConnectionLifeTime=0, connectTimeout=10000, socketTimeout=0, 
socketKeepAlive=
false, sslEnabled=false, sslInvalidHostNamesAllowed=false, 
alwaysUseMBeans=false
, heartbeatFrequency=10000, minHeartbeatFrequency=500, 
heartbeatConnectTimeout=2
0000, heartbeatSocketTimeout=20000, localThreshold=15, 
requiredReplicaSetName='n
ull', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@5ecca014, 
dbEncoderFactory
=com.mongodb.DefaultDBEncoder$1@7f2b64e0, 
socketFactory=javax.net.DefaultSocketF
actory@704899ba, cursorFinalizerEnabled=true, 
connectionPoolSettings=ConnectionP
oolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, 
maxWaitTimeMS=120000,
maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, 
maintenanceInitialDelayMS=
0, maintenanceFrequencyMS=60000}, 
socketSettings=SocketSettings{connectTimeoutMS
=10000, readTimeoutMS=0, keepAlive=false, receiveBufferSize=0, 
sendBufferSize=0}
, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, 
minHeartbeatFrequenc
yMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, 
readTim
eoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2016-09-27 10:29:28,030 INFO  org.mongodb.driver.connection - Opened 
connection
[connectionId{localValue:1, serverValue:42}] to localhost:27017
2016-09-27 10:29:28,033 INFO  org.mongodb.driver.cluster - Monitor thread 
succes
sfully connected to server with description 
ServerDescription{address=localhost:
27017, type=STANDALONE, state=CONNECTED, ok=true, 
version=ServerVersion{versionL
ist=[2, 6, 12]}, minWireVersion=0, maxWireVersion=2, electionId=null, 
maxDocumen
tSize=16777216, roundTripTimeNanos=1918200}
2016-09-27 10:29:28,253 INFO  o.s.b.c.e.ServletRegistrationBean - Mapping 
servle
t: 'dispatcherServlet' to [/]
2016-09-27 10:29:28,260 INFO  o.s.b.c.e.FilterRegistrationBean - Mapping 
filter:
 'characterEncodingFilter' to: [/*]
2016-09-27 10:29:28,260 INFO  o.s.b.c.e.FilterRegistrationBean - Mapping 
filter:
 'loggingFilter' to: [/*]
2016-09-27 10:29:28,675 INFO  org.mongodb.driver.connection - Opened 
connection
[connectionId{localValue:2, serverValue:43}] to localhost:27017
2016-09-27 10:29:31,076 INFO  org.mongodb.driver.cluster - Monitor thread 
succes
sfully connected to server with description 
ServerDescription{address=localhost:
27017, type=STANDALONE, state=CONNECTED, ok=true, 
version=ServerVersion{versionL
ist=[2, 6, 12]}, minWireVersion=0, maxWireVersion=2, electionId=null, 
maxDocumen
tSize=16777216, roundTripTimeNanos=453641}
2016-09-27 10:29:31,078 INFO  org.mongodb.driver.connection - Opened 
connection
[connectionId{localValue:5, serverValue:46}] to localhost:27017
2016-09-27 10:29:31,079 INFO  org.mongodb.driver.cluster - Monitor thread 
succes
sfully connected to server with description 
ServerDescription{address=localhost:
27017, type=STANDALONE, state=CONNECTED, ok=true, 
version=ServerVersion{versionL
ist=[2, 6, 12]}, minWireVersion=0, maxWireVersion=2, electionId=null, 
maxDocumen
tSize=16777216, roundTripTimeNanos=423444}
2016-09-27 10:29:31,082 INFO  c.c.dashboard.config.MongoConfig - 
Connecting to M
ongo: Mongo{options=MongoClientOptions{description='null', 
readPreference=primar
y, writeConcern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, 
codecRegistr
y=org.bson.codecs.configuration.ProvidersCodecRegistry@f0b59a60, 
minConnectionsP
erHost=0, maxConnectionsPerHost=100, 
threadsAllowedToBlockForConnectionMultiplie
r=5, serverSelectionTimeout=30000, maxWaitTime=120000, 
maxConnectionIdleTime=0,
maxConnectionLifeTime=0, connectTimeout=10000, socketTimeout=0, 
socketKeepAlive=
false, sslEnabled=false, sslInvalidHostNamesAllowed=false, 
alwaysUseMBeans=false
, heartbeatFrequency=10000, minHeartbeatFrequency=500, 
heartbeatConnectTimeout=2
0000, heartbeatSocketTimeout=20000, localThreshold=15, 
requiredReplicaSetName='n
ull', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@5ecca014, 
dbEncoderFactory
=com.mongodb.DefaultDBEncoder$1@7f2b64e0, 
socketFactory=javax.net.DefaultSocketF
actory@704899ba, cursorFinalizerEnabled=true, 
connectionPoolSettings=ConnectionP
oolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, 
maxWaitTimeMS=120000,
maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, 
maintenanceInitialDelayMS=
0, maintenanceFrequencyMS=60000}, 
socketSettings=SocketSettings{connectTimeoutMS
=10000, readTimeoutMS=0, keepAlive=false, receiveBufferSize=0, 
sendBufferSize=0}
, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, 
minHeartbeatFrequenc
yMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, 
readTim
eoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2016-09-27 10:29:31,379 INFO  o.s.j.e.a.AnnotationMBeanExporter - 
Registering be
ans for JMX exposure on startup
2016-09-27 10:29:31,391 INFO  s.d.s.w.p.DocumentationPluginsBootstrapper - 
Conte
xt refreshed
2016-09-27 10:29:31,418 INFO  s.d.s.w.p.DocumentationPluginsBootstrapper - 
Found
 1 custom documentation plugin(s)
2016-09-27 10:29:31,432 INFO  s.d.s.w.s.ApiListingReferenceScanner - 
Scanning fo
r api listing references
2016-09-27 10:29:31,857 INFO  s.d.s.w.r.o.CachingOperationNameGenerator - 
Genera
ting unique operation named: searchUsingGET_1
2016-09-27 10:29:31,944 INFO  s.d.s.w.r.o.CachingOperationNameGenerator - 
Genera
ting unique operation named: createBuildUsingPOST_1
2016-09-27 10:29:31,957 INFO  s.d.s.w.r.o.CachingOperationNameGenerator - 
Genera
ting unique operation named: deployStatusUsingGET_1
2016-09-27 10:29:32,138 INFO  s.d.s.w.r.o.CachingOperationNameGenerator - 
Genera
ting unique operation named: qualityDataUsingGET_1
2016-09-27 10:29:32,181 INFO  o.a.coyote.http11.Http11NioProtocol - 
Initializing
 ProtocolHandler ["http-nio-8080"]
2016-09-27 10:29:32,197 INFO  o.a.coyote.http11.Http11NioProtocol - 
Starting Pro
tocolHandler ["http-nio-8080"]
2016-09-27 10:29:32,203 INFO  o.a.tomcat.util.net.NioSelectorPool - Using 
a shar
ed selector for servlet write/read
2016-09-27 10:29:32,226 INFO  o.s.b.c.e.t.TomcatEmbeddedServletContainer - 
Tomca
t started on port(s): 8080 (http)
2016-09-27 10:29:32,228 INFO  com.capitalone.dashboard.Application - 
Started App
lication in 8.922 seconds (JVM running for 9.848)

It seems it is running successfully but I am not able to access it through 
my ip address:port i.e., 169.50.118.135 :8080/api

**Comment by mrpudn** [comment]
You might have the same problem as #698

If you're running Hygieia from within a VM, the API will be listening at `http://localhost:8080` in your VM - in order to access it from the host, you should be able to use `http://10.0.2.2:8080`.

If you're not using a VM, you should be able to reach the API at `http://localhost:8080`. The UI should be available at `http://localhost:3000`.

**Comment by satishc1** [comment]
Reopen if this is still an issue.
