### ISSUE TITLE
Product dashboard doesn't display data right away

### ISSUE THREAD

**Issue by MarkRx** [capitalone/Hygieia#864]
Not sure why yet but when I first load the product dashboard everything is blank. To get data to start showing I have to click the configure button to open that dialog then close it. Data will also show up if I wait a minute or so (perhaps some auto refresh gets triggered).

![image](https://cloud.githubusercontent.com/assets/17504314/18785319/981a330a-8165-11e6-8d09-ce0536534002.png)

Chrome Version 53.0.2785.116 m (64-bit)

**Comment by sanjeevnewt** [comment]
I too not able to see the data even after many refresh.

**Comment by MarkRx** [comment]
I'm not a web developer but I think some kind of refresh/notification needs to happen to the row after data is updated in product/view.js setTeamData. I suspect there is a periodic refresh of 1 minute somewhere that is causing the data to get updated but delayed by 1 refresh (so the second refresh shows the data from the 1st call, the 3rd refresh shows the data from the second call, etc).

**Comment by tabladrum** [comment]
I will take a look at it tonight

**Comment by sanjeevnewt** [comment]
@tabladrum any update on this one?

**Comment by tabladrum** [comment]
It does take a few minutes to get the data for the first time. From that time onwards it uses the browser cache. So depending upon how much data you already have it may take about 2 minutes for the initial load.

**Comment by MarkRx** [comment]
@tabladrum it still occurs even if the data response is very fast. I watched the response through the debugger and the data comes back in less than a second.

**Comment by tabladrum** [comment]
Interesting.Let me hit it with more debugs.

**Comment by MarkRx** [comment]
@tabladrum I think I found and fixed the issue. #1021

**Comment by nireeshT** [comment]
Fixed with #1020
