### ISSUE TITLE
Bug: pipeline dashboard build commit time statistics off

### ISSUE THREAD

**Issue by MarkRx** [capitalone/Hygieia#869]
BuildEventListener.java is using build.getTimestamp() for the PipelineCommit timestamps. The timestamp on builds is being stamped with the system time of when the collector was run. Hence when the collector first runs and picks up a lot of builds these builds will have nearly identical timestamps. The pipeline will then report numbers based on these timestamps (when the collector ran as opposed to when the build ran).

The code should instead reference build.getStartTime() (or build.getEndTime()) to more accurately represent when the commit entered that stage of the pipeline.

**Comment by mrpudn** [comment]
@MarkRx can we close this one? It appears to be resolved with #888

**Comment by MarkRx** [comment]
yup
