### ISSUE TITLE
UI Issue

### ISSUE THREAD

**Issue by elakkiyaguru** [capitalone/Hygieia#871]
If more than user is signed into the Hygieia then if a user does any activity on screen like scroll screen etc. then it is reflected on screen of others. What is the purpose of this functionality and how can we turn this off?

**Comment by mrpudn** [comment]
I believe this is a browser-sync feature - you'll need to build (`gulp build`) the UI and serve it via a webserver like nginx or Apache for "production" deployments.

**Comment by elakkiyaguru** [comment]
Can you please tell me how to Deploy this UI in Tomcat ?

**Comment by elakkiyaguru** [comment]
Our team is looking to integrate Hygieia with single sign on. Our team has the option of using Siteminder or SAML 2.0. Please let us know 

a) if there is support for either of these in Hygieia. 
b) Are there any plans of integrating with either ?

**Comment by mrpudn** [comment]
Duplicate #627

Single sign on should now be supported via LDAP - see #958
