### ISSUE TITLE
Jenkins build collector issue

### ISSUE THREAD

**Issue by summit123** [capitalone/Hygieia#872]
Hi,
I have installed hygieia on a separate machine than jenkins. On the properties file for the jenkins build collector, I am having issues connecting to my Jenkins from the hygieia machine. provided the api keys from Credentials->configure->API keys. But still not connecting to Jenkins.
Can anyone assist?
Jenkins server (required) - Can provide multiple

jenkins.servers[0]=http://123.34.23.423:1234/jenkins/
or
jenkins.servers[0]=http://my-jenkins.url:1234/jenkins/
If using username/token for api authentication
(required for Cloudbees Jenkins Ops Center) see sample
# jenkins.servers[1]=http://username:token@jenkins.company.com

Another option: If using same username/password Jenkins auth,
set username/apiKey to use HTTP Basic Auth (blank=no auth)

jenkins.username=ab1234
jenkins.apiKey=myapikey

Thanks
Sam G

**Comment by tabladrum** [comment]
Can you paste the stack trace? Thanks.

**Comment by summit123** [comment]
Solved this by opting to use hygieia-jenkins-plugin. Thanks!!

**Comment by Ashissh021** [comment]
Hi,

I am having issue with Jenkins and hygieia connectivity, I am using cludbees Jenkins and trying to connect with username and API (jenkins.servers[0]=https://userName:***API***@****.net) but getting error 
ValidatorException: PKIX path building failed: sun.security.provider.cer
tpath.SunCertPathBuilderException: unable to find valid certification path to re
quested target
