### ISSUE TITLE
Disable Click to Signup

### ISSUE THREAD

**Issue by rpatel01** [capitalone/Hygieia#876]
Is it possible to disable the sign up feature at the login page?
If we were to deploy this on the cloud for example, it does pose a security risk.

**Comment by satishc1** [comment]
There is no feature to disable it on the fly, however you could take it out from UI\src\app\dashboard\views\login.html . But the right way to do it is to make it feature / parameter driven and enable / disable on the fly.

**Comment by MarkRx** [comment]
This is on my list of things to do
