### ISSUE TITLE
Formatting Text

### ISSUE THREAD

**Issue by eldojoseph** [capitalone/Hygieia#878]
Can someone help to change the color of text. I changed background to gray but I am not able to change the text color.

**Comment by eldojoseph** [comment]
@tabladrum, can you help?

**Comment by eldojoseph** [comment]
@tabladrum any luck?

**Comment by mrpudn** [comment]
You'll have to be more specific. Where are you trying to change the text?

It should be a matter of adding this to the desired element in your LESS files:
```less
// ...
color: #123456;
// ...
```

**Comment by eldojoseph** [comment]
Thank you @mrpudn. I am trying to modify text color for all widgets using.

**Comment by eldojoseph** [comment]
I will try this option and let you know.

**Comment by eldojoseph** [comment]
@mrpudn I tried updating less file under UI\src\components\widgets but still no changes I could see. One of the example where I am trying to make change is - "Build" widget and text "BUILDS PER DAY"

**Comment by mrpudn** [comment]
@eldojoseph let me know if you've resolved this

**Comment by eldojoseph** [comment]
Nope. We are still struggling.

**Comment by eldojoseph** [comment]
Nope. We are still struggling.

**Comment by mrpudn** [comment]
I believe you're looking for the `buildsPerDay` directive:
https://github.com/capitalone/Hygieia/blob/master/UI/src/components/widgets/build/directives/buildsPerDay.html

**Comment by nireeshT** [comment]
@eldojoseph  - try adding color attribute in UI/src/app/css/common.less

widget-body .widget {
        padding: 0;

        .widget-heading {
            border-bottom-color: @dash-widget-sub-heading-border;
            .text-standard;
            **color:red;**
            text-transform: uppercase;
        }
    }

* Please reopen the issue if it did not fix it.

**Comment by eldojoseph** [comment]
@nireeshT It worked fine for widget headings. but I need to update the color for all the texts highlighted in the image.
![pasted image 0](https://cloud.githubusercontent.com/assets/20114565/22156011/7e85171e-deff-11e6-9eb1-c506f2d994f3.png)
