### ISSUE TITLE
Product dashboard displays NaN for Security Issues

### ISSUE THREAD

**Issue by sanjeevnewt** [capitalone/Hygieia#881]
@tabladrum Product dashboard displays NaN for security issues, if 'blocker' issues contain empty string, though 'critical' or 'major' issues types have non Zero values. The graph for security issues also displays nothing in such cases, if 'blocker' issues have a zero value.

Possible cause might be usage of parseInt in /Hygieia/UI/src/components/widgets/product/js/security-analysis-data.js, which returns NaN for empty string.

Line 68 : blocker: parseInt(getCaMetric(metrics, 'blocker'))

**Comment by nireeshT** [comment]
@sanjeevnewt  - can you paste a screenshot for this issue.

**Comment by nireeshT** [comment]
@sanjeevnewt  update to latest codebase and reopen with screenshot and error log if still an issue.
