### ISSUE TITLE
Publish sonar results using hygieia-jenkins-plugin

### ISSUE THREAD

**Issue by summit123** [capitalone/Hygieia#882]
Hi, I am getting the following output while trying to publish sonar results to hygieia. It says nothing to publish. Sonar analysis runs successfully in Jenkins. Sonarqube version is 5.6.1.

Hygieia: Published Build Complete Data. Response Code: 201. Response Value= 57f25ff746e0fb000e7a5e98
Hygieia: Published Sonar Result. Nothing to publish

Any help is appreciated!! Thanks

**Comment by tabladrum** [comment]
@rohans84 can you check?

**Comment by summit123** [comment]
@tabladrum anyone else that can assist with this?

Thanks!!

**Comment by summit123** [comment]
Closed by mistake. Reopening
