### ISSUE TITLE
private github repository not showing up on Hygieia dashboard

### ISSUE THREAD

**Issue by anchatho** [capitalone/Hygieia#883]
Hi,

Our organization has its own github repository  - github.<companyname>.com 

When we try to configure the same using github properties file with the below value it is not showing anything. 

Normal github.com/projectname can be accessible as it is public.

**github.host=https://<token>8de6fcfdd0a6@github.company.com/<username>/demo.git**

In general in the collector log **we see 401 error**.  when we try to access the above **URL it redirects to organization SSO page.** 

Is there any suggestion on this.

**Comment by satishc1** [comment]
@anchatho Refer to http://www.capitalone.io/Hygieia/githubsourcecode_collector.html . It shows a sample properties file with github.com

**Comment by anchatho** [comment]
We have been referring to the same application.properties file and trying.  
This morning also after lot of research we have created personal tokens and tried with the below parameter in the **application.properies** file

**github.host= https://github.company.com
github.UserId=username
github.key=ebxxxxxxxxxxxxxxxxxxxxdea33fe7f**

**The output we get is ERROR c.c.d.collector.DefaultGitHubClient - 401 Unauthorized:https://github.org.com/api/v3/repos/username/hello/commits?sha=master&since=2016-10-06T11:39Z**

**Comment by satishc1** [comment]
@anchatho Refer to the "Encryption for private repos" section in the UI module readme.

**Comment by anchatho** [comment]
Based on one of the suggestion referenced the UI readme file section in the  Encryption for private repos

 

Following the below step have generated a secret key and updated the respective properties file. Look like this also did not help..


1. From module core generate a secret key.
java -jar <path-to-jar>/core-2.0.2-SNAPSHOT.jar com.capitalone.dashboard.util.Encryption


2. Add this generated key to api.properties
### api.properties
key=<your-generated-key>


3. Add the same key to your repo settings file.
This is needed for the target collector to decrypt your saved repo password.
For example, if your repo is github add the following.
### github.properties
github.key=<your-generated-key>

 

2016-10-12 14:06:03,501 ERROR c.c.d.collector.DefaultGitHubClient - 401 Unauthorized:https://github.org.com/api/v3/repos/<userdetails>/<reponame>/commits?sha=master&since=2016-10-12T13:56Z
