### ISSUE TITLE
Hygieia Publisher (Jenkins Plugin), which post action build use?

### ISSUE THREAD

**Issue by oshingc** [capitalone/Hygieia#884]
Hi team,
I'd like to know which Post Action Build is needed to configure Hygieia Jenkins plugin.

Here an image of what i've got so far, does this error is printed because the post action build wasn't configured yet?

![pkghf](https://cloud.githubusercontent.com/assets/3100819/19082919/ba97e936-8a25-11e6-92c8-9aa27440f8dd.png)

Thanks in advance!

Ale from Peru

**Comment by tabladrum** [comment]
This is the global Jenkins settings. Please click "Apply" and then "Test Connection".

**Comment by oshingc** [comment]
Great, test connection works.
![Uploading test.png…]()

Where can I find the option for adding a Post build action "Hygieia Publisher" please?

**Comment by tabladrum** [comment]
Go to the job config page. There should be a Post Build action "Hygieia Publisher" in the drop down.

![image](https://cloud.githubusercontent.com/assets/6014941/19084222/a320e7e0-8a33-11e6-8efc-53d6e5b43c30.png)

**Comment by oshingc** [comment]
Good!
I have Hygieia Jenkins Plugin congured as the following image:
![hygieia plugins](https://cloud.githubusercontent.com/assets/3100819/19095698/e90d1b38-8a5c-11e6-9f2e-b5a0c4f91f34.png)

But on the Team Dashboard from Deployment Collector I don't have any option...
![dash](https://cloud.githubusercontent.com/assets/3100819/19095720/10c55fdc-8a5d-11e6-8e8c-a7697cb66b19.png)

**Comment by oshingc** [comment]
Any update?

**Comment by tabladrum** [comment]
@oshingc for deployment, use the "Publish Deployment Results".
If you have a single job that does ALL (buid, sonar, test, deploy) then click all of them and enter the necessary information.

**Comment by oshingc** [comment]
I created a job in my jenkins with Hygieia Publisher (Jenkins Plugin) per each stage Dev, Qa, Int, Perf, Prod (So I have 5 jobs created) 
![dash2_1](https://cloud.githubusercontent.com/assets/3100819/19445700/1383efc4-945b-11e6-8c16-764a2cc7491a.png)

This allowed me to see an option in Deploy Widget:

![dash2_2](https://cloud.githubusercontent.com/assets/3100819/19445758/49d71682-945b-11e6-8cd4-bd390ca18266.png)

And that will create the stages on deploy widget:

![dash2_3](https://cloud.githubusercontent.com/assets/3100819/19445856/a8c01efa-945b-11e6-9d9c-e89d03a8c01c.png)


NowiIn Pipeline Tab is possible to configure Delivery Pipeline:
![dash2_4](https://cloud.githubusercontent.com/assets/3100819/19445911/ee7eb186-945b-11e6-843b-6db4ddeb3c4c.png)

And see the Pipeline:

![dash2_5](https://cloud.githubusercontent.com/assets/3100819/19445926/facdc300-945b-11e6-954e-71a33d416274.png)

Thanks Hygieia Team!

Ale from Peru

**Comment by anjana83** [comment]
Hi Oshingc.. 
As you have mentioned above that you have created 5 diff jobs for dev, qa, perf etc. Can I know.. what are those jobs about? is that for build project and deployment as well

**Comment by shilpsl1** [comment]
Hi,
I am facing issue in Product Dashboard. I can see pipeline view but nothing comes up in product dashboard environment.
Posted issue in https://github.com/capitalone/Hygieia/issues/1165
Could you please help me if you know any solution. Thanks!!!

**Comment by smsuresh** [comment]
It works for me, Thankyou!

**Comment by shilpsl1** [comment]
@smsuresh
we are not able to view environment pipeline in Product Dashboard, that is the issue we are facing. how did you fix it ? below is the screen shot of Product Dashboard.
![5ef23e3a5373d0d3](https://cloud.githubusercontent.com/assets/24657895/23068881/5a7b2b42-f4f3-11e6-99b2-313b43f6bdef.jpg)
![7059b5b1d356b53c](https://cloud.githubusercontent.com/assets/24657895/23068884/5cfea588-f4f3-11e6-89df-6e42c9888b85.jpg)

**Comment by smsuresh** [comment]
@shilpsl1  Sorry , I was referring to Deploy widget & Pipeline  not product dashboard,
for product dashboard even I've the same issue.
I believe that work is still in-progress.. not sure

**Comment by suppu07** [comment]
were can i download hygieia -jenkins plugin .. i am not able to find it can anyone help me put ?

**Comment by nireeshT** [comment]
@suppu07  follow https://github.com/capitalone/Hygieia/tree/master/hygieia-jenkins-plugin to build hpi file and install in jenkins.

**Comment by suppu07** [comment]
@nireeshT thank you for update .. it was available in the package .. here i find issue in Hygieia UI
logs are running fine but metrics are not seen in dashboard... only the build time is seen at top.. 
![image](https://user-images.githubusercontent.com/26898581/28202068-5d73700e-6891-11e7-9a46-01f5b8dd0202.png)

**Comment by suppu07** [comment]
and m posting my jenkins -hygieia configuration

![image](https://user-images.githubusercontent.com/26898581/28202190-dcad778e-6891-11e7-90ba-cd0d61927085.png)

![image](https://user-images.githubusercontent.com/26898581/28202251-1b959602-6892-11e7-86f3-0591488c40ba.png)
