### ISSUE TITLE
Steps for creating Custom Collector

### ISSUE THREAD

**Issue by JayanthiKandasamy** [capitalone/Hygieia#885]
HI., I am very new to Hygieia. I need to create customer collector for my customized organization Tool .
Please let me know the steps from scratch ,if possible share sample projects if any.

Thanks

**Comment by satishc1** [comment]
@JayanthiKandasamy  Go to http://capitalone.io/Hygieia/ and browse the Getting Started section and the Collectors section links on the top and let us know if you have any problems.

**Comment by monabhardwaj** [comment]
Hello! I'm new to Hygieia and currently attempting to create a custom github collector. I have gone through various articles on the same but weren't of much help on the beginner level. It would be invaluable for me if could extend any advice or sample projects on how you got your custom collector working. @JayanthiKandasamy @satishc1 
Thank You!
