### ISSUE TITLE
OS Requirements

### ISSUE THREAD

**Issue by ankitgupta07** [capitalone/Hygieia#886]
Is there any recommended configuration install/configure Hygieia. While setting it up on CentOS 7, I ran into npm dependency issues and could not have the UI up and running. But while setting it up on Windows OS, I could setup Hygieia without any issues.

Could you please confirm if there are any recommendations. I would prefer to run this on a Linux box and therefore want to confirm.

**Comment by amitmawkin** [comment]
@ankitgupta07 you need to make sure that npm can access internet for downloading node modules.

**Comment by mrpudn** [comment]
We've had success running Hygieia on CentOS-based Linux distros.

If you're behind a corporate proxy, I'd look into @amitmawkin's suggestion.

**Comment by satishc1** [comment]
https://github.com/capitalone/Hygieia/issues/805
https://github.com/capitalone/Hygieia/issues/753
