### ISSUE TITLE
Request: remove Maven files

### ISSUE THREAD

**Issue by bodiam** [capitalone/Hygieia#89]
Hi all,

Right now, the Hygieia code is using two build tools, Maven and Gradle, and I find it a bit confusing to know which one to use. The current documentation is just as confusing, since some of the documentation (for example, the main documentation) talks about Gradle, but the documentation of the sub projects talk about Maven. 

I can do a pull request, that's fine, but I'd like to know the general sentiment about getting rid of the Maven code.

**Comment by amitmawkin** [comment]
We removed the maven code, but some developers were not comfortable with Maven, hence we decided to put it back,  I will add instructions on main Readme for building via Maven, they were there if you look at the commit history , but were updated for gradle

**Comment by bodiam** [comment]
Were there specific reasons why they were not comfortable with Gradle? Doing a `mvn clean install` or `gradle build` can hardly be the reason right?

We are experimenting with Hygieia too, and I don't care which build tool you use, but some of my colleagues are adding features, and are updating the pom. I use the Gradle version, and of course we run into the problems that only the pom.xml is updated. Also, right now the documentation is inconsistent: the main documentation talks about Gradle, while (some of?) the sub projects talk about Maven. Confusing at best, but it will make contributions a lot harder in regard for writing features and documentation.

I'm trying to make a point here to just have one build tool and deal with it :-). If it's Maven, fine, if it's Gradle, better, but having two is the worst scenario IMO.

I would just remove everything from Maven, and just add some clear documentation about Gradle. That's what I will also do for our local fork.

**Comment by srid99** [comment]
:+1: for removing Maven

Recently I had some problems (got NoSuchMethodError exceptions) with running the application from my IDE (IntelliJ) on analyzing the issue noticed that there were some mismatch with Spring versions. And understood that the actual cause for the issue is by mistake I enabled Gradle support (stupid mistake from my side). So all dependencies are added twice (from Maven and Gradle) and they are not in sync. To avoid such confusions and for maintenance sake, we should just stick with one build tool.

I prefer Gradle.

**Comment by tabladrum** [comment]
I want to get Gradle working too and stay with one single build system. Want to make sure that everything works seamlessly irrespective of IDE used (Eclipse, IntelliJ etc). Command line worked great. Working through some issues with Eclipse setup. Once this is done, will switch to ONE build system.

**Comment by tabladrum** [comment]
Heads up: We will be staying with Maven. I will do a PR within 24 hrs to clean up and making all documents consistent.

**Comment by bodiam** [comment]
@tabladrum thanks for the update. Any specific reason why Maven? Any issues you are running into when using Gradle?

**Comment by tabladrum** [comment]
Moved back to Maven. @bodiam We will still look to resolve the issues we had with gradle. 

Main issue we ran into was a good way to pass in Environment variable in the command line (gradlew).
Any help will be appreciated.

**Comment by bodiam** [comment]
Okay, good to hear a choice has been made for now.

Could you make an issue for the problem you had with Gradle? I don't mind looking into it.

**Comment by amitmawkin** [comment]
https://github.com/capitalone/Hygieia/issues/97 has been created, your cooperation is needed. We have also improved on documentation and now you can run api layer and UI from maven only , please check the documentation in Readme.md

Thanks

**Comment by dstine** [comment]
@tabladrum You noted:
> Main issue we ran into was a good way to pass in Environment variable in the command line (gradlew)

Can you provide more info or a more concrete example? I'm another potential helper who would would like to see a Gradle build.

**Comment by tabladrum** [comment]
Main issue: the API needs an environment variable DASHBOARD_PROP or a system variable dashboard.prop to be set to point to the properties file. 

Somehow this is not working with Gradlew command line. The API kept using default set hard coded in the API code. 

IDE issue with Eclipse: with gradle enabled, usual eclipse feature to run the API by context menu "Run on server" is no longer available. And running gradle task ran into the same issue with passing environment variable.

IDE issue with IntelliJ: same as passing the env variable via IntelliJ run config. Also tried with IntelliJ tomcat config - it overrides my machines Tomcat's setenv.sh ignoring any export I may have in there.

**Comment by jdamick** [comment]
please see my response to #97

**Comment by jdamick** [comment]
move to #97

**Comment by tabladrum** [comment]
Main issue: the API needs an environment variable DASHBOARD_PROP or a system variable dashboard.prop to be set to point to the properties file. 

Somehow this is not working with Gradlew command line. The API kept using default set hard coded in the API code. 

IDE issue with Eclipse: with gradle enabled, usual eclipse feature to run the API by context menu "Run on server" is no longer available. And running gradle task ran into the same issue with passing environment variable.

IDE issue with IntelliJ: same as passing the env variable via IntelliJ run config. Also tried with IntelliJ tomcat config - it overrides my machines Tomcat's setenv.sh ignoring any export I may have in there.
