### ISSUE TITLE
Global configuration?

### ISSUE THREAD

**Issue by MarkRx** [capitalone/Hygieia#890]
Is there a place where global system configurations live? The UI has the ability to configure themes but it doesn't seem this data is persisted.

I have a use case where I have a configuration that might effect multiple images (ui, api, and collectors). I need someplace common to store the configuration.

**Comment by MarkRx** [comment]
Examples:

- allowScmCredentials - if the UI should show the username/password fields for SCM
- allowAccountCreation - if account creation is allowed (for future LDAP hookup)
- globalTheme - the global theme

**Comment by mrpudn** [comment]
I always thought there should be a `/config` directory at the top-level of the project, which would contain all configuration for Hygieia.

There should be a `.dist` version for each config file (ex. `api.properties.dist`), which would be the "distributable" version of the configuration. You'd copy the dist version and remove the `.dist` to apply your custom configurations - these would all be `.gitignore`ed.

I'd rather have all configuration in one file (`hygieia.properties`), but I'm not sure how everyone would feel about that.

Thoughts?

**Comment by MarkRx** [comment]
How would that work when using docker? I wouldn't want properties to be handled at compile time.

I think for now I'm going to look into creating a rest service on the api that returns a bunch of configuration options that the UI makes use of when deciding how to render the views. The properties would be set in the api's application.properties file. The config is still static (needs to be compiled before running) but I'm not sure it would make sense for those properties that I mentioned in my use case to be dynamically configurable.

**Comment by mrpudn** [comment]
Yeah configuring docker containers is a little more complicated.. like you said, ideally configuration would be done at runtime, not compile time, so that you can have a generic image with specific configuration.

**Comment by MarkRx** [comment]
Threw in config skeleton as part of #891

**Comment by MarkRx** [comment]
Closing.
