### ISSUE TITLE
Cannot access api from UI 

### ISSUE THREAD

**Issue by preetcam** [capitalone/Hygieia#895]
Migrating my project from gulp to apache. I am able to successfully run my UI, but API’s are not getting called. I am getting 404 error, as the URL gets changed.
old gulp port for UI : 3000
New apache port for UI : 80
I haven’t changed any port in api. I ran my api jar. 

Project works fine if I run with gulp, but doesn’t work with apache. 
Please guide how api and UI are connected. 

<img width="1260" alt="screen shot 2016-10-10 at 3 55 18 pm" src="https://cloud.githubusercontent.com/assets/4131188/19253706/0025192a-8f02-11e6-87c8-98f4921b5974.png">

**Comment by satishc1** [comment]
@preetcam 
For the UI module set the proxypass directive in apache to point to wherever your api module is running.

ProxyPass /api http://localhost:8080/api

To find out where the api module is running ...
If you have logging set, you should see something like the following line when the api module is started up.
2016-10-07 15:20:29,037 INFO  o.s.b.c.e.t.TomcatEmbeddedServletContainer - Tomcat initialized with port(s): 8080 (http)

The above line will tell you the port number that the api runs on. Test it with the ping api..
http://localhost:8080/api/ping

**Comment by preetcam** [comment]
Thanks it works !!
