### ISSUE TITLE
Deploying Hygieia dashboard in Apache server

### ISSUE THREAD

**Issue by LokeshNewt** [capitalone/Hygieia#896]
Hi,

I am trying to deploy Hygieia dashboard in Apache server. Successfully run the API using the below command,
java -jar api.jar --spring.config.location=dashboard.properties

Copied all the UI/dist files to /var/www/html folder for the UI stuffs. Our requirement is to use apache server alone(not gulp) in the production environment. I hope gulp serve is the development web server. So, we dont't want to run gulp serve command in production.

Now the problem is, there is no connectivity between UI and the API. I am getting the below error when I am trying to signUp.

The requested URL /api/registerUser/ was not found on this server.

Please let me know how to fix this issue.

Thanks.

**Comment by satishc1** [comment]
@LokeshNewt Refer to https://github.com/capitalone/Hygieia/issues/895

**Comment by LokeshNewt** [comment]
Thanks..
