### ISSUE TITLE
JIRA instance for Hygieia Dashboard

### ISSUE THREAD

**Issue by anchatho** [capitalone/Hygieia#898]
Hi,

We are trying to setup the JIRA instance for Hygieia Dashboard.

In **JIRA** we have a defined **a new project of type Project Management process.**
Created multiple issue of type **STORY** and **TASKS** 

**In simple terms just wanted to know what gets displayed from JIRA into Hygieia Dashboard ?** 

Attached is the snapshot of the same we do not see anything except the message no iterations defined.
![jira_hygieia_display1](https://cloud.githubusercontent.com/assets/19856681/19345188/f3d595f4-915a-11e6-9141-c53f6eb69637.jpg)

**Comment by MarkRx** [comment]
There is a troubleshooting guide @ https://github.com/capitalone/Hygieia/tree/master/collectors/feature/jira. Jira will not function if it is not configured correctly.

At present it will show active sprints with the total number of story points (or hours), the number of story points or hours in progress, and the number done. It will also show the number of story points attached to epics in progress for the sprint. The scrum / kanban implementation isn't 100% and I am working on it now #678

**Comment by anchatho** [comment]
Mark- Thanks for making it clear.

**With the information I have started with JIRA by creating a Sprint  consisting of multiple Stories and Tasks.**

![jira_hygieia_sprint](https://cloud.githubusercontent.com/assets/19856681/19432614/01c9a6fa-947b-11e6-8fa8-cbdc5958ba20.jpg)

**When it comes to showing up in dashboard it shows the below status. Which I am unable to correlate.**  

![hygieia_jira_status](https://cloud.githubusercontent.com/assets/19856681/19432642/25451f38-947b-11e6-875d-b3b0c950e047.jpg)

Any suggestion would be of great help.

**Comment by satishc1** [comment]
@anchatho The feature widget now has an option to display metrics based on the number of tickets instead of estimates. This is for setups that do not use estimates.
Functionality merged in https://github.com/capitalone/Hygieia/pull/1054 Use latest codebase. You’ll also need to follow cleanup instructions provided in https://github.com/capitalone/Hygieia/pull/1137
