### ISSUE TITLE
Need help 

### ISSUE THREAD

**Issue by anurag111527** [capitalone/Hygieia#900]
Hello, I am trying to get familiar with Hygieia. I would not like to use a local host rather I would like to use a seperate host name. I made those changes in in api at applications.properties. api works fine and also my jenkins build collecter works fine. But when run a java -jar command on the other collecters, I get:
```
2016-10-14 13:43:11,036 INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 5.1.3.Final
2016-10-14 13:43:12,041 INFO  o.s.s.c.ThreadPoolTaskScheduler - Initializing ExecutorService  'taskScheduler'
2016-10-14 13:43:12,160 INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: localhost:27017
2016-10-14 13:43:12,340 INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
```
what I am looking is to connect a hostname of my choice rather than default (localhost).
can anyone help how to make the change?
TIA

**Comment by mrpudn** [comment]
To use a different database host, you'll have to change the `dbhost` property in your collector's `application.properties`.

**Comment by anurag111527** [comment]
Thank you for responding to my email. I have changed the dbhost properties
in 3 different locations(application.properties, collecter
name->target->classes->application.properties and the other one is at
collector level. When I run the java -jar command it connects to local
host. Is there another location where we can specify ?

**Comment by mrpudn** [comment]
The collector should read from its `src/main/resources/application.properties` file - you can try changing the `dbhost` property there. If it doesn't exist, you should be able to create it based on the example in the collector's `README.md`.

**Comment by anurag111527** [comment]
Thank you once again. I changed the property from there too. It Did not
help. One thing I noticed is in core you have a Mongodb.java where the host
parameters is assigned with local host. Currently I don't have access to
the system on which I have the logs.

Thanks

**Comment by mrpudn** [comment]
@tabladrum you should be able to change the db host from `localhost` to something else by changing the collector's `application.properties` file, right?

It doesn't seem to be working for @anurag111527 - I'll look further into it

**Comment by MarkRx** [comment]
It works for non localhost. Try passing in --spring.config.location to point to your application.properties file


> set DEFAULT_JVM_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5011
> java %DEFAULT_JVM_OPTS% -jar "C:/vagrant/hygieia/hygieia/collectors/deploy/xldeploy/target/xldeploy-deployment-collector-2.0.4-SNAPSHOT.jar" --spring.config.location="C:/vagrant/hygieia/xld-windows.properties"

**Comment by anurag111527** [comment]
Thankyou once again. I tried this. I pointed --spring.config.location=full/path/to/appliation.properties and also passed --spring.config.name==full/path/to/appliation. This dint work either :(. Much appreciate your help!!

**Comment by tabladrum** [comment]
Please paste your properties file.

**Comment by anurag111527** [comment]
spring.data.mongodb.database=dashboard

#Database HostName - default is localhost
spring.data.mongodb.host=localhost

#Database Port - default is 27017
spring.data.mongodb.port=27017

#Database Username - default is blank
spring.data.mongodb.username=HYGIEIA

#Database Password - default is blank
spring.data.mongodb.password=hygieia123
#Collector schedule (required)
git.cron=0 * * * * *

#mandatory
#git.host=bitbucket.org/
git.host=stash.XX.XXX.XXX

#mandatory
#git.api=/!api/2.0/repositories/
git.api=/rest/api/1.0/

**Comment by oshingc** [comment]
@anurag111527 
Can you try adding this field?
git.product=server

**Comment by MarkRx** [comment]
@anurag111527 it looks like that documentation is out of date. Look at https://github.com/capitalone/Hygieia/blob/master/collectors/scm/bitbucket/docker/bitbucket-properties-builder.sh for what generates the properties file for docker.

> #Database Name
> dbname=${HYGIEIA_API_ENV_SPRING_DATA_MONGODB_DATABASE:-dashboard}
> #Database HostName - default is localhost
> dbhost=${MONGODB_HOST:-10.0.1.1}
> #Database Port - default is 27017
> dbport=${MONGODB_PORT:-27017}
> #Database Username - default is blank
> dbusername=${HYGIEIA_API_ENV_SPRING_DATA_MONGODB_USERNAME:-db}
> #Database Password - default is blank
> dbpassword=${HYGIEIA_API_ENV_SPRING_DATA_MONGODB_PASSWORD:-dbpass}

**Comment by oshingc** [comment]
What does work for just a properties file?

**Comment by anurag111527** [comment]
Thanks everyone for your support. Due to some reasons our team chose to use localhost.
