### ISSUE TITLE
password based authentication for SONAR

### ISSUE THREAD

**Issue by smsuresh** [capitalone/Hygieia#905]
I took the latest HYgieia from github,
but cudnt connect to SONAR using password.

Do we have a password based connection to SONAR, from hygieia?
    - If not, what is the alternative way to connect?  -- Please help

**Comment by satishc1** [comment]
@smsuresh Did you add these two to the sonar.properties file ?
sonar.username=
sonar.password=

**Comment by smsuresh** [comment]
Yes Sathish !

Suresh.S

Sent from Yahoo Mail on Android 
 
  On Fri, Nov 4, 2016 at 6:17 AM, satishc1<notifications@github.com> wrote:   
@smsuresh Did you add these two to the sonar.properties file ?
sonar.username=
sonar.password=

**Comment by satishc1** [comment]
@smsuresh What are you seeing in the sonar collector log ? If the collector is not working, 
you could also try using the hygieia publisher plugin from Jenkins. It has an option to publish the sonar analysis. You will need to add the SonarQube server in the main configuration and provide a server authentication token.

**Comment by satishc1** [comment]
@smsuresh assuming the password based authentication is working. Looks like you have one more issue in regards to gathering the data https://github.com/capitalone/Hygieia/issues/945
