### ISSUE TITLE
password based authentication for Jenkins

### ISSUE THREAD

**Issue by smsuresh** [capitalone/Hygieia#906]
I recently update hygieia from github

How can I connect t Jenkins server which will require password based authentication.. -- PLease help

**Comment by MarkRx** [comment]
You need to generate API keys and use that as the password

**Comment by satishc1** [comment]
@smsuresh Look at the sample properties file in http://www.capitalone.io/Hygieia/jenkinsbuild_collector.html

**Comment by taozi34** [comment]
@MarkRx 
I not found the Jenkins api keys,how generate it?
Thanks a lot!

**Comment by taozi34** [comment]
@MarkRx 
got it .thanks
