### ISSUE TITLE
Unauthorized: access issue while connecting to private github repository 

### ISSUE THREAD

**Issue by anchatho** [capitalone/Hygieia#908]
Based on the suggestion referenced the UI readme file section in the Encryption for private repos

Following the below step have generated a secret key and updated the respective properties file. Look like this also did not help..

From module core generate a secret key.
```bash
java -jar /core-2.0.2-SNAPSHOT.jar com.capitalone.dashboard.util.Encryption
```

Add this generated key to api.properties
```properties
    key=

    Add the same key to your repo settings file.
    This is needed for the target collector to decrypt your saved repo password.
    For example, if your repo is github add the following.
    github.properties

    github.key=
```
```
2016-10-12 14:06:03,501 ERROR c.c.d.collector.DefaultGitHubClient - 401 Unauthorized:https://github.org.com/api/v3/repos///commits?sha=master&since=2016-10-12T13:56Z
```
Note: Manually when we try to connect via api using browser it show the below output.

API URL :- https://github.org.com/api/v3/repos/<userid>/<reponame>/commits?access_token=<tokenname>
```json
[
  {
    "sha": "019d4ba39025bfb56c7b6fdc717bf283484347",
    "commit": {
      "author": {
        "name": "username",
        "email": "email address",
        "date": "2016-10-12T09:08:20Z"
      },
      "committer": {
        "name": "GitHub Enterprise",
        "email": "noreply@github.org.com",
        "date": "2016-10-12T09:08:20Z"
      },
      "message": "Update README",
      "tree": {
        "sha": "019d4ba39025bfb56c7b6fdc717bf283484347",
        "url": "https://github.org.com/api/v3/repos/<userid>/<reponame>/git/trees/019d4ba39025bfb56c7b6fdc717bf283484347"
      },
      "url": "https://github.org.com/api/v3/repos/<userid>/<reponame>/git/commits/019d4ba39025bfb56c7b6fdc717bf283484347",
      "comment_count": 0
    },
```

**Comment by satishc1** [comment]
@anchatho Did you save the credentials ? 
![picture1](https://cloud.githubusercontent.com/assets/21199084/19563428/e6afdd00-96ad-11e6-9c15-59f77c1bb486.png)

**Comment by anchatho** [comment]
Hope this is new code for me credentials window do not show up only Repo Type, Repo URL and Branch show up here.

**Comment by satishc1** [comment]
@anchatho Yes.. this code was merged in https://github.com/capitalone/Hygieia/pull/835
Download the new codebase then Refer to the "Encryption for private repos" section in the UI module readme. Reopen if it doesn't work after doing this.
