### ISSUE TITLE
how to change username

### ISSUE THREAD

**Issue by anurag111527** [capitalone/Hygieia#909]
Hello everyone!! I created a user and have been using the same name for most of the time.  I would like to change the username(and password if possible) so that the details can be shared between the team. Please suggest how do I do that?
TIA!!

**Comment by mrpudn** [comment]
I don't believe there's a way to do this via the UI.

You can use the `mongo` shell to modify users - just connect to the database and modify the user in the `authentication` collection.

Users look like this:
```
{
	"_id" : ObjectId("..."),
	"_class" : "com.capitalone.dashboard.model.Authentication",
	"username" : "...",
	"password" : "..."
}
```

**Comment by satishc1** [comment]
@anurag111527 @mrpudn As suggested above you could change the username via mongo shell or using a client like RoboMongo. For the password, you could create a new account with the password you want, then replace the existing one with the hash of the new one.

**Comment by anurag111527** [comment]
I dint quiet understand. When I sign up in Hygiea dashboard, where would the login credentials be stored. And also if I would liketo see how many  users have signed up, where can I see that information.
Thanks

**Comment by anurag111527** [comment]
I dint quiet understand. When I sign up in Hygiea dashboard, where would the login credentials be stored. And also if I would liketo see how many  users have signed up, where can I see that information.
#909
Thanks

**Comment by mrpudn** [comment]
Login credentials are stored in the `authentication` collection in MongoDB.

You can list the number of users from the `mongo` shell:
```
db.authentication.count()
```

**Comment by anurag111527** [comment]
thankyou for your swift response. I tried to do that using mongo shell and I get "0"

**Comment by mrpudn** [comment]
Yup, so you have 11 users in your database :)

**Comment by anurag111527** [comment]
yes. I tried using db.getUsers() and it gives me only 2 users on that db. is there any other way that I can get the list of the other user. 
Thanks!!

**Comment by mrpudn** [comment]
`db.getUsers()` will give you the **MongoDB** users.
`db.authentication.find()` will give you the **Hygieia** users.

**Comment by anurag111527** [comment]
Thankyou!!!  I will try that and any command to get a list of uers please?

**Comment by mrpudn** [comment]
The `mongo` shell is actually a JavaScript shell, so you can do things like:
```js
> var users = db.authentication.find()

// print the first user
> users[0]

// print the user count:
> users.length()

// print each user's username
> for (var i = 0; i < users.length(); i++) { print(users[i].username); }
```

**Comment by anurag111527** [comment]
excellent!!  and i hope we(admin) can edit the users and change passwords?

**Comment by mrpudn** [comment]
If you have access to the database, you can do whatever you want to :)

**Comment by anurag111527** [comment]
wonderful!! thanks for your vluable help  (Y)

**Comment by anurag111527** [comment]
How to view them or list them. I tried using db.getUser().. but dint list
all 11 users. Is there any other command. Thanks
