### ISSUE TITLE
TFS Collector

### ISSUE THREAD

**Issue by campbellgunn** [capitalone/Hygieia#91]
Is it possible to do a TFS collector? I know that there is a Java SDK for TFS found here http://blogs.msdn.com/b/bharry/archive/2011/05/16/announcing-a-java-sdk-for-tfs.aspx

Not sure if anyone has done this before?
Is it something that can be added to this repo?

Thanks.

**Comment by campbellgunn** [comment]
Correction on the URL it is now located here - http://www.microsoft.com/en-us/download/details.aspx?id=47727.

**Comment by amitmawkin** [comment]
You can write it any language you want to, java would be nicer as it would fit in the ecosystem as well as follow same model and the collectors are platform neutral. I have not yet seen any pull request or anybody committing on this.

**Comment by tabladrum** [comment]
@campbellgunn I am not familiar with TFS. What data are you planning to collect? Features/Stories, Code Commits, Build etc?
If there is an SDK or API, it is easy to write a collector.

**Comment by campbellgunn** [comment]
yes, that is exactly what I need to do.

**Comment by tabladrum** [comment]
Visual Studio REST API reference: https://www.visualstudio.com/integrate/api/overview

**Comment by deepakasa** [comment]
Any updates on TFS collector is anyone working on this?

**Comment by vijayct2001** [comment]
Please let me know if any one done TFS collector?

**Comment by Sbrenthughes** [comment]
Please reopen if this is still a valid issue.

**Comment by jagnathan** [comment]
Any update on TFS collector? Has anyone successfully implemented it?

**Comment by mohitsinghal83** [comment]
Any update on TFS collector? I can't find any reference to TFS Collector in pending PR and branch.

I can see a comment in repo and build widget on TFS as a possible collector. 

https://github.com/capitalone/Hygieia/blob/5df7c9f293035b421d744b6e9aab21d09992a42d/core/src/main/java/com/capitalone/dashboard/model/Build.java

https://github.com/capitalone/Hygieia/blob/d6f7a6384c180280a818db29ded7db25f4db0a8c/core/src/main/java/com/capitalone/dashboard/model/Commit.java

**Comment by JULIANCHO923** [comment]
Hello, any updates on TFS collector? thanks

**Comment by sanojdev89** [comment]
I have created tfs collector for hygiea dashboard.for any queries pls get in touch.

**Comment by JULIANCHO923** [comment]
> I have created tfs collector for hygiea dashboard.for any queries pls get in touch.

my email is julianhenao92@gmail.com. Can you tell me more about that?? thanks you

**Comment by Sbrenthughes** [comment]
@sanojdev89  Can you contribute this back?

**Comment by JULIANCHO923** [comment]
> I have created tfs collector for hygiea dashboard.for any queries pls get in touch.

Hello @sanojdev89, could you share your code with the community?
Best Regards

**Comment by sharnal** [comment]
Hello @sanojdev89  yes please refer to appropriate reference on the TFS collector. Thanks.

**Comment by cod3braker** [comment]
Hi @sanojdev89 , can you help me out over the TFS collector. Please reach out to cod3braker@gmail.com. Thanks.
