### ISSUE TITLE
Purpose of Scope repository

### ISSUE THREAD

**Issue by pxk5958** [capitalone/Hygieia#914]
Versionone collector collects team data into ScopeOwner repository and project data into Scope repository; Jira collector, on the other hand, collects project data into both ScopeOwner and Scope repository for now. From what I understand, ScopeOwner corresponds to team and Scope corresponds to project. The feature plugin in the UI categorizes based on ScopeOwner (teams). So what is the Scope repository to be used for?

**Comment by rob-miller-777** [comment]
I've actually been wondering the same thing. Been building a feature collector for gitlab issue boards, and I can't seem to figure out the purpose of the scope repository.

**Comment by tabladrum** [comment]
I am taking another look at it right now for a different reason. I think the scope collection may be very specific for VersionOne. Will confirm.

**Comment by pxk5958** [comment]
@tabladrum Versionone stores project information in Scope repository but doesn't use it.

@rob-miller-777 It'll be of use soon. We're working on Jira collector collecting actual project information in Scope repository and letting the feature widget be configurable by Scope repository as well as the ScopeOwner repository.

**Comment by tabladrum** [comment]
Not sure if @amp5208 still is watching this repo. @amp5208 ?

**Comment by amitmawkin** [comment]
@MarkRx @pxk5958 @tabladrum I am forming a view that we need to separate widgtes in UI for VersionOne and Jira. Our goal always have been for UI to have a tool agnostic domain model , looks like with Jira and Version One it might not be possible. 

thoughts?

**Comment by pxk5958** [comment]
@amitmawkin Currently, we have been able to add new features as well in a tool agnostic manner. They both have projects, teams, sprints, issues/stories and epics right? Is there anything specific I am missing that made you form that view?

**Comment by tabladrum** [comment]
Lets  stick to tool agnostic nature of Hygieia.

**Comment by MarkRx** [comment]
I'm not too worried about the UI as the differences between the two are minimal. Should they become a painpoint then it could be addressed then.

**Comment by amitmawkin** [comment]
@pxk5958 it will still be same in UI, just separation from different widgets. if you look at how each widget is currently , scopes was one thing which based on your definition above could be different for v1 and jira, definition of scope for V1 is given here https://community.versionone.com/VersionOne_Connect/Developer_Library/Getting_Started/Platform_Concepts/Attribute_Definition_Syntax

**Comment by amitmawkin** [comment]
@MarkRx  do you guys use both VersioOne and Jira ..?

**Comment by MarkRx** [comment]
Nope just jira.

**Comment by amitmawkin** [comment]
We use both , was just wondering one could potentially affect other. As you would not have access to test Versionone.

**Comment by satishc1** [comment]
@pxk5958 Based on the discussions in https://github.com/capitalone/Hygieia/pull/1030 We've tried to cleanup some of this in https://github.com/capitalone/Hygieia/pull/1137 . Team now has its own collection and Scope is for project. The UI has also been cleaned up along the same lines. To use https://github.com/capitalone/Hygieia/pull/1137 you'll need to follow the cleanup instructions provided in it.
