### ISSUE TITLE
Corporate Contributor License Grant

### ISSUE THREAD

**Issue by Bradmoon** [capitalone/Hygieia#919]
i am trying to get our company to contribute and use this product which requires a CLA to be signed.   However, the CLA link in the doc appears to point to a CLA geared toward an individual.  the individual CLA does reference a `Corporate Contributor License Grant`, but i have been unable to locate it.    any help would be appreciated.

**Comment by amitmawkin** [comment]
Brad,
Work in Progress, It is pending CapitalOne legal team approval, @jaredsmith  @tabladrum   are on top of it . More to come soon.

**Comment by Bradmoon** [comment]
thanks amit, any suggestions on how we have our team make these contributions as i don't think it'll be an option for each individual to sign off.

**Comment by jaredsmith** [comment]
@Bradmoon We hope to have the Corporate Contributor License Agreement in place in the next week or so -- unfortunately, there's not much else we can do until that's been approved by our legal team, unless you want to have a few people sign the individual CLA until the Corporate CLA is approved.

**Comment by Bradmoon** [comment]
while we wait for `Corporate Contributor License Agreement`, i have asked for two of my folks to sign and submit pull requests for a couple minor features/fixes.   thanks.

**Comment by jaredsmith** [comment]
Thanks @Bradmoon.  We are making progress internally on the Corporate CLA front, but I don't yet have anything to show for it publicly.  In the meantime, we'll try to act quickly on the pull requests from your team.

**Comment by Bradmoon** [comment]
we're still signing individual CLA's and contributing under those.  we've submitted the following pr's through these individual CLA's: 

- https://github.com/capitalone/Hygieia/pull/923
- https://github.com/capitalone/Hygieia/pull/924
- https://github.com/capitalone/Hygieia/pull/936

we have a couple more enhancements, but if you think Corp CLA is coming quickly, i'd hold on those.  

really like the product you folks have here.  let me know on the corp CLA

**Comment by jaredsmith** [comment]
Just a quick status update on the Corporate CLA -- it's been approved by our legal team, and we're setting up the online form for you to be able to sign it.  We should have it up and running by the end of next week at the very latest.

**Comment by Bradmoon** [comment]
any word on how the Corporate CLA is progressing?

**Comment by Bradmoon** [comment]
Any word on this?

**Comment by jaredsmith** [comment]
You can sign the Corporate CLA here... We're currently using a Google Form to collect the information.  I'll be adding this to the README.md file shortly.

https://docs.google.com/forms/d/e/1FAIpQLSeAbobIPLCVZD_ccgtMWBDAcN68oqbAJBQyDTSAQ1AkYuCp_g/viewform?usp=send_form

**Comment by jaredsmith** [comment]
OK, the link has been added to README.md in pull request #1000.  Closing this issue, but please feel free to reach back out if you have any questions or concerns!

Thanks!
