### ISSUE TITLE
git hub widget not showing data.. git hub collector runs fine inserted data in mongo db

### ISSUE THREAD

**Issue by rabarisanjay** [capitalone/Hygieia#926]
Hi,
I am able to run git hub collector properly and data is inserted in mongo db..
but I can not see commit details in github widget.. its not reflecting.

**Comment by tabladrum** [comment]
Can you paste any bowser console log?

**Comment by rabarisanjay** [comment]
Thanks @tabladrum for your response.
you need browser log ?

I am not sure of this 
1) application.properties file contain git hub related details..

the same details used for loading data from github to mongo db and showing data from mongo db to dashboard ?

**Comment by satishc1** [comment]
@rabarisanjay Use latest codebase. Reopen if still an issue.
