### ISSUE TITLE
Build Rally feature collector

### ISSUE THREAD

**Issue by gokulknewt** [capitalone/Hygieia#927]
Hi Team, 
I have noticed few comments from Hygieia forum.We are not sure how to build the rally collector with dashboard.To integrate the rally-feature-collector with dashboard, What are the configuration steps we suppose to make sure.Also we would like to know about initial setup to proceed our implementation.
Can you please provide the steps?

Thanks and Regards,
Gokul k

**Comment by mrpudn** [comment]
Hygieia does not yet support Rally - if you'd like to participate in developing it, see #950
