### ISSUE TITLE
Configuring Deploy Widget

### ISSUE THREAD

**Issue by princevijayakumar** [capitalone/Hygieia#930]
Hi Team,

I have configured the deploy widget successfully, currently, we are using 2 environments Dev and QA. 

a.) How to configure more than 2 environments in deploy widget .

b.) In Deploy widget we find two arrows(up & down) could you please explain us what value need to be populated , currently it shows us 0.

Please clarify .

Thanks in Advance .

![image](https://cloud.githubusercontent.com/assets/835620/20005817/4ee59fe6-a2ba-11e6-9502-a1ee6fe1994e.png)

**Comment by smsuresh** [comment]
PrinceVijay ,can you please help me for initial setup, unable to bring the api itself up, took latest & did build

**Comment by tabladrum** [comment]
@princevijayakumar are you using the Jenkins plugin?

**Comment by supremex1** [comment]
Hi @princevijayakumar It will be helpful if you would like to share the deploy widget configuration process in detail. Thank you.

**Comment by nireeshT** [comment]
@princevijayakumar  @supremex1 
a) if using Hygieia jenkins plugin, you can configure Post build actions for Jenkins job -> Configure -> Post build actions -> select Hygieia Publisher, for each Jenkins job specific to environment. This will help Hygieia plugin to push all the data to your dashboard. 
Check Publish Deployment Resulyts 
Check Deploy Start Status 
Application Name:  
Environment Name : Dev/Int/Perf/Prod/QA
Artifact Directory :  /<directory name>/
Artifact File Name Pattern : <artifactname>-<version>.jar
Atrifcat Group : details found in pom.xml
Artifact version : details found in pom.xml
b)  Up & down arrows specify the count of servers online/offline.

**Comment by satishc1** [comment]
@princevijayakumar Closed. Reopen if still an issue.

**Comment by lyndomiao** [comment]
@nireeshT the Up & down arrows in deploy widget specify the count of servers online/offline,but I dont understand what are the servers online/offline.Could u please explain this?

**Comment by lyndomiao** [comment]
@tabladrum the Up & down arrows in deploy widget specify the count of servers online/offline,but I dont understand what are the servers online/offline.Could u please explain this?
