### ISSUE TITLE
How Deploy Widget Functionality Works

### ISSUE THREAD

**Issue by princevijayakumar** [capitalone/Hygieia#934]
Hi Team,
            I have configured the Deploy widget in Hygieia dashboard. I couldn't find any deploy widget functional document or tutorial, It would be great if you share some document or URL for better understanding.

**Comment by tabladrum** [comment]
@princevijayakumar Are you using Jenkins plugin?

**Comment by princevijayakumar** [comment]
yes, i have configured the Jenkins plugin in Jenkins

**Comment by supremex1** [comment]
@princevijayakumar @tabladrum  Hi, I am also facing the same issue with configuring the deploy widget. What are the jobs Dev, Int are all about? Is it compulsory to create them all? Or any job with the post build action setting can do the job?

**Comment by princevijayakumar** [comment]
you should configure the post build action settings in jenkins(Hygieia publisher). 
Set Environment Name : DEV
Jenkins ->job->configure->Post-build-Actions->Publish Deployment Results->Environment Name: DEV

**Comment by supremex1** [comment]
@princevijayakumar  Yes, I have already set the environment name there but it is not displaying in the Hygieia db in Deploy widget config. Any pointers?

**Comment by satishc1** [comment]
Refer to https://github.com/capitalone/Hygieia/issues/1034 . Re-open if still an issue.
