### ISSUE TITLE
Configuring UrbanCode Parameters(DEV, QA) to Product Dashboard

### ISSUE THREAD

**Issue by princevijayakumar** [capitalone/Hygieia#935]
Hi Team,

I having configured Product Dashboard with DEV & QA. The build initiated from Urban code pass through Jenkins and finally reaches our Dashboard.

Is there any direct way to configure the parameters(DEV, QA) from Urban code to our Product Dashboard  , If so please assist us how to proceed further.

Thanks in Advance.

**Comment by tabladrum** [comment]
You can directly call the APIs from urbancode. Or use the udeploy collector. I am not sure why you needed to have Jenkins in the middle.

**Comment by princevijayakumar** [comment]
I have already configured Udeploy collector but could not retrieve the complete data from Urbancode REST API,  While doing analysis we found only partial data could be retrieved.

Please find the **URL** 
http://ip:8080/rest/deploy/environment/69ab4c65-c8d7-42c6-9d85-e3b72892bb18/noncompliantResources

**Response** : [] (Result was Empty)

so please assist us how to proceed further.

**Comment by nireeshT** [comment]
@princevijayakumar  Refer https://github.com/capitalone/Hygieia/issues/1084

**Comment by nitin1706** [comment]
please use above mentioned issue #1084 for updates on this.
