### ISSUE TITLE
explain the purpose of Pipeline Health Trends Up or Down arrows

### ISSUE THREAD

**Issue by princevijayakumar** [capitalone/Hygieia#937]
In Pipeline Health Trends we find Arrows(Up & Down) followed by percentage values. Could you please explain the purpose of Up and Down arrows and it's colors.

![image](https://cloud.githubusercontent.com/assets/835620/20137524/fe78a16c-a6a0-11e6-8f35-619da19fcc53.png)

**Comment by tabladrum** [comment]
The arrows are for showing trend. Up is going high. Down is going low. Some UPs are bad and hence colored red. Some DOWNs are good and hence colored green..
Green = good. Red = bad. Up = trending up in value (% or count etc). Down = trending down.

**Comment by princevijayakumar** [comment]
Thanks for your help
