### ISSUE TITLE
Customizable States for Feature / Jira Widget 

### ISSUE THREAD

**Issue by leahxu** [capitalone/Hygieia#939]
My company uses Jira with four different states: Blocked, To Do, In Progress, and Done. 
With the way that the feature widget is implemented, there are a lot of changes that must be made to display all 4 queues. Has anyone made modifications like this?

**Comment by MarkRx** [comment]
Internally jira has 3 non-modifiable categories: open, in progress, and done. This is the way jira works. Versionone appears to be the same. Your company must of mapped "blocked" to one of those types. The existing feature widget / collectors are modeled around this assumption so adding a fourth category would be a large change.
