### ISSUE TITLE
New and example dashboards only display Topo's Dashboard

### ISSUE THREAD

**Issue by mitchb95** [capitalone/Hygieia#941]
Hi,

Whenever I create a new dashboard or try to view sample dashboards, it always display's Topo's Dashboard, which looks like a team dashboard.

I have mongo running with configured user access, and api and UI are running, too.  I have the jenkins collector running but I am obviously unable to see any meaningful output.

Thanks!

**Comment by satishc1** [comment]
@mitchb95 Did you setup hygieia from scratch or are you using a mongo database provided by someone ? If you are internal to CapitalOne you could also reach out to our internal slack channel.

**Comment by satishc1** [comment]
@mitchb95 closed. Reopen if still an issue.
