### ISSUE TITLE
Drilldown feature for JIRA, Stash, ...

### ISSUE THREAD

**Issue by knagendrak** [capitalone/Hygieia#956]
We have created Hygieia dashboard integrating JIRA, Stash, Jenkins and SONAR.

My rmanagement asked me to provide link to drilldown further to understand more details.

Ex: **JIRA Sprint** -  Links to FEATURES IN PROGRESS

Similarly Want to display X and Y axes titles for **BUILD**

Can anyone let me know is it possible to do it or not.
If it can be done, please provide steps on how to do this?

Advanced thanks.

**Comment by MarkRx** [comment]
@pxk5958 is working on having links for features in progress. It will be in a PR within a few weeks.

**Comment by knagendrak** [comment]
Hi MarkRx, thanks for the update and considering this as valuable feature. In the dashboard we are trying to get more additional information by drilling down into the respective tools (JIRA, Jenkins, Stash..) using links. If possible try to consider this one.

I am not sure it will be good or not to ask you this question, By when we can expect this feature in production (PR), I am asking this question because our budget is getting over in 3-4 weeks and also I want to set the expectations to my mgmt.

Thanks in Advance.

**Comment by MarkRx** [comment]
Hyperlinks are in PR #974

**Comment by knagendrak** [comment]
Hi MarkRx, thanks for considering and incorporating this feature.
I just downloaded the code but the changes were not there. Is it something I am looking different link? can you please provide me the exact link.

**Comment by pxk5958** [comment]
Are you sure you checked out the right code? The PR hasn't been approved and merged into master yet.

**Comment by knagendrak** [comment]
Hi pxk5958, I pulled the code from master, may that is the reason I didn't see the changes. I am eager to see these features. Can you please let me know,from when this will be available in master? Currently in which link these changes are available, so that i will download and chk.

**Comment by MarkRx** [comment]
PR #974 needs to be accepted first. Until then you can build the branch it is based off of: paychex:feature/TAXSDLC-1081

**Comment by knagendrak** [comment]
I ran 'mvn clean install package', but the BUILD is FAIL

[INFO] com.capitalone.dashboard:Hygieia ................... SUCCESS [  2.087 s]
[INFO] com.capitalone.dashboard:core ...................... SUCCESS [01:08 min]
[INFO] com.capitalone.dashboard:api ....................... SUCCESS [ 32.913 s]
[INFO] com.capitalone.dashboard:bamboo-build-collector .... SUCCESS [ 10.260 s]
[INFO] com.capitalone.dashboard:jenkins-build-collector ... SUCCESS [  9.411 s]
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SUCCESS [  5.459 s]
[INFO] com.capitalone.dashboard:sonar-codequality-collector SUCCESS [  1.219 s]
[INFO] com.capitalone.dashboard:aws-cloud-collector ....... SUCCESS [  1.418 s]
[INFO] com.capitalone.dashboard:udeploy-deployment-collector SUCCESS [  6.038 s]
[INFO] com.capitalone.dashboard:xldeploy-deployment-collector SUCCESS [  6.106 s]
[INFO] com.capitalone.dashboard:jira-feature-collector .... SUCCESS [ 20.389 s]
[INFO] com.capitalone.dashboard:versionone-feature-collector SUCCESS [  7.209 s]
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SUCCESS [  1.240 s]
[INFO] com.capitalone.dashboard:bitbucket-scm-collector ... SUCCESS [ 10.446 s]
[INFO] com.capitalone.dashboard:github-scm-collector ...... SUCCESS [  5.638 s]
[INFO] com.capitalone.dashboard:subversion-collector ...... SUCCESS [  0.981 s]
[INFO] com.capitalone.dashboard:gitlab-git-collector ...... SUCCESS [  1.666 s]
[INFO] com.capitalone.dashboard:UI ........................ FAILURE [04:09 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

This is the **error**

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.29:npm (npm install) on project UI: Failed to run task: 'npm install' failed. (error code 1) -> [Help 1]

I am running in Windows 7, JDK 1.8

any help?

**Comment by pxk5958** [comment]
Have you installed NodeJS?

**Comment by knagendrak** [comment]
I have installed MongoDB in my 64 bit Windows 7 system.
After installing Hotfix, I ran "mongod --dbpath command" and it is stopped at "**waiting for connection on port 27017**"

c:\Program Files\MongoDB\Server\3.2\bin>mongod --dbpath c:/data
2016-12-05T10:15:09.928-0500 I CONTROL  [main] Hotfix KB2731284 or later update is installed, no nee
d to zero-out data files
2016-12-05T10:15:09.930-0500 I CONTROL  [initandlisten] MongoDB starting : pid=1556 port=27017 dbpat
h=c:/data 64-bit host=Nagu-PC
2016-12-05T10:15:09.930-0500 I CONTROL  [initandlisten] targetMinOS: Windows 7/Windows Server 2008 R
2
2016-12-05T10:15:09.931-0500 I CONTROL  [initandlisten] db version v3.2.11
2016-12-05T10:15:09.931-0500 I CONTROL  [initandlisten] git version: 009580ad490190ba33d1c6253ebd8d9
1808923e4
2016-12-05T10:15:09.931-0500 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t-fips  3 May
2016
2016-12-05T10:15:09.931-0500 I CONTROL  [initandlisten] allocator: tcmalloc
2016-12-05T10:15:09.931-0500 I CONTROL  [initandlisten] modules: none
2016-12-05T10:15:09.931-0500 I CONTROL  [initandlisten] build environment:
2016-12-05T10:15:09.931-0500 I CONTROL  [initandlisten]     distmod: 2008plus-ssl
2016-12-05T10:15:09.931-0500 I CONTROL  [initandlisten]     distarch: x86_64
2016-12-05T10:15:09.932-0500 I CONTROL  [initandlisten]     target_arch: x86_64
2016-12-05T10:15:09.932-0500 I CONTROL  [initandlisten] options: { storage: { dbPath: "c:/data" } }
2016-12-05T10:15:09.933-0500 I -        [initandlisten] Detected data files in c:/data created by th
e 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2016-12-05T10:15:09.935-0500 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=4G
,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,ar
chive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60
,log_size=2GB),statistics_log=(wait=0),
2016-12-05T10:15:11.422-0500 I NETWORK  [HostnameCanonicalizationWorker] Starting hostname canonical
ization worker
2016-12-05T10:15:11.422-0500 I FTDC     [initandlisten] Initializing full-time diagnostic data captu
re with directory 'c:/data/diagnostic.data'
2016-12-05T10:15:11.513-0500 I NETWORK  [initandlisten] waiting for connections on port 27017

So, after doing some googling, I have **kept that command window in the same state and opened new command window** and ran "**mongo**" command then the previous window, where i ran mongodb --dbpath command was showing "2016-12-05T10:18:14.361-0500 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:1217 #1 (1 connection now open)"

but the issue is,, if i closed the 2nd command window the connection is closing.

any solution for this?

**Comment by pxk5958** [comment]
@knagendrak May I know what you are trying to do exactly? It seems to be behaving as it should. [mongod](https://docs.mongodb.com/manual/reference/program/mongod/) handles the data requests. [mongo](https://docs.mongodb.com/manual/reference/program/mongo/) is a shell interface to MongoDB, so it connects to your mongo database and gets disconnected when you close it as it should.

**Comment by knagendrak** [comment]
Actually i am trying to follow the steps to install this Hygieia dashboard.
as part of it installed MongoDB and then followed next step to API
in API section when I ran "java -jar api.jar --spring.config.location=dashboard.properties" i got the Timeout exception as shown below...

Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server th
at matches PrimaryServerSelector. Client view of cluster state is {type=UNKNOWN, servers=[{address=l
ocalhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSecurityException: Excep
tion authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='dashboarduser', source='dashboa
rddb', password=<hidden>, mechanismProperties={}}}, caused by {com.mongodb.MongoCommandException: Co
mmand failed with error 18: 'Authentication failed.' on server localhost:27017. The full response is
 { "ok" : 0.0, "code" : 18, "errmsg" : "Authentication failed." }}}]

**Comment by pxk5958** [comment]
Check your credentials. Did you create the corresponding username, password on the database? Seems you got that mixed up.

**Comment by knagendrak** [comment]
oh... actually i have used the same credentials what was there in the script... can you please let me know how to check the crendentials

**Comment by knagendrak** [comment]
Following setup.md instructions
under API, created dashboard.properties with the following contents and saved in api/target path
dbname=dashboarddb
dbusername=dashboarduser
dbpassword=ZGJwYXNzd29yZA==
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
server.contextPath=/api
server.port=8080
version.number=@application.version.number@

after this ran "java -jar api.jar --spring.config.location=dashboard.properties"
It thrown **following error** 
Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server th at matches PrimaryServerSelector. Client view of cluster state is {type=UNKNOWN, servers=[{address=l ocalhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSecurityException: Excep tion authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='dashboarduser', source='dashboa rddb', password=<hidden>, mechanismProperties={}}}, caused by {com.mongodb.MongoCommandException: Co mmand failed with error 18: 'Authentication failed.' on server localhost:27017. The full response is { "ok" : 0.0, "code" : 18, "errmsg" : "Authentication failed." }}}]

Anyone can help in this regards...

**Comment by knagendrak** [comment]
In setup.md after executing "Run the API", i tried to run Docker Image

Create -> mvn clean package -pl api docker:build  (trying to run this command from Hygieia-Master path)

[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.10:build (default-cli) on project
 api: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.ja
vax.ws.rs.ProcessingException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:2
375 [localhost/127.0.0.1] failed: Connection refused: connect -> [Help 1]

**Comment by knagendrak** [comment]
@pxk5958, I am still facing issues in setting up this, mean while is it possible to share the screen shot of the Hygieia-JIRA, where it will give Hyperlink for the features it is displaying. So, that at least it will be a confirmation for my mgmt. and not hurry me.

**Comment by pxk5958** [comment]
Run "mvn clean package install docker:build" from the hygieia directory to build all projects' jar files and build docker images.

**Comment by knagendrak** [comment]
is these changes are merged into master? If I download master, will I get all these changes?

Please confirm at the earliest

**Comment by tabladrum** [comment]
Merged in the current master.
