### ISSUE TITLE
User name / password visible in dashboard URL

### ISSUE THREAD

**Issue by bjayagop** [capitalone/Hygieia#967]
User name / password are visible in dashboard URL. This should not appear in query string.

http://localhost:3000/?username=123123&password=123123#/site

Please suggest to resolve.

**Comment by amitmawkin** [comment]
not sure what you are doing.Authentication is a http post call.
Can you paot sone gif recordings of your interactions

**Comment by satishc1** [comment]
@bjayagop @amitmawkin 
I am able to recreate it if starting up the UI with gulp serve.
The default page that pops up is http://localhost:3000/#/
Edit the url as 
http://localhost:3000/?username=youruser&password=yourpass#/
This works fine and redirects to the login page.
Now edit the url as listed in the issue above 
http://localhost:3000/?username=youruser&password=yourpass#/site
Although you can't do much on this page, could add a check in site.js and redirect to login page.

**Comment by mrpudn** [comment]
I'm still unclear as to whether this is an issue - more like a non-standard way to use the dashboard.

Can we close this one?

**Comment by satishc1** [comment]
@nireeshT Please take a look and see if you can resolve this one.

**Comment by mrpudn** [comment]
This doesn't appear to be an issue, so I'm closing it

**Comment by satishc1** [comment]
@nireeshT @mrpudn Please take a look and see if you can resolve this one.

**Comment by satishc1** [comment]
Closed.
