### ISSUE TITLE
Unable for compile api

### ISSUE THREAD

**Issue by Cybertran** [capitalone/Hygieia#968]
Hi there,
This looks great dashboard when i try to compile api code i found few modal classes are missing
eg QCodeQuality,QBuild,QCommit,QScopeOwner,QTestResult etc
guys can any body push this code so that i can compile and run this.

**Comment by satishc1** [comment]
@Cybertran Those are generated files. What environment are you building this on ? mvn install should work.

**Comment by satishc1** [comment]
@Cybertran Follow the instructions in http://www.capitalone.io/Hygieia/api.html to build the api module.
