### ISSUE TITLE
Encrypted Properties

### ISSUE THREAD

**Issue by Mpluya** [capitalone/Hygieia#969]
Our organization has a requirement to not store credentials (i.e. database credentials) in plaintext on the property files.
I noticed the codebase already has support for encrypt/decrypt by using the Encryption class on the core project.
The only downside in my opinion is I now have to add code to call the encryption class. It would be nice if my encypted properties are served up automatically decrypted.
That said, I found jasypt-spring-boot (Jasypt integration for Spring boot). It boot straps a Spring post processor which makes the app aware of the encrypted properties. Details about jasypt-spring-boot is here https://github.com/ulisesbocchio/jasypt-spring-boot.

My question is, would there be any interest in incorporating this in Hygieia?

**Comment by tabladrum** [comment]
@Mpluya Thanks for the link. Definitely interested.

**Comment by Mpluya** [comment]
@tabladrum cool. Thank you. I'll submit a PR early next week at the latest.

**Comment by satishc1** [comment]
Closed.
