### ISSUE TITLE
Not able to get API layer running with Gradle builds

### ISSUE THREAD

**Issue by amitmawkin** [capitalone/Hygieia#97]
Gradle was introduced by committers of Hygieia , but it was later found that API layer was not running correctly in IDE's like Eclipse , we need more time fixing it,
 Gradle has been pulled out for now and maven based build pom's are put back.

The issue is open to get Gradle based build working. A seperate branch <code> gradle </code> has been created for this purpose

**Comment by dstine** [comment]
@amitmawkin Which branch are you referring to? I see both `gradle` and `gradle-fix` branches.

**Comment by jdamick** [comment]
gradle, i need to remove the other one

**Comment by amitmawkin** [comment]
updated the description as well as removed the branch

**Comment by jdamick** [comment]
Some of this lack of documentation on how to correctly debug & run from the cmd line. 

See this commit (it should have resolved those issues):
https://github.com/capitalone/Hygieia/commit/d0fe4562f38bff450905b26b5642bb519f365dd3

**Comment by bodiam** [comment]
But what's the issue now? I had the complete build running, also in IntelliJ, and we converted the API to Spring Boot. What were the concrete issues you were running into? 

(btw, I didn't check Eclipse, and I'm also not planning to spend time on Eclipse)

**Comment by tabladrum** [comment]
It looks like we have a solution now. With command line fix that @jdamick has, we should be fine. Will have another try at switching to gradle. @bodiam can you do a PR for the API Spring Boot? Thanks

**Comment by bodiam** [comment]
Sure, can do, but you first need to switch to Gradle for that, after that I will do a pull request.

**Comment by tabladrum** [comment]
Target next week after we do a few pending PRs. Will keep you posted.

**Comment by bodiam** [comment]
I did a sync with the upstream, and now all the Gradle things are gone. However, I cannot run the UI anymore. I used to do it with Gradle, but maven fails, and so does `gulp serve` when I login:

````
[BS] Watching files...
_http_outgoing.js:335
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.writeHead (_http_server.js:195:21)
    at ProxyServer.<anonymous> (/Users/erikp/Userfiles/Klanten/Rabobank/Projects/cqc-dashboard/UI/gulp/proxy.js:32:7)
    at ProxyServer.emit (/Users/erikp/Userfiles/Klanten/Rabobank/Projects/cqc-dashboard/UI/node_modules/http-proxy/node_modules/eventemitter3/index.js:100:27)
    at ClientRequest.proxyError (/Users/erikp/Userfiles/Klanten/Rabobank/Projects/cqc-dashboard/UI/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:139:16)
    at ClientRequest.emit (events.js:129:20)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)
`````

Suggestions?

**Comment by tabladrum** [comment]
@bodiam Can we close this?

**Comment by tabladrum** [comment]
This is actually fixed.

**Comment by bodiam** [comment]
No, it's not fixed.
