### ISSUE TITLE
How to collect data for customized Deployment collector

### ISSUE THREAD

**Issue by Mahendra1260** [capitalone/Hygieia#975]
@tabladrum 
We are having many data centers server where our application is getting deployed using some customized bash scripts. My requirement is to display the data on the Hygieia Dashboard about the the deployment statistics.
As per documentation, deploy collector has on udeploy and XLDeploy. Can you please provide me a pointer to some documentation or way to achieve my requirement?

**Comment by tabladrum** [comment]
Try to do this:
``
curl -v -H "Accept: application/json" -H "Content-Type:application/json" -X POST -d '{"executionId":"12345","jobUrl":"another-url","appName":"Hygieia","envName":"DEV","artifactName":"core.jar","artifactVersion":"0.3.1-SNAPSHOT","jobName":"MyJob","instanceUrl":"someurl","deployStatus":"SUCCESS","startTime":1461281534380,"artifactGroup":"com.capitalone.dashboard","endTime":0,"duration":0,"startedBy":"Jenkins"}' http://localhost:8080/api/deploy/
``

**Comment by Mahendra1260** [comment]
Where do I need to update the command and how do I get these variables automatically?

**Comment by Mahendra1260** [comment]
where to run the curl command?

**Comment by tabladrum** [comment]
You can run this from shell script. If you notice, most of the variables will be static for your deployment job including the artifact name etc. if not you need to get those using other shell commands.

**Comment by Mahendra1260** [comment]
Here are my understanding. Please correct me if I am wrong any where.
1.executionId : Id of Deployment Jenkins Job
2.jobUrl: Jenkins job url for the Deployment Job
3.appName: would be my applicatoin name
4.artifactName: my application jar/war file 
5.artifactVersion: war file version name
6.jobName: Jenkins Deployment job name
7.instanceUrl: url of the application???
8.startTime: Jenkins Deployment Job Start time
9.artifactGroup: my application artifactgroup Id

Please correct if I am having any wrong understanding

**Comment by tabladrum** [comment]
Pretty much. If it is not Jenkins, then:

1.executionId : Id of Deployment Job - some sequence number.
2.jobUrl: url for the Deployment Job
3.appName: would be my applicatoin name
4.artifactName: my application jar/war file
5.artifactVersion: war file version name
6.jobName: Deployment job name
7.instanceUrl: url of the application???
8.startTime: Deployment Job Start time
9.artifactGroup: my application artifactgroup Id

**Comment by Mahendra1260** [comment]
Thanks. We are having the Jenkins for such deployment. So in that case I can fetch all the variable via Jenkins or via some shell command..
One last question on this, do I need to run this curl command only on the Hygieia installed server or I can run on any server?

**Comment by tabladrum** [comment]
If you are using Jenkins for deployments, then we can use the Hygieia Jenkins plugin https://github.com/capitalone/Hygieia/tree/master/hygieia-jenkins-plugin.

In any case, you can run the curl command from the "server" that runs the deployment job. In your case, it's Jenkins. 

So, you have two options:
1. Use the jenkins plugin
2. Use the curl in Jenkins job's shell command window.

**Comment by Mahendra1260** [comment]
Ok. . I will explore both the options

Thanks for the detailed info.

**Comment by Mahendra1260** [comment]
thanks, I am closing the issue and you have resolved all my queries perfectly.
