### ISSUE TITLE
Build broken in Jenkins plugin with java7 due core dependency

### ISSUE THREAD

**Issue by mqglobant** [capitalone/Hygieia#979]
Hi! 

I need to generate the Jenkins plugin and the plugin should be compiled with the same version of Java that Jenkins is using, in my case java7, but the plugin depends of the “core” project of Hygieia and it uses some features that are only present in Java 8 ( Lamda functions ).
So, there is a way to compile or generate jenkins plugin to run in java7 or just it won't work? 

Thank you!

**Comment by MarkRx** [comment]
Hygieia requires java 8. You could always run jenkins with a java 8 runtime and see if it functions properly.

Technically you could make a java 7 build by removing the CommitEventListener class as it seems to be the only item in core that requires java 8 features. No guarantees it will work as dependent libraries may require java 8 as well.

**Comment by mqglobant** [comment]
Right now upgrade Jenkins to run in Java8 is not an option, it has a lot of plugins and there is a lot of people using it , so we can't risk to let Jenkins broken while we test ... I'll try to test in some other instance of Jenkins but it'll requiere a license (It's the cloudbee version) ...
Thanks anyway for your time :)

Regards,
