### ISSUE TITLE
Jenkins deploy collector

### ISSUE THREAD

**Issue by szabbas** [capitalone/Hygieia#981]
Is there any collector to collect data from jenkins auto deploy data. We are using Jenkins for deployment in various stages. We need to collect data and display it in the Deploy widget and Product dashboard view.

**Comment by MarkRx** [comment]
There is not. At present the only way to do this using jenkins is to use a push model and call rest API endpoints to put in deployment data. The jenkins plugin has some functionality to do this. You can also use curl POST calls.

**Comment by tabladrum** [comment]
Jenkins being a generic job scheduler, it is difficult to know what the jobs are doing. No way to distinguish between a Jenkins job doing just the build vs say creating a full stack and deploying app. There may be some work arounds (which are not clean) such as having the job names follow certain naming convention etc. Thoughts?

**Comment by jimzucker** [comment]
@tabladrum One 'right way' to consider would be to create a Hygieia jenkins plugin that the client adds to thier build as a step, in that plugin we can signal/do whatever we want/need.

**Comment by tabladrum** [comment]
The plugin is already there. We use it.

**Comment by satishc1** [comment]
@szabbas Use the hygieia jenkins plugin.
