### ISSUE TITLE
Artifactory collector not working

### ISSUE THREAD

**Issue by vetrivelan25** [capitalone/Hygieia#982]
I'm trying to connect Nexus repository for that JVM is build successfully but it's failed to fetch.I have attached the issue in the below screen shots.I dono why that /api/repositories is added at the end of the url  

![artifacotycollectormessage](https://cloud.githubusercontent.com/assets/23630163/20662505/a8a8d5ee-b579-11e6-892e-16d5642cde2b.png)

nexus.properties:
![nexus properties](https://cloud.githubusercontent.com/assets/23630163/20662627/30f31ab8-b57a-11e6-9770-5a8af8012f76.png)

**Comment by MarkRx** [comment]
By nexus repository do you mean an artifactory repository named 'nexus' or Nexus the product? https://www.sonatype.com/nexus-repository-sonatype

@pxk5958 could you check the config

**Comment by MarkRx** [comment]
What version of artifactory? 

try removing components/ from the end of the server url. If you need to tweak the rest endpoint maybe do it with the artifactory.endpoint property. By default it is 'artifactory/'

**Comment by vetrivelan25** [comment]
i tried your suggestions as you mentioned above but sill /api /repositories is added at the end of artifactory url. Getting the same issue.

**Comment by MarkRx** [comment]
The proper rest endpoint for obtaining the list of repositories is defined here: https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-GetRepositories

> GET /api/repositories[?type=repositoryType (local|remote|virtual)]

In order to work properly you must be configured such that the URL results in the following:
> http://myurl:8383/api/repositories

Your screenshot has an additional "components" portion in the URL which is incorrect.

```
artifactory.servers[0]=http:/myurl:8383/
artifactory.endpoint=artifactory/
```

**Comment by vetrivelan25** [comment]
I have installed nexus on http:/myurl:8383/components/   url only if i removed /components in the url it won't work. if i browse the url like  http:/myurl:8383/components/ then only it will work.

**Comment by vetrivelan25** [comment]
Thanks for your suggestions After i changed the url structure as you mentioned above still i'm facing the same issue
Actually i have installed sonatype nexus artifactory on that url. I try to connect nexus with Hygieia.

![nexus prop](https://cloud.githubusercontent.com/assets/23630163/20753220/52d88f3e-b72b-11e6-952f-970379e98cc4.png)
![error prop](https://cloud.githubusercontent.com/assets/23630163/20753228/583b4f02-b72b-11e6-9928-3c1ac3f303f0.png)

**Comment by MarkRx** [comment]
The collector was created for JFrog artifactory (https://www.jfrog.com/artifactory/). It does not support Nexus. There is currently no collector support for Nexus.

**Comment by Mahendra1260** [comment]
@MarkRx I am able to run jFrog Artifacory collector. how do I see the data on the Dashboard? Which Widget i should configure to see the artifactory collector data?

**Comment by MarkRx** [comment]
@Mahendra1260 at this time there is no UI widget to display the data. It is used by the pipeline collector to correlate deployments to artifacts to builds/commits.

**Comment by Mahendra1260** [comment]
@MarkRx Thanks Mark for the update. Hoping to see the widget for artifactory soon.
At this moment, is there a way I can make use of the data collected by artifactory collector?

**Comment by Mahendra1260** [comment]
Thanks @MarkRx 
Well, I am deploying my application using bash scripts. so if my bash script deployed artifacts matches with the one in artifactory collector, will it be display on pipeline OR it will only work with udeploy/xldeploy?

**Comment by MarkRx** [comment]
It should work. There is an event listener that listens to when environment_component's are saved. The api has a rest call to save those.

**Comment by vetrivelan25** [comment]
Ok..thanks

**Comment by nireeshT** [comment]
@vetrivelan25  - Reopen if issue is not resolved.
