### ISSUE TITLE
Renaming Dashboard: Do not reload if renaming is exited

### ISSUE THREAD

**Issue by tabladrum** [capitalone/Hygieia#984]
If I click the 'X' on the window, the dashboard is reloaded. Should not be.

![image](https://cloud.githubusercontent.com/assets/6014941/20680314/8512ad88-b56c-11e6-9bec-e879b8e288b1.png)

**Comment by satishc1** [comment]
@nireeshT Please see if you can resolve this one.

**Comment by satishc1** [comment]
Closed.
