### ISSUE TITLE
Creating Custom Collectors (Skeleton project)

### ISSUE THREAD

**Issue by coreymeadln** [capitalone/Hygieia#985]
I am following the guide at the link below to learn more about creating collectors and how they work.  The guide references a "sample collector project" in the Copy Skeleton Collector Project section, but I do not see the sample project anywhere in the repository.  Perhaps I'm just missing something, in which case please let me know where I can find that.  Otherwise, I'd love for that to be added so we have a place to start instead of scrapping everything from an existing collector.

https://github.com/capitalone/Hygieia/blob/master/core/create_collector.md

**Comment by elangesk** [comment]
@coreymeadln 
    Good sharing... I am working on Rally integration with Hygieia. But not much reference to rally integrate with hygieia. I did already long back as you provided in the read me.

Now I am in stage to store populated data from Rally system in to mongodb. Could you please provide reference code that populated data get save with  MongoDB in your case.

Thanks in advance..

**Comment by coreymeadln** [comment]
I've just started exploring a custom collector, so I haven't yet gotten that far to actually save data into the DB.

Briefly looking at the code, it looks like there's a save method on the Job Repositories.  For instance, in HudsonCollectorTask, hudsonJobRepository.save(existing).  I imagine you can use that to figure out how to save what you need.

**Comment by coreymeadln** [comment]
Anyone know anything on the skeleton project?  I'd love to know where it is or if it just hasn't been added yet.

Thanks!

**Comment by amitmawkin** [comment]
There is no skeleton project as such, you can pick any of the existing collector , i would say pick Github collector and modify it for your need.

**Comment by coreymeadln** [comment]
Ok great - thanks for the response.  I would maybe suggest changing the wording on the create_collector guide since it's a little misleading.  Using the Github works with me!

Thanks!

**Comment by monabhardwaj** [comment]
Hello! I'm new to Hygieia and currently attempting to create a custom github collector. I have gone through various articles on the same but weren't of much help on the beginner level. It would be invaluable for me if could extend any advice or sample projects on how you got your custom collector working. @coreymeadln 
Thank You!
