### ISSUE TITLE
Deployment Pipeline Configurability

### ISSUE THREAD

**Issue by MarkRx** [capitalone/Hygieia#989]
Currently the Hygieia pipeline is hard coded to use at most 5 stages in the order of DEV > QA > INT > PERF > PROD. We have found that this approach does not satisfy all pipelines. 

I propose the following enhancements:

- (A) Custom stage names with a configurable number of system level stages. Some teams may use more than one level of integration environments. So the pipeline would become DEV > QA > INT1 > INT2 > PERF > PROD
- ~~(B) Configurable order of stages - Some teams use different staging orders. For example PERF testing might come at different locations in the pipeline.~~ System stage groups should be generic enough to work for all teams. I think keeping order consistent will simplify aggregation and metrics a bunch.
- (C) Multiple environments per stage - There may be parallel environments within a stage. For example, suppose there are 3 independent QA environments - qa1, qa2, and qa3. Components may go to any QA in any order. They must go to at least one QA before moving to a higher environment.

(A) is simply a matter of refactoring and adding functionality. (B) and (C) add flexibility at the cost of complexity.

Each team dashboard would be able to define which system level stages to use ~~along with the order that they are used in their pipeline~~. Grouping would also be definable so that N number of environments may be part of the same stage. The UI would have to be updated to display this information.

Product dashboards would have to change to take into account multiple environments per stage. In the case of a team having multiple environments per a stage the earliest date a PipelineCommit is seen in any of the environments in the stage would be used for calculations. 

## Examples
Given a system stage config of DEV, QA, INT1, INT2, PERF, PROD:

| Pipeline | DEV | QA            | INT1 | INT2 | PERF | PROD |
|----------|------|------------|-------|------|-------|--------|
| APP A   | dev1 | qa1 | int-a  | int-main | p1 | prod |
| APP B   | dev1 | qa1 / qa2 | int-a  | int-main | p2 | prod |
| APP C   |         | qa1 |   | int-main | p2 | prod |

Observe that App B has multiple parallel environments defined for the 'QA' stage.

**Comment by MarkRx** [comment]
Updated. After several discussions I decided to scratch (B) due to potential complexities it could add. It will be up to the system admin to define the stages in a generic way so that it fits for all teams.

**Comment by MarkRx** [comment]
Phase I custom stage names in PR #1020

**Comment by nireeshT** [comment]
PR https://github.com/capitalone/Hygieia/pull/1020 merged
