### ISSUE TITLE
Question How I can "clean" data ?

### ISSUE THREAD

**Issue by juantoledo** [capitalone/Hygieia#995]
How I can "clean" data ? I mean, clean Jira docs from Mongo, is there an API endpoint to do that ?

**Comment by pxk5958** [comment]
Have to do it manually on the MongoDB. Won't it be a security risk if there is an api endpoint to delete data? Unless it is restricted to admin of course.

**Comment by satishc1** [comment]
@juantoledo You should be able to just drop the feature and scope collections from mongodb and then re-run the jira collector to refetch the data.

Offcourse, make a backup of your mongodb before manipulating collections.

**Comment by satishc1** [comment]
@juantoledo Closed.
