### ISSUE TITLE
Jenkins-collector issue Regarding SSLHandshake Exception

### ISSUE THREAD

**Issue by prvnsinghal** [capitalone/Hygieia#998]
Hi There,
     when I am trying to run "jenkins-build-collector-2.0.4-SNAPSHOT.jar" file then it is showing some errors related to some SSL certification, while I have imported all the Self signed certificate.
please have a look into the attached screenshot and guide that how can we resolve it
Thankyou
![error](https://cloud.githubusercontent.com/assets/20596360/20793606/d68e349c-b7ed-11e6-920f-ad4929fa937c.PNG)

**Comment by MarkRx** [comment]
Try importing it into javas cert store

To debug certs:

> -Djavax.net.debug=all

http://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/ReadDebug.html

**Comment by prvnsinghal** [comment]
I installed all the each and every certificate of http://jenkins.company.com/ in the Hygieia server by using "keytool -import -trustcacerts -noprompt -storepass changeit -alias $REMHOST -file $REMHOST.pem" 
but still it is showing ssl exception error.

**Comment by satishc1** [comment]
@prvnsinghal Try launching your jenkins collector specifying the location of your truststore. -Djavax.net.ssl.trustStore=

**Comment by satishc1** [comment]
@prvnsinghal If above suggestion doesn't resolve the issue, please re-open.
